### ISSUE TITLE
Error building on Windows 10 problem

### ISSUE THREAD

**Issue by SumTse** [Autodesk/maya-usd#1014]
**Describe the issue**
I am attempting to build this plugin on windows. Following the instructions on the build page, I have cloned the repo and on attempting to run the build.py file, it errors with the following.
[build_log.txt](https://github.com/Autodesk/maya-usd/files/5709194/build_log.txt)
[build_log.txt](https://github.com/Autodesk/maya-usd/files/5709195/build_log.txt)

D:\usd\git\maya-usd>py -2.7 build.py --maya-location "C:/Program Files/Autodesk/Maya2020" --pxrusd-location "D:/usd/build/USD" --devkit-location "C:/Users/fatface/devkitBase" "D:/usd/build/USD_maya"

    Building with settings:
      Source directory          D:\usd\git\maya-usd
      Workspace directory       D:\usd\build\USD_maya
      Build directory           D:\usd\build\USD_maya\build\RelWithDebInfo
      Install directory         D:\usd\build\USD_maya\install\RelWithDebInfo
      Variant                   RelWithDebInfo
      Python Debug              Off
      CMake generator           Default
      Build Log                 D:\usd\build\USD_maya\build\RelWithDebInfo\build_log.txt
      Stages arguments          ['clean', 'configure', 'build', 'install']
Traceback (most recent call last):
  File "build.py", line 602, in <module>
    BuildAndInstall(context, context.buildArgs, context.stagesArgs)
  File "build.py", line 371, in BuildAndInstall
    RunCMake(context, extraArgs, stagesArgs)
  File "build.py", line 277, in RunCMake
    extraArgs=(" ".join(extraArgs) if extraArgs else "")))
  File "build.py", line 143, in Run
    stderr=subprocess.STDOUT)
  File "C:\Python27\lib\subprocess.py", line 394, in __init__
    errread, errwrite)
  File "C:\Python27\lib\subprocess.py", line 644, in _execute_child
    startupinfo)
WindowsError: [Error 2] The system cannot find the file specified

**Build log**
Please attach a build_log.txt

**Specs:**
 - Windows 10
 - VS 2019
 - Maya 2020.1
 - Maya USD commit SHA dev bf4ea92
 - Pixar USD commit SHA download from https://github.com/PixarAnimationStudios/USD release d8a405a
 
**Additional context**
i want to on --build-debug by i type --build-debug=True will return error 
build.py: error: argument --build-debug: ignored explicit argument 'True'

**Comment by seando-adsk** [comment]
The error you show above is from python. What version of python are you using to call build.py?

For your second comment you just need to use **--build-debug** (do not add =True).

**Comment by dgovil** [comment]
Do you have cmake available in the same command line environment that you're calling Python in?

**Comment by SumTse** [comment]
hi seando,
I use python 2.7.15, I install PySide and pyopenGL site-packages.
hi dgobil,
Sorry, I a very new user of cmake, how to check cmake available in the same command-line environment?

**Comment by seando-adsk** [comment]
In the command prompt where you are running build.py from what does "cmake --version" return? Maya-usd supports versions 3.13 to 3.17.

Something else I noticed above is you are using VS2019. That VS version is not supported by us yet. Please have a look at the table at [Tools and system prerequisites](https://github.com/Autodesk/maya-usd/blob/dev/doc/build.md#1-tools-and-system-prerequisites) for the supported VS version depending on what Maya version you are using.

**Comment by SumTse** [comment]
seando,
i install to VS2017 and cmake version is 3.18.4. build again but stil error

**Build log**
D:\usd_file\git\maya-usd>py -2.7 build.py --maya-location "C:\Program Files\Autodesk\Maya2018" --pxrusd-location "D:\usd_file\build_USD" --devkit-location "C:\Users\sum tse\devkitBase" --build-debug --debug-python "D:\usd_file\build_maya_usd"

    Building with settings:
      Source directory          D:\usd_file\git\maya-usd
      Workspace directory       D:\usd_file\build_maya_usd
      Build directory           D:\usd_file\build_maya_usd\build\Debug
      Install directory         D:\usd_file\build_maya_usd\install\Debug
      Variant                   Debug
      Python Debug              On
      CMake generator           Default
      Build Log                 D:\usd_file\build_maya_usd\build\Debug\build_log.txt
      Stages arguments          ['clean', 'configure', 'build', 'install']
#####################################################################################
log date: 2020-12-18 23:05
commit sha: 1c51229b6830ed47a051319961a98ae36e7d02bc
commit date: Thu Dec 17 08:47:33 2020 -0500
#####################################################################################

cmake -DCMAKE_INSTALL_PREFIX="D:\usd_file\build_maya_usd\install\Debug" -DCMAKE_BUILD_TYPE=Debug -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -G "Visual Studio 14 2015 Win64" -DMAYA_LOCATION="C:\Program Files\Autodesk\Maya2018" -DPXR_USD_LOCATION="D:\usd_file\build_USD" -DMAYA_DEVKIT_LOCATION="C:\Users\sum tse\devkitBase" -DMAYAUSD_DEFINE_BOOST_DEBUG_PYTHON_FLAG=ON "D:\usd_file\git\maya-usd"
-- Selecting Windows SDK version  to target Windows 10.0.18363.
CMake Error at CMakeLists.txt:18 (project):
  Failed to run MSBuild command:

    MSBuild.exe

  to get the value of VCTargetsPath:

    The system cannot find the file specified



-- Configuring incomplete, errors occurred!
See also "D:/usd_file/build_maya_usd/build/Debug/CMakeFiles/CMakeOutput.log".

Traceback (most recent call last):
  File "build.py", line 602, in <module>
    BuildAndInstall(context, context.buildArgs, context.stagesArgs)
  File "build.py", line 371, in BuildAndInstall
    RunCMake(context, extraArgs, stagesArgs)
  File "build.py", line 277, in RunCMake
    extraArgs=(" ".join(extraArgs) if extraArgs else "")))
  File "build.py", line 165, in Run
    .format(cmd=cmd, log=os.path.abspath(context.logFileLocation)))
RuntimeError: Failed to run 'cmake -DCMAKE_INSTALL_PREFIX="D:\usd_file\build_maya_usd\install\Debug" -DCMAKE_BUILD_TYPE=Debug -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -G "Visual Studio 14 2015 Win64" -DMAYA_LOCATION="C:\Program Files\Autodesk\Maya2018" -DPXR_USD_LOCATION="D:\usd_file\build_USD" -DMAYA_DEVKIT_LOCATION="C:\Users\sum tse\devkitBase" -DMAYAUSD_DEFINE_BOOST_DEBUG_PYTHON_FLAG=ON "D:\usd_file\git\maya-usd"'
See D:\usd_file\build_maya_usd\build\Debug\build_log.txt for more details.

**Additional context**
i check the MSBuild.exe have install to VS2017. 
i build to Maya version 2018
cmake (3.18.4.post1)
Jinja2 (2.11.2)
MarkupSafe (1.1.1)
pip (9.0.3)
PyOpenGL (3.1.5)
PySide (1.2.4)
PyYAML (5.3.1)
setuptools (39.0.1)

**Comment by seando-adsk** [comment]
Are you using a "Developer Command Prompt"? You can open that from the start menu or from any command prompt by executing "C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Auxiliary\Build\vcvars64.bat"

**Comment by SumTse** [comment]
@seando-adsk i forget using a "x64 Native Tools Command Prompt"! But i change still have other error

**Build log**
**********************************************************************
** Visual Studio 2017 Developer Command Prompt v15.9.30
** Copyright (c) 2017 Microsoft Corporation
**********************************************************************
[vcvarsall.bat] Environment initialized for: 'x64'

C:\Windows\System32>D:

D:\>cd usd_file\git\maya-usd

D:\usd_file\git\maya-usd>py -2.7 build.py --maya-location "C:\Program Files\Autodesk\Maya2018" --pxrusd-location "D:\usd_file\build_USD" --devkit-location "C:\Users\sum tse\devkitBase" --build-debug --debug-python "D:\usd_file\build_maya_usd"

    Building with settings:
      Source directory          D:\usd_file\git\maya-usd
      Workspace directory       D:\usd_file\build_maya_usd
      Build directory           D:\usd_file\build_maya_usd\build\Debug
      Install directory         D:\usd_file\build_maya_usd\install\Debug
      Variant                   Debug
      Python Debug              On
      CMake generator           Default
      Build Log                 D:\usd_file\build_maya_usd\build\Debug\build_log.txt
      Stages arguments          ['clean', 'configure', 'build', 'install']
#####################################################################################
log date: 2020-12-19 00:37
commit sha: 1c51229b6830ed47a051319961a98ae36e7d02bc
commit date: Thu Dec 17 08:47:33 2020 -0500
#####################################################################################

cmake -DCMAKE_INSTALL_PREFIX="D:\usd_file\build_maya_usd\install\Debug" -DCMAKE_BUILD_TYPE=Debug -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -G "Visual Studio 15 2017 Win64" -DMAYA_LOCATION="C:\Program Files\Autodesk\Maya2018" -DPXR_USD_LOCATION="D:\usd_file\build_USD" -DMAYA_DEVKIT_LOCATION="C:\Users\sum tse\devkitBase" -DMAYAUSD_DEFINE_BOOST_DEBUG_PYTHON_FLAG=ON "D:\usd_file\git\maya-usd"
-- Selecting Windows SDK version 10.0.17763.0 to target Windows 10.0.18363.
-- The C compiler identification is MSVC 19.16.27045.0
-- The CXX compiler identification is MSVC 19.16.27045.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x64/cl.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x64/cl.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found Python: C:/Python27/python.exe (found suitable exact version "2.7.15") found components: Interpreter
-- _PYTHON_VERSION_LIST: 2.7.15.final.0
-- PYTHON_PREFIX: C:\Python27
-- PYTHON_INCLUDE_DIR: C:\Python27\include
-- PYTHON_SITE_PACKAGES: C:\Python27\Lib\site-packages
-- PYTHON_MODULE_EXTENSION: .pyd
-- PYTHON_IS_DEBUG: 0
-- PYTHON_SIZEOF_VOID_P: 8
-- PYTHON_LIBRARY_SUFFIX: 27
-- PYTHON_LIBDIR:
-- PYTHON_MULTIARCH:
-- Found PythonLibs: C:/Python27/libs/Python27.lib
-- Build MayaUSD with Python3 = OFF
--    PYTHON_INCLUDE_DIRS = C:/Python27/include
--    PYTHON_LIBRARIES    = C:/Python27/libs/Python27.lib
--    Python_EXECUTABLE   = C:/Python27/python.exe
-- Found Maya: C:/Program Files/Autodesk/Maya2018/bin/maya.exe (found suitable version "2018", minimum required is "2018")
-- USD include dir: D:/usd_file/build/USD_20_11/include
-- USD library dir: D:/usd_file/build/USD_20_11/lib
-- USD version: 0.20.11
-- Found USD: D:\usd_file\build_USD (found version "0.20.11")
Updated PYTHONPATH: D:\usd_file\build\USD_20_11\lib\python;D:\usd_file\build_USD\lib\python
Updated PATH: C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\bin\HostX64\x64;C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCPackages;C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\CommonExtensions\Microsoft\TestWindow;C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer;C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\bin\Roslyn;C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Team Tools\Performance Tools\x64;C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Team Tools\Performance Tools;C:\Program Files (x86)\Microsoft Visual Studio\Shared\Common\VSPerfCollectionTools\\x64;C:\Program Files (x86)\Microsoft Visual Studio\Shared\Common\VSPerfCollectionTools\;C:\Program Files (x86)\HTML Help Workshop;C:\Program Files (x86)\Windows Kits\10\bin\10.0.17763.0\x64;C:\Program Files (x86)\Windows Kits\10\bin\x64;C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\\MSBuild\15.0\bin;C:\WINDOWS\Microsoft.NET\Framework64\v4.0.30319;C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\;C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\Tools\;C:\Program Files\ImageMagick-7.0.10-Q16-HDRI;C:\Program Files (x86)\Intel\iCLS Client\;C:\ProgramData\Oracle\Java\javapath;C:\Program Files (x86)\Common Files\Intel\Shared Libraries\redist\intel64\compiler;C:\Program Files\Intel\iCLS Client\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;C:\Program Files (x86)\QuickTime\QTSystem\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\Git\cmd;C:\Python27;C:\Python27\Scripts;D:\usd_file\build\USD_20_11\bin;D:\usd_file\build\USD_20_11\lib;C:\Program Files\dotnet\;C:\Users\sum tse\AppData\Local\Microsoft\WindowsApps;C:\Users\sum tse\AppData\Local\GitHubDesktop\bin;C:\Users\sum tse\.dotnet\tools;C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin;C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\Ninja;D:\usd_file\build_USD\bin;D:\usd_file\build_USD\lib
CMake Warning (dev) at CMakeLists.txt:102 (message):

  =========================================================================================
  UFE is not available in Maya.  Maya2019 and later are supported only.
  =========================================================================================
This warning is for project developers.  Use -Wno-dev to suppress it.

-- QT_LOCATION not set. Building Qt features will be disabled.
-- ========== Installing GoogleTest... ==========
-- Selecting Windows SDK version 10.0.17763.0 to target Windows 10.0.18363.
-- Configuring done
-- Generating done
-- Build files have been written to: D:/usd_file/build_maya_usd/build/Debug/googletest-config
Microsoft (R) Build Engine version 15.9.21+g9802d43bc3 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

  Checking Build System
  Creating directories for 'googletest'
  Building Custom Rule D:/usd_file/build_maya_usd/build/Debug/googletest-config/CMakeLists.txt
  Performing download step (git clone) for 'googletest'
  Cloning into 'googletest-src'...
  HEAD is now at 703bd9ca Googletest export
  Performing update step for 'googletest'
  No patch step for 'googletest'
  Performing configure step for 'googletest'
  -- Selecting Windows SDK version 10.0.17763.0 to target Windows 10.0.18363.
  -- The C compiler identification is MSVC 19.16.27045.0
  -- The CXX compiler identification is MSVC 19.16.27045.0
  -- Detecting C compiler ABI info
  -- Detecting C compiler ABI info - done
  -- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x64/cl.exe - skipped
  -- Detecting C compile features
  -- Detecting C compile features - done
  -- Detecting CXX compiler ABI info
  -- Detecting CXX compiler ABI info - done
  -- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x64/cl.exe - skipped
  -- Detecting CXX compile features
  -- Detecting CXX compile features - done
  -- Found PythonInterp: C:/Python27/python.exe (found version "2.7.15")
  -- Looking for pthread.h
  -- Looking for pthread.h - not found
  -- Found Threads: TRUE
  -- Configuring done
  -- Generating done
CUSTOMBUILD : CMake warning :  [D:\usd_file\build_maya_usd\build\Debug\googletest-config\googletest.vcxproj]
  -- Build files have been written to: D:/usd_file/build_maya_usd/build/Debug/googletest-build
    Manually-specified variables were not used by the project:

      CMAKE_BUILD_TYPE


  Performing build step for 'googletest'
  Microsoft (R) Build Engine version 15.9.21+g9802d43bc3 for .NET Framework
  Copyright (C) Microsoft Corporation. All rights reserved.

    Checking Build System
    Building Custom Rule D:/usd_file/build_maya_usd/build/Debug/googletest-src/googlemock/CMakeLists.txt
    gtest-all.cc
    gmock-all.cc
    Generating Code...
       Creating library D:/usd_file/build_maya_usd/build/Debug/googletest-build/lib/Debug/gmockd.lib and object D:/usd_file/build_maya_usd/build/Debug/googletest-build/lib/Debug/gmockd.exp
    gmock.vcxproj -> D:\usd_file\build_maya_usd\build\Debug\googletest-build\bin\Debug\gmockd.dll
    Building Custom Rule D:/usd_file/build_maya_usd/build/Debug/googletest-src/googlemock/CMakeLists.txt
    gtest-all.cc
    gmock-all.cc
    gmock_main.cc
    Generating Code...
       Creating library D:/usd_file/build_maya_usd/build/Debug/googletest-build/lib/Debug/gmock_maind.lib and object D:/usd_file/build_maya_usd/build/Debug/googletest-build/lib/Debug/gmock_maind.exp
    gmock_main.vcxproj -> D:\usd_file\build_maya_usd\build\Debug\googletest-build\bin\Debug\gmock_maind.dll
    Building Custom Rule D:/usd_file/build_maya_usd/build/Debug/googletest-src/googletest/CMakeLists.txt
    gtest-all.cc
       Creating library D:/usd_file/build_maya_usd/build/Debug/googletest-build/lib/Debug/gtestd.lib and object D:/usd_file/build_maya_usd/build/Debug/googletest-build/lib/Debug/gtestd.exp
    gtest.vcxproj -> D:\usd_file\build_maya_usd\build\Debug\googletest-build\bin\Debug\gtestd.dll
    Building Custom Rule D:/usd_file/build_maya_usd/build/Debug/googletest-src/googletest/CMakeLists.txt
    gtest_main.cc
       Creating library D:/usd_file/build_maya_usd/build/Debug/googletest-build/lib/Debug/gtest_maind.lib and object D:/usd_file/build_maya_usd/build/Debug/googletest-build/lib/Debug/gtest_maind.exp
    gtest_main.vcxproj -> D:\usd_file\build_maya_usd\build\Debug\googletest-build\bin\Debug\gtest_maind.dll
    Building Custom Rule D:/usd_file/build_maya_usd/build/Debug/googletest-src/CMakeLists.txt
  Performing install step for 'googletest'
  Microsoft (R) Build Engine version 15.9.21+g9802d43bc3 for .NET Framework
  Copyright (C) Microsoft Corporation. All rights reserved.

    gmock.vcxproj -> D:\usd_file\build_maya_usd\build\Debug\googletest-build\bin\Debug\gmockd.dll
    gmock_main.vcxproj -> D:\usd_file\build_maya_usd\build\Debug\googletest-build\bin\Debug\gmock_maind.dll
    gtest.vcxproj -> D:\usd_file\build_maya_usd\build\Debug\googletest-build\bin\Debug\gtestd.dll
    gtest_main.vcxproj -> D:\usd_file\build_maya_usd\build\Debug\googletest-build\bin\Debug\gtest_maind.dll
    -- Install configuration: "Debug"
    -- Installing: D:/usd_file/build_maya_usd/build/Debug/googletest-install/include
    -- Installing: D:/usd_file/build_maya_usd/build/Debug/googletest-install/include/gmock
    -- Installing: D:/usd_file/build_maya_usd/build/Debug/googletest-install/include/gmock/gmock-actions.h
    -- Installing: D:/usd_file/build_maya_usd/build/Debug/googletest-install/include/gmock/gmock-cardinalities.h
    -- Installing: D:/usd_file/build_maya_usd/build/Debug/googletest-install/include/gmock/gmock-function-mocker.h
    -- Installing: D:/usd_file/build_maya_usd/build/Debug/googletest-install/include/gmock/gmock-generated-actions.h
    -- Installing: D:/usd_file/build_maya_usd/build/Debug/googletest-install/include/gmock/gmock-generated-actions.h.pump
    -- Installing: D:/usd_file/build_maya_usd/build/Debug/googletest-install/include/gmock/gmock-generated-function-mockers.h
    -- Installing: D:/usd_file/build_maya_usd/build/Debug/googletest-install/include/gmock/gmock-generated-function-mockers.h.pump
    -- Installing: D:/usd_file/build_maya_usd/build/Debug/googletest-install/include/gmock/gmock-generated-matchers.h
    -- Installing: D:/usd_file/build_maya_usd/build/Debug/googletest-install/include/gmock/gmock-generated-matchers.h.pump
    -- Installing: D:/usd_file/build_maya_usd/build/Debug/googletest-install/include/gmock/gmock-matchers.h
    -- Installing: D:/usd_file/build_maya_usd/build/Debug/googletest-install/include/gmock/gmock-more-actions.h
    -- Installing: D:/usd_file/build_maya_usd/build/Debug/googletest-install/include/gmock/gmock-more-matchers.h
    -- Installing: D:/usd_file/build_maya_usd/build/Debug/googletest-install/include/gmock/gmock-nice-strict.h
    -- Installing: D:/usd_file/build_maya_usd/build/Debug/googletest-install/include/gmock/gmock-spec-builders.h
    -- Installing: D:/usd_file/build_maya_usd/build/Debug/googletest-install/include/gmock/gmock.h
    -- Installing: D:/usd_file/build_maya_usd/build/Debug/googletest-install/include/gmock/internal
    -- Installing: D:/usd_file/build_maya_usd/build/Debug/googletest-install/include/gmock/internal/custom
    -- Installing: D:/usd_file/build_maya_usd/build/Debug/googletest-install/include/gmock/internal/custom/gmock-generated-actions.h
    -- Installing: D:/usd_file/build_maya_usd/build/Debug/googletest-install/include/gmock/internal/custom/gmock-generated-actions.h.pump
    -- Installing: D:/usd_file/build_maya_usd/build/Debug/googletest-install/include/gmock/internal/custom/gmock-matchers.h
    -- Installing: D:/usd_file/build_maya_usd/build/Debug/googletest-install/include/gmock/internal/custom/gmock-port.h
    -- Installing: D:/usd_file/build_maya_usd/build/Debug/googletest-install/include/gmock/internal/custom/README.md
    -- Installing: D:/usd_file/build_maya_usd/build/Debug/googletest-install/include/gmock/internal/gmock-internal-utils.h
    -- Installing: D:/usd_file/build_maya_usd/build/Debug/googletest-install/include/gmock/internal/gmock-port.h
    -- Installing: D:/usd_file/build_maya_usd/build/Debug/googletest-install/include/gmock/internal/gmock-pp.h
    -- Installing: D:/usd_file/build_maya_usd/build/Debug/googletest-install/lib/gmockd.lib
    -- Installing: D:/usd_file/build_maya_usd/build/Debug/googletest-install/bin/gmockd.dll
    -- Installing: D:/usd_file/build_maya_usd/build/Debug/googletest-install/lib/gmock_maind.lib
    -- Installing: D:/usd_file/build_maya_usd/build/Debug/googletest-install/bin/gmock_maind.dll
    -- Installing: D:/usd_file/build_maya_usd/build/Debug/googletest-install/lib/gmockd.pdb
    -- Installing: D:/usd_file/build_maya_usd/build/Debug/googletest-install/lib/gmock_maind.pdb
    -- Installing: D:/usd_file/build_maya_usd/build/Debug/googletest-install/lib/pkgconfig/gmock.pc
    -- Installing: D:/usd_file/build_maya_usd/build/Debug/googletest-install/lib/pkgconfig/gmock_main.pc
    -- Installing: D:/usd_file/build_maya_usd/build/Debug/googletest-install/lib/cmake/GTest/GTestTargets.cmake
    -- Installing: D:/usd_file/build_maya_usd/build/Debug/googletest-install/lib/cmake/GTest/GTestTargets-debug.cmake
    -- Installing: D:/usd_file/build_maya_usd/build/Debug/googletest-install/lib/cmake/GTest/GTestConfigVersion.cmake
    -- Installing: D:/usd_file/build_maya_usd/build/Debug/googletest-install/lib/cmake/GTest/GTestConfig.cmake
    -- Up-to-date: D:/usd_file/build_maya_usd/build/Debug/googletest-install/include
    -- Installing: D:/usd_file/build_maya_usd/build/Debug/googletest-install/include/gtest
    -- Installing: D:/usd_file/build_maya_usd/build/Debug/googletest-install/include/gtest/gtest-death-test.h
    -- Installing: D:/usd_file/build_maya_usd/build/Debug/googletest-install/include/gtest/gtest-matchers.h
    -- Installing: D:/usd_file/build_maya_usd/build/Debug/googletest-install/include/gtest/gtest-message.h
    -- Installing: D:/usd_file/build_maya_usd/build/Debug/googletest-install/include/gtest/gtest-param-test.h
    -- Installing: D:/usd_file/build_maya_usd/build/Debug/googletest-install/include/gtest/gtest-printers.h
    -- Installing: D:/usd_file/build_maya_usd/build/Debug/googletest-install/include/gtest/gtest-spi.h
    -- Installing: D:/usd_file/build_maya_usd/build/Debug/googletest-install/include/gtest/gtest-test-part.h
    -- Installing: D:/usd_file/build_maya_usd/build/Debug/googletest-install/include/gtest/gtest-typed-test.h
    -- Installing: D:/usd_file/build_maya_usd/build/Debug/googletest-install/include/gtest/gtest.h
    -- Installing: D:/usd_file/build_maya_usd/build/Debug/googletest-install/include/gtest/gtest_pred_impl.h
    -- Installing: D:/usd_file/build_maya_usd/build/Debug/googletest-install/include/gtest/gtest_prod.h
    -- Installing: D:/usd_file/build_maya_usd/build/Debug/googletest-install/include/gtest/internal
    -- Installing: D:/usd_file/build_maya_usd/build/Debug/googletest-install/include/gtest/internal/custom
    -- Installing: D:/usd_file/build_maya_usd/build/Debug/googletest-install/include/gtest/internal/custom/gtest-port.h
    -- Installing: D:/usd_file/build_maya_usd/build/Debug/googletest-install/include/gtest/internal/custom/gtest-printers.h
    -- Installing: D:/usd_file/build_maya_usd/build/Debug/googletest-install/include/gtest/internal/custom/gtest.h
    -- Installing: D:/usd_file/build_maya_usd/build/Debug/googletest-install/include/gtest/internal/custom/README.md
    -- Installing: D:/usd_file/build_maya_usd/build/Debug/googletest-install/include/gtest/internal/gtest-death-test-internal.h
    -- Installing: D:/usd_file/build_maya_usd/build/Debug/googletest-install/include/gtest/internal/gtest-filepath.h
    -- Installing: D:/usd_file/build_maya_usd/build/Debug/googletest-install/include/gtest/internal/gtest-internal.h
    -- Installing: D:/usd_file/build_maya_usd/build/Debug/googletest-install/include/gtest/internal/gtest-param-util.h
    -- Installing: D:/usd_file/build_maya_usd/build/Debug/googletest-install/include/gtest/internal/gtest-port-arch.h
    -- Installing: D:/usd_file/build_maya_usd/build/Debug/googletest-install/include/gtest/internal/gtest-port.h
    -- Installing: D:/usd_file/build_maya_usd/build/Debug/googletest-install/include/gtest/internal/gtest-string.h
    -- Installing: D:/usd_file/build_maya_usd/build/Debug/googletest-install/include/gtest/internal/gtest-type-util.h
    -- Installing: D:/usd_file/build_maya_usd/build/Debug/googletest-install/include/gtest/internal/gtest-type-util.h.pump
    -- Installing: D:/usd_file/build_maya_usd/build/Debug/googletest-install/lib/gtestd.lib
    -- Installing: D:/usd_file/build_maya_usd/build/Debug/googletest-install/bin/gtestd.dll
    -- Installing: D:/usd_file/build_maya_usd/build/Debug/googletest-install/lib/gtest_maind.lib
    -- Installing: D:/usd_file/build_maya_usd/build/Debug/googletest-install/bin/gtest_maind.dll
    -- Installing: D:/usd_file/build_maya_usd/build/Debug/googletest-install/lib/gtestd.pdb
    -- Installing: D:/usd_file/build_maya_usd/build/Debug/googletest-install/lib/gtest_maind.pdb
    -- Installing: D:/usd_file/build_maya_usd/build/Debug/googletest-install/lib/pkgconfig/gtest.pc
    -- Installing: D:/usd_file/build_maya_usd/build/Debug/googletest-install/lib/pkgconfig/gtest_main.pc
  Completed 'googletest'
  Building Custom Rule D:/usd_file/build_maya_usd/build/Debug/googletest-config/CMakeLists.txt
-- ========== ...  GoogleTest installed. ==========
-- Found Boost 1.70.0 at D:/usd_file/build/USD_20_11/lib/cmake/Boost-1.70.0
--   Requested configuration: QUIET REQUIRED COMPONENTS filesystem;system
-- Found boost_headers 1.70.0 at D:/usd_file/build/USD_20_11/lib/cmake/boost_headers-1.70.0
CMake Error at D:/usd_file/build/USD_20_11/lib/cmake/Boost-1.70.0/BoostConfig.cmake:95 (find_package):
  Could not find a package configuration file provided by "boost_filesystem"
  (requested version 1.70.0) with any of the following names:

    boost_filesystemConfig.cmake
    boost_filesystem-config.cmake

  Add the installation prefix of "boost_filesystem" to CMAKE_PREFIX_PATH or
  set "boost_filesystem_DIR" to a directory containing one of the above
  files.  If "boost_filesystem" provides a separate development package or
  SDK, be sure it has been installed.
Call Stack (most recent call first):
  D:/usd_file/build/USD_20_11/lib/cmake/Boost-1.70.0/BoostConfig.cmake:124 (boost_find_dependency)
  C:/Python27/Lib/site-packages/cmake/data/share/cmake-3.18/Modules/FindBoost.cmake:448 (find_package)
  lib/mayaUsd/CMakeLists.txt:29 (find_package)


-- Configuring incomplete, errors occurred!
See also "D:/usd_file/build_maya_usd/build/Debug/CMakeFiles/CMakeOutput.log".
See also "D:/usd_file/build_maya_usd/build/Debug/CMakeFiles/CMakeError.log".

Traceback (most recent call last):
  File "build.py", line 602, in <module>
    BuildAndInstall(context, context.buildArgs, context.stagesArgs)
  File "build.py", line 371, in BuildAndInstall
    RunCMake(context, extraArgs, stagesArgs)
  File "build.py", line 277, in RunCMake
    extraArgs=(" ".join(extraArgs) if extraArgs else "")))
  File "build.py", line 165, in Run
    .format(cmd=cmd, log=os.path.abspath(context.logFileLocation)))
RuntimeError: Failed to run 'cmake -DCMAKE_INSTALL_PREFIX="D:\usd_file\build_maya_usd\install\Debug" -DCMAKE_BUILD_TYPE=Debug -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -G "Visual Studio 15 2017 Win64" -DMAYA_LOCATION="C:\Program Files\Autodesk\Maya2018" -DPXR_USD_LOCATION="D:\usd_file\build_USD" -DMAYA_DEVKIT_LOCATION="C:\Users\sum tse\devkitBase" -DMAYAUSD_DEFINE_BOOST_DEBUG_PYTHON_FLAG=ON "D:\usd_file\git\maya-usd"'
See D:\usd_file\build_maya_usd\build\Debug\build_log.txt for more details.

[build_log.txt](https://github.com/Autodesk/maya-usd/files/5716978/build_log.txt)
[CMakeError.log](https://github.com/Autodesk/maya-usd/files/5716975/CMakeError.log)

**Comment by seando-adsk** [comment]
Is there a specific reason you used the flags "--build-debug --debug-python"? That configuration is much harder to build because you need debug builds of all the other dependencies (Maya, USD, python, etc). I would suggest not adding these two flags, which will build the default "RelWithDebInfo" config.

**Comment by SumTse** [comment]
@seando-adsk i test remove the flags "--build-debug --debug-python", is the same error, i think the problem may be boost_filesystem?
**Build log**
CMake Error at D:/usd_file/build/USD_20_11/lib/cmake/Boost-1.70.0/BoostConfig.cmake:95 (find_package):
Could not find a package configuration file provided by "boost_filesystem"
(requested version 1.70.0) with any of the following names:
Add the installation prefix of "boost_filesystem" to CMAKE_PREFIX_PATH or
set "boost_filesystem_DIR" to a directory containing one of the above
files. If "boost_filesystem" provides a separate development package or
SDK, be sure it has been installed.
Call Stack (most recent call first):
D:/usd_file/build/USD_20_11/lib/cmake/Boost-1.70.0/BoostConfig.cmake:124 (boost_find_dependency)
C:/Python27/Lib/site-packages/cmake/data/share/cmake-3.18/Modules/FindBoost.cmake:448 (find_package)
lib/mayaUsd/CMakeLists.txt:29 (find_package)

**Comment by seando-adsk** [comment]
When you build USD you need to provide some extra build args for the boost part of the build like so:
`--build-args "boost,--with-date_time --with-thread --with-system --with-filesystem"`

**Comment by SumTse** [comment]
hi @seando-adsk,
sound good, i go back to build USD,use your flag can build maya usd now,Thanks!

**Comment by seando-adsk** [comment]
@SumTse That is good news. I'm going to close this issue then.
