### ISSUE TITLE
[MAYA-108960] Usd Layer Editor Fatal error

### ISSUE THREAD

**Issue by jhultgre** [Autodesk/maya-usd#1020]
**Describe the bug**
When I press the the Loadfrom existing layer button maya fatal errors.

**Steps to reproduce**
1. Open new maya session
2. Open USD Layer Editor
3. Create menu > Stage with new layer
4. Press the load an existing layer icon.

**Expected behavior**
Maya doesn't crash

**Attachments**
If applicable, add screenshots, sample files, etc to help explain your problem.

**Specs (if applicable):**
 - Windows 10
 - Maya 2020.4
 - Maya USD 0.6.0

![image](https://user-images.githubusercontent.com/6559190/102565265-f896cc80-4091-11eb-9804-7847365e0bf4.png)

**Comment by santosd** [comment]
Hello @jhultgre,
Thank you for reporting the issue that you are experiencing. I downloaded the Maya USD from the releases [page](https://github.com/Autodesk/maya-usd/releases), and wasn't able to replicate the issue. Can you go into Help > About Maya and provide me with the cut ID? Could you also go into Windows > Settings\Preferences > Plug-in Manager and check what the cut is in the path of the Maya USD plugin? For example in the path you should see something like 0.6.0_202012102328-efea2cd are you seeing the same cut ID for yours? If it is different, please let me know what your version is. Another possible thing to try is to default the Maya 2020.4 preferences. The preferences can be reset to default by assuring that Maya is closed then renaming the 2020 folder found at  Documents/maya/2020 to something like 2020.old and launching Maya. At launch you can create default preferences.

I hope that information is helpful.

Cheers,
David Santos

**Comment by luceric-adsk** [comment]
Hello, I think this crash occurs if the MayaHIK plugin is not loaded in Maya

**Comment by santosd** [comment]
Thank you @luceric-adsk  I tested this out and unloaded HIK then I was able to hit the crash. I have logged the issue internally for a fix to be implemented.

**Comment by jhultgre** [comment]
Good to know. Are there any other plugins to watch out for? For example we don't use arnold either since it breaks our pipeline.

**Comment by luceric-adsk** [comment]
no, it was just that we used an icon from the HIK plugin thinking it was standard maya icon. Sorry about that. We'll be addressing that soon.

**Comment by jhultgre** [comment]
Just checked and this is fixed in 0.7.0
