### ISSUE TITLE
[MAYA-102266] VP2RenderDelegate: Selection Highlight Consistent ( No visual cue for last selected object )

### ISSUE THREAD

**Issue by cfmoore007** [Autodesk/maya-usd#104]
**Issue :**

When selecting multiple DAG objects in Maya, the application lets you visually see the last selected object ( highlighted in green vs the earlier selections that are highlighted white ).

While selecting USD Prims ( as part of the same proxy shape ), all selected objects are highlighted in green.  This makes it difficult to know the last selected object.
 

**Steps to reproduce :**

1. open the maya file included in **selectionTest.tar.gz**
2. shift-select sphere prims ( notice the highlight color is the same on all 3 )
3. now try making a few maya spheres ( DAG objects ) and try the same
4. Notice the difference in selection highlighting.

**Comment by cfmoore007** [comment]
I should note that this was actually tested with the dev branch and PR#91.

**Comment by cfmoore007** [comment]
![SelectionHighlighting](https://user-images.githubusercontent.com/2152250/68489212-a8a1d100-0214-11ea-95d6-634496a06757.jpg)

**Comment by cfmoore007** [comment]
[selectionTest.tar.gz](https://github.com/Autodesk/maya-usd/files/3825263/selectionTest.tar.gz)

**Comment by HdC-adsk** [comment]
Logged as MAYA-102266.

**Comment by cfmoore007** [comment]
Is this by any chance related to this issue on the usd repo : https://github.com/PixarAnimationStudios/USD/issues/1096 ?

**Comment by HdC-adsk** [comment]
No, we don't use Hydra GL imaging system.
