### ISSUE TITLE
[MAYA-105141] Transform's offsetParentMatrix attribute not being used when exporting transforms using mayaUsdPlugin.

### ISSUE THREAD

**Issue by FrodeMohrsen** [Autodesk/maya-usd#1045]
**Describe the bug**
The offsetParentMatrix attribute of transform nodes is not taken into consideration when exporting transform nodes from Maya using the mayaUsdPlugin.

**Steps to reproduce**
1. Create an empty scene in maya
2. Create a poly sphere and a poly cube
3. Connect the worldMatrix[0] attribute of the sphere to the offsetParentMatrix attribute of the cube
4. Set the translateY attribute of the splere to 1, which will also move the cube to the sphere's location
5. Export the sphere and the cube using the mayaUsdPlugin
6. Import the cube and the sphere using the mayaUsdPlugin.
7. You can now see that the imported cube is in the center of the scene and not at the sphere's location where it should be.

**Expected behavior**
Would expect the cube to be in the sphere's location. Would expect this to be solved by multiplying the offsetParentMatrix attribute of transforms to the matrix of the transforms during usd export.

**Specs (if applicable):**
 - OS & version: windows 10
 - Maya version: 2020.2
 - Plugin version 0.5.0
 - API version 20200200.

**Additional context**

**Comment by kxl-adsk** [comment]
Thank you for reporting. We are aware of the lack of support for offsetParentMatrix. The short term plan is to properly export offsetParentMatrix by baking it into objects transformations (I believe this matches your expected behavior). A longer-term plan is to include it in xform stack we export and allow roundtrip.

**Comment by santosg87** [comment]
note that this issue was brought up by a different user as well on #1925.

**Comment by santosg87** [comment]
This should be fixed with #2731. :)

marking this issue as closed for the time being, if this is still an issue, feel free to either reopen this, or log a new issue so we can track it.
