### ISSUE TITLE
Autodesk plugin does not return stage pointer via python.

### ISSUE THREAD

**Issue by manneohrstrom** [Autodesk/maya-usd#1046]
**Describe the bug**
Autodesk plugin (v0.6.0/USD 20.02/Maya 2020.3) does not return stage pointer via python due to what looks like invalid dagpath resolution.

**Steps to reproduce**

*Using the UI*
1. Build 0.6.0 Autodesk portion of plugin only, using USD 20.02 and Maya 2020.3 (note: the issue is likely unrelated to version of USD and can be reproduced in maya 2019.2 as well)
2. Start maya 2020.3. Load Autodesk Maya USD plugin
3. Click Menu: Create > Universal Scene Description > Stage from file. Choose pixar kitchen
4. Select maya usd proxy node in maya outliner 
5. In attribute editor, the root layer and default prim are not populated with any values. *see attached screenshot*

*Python API*
1. Build 0.6.0 Autodesk portion of plugin only, using USD 20.02 and Maya 2020.3 (note: the issue is likely unrelated to version of USD and can be reproduced in maya 2019.2 as well)
2. Start maya 2020.3. Load Autodesk Maya USD plugin
3. Click Menu: Create > Universal Scene Description > Stage from file. Choose pixar kitchen
6. In the python console, type in:

```python
import mayaUsd.ufe
stage = mayaUsd.ufe.getStage("|Kitchen_set|Kitchen_setShape")
```
You get an error message - *see attached screenshot*

**Expected behavior**
I would expect the following code to return the usd stage object:

```python
import mayaUsd.ufe
stage = mayaUsd.ufe.getStage("|Kitchen_set|Kitchen_setShape")
```

**Workaround**
It looks like there is logic in the code to try to convert a full dag path to a leaf-only dag path (e.g. `|Kitchen_set|Kitchen_setShape` -> `Kitchen_setShape`), however this logic converts `|Kitchen_set|Kitchen_setShape` -> `|Kitchen_setShape` which is an invalid dag path. Removing the initial pipe symbol from the "local" dag path works around the issue.

This conversion only happens for UFE 1.0, so i am guessing this bug is only happening in maya versions 2018-2020. I haven't tested latest 2021 PR versions, but i would suspect this bug doesn't happen there. 

**Attachments**

Missing info in the AE template:
<img width="1562" alt="ui-repro" src="https://user-images.githubusercontent.com/337710/103903678-1b962880-50f4-11eb-91b2-05d2ed603e0b.png">

Python Error:
<img width="2657" alt="python-repro" src="https://user-images.githubusercontent.com/337710/103903696-2224a000-50f4-11eb-850a-1f4c18637d97.png">

Code workaround [modifying this code](https://github.com/Autodesk/maya-usd/blob/v0.6.0/lib/mayaUsd/ufe/UsdStageMap.cpp#L28):
<img width="745" alt="workaround" src="https://user-images.githubusercontent.com/337710/103903838-54360200-50f4-11eb-9683-9ce62db71af6.png">

Build Parameters:
<img width="1051" alt="build-parameters" src="https://user-images.githubusercontent.com/337710/103903853-5bf5a680-50f4-11eb-9d78-c73765b7712e.png">

**Specs (if applicable):**
 - OS & version: Centos 7
 - Compiler & version: VFX Platfrom 2019 (gcc 631)
 - Maya version: Maya 2020.3
 - Maya USD commit: tag 0.6.0
 - Pixar USD commit: tag 20.02

**Comment by seando-adsk** [comment]
@manneohrstrom I had a look and found there is a bug in the getStage() function in the UFE v1 code path. It works correctly for UFE v2. It is a simple fix. I'll try to get it posted to GitHub shortly.

**Comment by manneohrstrom** [comment]
Thank you Sean! Great to get this fixed!

This does make me slightly concerned about the test coverage and QA for UFE 1.0 and maya 2019/2020 - do you have a regression test suite that you go through with maya 2019/2020 for each new maya usd release up or do you just cover the Maya PR releases (UFE 2 pathways) when you do QA?

**Comment by kxl-adsk** [comment]
Hi @manneohrstrom Yes, we have regression tests and each of them have to pass across the matrix of supported Maya and USD versions before we merge a pull request.

**Comment by manneohrstrom** [comment]
Just saw your comment over in https://github.com/Autodesk/maya-usd/pull/1050 about adding additional tests to cover this - thank you!

**Comment by manneohrstrom** [comment]
@kxl-adsk is this matrix documented somewhere? Given the large number of permutations between usd versions, maya versions and build configurations, it would be really helpful to have this info exposed somewhere!

**Comment by kxl-adsk** [comment]
Did you check https://github.com/Autodesk/maya-usd/blob/dev/doc/build.md#2-download-and-build-pixar-usd document?

**Comment by manneohrstrom** [comment]
@kxl-adsk Thanks, that document is great and extremely helpful. I did go through it but i forgot that it contains the set of supported versions! Perfect! I'll assume going forward that those (144+) combinations are the supported ones that get tested and QAed. Thx!

**Comment by kxl-adsk** [comment]
As you have pointed out, number of combinations is hight and we are only talking about automatic regression tests coverage. You can add to the mix number of platforms, release and debug build, different combinations of build flags. In reality with PF time taking up to one hour we can’t and won’t attempt to run them all, but we want to run at least one platform for each supported Maya version and at validate minimal and latest supported versions of USD. 

Finally, do not mix QA manual validation with running regression tests. 

BTW. I’m wondering what’s the source of your question? Is there a particular problem you are trying to solve?

**Comment by manneohrstrom** [comment]
Thanks for all the info. The reason i am asking is because i am trying to understand to what extent maya 2019 and 2020 is currently supported, and what the plan going forward is. Understanding this helps inform our studio strategy.

This bug seemed like a pretty obvious one (root layer and default prim fields empty in AE template UI when loading basic usd scene) - i was surprised it wasn't caught by QA. This made me wonder whether there was any QA being carried out at all on 2019/2020 (UFE 1.0) and what the plan is going forward when it comes to supporting these versions.

I think however that this is probably more of a product management question; i posted in the beta forums a couple of days ago - we can probably conclude the conversation here and I'll wait for a response over in the forums.

Thank you for being so helpful and proactive!

**Comment by kxl-adsk** [comment]
The response in forums is coming :)

**Comment by seando-adsk** [comment]
@manneohrstrom Sorry it took longer than expected, but my PR #1050 has been merged.

**Comment by kxl-adsk** [comment]
@manneohrstrom can you validate and close this ticket?

**Comment by manneohrstrom** [comment]
This is verified in 0.8.0! Thanks so much! Closing!
