### ISSUE TITLE
VP2RenderDelegate: Selection Highlight Lost When Selecting Multiple Proxy Shapes ( only last selection is highlighted )

### ISSUE THREAD

**Issue by cfmoore007** [Autodesk/maya-usd#105]
**Issue :**

When selecting multiple AL Proxy Shapes objects in Maya, only the last selected shape shows it's selection highlight.

Selecting the prims themselves across proxy shapes all show up highlighted green ( see https://github.com/Autodesk/maya-usd/issues/104 for that separate highlight color related issue )

**Steps to reproduce :**

1.open the maya file included in **selectionTest.tar.gz**
2. select first proxy shape in Maya Outliner ( notice it's highlighted green, this is expected )
3. now shift-select the second proxyShape
4. Notice the first proxyShape loses it's selection highlight once the second proxyShape is selected.

**Comment by cfmoore007** [comment]
I should note that this was actually tested with the dev branch and PR#91.

**Comment by cfmoore007** [comment]
![SecondProxyShapeHighlighted_FirstLost](https://user-images.githubusercontent.com/2152250/68489278-ca9b5380-0214-11ea-80ff-ea0e01f924b3.jpg)

**Comment by cfmoore007** [comment]
[selectionTest.tar.gz](https://github.com/Autodesk/maya-usd/files/3825262/selectionTest.tar.gz)

**Comment by HdC-adsk** [comment]
Logged as MAYA-102267.

**Comment by cfmoore007** [comment]
The linked PR seems to address this specific issue.
