### ISSUE TITLE
Skeletons not exporting from Maya scene

### ISSUE THREAD

**Issue by TechArtistG** [Autodesk/maya-usd#1055]
**Note:  This bug is still valid but I've worked out it's specific to using cmds.file.  Exporting USDSkel works with cmds.mayaUSDExport.**

I'm trying to export a skeleton of joint objects in a Maya scene to USD but can't get it to export any skeleton information.

1. Load the skeleton test scene from the repo: 
maya-usd\test\lib\usd\translators\UsdExportSkeletonTest\UsdExportSkeleton.ma

2. Export file to USD with exportSkels='auto' option:
```
import maya.cmds as cmds
cmds.file("c:/temp/USD/skelTest07.usda", defaultExtensions=False, exportAll=True, preserveReferences=True, type="USD Export", options="shadingMode='none'; mergeTransformAndShape=1; exportSkels='auto'")
```
Note: Options are taken from maya-usd\test\lib\usd\translators\testUsdExportSkeleton.py

3. Load exported USD file, the skeleton is not exported.

Maya Version: 2021 PR121
Maya USD Plugin Version: 0.6
OS: Windows 10

**Comment by MKGitHub** [comment]
Same issue macOS maya2022 R23.

**Comment by santosg87** [comment]
I was able to confirm this is due to the way the command works, when using the export command, it doesn't support any spaces between the flags. marking this one closed for now. feel free to re-open if you still find this one to be an issue. :)
