### ISSUE TITLE
Maya always uses "pxrUsdImport" file type to load references in reference editor.

### ISSUE THREAD

**Issue by hongloull** [Autodesk/maya-usd#107]
Hi There,

It looks like Maya always uses "pxrUsdImport" type instead of use specified type to load reference files. 

Issue reproducing steps:
1. New a Maya scene
2. Load Pxr Maya plugins and AL Maya plugins at the same time.
3. Make a polygon cube and export it with "**AL usdmaya export**" file type option.
4. Reference the exported usd file with "**AL usdmaya import**" file type option.
5. Get below issue if unload or reload the referenced file in Reference Editor:
// Error: Unknown flag 'Import_Meshes' -- Coding Error in ParseArgumentValue at line 1871 of C:\workspace_usd\maya-usd\plugin\pxr\maya\lib\usdMaya\util.cpp // 
// Error: Unknown flag 'Import_Curves' -- Coding Error in ParseArgumentValue at line 1871 of C:\workspace_usd\maya-usd\plugin\pxr\maya\lib\usdMaya\util.cpp // 
// Error: Unknown flag 'Import_Animations' -- Coding Error in ParseArgumentValue at line 1871 of C:\workspace_usd\maya-usd\plugin\pxr\maya\lib\usdMaya\util.cpp // 
// Error: Unknown flag 'Import_Dynamic_Attributes' -- Coding Error in ParseArgumentValue at line 1871 of C:\workspace_usd\maya-usd\plugin\pxr\maya\lib\usdMaya\util.cpp // 
// Error: Unknown flag 'Load_None' -- Coding Error in ParseArgumentValue at line 1871 of C:\workspace_usd\maya-usd\plugin\pxr\maya\lib\usdMaya\util.cpp // 
// Error: Unknown flag 'Read_Default_Values' -- Coding Error in ParseArgumentValue at line 1871 of C:\workspace_usd\maya-usd\plugin\pxr\maya\lib\usdMaya\util.cpp // 

The saved Maya scene looks as:

//Maya ASCII 2019 scene
//Name: test.ma
//Last modified: Sun, Nov 10, 2019 12:39:06 PM
//Codeset: 936
file -rdi 1 -ns "cube" -rfn "cubeRN" -op "..." -typ "**pxrUsdExport**" "foo.usdc";
file -r -ns "cube" -dr 1 -rfn "cubeRN" -op "..." -typ "**pxrUsdExport**" "foo.usdc";

It looks like Maya uses "**pxrUsdImport**" type instead of "**AL usdmaya import**" type to load reference files.  Are there any ways to let Maya uses user selected import type(it is "AL usdmaya import" in this example) instead of "**pxrUsdImport**" to load references? Not sure is this a plugin issue or my settings issue. Really appreciate.

Best Regards,

-Jerry

**Comment by santosg87** [comment]
Hi Jerry,

thanks for the info. i can also reproduce this on my side. I logged it internally as MAYA-101980 so we can track things there as well

**Comment by hongloull** [comment]
Hey Santosg87,

Thanks to mark it.

-Jerry

**Comment by santosg87** [comment]
Hi @hongloull. I believe this is now fixed on the mayaUsd plugin. would you be able to validate and maybe close this? cheers!

**Comment by santosg87** [comment]
Marking this one as closed for now based on the above comment and internal testing.  @hongloull please re-open if this is still a problem :)
