### ISSUE TITLE
maya to hydra 0.6.0 crashes maya 2019.2 with usd 20.08/centos 7

### ISSUE THREAD

**Issue by manneohrstrom** [Autodesk/maya-usd#1083]
**Describe the bug**
Switching to any hydra renderer in maya 2019.2 with usd 20.08 on centos 7 crashes maya. 
Maya 2019.2 with usd 20.02 works fine and maya 2020.3 with 20.08 works fine.

**Steps to reproduce**
1. compile 0.6.0 with gcc 631, reference platform lib versions and usd 20.08, build with autodesk plugin only, QT off.
2. start maya 2019.2, load mtoh plugin
3. switch to embree or gl (storm) renderer via renderer menu
4. maya crashes

Note: Other combinations work: maya 2019.2 and usd 20.02 is fine. Maya 2020.3 and usd 20.08 is also fine. 

I am trying to understand if this is somehow related to my build configuration or if it can be reproduced independently. The fact that all other combinations of maya and usd i have tried work just fine makes me wonder if it somehow can be a bug reproducible on other setups.

**Expected behavior**
Maya should not crash.

**Specs (if applicable):**
 - OS & version: centos 7
 - Compiler & version: gcc 6.3.1, vfx platform 2019
 - Maya version: 2019.2
 - Maya USD: 0.6.0
 - Pixar USD: 20.08

**Comment by kxl-adsk** [comment]
We had a discussion about it recently when adding regression tests for mtoh. 

Decision was to disable building it by default in certain combinations of builds - see https://github.com/Autodesk/maya-usd/discussions/1017 for more details. 

Unless there is something missing, please close this ticket.

**Comment by manneohrstrom** [comment]
hi @kxl-adsk - firstly, thank you for your quick reply.

I guess this is the kind of thing i was wondering with my questions about testing and having a supported matrix of versions over in https://github.com/Autodesk/maya-usd/issues/1046. Your earlier comment, pointing to the [build page](https://github.com/Autodesk/maya-usd/blob/dev/doc/build.md#2-download-and-build-pixar-usd) made me think that the plugin had been tested with maya 2019 and 20.08 - now it turns out there are actually known issues with that particular build combination.

We are considering using this in production - as i am sure you can imagine, upgrading our studio USD ecosystem to 21.02 is far from straight forward. Upgrading to maya 2020 is even more complex and will likely take us months. We really would love to use the maya plugins soon, but being able to mitigate this kind of risk is key for us. 

I suggest expanding the support matrix you have on the build page to to include known issues, especially when they prevent large parts of the plugin from working. It would also be really helpful to know which combination of maya/usd versions have been taken through quality assurance and not just unit and integration testing.

Thanks!

**Comment by kxl-adsk** [comment]
We had a gap in automated testing when it comes to mtoh and this was recently addressed. Discussion you saw was a result of this effort.

**Comment by manneohrstrom** [comment]
Glad my feedback is helpful! I will see if i can `LD_PRELOAD` my glew libs as @pmolodo suggests... if that doesn't work then we will have to think further...

**Comment by manneohrstrom** [comment]
Update: `LD_PRELOAD`ing the glew version that is shipping with maya 2020.3 prior to launching maya 2019 does seem to resolve the crash. I need to test further to understand what the side effects of this kind of change would be...

**Comment by kxl-adsk** [comment]
I agree with you that we should have documented when `mtoh` is disabled (oversight when we merged #1023). 

Please use discussion thread #1017 to update us on how `LD_PRELOAD` workaround worked for you.

Finally, I believe we already answered your question about QA manual testing, when you posted it internally. Binaries we post (2020 and beta) are first tested by QA. Having said that, it shouldn't be a surprise that we focus QA testing more on new beta features and rely on automated testing to cover different combinations of the build settings.

**Comment by manneohrstrom** [comment]
Sure! `LD_PRELOAD` of maya 2020.3's glew when running 2019.2 is looking good initially - I will post some more comments when i have been running some more tests. I had some issues earlier but it turns out to be another unrelated issue (it seems the `usdMayaProxyShape` node crashes when you load in usd data which uses custom schemas if those schemas have not been loaded - but I need to narrow that down into a proper bug report so stay tuned).

Thank you!

**Comment by manneohrstrom** [comment]
the workaround seems good as far as i can tell. Closing this! Thanks for the help!
