### ISSUE TITLE
Error C2440 when building usd maya plugins.

### ISSUE THREAD

**Issue by yjcnbnbnb200** [Autodesk/maya-usd#1087]
**Describe the issue**
I met an ERROR C2440 during building usd plugins, the command line I use is:
**python build.py --maya-location "C:\Program Files\Autodesk\Maya2018" --pxrusd-location D:\USD --devkit-location D:\devkitbase D:\workspace**
I attached my log file.

**Build log**
Please attach a build_log.txt
[build_log.txt](https://github.com/Autodesk/maya-usd/files/5829666/build_log.txt)

_D:\maya-usd\lib\mayaUsd\fileio\shading\shadingModeRegistry.cpp(186): error C2440: 'initializing': cannot convert from 'initializer list' to 'pxrInternal_v0_20__pxrReserved__::UsdMayaShadingModeRegistry::ConversionInfo' [D:\workspace\build\RelWithDebInfo\lib\mayaUsd\mayaUsd.vcxproj]
  D:\maya-usd\lib\mayaUsd\fileio\shading\shadingModeRegistry.cpp(186): note: No constructor could take the source type, or constructor overload resolution was ambiguous
D:\maya-usd\lib\mayaUsd\fileio\shading\shadingModeRegistry.cpp(186): error C2440: '<function-style-cast>': cannot convert from 'const pxrInternal_v0_20__pxrReserved__::TfToken' to 'std::pair<const _Kty,_Ty>' [D:\workspace\build\RelWithDebInfo\lib\mayaUsd\mayaUsd.vcxproj]
          with
          [
              _Kty=pxrInternal_v0_20__pxrReserved__::TfToken,
              _Ty=pxrInternal_v0_20__pxrReserved__::UsdMayaShadingModeRegistry::ConversionInfo
          ]
  D:\maya-usd\lib\mayaUsd\fileio\shading\shadingModeRegistry.cpp(186): note: No constructor could take the source type, or constructor overload resolution was ambiguous
D:\maya-usd\lib\mayaUsd\fileio\shading\shadingModeRegistry.cpp(210): error C2440: 'initializing': cannot convert from 'initializer list' to 'pxrInternal_v0_20__pxrReserved__::UsdMayaShadingModeRegistry::ConversionInfo' [D:\workspace\build\RelWithDebInfo\lib\mayaUsd\mayaUsd.vcxproj]
  D:\maya-usd\lib\mayaUsd\fileio\shading\shadingModeRegistry.cpp(210): note: No constructor could take the source type, or constructor overload resolution was ambiguous
D:\maya-usd\lib\mayaUsd\fileio\shading\shadingModeRegistry.cpp(210): error C2440: '<function-style-cast>': cannot convert from 'const pxrInternal_v0_20__pxrReserved__::TfToken' to 'std::pair<const _Kty,_Ty>' [D:\workspace\build\RelWithDebInfo\lib\mayaUsd\mayaUsd.vcxproj]
          with
          [
              _Kty=pxrInternal_v0_20__pxrReserved__::TfToken,
              _Ty=pxrInternal_v0_20__pxrReserved__::UsdMayaShadingModeRegistry::ConversionInfo
          ]
  D:\maya-usd\lib\mayaUsd\fileio\shading\shadingModeRegistry.cpp(210): note: No constructor could take the source type, or constructor overload resolution was ambiguous_

**Specs:**
 - Windows 10
 - Visual Studio 2015 SP3
 - Maya 2018 SP6

**Comment by kxl-adsk** [comment]
Thank you for reporting this @yjcnbnbnb200. I'm afraid you have discovered a weakness in our validation - VS2015. We have updated to VS2017 and VS2019...and unfortunately, we don't have coverage for VS2015 anymore.

Do you think you can upgrade to VS2017?

If that's not an option, then fixing a part of compilation errors is relatively easy:
```
diff --git a/lib/mayaUsd/fileio/shading/shadingModeRegistry.h b/lib/mayaUsd/fileio/shading/shadingModeRegistry.h
index f3a51dad6..b41b59544 100644
--- a/lib/mayaUsd/fileio/shading/shadingModeRegistry.h
+++ b/lib/mayaUsd/fileio/shading/shadingModeRegistry.h
@@ -178,6 +178,10 @@ public:
         TfToken importDescription;
         bool    hasExporter = false;
         bool    hasImporter = false;
+
+        ConversionInfo() = default;
+        ConversionInfo(TfToken rc, TfToken nn, TfToken ed, TfToken id, bool he, bool hi)
+            : renderContext(rc), niceName(nn), exportDescription(ed), importDescription(id), hasExporter(he), hasImporter(hi) {}
     };

     /// Gets the conversion information associated with \p materialConversion on export and import
diff --git a/lib/mayaUsd/render/mayaToHydra/renderGlobals.h b/lib/mayaUsd/render/mayaToHydra/renderGlobals.h
index 97ca4c37d..c3277ea38 100644
--- a/lib/mayaUsd/render/mayaToHydra/renderGlobals.h
+++ b/lib/mayaUsd/render/mayaToHydra/renderGlobals.h
@@ -47,6 +47,10 @@ public:
         // If creating the attribute for the first time, immediately set to a user default
         const bool fallbackToUserDefaults = true;
         // TODO: Extend this and mtoh with a setting to ignore scene settings
+
+        GlobalParams() = default;
+        GlobalParams(const TfToken f, bool fir, bool ftud)
+            : filter(f), filterIsRenderer(fir), fallbackToUserDefaults(ftud) {}
     };

     // Creating render globals attributes on "defaultRenderGlobals"
diff --git a/plugin/al/mayautils/AL/maya/utils/PluginTranslatorOptions.cpp b/plugin/al/mayautils/AL/maya/utils/PluginTranslatorOptions.cpp
index a7d9228b8..b276988f5 100644
--- a/plugin/al/mayautils/AL/maya/utils/PluginTranslatorOptions.cpp
+++ b/plugin/al/mayautils/AL/maya/utils/PluginTranslatorOptions.cpp
@@ -258,7 +258,7 @@ void PluginTranslatorOptionsInstance::parse(MString key, const MString& value)
             if (opt->name == key) {
                 auto& optData = set.m_options[i];
                 switch (opt->type) {
-                case OptionType::kBool: optData.m_bool = value.asInt(); break;
+                case OptionType::kBool: optData.m_bool = (value.asInt() > 0); break;
                 case OptionType::kInt: optData.m_int = value.asInt(); break;
                 case OptionType::kEnum: optData.m_int = value.asInt(); break;
                 case OptionType::kFloat: optData.m_float = value.asFloat(); break;
```

That lets you pass compilation if you build **without** Qt. If you build **with** Qt, then there are remaining compilation errors caused by the same symbol being defined by Qt and USD:
```
C:\artifactory\windows\qt\5.6.1\14f946f\include\qtcore\qendian.h(67): error C2872: 'uchar': ambiguous symbol
C:\artifactory\Windows\qt\5.6.1\14f946f\include\QtCore/qglobal.h(204): note: could be 'unsigned char uchar'
C:\artifactory\Pixar_USD_VS2015\include\pxr/base/arch/inttypes.h(58): note: or       'pxrInternal_v0_21__pxrReserved__::uchar'
```

I don't know the trick how to work around the last one.

FWIW. We plan to revisit our minimum requirements like the minimum supported USD version. As part of it, we should revisit compiler settings as well.

**Comment by yjcnbnbnb200** [comment]
> 
> 
> Thank you for reporting this @yjcnbnbnb200. I'm afraid you have discovered a weakness in our validation - VS2015. We have updated to VS2017 and VS2019...and unfortunately, we don't have coverage for VS2015 anymore.
> 
> Do you think you can upgrade to VS2017?
> 
> If that's not an option, then fixing a part of compilation errors is relatively easy:
> 
> ```
> diff --git a/lib/mayaUsd/fileio/shading/shadingModeRegistry.h b/lib/mayaUsd/fileio/shading/shadingModeRegistry.h
> index f3a51dad6..b41b59544 100644
> --- a/lib/mayaUsd/fileio/shading/shadingModeRegistry.h
> +++ b/lib/mayaUsd/fileio/shading/shadingModeRegistry.h
> @@ -178,6 +178,10 @@ public:
>          TfToken importDescription;
>          bool    hasExporter = false;
>          bool    hasImporter = false;
> +
> +        ConversionInfo() = default;
> +        ConversionInfo(TfToken rc, TfToken nn, TfToken ed, TfToken id, bool he, bool hi)
> +            : renderContext(rc), niceName(nn), exportDescription(ed), importDescription(id), hasExporter(he), hasImporter(hi) {}
>      };
> 
>      /// Gets the conversion information associated with \p materialConversion on export and import
> diff --git a/lib/mayaUsd/render/mayaToHydra/renderGlobals.h b/lib/mayaUsd/render/mayaToHydra/renderGlobals.h
> index 97ca4c37d..c3277ea38 100644
> --- a/lib/mayaUsd/render/mayaToHydra/renderGlobals.h
> +++ b/lib/mayaUsd/render/mayaToHydra/renderGlobals.h
> @@ -47,6 +47,10 @@ public:
>          // If creating the attribute for the first time, immediately set to a user default
>          const bool fallbackToUserDefaults = true;
>          // TODO: Extend this and mtoh with a setting to ignore scene settings
> +
> +        GlobalParams() = default;
> +        GlobalParams(const TfToken f, bool fir, bool ftud)
> +            : filter(f), filterIsRenderer(fir), fallbackToUserDefaults(ftud) {}
>      };
> 
>      // Creating render globals attributes on "defaultRenderGlobals"
> diff --git a/plugin/al/mayautils/AL/maya/utils/PluginTranslatorOptions.cpp b/plugin/al/mayautils/AL/maya/utils/PluginTranslatorOptions.cpp
> index a7d9228b8..b276988f5 100644
> --- a/plugin/al/mayautils/AL/maya/utils/PluginTranslatorOptions.cpp
> +++ b/plugin/al/mayautils/AL/maya/utils/PluginTranslatorOptions.cpp
> @@ -258,7 +258,7 @@ void PluginTranslatorOptionsInstance::parse(MString key, const MString& value)
>              if (opt->name == key) {
>                  auto& optData = set.m_options[i];
>                  switch (opt->type) {
> -                case OptionType::kBool: optData.m_bool = value.asInt(); break;
> +                case OptionType::kBool: optData.m_bool = (value.asInt() > 0); break;
>                  case OptionType::kInt: optData.m_int = value.asInt(); break;
>                  case OptionType::kEnum: optData.m_int = value.asInt(); break;
>                  case OptionType::kFloat: optData.m_float = value.asFloat(); break;
> ```
> 
> That lets you pass compilation if you build **without** Qt. If you build **with** Qt, then there are remaining compilation errors caused by the same symbol being defined by Qt and USD:
> 
> ```
> C:\artifactory\windows\qt\5.6.1\14f946f\include\qtcore\qendian.h(67): error C2872: 'uchar': ambiguous symbol
> C:\artifactory\Windows\qt\5.6.1\14f946f\include\QtCore/qglobal.h(204): note: could be 'unsigned char uchar'
> C:\artifactory\Pixar_USD_VS2015\include\pxr/base/arch/inttypes.h(58): note: or       'pxrInternal_v0_21__pxrReserved__::uchar'
> ```
> 
> I don't know the trick how to work around the last one.
> 
> FWIW. We plan to revisit our minimum requirements like the minimum supported USD version. As part of it, we should revisit compiler settings as well.

Thanks man, I will seitch to VS2017 since I have it installed on my PC, thanks for your reply!

**Comment by kxl-adsk** [comment]
Thx. Make sure to grab https://github.com/Autodesk/maya-usd/pull/1096 (it has one fix for Maya 2018).
