### ISSUE TITLE
resource ("mayaUsdPlugin","kCreate") is not registered

### ISSUE THREAD

**Issue by charlesfleche** [Autodesk/maya-usd#1089]
**Describe the bug**

When selecting `Create > USD > Stage from file`, maya displays the `resource ("mayaUsdPlugin","kCreate") is not registered` error and nothing happens. However, when selecting `Create > USD > Stage with New Layer`, a new `stage1` nodes appears in the outliner and by setting its `Stage Source > File Path` attributes to a working USD file (Pixar's Kitchen Set), the stage is loaded and displayed as expected.

**Steps to reproduce**
1. Click on Menu `Create > USD > Stage from file`

**Expected behavior**

**Attachments**
![image](https://user-images.githubusercontent.com/2563098/104944828-c674d500-5985-11eb-90aa-8c1a4924eae3.png)

**Specs (if applicable):**
 - CentOS Linux release 7.6.1810 (Core)
 - devtoolset-6 gcc version 6.3.1 20170216 (Red Hat 6.3.1-3) (GCC) 
 - Maya 2020.2
 - Maya USD 0.6.0 bf4ea929c04c2fcef5d41050ce7cd1a309a1049a https://github.com/Autodesk/maya-usd/tree/v0.6.0 
 - Pixar USD 20.11 d8a405a1344480f859f025c4f97085143efacb53 https://github.com/PixarAnimationStudios/USD/tree/v20.11

**Additional context**

We only build the ASDK plugin using CMake, but not the Pixar or AL parts of the code.

```cmake
ExternalProject_Add(maya-usd
    GIT_REPOSITORY https://github.com/Autodesk/maya-usd.git
    GIT_TAG v${GIT_TAG_VERSION}

    CMAKE_ARGS
        -DCMAKE_INSTALL_PREFIX=${CMAKE_INSTALL_PREFIX}
        -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE}
        -DBUILD_WITH_PYTHON_3=${BUILD_WITH_PYTHON_3}
        -DPython_EXECUTABLE=$ENV{MAYA_LOCATION}/bin/mayapy$ENV{MAYA_PYTHON_VERSION}
        -DMAYA_DEVKIT_LOCATION=$ENV{MAYA_LOCATION}/devkit
        -DPXR_USD_LOCATION=$ENV{REZ_USD_ROOT}
        -DBUILD_PXR_PLUGIN=OFF
        -DBUILD_AL_PLUGIN=OFF
        -DBUILD_RFM_TRANSLATORS=OFF
        -DBUILD_TESTS=OFF
)
```

**Comment by kxl-adsk** [comment]
@charlesfleche this was already reported - please see https://github.com/Autodesk/maya-usd/issues/1005 for more details. The bottom line was - you have to build with Qt support.

I'm closing the ticket since it's a duplicate.
