### ISSUE TITLE
[dev] Build on windows fails due to UFE_TEST.util command being too long

### ISSUE THREAD

**Issue by elrond79** [Autodesk/maya-usd#116]
It seems that UFE_TEST.util just calls cmd.exe with a massive "&&" join of a bunch of tests, which results in the command being over the 8192 char limit for me, with my dir structure.  (Which isn't even all that long, to be honest: `D:\Projects\Dev\USD\maya-usd`).

This command needs to break this up into multiple commands to run (ideally, in parallel!), to avoid this issue.

**Comment by HamedSabri-adsk** [comment]
Huh!! What is this `UFE_TEST.util` and where does the call to cmd.exe happen?

**Comment by elrond79** [comment]
Apparently introduced in this commit:

c217793790c365eb28e6d272f23fa5045e0e7d4b

**Comment by elrond79** [comment]
Or possibly this one, not sure:

2d7b9bead76bec1971fb98e144a686a41b65b221

**Comment by elrond79** [comment]
Failure message looks like this (trimmed):

```
[241/479] Running utility command for UFE_TEST
FAILED: test/lib/ufe/CMakeFiles/UFE_TEST.util
cmd.exe /C "cd /D D:\Projects\Dev\USD\maya-usd\work\build\Release\test\lib\ufe && "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin\cmake.exe" -E copy_if_different D:/Projects/Dev/USD/maya-usd/src/test/lib/ufe/test-samples/ballset/StandaloneScene/Assembly_room_set.usda D:/Projects/Dev/USD/maya-usd/work/build/Release/test/lib/ufe/test-samples/ballset/StandaloneScene/Assembly_room_set.usda &&
```

**Comment by kxl-adsk** [comment]
I honestly can't find this file. It looks like it's in the build folder...but this is what I have:
E:\Dev\usd\_workspaces_latest\Maya_USD\build\RelWithDebInfo\test\lib\ufe\CMakeFiles\UFE_TEST.dir and in this folder I have`utility.bat` file. Nowhere I can find UFE_TEST.util.

**Comment by HamedSabri-adsk** [comment]
c217793 and 2d7b9be are what that brings support for UFE tests.

The Failure message doesn't really help.  Is this Windows 7 or 10?

**Comment by HamedSabri-adsk** [comment]
> 
> 
> I honestly can't find this file. It looks like it's in the build folder...but this is what I have:
> E:\Dev\usd_workspaces_latest\Maya_USD\build\RelWithDebInfo\test\lib\ufe\CMakeFiles\UFE_TEST.dir and in this folder I have`utility.bat` file. Nowhere I can find UFE_TEST.util.

I am on Windows 10 and same as Krystian can't find this file anywhere on my machine.

![UFE_TEST](https://user-images.githubusercontent.com/48299423/68723449-957d6100-0586-11ea-8365-e1e6c45bf877.PNG)

Also, mayaUsd_copyDirectory and mayaUsd_copyFiles are the utility functions that handle copying UFE resources ( e.g *.maya, *.usda, *.py ,etc...) in the `build\test\lib\ufe` directory.

**Comment by seando-adsk** [comment]
How are you running the builld? Thru some docker or other shell? In my utility.bat it is just calling cmake.exe directly. But from your trimmed error line it is calling cmd.exe to then call cmake.exe. Here on Windows we would just run the build thru a normal Windows command prompt.

**Comment by elrond79** [comment]
I also don't have a UFE_TEST.util on disk - the build dir:

```
test/lib/ufe/CMakeFiles/
```

...is actually empty for me.  So either it's something that automatically gets cleaned up, or a target that failed to build, or a dummy target that doesn't actually correspond to a file on disk (which is my guess).

I'm building on Windows 10 Pro, 1903, 18362.418.

I'm building directly from a windows shell, from which I manually invoke a Visual Studio `vcvarsall.bat`, as well as set some other env vars:

```
REM set VS build env vars
call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsall.bat" x64

REM use python-27
set PATH=C:\Apps\DevTools\Python27;C:\Apps\DevTools\Python27\Scripts;%PATH%

REM use VS's ninja
set PATH=C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\Ninja;%PATH%

set MAYA_LOCATION=C:\Apps\3D\Autodesk\Maya2019
```

I build using your provided python build.py, not via invoking cmake directly.

I don't have a utility.bat - I think the command that fails is the one that would be in charge of making that UFE_TEST.dir folder (which includes the afore-mentioned utility.bat).

**Comment by HamedSabri-adsk** [comment]
O.K thanks for the info. I have the same setup as yours. I will have a look into this later today. Very strange indeed!

**Comment by HamedSabri-adsk** [comment]
Interesting that stamp file doesn't created for you under test\lib\ufe\CMakeFiles

Here is what I get in that directory:

generate.stamp
`# CMake generation timestamp file for this directory.`

generate.stamp.depend
```
# CMake generation dependency list for this directory.
C:/Users/hamed/Autodesk2019/maya-usd/test/lib/ufe/CMakeLists.txt
```
Could be it related to Ninja generator? I realized I have been using VS generator for a while on Windows. Let me switch to Ninja and see If I can reproduce the problem.

**Comment by HamedSabri-adsk** [comment]
That's it! 

Now I don't see the stamp files generated anymore and it looks like Ninja now creates this `utility.bat`
under `test\lib\ufe\CMakeFiles\UFE_TEST.dir\`

Here is the content of `utility.bat`:
[utility.txt](https://github.com/Autodesk/maya-usd/files/3846632/utility.txt)

Not only that now only 9% tests pass. 
[tests_failed_ninja.txt](https://github.com/Autodesk/maya-usd/files/3846639/tests_failed_ninja.txt)

**Comment by elrond79** [comment]
Well, I just built recently on windows, and didn't see this pop up, so it's either been fixed or can't be reproduced. Closing.
