### ISSUE TITLE
.mod file for Pixar plugin does allow use of pxr.UsdMaya module

### ISSUE THREAD

**Issue by pmolodo** [Autodesk/maya-usd#1190]
**Describe the bug**
If you rely solely on the included `pxrUsd.mod` file to set up the Pixar plugin, but already have the USD python libs on your `PYTHONPATH`, then you will not be able to import the `pxr.UsdMaya` module.

This is because, since the `pxr.UsdMaya` works by "overriding" / "patching" the "normal" `pxr` module included by USD, it MUST come before the "normal" USD entry on the `PYTHONPATH`.

However, `pxrUsd.mod` appends to the `PYTHONPATH`, not prepends, so any existing USD entries will still take priority.

**Steps to reproduce**
1. Ensure the USD python libs are on `PYTHONPATH` - ie, on linux, `export PYTHONPATH=${PYTHONPATH}:${USD_ROOT}/lib/python`
2. Ensure the Maya-USD root is on the `MAYA_MODULE_PATH` - ie, `export MAYA_MODULE_PATH=${MAYA_USD_ROOT}`
3. Launch Maya
4. Do `import pxr.UsdMaya` in a pythons script editor
5. It will error that there is `No module named UsdMaya`

**Expected behavior**
We should be able to import the `pxr.UsdMaya` python module

**Specs (if applicable):**
 - OS & version Linux - Centos 7.7
 - Compiler & version - gcc 6.3.1
 - Maya version - Maya 2020
 - Maya USD commit SHA - 0.7.0 [0fe9ea49]
 - Pixar USD commit SHA - 0.20.11 [d8a405a1]

**Additional context**
Is there any way to tell a `.mod` file to prepend instead of append? If so, this is an easy fix...

**Comment by seando-adsk** [comment]
I was looking at some of the older issues and might have an answer for this one. Yes you can prepend (instead of append) by using * instead of + in a Maya mod file.

**Comment by pmolodo** [comment]
That sounds like it would do the trick!

**Comment by tanant** [comment]
Doing some housekeeping @pmolodo and noticed this one here - typing this remote so i don't have the relevant plugin handy but is this as simple as updating the .mod template from  
```
PYTHONPATH+:=lib/python
```
to 
```
PYTHONPATH*:=lib/python
```
for the prepend? (i'm assuming that `${PXR_OVERRIDE_PLUGINPATH_NAME}+:=lib/usd` is fine as an append as it's just a plugin search stack)

If so, seems like a pretty simple PR you (or I) can do, and close this issue out.

**Comment by pmolodo** [comment]
Hi - yes, it sounds like that would fix it!  I'm no longer involved with maya development these days, though, so if you want to just close the issue, I'm fine with that too!
