### ISSUE TITLE
Viewport does not immediately update when setting transform attr of adsk proxy parent

### ISSUE THREAD

**Issue by pmolodo** [Autodesk/maya-usd#1191]
**Describe the bug**
If you change the parent transform of an adsk proxyShape (ie, via python), the viewport does not immediately update to reflect the shape.  If you manipulate the shape, it will "pop" into the correct position.

The same issue does not occur with the AL proxyShape.

**Steps to reproduce**
1. Download the attached `plane.usda`
2. Run this in a python script editor, replacing `/path/to/plane.usda`:

    ```# test display of proxy after setAttr(proxy + ".rx", -45) - ADSK

    import maya.cmds as cmds

    plane_usd = '/path/to/plane.usda'

    cmds.loadPlugin('mayaUsdPlugin', quiet=1)

    cmds.file(f=1, new=1)
    cmds.select(clear=1)
    proxyShape = cmds.createNode('mayaUsdProxyShape')
    cmds.setAttr(proxyShape + '.filePath', plane_usd, type='string')

    proxyTrans = cmds.listRelatives(proxyShape, fullPath=1, parent=1)[0]
    cmds.setAttr(proxyTrans + '.rx', -45)```
3. Note that the viewport does not show the plane rotated
4. Use any transform manipulator to move the parent transform slightly
5. See the viewport "pop" into place
2. Run this in a python script editor, replacing `/path/to/plane.usda`:
    ```# test display of proxy after setAttr(proxy + ".rx", -45) - AL

    import maya.cmds as cmds

    plane_usd = '/path/to/plane.usda'

    cmds.loadPlugin('AL_USDMayaPlugin', quiet=1)

    cmds.file(f=1, new=1)
    cmds.select(clear=1)
    proxyShape = cmds.AL_usdmaya_ProxyShapeImport(file=plane_usd)[0]

    proxyTrans = cmds.listRelatives(proxyShape, fullPath=1, parent=1)[0]
    cmds.setAttr(proxyTrans + '.rx', -45)
    ```
7. Note that it DOES show the rotated plane

**Expected behavior**
When modifying a parent xform via python, the viewport should immediately update to reflect the change

**Attachments**
[plane.zip](https://github.com/Autodesk/maya-usd/files/5999369/plane.zip)

**Specs (if applicable):**

- OS & version Linux - Centos 7.7
- Compiler & version - gcc 6.3.1
- Maya version - Maya 2020
- Maya USD commit SHA - 0.7.0 [0fe9ea4]
- Pixar USD commit SHA - 0.20.11 [d8a405a1](https://github.com/PixarAnimationStudios/USD/commit/d8a405a1)

**Comment by santosd** [comment]
Hello @pmolodo, I have tested this in Maya using the latest release and was not able to reproduce the issue that you are seeing with the Maya Proxy Shape. Can you test again with the latest release and let me know if you are still seeing this issue. I know we have done some work on the viewport updates since this issue was first logged. Thank you and looking forward to hearing back.

**Comment by pmolodo** [comment]
Hi - I’m not working with maya-usd anymore, so not really in a position to test this, but if you’ve followed the reproduction steps and it works, then I’d imagine it’s fixed.  This issue is quite old, and predates the xform overhaul.
