### ISSUE TITLE
build.py not find USD_GENSCHEMA

### ISSUE THREAD

**Issue by cds1503** [Autodesk/maya-usd#12]
use command : python build.py --maya-location /usr/autodesk/maya2019 --pxrusd-location /usr/dev/lib/usd/19.07/USD-core /usr/dev/lib/usd/19.07-maya

but FindUSD cmake occurt error.

if pxrUsd build thirdparty problem?

**Comment by dtlindsey** [comment]
I believe this is the error.  After checking the build_log.txt and the CMakeOutput.log,  I could not find anything that would cause this issue.  I have also successfully built this package on a different machine, with the same version of USD (19.05), and all the same build settings, as well as the same build settings for the maya-usd plugins.  Any help would be appreciated

========== Pixar USD Plugin ==========
-- Found Maya: C:/Program Files/Autodesk/Maya2019/bin/maya.exe (found version "20190000")
CMake Error at C:/Program Files/CMake/share/cmake-3.15/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find USD (missing: USD_GENSCHEMA) (found version "0.19.5")
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.15/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  cmake/modules/FindUSD.cmake:70 (find_package_handle_standard_args)
  plugin/pxr/CMakeLists.txt:23 (find_package)


-- Configuring incomplete, errors occurred!
See also "C:/Users/lindd067/dev/external/install/maya-2019-usd-19.05/build/Release/CMakeFiles/CMakeOutput.log".

Traceback (most recent call last):
  File "build.py", line 458, in <module>
    InstallMayaUSD(context, context.forceBuild, context.buildArgs)
  File "build.py", line 307, in InstallMayaUSD
    RunCMake(context, force, extraArgs)
  File "build.py", line 281, in RunCMake
    extraArgs=(" ".join(extraArgs) if extraArgs else "")))
  File "build.py", line 189, in Run
    .format(cmd=cmd, log=os.path.abspath(context.logFileLocation)))
RuntimeError: Failed to run 'cmake -DCMAKE_INSTALL_PREFIX="C:\Users\lindd067\dev\external\install\maya-2019-usd-19.05\install\Release" -DCMAKE_BUILD_TYPE=Release -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -G "Visual Studio 14 2015 Win64" -DMAYA_LOCATION="C:\Program Files\Autodesk\Maya2019" -DPXR_USD_LOCATION="C:\Users\lindd067\dev\external\install\USD-19.05-all" "C:\Users\lindd067\dev\external\git\maya-usd"'

**Comment by HamedSabri-adsk** [comment]
There are two things to check:

1- Make sure you have `usdGenSchema` in your core USD bin directory
2- Make sure you don't have older USD in your PYTHONPATH

**Comment by dtlindsey** [comment]
Thanks.  Oddly enough the usdGenSchema didn't end up in the bin dir for some reason.  Just did another clean build, and it didn't show up.  Are there special options we need to add to the build process.

**Comment by emilche** [comment]
I am encountering this problem too. Is there some solution?

**Comment by emilche** [comment]
Found a solution for that problem for me at least! It was that i did not have jinja2 installed. Just do a pip install jinja2

**Comment by dtlindsey** [comment]
Thanks @emilche I just got that fix this morning in a reply to my posting on the Pixar USD page.  Attempting today, and will reply with results

**Comment by dtlindsey** [comment]
@emilche installing jinja did the trick.  this issue can be closed, but we may want to add this requirement to the docs.

**Comment by HamedSabri-adsk** [comment]
Glad it works!

Pixar's document mentions installing Jinja2 that is required for the core code generator of usdGenSchema. But that information is not mentioned in the main page https://github.com/PixarAnimationStudios/USD and rather in https://github.com/PixarAnimationStudios/USD/blob/master/BUILDING.md
which make it possible for one to miss in my opinion.

**Comment by kreppene** [comment]
Hi, 
im still strugeling with this error,  even after pip installing Jinja2

**my setup is** 
windows
USD 0.19.5 
[compile_maya-usd.log](https://github.com/Autodesk/maya-usd/files/3534395/compile_maya-usd.log)


python build.py --maya-location "C:/Program Files/Autodesk/maya2019/" --pxrusd-location C:/qvisten_pipeline/usd_2/ C:\qvisten_pipeline\deploy\maya-usd

Any help is very much appreciated

**Comment by seando-adsk** [comment]
@kreppene  Your build log is saying that it cannot find USDGENSCHEMA which from your USD path should be: 
C:\qvisten_pipeline\usd_2\bin\usdGenSchema.cmd

Does that file exist? If not, then you probably need to rebuild USD now that you have Jinja2 installed. It is a requirement that is checked when building USD.

**Comment by kreppene** [comment]
Thanks @seando-adsk 
that was it i recompiled usd again after installing jinja2
now it works

Thanks again

**Comment by aka-anoop** [comment]
> Found a solution for that problem for me at least! It was that i did not have jinja2 installed. Just do a pip install jinja2

Worked great on mac. Thank you

**Comment by dtlindsey** [comment]
@HamedSabri-adsk who are you requesting close this?  I do not have the ability, though I am the one that opened it.  I'm assuming this is managed by someone at Autodesk?

**Comment by BigRoy** [comment]
@cds1503 Is the original creator of the issue and should be able to close it.

**Comment by cds1503** [comment]
i'm sorry, i watch reply too late :(
