### ISSUE TITLE
UV's missing when exporting to USD

### ISSUE THREAD

**Issue by swamiforlife** [Autodesk/maya-usd#1202]
When i export some geometry to USD the UV's are missing.
Is this feature yet to be implemented? or is it a bug?

**Comment by eoffermann** [comment]
Obvious question perhaps but did you set the "exportUVs" tag (if you're doing it in python/mel) or make sure the box is checked next to "UV Sets" in the export dialog?

In general, we get UVs when we export to USD. There are some gotchas in some situations (mostly around multiple UV sets) that you may find yourself needing to be aware of but otherwise, your UVs should be there.

**Comment by swamiforlife** [comment]
Sorry, i didn't word the issue correctly.
When I export a USD file it has the UV data inside it but when I import the USD file into Houdini or Katana the UV's will not show.
If I export a USD file from Houdini the UV's will correctly show in Katana.
So it seems to be how UV export is implemented in the Maya USD plugin that is causing this issue. 

Below is a link to a video showing the problem
https://youtu.be/oAcjVxudQFM

**Comment by kxl-adsk** [comment]
I wonder if it's related to https://github.com/Autodesk/maya-usd/pull/876. Did you try using MAYAUSD_EXPORT_MAP1_AS_PRIMARY_UV_SET and MAYAUSD_IMPORT_PRIMARY_UV_SET_AS_MAP1 to bring back the renaming behavior we had before?

**Comment by WallmanMark** [comment]
Hi.  As kxl said.  By changing the settings as above I can now get UV's in other apps.  Best  Mark

**Comment by kxl-adsk** [comment]
@swamiforlife did you have a chance to try it? If env variables solved your problem, I suggest we close this issue.

**Comment by swamiforlife** [comment]
@kxl-adsk yes it is working now with the env variables. So, you can close this issue.
Also in future releases will this env variable option exist or are there any plans for changing it?

**Comment by kxl-adsk** [comment]
It's too early to make any plans for removing it. Other USD consumers (importers, renderers) will have to follow and stop using hardcoded "st" name for UV.
