### ISSUE TITLE
cbegin/cend are only available in 2019 and later, making this fairly minor sanity check a breaking change

### ISSUE THREAD

**Issue by eoffermann** [Autodesk/maya-usd#1215]
https://github.com/Autodesk/maya-usd/blob/c820064d3ff4014aa3a0c81e9a15b720a6e1f64f/lib/usd/translators/jointWriter.cpp#L267-L272

As stated in the subject: MIntArray.cbegin/MIntArray.cend were introduced to the API in Maya2019 - if building against Maya2018, this simple debug code prevents the plugin from building. 

It would be a shame to halt support for 2018 for this.

**Comment by kxl-adsk** [comment]
You discovered something that I was planning to post a message on Discussions. We indeed are stopping official support for Maya 2018. I will go ahead and make this post right away.

**Comment by kxl-adsk** [comment]
The PR is open to fix Maya 2018 compilation. Past this, see https://github.com/Autodesk/maya-usd/discussions/1217 discussion.
