### ISSUE TITLE
AL's SIMD operations are disabled

### ISSUE THREAD

**Issue by HamedSabri-adsk** [Autodesk/maya-usd#122]
### Issue

AL's SIMD operations are wrapped by AL_UTILS_ENABLE_SIMD but I can't find a #define directive for it anywhere in the code base. 

### Specs

- All platforms ( Linux, MacOSX, Windows )
- affected branches: master, dev, refactoring_sandbox

**Comment by murphyeoin** [comment]
Hi @HamedSabri-adsk as discussed, this is probably just an omission - we can certaintly try and switch on again

**Comment by kxl-adsk** [comment]
Indeed it can be easily switched on...but then it has to support all platforms.

**Comment by vlasovi** [comment]
The issue seems obsolete, closing.
