### ISSUE TITLE
AETemplates use unsupported ufeSupport in Maya 2020

### ISSUE THREAD

**Issue by dgovil** [Autodesk/maya-usd#1238]
**Describe the bug**
When creating a USD Stage in Maya, the Attribute Editor errors with a failed import from https://github.com/Autodesk/maya-usd/commit/04eba857c3007b3af3c2b46f2f7ac7fcf3587ab3#diff-4766f35a32ff713eeced3da2ad76371ee864c08640cc1451f4974e4931c6cfa7 because it can't find `ufeSupport` in `maya.internal` .

According to https://github.com/Autodesk/maya-usd/blob/4ab1eb7a1f3e301dac19d7999d4d0c673ae9c991/test/testUtils/ufeUtils.py#L27 however, it seems this isn't supported.

However running the alternative in there also fails: `from ufeScripts import ufeSelectCmd` with a `No module named ufeScripts`

I don't see either ufeScripts or ufeSupport in either the 2020 devkit, or the maya-usd repo. Should we be grabbing a newer devkit that has one of these? or is this a 2021 thing and we should adjust the AE Templates to not import for 2020?

We'd only started hitting this recently as we're finally starting to enable UFE and Qt support as part of our builds.

**Steps to reproduce**
1. Go to Create>USD>Stage from File

**Expected behavior**

**Specs (if applicable):**
 - OS & version  macOS 11.2
 - Compiler & version  clang 11
 - Maya version  Maya 2020.3
 - Maya USD commit SHA  1b3256be8293992f0ec275d76aa210c57dae46a8
 - Pixar USD commit SHA  dc710925675f7f58f7a37f6c18d046a687b09271

**Comment by seando-adsk** [comment]
@dgovil Sorry about that, it is my mistake. I used some stuff that is not available in Maya 2020 and below. I've reopened our internal ticket and will rework this to support Maya 2020.

**Comment by dgovil** [comment]
Thanks @seando-adsk

**Comment by seando-adsk** [comment]
@dgovil I committed the fix, so this should now work correctly in Maya 2020. Please see PR #1242 for fix.

**Comment by dgovil** [comment]
Awesome. Thanks for the quick turnaround. Tested a build here and no longer getting the errors from above.
Cheers
