### ISSUE TITLE
[MAYA-110448] Referenced USD using wrong translator

### ISSUE THREAD

**Issue by ghostvfx-jimmy** [Autodesk/maya-usd#1244]
**Describe the bug**
When creating an USD reference in the reference editor it creates the reference, but when saving the maya scene it's the wrong "type".

**Steps to reproduce**
1. Create an USD reference using the reference editor.
2. Save the maya scene.
3. Re-open the maya scene and notice that the reference is not loaded.

I made a script that reproduces it :
```python
import maya.standalone
maya.standalone.initialize()
from maya import cmds
sphereFileName = "/tmp/sphere.usda"
mayaFileName = "/tmp/maya.ma"

cmds.loadPlugin("mayaUsdPlugin")

## Export sphere as USDA
cmds.file(new=True, force=True)
sphere = cmds.polySphere()
cmds.select(d=True)
cmds.select(sphere)
cmds.mayaUSDExport(file=sphereFileName, selection=True)

# Create a new scene and import the USD sphere as reference and save the maya scene
cmds.file(new=True, force=True)
cmds.file(sphereFileName, reference=True, type="USD Import", options="")
cmds.file(rename=mayaFileName)
cmds.file(save=True, type='mayaAscii')

# Reopen the scene
cmds.file(new=True, force=True)
cmds.file(mayaFileName, open=True)
refNode = cmds.file(sphereFileName, query=True, referenceNode=True)
print(cmds.file(query=True, referenceNode=refNode, deferReference=True))
```
This script should output False in the end (not defered)

**Expected behavior**
When you open the scene the reference is loading and working.

**Specs (if applicable):**
 - Linux
 - Maya 2020.4
 - Maya USD v0.8.0 (release from this site)

**Additional context**
When looking in the maya ascii scene the file translator type is set to "USD Export" and not "USD Import". If manually changed to "USD Import" it works when opening the scene, but is broken when saved again.

If the plugin is recompiled with the "USD Export" not registrered, the above script works, but no option to do "export selection" to USD.

**Comment by santosg87** [comment]
Thank you for reporting this!

we can also reproduce this issue internally. I went ahead and logged it on our internal database so we can investigate a bit deeper.

**Comment by santosd** [comment]
Hi @ghostvfx-jimmy, one of our devs had a look at this issue and made mention that something that may be a possible workaround is to use a .usd file. I Tested this on my end and if I use a .usda extension file it doesn't work, but it does work with a .usd file. Would you be able to test this out on your end and is it a viable workaround for the time being while we work to resolve the issue?

**Comment by ghostvfx-jimmy** [comment]
You're right. It does seem to work with `.usd`, but we use `.usda` quite alot for layout due to it's readability.

**Comment by santosd** [comment]
Hi @ghostvfx-jimmy, you should still be able to save an ascii version of a usd file with a .usd extension at least if you are creating them from within Maya. In export options you would set ascii format but save the file with a .usd extension:

![exportOptions](https://user-images.githubusercontent.com/29235905/113351044-4ca78300-9308-11eb-8a2f-876f1de31f04.png)

You should also actually also be able to change the extension of a .usda file to .usd and it shouldn't make affect the file.

I hope that helps.

**Comment by jacobvfx** [comment]
It would be great to get the bug fixed, as renaming files exported from other applications or coming in from other vendors doesn't really feel like a solution to this problem.

Any progress on this?

**Comment by tanant** [comment]
Slight late update, we've done some internal digging and we're exploring a couple different approaches to it, being careful mainly to avoid causing general side effects across the entire export/import translator framework, which would be bad.
