### ISSUE TITLE
[MAYA-109238] mtoh crashes on macOS when switching to Hydra GL with Maya geometry present

### ISSUE THREAD

**Issue by dgovil** [Autodesk/maya-usd#1283]
**Describe the bug**
When using the mtoh plugin with Maya, it causes an instant sigabrt when switching a viewport to the Hydra GL render if there's also Maya geometry in the scene.

I'm seeing if I can get to the source of it here, but I just wanted to file the issue in case others hit it or if Autodesk is either already looking into it or has some ideas about it.

We've tried this with Maya 2020, 2022 and the pre 2022 betas.

**Steps to reproduce**
1. Enable mtoh plugin
2. Switch viewport to Hydra GL
3. Create a polyCube

**Specs (if applicable):**
 - OS & version [e.g. Windows 10] macOSX Big Sur 11.2
 - Compiler & version [e.g. gcc 6.3.1] Clang 12
 - Maya version 2020, Beta, 2022
 - Maya USD commit SHA 8b00e510717e9339fe174b5e07bcfd0f607becc9
 - Pixar USD commit SHA https://github.com/PixarAnimationStudios/USD/commit/dc710925675f7f58f7a37f6c18d046a687b09271

**Comment by dgovil** [comment]
For reference, this is the crash stack with Maya 2020 and USD 21.02. It looks like it's crashing out in the HgiMetal pipeline.
[mtoh_stack.txt](https://github.com/Autodesk/maya-usd/files/6214672/mtoh_stack.txt)

**Comment by kxl-adsk** [comment]
Haven’t tried it yet, but by the sound of it I’m guessing it’s due to Hydra Storm that isn’t yet supported on macOS.

**Comment by santosg87** [comment]
if this is with Hydra Storm, i believe we have reproduced it internally, seems to be related to the AMD graphics.

**Comment by dgovil** [comment]
I believe some amount of Storm supports Metal from 20.08 onwards but not fully.

And yes, all the machines we were testing it on are AMD graphics. 

I'll be following up internally to see what the status is and when we can get this resolved. 

I just wanted to file the issue for tracking purposes (and visibility if others hit it) and to see if it was a documented issue with any workarounds.

**Comment by kxl-adsk** [comment]
Hgi refactoring has been landing in USD for some time now, but as far as I’m aware, this work hasn’t completed yet and there is no Storm support on macOS yet. Happy to be wrong here!

**Comment by dgovil** [comment]
Ah you're likely right. I haven't built USD from `release` with `UsdView` in a while. So everything was ahead of master etc...

**Comment by dgovil** [comment]
So just circling back, I did a build with Imaging enabled against USD 21.05 and 21.02 (didn't bother going further back because I'd need to rebuild a bunch of dependencies too ) and it does work (albeit with broken shading and materials) on a Mac

![image](https://user-images.githubusercontent.com/4443090/114651469-e112cd80-9c98-11eb-97ae-ee913cd973f3.png)

**Comment by wtelford** [comment]
@santosg87 can you link this to the internal jira issue?
