### ISSUE TITLE
Maya crashes when trying to exporting pxr usd

### ISSUE THREAD

**Issue by suekieza** [Autodesk/maya-usd#129]
Hey there,
When trying to export using pxr usd my Maya crashes. Here's the dump files
[dumpdata.zip](https://github.com/Autodesk/maya-usd/files/3878376/dumpdata.zip)
Heres a video of what that looks like when happening:
[2019-11-22 09-30-03.flv.tar.gz](https://github.com/Autodesk/maya-usd/files/3878403/2019-11-22.09-30-03.flv.tar.gz)
Thanks

**Comment by HamedSabri-adsk** [comment]
Thank you @suekieza. I will look into it. Is there a possibility to share the barrel asset?

**Comment by fowlertADSK** [comment]
And any chance the folder you're saving to is a symlink?

**Comment by suekieza** [comment]
Hey there,
Link to barrel
https://drive.google.com/drive/folders/1n1M5oM9TBzoY-vSCE-AXGviU1pRpSfyo?usp=sharing

Don't believe I'm using symlink

**Comment by HamedSabri-adsk** [comment]
@suekieza can you give me access to download it? I just requested access with my gmail account. Thanks

**Comment by suekieza** [comment]
Cool you have access now

**Comment by HamedSabri-adsk** [comment]
@suekieza I don't have access to my Linux machine today but I tried the workflow on Windows with the same export settings that you have in your video but can't reproduce the crash ( see attached video ). 

FWIW, this is a pretty light mesh object with clean topology. I will try to test it on other platforms when I get a chance.

[barrel_export_windows.zip](https://github.com/Autodesk/maya-usd/files/3880648/barrel_export_windows.zip)

**Comment by kxl-adsk** [comment]
@suekieza now that you have a new USD build with a matching compiler. Can you try it again?

**Comment by suesauer** [comment]
Let me take a look quick

**Comment by suesauer** [comment]
Worked fine now the miss matching devtoolset was the problem here as well.
