### ISSUE TITLE
Please update Build Requirements for Maya 2022

### ISSUE THREAD

**Issue by dgovil** [Autodesk/maya-usd#1296]
https://github.com/Autodesk/maya-usd/blob/dev/doc/build.md doesn't yet include Maya 2022.
It would be great if that was updated to include the exact requirements for Maya 2022 to complement the previous Maya versions.

**Comment by kxl-adsk** [comment]
Thank you for this reminder. It’s an oversight on our end (slight affected by the fact that we can’t disclose this prior the release)
