### ISSUE TITLE
[MAYA-111084] Layer Editor save icon missing when Interface Scaling is 125%

### ISSUE THREAD

**Issue by mike1158** [Autodesk/maya-usd#1316]
**Describe the bug**
When Maya's Interface Scaling setting is set to 125%, the Layer Editor's save icon is missing and the following messages appear on startup:
```
Could not create pixmap from :/UsdLayerEditor/LE_save_all_125.png
Could not create pixmap from :/UsdLayerEditor/LE_save_all_125.png
Could not create pixmap from :/UsdLayerEditor/LE_save_all_pressed_125.png
```

**Steps to reproduce**
Set Maya's Interface Scaling setting to 125%

**Attachments**
It looks like icons are included for the other three custom scaling settings, just not 125%:
```
# grep -r LE_save_all .
./lib/usd/ui/layerEditor/resources.qrc:        <file alias="LE_save_all_100.png">resources/save_all_100.png</file>
./lib/usd/ui/layerEditor/resources.qrc:        <file alias="LE_save_all_150.png">resources/save_all_150.png</file>
./lib/usd/ui/layerEditor/resources.qrc:        <file alias="LE_save_all_200.png">resources/save_all_200.png</file>
```

**Comment by santosd** [comment]
Hello @mike1158, Thank you for reporting this issue. I have taken a look and have been able to reproduce the issue on our end. I will review the issue with the team to schedule it to be fixed.

**Comment by santosg87** [comment]
@mike1158 this one should be fixed with https://github.com/Autodesk/maya-usd/pull/1408.
