### ISSUE TITLE
Can I change pointInstance in Maya, after instance usd file load

### ISSUE THREAD

**Issue by cgTD123** [Autodesk/maya-usd#1322]
**Describe the bug**

**Steps to reproduce**

**Expected behavior**

**Attachments**
If applicable, add screenshots, sample files, etc to help explain your problem.

**Specs (if applicable):**
 - OS & version [e.g. Centos7]
 - Compiler & version [e.g. gcc 6.3.1]
 - Maya version [e.g. Maya 2019]
 - Maya USD commit SHA [e.g. dev at caa921c1]
 - Pixar USD commit SHA [e.g. dev at b85ddac2]

**Additional context**

**Comment by santosg87** [comment]
hi there, Sorry. I don't think i understand much of the issue. are you looking at selection? or changing the instances? I would recommend moving this to a discussion, as it seems you have a question that needs a bit more info? :)

cheers!
