### ISSUE TITLE
[MAYA-114699] Can´t import animations from a usdz model downloaded for ios.

### ISSUE THREAD

**Issue by Vdal1989** [Autodesk/maya-usd#1327]
I have the last version o maya-usd plugin ("Version 0.9.0") and I can´t import animations from a usdz model downloaded for ios. With the version "Version 0.8.0" when I created a stage from file "usdz" and saw a node called "All_Animations" in the Outliner with some information about animations. But now this node is empty and if I create a a stage from a file "usdz" I have no see any mesh.
This is the log when I tried to create a stage from file usdz

file -f -new;
// untitled // 
commandPort -securityWarning -name commandportDefault;
onSetCurrentLayout "Maya Classic";
// Loading Bifrost version 2.2.1.0-202102081428-b33b49f
// Bifrost: Loading library: Amino, from: Autodesk.
// Bifrost: Loading library: AminoMayaTranslation, from: Autodesk.
// Bifrost: Loading library: bif, from: Autodesk.
// Bifrost: Loading library: bifrostObjectMayaTranslations, from: Autodesk.
// Bifrost: Loading library: geometries, from: Autodesk.
// Bifrost: Loading library: fluids, from: Autodesk.
// Bifrost: Loading library: particles, from: Autodesk.
// Bifrost: Loading library: file, from: Autodesk.
// Bifrost: Loading library: midgard, from: Autodesk.
// Bifrost: Loading library: modeling, from: Autodesk.
// Bifrost: Loading library: nucleus, from: Autodesk.
// Bifrost: Loading library: simulation, from: Autodesk.
// Bifrost: Loading library: riv_types, from: Autodesk.
// Bifrost: Loading library: riv, from: Autodesk.
// Bifrost: Loading library: scatter_pack, from: Autodesk.
// Warning: file: C:\Users\lvidal\Documents\maya\2022\prefs\filePathEditorRegistryPrefs.mel line 4: filePathEditor: Attribute 'aiImage.filename' is invalid or is not designated 'usedAsFilename'. // 
// Warning: file: C:\Users\lvidal\Documents\maya\2022\prefs\filePathEditorRegistryPrefs.mel line 5: filePathEditor: Attribute 'aiPhotometricLight.aiFilename' is invalid or is not designated 'usedAsFilename'. // 
// Warning: file: C:\Users\lvidal\Documents\maya\2022\prefs\filePathEditorRegistryPrefs.mel line 6: filePathEditor: Attribute 'aiStandIn.dso' is invalid or is not designated 'usedAsFilename'. // 
// Warning: file: C:\Users\lvidal\Documents\maya\2022\prefs\filePathEditorRegistryPrefs.mel line 7: filePathEditor: Attribute 'aiVolume.filename' is invalid or is not designated 'usedAsFilename'. // 
// AbcExport v1.0 using Alembic 1.7.5 (built Nov 30 2020 18:40:46)
evalDeferred "shaderBallRendererMenuUpdate";
// Warning: line 1: filePathEditor: Attribute 'aiStandIn.dso' and label 'Standin' have been saved already. // 
// Warning: line 1: filePathEditor: Attribute 'aiVolume.filename' and label 'VDB' have been saved already. // 
// Warning: line 1: filePathEditor: Attribute 'aiImage.filename' and label 'Image' have been saved already. // 
// Warning: line 1: filePathEditor: Attribute 'aiPhotometricLight.aiFilename' and label 'IES' have been saved already. // 
import arnold
// Successfully imported python module 'arnold'
import mtoa
// Successfully imported python module 'mtoa'
import mtoa.cmds.registerArnoldRenderer;mtoa.cmds.registerArnoldRenderer.registerArnoldRenderer()
// Successfully registered renderer 'arnold'
updateRenderOverride;
// Warning: file: C:/Program Files/Autodesk/Maya2022/scripts/startup/autoLoadPlugin.mel line 40: Loading plug-in "mtoa" has resulted in changes to the scene that may need to be saved. // 
// AbcImport v1.0 using Alembic 1.7.5 (built Nov 30 2020 18:40:46)
updateRendererUI;
// Warning: Ill-formed SdfPath <D:\Borrar\usdz\zip\0>: syntax error // 
// Warning: Velociraptor_iosShape: Shape primPath <> is not a descendant of input stage primPath </> // 
// Warning: Found binding property </Velociraptor_2/SkinnedMeshes/Bone_GSRT/Bone_Root/skeleton__0/Velociraptor_mesh.primvars:skel:jointIndices>, but the SkelBindingAPI was not applied on the owning prim. In the future, binding properties will be ignored unless the SkelBindingAPI is applied (see UsdSkelBindingAPI::Apply) // 
// Warning: Found binding property </Velociraptor_2/SkinnedMeshes/Bone_GSRT/Bone_Root/skeleton__0/Velociraptor_mesh.primvars:skel:jointWeights>, but the SkelBindingAPI was not applied on the owning prim. In the future, binding properties will be ignored unless the SkelBindingAPI is applied (see UsdSkelBindingAPI::Apply) // 
// Error: Unsupported prim type: extComputation -- Coding Error in InsertPrim at line 100 of S:\jenkins\workspace\ecg-usd-full-python3-windows\ecg-usd-build\usd\pxr\imaging\hd\primTypeIndex.cpp // 
// Error: Unsupported prim type: extComputation -- Coding Error in InsertPrim at line 100 of S:\jenkins\workspace\ecg-usd-full-python3-windows\ecg-usd-build\usd\pxr\imaging\hd\primTypeIndex.cpp // [](url)

**Comment by santosg87** [comment]
thanks for logging this. would you be able to attach a sample file that we can use to try and narrow down things? I have tried a few of the Apple USdz Gallery files, and i see animation as expected. 

Cheers!

**Comment by Vdal1989** [comment]
> 
> 
> thanks for logging this. would you be able to attach a sample file that we can use to try and narrow down things? I have tried a few of the Apple USdz Gallery files, and i see animation as expected.
> 
> Cheers!

Of course. Here is the model. https://drive.google.com/file/d/1dVHizaFmZqo70i56dkeED5LVZPD_3fGZ/view?usp=drivesdk
Thanks for your atention

**Comment by santosg87** [comment]
thanks vdal. we can reproduce this on our side as well. It seems to be something on how the animation is indexed. 

I am investigating a bit deeper to see what could be specific issue causing the animation to be lost.

**Comment by Vdal1989** [comment]
Okay, thank you for investigating this issue. I tried importing this model into SimLab Composer software and import the animation without any problem. Hope you can solve this issue

**Comment by wtelford** [comment]
@santosg87 Can you please log this internally.
