### ISSUE TITLE
Standard Surface materials exporting IOR with incorrect values

### ISSUE THREAD

**Issue by dgovil** [Autodesk/maya-usd#1343]
**Describe the bug**
In the attached file, if you export the scene with materials, the Standard Surface material will export with an IOR of 50 regardless of the value set on the material.

In this particular scene, IOR is set to 1.43

**Steps to reproduce**
1. Export scene
2. Inspect standardSurface2 material. 
3. Compare IOR value

**Expected behavior**
IOR should be 1.43 not 50

**Attachments**
[maya_ior_bug.zip](https://github.com/Autodesk/maya-usd/files/6327954/maya_ior_bug.zip)

**Specs (if applicable):**
 - macOS Big Sur
 - Clang 12
 - Maya 2022
 - Maya USD commit SHA 33bfffa161fa1bd9fdbd1bece817a068083b456f
 - Pixar USD : vanilla 21.05

**Comment by ysiewappl** [comment]
Just to provide some context, we've identified the code that writes this out here:

From `lib/usd/translators/shading/usdStandardSurfaceWriter.cpp`:

```
    if (status == MS::kSuccess && UsdMayaUtil::IsAuthored(metalnessPlug)) {
        AuthorShaderInputFromShadingNodeAttr(
            depNodeFn,
            _tokens->metalness,
            shaderSchema,
            PxrMayaUsdPreviewSurfaceTokens->MetallicAttrName,
            usdTime);
        // IOR value from Gold USDPreviewSurface preset
        shaderSchema
            .CreateInput(PxrMayaUsdPreviewSurfaceTokens->IorAttrName, SdfValueTypeNames->Float)
            .Set(50.0f, usdTime);
```

But wanted to get clarification on why, if the user elects to author metalness, that the IOR is set to a value of `50` automatically. I can understand this being the case if it was authored explicitly (i.e. non-zero). But if a texture map is connected (which is the case here), then setting it automatically seems to be an incorrect choice?

**Comment by JGamache-autodesk** [comment]
Looks like debugging code I forgot to remove. Should not be there. Feel free to submit a fix since the viewport now works correctly with metallic surfaces thanks to the update you did recently.
