### ISSUE TITLE
User-friendly UI to de-instance models

### ISSUE THREAD

**Issue by dj-mcg** [Autodesk/maya-usd#1345]
Pixar TDs will often want to expose the guts of a USD-based model in order to interact with subcomponents. In the UFE world, TDs will need to disable "instanceable" via the Attribute Editor. It would be nice if this toggle was included in the Context Menu when right-clicking models in the Outliner, if this is in line with the UX experience that the Autodesk designers are trying to provide.

**Comment by dj-mcg** [comment]
Hi Will,

Thanks for the response! This request was specifically for a more user-friendly way to de-instance, to avoid requiring users from having to jump into the AE. Users have requested this be available in the Outliner context menu when right-clicking a model. Just a quality-of-life request - I was thinking of taking a crack at this myself, perhaps next week, but I wanted to make sure I wasn't stepping on any design/UX toes. 

Thanks
Dan

**Comment by womanyoyoyo-adsk** [comment]
Hi Dan,

Thanks for checking in to see if this lines up with our UX experience. I understand how your TDs would like a quicker and more user-friendly way to de-instance prims. I made a quick mockup. I grouped the attribute (Visibility) and the metadata (Deactivation and Instanceable) together. It's true we don't want this menu to explode. We've already made a decision to hard-code Instanceable in the Attribute Editor as one of four common metadatum at the top for convenience. Following this paradigm for the Outliner makes sense. ‘Mark as Instanceable’ would change to ‘Unmark as Instanceable’ when on a prim that is already marked as Instanceable. Would this work for your TDs?

![outliner_instanceable](https://user-images.githubusercontent.com/49446314/115920861-c256c880-a448-11eb-8e29-37ac6525202e.png)

Thanks,
Natalia (designer on Maya-USD)

**Comment by dj-mcg** [comment]
Hi Natalia,

Yep! That looks exactly like what we were thinking. Thanks so much for
mocking it up. If you feel like it is in line with the overall design
approach you would like to take, I could try to get to this myself at some
point soon. If someone on the Autodesk side wants to run with it, just let
me know -- thanks!

Dan

**Comment by womanyoyoyo-adsk** [comment]
Hi Dan,

No problem, I am happy to help with UX. This is in line with the overall design. We currently we don't have this work scheduled. If you'd like you can give this a go. Let me know if you need any other help.

Thanks,
Natalia
