### ISSUE TITLE
Maya 2022 links to missing Python on Big Sur, causing CMake builds to fail

### ISSUE THREAD

**Issue by dgovil** [Autodesk/maya-usd#1351]
Maya 2022 symlinks to Python 3.7 on Big Sur. I believe Maya 2022 is built on Catalina where this is possible, but this is not the case on Big Sur.

The [python.cmake](https://github.com/Autodesk/maya-usd/blob/dev/cmake/python.cmake) file tries to find the python3 file at this path `Maya.app/Contents/Frameworks/Python.framework/Versions/Current/bin/python3` and errors out during build because it can't execute it further down.

Setting this to point to `mayapy` doesn't seem to satisfy CMake either, because the default CMake `FindPython.cmake` does not respect `mayapy` as a valid interpreter name.

A simple fix on our end has been to modify `python.cmake` in our internal fork of this repo and adding this at the head, and passing in `-DMAYAPY_PATH=path/to/mayapy` to CMake. This short circuits the logic in the file and lets us work through the builds successfully.

```cmake
if(DEFINED MAYAPY_PATH)
    MESSAGE(STATUS "Setting Python_EXECUTABLE to MayaPy ${MAYAPY_PATH}")
    set(Python_EXECUTABLE ${MAYAPY_PATH})
    set(Python_Interpreter_FOUND TRUE)
    return()
endif()
```

While this unblocks us internally, I do think it's perhaps an issue that could be wider addressed in the main CMake definition for this project to simply accept mayapy as the project. I also think this will be problematic long term (in general) for Maya's python libraries to assume that the OS bundles Python anymore to symlink against, since that's not a safe assumption anymore.

**Comment by wayne-arnold-adsk** [comment]
the embedded Python 3.7.7 in Maya is from python.org  I had thought that the internal library dependencies had been changed to make the embedded relocatable.  stills its not.

a workaround would be to install Python 3.7.7 from python.org to satisfy the dependencies.   just a workaround.   the issue has been entered to look at what can be done on the Maya side.  

Maya itself doesn't show the issue as use of DYLD_LIBRARY_PATH overrides where the libraries are located
