### ISSUE TITLE
Multiple segfaults on CentOs7 with refactoring_sandbox

### ISSUE THREAD

**Issue by radon199** [Autodesk/maya-usd#136]
Hey,

We have been attempting to build the refactoring sandbox but have been unable to get a functional plugin after many attempts. We are able to build the Pixar plugin along with our 19.11 core without any issues.

We are using : maya_usd fork from November 20th, UFE enabled, Usd 19.11, Maya 2019.2.8774, CentOs7.6, Nvidia GTX1080ti with driver 390.77 and 430.50

We have built both the Adsk and AL plugins. The 

**Adsk proxy does not draw in the viewport**
When we create an Autodesk proxy it does not draw in Viewport 2.0. The bounding box of the proxy does populate with the correct values. The population of the subcomponents from UFE is random, sometimes it happens and sometimes it doesn't. Changing the proxy to a new usd file does not refresh the subcomponents and they stay the way they were before. Expanding the transform node to show the Shape causes the subcomponents to disappear and reappear every time to transform is toggled.
We can get the proxy to draw in the viewport and update it's subcomponents by duplicating it, but then selecting any mesh in the viewport or outliner causes a segfault : 
**UPDATED : This still happens with the fix but the proxy also loads properly when loading a Maya scene with an existing proxy. It however still doesn't allow us to switch stages without a reload.**
[select_duplicated_proxy.20191126.1318.crash.txt](https://github.com/Autodesk/maya-usd/files/3894071/select_duplicated_proxy.20191126.1318.crash.txt)

**Selecting prims with the AL_Proxy causes a segfault**
~~The AL_UsdMaya proxy is more stable than the adsk one, when created it draws in Viewport 2.0 and properly creates it's subcomponents in the Outliner. However when the proxy is pointed to a new layer path it does not redraw, and only the subcomponents are updated.
Selecting the AL proxy in the viewport or outliner crashes with a similar stack trace to the one above from the Adsk plugin.~~
**RESOLVED : Caused by not using the same GCC version between usd and maya_usd.**
[select_AL_proxy.20191126.1336.crash.txt](https://github.com/Autodesk/maya-usd/files/3894105/select_AL_proxy.20191126.1336.crash.txt)

**Switching to the GL renderer segfaults**
~~Switching to the GL ( or Embree ) render delegate causes a segfault regardless of if there is a adsk proxy in the scene or not.~~
*UPDATED : This segfault has gone but we now get one related to MtlX.**
[switch_to_GL_renderer.20191126.1328.crash.txt](https://github.com/Autodesk/maya-usd/files/3894082/switch_to_GL_renderer.20191126.1328.crash.txt)

**Loading a layer with instancing crashes both the Adsk and AL proxy**
~~As the title says this happens with both the adsk and al proxy. When importing a layer with instanced prims it will crash. I am unable to get a Maya crash log from this and have to use a debugger to catch it.~~
**RESOLVED : Caused by not using the same GCC version between usd and maya_usd.**
[load_layer_with_instancing.txt](https://github.com/Autodesk/maya-usd/files/3894131/load_layer_with_instancing.txt)

The trend of all of these seem to be the interface between the the plugin and the viewport. I'm not sure exactly what we are doing wrong here. As I said we have been building USD for a while and the Maya plugin from 19.11 built against the same core has no issues.

**Comment by suekieza** [comment]
I too have issues on centos 7 https://github.com/Autodesk/maya-usd/issues/98

**Comment by radon199** [comment]
On the issue : **Loading a layer with instancing crashes both the Adsk and AL proxy**

If I set the Usd work threading to 1 with **PXR_WORK_THREAD_LIMIT**=1 then loading the stage with the AL proxy does not crash, but it also doesn't present the correct stage. Instead I get everything rendering without their transforms at the origin.

I also get the coding error : 
`Coding Error: in GetInstancerDirtyBits at line 341 of /sw/dev/rousselp/src/MTCR/usd/build/platform-linux/arch-x86_64/os-CentOS-7/boost-1.61.0/python-2.7/pyside-2.0.0/ptex/qt_devel/usd/src/usd/pxr/imaging/lib/hd/changeTracker.cpp -- Failed verification: ' it != _instancerState.end() '
`

Opening the same layer in usdview with or without the multi-threading the layer draws as expected with instances in the proper location.

**Comment by radon199** [comment]
On that note, all segfaults seem to occur when either a std::unordered_map or a TfHashMap are being accessed.

Issue 1 and 2: HdSelection::AddRprim is adding a selection and path to a std::unordered_map

Issue 3: HdChangeTracker::AddCollection is finding and then adding a collection to a TfHashMap.

Issue 4: HdChangeTracker::GetInstancerDirtyBits is finding a id in a TfHashMap.

**Comment by radon199** [comment]
I'll add one more.

**Creating a Adsk proxy with VP2_RENDER_DELEGATE_PROXY=0 causes a segfault**
If we have this env variable off Maya with crash as soon as we attempt to make even a single Adsk proxy. The crash doesn't happen with an Al proxy.
[VP2_RENDER_DELEGATE_PROXY_OFF.20191129.1334.crash.txt](https://github.com/Autodesk/maya-usd/files/3906419/VP2_RENDER_DELEGATE_PROXY_OFF.20191129.1334.crash.txt)

**Comment by kxl-adsk** [comment]
Regarding segfaults with containers - it is necessary to compile both usd and maya-usd with the same compiler and same compiler settings. Is it possible that usd binaries were not built by you?

**Comment by suesauer** [comment]
Can you build USD with devtoolset 6? They way usd-maya is?

**Comment by kxl-adsk** [comment]
Yes, you can and should build both with devtoolset 6 (we use 6.3.1). Having a mismatch could explain some crashes you are experiencing.

**Comment by suekieza** [comment]
That seemed to do the trick thanks @kxl-adsk \:D/
![Screenshot from 2019-12-03 15-12-36](https://user-images.githubusercontent.com/53234220/70059635-cda61b80-15e9-11ea-8dcc-15e65088d3af.png)

**Comment by kxl-adsk** [comment]
@radon199 can you try to do the same?

**Comment by radon199** [comment]
Hey,

So better results! Building usd and maya_usd with different gcc versions appears to have been causing the majority of the crashes.

One that didn’t go away was the Autodesk Proxy drawing correctly right away. When inputting a USD path into the proxy nothing draws, however I found it would draw if duplicated OR if the scene is saved and reopened. Swapping out the USD path on the proxy when it is drawing also doesn’t switch it to the new USD stage. I have to save and reopen the Maya file in order to make it update.

I’m not sure if this is still a configuration issue on our side or not.

**Comment by kxl-adsk** [comment]
Please log the drawing issue separately and close this ticket. It will help focus discussion on a specific subject and avoid having to read outdated comments.
