### ISSUE TITLE
mayaUSDExport is exporting mesh with no subdivision scheme

### ISSUE THREAD

**Issue by mhamid3d** [Autodesk/maya-usd#1362]
I've run the following code to export a selected mesh in maya:

```
import maya.cmds as mc


mc.mayaUSDExport(
    file='/home/mhamid/Documents/usd_test/walkman_v001.usd',
    chaser=['alembic'],
    chaserArgs=[
        ('alembic', 'primvarprefix', 'CMT_=CMT_')
    ],
    shadingMode='none',
    selection=True,
    kind='component',
    exportDisplayColor=True,
    defaultMeshScheme='catmullClark'
)
```

Upon inspecting the resulting usd file in usdview, the subdivisionScheme attribute is set to none. However when using the File-->Export Selection gui in Maya, with the same export options as the python command, it will export with catmullClark subdivisionScheme. Keep in mind none of the shapes have any USD_* attributes, so they are not being overridden anywhere.

Maya 2022
USD v21.05
maya-usd v0.9.0

**Comment by santosd** [comment]
Hello @mhamid3d, I gave this a try on my end in 2022 and in PR124 and I was not able to replicate the issue.  I used your above command however, without the chaser args. When I create a stage using the file I exported from Maya, I see that the Subdivision Scheme is set to catmullClark. Attached is the file I saved it as .txt to be able to attach it but feel free to change the extension back to .usda. This is the file I exported using your command and notice when you create a stage that catmullClark is set as the Subdivision Scheme.

Let me know if I am missing anything.

[ncloth_USDExport_2022.txt](https://github.com/Autodesk/maya-usd/files/6386729/ncloth_USDExport_2022.txt)

**Comment by mhamid3d** [comment]
Hi @santosd , removing the chaser would solve the problem with the subdivisionScheme, but we need the chaser in order to export out prefixed primvars. So this is technically still considered a bug. If you have the pxrUsd plugin, would you mind testing it out on your end?

Thanks a lot

**Comment by mhamid3d** [comment]
Hi @santosd , I came across another thing. The UV's are not being written out when using the alembic chaser, but they export perfectly fine without the chaser. So I'm just wondering why the export behaves so differently with the chaser? The only feature I want from the chaser is exporting primvars with a prefix. Is there perhaps another way to do it then?

**Comment by dgovil** [comment]
@mhamid3d I have a discussion here about the ability to export custom data: https://github.com/Autodesk/maya-usd/discussions/896

Unfortunately the only other solutions I know off, (assuming you can't get the alembic chaser working appropriately) of the top of my head are:

1. Write a custom export chaser
2. Use the Pixar export UI to manually define the attributes https://github.com/Autodesk/maya-usd/blob/595df7fea82c4d282d63cb7065962b4ed7d2dede/plugin/pxr/doc/README.md#specifying-arbitrary-attributes-for-export

**Comment by ysiewappl** [comment]
@mhamid3d The culprit for your issue is probably here, in `alembicChaser.cpp`:

```
// alembic by default sets meshes to be poly unless it's explicitly set to be
// subdivision.  UsdExport makes meshes catmullClark by default.  Here, we
// implement logic to get set the subdivision scheme so that it matches.
static void _SetMeshesSubDivisionScheme(
    UsdStagePtr                                                     stage,
    const UsdMayaExportChaserRegistry::FactoryContext::DagToUsdMap& dagToUsd)
{

    for (const auto& p : dagToUsd) {
        const MDagPath& dag = p.first;
        const SdfPath&  usdPrimPath = p.second;
        if (!dag.isValid()) {
            continue;
        }

        MStatus status;
        MFnMesh meshFn(dag, &status);
        if (!status) {
            continue;
        }

        if (UsdGeomMesh usdMesh = UsdGeomMesh::Get(stage, usdPrimPath)) {
            MPlug plug = meshFn.findPlug("SubDivisionMesh");
            bool  isSubDivisionMesh = (!plug.isNull() && plug.asBool());

            if (!isSubDivisionMesh) {
                usdMesh.GetSubdivisionSchemeAttr().Set(UsdGeomTokens->none);
            }
        }
    }
}
```

I would advise trying to see if your mesh in question has a `SubDivisionMesh` attribute. That would be the most likely reason your subdivision scheme is being reset to `none` when you export using the Alembic chaser. The other alternative for you is simply removing the call to this function in `ExportDefault()` of the Alembic chaser and re-compiling the plugin for your specific needs.

**Comment by mhamid3d** [comment]
@ysiewappl Sorry for the late reply, I can confirm that adding the attribute `SubDivisionMesh` does work! This also means I don't need the alembic chaser anymore, and for additional attributes I will just use the post callback method. Thanks a lot!

**Comment by wtelford** [comment]
It sounds like this issue is resolved with the SubDivisionMesh attribute resolves this issue. Closing for now. Please reopen if this needs further attention.
