### ISSUE TITLE
Can't load USD plugin in Maya 2022

### ISSUE THREAD

**Issue by BrianHanke** [Autodesk/maya-usd#1389]
**Describe the bug**

I'm unable to load any version of the USD plugin in Maya 2022. Neither the one that comes with Maya (0.8) or the most recent 0.9 build work.

**Steps to reproduce**
1. Go to plugin manager
2. Click check box next to MayaUsdPlugin.mll
3. Error message: 

```
// Error: file: C:/Program Files/Autodesk/Maya2022/scripts/others/pluginWin.mel line 316: Unable to dynamically load : C:/Program Files/Autodesk/MayaUSD/Maya2022/0.9.0_202103310341-8b4f782/mayausd/MayaUSD3/plugin/adsk/plugin/mayaUsdPlugin.mll
The specified procedure could not be found.
 // 
// Warning: [mtoa] Error loading extension library: The specified procedure could not be found.
 // 
// Error: [mtoa] Deleting Extension usdProxyShapeTranslator .Unable to load library: (C:/Program Files/Autodesk/Arnold/maya2022/extensions/usdProxyShapeTranslator.dll) // 
// Error: file: C:/Program Files/Autodesk/Maya2022/scripts/others/pluginWin.mel line 316: The specified procedure could not be found.
 (mayaUsdPlugin) // 
```

**Expected behavior**

Expect the plugin to load.

**Specs (if applicable):**
 - Windows 10
 - Maya 2022

**Additional context**
I don't have any fancy plugins or extras in Maya, just a few custom shelves. Even a totally vanilla install gives me the same error. I want to experiment with transferring USD files from Houdini Solaris to Maya, but I'm not having any success here.

**Comment by HamedSabri-adsk** [comment]
@BrianHanke My guess would be that you have conflicting PYTHONPATH or PATH to USD somewhere in your ENV variable?

Could you post what you have in your env settings?

**Comment by BrianHanke** [comment]
Thanks for the reply. I don't have anything Python- or USD-related in Maya.env or my Windows path. See below:

```
OCIO=C:\Users\Brian\OneDrive\3D Materials\OCIO\brian.ocio
MAYA_CM_DISABLE_ERROR_POPUPS=1
```
![path](https://user-images.githubusercontent.com/59420805/117153021-93b1e980-ad88-11eb-9f47-0228f0c23ab5.png)

**Comment by hamedsabri** [comment]
@BrianHanke Thanks. Your env settings looks good to me.  Do you by any chance have any traces of older versions of MayaUsd installed on your machine?

**Comment by BrianHanke** [comment]
@hamedsabri I don't think so. I did have the 0.8 release installed, but I removed it before trying 0.9. I suppose there might be a lingering registry entry or temp folder somewhere. This is pretty much a fresh Maya 2022 install. Last week I had trouble with the license and did a total wipe of all Autodesk stuff and had help fixing it from AD support after that. Everything is working fine now except for USD. My Houdini Solaris implementation of USD is solid. By the way, I just checked my other desktop computer and it throws the same error trying to load MayaUSD. Apparently I'm cursed!

**Comment by dgovil** [comment]
I'm not sure if it's the case on Windows, but for me on Mac, I get that
error but the plugin does load. i.e I can still export and do all the usual
USD tasks.

One thing you might try is loading Maya without Arnold, then load the Maya
plugin, and then load Arnold after. Something about the combination of the
two seems problematic

**Comment by BrianHanke** [comment]
@dgovil It's definitely not loading. The checkbox immediately unchecks itself after I try to load in the plugin manager. I also tried setting the USD stuff to autoload and turned off Arnold autoload, but that didn't help. I was snooping around the MayaUSD install folder and found this in mayausd.mod. Seems rather empty, no? Is %MAYA_PYTHON_VERSION% set somewhere? It's not in my system path or in Maya.env.

```
+ USD 0.20.11-gold-take2 mayausd/USD%MAYA_PYTHON_VERSION%
icons: 
plug-ins: 
presets: 
scripts: 
resources: 
PYTHONPATH+:=lib/python
PATH+:=bin
PATH+:=lib
USD_LOCATION:=
MAYA_USD_VERSION=0.20.11-gold-take2

+ MayaUSD_LIB 0.9.0 mayausd/MayaUSD%MAYA_PYTHON_VERSION%
icons: lib/icons
plug-ins: 
presets: 
scripts: 
resources: 
PATH+:=lib
PYTHONPATH+:=lib/python
PXR_PLUGINPATH_NAME+:=lib/usd
MAYAUSD_VERSION=0.9.0


+ MayaUSD 0.9.0 mayausd/MayaUSD%MAYA_PYTHON_VERSION%/plugin/adsk
plug-ins: plugin

+ MTOH 0.9.0 mayausd/MayaUSD%MAYA_PYTHON_VERSION%/lib
icons: 
plug-ins: maya
presets: 
scripts: 
resources: 
```

**Comment by HamedSabri-adsk** [comment]
@BrianHanke MAYA_PYTHON_VERSION is Maya CMake flag that we use for switching between python (Python2 or 3).

You shouldn't need to manually change the mod file. %MAYA_PYTHON_VERSION% should be populated automatically 
to "2" or "3" based on the Python version of your Maya. Maya 2022 is Python 3 only. 

Could you run this MEL command in Maya and see what it prints?

`getenv("MAYA_PYTHON_VERSION");`

Not that you need to but try setting "MAYA_PYTHON_VERSION" to 3 in your env setting and see if it helps.

**Comment by BrianHanke** [comment]
@HamedSabri-adsk Ran the MEL command, confirmed Python v3. Adding that line to Maya.env didn't help. Here's a list of my autoload plugins. Any potential conflicts in there? By the way, I also tried installing Maya 2020 and a 2020-compatible version of the plugin and even there it gives the same error.

```
evalDeferred("autoLoadPlugin(\"\", \"invertShape\", \"invertShape\")");
evalDeferred("autoLoadPlugin(\"\", \"mayaHIK\", \"mayaHIK\")");
evalDeferred("autoLoadPlugin(\"\", \"curveWarp\", \"curveWarp\")");
evalDeferred("autoLoadPlugin(\"\", \"tiffFloatReader\", \"tiffFloatReader\")");
evalDeferred("autoLoadPlugin(\"\", \"MASH\", \"MASH\")");
evalDeferred("autoLoadPlugin(\"\", \"poseInterpolator\", \"poseInterpolator\")");
evalDeferred("autoLoadPlugin(\"\", \"hairPhysicalShader\", \"hairPhysicalShader\")");
evalDeferred("autoLoadPlugin(\"\", \"ikSpringSolver\", \"ikSpringSolver\")");
evalDeferred("autoLoadPlugin(\"\", \"ik2Bsolver\", \"ik2Bsolver\")");
evalDeferred("autoLoadPlugin(\"\", \"xgenToolkit\", \"xgenToolkit\")");
evalDeferred("autoLoadPlugin(\"\", \"AbcExport\", \"AbcExport\")");
evalDeferred("autoLoadPlugin(\"\", \"sweep\", \"sweep\")");
evalDeferred("autoLoadPlugin(\"\", \"OpenEXRLoader\", \"OpenEXRLoader\")");
evalDeferred("autoLoadPlugin(\"\", \"Unfold3D\", \"Unfold3D\")");
evalDeferred("autoLoadPlugin(\"\", \"mayaCharacterization\", \"mayaCharacterization\")");
evalDeferred("autoLoadPlugin(\"\", \"Type\", \"Type\")");
evalDeferred("autoLoadPlugin(\"\", \"mtoa\", \"mtoa\")");
evalDeferred("autoLoadPlugin(\"\", \"modelingToolkit\", \"modelingToolkit\")");
evalDeferred("autoLoadPlugin(\"\", \"meshReorder\", \"meshReorder\")");
evalDeferred("autoLoadPlugin(\"\", \"rotateHelper\", \"rotateHelper\")");
evalDeferred("autoLoadPlugin(\"\", \"MayaMuscle\", \"MayaMuscle\")");
evalDeferred("autoLoadPlugin(\"\", \"matrixNodes\", \"matrixNodes\")");
evalDeferred("autoLoadPlugin(\"\", \"AbcImport\", \"AbcImport\")");
evalDeferred("autoLoadPlugin(\"\", \"autoLoader\", \"autoLoader\")");
evalDeferred("autoLoadPlugin(\"\", \"sceneAssembly\", \"sceneAssembly\")");
evalDeferred("autoLoadPlugin(\"\", \"gpuCache\", \"gpuCache\")");
evalDeferred("autoLoadPlugin(\"\", \"objExport\", \"objExport\")");
evalDeferred("autoLoadPlugin(\"\", \"ufeSupport.py\", \"ufeSupport\")");
evalDeferred("autoLoadPlugin(\"\", \"ArubaTessellator\", \"ArubaTessellator\")");
evalDeferred("autoLoadPlugin(\"\", \"mayaVnnPlugin\", \"mayaVnnPlugin\")");
evalDeferred("autoLoadPlugin(\"\", \"quatNodes\", \"quatNodes\")");
evalDeferred("autoLoadPlugin(\"\", \"fbxmaya\", \"fbxmaya\")");
```

**Comment by BrianHanke** [comment]
Update: forget the Maya plugin, I can't even run usdview. At first it gave me an error about PySide2. I installed the most recent release of Python and ran pip install PySide2. That cleared up that error, but now I've got this one. Seems to be there's a fundamental problem with the USD installation?

```
PS C:\Program Files\Autodesk\MayaUSD\Maya2022\0.9.0_202103310341-8b4f782\mayausd\USD3\bin> ./usdview "C:\Users\Brian\OneDrive\ZBrush\Rosangela\scenes\usd\main\karma_main.usd"
Traceback (most recent call last):
  File "C:\Program Files\Autodesk\MayaUSD\Maya2022\0.9.0_202103310341-8b4f782\mayausd\USD3\bin\usdview", line 28, in <module>
    import pxr.Usdviewq as Usdviewq
  File "C:\Program Files\Autodesk\MayaUSD\Maya2022\0.9.0_202103310341-8b4f782\mayausd\USD3\lib\python\pxr\Usdviewq\__init__.py", line 30, in <module>
    from .common import Timer
  File "C:\Users\Brian\AppData\Local\Programs\Python\Python39\Lib\site-packages\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "C:\Program Files\Autodesk\MayaUSD\Maya2022\0.9.0_202103310341-8b4f782\mayausd\USD3\lib\python\pxr\Usdviewq\common.py", line 28, in <module>
    from pxr import Ar, Tf, Sdf, Kind, Usd, UsdGeom, UsdShade
  File "C:\Users\Brian\AppData\Local\Programs\Python\Python39\Lib\site-packages\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "C:\Program Files\Autodesk\MayaUSD\Maya2022\0.9.0_202103310341-8b4f782\mayausd\USD3\lib\python\pxr\Ar\__init__.py", line 24, in <module>
    from . import _ar
  File "C:\Users\Brian\AppData\Local\Programs\Python\Python39\Lib\site-packages\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
ImportError: DLL load failed: The specified procedure could not be found.
```

**Comment by HamedSabri-adsk** [comment]
@BrianHanke

> Any potential conflicts in there? By the way, I also tried installing Maya 2020 and a 2020-compatible version of the plugin and even there it gives the same error.

The plugins that you've listed should not have any conflicts with USD at all and they are perfectly fine to be loaded besides mayaUsd plugin.

As for the issue with usdview, I don't think you need to install any python since we use python that comes from Maya ( a.k.a **mayapy.exe** ) which also now comes with pip package manager.  If you open up the usdview with a text editor you should see the **shebang** to be set `#!mayapy.exe`

I haven't tried usdview that we ship since I always build usd myself.  @santosg87 @santosd  are you guys able to run **usdview** that we ship with the installer on your machines?

My hunch is that you have Python collision from somewhere.

**Comment by BrianHanke** [comment]
IT'S WORKING! For anybody that has this problem, here's what I did:

1. Install the latest build of Python (3.9.5 in my case).
2. Make sure you have C:\<python_install_dir and C:\<python_install_dir\Scripts in your Windows PATH.
3. Add a new Windows env variable PYTHONPATH and point it to your MayaUSD folder (C:\Program Files\Autodesk\MayaUSD\Maya2022\0.9.0_202103310341-8b4f782\mayausd\USD3\lib\python in my case).

Honestly I don't know if steps 1 and 2 are even needed. 3 is what seems to have done it for me, but I don't want to go back and test from scratch to check. I did "pip install PySide6" when it complained about missing PySide at some point, but again, that may not have anything to do with the final solution. 

Perhaps the MayaUSD plugin installer should add that env variable to Windows automatically?

Regardless, I'm in business now! Thanks to all for you attention and assistance.

**Comment by dgovil** [comment]
oh I certainly don't recommend going that route. I assume that lets you
view usdview? I'm not sure that would affect your MayaUSD plugin being able
to load, unless something else was messing up Maya's own PYTHONPATH

You're going to introduce conflicts whenever you use Python scripts that
might fall through into using the Maya libs.
You're also going to hit issues if anything has any ABI incompatibility
between Maya's Python and the Windows Python.

For USDView, check out Sean's comment here:
https://github.com/Autodesk/maya-usd/issues/1373#issuecomment-829589525

**Comment by BrianHanke** [comment]
@dgovil Huh. I went to check what would happen if I removed PYTHONPATH and the plugin is indeed loading now. What a perplexing situation. I've done so much fiddling by now who knows what did what.

**Comment by BrianHanke** [comment]
Aha, final update. I remembered I could go to my desktop and redo this process to get it working over there. Here was the problem:

I had Nuke in my PATH. 

Took that out and all working fine now. No need to install Python or do any of that other stuff!

**Comment by HamedSabri-adsk** [comment]
Glad it works! Getting rid of Nuke from the path makes a lot more sense. I also strongly agree with @dgovil comment and would avoid going that rout.

**Comment by HamedSabri-adsk** [comment]
@BrianHanke closing this issue since it is resolved.

**Comment by nn2jay** [comment]
Hello Everyone,
I'm not too familiar with coding and all that stuff but after carefully going through your comments it seems to remove nuke from the USD path was the issue. Thanks for all your contributions. Could anyone give me a layman's instruction on removing NUKE to solve this USD issue I'm also experiencing? Thanks.
