### ISSUE TITLE
[MAYA-111540] Multi proxy shape types UFE handlers

### ISSUE THREAD

**Issue by fabal** [Autodesk/maya-usd#1399]
Currently, in an environment where 2 plugins were loaded in the same session (e.g. AL_USDMaya AND maya-usd), depending on the order of which the plugins are loaded, a different UFE TransformHandler type will be active.
It would be beneficial, as in more robust, to unify the handlers registration as it can otherwise lead to undesirable and difficult to track issues.

**Comment by fabal** [comment]
Sounds good to me, thanks @ppt-adsk :+1:

**Comment by ppt-adsk** [comment]
Hi @fabal, let us know if the code change works for you.  Thanks!

**Comment by fabal** [comment]
It does, thanks @ppt-adsk :+1:
