### ISSUE TITLE
[MAYA-112059] USD stage displaying textures incorrectly.

### ISSUE THREAD

**Issue by daviddeacon** [Autodesk/maya-usd#1417]
Hi,

I'm testing out converting Maya assets to USD, I'm using the standard surface material. I'm keeping it simple and just connecting a sRGB base colour map. I then export from Maya to USD, with the material's option set to 'USD Preview Surface'

When reading in the USD via a USD stage, the colour map displays incorrectly, it looks like it might just be a colour space issue. I tried to match the USD source's texture colour space to what I was seeing on the stage but nothing matched.

I also tried exporting with basic Lambert material assigned, it also had the same issue with being too dark with a red hue.

Viewport screenshot - 
<img width="1852" alt="previewSurfaceColourSpace" src="https://user-images.githubusercontent.com/60041784/118398012-a06af300-b64e-11eb-951d-68abccf5260e.png">
[https://www.dropbox.com/s/pzv7fdx5ku12le8/previewSurfaceColourSpace.png?dl=0](url)

Scene file - 
[https://www.dropbox.com/sh/nxhy4s2h0ud64rf/AACMz1wpW9SnDQfNPEHN6i3ya?dl=0](url)

macOS Big Sur, 11.2.3
Maya USD 0.9.0
Maya 2022

**Comment by JGamache-autodesk** [comment]
The USD stage uses USD's image loader and tries to color correct the texture data from sRGB to ACEScg using the following code:
https://github.com/Autodesk/maya-usd/blob/dev/lib/mayaUsd/render/vp2ShaderFragments/UsdUVTexture.xml#L63
Deactivating that code gives back the equivalent of "raw" in Maya, so this is where the redshift happens.
I will have to consult with our color management experts to see if a better transform exists that would replicate what we get with the Maya image handlers.

**Comment by JGamache-autodesk** [comment]
Logged internally as MAYA-112059
