### ISSUE TITLE
[MAYA-111835]Selecting and grouping object that is part of USD stage crashes Maya

### ISSUE THREAD

**Issue by daviddeacon** [Autodesk/maya-usd#1418]
This is an odd one, not 100% sure it's a real workflow but it should error rather than hard crashing Maya.

1. New Scene,
2. Create poly sphere, export as polySphere as USD file,
3. New Scene,
4. Load USD file via, stage from file.
5. In the viewport select the pSphere1,
6. Hit cmd+g, to group

For me I see the error,
"// Error: file: /Applications/Autodesk/maya2022/Maya.app/Contents/scripts/others/showEditor.mel line 4466: Invalid object name: |Sphere|SphereShape,/pSphere1"

The pSphere1, does get put into a group1. _( I'm not sure if this is desired or not)_

7. Hit cmd+g again, Maya crashes.

I found that it only happens if you try the send group command after getting the error, selecting something else and hitting cmd+g is fine.

macOS Big Sur, 11.2.3
Maya USD 0.9.0
Maya 2022

**Comment by daviddeacon** [comment]
> @daviddeacon the crash should be fixed now. Can you please try things again and close this issue if it is not longer reproducible?

Is there a new compiled build that's available to test?

**Comment by HamedSabri-adsk** [comment]
The fix was merged in about 9 days ago. If you are to able to build the project then you should have it. Otherwise you have to wait for the next precompiled binary release to be able to test it.

**Comment by santosd** [comment]
Closing this one out since it has been resolved. Feel free to test and confirm when the release is out or by building yourself from the latest.
