### ISSUE TITLE
[MAYA-110842] UseDefaultMaterial button resets point instancers

### ISSUE THREAD

**Issue by flord** [Autodesk/maya-usd#1419]
When you have a stage open that has point instancers, and you click on the "Use Default Material" button in the viewport, the point instances reset to the origin, losing the set dress.

![UseDefaultMaterial](https://user-images.githubusercontent.com/575125/118550663-f3b27380-b72a-11eb-9f3f-a1b81e8406a1.gif)

**Specs (if applicable):**
 - CentOS 7.6
 - Maya version 2022
 - Maya USD version: 0.9.0 (downloaded from github)

Scene available upon request.

**Comment by santosd** [comment]
Hi @flord, this issue has been resolved internally and should be available in the next release. I will go ahead and close this issue out for now, but feel free to test in the next release and if you run into any issues please let us know.

**Comment by flord** [comment]
Thanks!
