### ISSUE TITLE
Can't do a pip install of pyside2 and shiboken2

### ISSUE THREAD

**Issue by Ryanagogo** [Autodesk/maya-usd#143]
I'm using python 2.7, and when I do a pip install of pyside2 and shiboken2, it errors and says there is no version.

What is the procedure for installing pyside2 and shiboken2?

**Comment by suesauer** [comment]
Thats odd, What are you on? Windows/Linux?

**Comment by BigRoy** [comment]
That's correct, Python 2 doesn't have a `PySide2` that is installable through `pip` - however [this might only be the case on Windows as it's green here for OS X and Linux](https://wiki.qt.io/Qt_for_Python). Some old notes on why this is so problematic on Python 2 can be found [here](https://github.com/PySide/pyside2/wiki).

There is `python-qt5` that will install `PyQt5`, but will still leave you without `PySide2`. I think it is possible to manually compile `PySide2` for python 2, however I'm not sure whether it's trivial.

**Comment by Ryanagogo** [comment]
Hello,

I use windows 10. Compiling my own pyside2 is a bit of a pain, I don’t know how to do that. 

Can you guys just compile everything, so we can just install and use the plugins?  For someone like me, it’s pretty daunting to go through this whole compiling process just so I can see what this usd thing is about.

The documentation may make sense to a real programmer, but I don’t really understand what I’m looking at. It’s super frustrating. I just want to give up. 

Usd looks great to use on YouTube, but that’s as far as I’ve gotten,

Ryan

**Comment by HamedSabri-adsk** [comment]
Hi @Ryanagogo  You really don't need Pyside2 nor Shiboken2 on Windows.

Just go with `pip install PySide` and that will do.

Also check to see if you already have PyOpenGL, PyYAML, and Jinja2 . If not, please install them as well.
`pip install PyOpenGL PyYAML Jinja2`

You can see the list of installed packages by simply calling:  `pip list`

**Comment by HamedSabri-adsk** [comment]
@Ryanagogo can this issue be closed?

**Comment by Ryanagogo** [comment]
I haven't had time yet to try out the suggestion, but you can go ahead and close
Ryan

    On Wednesday, December 4, 2019, 11:47:37 AM CST, Hamed Sabri <notifications@github.com> wrote:  
 
 
@Ryanagogo can this issue be closed?

**Comment by Ryanagogo** [comment]
Sorry to write to this thread again.  This is not about the pip install and this is not an issue.  I'm just wondering where I can go to get help on building these plugins.  I'm not a programmer, so the instructions in the build document actually make no sense to me.  I really need something that has much more detailed and specific steps of instructions on how to build on windows 10.  Do you know of a website or forum where I can get help?
Thank you,
Ryan

    On Thursday, December 5, 2019, 02:47:37 AM GMT+9, Hamed Sabri <notifications@github.com> wrote:  
 
 
@Ryanagogo can this issue be closed?
