### ISSUE TITLE
Build fails due to set_tests_properties called with incorrect number of arguments.

### ISSUE THREAD

**Issue by BigRoy** [Autodesk/maya-usd#144]
# Issue

In some case building fails on [this line in `plugin/al/usdtransaction/AL/usd/transaction/tests/CMakeLists.txt`](https://github.com/Autodesk/maya-usd/blob/f952d26bd76d59b141e3944add16c7c946620ea7/plugin/al/usdtransaction/AL/usd/transaction/tests/CMakeLists.txt#L52) with the following error:

```
-- Found GTest: D:/git_pipeline/rez-packages/maya_usd/build/platform-windows/arch==AMD64/maya-usd/googletest-install/lib/gtest.lib
CMake Error at plugin/al/usdtransaction/AL/usd/transaction/tests/CMakeLists.txt:50 (set_tests_properties):
  set_tests_properties called with incorrect number of arguments.
```

This makes the build fail.

A [working patch was mentioned here](https://github.com/Autodesk/maya-usd/issues/86#issuecomment-561011247). It [fixed my build problems here](https://github.com/Autodesk/maya-usd/issues/126#issuecomment-561052142).

Likely it fails to correctly parse the arguments if there's a path or variable resolved there that contains a path with spaces (or maybe backslashes?), that I didn't figure out yet.

---

Should this be patched up with a PR?

**Comment by kxl-adsk** [comment]
@BigRoy Please open a PR for this.

**Comment by fdevic** [comment]
Hello!

So I have the same issue :(

I did use the fix of changing the "usd\cmake\pxrTargets.cmake" file 

I am on the dev branch of Maya.
I set up paths
`
set GIT=C:\Program Files\Git
set PATH=%GIT%\usr\bin;%GIT%\mingw64\bin;%PATH%
set PATH=%PATH%;c:\Python27;c:\Python27\Scripts
`

I compiled USD v19.11 with this line :
`python USD\build_scripts\build_usd.py --build-args=boost,"--with-date_time --with-thread --with-system --with-filesystem" --force-all --no-maya --python --no-houdini "d:\myproject\usd_19_11_boost_no_alembic"`

then setting up my paths
`set MAYA_PATH=C:\Program Files\Autodesk\Maya2020
set PYTHONPATH=d:\myproject\usd_19_11_boost_no_alembic\lib\python
set PATH=%PATH%;d:\myproject\usd_19_11_boost_no_alembic\bin;d:\myproject\usd_19_11_boost_no_alembic\lib
`
And then tried to compile Maya-usd
`python build.py --maya-location="c:\Program Files\autodesk\Maya2020" --pxrusd-location="d:\myproject\usd_19_11_boost_no_alembic" --devkit-location="d:\myproject\external\Maya\sdk\2020\devkitbase" e:\\maya_usd_19_11`


and then

`-- ========== ...  GoogleTest installed. ==========
-- Found GTest: E:/maya_usd_19_11/build/RelWithDebInfo/plugin/al/googletest-install/lib/gtest.lib
CMake Error at plugin/al/usdtransaction/AL/usd/transaction/tests/CMakeLists.txt:49 (set_tests_properties):
  set_tests_properties called with incorrect number of arguments.


-- Building AL_USDMayaSchemas
Processing schema classes:
ALModelAPI, ALMayaReference, ALFrameRange
Loading Templates from d:\myproject\usd_19_11_boost_no_alembic\lib\usd\usd\resources\codegenTemplates
Writing API:
            wrote E:\maya_usd_19_11\build\RelWithDebInfo\plugin\al\schemas\AL\usd\schemas\maya\api.h
Writing Schema Tokens:
            wrote E:\maya_usd_19_11\build\RelWithDebInfo\plugin\al\schemas\AL\usd\schemas\maya\tokens.h
            wrote E:\maya_usd_19_11\build\RelWithDebInfo\plugin\al\schemas\AL\usd\schemas\maya\tokens.cpp
            wrote E:\maya_usd_19_11\build\RelWithDebInfo\plugin\al\schemas\AL\usd\schemas\maya\wrapTokens.cpp
Generating Classes:
            wrote E:\maya_usd_19_11\build\RelWithDebInfo\plugin\al\schemas\AL\usd\schemas\maya\ModelAPI.h
            wrote E:\maya_usd_19_11\build\RelWithDebInfo\plugin\al\schemas\AL\usd\schemas\maya\ModelAPI.cpp
            wrote E:\maya_usd_19_11\build\RelWithDebInfo\plugin\al\schemas\AL\usd\schemas\maya\wrapModelAPI.cpp
            wrote E:\maya_usd_19_11\build\RelWithDebInfo\plugin\al\schemas\AL\usd\schemas\maya\MayaReference.h
            wrote E:\maya_usd_19_11\build\RelWithDebInfo\plugin\al\schemas\AL\usd\schemas\maya\MayaReference.cpp
            wrote E:\maya_usd_19_11\build\RelWithDebInfo\plugin\al\schemas\AL\usd\schemas\maya\wrapMayaReference.cpp
            wrote E:\maya_usd_19_11\build\RelWithDebInfo\plugin\al\schemas\AL\usd\schemas\maya\FrameRange.h
            wrote E:\maya_usd_19_11\build\RelWithDebInfo\plugin\al\schemas\AL\usd\schemas\maya\FrameRange.cpp
            wrote E:\maya_usd_19_11\build\RelWithDebInfo\plugin\al\schemas\AL\usd\schemas\maya\wrapFrameRange.cpp
            wrote E:\maya_usd_19_11\build\RelWithDebInfo\plugin\al\schemas\AL\usd\schemas\maya\plugInfo.json
Generating Schematics:
            wrote E:\maya_usd_19_11\build\RelWithDebInfo\plugin\al\schemas\AL\usd\schemas\maya\generatedSchema.usda
Processing schema classes:
ALExamplePolyCubeNode
Loading Templates from d:\myproject\usd_19_11_boost_no_alembic\lib\usd\usd\resources\codegenTemplates
Writing API:
            wrote E:\maya_usd_19_11\build\RelWithDebInfo\plugin\al\schemas\AL\usd\schemas\mayatest\api.h
Writing Schema Tokens:
            wrote E:\maya_usd_19_11\build\RelWithDebInfo\plugin\al\schemas\AL\usd\schemas\mayatest\tokens.h
            wrote E:\maya_usd_19_11\build\RelWithDebInfo\plugin\al\schemas\AL\usd\schemas\mayatest\tokens.cpp
            wrote E:\maya_usd_19_11\build\RelWithDebInfo\plugin\al\schemas\AL\usd\schemas\mayatest\wrapTokens.cpp
Generating Classes:
            wrote E:\maya_usd_19_11\build\RelWithDebInfo\plugin\al\schemas\AL\usd\schemas\mayatest\ExamplePolyCubeNode.h
            wrote E:\maya_usd_19_11\build\RelWithDebInfo\plugin\al\schemas\AL\usd\schemas\mayatest\ExamplePolyCubeNode.cpp
            wrote E:\maya_usd_19_11\build\RelWithDebInfo\plugin\al\schemas\AL\usd\schemas\mayatest\wrapExamplePolyCubeNode.cpp
        unchanged E:\maya_usd_19_11\build\RelWithDebInfo\plugin\al\schemas\AL\usd\schemas\mayatest\plugInfo.json
Generating Schematics:
            wrote E:\maya_usd_19_11\build\RelWithDebInfo\plugin\al\schemas\AL\usd\schemas\mayatest\generatedSchema.usda
-- Building AL_USDMayaTranslators
-- Configuring incomplete, errors occurred!
See also "E:/maya_usd_19_11/build/RelWithDebInfo/CMakeFiles/CMakeOutput.log".
See also "E:/maya_usd_19_11/build/RelWithDebInfo/CMakeFiles/CMakeError.log".

Traceback (most recent call last):
  File "build.py", line 482, in <module>
    InstallMayaUSD(context, context.buildArgs, context.stagesArgs)
  File "build.py", line 319, in InstallMayaUSD
    RunCMake(context, extraArgs, stagesArgs)
  File "build.py", line 283, in RunCMake
    extraArgs=(" ".join(extraArgs) if extraArgs else "")))
  File "build.py", line 189, in Run
    .format(cmd=cmd, log=os.path.abspath(context.logFileLocation)))
RuntimeError: Failed to run 'cmake -DCMAKE_INSTALL_PREFIX="e:\maya_usd_19_11\install\RelWithDebInfo" -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -G "Visual Studio 15 2017 Win64" -DMAYA_LOCATION="c:\Program Files\autodesk\Maya2020" -DPXR_USD_LOCATION="d:\myproject\usd_19_11_boost_no_alembic" -DMAYA_DEVKIT_LOCATION="d:\dxm\external\Maya\sdk\2020\devkitbase" "E:\github\maya-usd"'
See e:\maya_usd_19_11\build\RelWithDebInfo\build_log.txt for more details.`

I am compiling in the x64Native Tools Command prompt for VS 2017

ANd I use this : https://github.com/Autodesk/maya-usd/issues/86

**Comment by HamedSabri-adsk** [comment]
This issue is fixed as part of #198 which was merged recently into dev branch.

**Comment by HamedSabri-adsk** [comment]
Bonjour @fdevic , I am going to reopen this issue until I understand what exactly is causing this.

**Comment by fdevic** [comment]
> Bonjour @fdevic , I am going to reopen this issue until I understand what exactly is causing this.

Thanks. Tell me if I can be of any help
