### ISSUE TITLE
Adding '-root' flag to usdExport command that limits the selected objects parents

### ISSUE THREAD

**Issue by BSalem** [Autodesk/maya-usd#1440]
**Is your feature request related to a problem? Please describe.**
Pipelines used to rely on alembic where the -root flag is used with -sl flag to set and limit the parents that will be written out in the cache of the selected objects (especially when these unwanted parents have transforms that we don't want it to affect the children transformation in the generated cache), so we need the usdExport to have similar flag so we can produce the same hierarchies and behavior as AbcExport used to provide, that, to avoid making major modifications to all apps and pipeline tools that used to rely on alembic before moving to USD.

**Describe the solution you'd like**
add a -root (multiUse) flag that tells the exporter the high parents that it should not go beyond when writing the selected (-sl) objects.

**Additional context**
Example:
if we have the following hierarchy
chr_mode_ast
|---- body_grp
|--------- body
|--------- eyes
|---- accessories_grp
|--------- belt
|--------- dress

we would like to select the belt, dress, body and eyes, then do:
usdExport -sl -root "accessories_grp" -root "body_grp" -file "/some/path.usda"

the command above is expected then to write out the selected objects under the given root parents with disrespect to the 'chr_mode_ast' parent that we don't want it cached in the generated file.

**Note: adding such flag may also require adding a -world flag that if given, should write the selected object roots in world space transformation**

**Comment by daviddeacon** [comment]
Hi,

Yes this is exactly what I need for the same reasons of mimicking the AbcExport behaviour.

Good news is I think this is actively being worked on, as I believe this pull request is discussing the same feature.

https://github.com/Autodesk/maya-usd/pull/1111#issue-561470275

**Comment by wtelford** [comment]
Hey @BSalem as @daviddeacon mentions there is an open pull request https://github.com/Autodesk/maya-usd/pull/1111#issue-561470275 where this is being discussed.  I'm closing this issue in favor of that pull request. Please reopen this issue and let us know if the solutions proposed in that thread do not meet your needs.

**Comment by kxl-adsk** [comment]
We can leverage "linked issues" field in PR to get this issue closed automatically. No need to close ahead of time.

**Comment by BSalem** [comment]
I actually submitted a pull request #1471 that has both -userattr and -root (both are multi-flags), where the -root/-rt attribute was what I was looking for in here... using -root flag, we can pass multiple roots, any parent to these roots will be ignored when writing the USD, in combination with the -sl flag, we can also limit what exactly under the root will be exported and what will be ignored.
