### ISSUE TITLE
Maya crashes when creating USD stages 

### ISSUE THREAD

**Issue by DavidSpeicher** [Autodesk/maya-usd#1441]
Fatal crash at any attempt to create a stage 
![Screenshot_297](https://user-images.githubusercontent.com/65549190/119976962-1f99e880-bfb8-11eb-9ee1-6507a76f12fc.png)

**Steps to reproduce**
1. Go to Create menu
2. Click on stage with New layer option
![Screenshot_298](https://user-images.githubusercontent.com/65549190/119977101-4bb56980-bfb8-11eb-9e79-2a8add3db460.png)

3. See error

**Expected behavior**
use plugin with no crashes

**Specs (if applicable):**
Windows 10 
I9 9980xe 64gb ram Nvidia 2080s 
Maya 2022
USD prebuilt version in plugin

**Comment by ppt-adsk** [comment]
Hi @DavidSpeicher, we suspect you're hitting path problems, and these are usually having another USD or another Python in your paths.  @seando-adsk recommends the following.  In Maya, run these two commands:

getenv "PATH";
getenv "PYTHONPATH";

Make sure there is no path to another USD or another Python in there.  If you're unsure, copy the results here in the issue and we'll try to help out.  Cheers.

**Comment by santosd** [comment]
Hi @DavidSpeicher, I wanted to check back on this and see if you were still experiencing this issue or if all was well and we could close this ticket out. Looking forward to hearing back from you.

**Comment by DavidSpeicher** [comment]
Yes i managed to fix it on my own. 
the installer though should of done this though to be honest when installing maya 2022.

but anyways thanks :)

**Comment by santosd** [comment]
Thank you for the reply and glad to hear you were able to fix it.
