### ISSUE TITLE
Better representation of USD root in UFE outliner

### ISSUE THREAD

**Issue by dj-mcg** [Autodesk/maya-usd#1454]
Currently, users must enable "Display Shapes" in the Outliner in order to be able to access the USDProxyShape and to introspect the USD scene. Users would like a separate Display Option for USD specifically, since turning on "Display Shapes" might expose a bunch of garbage in the outliner they'd rather not see.

Also, the fact that the Root level of the USD scene is nested under a Shape node (and the Shape node is itself nested under an XForm) is confusing for users. The outliner should provide the option to view only the USD scene hierarchy as if it were at the root.

(Tracking this within Pixar as MAYA-2976)

**Comment by wtelford** [comment]
There are two issues here.
1. The Outliner "Shapes" display filter should not apply to USD proxyShapes.
2. USD data should be presented at the Outliner root.

@santosg87 can you log these two separately internally?

**Comment by wtelford** [comment]
Part one:
"As a user, I'd like proxyShapes to be ignored by the Display - Shapes filter"
...has been logged internally as MAYA-112223

**Comment by santosg87** [comment]
the initial part of ignoring the "shapes" filter on the outliner is now available on Maya 2024. :) 

we currently don't have a plan on moving the root node of the USD stage on the hierarchy. closing this issue for the time being
