### ISSUE TITLE
[UFE] Crash when selecting after Proxy Shape was renamed

### ISSUE THREAD

**Issue by BigRoy** [Autodesk/maya-usd#146]
# Issue

When renaming the Proxy Shape in the outliner after it was generated then it will end up crashing later as you go through the UFE hierarchy.

Here's the Crash Dump:
[MayaCrashLog191203.1035.zip](https://github.com/Autodesk/maya-usd/files/3915874/MayaCrashLog191203.1035.zip)
And here is the dump copied to clipboard text:
[toclipboard_MayaCrashLog191203.1035.txt](https://github.com/Autodesk/maya-usd/files/3915877/toclipboard_MayaCrashLog191203.1035.txt)

_This is reproducable with the AL proxy shape and the `mayaUsdProxyShape`._

#### To reproduce

1. Create a proxy shape and load USD file.
2. Show Shapes in Outliner, double click the Proxy Shape and rename it.
3. Continue selecting parts of the UFE hierarchy, it will crash Maya.

I've had some cases where it didn't crash but then disallowed any selection in the UFE hierarchy or viewport - which is it still breaking but at least a bit nicer to the user. So the easiest way to consistently crash it is this:

1. Make sure you expand the UFE hierarchy before renaming.
2. Then after renaming on one of the children in the UFE hierarchy (note how no viewport selection happens)
3. Activate a tool like the Move Tool - crash.

Having the UFE hierarchy expanded first means it doesn't "refresh" whether it's valid after the rename, as such you can still select the 'old' UFE children hierarchy which are actually invalid. You can see they were invalidated by collapsing the Shape node hierarchy and then expanding it again, note how you can't expand it and now also can't select things in the viewport.

### Specs

- Windows 10
- Maya 2019.2
- dev branch ( [`f952d26`](https://github.com/Autodesk/maya-usd/commit/f952d26bd76d59b141e3944add16c7c946620ea7) ) 
- Pixar USD dev ( `2ef943b` )

**Comment by BigRoy** [comment]
If I avoid clicking in the already expanded UFE hierarchy in the Outliner then I can work around the crash, as the crash originates from the invalidated UFE hierarchy.

The Output Window logs this:
```
Warning: in getInstancedSelectionPath at line 517 of d:\dev\usd\maya-usd\lib\render\vp2renderdelegate\proxyrenderdelegate.cpp -- UFE runtime is not updated for the USD stage. Please save scene and reopen.
```

Is there any way we can have it automatically "update" based on Proxy rename?

**Comment by fowlertADSK** [comment]
I have reproduced this here and have logged it internally as MAYA-102361

**Comment by ppt-adsk** [comment]
Fixed in the next preview release of Maya.

**Comment by santosg87** [comment]
@BigRoy this should be fixed now in PR114, would you be able to validate it?

there is a pre-built version of mayaUsd included in the PR114 just as it was with PR113. :)
