### ISSUE TITLE
AE template UI layout broken in Python 2.x

### ISSUE THREAD

**Issue by csyshing** [Autodesk/maya-usd#1460]
**Describe the bug**

Hi,

The AE UI layout from MayaUSD v0.9.0 seems broken if it's running in Python 2.x Maya, see screenshot:

![AE_UI_layout_MayaUSD_v0 9 0_python-2 7](https://user-images.githubusercontent.com/1593576/120770654-b854d900-c561-11eb-819e-e672f4973bc1.png)

And it looks fine if it's in Python 3.x, prim attributes are grouping nicely:

![AE_UI_layout_MayaUSD_v0 9 0_python-3 7](https://user-images.githubusercontent.com/1593576/120770728-cefb3000-c561-11eb-994f-b8f0019f8f83.png)

MayaUSD v0.8.0 does not have this problem.

We found that this single **non ASCII** character `’` is causing the issue:

https://github.com/Autodesk/maya-usd/blob/dev/lib/mayaUsd/resources/ae/usdschemabase/ae_template.py#L140

```
.... it doesn’t ....
             ^
```

Changing it to an ASCII character fixed the issue.

I don't see anyone else has reported, maybe just our studio having this problem?

**Steps to reproduce**
1. Launch Maya in python 2.7 environment and load MayaUSD plugin
2. Load any USD file
3. Select any prim and take a look at AE

**Expected behavior**
Consistent look and feel regardless of Python version.

**Specs (if applicable):**
 - OS & version Centos 7.4
 - Compiler & version gcc 6.3.1
 - Maya version Maya 2022
 - Maya USD commit SHA Official v0.9.0
 - Pixar USD commit SHA Official USD 20.11

**Comment by kxl-adsk** [comment]
@csyshing Thank you for reporting! We haven't caught this in testing and will validate again...but it didn't hurt to make the change and PR was already merged. Thank you @seando-adsk!
