### ISSUE TITLE
target version for USD?

### ISSUE THREAD

**Issue by rhaleblian** [Autodesk/maya-usd#15]
Hi guys. I ultimately want to build against USD 19.07 with one of the refactoring branches. It seems that the USD version expected is something between 19.1 and 19.07, and build breaks on either of those versions suggest the real answer is somewhere inbetween...

thx,
-ray (Disney Animation)

**Comment by BigRoy** [comment]
According to [this](https://github.com/Autodesk/maya-usd/issues/1#issuecomment-517684610) it should be **19.05**.

**Comment by rhaleblian** [comment]
Ohh thanks @BigRoy. It's actually reflected in Versions.cmake as well.
BTW, should have mentioned i'm on Linux.
