### ISSUE TITLE
Add minimum CMake version to docs

### ISSUE THREAD

**Issue by seymour88** [Autodesk/maya-usd#150]
I was having issues compiling the refactoring_sandbox branch and the issue turned out to be the version of CMake being used was too old and therefore missing features required to compile.

I found the minimum required version to be 3.12.0.

It'd be great to add this to the build docs.

**Comment by kxl-adsk** [comment]
We should actually bump the minimum CMake version in CMakeLists file (https://github.com/Autodesk/maya-usd/blob/master/CMakeLists.txt#L19). Feel free to open a PR for it.

**Comment by BigRoy** [comment]
I've set up a PR that bumps the required CMake version to `3.12.0`: #152 - please give it a test run to see if it correctly detects the invalid versions on your end.

**Comment by hamedsabri** [comment]
@BigRoy @ryan-seymour what was the reason that required you to bump up the version? What was the missing features?

**Comment by kxl-adsk** [comment]
IIRC. It's because of the file touch which doesn't exist prior to 3.12 and is used in a few places in our cmake files.

**Comment by ryan-seymour** [comment]
Sorry for the slow reply, I'm based in Australia.
To confirm, it was the file touch commands which were tripping up the older version of CMake I was using. I should have put that in the issue. The PR by @BigRoy addresses catches failure.
