### ISSUE TITLE
Constant vertex colour display

### ISSUE THREAD

**Issue by fabal** [Autodesk/maya-usd#1500]
Hi there, the VP2 render delegate displays vertex colours authored in USD using a constant interpolation differently than other interpolation, i.e.:
https://github.com/Autodesk/maya-usd/blob/7250d4adbd08f212188e5e211215d02f4498e1ae/lib/mayaUsd/render/vp2RenderDelegate/mesh.cpp#L1784
The rationale for this behaviour is unclear to me, is it still needed?

**Comment by kxl-adsk** [comment]
Hi @fabal, I will convert this issue to a discussion and in future please use discussion forums to ask question.
