### ISSUE TITLE
Version 0.10.0 for Maya2022 crashes Maya when loaded with Arnold on MacOS

### ISSUE THREAD

**Issue by MKGitHub** [Autodesk/maya-usd#1529]
**Describe the bug**
When version 0.10.0 is installed Maya crashes on launch or when the plugin is enabled.
macOS Big Sur 11.4 (20F71)

<img width="857" alt=" 2021-06-30 at 00 30 05" src="https://user-images.githubusercontent.com/535550/123876287-62ded280-d93b-11eb-9a24-640dc7dd1b5c.png">
<img width="827" alt=" 2021-06-30 at 00 33 16" src="https://user-images.githubusercontent.com/535550/123876302-67a38680-d93b-11eb-82f7-b6096167ac3b.png">

**Comment by santosg87** [comment]
Hi @MKGitHub, thanks for logging this. I am trying a few things on our side to narrow things down. we have been able to reproduce a crash with the mtoa plugin, so i am wondering if that could be the issue for you as well.

if you unload the mtoa plugin, does that allow mayausd to load?

**Comment by MKGitHub** [comment]
@santosg87 You are correct, I unloaded the mtoa plugin and version 0.10.0 works :-)

**Comment by santosg87** [comment]
@MKGitHub I would recommend updating Arnold to a more recent version then, as there is probably just difference on libraries, as the arnold release with gold is quite older. arnold 4.2.3 should be available for download on the arnold side. :)
