### ISSUE TITLE
[MAYA-112624] vp2RenderDelegate and custom surface shaders

### ISSUE THREAD

**Issue by jufrantz** [Autodesk/maya-usd#1532]
Hello,

We are using custom surface shader nodes (i.e. not `UsdPreviewSurface`) in `UsdPreview like`  node graphs (using `UsdUVTexture`, `UsdPrimvarReader` and `UsdTransform2d`). These nodes are registered in SdrRegistry thanks to an usd plugin and HdSt renders the shading effect from custom glslfx files. This works flawlessly in usdview/storm as well as in maya/storm batchRenderer. 

We are now trying to render these scenes in maya 2022 viewport using `vp2RenderDelegate` override, by providing vp2 implementations of the former glslfx files.

Looking at the current state of vp2RenderDelegate, I was confident enough that it was possible. I replicated integration of `UsdPreviewSurface` shader : a dedicated vp2 fragment graph named with the Sdr identifier is registered in the fragmentManager. `vp2RenderDelegate` is then able to create a valid `MShaderInstance` instead of a fallback, but .. the resulting effect is wrong, the shader needs surface normals for lighting and they are not provided (a default constant normal is used). 

I dug more into this problem to find out if it can be fixed on our side and found a special case in `HdVP2Material` when it parses `HdMaterialNetwork` primvar requirements : normals are implicitly required iff the network contains an UsdPreviewSurface. 

https://github.com/Autodesk/maya-usd/blob/1b83d33e1b0d7b1af94afc0acab57756d9f6bced/lib/mayaUsd/render/vp2RenderDelegate/material.cpp#L1474-L1476

**Describe the solution you'd like**

I would like a way to notice vp2RenderDelegate that the non-UsdPreviewSurface shader implicitly needs surface normals (and possibly other usd primvars). This could for instance be with SdrShaderNode metadata or vp2 fragment param semantics. I tried a quick change on my side by extending primvars requirements using `MShaderInstance::requiredVertexBuffers()` and it did the job.

**Describe alternatives you've considered**
None.

Thank you in advance for your help
Best regards,
Julien

**Comment by williamkrick** [comment]
I think that if we checked the MShaderInstance::requiredVertexBuffers() somewhere between calling _createShaderInstance() and where _requiredPrimvars is set at [line 1178 of material.cpp](https://github.com/Autodesk/maya-usd/blob/1b83d33e1b0d7b1af94afc0acab57756d9f6bced/lib/mayaUsd/render/vp2RenderDelegate/material.cpp#L1178) that would fix the problem for you. Is my understanding here correct?

Making sure the requirements are correct at that point is a better fix then the explicit check we have now for UsdPreviewSurface.

**Comment by jufrantz** [comment]
Hello William,

Yes you are correct, this is exactly what I tried and this would fix our missing normals.
This would be great if it could handle arbitrary primvars as well (not only standard MGeometry semantics like normals).

Thank you for the fast answer,
Julien

**Comment by williamkrick** [comment]
I've logged MAYA-112624 to track this one.

**Comment by williamkrick** [comment]
@jufrantz I believe this on is fixed now, please re-open if you still have issues.
