### ISSUE TITLE
[MAYA-122903] Opinions in the session layer should not block edits on an authoring layer

### ISSUE THREAD

**Issue by dj-mcg** [Autodesk/maya-usd#1539]
While testing, our users noticed that they were unable to reparent a Point Instancer after changing its Draw Mode. This was due to the fact that we are authoring the Draw Mode opinion in a session layer, which is stronger than the layer containing scene edits. We'd like an option to "special case" session layers to allow them to be implicitly modified when making edits to a scene layer, not only to prevent blocking of the reparent, but to actually modify corresponding opinions in the session layer, so in this specific case, the draw mode preference would follow the Point Instancer and persist after the reparenting operation.

**Comment by wtelford** [comment]
We're going to need to gather some more feedback on this behavior. Currently we are very restrictive on what can prevent edits in order to prevent very complex editing scenarios from arising. Loosening those up for only the session layer seems like a potential area for loosening those restrictions.

**Comment by neilh-adsk** [comment]
As discussed we are looking at lifting restrictions in certain cases.  I'll move this to an internal tracking

**Comment by womanyoyoyo-adsk** [comment]
Logged internally as MAYA-122903

**Comment by womanyoyoyo-adsk** [comment]
This is currently in progress.

**Comment by santosg87** [comment]
this should be implemented on mayaUSD 0.24.0 with Maya 2024. :) marking this issue as closed now

**Comment by dj-mcg** [comment]
Hey @santosg87 - here's another one that appears to work for us in 2023.3! Please let me know if this surprises you since I'm hoping I'm just not doing something wrong on my end
