### ISSUE TITLE
[MAYA-104475] Outliner Context Menu should perform edits on all selected nodes

### ISSUE THREAD

**Issue by dj-mcg** [Autodesk/maya-usd#1540]
If a user selects multiple nodes in the Outliner and opens the context menu, any action performed in that menu will only affect the object that was underneath the mouse cursor when the context menu was opened. If right-clicking on one of the selected nodes, the context menu actions should affect all selected nodes.

If multiple nodes are selected and the user right clicks on an UNSELECTED node, it makes sense that selection should change to that node along with displaying the context menu, which would affect the newly selected node.

**Comment by wtelford** [comment]
This is not a Maya USD specific behavior, but a default Maya behavior. We need to investigate if this is within scope for this project.

**Comment by wtelford** [comment]
Hey Grace,
Thanks for reaching out. This behavior is not unique to MayaUSD, but rather how the Outliner currently functions on Maya data as well. Given that this is Maya's pre-existing behavior and has much broader workflow implications, we were not considering this feature as being in scope right now. I do agree that bulk editing in general is a beneficial feature though. We should discuss if there is an alternate approach to bulk editing that could still address your users workflow concerns.

**Comment by womanyoyoyo-adsk** [comment]
Hi @gracekumagai and @dj-mcg,

Please see the design for this [here](https://github.com/Autodesk/maya-usd/discussions/2301). Since we last spoke I changed one thing in particular - I told you that the bulk actions offered on selected prims would be the common actions that the selected prims all possessed, but instead due to performance, we would offer bulk actions that the prim which was right-clicked possessed. I expand on this in the post. 

Looking forward to your feedback on this!
Natalia

**Comment by womanyoyoyo-adsk** [comment]
@dj-mcg @gracekumagai We are almost there with this! Here is the bulk menu so far:
![image](https://github.com/Autodesk/maya-usd/assets/49446314/686ffc09-3372-415b-9f68-f1f0802b54ae)

Question: Is it terrible that '[Load](https://openusd.org/release/api/class_usd_stage_load_rules.html#a612c20fb472a2f3a45873ef925d40fd1)' isn't there?

**Comment by santosg87** [comment]
closing this issue for now, as the work for this issue has been in for some time now. 

if there are any issues with the workflow, feel free to log a new ticket so we can track the work there. :)
