### ISSUE TITLE
[MAYA-113820] Unloaded prims should appear in the outliner

### ISSUE THREAD

**Issue by dj-mcg** [Autodesk/maya-usd#1543]
Users requested that unloaded prims still appear in the outliner to allow them to view the entire hierarchy without having to load everything, primarily to introspect the unloaded children of a group node. There should be some indication that the model is unloaded. The children/contents of unloaded prims should still be hidden, and unloaded prims should not need to be expandable.

**Comment by wtelford** [comment]
@womanyoyoyo-adsk We need to investigate this internally. If we change this behavior, we'll need a way to indicate an unloaded prim and perhaps an outliner filter.

**Comment by gracekumagai** [comment]
Hi @seando-adsk - thank you for the fix from https://github.com/Autodesk/maya-usd/pull/1877!

I was testing it on the kitchen_set and kitchen_set_instanced, and we found that:
- if a node's children includes props (xform with a reference, payload) and groups (xform without a composition arc), if the node or any of its parents are unloaded, its children are displayed in the outliner
- if a node's children includes only props (xform with a reference, payload), if the node or any of its parents are unloaded, its **children are not displayed in the outliner** (the node does not have the + to introspect it in the outliner)

Overall, we'd expect all unloaded nodes to appear in the outliner. Regardless if they are a group or a prop. Let me know if this is out of scope for this ticket and if you'd like me to create another one.

To reproduce: 
1. Open `kitchen_set` or `kitchen_set_instanced`
2. Navigate to `|Kitchen_set|Kitchen_setShape,/Kitchen_set/Props_grp/Ceiling_grp`
3. Notice that the `Ceiling_grp` only has 1 child which is a prop (xform with a reference, payload)
4. Unload `|Kitchen_set|Kitchen_setShape,/Kitchen_set/Props_grp`
5. Navigate back to `|Kitchen_set|Kitchen_setShape,/Kitchen_set/Props_grp/Ceiling_grp`
6. Notice that you cannot introspect its children

However, if you add a group (empty xform) as a child of Ceiling_grp, then you will have able to introspect its children. If you add a prop as a child of the new group, then if the new group is unloaded, you cannot introspect the group's children (but you can still introspect Ceiling_grp's immediate children as it still contains a group).
![outliner_does_not_display_unloaded_children](https://user-images.githubusercontent.com/12554015/145077249-d5bd656e-7fe9-4fc9-ba42-413a0b316987.gif)

There's a bit of a strange behaviour if you unload a group that only contains props with it expanded, you can still see its children. However, if you force the outliner to re-draw the group, it will go back to hiding the children.
![outliner_does_not_display_unloaded_children_toggle](https://user-images.githubusercontent.com/12554015/145077532-a98bd538-2ca9-4c6e-8650-867bf7ad6a1b.gif)

Thank you!

**Comment by seando-adsk** [comment]
@gracekumagai My fix was committed very recently and not part of any released build yet. Did you compile the plugin yourself? I just tried your repro steps and I do see the child of `Ceiling_grp` after I unload `Props_grp`.
![image](https://user-images.githubusercontent.com/23455376/145105050-8924bdf8-d37d-418c-89c8-d744323793ee.png)

Thanks,
Sean

**Comment by gracekumagai** [comment]
Yes, we are currently working off of the dev branch and we pulled in the updates after your change went in yesterday. 

I just re-tested the issue I was running into and it looks like it was user error on my side - I was using a stale build. Everything seems to be showing up! 

Sorry about that and thank you so much!

**Comment by seando-adsk** [comment]
@gracekumagai No problem. I'm glad everything is working now.

**Comment by santosg87** [comment]
Marking this one as closed, based on the conversation. :)
