### ISSUE TITLE
[MAYA-112663] Point Instancer Selection Mode menu item

### ISSUE THREAD

**Issue by dj-mcg** [Autodesk/maya-usd#1544]
Currently the only way to change the Point Instancer Selection mode is via the Script Editor by setting an option var. This should be surfaced to the user, probably in the USD section of the Select menu similar to the USD Selection mode.

**Comment by womanyoyoyo-adsk** [comment]
Hi @dj-mcg ,

How's this design? This submenu would be under the Select main menu. The Kind selection mode would work in combination with the Point Instancer selection mode. The submenu will be tearable. 
![pointInstancer](https://user-images.githubusercontent.com/49446314/124643305-f1cd7c80-de5e-11eb-9e76-f1f8f8ecc4e7.png)

**Comment by kxl-adsk** [comment]
The internal ticket was closed but we never reflected it on GitHub. Closing since it's already implemented by #1677
