### ISSUE TITLE
Disabling Selection Highlighting should work with USD prims

### ISSUE THREAD

**Issue by dj-mcg** [Autodesk/maya-usd#1545]
Our users noticed that USD prims would ignore the "Disable Selection Highlighting" preference. They would prefer they honor this preference instead.

**Comment by wtelford** [comment]
@womanyoyoyo-adsk We should log this internally as a story.

**Comment by kxl-adsk** [comment]
@wtelford @womanyoyoyo-adsk This looks to be already logged - #1125 (MAYA-107000). I will close this issue.
