### ISSUE TITLE
No support for rational spline curves

### ISSUE THREAD

**Issue by VikingScientist** [Autodesk/maya-usd#1549]
**Describe the bug**
I cannot find any way to format rational spline curves within the framework. Please relabel this as "help wanted" if the functionality does exist, or "feature wanted" if it does not exist. The feature exist for surfaces, but not for curves.

**Steps to reproduce**
1. Go to the API for  [UsdGeomNurbsCurves](https://graphics.pixar.com/usd/docs/api/class_usd_geom_nurbs_curves.html#details)
2. Look for anywhere to specify the rational weights of  the curve
3. Realize that this is nowhere to be found

**Expected behavior**
I expect that there exist a similar function as can be found  in [UsdGeomNurbsPatch](https://graphics.pixar.com/usd/docs/api/class_usd_geom_nurbs_patch.html#a7289647930b8aad6f68d809cf0185f17) called `GetPointWeightsAttr` to be implemented in the `UsdGeomNurbsCurves` class.

**Comment by wtelford** [comment]
Closing here as this would be an implementation of USD itself, not Maya USD. You can find that repo here:
https://github.com/PixarAnimationStudios/USD

Feel free to reopen here if I'm misunderstanding your issue.

**Comment by VikingScientist** [comment]
You are completely right and I've opened a ticket in the right place. Thanks 😄

**Comment by spiffmon** [comment]
Hi @VikingScientist  and @wtelford , just wanted to note that schema-level support landed in the dev branch recently as indicated in the above-referenced USD Issue, and will be part of the next USD release... maybe there's time to get Maya support in for it for the next usdMaya release?
