### ISSUE TITLE
The specified module could not be found. (TBM_2D)

### ISSUE THREAD

**Issue by saikumarbonigala** [Autodesk/maya-usd#1551]
// Error: file: C:/Program Files/Autodesk/Maya 2020/script/others/pluginWin.mel line 317: The specified module could not be found. (TBM_2D)

**Comment by santosg87** [comment]
Hi @saikumarbonigala, the error message you are running into seem to be the generic Maya error for a plugin not loading. would you be able to provide some more info on your system? 
it would be helpful to know the version of your plugin and specific version of Maya 2020 (or 2020.update)

a few possible reasons for the plugin not loading could be:
- environment variables affecting your system
- the mod file for the plugin is missing a path
- incompatible version of the plugin
- missing/conflicting dependencies with other registered plugins

one thing to check - if you have arnold loaded, does unloading arnold and then loading mayaUSD works?

**Comment by santosg87** [comment]
@saikumarbonigala closing this issue for now, if this is still an issue on your side, feel free to reopen :)
