### ISSUE TITLE
Invalid flag '-optionVarChanged' 

### ISSUE THREAD

**Issue by wandth** [Autodesk/maya-usd#1580]
hello when I install mayausd plugin for maya2020.4 and load it
it has a error
```
// Error: file: C:/Program Files/Autodesk/MayaUSD/Maya2020/0.10.0_202106052251-73d6513/mayausd/MayaUSD/plugin/adsk/scripts/mayaUsdMenu.mel line 345: Invalid flag '-optionVarChanged' // 
```
platform:**maya2020.4**
mayausd: **version:0.10.0**

**Comment by seando-adsk** [comment]
Strange, we'll have to investigate. The flag "-optionVarChanged" was added to the "scriptJob" command in Maya 2019 so it should be available for you in Maya 2020.4.

**Comment by wandth** [comment]
@santosg87  I has uninstall mayaUsd0.10 and install mayausd 0.11, but it also has that error.
![image](https://user-images.githubusercontent.com/34237282/128795847-c09ae7ee-78b2-4a41-b79a-e583547deef3.png)

**Comment by wandth** [comment]
@santosg87 I will try to rebuild it,and thanks

**Comment by wandth** [comment]
@mike1158 I was recompile the plugin and change maya version to maya2019, the question is not appear,

**Comment by wandth** [comment]
@mike1158  and thanks you methord

**Comment by seando-adsk** [comment]
I reopened this issue, thanks to mike1158 who discovered the real problem. We should fix the flag so it works for all versions.
