### ISSUE TITLE
[MAYA-112854] mayaUSDImport throws USDZ related error when importing other file types

### ISSUE THREAD

**Issue by wjwilson** [Autodesk/maya-usd#1588]
**Describe the bug**
`mayaUSDImport` throws the following error when importing any form of USD file:

`# Error: The directory specified for USDZ texture imports: P:\current\project\sourceimages is not valid. # `

It is accurate that this folder does not exist, but I get this same error when importing a USDA with no textures. Setting `importUSDZTextures=False` has no effect. I can suppress the error by pointing `importUSDZTexturesFilePath` to some folder that exists (the temp folder for example), but I don't believe I should be seeing this error in the first place.

**Steps to reproduce**
1. Set the project to a location that does not have a "sourceimages" subfolder
2. Run `cmds.mayaUSDImport(file="path/to/any/usd.usda")`

**Expected behavior**
The USD file should be imported without error

**Specs (if applicable):**
 - Windows 10
 - Maya 2022
 - Python 3
 - maya-usd 0.10.0

**Comment by santosd** [comment]
Validated internally that this issue is resolved.
