### ISSUE TITLE
Build USD Maya with Renderman

### ISSUE THREAD

**Issue by suekieza** [Autodesk/maya-usd#159]
Hey there,

Been trying to build USD with renderman, so far no luck. I turn the flag on for prman and prman location but it gives me this error.

![Screenshot from 2019-12-05 16-19-15](https://user-images.githubusercontent.com/53234220/70243393-2bb63880-177b-11ea-99e8-5872f52fd75b.png)

Question:
1. Am I going about this the right way, as in: I turn on the flags when I compile USD PXR.
2. Will it pick up with Renderman 23 environment paths, like arnold(hydra) does or will I need to link to the renderman folder under USD called third party.
3. Do I need to do anything with usd-maya?

Thanks Sue 
[CMakeOutput.log](https://github.com/Autodesk/maya-usd/files/3927270/CMakeOutput.log)
[CMakeError.log](https://github.com/Autodesk/maya-usd/files/3927272/CMakeError.log)
[log.txt](https://github.com/Autodesk/maya-usd/files/3927273/log.txt)

**Comment by suesauer** [comment]
This seems to be a renderman 23 issue see:
https://github.com/PixarAnimationStudios/USD/issues/1054

**Comment by kxl-adsk** [comment]
@suesauer - any reason to keep this ticket open?

**Comment by suesauer** [comment]
Will post an update for when Renderman 23 is integrated. Or should I just close it?

**Comment by kxl-adsk** [comment]
If someone needs to track the status of this issue, then PixarAnimationStudios/USD#1054 is the place. 
Please close this one.
