### ISSUE TITLE
zips bundled in releases target Maya 2020, incompatible with Maya 2022?

### ISSUE THREAD

**Issue by AndrewSB** [Autodesk/maya-usd#1590]
Hey! I was trying to update the version of the plugin I was using. Maya 2022 seems to be bundled with maya-usd `0.8.0`. Downloading the macOS zip from https://github.com/Autodesk/maya-usd/releases/tag/v0.10.0, and using the wizard seems to installs the plugin at `/Applications/Autodesk/mayausd/maya2020/0.10.0_202106052251-73d6513/`. Which _may_ be incompatible with Maya 2020 (notice the `/maya2020/` in that path).

Attempting to install the plugin in Maya 2022, by selecting `/Applications/Autodesk/mayausd/maya2020/0.10.0_202106052251-73d6513/mayausd/MayaUSD/plugin/adsk/plugin/mayaUsdPlugin.bundle` shows the following error:

```
// Error: file: /Applications/Autodesk/maya2022/Maya.app/Contents/scripts/others/pluginWin.mel line 934: Unable to dynamically load : /Applications/Autodesk/mayausd/maya2020/0.10.0_202106052251-73d6513/mayausd/MayaUSD/plugin/adsk/plugin/mayaUsdPlugin.bundle
dlopen(/Applications/Autodesk/mayausd/maya2020/0.10.0_202106052251-73d6513/mayausd/MayaUSD/plugin/adsk/plugin/mayaUsdPlugin.bundle, 1): Library not loaded: @rpath/libufe_1.dylib
  Referenced from: /Applications/Autodesk/mayausd/maya2020/0.10.0_202106052251-73d6513/mayausd/MayaUSD/plugin/adsk/plugin/mayaUsdPlugin.bundle
  Reason: image not found // 
// Error: file: /Applications/Autodesk/maya2022/Maya.app/Contents/scripts/others/pluginWin.mel line 934: dlopen(/Applications/Autodesk/mayausd/maya2020/0.10.0_202106052251-73d6513/mayausd/MayaUSD/plugin/adsk/plugin/mayaUsdPlugin.bundle, 1): Library not loaded: @rpath/libufe_1.dylib
  Referenced from: /Applications/Autodesk/mayausd/maya2020/0.10.0_202106052251-73d6513/mayausd/MayaUSD/plugin/adsk/plugin/mayaUsdPlugin.bundle
  Reason: image not found (mayaUsdPlugin) // 
updatePluginCallback();
// Warning: file: /Applications/Autodesk/maya2022/Maya.app/Contents/scripts/others/pluginWin.mel line 937: Could not load /Applications/Autodesk/mayausd/maya2020/0.10.0_202106052251-73d6513/mayausd/MayaUSD/plugin/adsk/plugin/mayaUsdPlugin.bundle as a plug-in // 
```

I am a novice with Maya, so I'm not sure if I'm missing something obvious, or if the prebuilt plugins are incompatible with newer Maya

**Comment by seando-adsk** [comment]
Just to verify - you are using Maya 2022? Did you download and install the MayaUsd plugin (v0.10.0) for Maya 2022? We provide binaries for both Maya 2020 and Maya 2022.

**Comment by AndrewSB** [comment]
my mistake, sorry about that! I glazed over the Maya version in the release and picked `MayaUSD_0.10.0_Maya2020_MacOS_.dmg` instead of `MayaUSD_0.10.0_Maya2022_OSX.dmg`
