### ISSUE TITLE
[EMSUSD-676] Custom Right click in Viewport 2.0 would be great to be an extension of the outliner.

### ISSUE THREAD

**Issue by swillisart** [Autodesk/maya-usd#1595]
**Is your feature request related to a problem? Please describe.**
Currently no right click context menu / marking menu is shown when a user right clicks a USD shape in the Viewport.

**Describe the solution you'd like**
It's much more intuitive to manipulate items (Especially Varaints and LOD's) by selecting the shape(s) you wan to modify in the viewport.

**Describe alternatives you've considered**
An alternative could be provide a customizable user marking menu exclusively for USD.

**Additional context**
![image](https://user-images.githubusercontent.com/33715288/126694382-48179535-735c-4966-a2d4-021eb2906453.png)

I'd be happy to help with making a PR for this in Maya/Python if It aligns with the project vision.

**Comment by ppt-adsk** [comment]
Hi @swillisart, @wtelford is out of the office currently, but we have discussed this exact feature internally before, so without a doubt we'll be getting back to you.

**Comment by wtelford** [comment]
@santosd  can you log this internally.

**Comment by womanyoyoyo-adsk** [comment]
Hi @swillisart,

Please see the design [here](https://github.com/Autodesk/maya-usd/discussions/2301) for the viewport marking menu. Let me know if you have any feedback.

**Comment by womanyoyoyo-adsk** [comment]
@swillisart Maybe this will help you in the meantime: #1773

**Comment by swillisart** [comment]
Excellent thank you!

**Comment by santosg87** [comment]
this should be implemented now with #3375.

note that the change is not on a mayausd release build yet, so to see the change, its necessary to build mayausd with a later commit than the above. otherwise, this should be available on future mayausd releases
