### ISSUE TITLE
UFE Selection of prims bleeds over the edge causing selection of multiple prims

### ISSUE THREAD

**Issue by radon199** [Autodesk/maya-usd#160]
Hey,

When selecting Prims in the Maya viewport with VP2 and HydraGL I am seeing a area around the edge of all Prims where multiple selection of objects happens. This does not happen with Hydra selection in UsdView.

I wonder if it is due to the size of the render used for the selection?

Gif of the selection overlap : 
![selection](https://user-images.githubusercontent.com/39324245/70263063-62c02600-174a-11ea-900c-16703f00ea93.gif)

**Comment by HdC-adsk** [comment]
This is an issue of Maya 2019 (logged as MAYA-99586) and will be fixed in next update.

**Comment by radon199** [comment]
Thanks. Well wait for the update.

**Comment by BigRoy** [comment]
This seems to indeed be fixed in Maya 2020.

**Comment by HdC-adsk** [comment]
@BigRoy Thanks for confirming.

**Comment by cfmoore007** [comment]
Sounds like this can be closed ?

**Comment by HdC-adsk** [comment]
I think @radon199 is waiting for the next 2019 update to confirm.

**Comment by santosg87** [comment]
@radon199 Maya 2019.3 is now available. would you be able to validate and close this? :)

**Comment by santosg87** [comment]
marking this one as closed based on our internal testing. @radon199 if this is still a problem, feel free to re-open :)
