### ISSUE TITLE
Maya USD plug-in builds but wont load (Maya 2019/Linux CentOS 7.7)

### ISSUE THREAD

**Issue by HarryMichalakeas** [Autodesk/maya-usd#1639]
Hi Guys,

We are having difficulties getting maya-usd up and running for Maya 2019 under linux (Centos 7.7). We managed to get the USD core and it's dependencies to build, and maya-usd does build,
but we get the following errors while trying to load the plug-in:

loadPlugin "/local/hmichalakeas/tmp/maya-usd_build/install/RelWithDebInfo/plugin/adsk/plugin/mayaUsdPlugin.so";
translator mayaUsd_Schemas not found.: (kFailure): Unexpected Internal Failure
translator mayaUsd_Schemas not found.translator mayaUsd_Translators not found.: (kFailure): Unexpected Internal Failure
// Error: line 1: initializePlugin function failed (mayaUsdPlugin) // 

We built the plug-in as follows:
sudo ./build.py --maya-location /usr/autodesk/maya2019 --pxrusd-location /local/hmichalakeas/tmp/USD_build/USD --devkit-location /local/hmichalakeas/maya2019/devkitBase --build-args="-DBUILD_ADSK_PLUGIN=ON,-DBUILD_PXR_PLUGIN=ON,-DBUILD_TESTS=OFF,-DBUILD_AL_PLUGIN=OFF,-DBUILD_HDHYDRA=ON,-DBUILD_RFM_TRANSLATORS=ON,-DBUILD_STRICT_MODE=OFF" /local/hmichalakeas/tmp/maya-usd_build

We are running gcc 6.3.1 and cmake.3.14.5

Thanks in advance for any help you can give as we are stuck here!

Harry

**Comment by seando-adsk** [comment]
Did you set the MAYA_MODULE_PATH to point to the folder where your mayaUsd.mod file is located? Probably `/local/hmichalakeas/tmp/maya-usd_build/install/RelWithDebInfo`

If you look in the `.../install/RelWithDebInfo/lib` folder do you have the file `libmayaUsd_Schemas.so`?

**Comment by HarryMichalakeas** [comment]
> Did you set the MAYA_MODULE_PATH to point to the folder where your mayaUsd.mod file is located? Probably `/local/hmichalakeas/tmp/maya-usd_build/install/RelWithDebInfo`
> 
> If you look in the `.../install/RelWithDebInfo/lib` folder do you have the file `libmayaUsd_Schemas.so`?

Setting the module path did the trick! Thank you!

**Comment by seando-adsk** [comment]
Excellent. I'm going to close this issue then.

**Comment by HarryMichalakeas** [comment]
> Excellent. I'm going to close this issue then.

Thanks again for the help! Have a nice day!
