### ISSUE TITLE
refactoring_sandbox : VP2 Delegate : Prims in Duplicated ProxyShapes Move Together

### ISSUE THREAD

**Issue by cfmoore007** [Autodesk/maya-usd#164]
**Issue :**

While testing PR#162, after I duplicated the proxyShape, I tried to move one of the sphere prims within one of the shapes.

When moving the prim in the one proxyShape, the prim with the same name is also moving in the other shape.  

![duplicateMovesSameTime](https://user-images.githubusercontent.com/2152250/70359378-c54c1b80-1849-11ea-8fd8-e3bde3da91d7.png)

This is not expected.

This occurs when there are session edits ( or not ).

**Steps to re-produce :
[3_Spheres.zip](https://github.com/Autodesk/maya-usd/files/3934157/3_Spheres.zip)
**

open maya ( UFE does not need to be set, just the envar for VP2_RENDER_DELEGATE_PROXY )
2) import an AL proxyShape :

import maya.cmds as cmds
cmds.loadPlugin ("AL_USDMayaPlugin")

```
# import proxyShape
cmds.AL_usdmaya_ProxyShapeImport(file="3_Spheres.usda")

# select and duplicate
cmds.select("AL_usdmaya_Proxy",r=True)
cmds.duplicate()

# select a prim and move it
```

**Comment by santosg87** [comment]
I can reproduce this on our side as well. this might be related to the session layer when modifying the objects, as they both reference in the same usd file. 

I can also reproduce this behavior by creating 2 stages using the same usd file (instead of doing a duplicate)

**Comment by cfmoore007** [comment]
I just tested this against Maya USD 0.6.0 w/ PR121 and the problem still exists.

**Comment by bfloch** [comment]
This is not a viable solution, but we found as temporary workaround - if you duplicate special and set to duplicate the input graph it will duplicate the StageDataNode, which eliminates the single stage/layer problem.
Edits will be unique again.

**Comment by kxl-adsk** [comment]
Linking with #1142 . 

@cfmoore007 and/or @bfloch - do you think you could give the above pull request a try?

**Comment by cfmoore007** [comment]
@kxl-adsk I just tried it and still see the issue as described in the ticket.  Note : this time, I'm using the Maya ProxyShape.

**Comment by cfmoore007** [comment]
After Kristian's note, when the edit target is not set to a file backed layer ( i.e : the session layer ), it works :

![duplicateFixed](https://user-images.githubusercontent.com/2152250/106791151-8d459180-6622-11eb-972a-a8a48d5d869f.png)

**Comment by santosg87** [comment]
closing this based on the internal testing and the comment above. :)
