### ISSUE TITLE
Maya UFE : Child Prims Not Displayed in Maya Outliner Under Instanceable Prim

### ISSUE THREAD

**Issue by cfmoore007** [Autodesk/maya-usd#166]
**Issue :**

It seems UFE does not like to display prims underneath a payload that is marked as 'instanceable'.  

The UFE Outliner shows only the payload prim.

![screenshot](https://user-images.githubusercontent.com/2152250/70470332-c921ad00-1a98-11ea-857b-537c85877651.jpg)

Also, when trying to select one of the prims, the following warning is printed out to the terminal :

"
Warning: in getInstancedSelectionPath at line 517 of maya-usd/lib/render/vp2RenderDelegate/proxyRenderDelegate.cpp – UFE runtime is not updated for the USD stage. Please save scene and reopen.
"
Saving and re-opening the scene results in the same issue.

So, this appears to affect :
- UFE Outliner representation ( missing prims )
- UFE Viewport selection ( broken )

**Steps to Re-produce :**
1) open included .usda files
2) expand UFE prims in the outliner

Tested with maya-usd dev branch at commit : b77aa8fd

Example Files :
- [PrimsNotDisplayedUnderInstanceablePayload.tar.gz](https://github.com/Autodesk/maya-usd/files/3941598/PrimsNotDisplayedUnderInstanceablePayload.tar.gz)
- payload_instanced.usda
- payload_noninstanced.usda
- screenshot.jpg

**Comment by cfmoore007** [comment]
Actually, this seems to be a duplicate of https://github.com/Autodesk/maya-usd/issues/153

**Comment by cfmoore007** [comment]
Here is a file with 2 instances from the same master.
Both do not show their prims under the payload Xform.
When selecting a sphere in the viewport, the payload prim is selected ( so it selects all 3 ).
![screenshot2](https://user-images.githubusercontent.com/2152250/70715391-33646880-1cb8-11ea-83af-c0d1216fa9bf.jpg)

[payload_instanced_2.tar.gz](https://github.com/Autodesk/maya-usd/files/3955859/payload_instanced_2.tar.gz)

**Comment by cfmoore007** [comment]
And one more example w/o the nested payload ( also does not work, with the same results ) :
![screenshot3](https://user-images.githubusercontent.com/2152250/70716591-a1119400-1cba-11ea-9177-2656fdec170a.jpg)

[payload_instanced_3.tar.gz](https://github.com/Autodesk/maya-usd/files/3955947/payload_instanced_3.tar.gz)

**Comment by cfmoore007** [comment]
It seems that the same selection behavior occurs in usdview :
![usdviewInstancedPayloadSelection](https://user-images.githubusercontent.com/2152250/71031310-22b15980-20e1-11ea-931e-df813961b717.jpg)

However, all prims are still listed in the outliner.   The Luma USD Outliner also shows all prims.

It seems in order to move the prims individually, instancing must be broken.

**Comment by kxl-adsk** [comment]
@cfmoore007 based on your findings, should we update the description?

**Comment by cfmoore007** [comment]
Sure.

I think it is reasonable that the expectation here is that the prims are still displayed.  We will limit this issue to that specifically.

From there, we get into workflows where one may want to disable instancing to be able to access and actually modify the child prim.  We'll leave that for a topic for another time :)

**Comment by cfmoore007** [comment]
Also having instanceable prims displayed in the outliner can support workflows like selecting some prims and marking them as instances for each other.  Or, selecting some prims and de-instancing them to allow for other overrides.

**Comment by kxl-adsk** [comment]
Fixed by #354 , @cfmoore007 can we close this issue?

**Comment by pilarmolinalopez** [comment]
yes, we can. Thanks @kxl-adsk !
