### ISSUE TITLE
Default attributes for Light type prims do not match

### ISSUE THREAD

**Issue by jcoelho88** [Autodesk/maya-usd#1664]
Hello,

I noticed that when brining in lights defined in Maya to Houdini or from Houdini to Maya that some of the default attributes did not match, and were therefore ignore outside the DCC that defined them.

To see what I mean you can run this code snippet in Maya's script Editor or Houdini's Python Source Editor.

```python
# Pixar
from pxr import Usd, UsdGeom, Sdf

stage = Usd.Stage.CreateInMemory()
prim = stage.DefinePrim('/test_light', 'SphereLight')

for attr in prim.GetAttributes():
    print attr
```

Here is the results for Houdini:

![image](https://user-images.githubusercontent.com/88895104/131387975-fee6264e-b996-461a-9662-ac86909195d4.png)

Results from Maya:

![image](https://user-images.githubusercontent.com/88895104/131388058-d150bd63-4d7b-4628-920c-c67d90e55bb2.png)

In the results from Maya you can see there is an added namespace (inputs:), I'm not sure what it was created for but I expected that a prim like "SphereLight" would have been defined in both DCC's the same way.

I will also be writing to SideFx support the same question.

Why would these be different?

Any insight into this would be helpful.

Maya 2022.1, Maya-usd 0.10.0

Houdini 18.5.596

Cheers,

Jason Coelho

**Comment by kxl-adsk** [comment]
Hi Jason. Can you verify USD version that is used by both applications? Starting USD 21.05 "UsdLux Shadow and Shaping APIs are now connectable. All attributes on these APIs have been given the "inputs:" prefix."

Cheers,
KxL

**Comment by jcoelho88** [comment]
Hi @kxl-adsk,

Maya is reporting (0, 21, 2)
Houdini is reporting (0, 20, 8)

So based off of your response the version of USD in 18.5.596 is not using the prefix.

Thank you for your time, I'll look out for an update on SideFx side to see when this might get updated, hopefully by Houdini 19.

I'll close this issue.

Cheers,

Jason Coelho
