### ISSUE TITLE
Maya 2020 with UFE v2 features fails to build

### ISSUE THREAD

**Issue by BigRoy** [Autodesk/maya-usd#168]
### Issue

I tried compiling `maya-usd` with the `refactoring_sandbox`  with commit `5e5dc8f23` against Maya 2020 devkit on Windows 10 with the UFE v2 option enabled: `--build-args=-DCMAKE_UFE_V2_FEATURES_AVAILABLE=True`.

It failed to build succesfully. Build log:
[build_log.txt](https://github.com/Autodesk/maya-usd/files/3946761/build_log.txt)

Errors near the end:
```
       (ClCompile target) -> 
d:\dev\usd\maya-usd\lib\ufe\usdattribute.h(20): fatal error C1083: Cannot open include file: 'ufe/attribute.h': No such file or directory (compiling source file D:\dev\usd\maya-usd\lib\ufe\UsdAttribute.cpp) [D:\git_pipeline\rez-packages\maya_usd\build\platform-windows\arch==AMD64\maya-usd\lib\mayaUsd.vcxproj]
d:\dev\usd\maya-usd\lib\ufe\usdundocreategroupcommand.cpp(75): error C2039: 'createGroup': is not a member of 'Ufe_v1::Hierarchy' [D:\git_pipeline\rez-packages\maya_usd\build\platform-windows\arch==AMD64\maya-usd\lib\mayaUsd.vcxproj]
d:\dev\usd\maya-usd\lib\ufe\usdattribute.h(20): fatal error C1083: Cannot open include file: 'ufe/attribute.h': No such file or directory (compiling source file D:\dev\usd\maya-usd\lib\ufe\UsdAttributes.cpp) [D:\git_pipeline\rez-packages\maya_usd\build\platform-windows\arch==AMD64\maya-usd\lib\mayaUsd.vcxproj]
d:\dev\usd\maya-usd\lib\ufe\usdattribute.h(20): fatal error C1083: Cannot open include file: 'ufe/attribute.h': No such file or directory (compiling source file D:\dev\usd\maya-usd\lib\ufe\UsdAttributesHandler.cpp) [D:\git_pipeline\rez-packages\maya_usd\build\platform-windows\arch==AMD64\maya-usd\lib\mayaUsd.vcxproj]
```

Used [this Maya 2020 devkit](https://s3-us-west-2.amazonaws.com/autodesk-adn-transfer/ADN+Extranet/M%26E/Maya/devkit+2020/Autodesk_Maya_2020_DEVKIT_Windows.zip).

The devkit also contains no `ufe/attribute.h` file. Nor does a file named like that exist anywhere in `devkitBase/`.

---

Or wait... is Maya 2020 Gold still on UFE v1?
```
-- UFE include dir: D:/rez_packages/maya_devkit/2020/platform-windows/devkitBase/devkit/ufe/include
-- UFE library: D:/rez_packages/maya_devkit/2020/platform-windows/devkitBase/devkit/ufe/lib/ufe_1.lib
-- UFE version: 1.0.0
-- Building with UFE 1.0.0 features enabled.
```

**Comment by kxl-adsk** [comment]
Correct, Maya 2020 Gold still have UFE v1.

**Comment by BigRoy** [comment]
Does that mean the Display as shown on [right hand side here](https://area.autodesk.com/dynamic_resources/area_blog_post_content/3189/html_content/31573663744.png) is not available in Maya 2019 nor 2020?

![](https://area.autodesk.com/dynamic_resources/area_blog_post_content/3189/html_content/31573663744.png)
[Source](https://area.autodesk.com/blogs/the-maya-blog/usd-plugin-for-maya-fundamental-pillars/)

Or should I be looking for something else for that?

**Comment by seando-adsk** [comment]
That is correct. The AE display on the right requires UFE v2 and changes in that Maya that are not part of 2020 (or 2019).

**Comment by BigRoy** [comment]
Thanks for the clarification. I'll close this issue as it's expected to not work with Maya 2020 gold release because of the lack of UFE v2.
