### ISSUE TITLE
Unexpected visibility when switching render purpose

### ISSUE THREAD

**Issue by csyshing** [Autodesk/maya-usd#1685]
**Describe the bug**

Hi,

In my USD file, there are two render purposes, each purpose has two prims, one is visible by default, the other is invisible by default; but the visibility attribute is not respected when switching render purpose.

The USD is like this:
```
#usda 1.0
(
    defaultPrim = "root"
)

def Xform "root"
{
    def Xform "GEO"
    {
        rel proxyPrim = </root/GEO_PROXY>
        uniform token purpose = "render"
        def Cube "vis_cube"
        {
            double3 xformOp:translate = (0, 0, 0)
            uniform token[] xformOpOrder = ["xformOp:translate"]
        }
        def Cube "invis_cube"
        {
            token visibility = "invisible"
            double3 xformOp:translate = (2, 0, 0)
            uniform token[] xformOpOrder = ["xformOp:translate"]
        }
    }

    def Xform "GEO_PROXY"
    {
        uniform token purpose = "proxy"
        def Sphere "vis_sphere"
        {
            double3 xformOp:translate = (0, 0, 2)
            uniform token[] xformOpOrder = ["xformOp:translate"]
        }
        uniform token purpose = "proxy"
        def Sphere "invis_sphere"
        {
            token visibility = "invisible"
            double3 xformOp:translate = (2, 0, 2)
            uniform token[] xformOpOrder = ["xformOp:translate"]
        }
    }
}
```

Suspecting it's related to vp2RenderDelegate.

Thanks,
Zhicheng

**Steps to reproduce**
1. Launch Maya and load the USD file (above), by default, the **Purpose** on ProxyShape node should have the **proxy** being on, and there should be only one prim on viewport: **/root/GEO_PROXY/vis_sphere**; 
2. Now turn on the **render** purpose on the ProxyShape, we expect only **/root/GEO/vis_cube** should be displayed but **/root/GEO/invis_cube** is also showing up on viewport.

This problem does not happen when USD storm is used (usdview or **MAYAUSD_DISABLE_VP2_RENDER_DELEGATE**=1) 

**Expected behavior**
Prim visibility attribute should be respected when switching purpose.

**Specs (if applicable):**
 - OS & version CentOS 7.4
 - Compiler & version gcc 6.3.1
 - Maya version [e.g. Maya 2020/Maya 2022
 - Maya USD commit SHA Tested with v0.10.0 (should be reproducible in v0.11.0 and v0.12.0)
 - Pixar USD commit SHA official USD-20.11

**Comment by santosd** [comment]
Hello @csyshing, I am wondering what version of Maya and Maya USD you are using. I tested using Maya 2022.1 and Maya USD 0.11.0 and I was not able to reproduce the issue in the file you provided:
![visibilityIssueGH1685](https://user-images.githubusercontent.com/29235905/132733407-4910be6b-5808-48eb-9425-67a1c6f2d271.gif)

**Comment by csyshing** [comment]
I was testing against v0.10 but didn't realize v0.11 has fixed this issue. I think this ticket can be canceled then. Thanks @santosd !
