### ISSUE TITLE
Camera schema translator doesn't work in standalone mode, works in GUI mode

### ISSUE THREAD

**Issue by mhamid3d** [Autodesk/maya-usd#1704]
When trying to do a Usd export of a camera from maya standalone via python, the camera is mis-classed  as a Xform instead of a Camera in the USD scenegraph. When I do the same python export command in Maya GUI, it works fine and the object is classed as a Camera.

This is the python command (this is a global command that I run for all usd publishes, so it works on geometry even in standalone mode, just not on cameras):

```
import maya.standalone as sa

sa.initialize()

import maya.cmds as mc

mc.loadPlugin("mayaUsdPlugin")
mc.loadPlugin("pxrUsd")

mc.select("|renderCamera")

mc.mayaUSDExport(
    file='/path/to/my/cam.usd',
    chaser=['alembic'],
    chaserArgs=[
        ('alembic', 'primvarprefix', 'MYPREFIX_=MYPREFIX_')
    ],
    shadingMode='none',
    selection=True,
    kind='component',
    exportDisplayColor=True,
    defaultMeshScheme='catmullClark',
    frameRange=[1001, 1001]
)
```

In the log I did notice this error when loading the usd plugins through python:

```
translator mayaUsd_Schemas not found.: (kFailure): Unexpected Internal Failure
translator mayaUsd_Schemas not found.translator mayaUsd_Translators not found.: (kFailure): Unexpected Internal Failure
Error: initializePlugin function failed (mayaUsdPlugin)
```

Maya USD Version: 0.12.0
USD Version: 21.08
OS: Centos 7

**Comment by kxl-adsk** [comment]
@mhamid3d Translators and schemas are two separate libraries that are discovered by the plugin via `PXR_PLUGINPATH_NAME`. When running in UI mode, you will get it set via `.mod` file (https://github.com/Autodesk/maya-usd/blob/dev/modules/mayaUSD_Win.mod.template#L21). I believe you may be missing it in your env setting when running standalone mode.

**Comment by mhamid3d** [comment]
@kxl-adsk I've just run maya standalone in `mayapy` to confirm this and actually `PXR_PLUGINPATH_NAME` are identical in both GUI mode and standalone. I would assume if it recognizes the plugin then that means the operations to load the module war ran. Is there any other environment variable I can check to see what's going wrong? Have you tried to reproduce this problem on your end?

**Comment by mhamid3d** [comment]
I've just found the issue. In my script I had `from pxr import Usd`, however it was being imported before maya initialization AND before `mc.loadPlugin('pxrUsd')`. The solution is the move `from pxr import Usd` after the plugins have loaded!

**Comment by kxl-adsk** [comment]
Thx for sharing @mhamid3d!
