### ISSUE TITLE
dev: Non-UFE: VP2 Proxy - AL sub-item selection not working

### ISSUE THREAD

**Issue by pmolodo** [Autodesk/maya-usd#171]
I tried building the latest dev branch recently, without UFE enabled, and selection of specific meshes within a USD with the AL proxy shape seems to be broken.

I was building against maya-2019.2.

Can anyone else confirm this?

**Comment by elrond79** [comment]
So, I realized the problem was because I was using the mayaUsd.mod, which sets

VP2_RENDER_DELEGATE_PROXY=1

Once I disabled this, selection works

I renamed the ticket to reflect this new info...

**Comment by elrond79** [comment]
Also, I think until this is resolved, we may want to NOT set VP2_RENDER_DELEGATE_PROXY by default in the .mod file, as item selection is a very important feature of the plugin...

**Comment by pmolodo** [comment]
This is an old ticket, and selection has undergone major changes since then, so I'm going to close the ticket.  Can re-open if needed.
