### ISSUE TITLE
[MAYA-114695] Exporting Custom Float2 Attribute Not Animated

### ISSUE THREAD

**Issue by lijenicol** [Autodesk/maya-usd#1712]
**Describe the bug**
When exporting an animated, compound float2 attribute as a primvar, animation is lost. This happens when I tag the parent attribute of the compound attr to be exported. When I tag the child attributes of the compound attribute to be exported, the primvars in the exported USD are animated (but they're not one single float2 anymore). This doesn't seem right, as it would mean there is no way to export a float2 primvar.

**Steps to reproduce**
1. Create a cube
2. Create a compound float2 attribute on the cube
3. Add a couple of keyframes and change the values of the float2 at different times
4. In the USD user exported attributes UI, tag the parent float2 attribute to be exported as a primvar
5. Export the object (making sure it's setup to export animation)

I have included a scene file attached with steps 1-4 already done - you should be able to see a cube with an animated attribute titled "Float2Test"  on its transform.

**Expected behavior**
I expected to see the primvar in the exported USD to be an animated float2. Upon inspection, I saw the float2 primvar, however it was not animated. 

**Specs (if applicable):**
- OS & version [CentOS 7]
- Compiler & version [gcc 6.3.1]
- Maya version [Maya 2020]
- Maya USD commit SHA [dev at 0c906e8]

**Example scene:**
https://drive.google.com/drive/folders/1lpaYZgjDk73suPkBWWBrRbbN21uZrt3k

**Comment by santosg87** [comment]
hi @lijenicol quick question on how you are exporting. from your steps, I should be safe to assume you are using export selection? when i do a "export all", i do see my animation exporting. is that the case for you as well?

**Comment by lijenicol** [comment]
hey @santosg87, yes that is correct, I was using export selection. I just ran a test "export all" and I did notice that the animation still wasn't exporting so I am unsure as to what the error is. Did you find animation wasn't exporting when using export selection?

**Comment by lijenicol** [comment]
hey @santosg87, just checking in to see if there are any updates on this

**Comment by santosg87** [comment]
Hi @lijenicol Sorry for the delay on this one. took me some time to reproduce this, but i can see the issue on my side as well. it seems our exporter can't support the animation on custom nodes. we will look into it to figure out the next steps.
