### ISSUE TITLE
MEL Select Command Errors out on selecting prims in Outliner

### ISSUE THREAD

**Issue by ansuter** [Autodesk/maya-usd#1719]
**Describe the bug**
I searched through issues, and didn't see this one, but please close if it's a dupe.
![image](https://user-images.githubusercontent.com/16786318/134396044-be86072f-73dd-4086-b316-edbe5800d240.png)
When I select something in the outliner like Cone1, the script editor outputs:
```select -r |stage1|stageShape1,/Scope1/Cone1 ;```
But when I try and re-run that command I get an error.
```
select -r |stage1|stageShape1,/Scope1/Cone1 ;
// Error: select -r |stage1|stageShape1,/Scope1/Cone1 ; // 
```
The bug here seems to be that what the script editor outputs is incorrect or doesn't process the USD path properly.

**Steps to reproduce**

1. Create Stage with new layer
2. Add scope
3. Add cone
4. try and select cone programmatically in script editor

**Expected behavior**
The script editor command should reflect what the outliner is doing.
If I select in outliner and it prints a command, I'd expect the command to work directly next time.

Top command is from outliner, second command is called directly.
```
select -r |stage1|stageShape1,/Scope1/Cone1 ;
select -r |stage1|stageShape1,/Scope1/Cone1 ;
// Error: select -r |stage1|stageShape1,/Scope1/Cone1 ; // 
// Error: Line 1.30: Syntax error // 
```

**Specs (if applicable):**
 - OS & version [e.g. Windows 10]. Win 10
 - Compiler & version [e.g. gcc 6.3.1].
 - Maya version [e.g. Maya 2020]. 2022.1
 - Maya USD commit SHA [e.g. dev at caa921c1] MayaUSD 0.8 - 392b2fe07ad88a4866aac0f5f819cd5241fcbe31
 - Pixar USD commit SHA [e.g. dev at b85ddac2]

**Comment by seando-adsk** [comment]
This is already a known issue and logged internally as:
MAYA-112136 - Attempting to run select echoed command for USD prim results in syntax error

As a workaround you simply need to surround the string with quotes ("), like so:
```select -r "|stage1|stageShape1,/Scope1/Cone1" ;```

**Comment by ppt-adsk** [comment]
Hey @ansuter thanks for reaching out.  @seando-adsk beat me to the response :)  We have a proposed fix to MAYA-112136, but the trouble is that it's a Maya-side bug, not a plugin-side bug, so it might take a while to reach you.  Use Sean's workaround in the meantime.

Note that this is just for UFE paths as string literals, not in MEL variables, so the following works fine:
string $myPath = "|stage1|stageShape1,/Scope1/Cone1";
select -r $myPath

Cheers.

**Comment by ansuter** [comment]
Awesome! Thank you both!!! I'll mark as closed since you have an internal ticket already!
