### ISSUE TITLE
getting errors when trying to build for windows

### ISSUE THREAD

**Issue by Ryanagogo** [Autodesk/maya-usd#174]
I'm running the windows build command, provided from step 7 of the build docs, and I'm getting errors. I would like to build this for maya 2019.

I've attached what was reported from the powershell

[build_error_from_powershell_12-12-19.txt](https://github.com/Autodesk/maya-usd/files/3952946/build_error_from_powershell_12-12-19.txt)

**Comment by BigRoy** [comment]
It seems to fail on running `MSBuild.exe` as it can't find it. Hinting at your environment not being set up in such a way that it can detect it.

Can you try to run the build command from Visual Developer command prompt? That initializes some bits for the environment that many build scripts rely on. Usually for testing compiles it makes things easy to give that a quick go. If you go to Windows start menu and start typing "Developer command prompt" you should find it.

Then later if you'd really want to run the compile from this Powershell you could look into what environment variables the developer command prompt sets (e.g. run `set`) and then compare with your environment in Powershell and add what's missing.

**Comment by Ryanagogo** [comment]
Ok, I will try finding the visual developer command prompt.  The instructions in the build document don't say what we should be using, so I was just taking a guess and using powershell.
Unfortunately, there is no compiled plugin I can use for USD, so I'm having to try and figure out how to compile it myself.  There are many things I don't understand, so I'll try the best I can.
Ryan

    On Thursday, December 12, 2019, 02:15:29 PM GMT+9, Roy Nieterau <notifications@github.com> wrote:  
 
 
It seems to fail on running MSBuild.exe as it can't find it. Hinting at your environment not being set up in such a way that it can detect it.

Can you try to run the build command from Visual Developer command prompt? That initializes some bits for the environment that many build scripts rely on. Usually for testing compiles it makes things easy to give that a quick go. If you go to Windows start menu and start typing "Developer command prompt" you should find it.

Then later if you'd really want to run the compile from this Powershell you could look into what environment variables the developer command prompt sets (e.g. run set) and then compare with your environment in Powershell and add what's missing.

**Comment by Ryanagogo** [comment]
ok, I found the visual studio developer prompt, and I ran the windows build command, but I'm still getting errors.  I've attached a text file with the errors that were given.
Your help is greatly appreciated!
Ryan


    On Thursday, December 12, 2019, 02:15:29 PM GMT+9, Roy Nieterau <notifications@github.com> wrote:  
 
 
It seems to fail on running MSBuild.exe as it can't find it. Hinting at your environment not being set up in such a way that it can detect it.

Can you try to run the build command from Visual Developer command prompt? That initializes some bits for the environment that many build scripts rely on. Usually for testing compiles it makes things easy to give that a quick go. If you go to Windows start menu and start typing "Developer command prompt" you should find it.

Then later if you'd really want to run the compile from this Powershell you could look into what environment variables the developer command prompt sets (e.g. run set) and then compare with your environment in Powershell and add what's missing.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
  
C:\github\maya-usd>python build.py --maya-location "C:\Program Files\Autodesk\maya2019" --pxrusd-location C:\github\USD C:\workspace

Building with settings:
  Source directory          C:\github\maya-usd
  Workspace directory       C:\workspace
  Build directory           C:\workspace\build\RelWithDebInfo
  Install directory         C:\workspace\install\RelWithDebInfo
  Variant                   RelWithDebInfo
  CMake generator           Default
  Build Log                 C:\workspace\build\RelWithDebInfo\build_log.txt
  Stages arguments      ['clean', 'configure', 'build', 'install']
2019-12-13 07:16
cmake -DCMAKE_INSTALL_PREFIX="C:\workspace\install\RelWithDebInfo" -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -G "Visual Studio 15 2017 Win64" -DMAYA_LOCATION="C:\Program Files\Autodesk\maya2019" -DPXR_USD_LOCATION="C:\github\USD" "C:\github\maya-usd"
CMake Warning (dev) in CMakeLists.txt:
  No project() command is present.  The top-level CMakeLists.txt file must
  contain a literal, direct call to the project() command.  Add a line of
  code such as

    project(ProjectName)

  near the top of the file, but after cmake_minimum_required().

  CMake is pretending there is a "project(Project)" command on the first
  line.
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Error in CMakeLists.txt:
  Generator

    Visual Studio 15 2017 Win64

  could not find any instance of Visual Studio.



-- Configuring incomplete, errors occurred!
See also "C:/workspace/build/RelWithDebInfo/CMakeFiles/CMakeOutput.log".

Traceback (most recent call last):
  File "build.py", line 482, in <module>
    InstallMayaUSD(context, context.buildArgs, context.stagesArgs)
  File "build.py", line 319, in InstallMayaUSD
    RunCMake(context, extraArgs, stagesArgs)
  File "build.py", line 283, in RunCMake
    extraArgs=(" ".join(extraArgs) if extraArgs else "")))
  File "build.py", line 189, in Run
    .format(cmd=cmd, log=os.path.abspath(context.logFileLocation)))
RuntimeError: Failed to run 'cmake -DCMAKE_INSTALL_PREFIX="C:\workspace\install\RelWithDebInfo" -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -G "Visual Studio 15 2017 Win64" -DMAYA_LOCATION="C:\Program Files\Autodesk\maya2019" -DPXR_USD_LOCATION="C:\github\USD" "C:\github\maya-usd"'
See C:\workspace\build\RelWithDebInfo\build_log.txt for more details.

**Comment by BigRoy** [comment]
> Visual Studio 15 2017 Win64 
> could not find any instance of Visual Studio

Interesting. This could be related to you running explicitly a Developer Command prompt from visual studio that initializes to non-64bit if you had the wrong one. Because it now suddenly does seem to find VS 2017, because the builld script starts passing that along as Generator but then it can't actually find it.

Could you show:
- Which specific Visual Studio Developer Command prompt you are running?
- What is shown at the beginning when opening the dev command prompt?
- What versions of Visual Studio do you have installed? And more importantly, which one are you trying to use? Because it seems to differ between these two logs.

**Comment by Ryanagogo** [comment]
Thank you for getting back to me!
For Visual Studio, I downloaded the community edition and installed it, so I have the latest version, which is 2019.  The build document doesn't specify versions.
I've attached images of what I'm using for the command prompt and what is shown after I open a new command prompt.

Ryan



    On Friday, December 13, 2019, 04:39:07 PM GMT+9, Roy Nieterau <notifications@github.com> wrote:  
 
 

Visual Studio 15 2017 Win64
could not find any instance of Visual Studio


Interesting. This could be related to you running explicitly a Developer Command prompt from visual studio that initializes to non-64bit if you had the wrong one. Because it now suddenly does seem to find VS 2017, because the builld script starts passing that along as Generator but then it can't actually find it.

Could you show:
   
   - Which specific Visual Studio Developer Command prompt you are running?
   - What is shown at the beginning when opening the dev command prompt?
   - What versions of Visual Studio do you have installed? And more importantly, which one are you trying to use? Because it seems to differ between these two logs.

**Comment by BigRoy** [comment]
Hi Ryan,

I am not seeing any attachments. I believe you are replying by email. Could you try uploading the images straight to the Github issue section on the website in a new comment? You can drag and drop images into the text field.

Regarding Visual Studio version. I believe 2019 should work, but for what it's worth I have been using 2017 as that's still matching the compiler version with Maya 2020 I believe. You could give that a try too, but maybe your attachments and latest logs already give some more clues.

**Comment by Ryanagogo** [comment]
Ok, I uploaded the images here on the github issue section:

![Snag_c8c8574](https://user-images.githubusercontent.com/7549411/70845809-8bf15c80-1e96-11ea-8ead-19774101f0cb.png)
![Snag_c8ca88d](https://user-images.githubusercontent.com/7549411/70845810-8f84e380-1e96-11ea-8478-9ae75ee6802b.png)

After some research, I found I could install older versions of visual studio, for 2015 and 2017.  I also came to realize that step 7 for the windows build is missing some flags, so I tried to include those.  It's getting further into the build now, but I'm still getting errors, though this time they are different errors.  I've also included the output from the command prompt on this message.

Thank you again for your help!

Ryan

[build_error_from_powershell_12-14-19.txt](https://github.com/Autodesk/maya-usd/files/3963614/build_error_from_powershell_12-14-19.txt)

**Comment by BigRoy** [comment]
In this case you're forcing the `Ninja` generator which you shouldn't need to do unless you explicitly want that. I believe it's fine to do so, but it's not required.

Anyway, the error you're having now is that it is saying it can not find USD. What exactly is in the `C:\github\USD` folder that you passed along with `--pxrusd-location`? This should be the compiled USD repository, *not* the source code.

I have a hunch that you're pointing it to the source code because compiling with VS 2019 so far is non-trivial for USD due to some bugs, e.g. see [this issue](https://github.com/PixarAnimationStudios/USD/issues/1041) and [this issue](https://github.com/PixarAnimationStudios/USD/issues/1055). For now I'd recommend using VS 2017 and compiling USD itself with that. It should be relatively straightforward. Here's some [more information on compiling USD on Windows in its README](https://github.com/PixarAnimationStudios/USD#windows).

Then afterwards, use the same visual studio to compile `maya-usd` and hopefully you'll be having some more luck.

**Comment by Ryanagogo** [comment]
Ok, I used the VS 2017 Dev command prompt.  I built USD without error.  I tried building maya-usd with VS 2017, but it's running into an error.  I've included the output from the command prompt

[build_error_from_powershell_12-15-19.txt](https://github.com/Autodesk/maya-usd/files/3964407/build_error_from_powershell_12-15-19.txt)

**Comment by BigRoy** [comment]
Very good, you are almost there.

You are running into this error:
```
C:\github\maya-usd\plugin\pxr\maya\lib\usdMaya\shadingModeExporterContext.cpp(304): error C2672: 'SdfPathFindLongestPrefix': no matching overloaded function found [C:\workspace\build\RelWithDebInfo\plugin\pxr\maya\lib\usdMaya\usdMaya.vcxproj]
C:\github\maya-usd\plugin\pxr\maya\lib\usdMaya\shadingModeExporterContext.cpp(305): error C2780: 'BidirectionalIterator pxrInternal_v0_19__pxrReserved__::SdfPathFindLongestPrefix(BidirectionalIterator,BidirectionalIterator,const pxrInternal_v0_19__pxrReserved__::SdfPath &)': expects 3 arguments - 2 provided [C:\workspace\build\RelWithDebInfo\plugin\pxr\maya\lib\usdMaya\usdMaya.vcxproj]
  C:\USD\include\pxr/usd/sdf/path.h(759): note: see declaration of 'pxrInternal_v0_19__pxrReserved__::SdfPathFindLongestPrefix'
```

This hints at an incompatibility between `USD` and `maya-usd`. Between different versions of USD sometimes functions change in the amount of arguments they need or type of arguments. Or in other cases functions move around, it can be anything.

Luckily `maya-usd` describes what versions of `USD` should be compatible. And that depends on which branch of `maya-usd` you are compiling. This is found in [`doc/DEVELOPER.md`](https://github.com/Autodesk/maya-usd/blob/dev/doc/DEVELOPER.md#source-versions). Take a look there for the branch of `maya-usd` you are compiling, above I linked the `dev` branch.

The characters next to the versions you are seeing mentioned are git commit hashes. These refer to the exact commit of the `USD` git repository it was built and tested against. I'd recommend going with that one to be sure if you have no need for a specific other version of `USD`.

Hope that helps.

**Comment by Ryanagogo** [comment]
Ok, I built USD using the version from your link, and I was able to successfully build maya-usd.

I really appreciate your help!

I assume eventually maya will have USD, similar to how houdini now has USD?  It will be nice when we can just use USD without having to worry about all this compiling stuff

**Comment by BigRoy** [comment]
> I assume eventually maya will have USD, similar to how houdini now has USD? It will be nice when we can just use USD without having to worry about all this compiling stuff

It can be somewhat expected, yes, but there have been no official statements regarding that as far as I know. I imagine either that too happen or more automated builds/installers to become available for those who need it in the future.

Good luck with playing around with the plug-in that is currently heavily being developed. If you run into any bugs or issues make sure to report them and state your compiled version of `maya-usd` and `USD`. Many improvements are being done in rapid succession so keep checking back in if you're looking for particular fixes or features.

If your issue is resolved and you can continue make sure to close the issue.
