### ISSUE TITLE
[MAYA-113125] Same file fails to export USDZ Skinner across Windows and macOS

### ISSUE THREAD

**Issue by aaronn** [Autodesk/maya-usd#1758]
**Describe the bug**
On Windows I'm using Maya  2022.1, on macOS I'm using 2022. When I export a .usdz file from macOS, the skinner is exported alongside it just fine. If I open up that same Maya file on my Windows machine and export that same .usdz, with the same export settings, the Skinner fails to export.

This happens for every file with joints where a skinner is expected.

**Steps to reproduce**
1. Open an .mb file and select an object with joints to export as a USDZ on macOS (2022)
2. Export Selected -> Export as USDZ
3. Open the USDZ file in Xcode, and notice that the Skinner is present.
4. Open the same .mb file on Windows (2022.1) and perform the same steps.
5. Transform the file over to macOS, to open in Xcode.
6. Notice that the Skinner data is not present.

**Expected behavior**
The skinner data should be present, regardless of being exported from macOS, Windows, Maya 2022, or Maya 2022.1

**Attachments**
If applicable, add screenshots, sample files, etc to help explain your problem.

**Specs (if applicable):**
 - Windows 10 & macOS 11
 - Compiler & version: Unknown, not building manualy
 - Maya version: Maya 2022 on macOS and 2022.1 on Windows
 - Maya USD commit SHA: Unknown, whatever's included with each version

**Comment by santosg87** [comment]
thank you for the extra info @aaronn. I believe this is something tied to the Maya version itself. we have had something similar regarding FBX exporters on that Maya Version. I will link the Maya internal issue here, so we can keep track of things, and report once we have any updates on a possible fix, if we have one. :)

cheers!

**Comment by santosg87** [comment]
@aaronn this issue should now be fixed on Maya 2022.3 - are you able to give it a shot on that version and confirm? :)

cheers!
