### ISSUE TITLE
[MAYA-114374] Crash when parenting prims with composition arcs to prims with composition arcs

### ISSUE THREAD

**Issue by gracekumagai** [Autodesk/maya-usd#1762]
**Describe the bug**
When testing [Autodesk's example](https://help.autodesk.com/view/MAYAUL/2022/ENU/?guid=GUID-C27A9992-10DD-4F4C-8D34-B7D176336039) of parenting a prim with a composition arc and variant to a prim that also has a composition arc and variant, it crashes Maya. 
It crashes Maya regardless if the prims are loaded or unloaded.

**Steps to reproduce**
1. Open the "kitchen_set_instanced"
2. Navigate to: `|Kitchen_set_instanced|Kitchen_set_instancedShape,/Kitchen_set/Props_grp/North_grp/NorthWall_grp/MeasuringSpoon_2`
3. Parent `MeasuringSpoon_2` to `MeasuringSpoon_1`

Step 3 triggers the crash.

Top of the stack trace:
```
Stack trace:
  Usd_PrimData::GetParent() const
  MayaUsd_v0::ufe::UsdHierarchy::parent() const
  /dist/sw/maya/2022.update2/lib2/libSharedUI.so(+0x3e9844) [0x7fbc3e34a844]
  /dist/sw/maya/2022.update2/lib2/libSharedUI.so(+0x3e8a58) [0x7fbc3e349a58]
  /dist/sw/maya/2022.update2/lib2/libSharedUI.so(+0x3e2b89) [0x7fbc3e343b89]
  Ufe_v2::Subject::notify(Ufe_v2::Notification const&)
  Ufe_v2::Scene::notify(Ufe_v2::Notification const&)
  void MayaUsd_v0::ufe::sendNotification<Ufe_v2::ObjectReparent>(std::shared_ptr<Ufe_v2::SceneItem> const&, Ufe_v2::Path const&)
  MayaUsd_v0::ufe::UsdUndoInsertChildCommand::insertChildRedo()
  MayaUsd_v0::ufe::UsdUndoInsertChildCommand::redo()
  /dist/sw/maya/2022.update2/lib2/libShared.so(+0x4df606) [0x7fbc3ba0b606]
  TparentCmd::redoIt()
  TparentCmd::doIt(TargList&)
```

**Expected behavior**
Artists can commonly and accidentally parent a model to another model when dressing a set. We would expect Maya not to crash.

**Attachments**
![outliner - parent comp arc crash](https://user-images.githubusercontent.com/12554015/137760268-9ad4166e-4221-408d-9f55-f111e66e317e.gif)

**Specs (if applicable):**
 - OS (Linux 64 bit)
- Maya USD: dev at 4710d36
- Pixar USD: dev at 96c5a3f
- Maya 2022.update2 (& Maya 2022.base)

**Comment by santosd** [comment]
A fix for this has been merged feel free to build with the latest fixes and test again. I have validated the fix on my end, Feel free to reopen this if you come across any issues with it.

**Comment by gracekumagai** [comment]
Seems to be working on our end too! Thank you!
