### ISSUE TITLE
[MAYA-114369] Crash when duplicating groups with loaded descendants

### ISSUE THREAD

**Issue by gracekumagai** [Autodesk/maya-usd#1763]
**Describe the bug**
If you create a group with a loaded or unloaded model, load the group, duplicate the group and try to load the group with descendants, Maya will crash.

**Steps to reproduce**
1. Open 'kitchen_set_instanced'
2. Unload the `|Kitchen_set_instanced|Kitchen_set_instancedShape,/Kitchen_set`
3. Navigate to and click on the `|Kitchen_set_instanced|Kitchen_set_instancedShape,/Kitchen_set/Props_grp/North_grp/SinkArea_grp/FlowerPotB_1` or any prim with a composition arc / is a component.
4. Press Ctrl+g to group
5. Right click on group -> Load with Descendents
6. Click on group, ctrl+d to duplicate
7. Right click on the new duplicated group -> Load with Descendants

Step 7 will trigger the crash.

Error:
```
maya.bin crashed. FATAL ERROR: Failed axiom: ' _primIndex '
in GetSourcePrimIndex at line 104 of pxr/usd/usd/primData.cpp
```

If you skip step 5 and do not load the group with descendants before duplicating, it will not crash.
Maya will crash regardless if the initially grouped prim was initially loaded or unloaded.

**Expected behavior**
I would expect Maya to load the group and not crash.

**Specs (if applicable):**
- OS (Linux 64 bit)
- Maya USD: dev at 4710d36
- Pixar USD: dev at 96c5a3f
- Maya 2022.update2 (& Maya 2022.base)

**Comment by gracekumagai** [comment]
Hey @santosd, I encountered the same error during a crash with slightly different repro steps:
1. Open 'kitchen_set_instanced'
2. Unload `|Kitchen_set_instanced|Kitchen_set_instancedShape,/Kitchen_set/Props_grp/West_grp/Ball_1` 
3. Press Ctrl+g to group the unloaded `Ball_1`
4. Press Ctrl+z to undo the group action
5. Press Ctrl+d to duplicate `Ball_1`
6. Load the duplicate of `Ball_1`

Step 6 triggers the same crash error mentioned above.

![crash_duplicate_unload](https://user-images.githubusercontent.com/12554015/138364261-3d6cbe97-f11a-4cc9-8210-c829c9f9a11b.gif)
Let me know if you'd like me to file a new ticket. Thanks!

**Comment by santosg87** [comment]
HI @gracekumagai this issue should be fixed on the latest version of the plugin, are you able to confirm and close? :)

**Comment by gracekumagai** [comment]
Hi @santosd, this seems to be fixed now! Thank you!
