### ISSUE TITLE
Attribute Editor: Displays attributes and/or name from last selection and renaming can crash

### ISSUE THREAD

**Issue by gracekumagai** [Autodesk/maya-usd#1764]
**Describe the bug**
If you group a prim and then, create an xform, when selecting the newly created xform, the attribute editor will enter a state where it does not refresh properly. 
-  When clicking back and forth between an xform and another prim, when selecting the xform, it will display the attributes associated with whatever was previously selected. 
- When clicking back to another prim, it may display the name of the xform and type by the text box. In this state, renaming this prim in the AE will cause Maya to crash.

**Steps to reproduce**
1. Open a new file in Maya 2022
2. Navigate to Create -> Universal Scene Description (USD) -> Stage with new layer
3. Right click on the proxy shape -> Add new prim -> Capsule
4. Click on the capsule and press Ctrl+g to group
5. Click on the proxy shape and right click on the proxy shape -> Add new prim -> Xform
6. **BUG**: Click from the proxy shape to the newly created xform. It displays the attributes associated with the stage
7. **BUG**: Click from the xform to the capsule and back to the xform. It displays the attributes associated with the capsule. You can modify the capsule's attributes (ex: axis) and it will update the capsule (even though the xform is selected).
8. **BUG**: Click from the xform to the capsule. It displays the xform's name and type instead of the capsule's name and type. 
9. **CRASH**: With the capsule still selected, click on the text box which contains the xforms name. Try to rename the capsule in the attribute editor and Maya will crash.

Stack trace for the rename crash:
```
TcommandEngine::getErrorString(Tstring&, Tstring const&, TcommandEngine::eDisplayContext) const
  TcommandEngine::internalDisplayError(Tstring const&, TcommandEngine::eDisplayContext)
  /dist/sw/maya/2022.update2/lib2/libShared.so(+0x2b4d47) [0x7f998ac74d47]
  TmetaCommand::doCommand(TargList&)
  /dist/sw/maya/2022.update2/lib2/libCommandEngine.so(+0x9cf44) [0x7f9987200f44]
  /dist/sw/maya/2022.update2/lib2/libCommandEngine.so(+0xc7109) [0x7f998722b109]
  /dist/sw/maya/2022.update2/lib2/libCommandEngine.so(+0xc72a1) [0x7f998722b2a1]
  SophiaExecutable::evaluate(void*)
  TcommandEngine::executeCommand(Tstring const&, bool, bool, TmelCmdResult*, unsigned int)
  TcommandEngine::executeCommand(TargList const&, bool, bool)
  /dist/sw/maya/2022.update2/lib2/libSharedUI.so(+0x34b7d6) [0x7f998d7407d6]
  /dist/sw/maya/2022.update2/lib/libQt5Core.so.5(+0x2dd3b5) [0x7f99845b23b5]
  QmayaField::handleEditingFinished()
```

**Expected behavior**
I would expect the AE to display the attributes for the prim I have selected. I would also expect Maya not to crash.

**Attachments**
Steps 3-9:
![ae - displays attributes from last selection](https://user-images.githubusercontent.com/12554015/137768829-2318f3c8-acef-46b8-88bc-c090ea9476f4.gif)

**Specs (if applicable):**
- OS (Linux 64 bit)
- Maya USD: dev at 4710d36
- Pixar USD: dev at 96c5a3f
- Maya 2022.update2

**Additional context**
During step 7, when you have the xform selected but it displays the attributes of the capsule:
- You can manipulate the attributes of whatever was previously selected (ex: in the gif, I am manipulating the capsule's axis even though I've selected the xform). 
- However, if you use the transform manip, it will move the xform (you cannot see the transform in the attribute editor, you have to look at the layer). 
- It also does not let the user rename the xform (ex: in the gif, I cannot type in the text box in the AE).

If you create several xforms and select one after the other, the attributes displayed will match whatever non-xform was previously selected.

Once you are in this state, closing and re-opening the AE does not solve the issue. The user is required to re-open Maya in order to access the attributes again. 

I can occasionally reproduce this crash just by selecting xforms in the kitchen set or working with a new stage & only creating 1 xform (without the grouping steps), however, it seems to be easier to reproduce with the grouping step.

Please let me know if you would prefer if I break up this report into several smaller bugs.

**Comment by wtelford** [comment]
closing as it sounds like it would be addressed by #1769
