### ISSUE TITLE
Attribute Editor: Does not display translate, rotate, scale info for xforms created when grouping

### ISSUE THREAD

**Issue by gracekumagai** [Autodesk/maya-usd#1765]
**Describe the bug**
When using the transform manips to transform an xform that was created when grouping, the translate, rotate, and scale information is not displayed in the AE.

**Steps to reproduce**
1. Open a new file in Maya 2022
2. Navigate to Create -> Universal Scene Description (USD) -> Stage with new layer
3. Right click on the proxy shape -> Add new prim -> Capsule
4. Click on the Capsule and press Ctrl+g to create a group
5. Click on the xform that was just created
6. Manipulate the xform using the transform manips. Translate, scale, rotate are not populated for this prim in the AE.

**Expected behavior**
When using the transform manips on the xform, I would expect the transforms to be populated in the AE. 

**Attachments**
![xform_ae_transforms](https://user-images.githubusercontent.com/12554015/137771642-df8693fb-af0d-475a-b28b-79e87f1b896a.gif)

**Specs (if applicable):**
- OS (Linux 64 bit)
- Maya USD: dev at 4710d36
- Pixar USD: dev at 96c5a3f
- Maya 2022.update2

**Additional context**
This bug can be challenging to test due to: #1764 

When creating the group, the following is printed in the script editor:
```
// Error: file: /dist/sw/maya/2022.update2/scripts/others/showEditor.mel line 3702: RuntimeError: file <...>/nodes/usdschemabase/ae_template.py line 594: Assertion failed: "false"
	File: maya_open_source/maya-usd/lib/mayaUsd/ufe/UsdAttributes.cpp
	Line: 172
	Function: getUfeTypeForAttribute
	Description: Invalid USDAttribute! // 
```

**Comment by gracekumagai** [comment]
Hey @santosd - I wanted to let you know that I re-tested in maya 2022.update2 and maya 2023 PR132 and I'm no longer able to reproduce :) I wonder if it was an artifact of #1764. 

Feel free to close it out if the investigation is wrapped up on your end too - thanks!

**Comment by santosd** [comment]
Thank you @gracekumagai for the reply on this one. I will go ahead and close it out.
