### ISSUE TITLE
[MAYA-114346] Outliner - Load with descendants collapses expanded sibling hierarchies 

### ISSUE THREAD

**Issue by gracekumagai** [Autodesk/maya-usd#1766]
**Describe the bug**
If you "Load with Descendants" on a node and it has siblings (and children of the siblings) that are expanded, it will collapse everything. "Unload" does not impact the expanded hierarchy.

**Steps to reproduce**
1. Open 'kitchen_set_instanced'
2. Navigate to `|Kitchen_set_instanced|Kitchen_set_instancedShape,/Kitchen_set/Props_grp/DiningTable_grp`
3. Expand `|Kitchen_set_instanced|Kitchen_set_instancedShape,/Kitchen_set/Props_grp/DiningTable_grp/TableTop_grp`
4. Expand `|Kitchen_set_instanced|Kitchen_set_instancedShape,/Kitchen_set/Props_grp/DiningTable_grp/TableTop_grp/CerealBowl_grp`
5. Unload `|Kitchen_set_instanced|Kitchen_set_instancedShape,/Kitchen_set/Props_grp/DiningTable_grp/KitchenTable_1` (Note: no change to the collapsed/expanded sibling hierarchies)
6. **BUG**: Load `|Kitchen_set_instanced|Kitchen_set_instancedShape,/Kitchen_set/Props_grp/DiningTable_grp/KitchenTable_1`. Loading the `KitchenTable_1` will collapse the `CerealBowl_grp` and the `TableTop_grp`

**Expected behavior**
I would expect the loading operations to not impact the expanded/collapsed state of its siblings (similar to unload). 

**Attachments**
Steps 2-6 + Testing with the `CerealBowl_grp`
![outliner - load with siblings expanded collapses siblings](https://user-images.githubusercontent.com/12554015/137773016-cce434a7-3e82-4049-bf80-06bfdd556d43.gif)

**Specs (if applicable):**
OS (Linux 64 bit)
Maya USD: dev at 4710d36
Pixar USD: dev at 96c5a3f
Maya 2022.update2

**Comment by santosd** [comment]
I tested and reproduced this one and logged it internally as MAYA-114346.

**Comment by santosd** [comment]
Hi Grace, a fix for this has been merged if you would like to build with the latest changes and retest. I tested on my end and I see that the collapse issue is fixed and didn't notice any regressions. I will go ahead and close this ticket out for now, but feel free to let me know if you find anything and we can reopen if needed.

**Comment by gracekumagai** [comment]
Hi @santosd, I tried building with the latest changes and I'm still running into the same issue. Is the fix only available in a new PR? Thanks!

**Comment by gracekumagai** [comment]
Hey @santosd, I tested today with Maya 2023 and I'm still running into the same issue. Is the fix coming in an update to Maya 2023? Thanks!

**Comment by seando-adsk** [comment]
@gracekumagai / @santosg87 - The fix for this was in Maya (not in the plugin). So you will need the latest Maya PR to see the fix.

**Comment by santosd** [comment]
Let us know if you run into any issues.

**Comment by gracekumagai** [comment]
I tested in maya2023.2 and it's fixed! thank you!
