### ISSUE TITLE
[MAYA-114344] Outliner: When parenting a prim to a collapsed group, it auto-expands the group

### ISSUE THREAD

**Issue by gracekumagai** [Autodesk/maya-usd#1767]
**Describe the bug**
When MMB dragging a prim to a collapsed group or using the "p" hotkey to parent a prim to a collapsed group, it will cause the group to auto-expand. 

**Steps to reproduce**
1. Open a new file in Maya 2022
2. Navigate to Create -> Universal Scene Description (USD) -> Stage with new layer
3. Right click on the proxy shape -> Add new prim -> Capsule
4. Click on the capsule and create a group (press Ctrl+g)
5. Click on the group and duplicate it (press Ctrl+d)
6. Collapse the first group
7. MMB drag the capsule in the 2nd group to the 1st group - this will auto-expand the collapsed group (where the prim was parented to). Using the "p" hotkey will also cause the group to auto-expand.

**Expected behavior**
We would expect the parenting behaviour to be consistent with Maya's native parenting behaviour where it does not auto-expand the collapsed group.

**Attachments**
This gif goes through steps 3-7:
![outliner - auto expands when moving an object to a collapsed group simple](https://user-images.githubusercontent.com/12554015/137776406-513a5da5-25c9-404c-ace1-0ab56e47b709.gif)

This gif compares the behaviour between ufe (with the kitchen set) and native Maya nodes.
![outliner - auto expands when moving an object to a collapsed group](https://user-images.githubusercontent.com/12554015/137775959-fa834494-b91e-441e-8dbb-a32df4a9cedc.gif)

**Specs (if applicable):**
OS (Linux 64 bit)
Maya USD: dev at 4710d36
Pixar USD: dev at 96c5a3f
Maya 2022.update2

**Comment by santosd** [comment]
Hi @gracekumagai, This one is now fixed however, it required Maya side changes so will need to be tested in the next PR when that is available. I can keep this issue open in the mean time while we wait for the next PR release and you can test it.

**Comment by santosg87** [comment]
marking this as closed, as the changes are all avaialable. if this is still an issue on the latest versions of Maya, feel free to reopen

**Comment by gracekumagai** [comment]
I tested in maya2023.2 and it's working as expected! Thank you!
