### ISSUE TITLE
[MAYA-104456] Outliner: Cannot MMB drag to re-parent prim between children.

### ISSUE THREAD

**Issue by gracekumagai** [Autodesk/maya-usd#1768]
**Describe the bug**
Cannot re-parent a prim by MMB dragging the prim under another parent and between the parent's children.

We can rearrange a prim by MMB dragging between it's siblings. We can also re-parent a prim by MMB dragging the prim directly onto the parent. However, it seems like we cannot re-parent and re-arrange in 1 step. 

**Steps to reproduce**
1. Open a new file in Maya 2022
2. Navigate to Create -> Universal Scene Description (USD) -> Stage with new layer
3. Right click on the proxy shape -> Add new prim -> Capsule
4. Click on the Capsule and duplicate 3 times (Ctrl+d)
5. Select 3 of the capsules and group them together (Ctrl+g)
6. Click on the ungrouped capsule and MMB drag in between the the other capsules. The ungrouped capsule will not be re-parented or re-arranged in between the other capsules.

**Expected behavior**
We would expect the user to have the same behaviour as native Maya where they are able to MMB drag a prim under another parent and insert it between that parent's children.

**Attachments**
Steps 3-6
![outliner - cant mmb group between children simple](https://user-images.githubusercontent.com/12554015/137778414-313392af-9e77-47d6-b1ff-d7f4e8b3f24f.gif)
Comparing the behaviour between ufe (with the kitchen set) and maya nodes in the outliner:
![outliner - cant mmb group between children](https://user-images.githubusercontent.com/12554015/137777702-22ced251-a244-4ccd-aff2-2d41ea895f85.gif)

**Spec:**
OS (Linux 64 bit)
Maya USD: dev at 4710d36
Pixar USD: dev at 96c5a3f
Maya 2022.update2

**Comment by santosd** [comment]
No problem at all. I logged it internally as MAYA-114310

**Comment by santosg87** [comment]
we have had the fix for this issue available starting on 0.24.0. Closing this issue for the time being as there are no new reports on this afterwards.

@gracekumagai feel free to re-open or log a new ticket if this is still an issue :)
