### ISSUE TITLE
Attribute Editor: The top level tabs disappear and reappear when tumbling the camera

### ISSUE THREAD

**Issue by gracekumagai** [Autodesk/maya-usd#1769]
**Describe the bug**
With the AE open and panning the camera using the Tumble tool (Alt + left mouse button + moving the mouse around), the top-level tabs in the AE disappear and reappear. 

**Steps to reproduce**
1. Open 'kitchen_set_instanced'
2. Click on the `|Kitchen_set_instanced|Kitchen_set_instancedShape,/Kitchen_set` (or any other prim)
3. Go over the viewport hold down Alt + left mouse button + move the mouse around, notice that the AE top level tabs disappear and reappear.

**Expected behavior**
We would expect the Attribute Editor not to remove the top level tabs.

**Attachments**
![ae pop up and down](https://user-images.githubusercontent.com/12554015/137779570-41067353-227b-4566-ac8d-2100204ebf4c.gif)

**Specs (if applicable):**
OS (Linux 64 bit)
Maya USD: dev at 4710d36
Pixar USD: dev at 96c5a3f
Maya 2022.update2

**Additional context:**
A few notes on how to reproduce:
- I was having trouble reproducing this in an empty stage. However, I can reproduce it pretty reliably with the kitchen set with the  `|Kitchen_set_instanced|Kitchen_set_instancedShape,/Kitchen_set` selected.
- I also found that the tabs seem to disappear after tumbling the camera (after releasing the buttons) and reappear when tumbling again. 
- Un-selecting and re-selecting the `Kitchen_set` also helped trigger it

**Comment by santosd** [comment]
Hello Grace,
I took a look at this in multiple versions of USD and Multiple versions of Maya and on Linux (Ubuntu) and Windows and I have not been able to reproduce the issue. Are you able to test in the PR129 release and see if the issue is present there for you? I can see if my colleague can test on CentOS and see if the issue is present for him there.
I wonder if this could have something to do with display settings maybe scaling or screen resolution? Are multiple users seeing this issue? Does this happen with Maya data or only USD data?

Thank you.

-David

**Comment by santosd** [comment]
I tested some more and I am still not able to reproduce the issue. Based off of what you are seeing in the AE, it looks like you might have a version of Maya that is missing some changes that went into the AE. As you can see from my screen capture we see different Attribute menu items in the AE. I believe this is an issue that may have existed at one point but it is no longer present. The AE changes that were implemented should be in the released version of 2022.2 as that is was I was testing on my end. Are you using a custom AE template on your end? Maybe that is the issue.

![image](https://user-images.githubusercontent.com/29235905/137987848-a35754d4-62bc-47d4-8b62-969a5ff56ea0.png)

**Comment by kxl-adsk** [comment]
We should move away from using UFE asserts and follow the coding guidelines by adopting TF diagnostics. Feel free to open a PR that replaces `UFE_ASSERT_MSG` with a TF_WARN. Some small code adjustments will be required like - https://github.com/Autodesk/maya-usd/blob/8f216a4fb955fc44c0abda55caa53ed295aaa625/lib/mayaUsd/ufe/UsdAttributes.cpp#L108
