### ISSUE TITLE
UFE : Hide / Unhide Commands Do Not Work

### ISSUE THREAD

**Issue by cfmoore007** [Autodesk/maya-usd#177]
Issue :

Maya's Hide / Unhide commands do not seem to work with UFE selected prims.

A warning is returned to the user : 
$MAYA_LOCATION/scripts/others/hideKeepSelection.mel line 36: No objects to hide.

However, hiding through the USD Stage directly works, and is reflected properly in the viewport.

Steps to reproduce :

1) import in proxyShape of the selected scene file
2) select prim via Maya Outliner or viewport
3) press either 'h' or 'ctrl-h'

[3_Spheres.zip](https://github.com/Autodesk/maya-usd/files/3957276/3_Spheres.zip)

**Comment by seando-adsk** [comment]
Internally this is logged as: MAYA-101356 - UFE: Hiding (Ctrl+H)/unhiding (Shift+H) prims doesn't work

**Comment by pilarmolinalopez** [comment]
Thanks, @seando-adsk !

**Comment by Xaia** [comment]
Hi there! Any update on this? 
Looks like hiding objects is still not possible but if I click "Hide unselected objects" everything is gone, even the selected ones :).

**Comment by seando-adsk** [comment]
@cfmoore007 / @pilarmolinalopez  Good news! The next Maya PR contains support for hide/unhide commands (and hotkeys) on UFE items. The following are now supported for UFE:
* Hide Selected (Ctrl+h)
* Show Last Hidden (Ctrl+Shift+h)
* Toggle Show/Hide (h)
* Show Selected (Shift+h)
* showHidden -below

**Comment by cfmoore007** [comment]
@seando-adsk  - that's great!  We'll definately check it out.

**Comment by santosg87** [comment]
this should be working for some time now. closing this issue for th etime being. if it is still a problem, please let us know :)

**Comment by cfmoore007** [comment]
@santosg87 - Confirmed, works here.  Thanks!
