### ISSUE TITLE
[MAYA-114501] Allow users to add site specific items to context menus and radial menus

### ISSUE THREAD

**Issue by dj-mcg** [Autodesk/maya-usd#1773]
**Is your feature request related to a problem? Please describe.**
Users have requested items in the Outliner context menu and in various radial menus in the viewport, many of which are specific to studio needs.

**Describe the solution you'd like**
It would be nice if a plugin mechanism was provided to allow studios or users to add custom commands to context menus and radial menus.

**Describe alternatives you've considered**
We could hack the code itself and have it live in an internal patch branch, but a plugin mechanism would be cleaner and would allow us to avoid any future merge conflicts.

**Comment by oumad** [comment]
This is definitely something we need, I've actually been looking how to hack this in, but if there was a way to add such options in a much simpler/cleaner way, ideally with python scripting. That would help us to greatly improve our artists worfkflow.

**Comment by seando-adsk** [comment]
Are you asking for a MayaUsd plugin mechanism to or something from Maya?

From Maya, I would suggest looking at the ```callbacks``` command in Maya. There are various menu item hooks, like ```addRMBBakingMenuItems``` which you can use to add items to the context menu when RMB over an object in the viewport. We are using this hook in the mayaUsd plugin to add some menus.

There is also a new hook added available in the latest Maya PR ```addItemsToOutlinerNodePopupMenu``` which you can use to add menu items to the context menu in the Outliner. We are also using this hook in the mayaUsdPlugin.

We don't have anything from MayaUsd, but it does use Ufe and the new Ufe ```ContextOps``` interface available in Ufe v2 (Maya 2022) to add menu items. https://help.autodesk.com/cloudhelp/2022/ENU/Maya-SDK/ufe_ref/class_ufe_1_1_context_ops.html

Does that help?
Sean

**Comment by seando-adsk** [comment]
There is a new menu hook (available in Maya 2023) that will be called when you RMB on a **non-Maya Ufe item** in the viewport. It looks for a MEL menu proc: <ufe runtime name> + "MenuProc" 
We are using this in the MayaUsd plugin: https://github.com/Autodesk/maya-usd/blob/dev/plugin/adsk/scripts/USDMenuProc.mel#L62

**Comment by oumad** [comment]
> There is a new menu hook (available in Maya 2023) that will be called when you RMB on a **non-Maya Ufe item** in the viewport. It looks for a MEL menu proc: + "MenuProc" We are using this in the MayaUsd plugin: https://github.com/Autodesk/maya-usd/blob/dev/plugin/adsk/scripts/USDMenuProc.mel#L62

Could you explain more how this one works ?
I tested to prepare a proc that ends with MenuProc but it didn't affect the menu, only when it has USDMenuProc, is "USD" here an important keyword or something ?
How could I inject other menu items in this one for example without editing the USDMenuProc function inside maya-usd plugin?

**Comment by seando-adsk** [comment]
> > There is a new menu hook (available in Maya 2023) that will be called when you RMB on a **non-Maya Ufe item** in the viewport. It looks for a MEL menu proc: + "MenuProc" We are using this in the MayaUsd plugin: https://github.com/Autodesk/maya-usd/blob/dev/plugin/adsk/scripts/USDMenuProc.mel#L62
> 
> Could you explain more how this one works ? I tested to prepare a proc that ends with MenuProc but it didn't affect the menu, only when it has USDMenuProc, is "USD" here an important keyword or something ? How could I inject other menu items in this one for example without editing the USDMenuProc function inside maya-usd plugin?

This new hook is exclusively for **non**-Maya **Ufe** items, ie it will not be called for any Maya objects. Currently the only Ufe plugin is this MayaUsd one. We register the ufe plugin with the name "USD" (as seen here: https://github.com/Autodesk/maya-usd/blob/dev/lib/mayaUsd/ufe/Global.cpp#L90). So when your RMB on a USD prim it will call the MEL proc "USDMenuProc" which we have defined in the plugin. Currently the only way to add your own menu items would be to edit this existing proc. You could do something simple like just adding a single line at the end of our proc to call your own proc (where you would add your own items):

`MyUSDMenuProc($parent, $obj);`

If injecting your own items into this menu is something you require we could add that functionality from our USDMenuProc to have it call a user one. Maya already has this for other menus.

Sean

**Comment by oumad** [comment]
> > > There is a new menu hook (available in Maya 2023) that will be called when you RMB on a **non-Maya Ufe item** in the viewport. It looks for a MEL menu proc: + "MenuProc" We are using this in the MayaUsd plugin: https://github.com/Autodesk/maya-usd/blob/dev/plugin/adsk/scripts/USDMenuProc.mel#L62
> > 
> > 
> > Could you explain more how this one works ? I tested to prepare a proc that ends with MenuProc but it didn't affect the menu, only when it has USDMenuProc, is "USD" here an important keyword or something ? How could I inject other menu items in this one for example without editing the USDMenuProc function inside maya-usd plugin?
> 
> This new hook is exclusively for **non**-Maya **Ufe** items, ie it will not be called for any Maya objects. Currently the only Ufe plugin is this MayaUsd one. We register the ufe plugin with the name "USD" (as seen here: https://github.com/Autodesk/maya-usd/blob/dev/lib/mayaUsd/ufe/Global.cpp#L90). So when your RMB on a USD prim it will call the MEL proc "USDMenuProc" which we have defined in the plugin. Currently the only way to add your own menu items would be to edit this existing proc. You could do something simple like just adding a single line at the end of our proc to call your own proc (where you would add your own items):
> 
> `MyUSDMenuProc($parent, $obj);`
> 
> If injecting your own items into this menu is something you require we could add that functionality from our USDMenuProc to have it call a user one. Maya already has this for other menus.
> 
> Sean

Yeah it's how I currently thought about doing it, but the downside of that is whenever we update the maya-usd plugin we'd have to add that line again.
I'm interested in the solution you're suggesting, if I understood right it wouldn't require doing the above whenever the plugin is updated.

**Comment by seando-adsk** [comment]
What I would suggest is having something just like what Maya already has. For example when a poly object is selected, Maya will call a user proc `contextPolyToolsObjectUserMM` (if it exists). I would propose adding this right at the end of our existing USDMenuProc function:
```
// Allow user to define a proc with additional menu items
if (`exists USDUserMenuProc`)
	USDUserMenuProc($parent $obj);
```
This way you would just have to add this function in your Maya user scripts folder in a file called USDUserMenuProc.mel and Maya will automatically find it. 

If you want to open a pull-request with this change I would gladly approve it. Then you wouldn't have to worry about the plugin being updated and your menu items no longer there. If you are unable to open a pull-request yourself, then I'll make sure to have this logged internally so that it can be looked at.

Sean

**Comment by oumad** [comment]
Thank you Sean,

I was able to test your suggestion in maya-usd 0.17.0 and maya 2023, it works very well, I can easily inject menu items or any kind of code with that.
I opened a pull request for this : https://github.com/Autodesk/maya-usd/pull/2305

**Comment by sbissonnette** [comment]
@seando-adsk Is there something similair but for the Outliner?

I was able to achieve what I need with `USDUserMenuProc` for the viewport, but I would like to do the same with the Outliner

**Comment by seando-adsk** [comment]
@sbissonnette Yes for the Outliner you can use the Maya callback `addItemsToOutlinerNodePopupMenu` . For more info see the Maya [callbacks](https://help.autodesk.com/view/MAYADEV/2025/ENU/?guid=__CommandsPython_callbacks_html) command.

**Comment by seando-adsk** [comment]
Or alternatively if you want to use Ufe you can create a Ufe plugin that decorates the MayaUsd ContextOps and add your items via code (can be either Python or C++). The advantage of this is that it is not specific to the Outliner or Viewport. For USD we have the same menu in both places. For an example of how to override it see how we are doing it in MayaUsd plugin where we override the one from UsdUfe for MayaUsd plugin (Maya specific items): https://github.com/search?q=repo%3AAutodesk%2Fmaya-usd%20MayaUsdContextOps%20&type=code

**Comment by sbissonnette** [comment]
I was able to achieve what I needed!

Thanks @seando-adsk
