### ISSUE TITLE
[MAYA-115007] Busy Cursor or Progress Bar when loading

### ISSUE THREAD

**Issue by dj-mcg** [Autodesk/maya-usd#1783]
**Is your feature request related to a problem? Please describe.**
Loading a large number of models can take several seconds to over a minute. Currently there is no indication that Maya is working during this time, and the app seems unresponsive or hung.

**Describe the solution you'd like**
Maya should display a progress bar or a busy cursor during loading to communicate that it is busy.

This is Pixar internal Jira MAYA-3070

**Comment by wtelford** [comment]
Hey Dan,
Is this about import, in memory stages via proxyShape, or both?

**Comment by gracekumagai** [comment]
Hey Will, I believe Dan is referring to loading by right-clicking on a group in the outliner and using "Load with Descendants"

**Comment by wtelford** [comment]
@womanyoyoyo-adsk  Can you bring this in as a story internally please.

**Comment by womanyoyoyo-adsk** [comment]
Logged internally as MAYA-115007.

**Comment by santosg87** [comment]
we have implemented changes to adress this issue around 0.27.0

marking this issue as closed for the time being. @gracekumagai feel free to re-open or log a new ticket if this issue still persists on your side. :)
