### ISSUE TITLE
Undefined symbol on linux with 0.13.0

### ISSUE THREAD

**Issue by sshklifov** [Autodesk/maya-usd#1801]
When I load the plugin in maya 2022, I get the following error:
```
// Error: file: /usr/autodesk/maya2022/scripts/others/pluginWin.mel line 316: Unable to dynamically load : /usr/autodesk/mayausd/maya2022/0.13.0_202110191046-3a94a0f/mayausd/MayaUSD3/plugin/adsk/plugin/mayaUsdPlugin.so
/usr/autodesk/mayausd/maya2022/0.13.0_202110191046-3a94a0f/mayausd/MayaUSD3/plugin/adsk/plugin/../../../lib/libmayaUsd.so: undefined symbol: _ZNK8Autodesk4Maya16OpenMaya202200009MHWRender11MRenderItem16InternalObjectIdEv // 
```
However, I can't find a method named InternalObjectId for class MRenderItem in the docs and it isn't defined in libOpenMayaRender.so. Any ideas?

**Comment by williamkrick** [comment]
I believe that you have a version of the MayaUSD plugin compiled for a newer Maya version than the one you are using. Can you verify that your Maya version is  2022.2?

**Comment by sshklifov** [comment]
It wasn't 2022.2. Thanks, resolved.
