### ISSUE TITLE
[MAYA-122424] Toggling left vs right handed tangent space after importing USD will kill the uv's

### ISSUE THREAD

**Issue by koen-v** [Autodesk/maya-usd#1824]
Hello autodesk, 

We found an odd issue with imported usd models. If you toggle the handedness of the tangent space you loose the uv's this does not happen when you do the same thing on a cube created in maya:

Imported from usd:
https://user-images.githubusercontent.com/4185553/141166630-758c5af3-2fec-49e7-a431-b4badecc8e6d.mp4

Created a cube:

https://user-images.githubusercontent.com/4185553/141166664-1c75a464-93eb-40e7-93c9-e66b3c774844.mp4

Thanks,
Koen

**Comment by santosg87** [comment]
hi @koen-v , I have tried a few different files and worfklows importing geometries into maya, and i can't seem to reproduce this behavior you are seeing. 

what is the exact build of mayaUSD you are using? I have treid on 0.13.0 and it doesn't seem to be happening for me at all. would you be able to add your sample usd file here, so i can try with a similar asset to yours?

thank you!

**Comment by koen-v** [comment]
Hello, 

Sorry for the later reply. Here is an example usd. it happens when there are animated points I think, this creates a blendshape network. 

Thanks for looking!

Koen

[box_tangentspace_uv_bug.zip](https://github.com/Autodesk/maya-usd/files/7619341/box_tangentspace_uv_bug.zip)

**Comment by santosg87** [comment]
ah! it seems to be related to animated data indeed, although specific to your FIle. I will dig a bit deeper to try and narrow down what exactly on your file make it break things.

**Comment by santosg87** [comment]
Hi @koen-v I have been testing this issue more recdently and we cannot reproduce this issue anymore on both Maya 2022.4 and newer versions. marking this one as closed for the time being. feel free to reopen if this is still an issue on the newer versions of Maya for you. :0
