### ISSUE TITLE
[MAYA-113800] Animation Data doesn't get exported with the Export Selection

### ISSUE THREAD

**Issue by Tylius** [Autodesk/maya-usd#1861]
**Describe the bug**
When I export an animated object with the file>Export Selection the exported USD file doesn't contain the animation data

**Steps to reproduce**
1. Create a Cube
2. Animate the rotation on Y axis
3. Go to file>Export Selection
4. Choose USD File
5. Check animation Data
6. Set the right frame range
7. Export

**Expected behavior**
I expect the exported USD to contain the animation data.

**Specs (if applicable):**
 - OS & version : Windows 10
 - Maya version :Maya 2022.2
 - Maya USD : 0.14.0

**Note**
With Maya 2020.4 the export selection works fine
There is no problem when I use the file>Export All

**Comment by oumad** [comment]
I confirm, I have this problem on my side too with Maya 2022.2 and maya-usd 0.13.0
I also tested on Maya 2020.4 the Animation data export seems to work fine with selection too.

**Comment by daviddeacon** [comment]
Possible work around at the moment is to use export via the cmds.mayaUSDExport and use the exportRoots flag.

`cmds.mayaUSDExport(file="myUSD.usda",
    exportRoots=['|myMayaObject'],
    stripNamespaces=True,
    frameRange=(1001, 1024),
    )`

It seems to export animation for me while isolating part of the scene.

David.

**Comment by santosg87** [comment]
We have something logged internally for this issue.

**Comment by santosd** [comment]
Hi @Tylius, I wanted to let you know that this issue has been resolved internally and should be available in an upcoming release of Maya.

**Comment by santosg87** [comment]
Marking this issue as closed for now. as we have tested it internally. @Tylius feel free to re-open if this is still persisting.

**Comment by JoshkVFX** [comment]
Hi all,

Is this fix going to be back-ported to 2022 or is it only available on 2023?

**Comment by santosg87** [comment]
@JoshkVFX which version of Maya 2022 are you runnig? I believe this is something that has been fixed on Maya 2022.4. :)

**Comment by JoshkVFX** [comment]
We've just updated to 2022.4 so I'll give it a test and see if that's resolved it
