### ISSUE TITLE
Building AL_USDMayaTranslators -- Configuring incomplete, errors occurred!

### ISSUE THREAD

**Issue by funghetto** [Autodesk/maya-usd#188]
```
-- Building AL_USDMayaTranslators
-- Configuring incomplete, errors occurred!
See also "C:/workspace/build/RelWithDebInfo/CMakeFiles/CMakeOutput.log".
See also "C:/workspace/build/RelWithDebInfo/CMakeFiles/CMakeError.log".

Traceback (most recent call last):
  File "build.py", line 482, in <module>
    InstallMayaUSD(context, context.buildArgs, context.stagesArgs)
  File "build.py", line 319, in InstallMayaUSD
    RunCMake(context, extraArgs, stagesArgs)
  File "build.py", line 283, in RunCMake
    extraArgs=(" ".join(extraArgs) if extraArgs else "")))
  File "build.py", line 189, in Run
    .format(cmd=cmd, log=os.path.abspath(context.logFileLocation)))
RuntimeError: Failed to run 'cmake -DCMAKE_INSTALL_PREFIX="C:\workspace\install\RelWithDebInfo" -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -G "Visual Studio 15 2017 Win64" -DMAYA_LOCATION="C:\Program Files\Autodesk\maya2019" -DPXR_USD_LOCATION="C:\Program Files\USD" -DMAYA_DEVKIT_LOCATION="C:\devkitBase" "C:\maya-usd-master"'
```

[CMakeError.log](https://github.com/Autodesk/maya-usd/files/3998699/CMakeError.log)
[CMakeOutput.log](https://github.com/Autodesk/maya-usd/files/3998700/CMakeOutput.log)

**Comment by BigRoy** [comment]
Hi @funghetto you should have a `build_log.txt` somewhere too that contains more information. That is, if you are using the `build.py` script.

Did you build `USD` using [what is described here]? If not, that'll likely fix it for you.
https://github.com/Autodesk/maya-usd/blob/c567a1661152ec2450359767fa2b0ca8cac4dc83/doc/build.md#boost):
```
python build_usd.py --build-args boost,"--with-date_time --with-thread --with-system --with-filesystem" --no-maya ~/Desktop/BUILD
```

The `boost`  build args are required for the Animal Logic plug-in to succeed. If you skipped these flags above then likely you do not have `pthread` or whatever you need for the build to succeed.

Also see the other issues:
- https://github.com/Autodesk/maya-usd/issues/86#issuecomment-547160074
- https://github.com/Autodesk/maya-usd/issues/30
- https://github.com/Autodesk/maya-usd/issues/27
- https://github.com/Autodesk/maya-usd/issues/1#issuecomment-520760657

**Comment by funghetto** [comment]
[build_log.txt](https://github.com/Autodesk/maya-usd/files/3998858/build_log.txt)

**Comment by funghetto** [comment]
I was able to get past that with https://github.com/Autodesk/maya-usd/issues/30#issuecomment-561010972
