### ISSUE TITLE
Cannot build maya usd win10

### ISSUE THREAD

**Issue by funghetto** [Autodesk/maya-usd#189]
This time I can't even find the error.
[build_log.txt](https://github.com/Autodesk/maya-usd/files/3998874/build_log.txt)

**Comment by BigRoy** [comment]
Did a quick search for `error` in the build log. Found this:
```
C:\maya-usd-master\plugin\pxr\maya\lib\usdMaya\shadingModeExporterContext.cpp(304): error C2672: 'SdfPathFindLongestPrefix': non sono state trovate funzioni in overload corrispondenti [C:\workspace\build\RelWithDebInfo\plugin\pxr\maya\lib\usdMaya\usdMaya.vcxproj]

C:\maya-usd-master\plugin\pxr\maya\lib\usdMaya\shadingModeExporterContext.cpp(305): error C2780: 'BidirectionalIterator pxrInternal_v0_19__pxrReserved__::SdfPathFindLongestPrefix(BidirectionalIterator,BidirectionalIterator,const pxrInternal_v0_19__pxrReserved__::SdfPath &)': argomenti previsti: 3, forniti: 2 [C:\workspace\build\RelWithDebInfo\plugin\pxr\maya\lib\usdMaya\usdMaya.vcxproj]

  C:\Program Files\USD\include\pxr/usd/sdf/path.h(759): note: vedere la dichiarazione di 'pxrInternal_v0_19__pxrReserved__::SdfPathFindLongestPrefix'
```
_There could be more, but this is just what I quickly found with my phone_.

Looks like you are using an incompatible `USD` version. Did you compile the right commit as stated in `doc/DEVELOPER.md`?

**Comment by funghetto** [comment]
I'm using the master branch and the documentation says: 

> We are currently using v19.05 for Maya plugin in master branch and therefore Pixar USD build should match this version.

Is this wrong?

**Comment by BigRoy** [comment]
I think that might be outdated. Definitely try the version mentioned [here](https://github.com/Autodesk/maya-usd/blob/master/doc/DEVELOPER.md#source-versions). Does that work?

**Comment by funghetto** [comment]
Yes with 19.11 it works, the documentations needs to be updated.
