### ISSUE TITLE
Offset Parent Matrix ignored on export

### ISSUE THREAD

**Issue by daviddeacon** [Autodesk/maya-usd#1925]
The Offset Parent Matrix option on transforms is being ignored when exporting to USD. 

We have started taking advantage of the offset parent matrix instead of parent constraints in a number of rigs. This is causing us a bunch of issues when trying to export these rigs to USD.

**Steps to reproduce**
New scene, 
create a cube,
create a locator,
connect locators world transforms matrix to cube's transform's offset parent matrix,
translate rotate scale the locator,
export cube to cube.usd,
load cube.usd via mayaUsdProxy
resulting usd cube is at the origin untransformed.

This is the same if the locator is animated.

**Expected behaviour**
I would expect the offset matrix to be combined with the cubes local transform and written to the resulting USD scene, so the Maya and USD scenes look the same

Testing in, Maya 2022.3, MayaUSD 0.13.0.

**Comment by daviddeacon** [comment]
Apologies, this is a duplicate of bug [https://github.com/Autodesk/maya-usd/issues/1045](url)

I missed it on my initial search, but I did notice it's almost a year old. Be great if it could be bumped up the priority a little.

Thanks

**Comment by santosg87** [comment]
thank you for the info @daviddeacon #1045 is currently on our backlog, I will raise the issue to the team and see if this can be given a higher priority.

I'm closing this one for the time being, as it is a duplicate issue.

cheers!
