### ISSUE TITLE
[MAYA-120891] Selection highlight sticks after selecting the proxy shape

### ISSUE THREAD

**Issue by gracekumagai** [Autodesk/maya-usd#1955]
**Describe the bug**
If you select the proxy shape in the wireframe display mode and clear your selection, the selection highlight is still displayed for its children. This does not occur in the smooth shaded mode. 

If you select one if its children, the selection highlight still displays for all the other children (even if the selection is cleared). If you select each child, it seems to reset the selection highlight and behave as expected.

This is likely related to issue #1752.

**Steps to reproduce**
1. Open a new file in Maya 2022
2. Navigate to Create -> Universal Scene Description (USD) -> Stage with new layer
3. Right click on the proxy shape -> Add new prim -> Capsule
4. Right click on the proxy shape -> Add new prim -> Cube
5. Select the proxy shape `stageShape1`
6. Ensure that you are using the wireframe display mode
6. Clear the selection by selecting elsewhere in the viewport. Notice that the selection highlight remains on the children even though the selection has been cleared

**Attachments**
![wireframe_after_proxyshape_selected](https://user-images.githubusercontent.com/12554015/148266754-fa5298d1-07e2-4959-b4fd-a5a95790bac7.gif)

**Specs (if applicable):**
maya2022.update3
Maya Usd: https://github.com/Autodesk/maya-usd/pull/1891

**Comment by williamkrick** [comment]
@gracekumagai I believe this is working correctly now, please let us know if you find more issues!

**Comment by gracekumagai** [comment]
It seems to be working on my end - thank you!
