### ISSUE TITLE
[MAYA-121618] Manipulator does not draw over the last selected object when multi-selecting maya and usd objects

### ISSUE THREAD

**Issue by gracekumagai** [Autodesk/maya-usd#1956]
**Describe the bug**
When selecting multiple maya and usd objects in the viewport, the manipulator is drawn over the last selected maya object. We would expect it to be drawn over the last selected object. It works as expected when only selecting usd objects or only selecting maya objects. 

The same behaviour occurs when clicking + dragging to perform a multi-select. 

**Steps to reproduce**
1. Open a new file in Maya 2022
2. Navigate to Create -> Universal Scene Description (USD) -> Stage with new layer
3. Right click on the proxy shape -> Add new prim -> Capsule
4. Navigate to Create -> Polygon Primitives -> Sphere
5. Select the native maya Sphere
6. Shift+click on the usd Capsule to add it to the selection. Notice that the manipulator remains over the native maya sphere.

If you select additional usd objects after selecting a maya object, the manipulator will remain over the last selected maya object. If you add another maya object to the selection, the manipulator will update and position over the maya object.

**Expected behavior**
We would expect it to be drawn over the last selected object. It works as expected when only selecting usd objects and when only selecting maya objects. 

**Attachments**
![manipulator](https://user-images.githubusercontent.com/12554015/148268956-8cd68636-2166-4f2e-9f92-6057cd03c00c.gif)

**Specs (if applicable):**
 - maya2022.update3
- Maya Usd: dev at 08445f6

Logged at Pixar as MAYA-3188

**Comment by santosg87** [comment]
re-visiting this issue, and i cannot reproduce it on either Maya 2024 or maya 2025 with the latest MayaUsd builds.

marking this ticket as closed for the time being, but feel free to re-open if this is still an issue.
