### ISSUE TITLE
Automated builds (CI)

### ISSUE THREAD

**Issue by tokejepsen** [Autodesk/maya-usd#2]
**Goal**

Automated the building process on merges.

**Motivation**

Having precompiled builds would lower the barrier for people wanting to use this plugin.

**Comment by xtvjxk123456** [comment]
great idea

**Comment by BigRoy** [comment]
As a reference, Victor Yudin created [saturn](https://github.com/VictorYudin/saturn) which automatically builds USD using Appveyor and looking at his latest commits he has been looking into Azure too.

Azure pipelines would be most interesting as it should be able to compile for Windows, Mac OS and Linux.

- [AppVeyor](https://www.appveyor.com/) - Linux and Windows
- [Azure](https://azure.microsoft.com/en-us/services/devops/pipelines/) - Linux, macOS, and Windows

Potentially @VictorYudin can contribute.

**Comment by gplsteph** [comment]
+1 for Azure Pipelines

**Comment by amotarzi** [comment]
As long as the much neglected Mac OS X is supported!

**Comment by HamedSabri-adsk** [comment]
Can this issue be closed?

> Azure pipelines would be most interesting as it should be able to compile for Windows, Mac OS and Linux.

Yes, Azure pipelines in particular is a good CI/DI system compare to the other ones out there. However, we won't be able to use it at all as this project has a dependency to the Maya binaries which we can't just deploy and use. We are currently exploring other possible solutions to the problem.

**Comment by tokejepsen** [comment]
> Can this issue be closed?

Has it been implemented, or it not going to be implemented?

**Comment by BigRoy** [comment]
> Can this issue be closed?

Preferrably not if this helps us remind to have this as a set goal. If there's a way for automated releases to be pushed on e.g. "major/minor" tags in the near future that would be super helpful for quicker adoption of maya-usd and its updates by the less technically inclined crowd.

A big hurdle of course is also the dependency on USD itself. It raises the question of what version of USD specifically would you bundle with. Always the latest and greatest that works with the maya-usd branch?

**Comment by kxl-adsk** [comment]
Sounds good, we can keep it as a reminder.

**Comment by kxl-adsk** [comment]
FYI. We are actually testing PF for GitHub pull requests. More info will be available soon.

**Comment by kxl-adsk** [comment]
We have been running GitHub actions for some time now - https://github.com/Autodesk/maya-usd/actions. This allows preflight for every pull request to test against a number of platforms and Maya versions.

Every time we post a new release, we are uploading Maya 2020 and Maya 2022 binaries. We are not anticipating generating and post binaries for every merge we do to the 'dev' branch.

With that said, I'm closing this issue.
