### ISSUE TITLE
MayaUSD 0.15 seems to come with the wrong USD version

### ISSUE THREAD

**Issue by sshklifov** [Autodesk/maya-usd#2005]
Under releases, mayaUsd 0.15.0 is compiled against USD 21.08, but in the highlights it is stated that 21.11 is used. Checking pxrConfig.cmake or pxr.h shows that the USD version is 21.08.

Just wanted to give a heads up.

**Comment by kxl-adsk** [comment]
You are correct. At that time we adopted 21.11 in our mainline testing but not yet for Maya 2020 and 2022. Next release will most likely come with 21.11.

Thank you, I fixed it.
