### ISSUE TITLE
fatal error on Maya launch with MayaUSD_0.15.0_Maya2022.3_OSX 

### ISSUE THREAD

**Issue by psql** [Autodesk/maya-usd#2006]
**Describe the bug**
This version crashes Maya 2022 on OSX with a fatal error

**Steps to reproduce**
Launch Maya, crashes when loading the mayaUSD plugin (last visible plugin in the splash screen readout)
Had to delete the directory from `/Applications/Autodesk/mayausd` to be able to launch Maya again. 

Fatal error when loading from Plug-in Manager too

![image](https://user-images.githubusercontent.com/688842/150402802-eed8808a-6bc8-49b4-957a-9c637a65467c.png)
![image](https://user-images.githubusercontent.com/688842/150402479-84a39f0d-cdb6-4fa1-9a8f-94ef42586c8e.png)

Error Reports attached:
[dumpdata.zip](https://github.com/Autodesk/maya-usd/files/7907762/dumpdata.zip)
[pasquale.20220120.1348.crash.txt](https://github.com/Autodesk/maya-usd/files/7907763/pasquale.20220120.1348.crash.txt)

**Comment by santosg87** [comment]
hi @psql, any updates if 0.16.0 works for you? 

I'll mark this issue as closed for the time being, but feel free to re-open if this is still an issue for you. :)

**Comment by bchirlsbiodigital** [comment]
I'm having the same issue with version 0.19.0. Also Monterey and Maya 2022. on an intel MacBook Pro. thanks.

**Comment by tanant** [comment]
@bchirlsbiodigital - excuse the mini thread necro (bad form for me commenting on closed issues, i know) - 0.19 wasn't tested against Monterey if i recall correctly, but the recently released 0.20.0 is.
