### ISSUE TITLE
runtime error - /usr/autodesk/arnold/maya2020/hydra/mayaUsdPlugInfo.json couldn't be read

### ISSUE THREAD

**Issue by sparklabo** [Autodesk/maya-usd#2010]
**Describe the bug**
I am testing the pre-built USD plugin for Maya 2020, and the recent versions(from 0.10.0 to 0.15.0) are showing this error and does not allow me to load the plugin.
```
Runtime Error: in readPlugInfoObject at line 78 of /home/S/jenkins/workspace/ecg-mayausd-full-2020-linux/ecg-maya-usd/maya-usd/lib/mayaUsd/utils/plugRegistryHelper.cpp -- Plugin info file /usr/autodesk/arnold/maya2020/hydra/mayaUsdPlugInfo.json couldn't be read
```
Note: I removed Arnold from Maya to use Renderman without conflicts.

**Steps to reproduce**
1. Download the current Release (from 0.10.0 to 0.15.0), for Maya 2020.4 Linux 64 
```https://github.com/Autodesk/maya-usd/releases/download/v0.15.0/MayaUSD_0.15.0_Maya2020.4_Linux.run```
2. Install the plugin
3. Open Maya, and Load mayaUsdPlugin.so

**Expected behavior**
I expect the plugin can handle when Arnold is not a default renderer.

**Specs (if applicable):**
 - OS & version CentOS 7.8
 - Maya version Maya 2020.4
 - Maya USD commit SHA cebd6ace734ba42054893a1683ee8f805f348e71

**Comment by kxl-adsk** [comment]
Since you removed Arnold, I would expect this file to not be read: `/usr/autodesk/arnold/maya2020/hydra/mayaUsdPlugInfo.json`. Can you move/rename it so it doesn't get loaded?

**Comment by sparklabo** [comment]
the file doesn't exist, and that is why the process cannot read the file. Is there a code looking for the file?

**Comment by kxl-adsk** [comment]
Can you find mtoa mod file? We believe it is setting `MAYA_PXR_PLUGINPATH_NAME` to this unexistent `json` file.

We have something to fix as well here...we convert this line to a warning and not an error - https://github.com/Autodesk/maya-usd/blob/600c31abcd68ef3fe0047b28fb5f33f6edd0872f/lib/mayaUsd/utils/plugRegistryHelper.cpp#L77.

**Comment by sparklabo** [comment]
Thank you for the description and also the change of the code. As your advice, there was a mtoa.mod file existing in a sneaky location, and removing the file eliminated the error with 0.15.0.
