### ISSUE TITLE
[MAYA-124897] When xformOp:translate:pivot is set, the scale manipulator does not draw at its location

### ISSUE THREAD

**Issue by gracekumagai** [Autodesk/maya-usd#2045]
**Describe the bug**
When xformOp:translate:pivot is set, the scale manipulator does not draw at its location. It looks like the scale transformation is still applied as expected. The translate and rotation manipulators are drawn at the xformOp:translate:pivot location.

**Steps to reproduce**
First, create a prim with xformOp:translate:pivot set
> 1. Create a native Maya cube. Create -> Polygon Primitives -> Cube
> 2. Set Local Rotate Pivot X on pCube1 to 2
![image](https://user-images.githubusercontent.com/12554015/151609277-560a89f0-ecc4-4bb4-bd9f-89073d0cad36.png)
> 3. Select the pCube1. Notice that the translate, rotate, scale manipulators are drawn at (2, 0, 0)
> 4. Export the cube. File -> Export Selection (file type = USD export)

Bring in exported file:
> 1. Open a new file in Maya 2022
> 2. Navigate to Create -> Universal Scene Description (USD) -> Stage from file and navigate to the file exported.
> 3. Select pCube1 on the stage. Notice that xformOp:translate:pivot is set.
> 4. Press "r" over the viewport to draw the scale manipulator. Notice that it's drawn at (0, 0, 0) instead of at the xformOp:translate:pivot location. The translate and rotation manipulators are drawn correctly. 
![scale_manipulator](https://user-images.githubusercontent.com/12554015/151610885-3d496a87-873b-44d1-8a56-e7646450d8a5.gif)

**Expected behavior**
We would expect the scalar manipulator to draw at xformOp:translate:pivot location.

**Specs (if applicable):**
 - maya2022.update3
 - Maya USD dev at 807a118

Pixar Internal JIRA: MAYA-3207

**Comment by santosg87** [comment]
this should be fixed on Mayausd 0.23.0

marking this issue as closed for now :)

**Comment by dj-mcg** [comment]
Hi @santosg87 - we are now seeing all manip types (translate, rotate, scale) ignoring the pivots. We are in Maya 2023 - is this a 2024 fix only?
