### ISSUE TITLE
[MAYA-124571] Rename command missing features

### ISSUE THREAD

**Issue by gracekumagai** [Autodesk/maya-usd#2093]
**Describe the bug**
The rename command is listed as one of the ufe aware commands. However, we discovered that it is missing a few features when porting our internal tools to work with ufe.

1. If you try to rename an object to its current name, it increments the suffix (id) at the end (ex: renaming "Sphere1" to "Sphere1" results in "Sphere2". In native Maya, it would result in "Sphere1". (It looks like it is counting itself when figuring out the suffix))
2. If new name contains "#", it results in "_". In native Maya, it uses "#" to let Maya know to figure out the suffix.
3. It does not return the new name. This can cause problems when porting code as it forces the code to rely on selection to figure out the new name (since the new name might be different from what the user inputted).

**Steps to reproduce**
Repro steps for 1:
1. Open a new file in Maya 2022
2. Navigate to Create -> Universal Scene Description (USD) -> Stage with new layer
3. Right click on the proxy shape -> Add new prim -> Sphere
4. Select the Sphere1
5. Run `cmds.rename('Sphere1')`

Notice that Sphere1 is renamed to Sphere2. We would expect it to remain as Sphere1.

Repro steps for 2:
If you modify Step 5 to run `cmds.rename('Sphere_#')`. It renames Sphere1 to Sphere__. We would expect it to rename to Sphere_1

Repro steps for 3:
If you print out the result of Step 5, it prints None. We would expect it to return the new name.

**Expected behavior**
We would expect the command to have the same behaviour with ufe strings as maya paths.

**Attachments**
![rename](https://user-images.githubusercontent.com/12554015/153513743-58f99305-353b-4d24-a7ae-d60e113c9e27.gif)

**Specs (if applicable):**
 - Maya version Maya 2023 PR132
 - Maya USD commit SHA dev at 1c07d8e
 - Pixar USD commit SHA dev at 7533212

Logged internally as Pixar MAYA-3215

**Comment by santosg87** [comment]
@gracekumagai this should be working on the latest version of Maya available.

marking this issue as closed for now. feel free to reopen if this is not working on your side. :)
