### ISSUE TITLE
[MAYA-122129] Attribute Editor: Does not display array-type attributes on usd scopes

### ISSUE THREAD

**Issue by mlfecho** [Autodesk/maya-usd#2111]
**Describe the bug**
The Attribute Editor does not display array-type attributes on usd scopes. These array attributes are, however, present, and queryable via the Usd API. Additionally, you must change tabs in the Attribute Editor to refresh and reflect newly created attributes.

**Steps to reproduce**
1. Open a new file in Maya 2022
2. Navigate to Create -> Universal Scene Description (USD) -> Stage with new layer
3. Right click on the proxy shape -> Add new prim -> Sphere
4. Select the sphere in the Outliner
5. Paste and run the following code in the Script Editor:
```
from maya import cmds
import mayaUsd.ufe
from pixar import Sdf

node = cmds.ls(sl=True, ufe=True)[0]
prim = mayaUsd.ufe.ufePathToPrim(node)

# this shows up under Extra Attributes (need to change tabs to refresh)
stringAttr = prim.CreateAttribute('stringAttr', Sdf.ValueTypeNames.String)
stringAttr.Set('hello world')
print(stringAttr.Get())

# this does not show up under in Attribute Editor
stringArrayAttr = prim.CreateAttribute('stringArrayAttr', Sdf.ValueTypeNames.StringArray)
stringArrayAttr.Set(['hello', 'world'])
print(stringArrayAttr.Get())

# this shows up under Extra Attributes (need to change tabs to refresh)
intAttr = prim.CreateAttribute('intAttr', Sdf.ValueTypeNames.Int)
intAttr.Set(42)
print(intAttr.Get())

# this does not show up under in Attribute Editor
intArrayAttr = prim.CreateAttribute('intArrayAttr', Sdf.ValueTypeNames.IntArray)
intArrayAttr.Set([42, 24])
print(intArrayAttr.Get())
```
6. Toggle tabs in the Attribute Editor to refresh, and expand Extra Attributes.
7. Only intAttr and stringAttr are shown

**Expected behavior**
All four newly created attributes (stringAttr, stringArrayAttr, intAttr, and intArrayAttr) should be shown in the Attribute Editor

**Attachments**
![missingAttrArrays1](https://user-images.githubusercontent.com/488219/154395561-c812a392-15e0-480a-af79-19c481deacc9.gif)

**Specs (if applicable):**
 - OS: Linux 64 bit
 - Maya version: Maya 2022.update3

**Comment by seando-adsk** [comment]
Great thanks for the update. 

@santosg87) Can you test "you must change tabs in the Attribute Editor to refresh and reflect newly created attributes" and log internally if needed.

**Comment by santosd** [comment]
Logged the AE refresh issue internally MAYA-122129.

**Comment by santosg87** [comment]
The fix for the AE refresh has been in for some time now without any new reports.

Marking this as closed, as all the relevant issues have been addressed.
