### ISSUE TITLE
[MAYA-121806] Flat lighting not used in Maya 2022.3

### ISSUE THREAD

**Issue by dgovil** [Autodesk/maya-usd#2121]
**Describe the bug**
Maya 2022.3 has a change in how flat lighting is represented with the USD Preview Surface
![image](https://user-images.githubusercontent.com/4443090/154609607-5159a184-64c9-4cf9-bbb2-97b6777f86e5.png)

**Steps to reproduce**
1. Created a sphere and assigned usdPreviewsuface shader with texture on diffuse color (attached test.ma)
2. Enable “Use Flat Lighting”

**Expected behavior**
There should be some amount of lighting contribution

**Attachments**
If applicable, add screenshots, sample files, etc to help explain your problem.

**Specs (if applicable):**
 - OS & version macOS 12.3
 - Compiler & version clang 13 (Xcode)
 - Maya version 2022.3
 - Maya USD commit SHA 1bfe5bbf017ed8bb25e46148d4b5f20d955aec60
 - Pixar USD commit SHA release 21.11 faed18ce62c8736b02413635b584a2f637156bad

**Additional context**
Maya file and texture attached inside the zip
[Asset.zip](https://github.com/Autodesk/maya-usd/files/8093802/Asset.zip)

**Comment by JGamache-autodesk** [comment]
Hi @dgovil , can you try the environment variable `MAYAUSD_VP2_USE_V1_LIGHT_API=1` to see it it fixes the issue you are having?

**Comment by santosg87** [comment]
@dgovil this is fixed on the latest Maya 2023 release. we are not sure on the viability of this being possible to backport onto 2022.

**Comment by dgovil** [comment]
Awesome. That's great to know. We're in the process of standing up 2023.2 right now on our side so I'll give that a whirl.

**Comment by dgovil** [comment]
Okay got 2023.2 stood up and it looks like this works well now. Thanks!
