### ISSUE TITLE
Textures appear different when using Async Texture Loading in the Nvidia Attic Scene

### ISSUE THREAD

**Issue by santosd** [Autodesk/maya-usd#2142]
**Describe the bug**
When the Nvidia Attic Scene is loaded with Async Texture Loading enabled the textures appear different than when the stage is loaded without Async Texture Loading.

**Steps to reproduce**
1. Make sure that Async Texture Loading is enabled.
2. Create a stage from the Nvidia Attic Scene. Notice the shading on the beams how it is dark one side.
3. Create a new file in Maya.
4. Disable async texture loading.
5. Create a stage from the Nvidia Attic Scene. Notice the shading on the beams is dark on the opposite side.

**Expected behavior**
Loading with and without async texture loading should look the same.

**Attachments**
Async Disabled:
![Screenshot 2022-02-24 09:27:19](https://user-images.githubusercontent.com/29235905/155576467-5f84cf91-e847-4f35-a380-778eb67acd41.png)

Async Enabled
![Screenshot 2022-02-24 09:29:36](https://user-images.githubusercontent.com/29235905/155576488-65f97fa9-7068-471d-9375-f26be0956661.png)

Nvidia Attic Scene can be downloaded from the following link:
https://developer.nvidia.com/attic-nvidia

**Comment by santosg87** [comment]
@santosd are you able to confirm the changes and close it? 

thank you! :)

**Comment by santosd** [comment]
I retested this issue and this seems to be resolved so closing this issue for the time being.
