### ISSUE TITLE
[MAYA-104046] - Attribute Editor: Xform ops names can be cut off

### ISSUE THREAD

**Issue by gracekumagai** [Autodesk/maya-usd#2180]
**Describe the bug**
Long xform ops names are cut off in the attribute editor

**Steps to reproduce**
1. Open a new file in Maya 2022
2. Navigate to Create -> Universal Scene Description (USD) -> Stage with new layer
3. Right click on the proxy shape -> Add new prim -> Capsule
4. Select the Capsule
5. Create xformOp:translate:rotatePivot and xformOp:translateScalePivot by clicking on Modify -> Center Pivot
6. Open Attribute Editor. Notice that the xform op names are cut off. Changing the width of the AE does not change the text.

**Expected behavior**
We would expect that the xform op names would not be cut off. Ideally, we would like to customize the names to make them shorter and more readable for the artists (#1947)

**Attachments**
![ae_xformOps](https://user-images.githubusercontent.com/12554015/157975742-dfe0b5e2-0b3b-4d05-ae96-54f77e2f106b.png)

**Specs (if applicable):**
 - Linux
 - Maya USD commit SHA [dev at 561fc86]
 - Pixar USD commit SHA [dev at ff1e6fd]

Pixar Internal MAYA-3230

**Comment by santosg87** [comment]
just a small update on this issue. after some investigation on the AE side, there isn't a viable fix to this with the amount of resources needed for it. Closing this issue for now as a "won't fix" issue/
