### ISSUE TITLE
[MAYA-122145] Cannot copy and paste prims

### ISSUE THREAD

**Issue by gracekumagai** [Autodesk/maya-usd#2181]
**Describe the bug**
Copy (& cut) and paste does not work with prims. We would like to be able to copy and paste prims within the same stage and across stages in different Maya files.

Atm, it prints the following in the script editor when I press Ctrl+c on a prim:
`// Warning: file: /dist/sw/maya/2022.update3/scripts/startup/cutCopyPaste.mel line 223: Nothing is selected. // `

**Steps to reproduce**
1. Open a new file in Maya 2022
2. Navigate to Create -> Polygon Primitives -> Sphere
3. Navigate to Create -> Universal Scene Description (USD) -> Stage with new layer
4. Right click on the proxy shape -> Add new prim -> Capsule
5. Click on poly sphere and press Ctrl+c
6. Press Ctrl+v. Notice that it creates a group with a pasted poly sphere as expected
7. Click on the Capsule and press Ctrl+c. Notice that it prints the warning above in the script editor
8. Press Ctrl+v. Notice that it pastes the poly sphere instead of the USD capsule.

The same occurs when using cut and when trying to copy and paste across Maya files.

**Expected behavior**
We would expect to be able to copy and paste USD groups and models within a stage and across Maya files / stages.

**Specs (if applicable):**
 - Linux
 - Maya 2022.update3 (& PR132)
 - maya-usd dev at ef766e1
 - USD dev at ff1e6fd

Pixar Interal MAYA-3232

**Comment by santosd** [comment]
Logged this internally as MAYA-122145.

**Comment by gracekumagai** [comment]
We've recently had an artist go through their set dressing workflows and wanted to follow up on this ticket. 

We wanted to raise that they mentioned that they use Copy & Paste to move objects to entire sections of a dressed set from one maya file to another (in this case, one usd stage to another). They also found it a little unexpected that an old maya object that was saved to their clipboard awhile ago was added to their file instead of the USD prims.

Thank you!

**Comment by santosd** [comment]
Hi Grace, The problem with this workflow is that the Copy and Paste commands are not UFE aware so when a prim is selected and the Copy command is executed the copy command doesn't see the prim as an object it recognizes so the warning comes up. At this point this work is not scheduled, but if it is a priority for your team, I can bring it up in one of our planning meetings to see if we can put it on the schedule.

Cheers! 😃

**Comment by womanyoyoyo-adsk** [comment]
@gracekumagai Hi Grace, I assume you don't want the pasted prims going into a scope (mirroring Maya behavior with pasting as a group). So for example, if you copy a capsule, you would paste a capsule (not a scope with a capsule in it). Correct?
