### ISSUE TITLE
[MAYA-122423] center to view (press F) not working as spected 

### ISSUE THREAD

**Issue by Lucas3Dspain** [Autodesk/maya-usd#2189]
**Describe the bug**
When I have the usdPrpxyShape isolated and I select a prim inside the usdPrpxyShape, the center to view will fit all the proxyShape and not the selected prim.

**Steps to reproduce**
1. Select mayaUsdPrpxyShape and isolate it (Ctrl +1)
2. Clear selection
3. Select a prim from inside the mayaUsdPrpxyShape
4. Press F to center prim to view.

If step 1 is skipped, and there are no isolations in the scene, center to view works as spected.

**Specs (if applicable):**
 - Windows 10
 - Maya 2022.3
 - MayaUSD 0.16

**Comment by santosg87** [comment]
logged it internally as MAYA-122423
