### ISSUE TITLE
[MAYA-124403] Changing purpose doesn't update viewport on prims that are not sharing the proxyShape draw purpose

### ISSUE THREAD

**Issue by gracekumagai** [Autodesk/maya-usd#2194]
**Describe the bug**
On prims not marked as instanceable, toggling their purpose from proxy->render or proxy->guide does not update the viewport until the selection changes.

This works as expected with prims marked as instanceable

**Steps to reproduce**
1. Open a new file in Maya 2022
2. Navigate to Create -> Polygon Primitives -> Sphere
3. Navigate to Create -> Universal Scene Description (USD) -> Stage with new layer
4. Right click on the proxy shape -> Add new prim -> Xform
5. Right click on xform -> Add Usd Reference -> I added the WoodSpoon.usd asset from the kitchen set
6. Click on the xform and verify that it is not marked as instanceable in the AE
7. Set the purpose to render. Notice that the spoon still appears in the viewport. De-select the spoon and now, it disappears. The same occurs if you set the purpose from proxy->guide.

**Expected behavior**
We would expect it to update the viewport without unselecting the prim. We would expect it to behave the same way as prims marked as instanceable.

**Attachments**
![purposeUpdate](https://user-images.githubusercontent.com/12554015/158638060-8e11ad2c-20c1-4f02-b531-ad0e1a3d019a.gif)

**Specs (if applicable):**
- Linux
- maya2022.update3
- Maya USD commit SHA [dev at https://github.com/Autodesk/maya-usd/commit/96d35935c2325ced15203b529f8366a34825a064]
- Pixar USD commit SHA [dev at aaced34]

**Comment by santosg87** [comment]
hi @gracekumagai I have tried this workflow in a few different ways and with a few different usd files and formats, and i cannot seem to reproduce it on our side. 

I noticed that you also have a step to create a sphere on the process. is there any other tranform of selecting i should do with the polySphere that maybe i am missing? :)

**Comment by gracekumagai** [comment]
Hi @santosg87 ! Whoops, sorry about leaving in step 2 (that was sloppy copy and paste on my part). 

Is the prim you are working with marked as instanceable? I'm only able to reproduce if the prim is not marked as instanceable.

**Comment by santosg87** [comment]
Interesting. I have the same set up as you. instanceable object, tested using both the full kitchen asset, and the wooden spoon asset itself, same purpose checked on the proxyShape. But for me it updates dynamically as expected. 

I will keep investigating, there might be a variable that i am missing on reproducing this one.

thank you!

**Comment by santosg87** [comment]
@gracekumagai I am still not being able to reproduce this on our side. would you be able to check if this is something that is possibly fixed on more recent versions?

**Comment by gracekumagai** [comment]
Hey @santosg87, thank you for looking into it. I tested again with 2023.base and am running into the same issue. I wanted to check that the spoon is not marked as instanceable in your case?

Here's another gif: 
![purposeBug](https://user-images.githubusercontent.com/12554015/173448644-59e11372-235a-4713-bcfd-d10878265e3b.gif)

**Comment by santosg87** [comment]
thanks @gracekumagai, i will try a few more things on a different platform.

**Comment by santosg87** [comment]
@gracekumagai I think i finally managed to reproduce this. Although, I am seeing the refresh issue on a prim independent of it being marked as instanceable.
it seems that mayausd doesn't refresh when the purpose is set to any purpose that is not active on the stage transform.
i.e. change the active purposes on the stage from proxy to render only, and now changing the purpose on the woodspoon prim will update properly when setting to render only, and proxy/guide will have the refresh issue. :)

**Comment by gracekumagai** [comment]
Thank you for looking into it! It's good to know that it's independent of marking the prim as instanceable too. Thanks!

**Comment by dj-mcg** [comment]
FWIW I'm having trouble reproducing this problem at all in 2023.3 - @santosg87 was this fixed?

**Comment by santosg87** [comment]
we haven't done any changes targetting this specifically, although re-testing this on my side anymore with maya 2023.3, 2024.2 or 2025 versions, so i believe this can be closed.
