### ISSUE TITLE
Compiling maya-usd using Visual Studio 2019: "could not find instance"

### ISSUE THREAD

**Issue by scratchapixel** [Autodesk/maya-usd#2196]
Hi there)

I have been trying to compile the plugin for a while (looking for solution myself) but without any luck. I started a command prompt window from Visual Studio 2019. When I type the command:

    C:\Program Files (x86)\Microsoft Visual Studio\2019\Community>python d:\libraries\maya-usd\build.py ..._

I keep getting 

    _cmake -DCMAKE_INSTALL_PREFIX="D:\libraries\maya-usd-build\install\RelWithDebInfo" -DCMAKE_BUILD_TYPE=RelWithDebInfo - 
    DCMAKE_EXPORT_COMPILE_COMMANDS=ON -G "Visual Studio 15 2017 Win64" -DMAYA_LOCATION="D:\Program 
    Files\Autodesk\Maya2022" -DPXR_USD_LOCATION="D:\libraries\USD_BUILD" -DMAYA_DEVKIT_LOCATION="D:\Program 
    Files\Autodesk\Maya2022\devkit" -DMAYAUSD_DEFINE_BOOST_DEBUG_PYTHON_FLAG=OFF "d:\libraries\maya-usd"
    CMake Error at CMakeLists.txt:18 (project):
          Generator

    Visual Studio 15 2017 Win64

    could not find any instance of Visual Studio.

This is strange as I managed to compile USD fine from this window. I have both MSCV v140 and v141 installed but I am not sure whether this where I should be looking. I tried to setup the toolchain for older version using:

    "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvarsall.bat" x86_x64 -vcvars_ver=14.0

For example but I didn't get any luck.

Any help would be greatly appreciated.

**Comment by seando-adsk** [comment]
@scratchapixel I think you have found a bug in build.py script. It is making an assumption about the generator when one isn't supplied: https://github.com/Autodesk/maya-usd/blob/dev/build.py#L247

I can think of three options:

1. In our internal builds we use Ninja by adding `--generator Ninja`.
2. Tell build.py the correct Visual Studio generator. I think this will work `--generator "Visual Studio 16 2019 -A x64"`
3. Make change 2 locally in build.py around line 249. Note: starting at VS2019 you have to add the -A flag for architecture.

Sean

**Comment by scratchapixel** [comment]
Thanks Sean for the feedback. I will close it for now and will give it another go later, trying your solution and eventually looking for an update. Thanks again for the swift and useful reply.

**Comment by seando-adsk** [comment]
@santosd Can you please log this in JIRA so we can make sure it gets fixed.

**Comment by santosd** [comment]
Logged the issue internally as: [MAYA-122322](https://jira.autodesk.com/browse/MAYA-122322)

**Comment by seando-adsk** [comment]
@scratchapixel FYI, I just committed the fix for this generator issue in PR #2575

**Comment by santosd** [comment]
@scratchapixel could you confirm that this is fixed on your end?

**Comment by scratchapixel** [comment]
On the road now. .Will do when back at the office. Thx for the fix.
