### ISSUE TITLE
Failed to run 'cmake --build . --config RelWithDebInfo --target install -- -j16'

### ISSUE THREAD

**Issue by MChenLiang** [Autodesk/maya-usd#2202]
**Describe the issue**
Compilation using Python failed。

**Build log**
[build_log.txt](https://github.com/Autodesk/maya-usd/files/8309736/build_log.txt)

**Specs:**
 -  Windows 10
 - gcc version 11.2.0 (GCC)
 - Maya 2022
 - Maya USD commit  dev at  d734a4275c47270d3450a8e768487c70cb803281
 - Pixar USD commit release at 857ffda41f4f1553fe1019ac7c7b4f08c233a7bb

**Additional context**
I have completed the construction of pixarusd. Under this folder：
“D:\software\mayaplugin\workspace\pixarUSD ”。

Next:
add PATH:
D:\software\mayaplugin\workspace\pixarUSD\bin
D:\software\mayaplugin\workspace\pixarUSD\lib

add PYTHONPATH:
D:\software\mayaplugin\workspace\pixarUSD\lib\python

Next：
using x64 Native Tools Command Prompt for VS 2017

python build.py --generator Ninja --build-args=-DCMAKE_MAKE_PROGRAM=ninja.exe --maya-location "D:\Program Files\Autodesk\maya2022" --pxrusd-location D:\software\mayaplugin\workspace\pixarUSD --devkit-location D:\software\mayaplugin\devkitBase\maya2022 D:\software\mayaplugin\workspace\mayaUSD --build-args="-BUILD_WITH_PYTHON_3=ON,-DBUILD_PXR_PLUGIN=OFF;-DBUILD_TESTS=OFF"

**Comment by seando-adsk** [comment]
There is a small mistake in your build.py line. You have two entries for `--build-args` with the 2nd one coming at the end (after the workspace location). Try moving that option and combining it with the first one you have where you set CMAKE_MAKE_PROGRAM (you shouldn't really need that since you are using the `--generator` flag.

Sean

**Comment by seando-adsk** [comment]
@MChenLiang Were you able to build MayaUsd successfully?
