### ISSUE TITLE
[MAYA-122280] Textured Control is not connected for USD data

### ISSUE THREAD

**Issue by santosd** [Autodesk/maya-usd#2206]
**Describe the bug**
In the Maya Viewport, the Texture (on\off) ![image](https://user-images.githubusercontent.com/29235905/159304428-551f2f51-5676-4dd4-9ed4-c8da6f927daa.png) control doesn't affect USD data.
In an effort to have USD data work seamlessly across Maya, we would like to have the Texture Control connected for USD data as well.

**Steps to reproduce**
1. Create a stage from USD data that has textures.
2. Enable and disable the Texture button in the Viewport.
3. Notice USD data is not affected and always shows the textures.

**Expected behavior**
Maya USD data should work similar to how textured Maya data works with the Textured viewport option enabled and disabled. 

**Attachments**

https://user-images.githubusercontent.com/29235905/159305903-9eda8155-c9ce-4ee5-b427-56ec627cc417.mp4

**Comment by santosd** [comment]
Logged internally.

**Comment by chrizzFTD** [comment]
I think initial support for `Textured` on/off was added here: https://github.com/Autodesk/maya-usd/pull/2599

**Comment by santosg87** [comment]
@chrizzFTD you are correct. :)
