### ISSUE TITLE
NVidia Attic sample produces some meshes with stange visualizing 

### ISSUE THREAD

**Issue by egorchatsperasoft** [Autodesk/maya-usd#2213]
**Describe the bug**
win10 Maya2022.3 usdMaya 0.16.0 from githus installer
Attic scene from Nvidia

![Capture](https://user-images.githubusercontent.com/101147738/160136705-684700d6-01ee-4a0e-9e5f-170d1917c236.PNG)
/Root/Geometry/stars_527/stars Mesh primitive is invisible, but warns with such strange message, when selected.

in usdMaya 0.13.0 it produced incorrect VP2-imaging, which looks like tangled triangles over correct points, but I have no that version more to make screencapture.

**Comment by egorchatsperasoft** [comment]
Looks like it is fixed for Maya2022.3Win. Thank you.

**Comment by santosd** [comment]
Thank you for confirming. I am going to go ahead and close this one out.
