### ISSUE TITLE
[MAYA-123818] Cannot use Universal Manipulator on usd prims

### ISSUE THREAD

**Issue by gracekumagai** [Autodesk/maya-usd#2233]
**Describe the bug**
When selecting the Universal Manipulator using Ctrl+T or from the Modify menu -> Transformation Tools -> Universal Manipulator, nothing appears around the selected prims.

**Steps to reproduce**
1. Open kitchen_set_instanced
2. Select any model. For example: `|Kitchen_set_instanced|Kitchen_set_instancedShape,/Kitchen_set/Props_grp/DiningTable_grp/TableTop_grp/Spoon_2`
We would expect to see and use the manipulator.

**Expected behavior**
We would expect to be able to use the Universal Manipulator to transform prims. Similar to native maya.

**Specs (if applicable):**
- Linux
- maya2022.update3
- Maya USD commit SHA [dev at 96d3593]
- Pixar USD commit SHA [dev at aaced34]

Pixar Internal Jira MAYA-3254

**Comment by santosg87** [comment]
we have a fix for this internally, however, it is worth mentioning the fix here requires changes into the maya code itself, so those will not be visible on released Maya versions for the time being.

**Comment by dj-mcg** [comment]
Hi @santosg87 - I heard mention that this was addressed in MayaUsd 0.27. What version of Maya is required?

**Comment by santosg87** [comment]
the fixes for this required Maya changes that would break compatibility on older maya builds, so this one will only be avaialble on maya 2025 builds.

**Comment by santosg87** [comment]
closing this issue for the time being, as we have the fixes available already. as mentioned previosuly, the fixes for this require maya 2025.
