### ISSUE TITLE
[MAYA-122562] Alt+arrow keys hotkey does not work as expected

### ISSUE THREAD

**Issue by gracekumagai** [Autodesk/maya-usd#2234]
**Describe the bug**
The "Move Selected Objects" (Alt+arrow keys) hotkeys do not work with single or multi-selected usd prims. 

**Steps to reproduce**
1. Open a new file in Maya 2022
2. Navigate to Create -> Polygon Primitives -> Sphere
3. Navigate to Create -> Universal Scene Description (USD) -> Stage with new layer
4. Right click on the proxy shape -> Add new prim -> Capsule
5. Click on the poly sphere. Hold Alt + press one of the arrow keys. Notice that the sphere moves as expected
6. Click on the Capsule. Hold Alt + press one of the arrow keys. The capsule does not move

**Expected behavior**
We would expect the same behaviour as native maya objects. We would also expect to be able to single and multi-select objects and use this hotkey.

**Specs (if applicable):**
- Linux
- maya2022.update3 (& maya2023.PR132)
- Maya USD commit SHA [dev at 3885eb0]
- Pixar USD commit SHA [dev at aaced34]

Pixar Internal Jira MAYA-3255

**Comment by santosg87** [comment]
Thanks for logging this @gracekumagai I am able to reproduce the issue on our side as well. the hotkey itself is working, but it somehow is not passing down to selection on the ufe side of things.

for the record, i can reproduce that within the stage by trying the hotkey on the proxyShape node itself. :)

**Comment by gracekumagai** [comment]
Hi @santosg87 - apologizes for the delay! We have 2023.2 up and running now!

Unfortunately, when using the Alt+arrow keys on a USD capsule, it still does not move. Let me know if I'm missing something on my end.

I tested with:
- maya2023.2
- maya usd commit SHA: dev at 302f393
- usd commit SHA: dev at 60ed06c

Thanks!

**Comment by santosg87** [comment]
hi @gracekumagai thanks for verifying, I think this might require Maya changes then, as i can see the proper behavior on my side with internal builds. I will bring the feedback to the team. thank you!

**Comment by gracekumagai** [comment]
thank you!

**Comment by tanant** [comment]
Admin note - MAYA-125791 - for our internal investigation of where the Maya-side changes landed and what UFE combo is needed.

**Comment by santosg87** [comment]
this issue is now fixed on the latest mayausd build.

it is worth noting that this required changes in the maya code, so maya 2024 is needed to see the fix. :)
