### ISSUE TITLE
[MAYA-122664] Maya 2023.0 crashes when exporting to USD file in use

### ISSUE THREAD

**Issue by chadmv** [Autodesk/maya-usd#2263]
**Describe the bug**
Maya 2023.0 crashes when exporting to USD file in use by a stage in the scene

**Steps to reproduce**
1. Create > Universal Scene Description > Stage with New Layer
2. Create polySphere, export sphere as USD
3. Add a Def prim to the stage and add the sphere usd as a reference to the def prim
4. Save the stage in the layer editor
5. Export the sphere again to the same USD file
6. Crash

**Expected behavior**
Maya should not crash. I should be able to reload the stage and see the updated USD reference

**Specs (if applicable):**
 - Windows 10 Pro (10.0.19044 Build 19044)
 - Maya 2023 cut 202202161415-df43006fd3
 - Maya USD 0.16.0

**Comment by santosg87** [comment]
Thanks for logging this @chadmv I am also able to reproduce this on our side. 

we logged it internally as MAYA-122664

**Comment by santosg87** [comment]
@chadmv this should be fixed on 0.19.0, are you able to test and confirm on your side?

**Comment by santosg87** [comment]
marking this one as closed for the time being. Feel free to re-open it if this issue is still persisting on your side. :)
