### ISSUE TITLE
Unable to build MtoH for Maya 2023

### ISSUE THREAD

**Issue by Vsevolod1983** [Autodesk/maya-usd#2264]
**Describe the issue**
I'm unable to build MtoH for Maya 2023.
If I use Python 3.7.7 like for Maya 2022 it builds ok but don't run because Maya 2023 use Python 3.9 inside

If I use Python 3.9 I'm able to build PixarUSD but unable to build MtoH itself - it says that Python 3.7 is required.
I use cmake 3.17.5 as stated in  the documentation.

Which cmake version I should use ?
Any other requirements I should met ?

Thank you!

**Build log**
[build_log.txt](https://github.com/Autodesk/maya-usd/files/8443808/build_log.txt)

**Specs:**
 - Windows 10
 - Compiler & version Visual Studio 2017, toolset 141
 - Maya version 2023
 - Maya USD commit  0.16 release
 - Pixar USD commit  21.11 release

**Additional context**

**Comment by seando-adsk** [comment]
How are you executing you build - calling cmake directly or using the build.py?

Where does MtoH say that python 3.7 is required? Is that a build error you get?

The best way to avoid build problems with python is to use the python directly from Maya. You can do that by setting three cmake vars (either directly from your cmake line, or by using `--build-args` from build.py). The needed flags can be seen here:
https://github.com/Autodesk/maya-usd/blob/dev/CMakeLists.txt#L81

Something like this:
```
--build-args="-DPYTHON_INCLUDE_DIR=xxx/include/Python39/Python,-DPython_EXECUTABLE=xxx/bin/mayapy.exe,-DPYTHON_LIBRARIES=xxx/lib/python39.lib,-DBUILD_WITH_PYTHON_3=ON,-DBUILD_WITH_PYTHON_3_VERSION=3.9
```

FYI, we also pass in the python from Maya when building USD.  There is a special flag for that:
```
--build-python-info PYTHON_EXECUTABLE PYTHON_INCLUDE_DIR PYTHON_LIBRARY PYTHON_VERSION
                        Specify a custom python to use during build
```

Sean

**Comment by Vsevolod1983** [comment]
Hello @seando-adsk 
Thank you for your response.
I attached build.log file with the error:

-- Found Maya: C:/Program Files/Autodesk/Maya2023/bin/maya.exe (found suitable version "2023", minimum required is "2018") 
CMake Error at C:/Program Files/CMake/share/cmake-3.17/Modules/FindPackageHandleStandardArgs.cmake:164 (message):
  Could NOT find Python (missing: Python_EXECUTABLE Interpreter) (Required is
  exact version "3.7")

      Reason given by package: 
          Interpreter: Wrong version for the interpreter "C:/Python3.9.7/python.exe"


I don't think the problem is in Python, I use exactly 3.9.7 as in Maya 2023.

Which version of cmake do you use ?
