### ISSUE TITLE
[MAYA-107834] Normal maps are not preserved in the round trip from Maya to USD back to Maya

### ISSUE THREAD

**Issue by chadmv** [Autodesk/maya-usd#2295]
**Describe the bug**
Normal maps are not preserved in the round trip from Maya to USD back to Maya

**Steps to reproduce**
1. Create a mesh, assign either a lambert or standard surface material.
2. Connect a tangent space normal map to the material
3. Export the mesh as USD with USD Preview Surface material
4. New scene
5. Reimport the USD, converting the material to either lambert or standard surface
6. There is no normal map connected to the material.

**Expected behavior**
The normal map should be connected to the material like in the original Maya source

**Specs (if applicable):**
- Windows 10 Pro (10.0.19044 Build 19044)
- Maya 2023 cut 202202161415-df43006fd3
- Maya USD 0.16.0

**Comment by Ziethriel** [comment]
I am having the same issue. When connecting normal maps with the bump2d node it causes rendering to fail (vray), when the file node is connected directly it simply doesn't import, but renders successfully (albeit without the normal map).

**Comment by santosd** [comment]
Yes, we currently don't have translation for bump2d in USD Preview surface this does cause issues on import and export for Normal maps. Like you said direct file node connections work but that doesn't translate properly for the render. At this point we have some logged issued to resolve this through Material X and add the ability to translate through a Material X as the material in the USD options. I am wondering if that is something that you could work with or if in your workflow you would prefer the ability to do it through a USD Preview Surface material?

**Comment by chadmv** [comment]
We could use MaterialX as we mainly just require better Maya viewport rendering since we are in the game industry and would like to use USD instead of Maya and FBX files.

**Comment by santosg87** [comment]
there are other avenues being investigated regarding normals on workflows that are less maya centric, so we don't plan on working on this. we recommend using MaterialX :)

**Comment by koen-v** [comment]
Hello Santos, 

UsdPreview is very fast to import, I cant test mtlx in maya yet with an import workflow ( when I need maya geometry ) but if usdview is anything to go by, compiling the mtlx based shader takes a while. Having usdpreview as a fast option would be a fantastic addition, and the only thing missing currently is that I need to insert a bump2d node ( and reset the bias and gain on the file node.) it would be great if you would consider adding a simple fix for this.

thanks,
Koen
