### ISSUE TITLE
USD and maya-usd paths insertion in "PYTHONPATH" order dependency.

### ISSUE THREAD

**Issue by KelSolaar** [Autodesk/maya-usd#23]
Hi,

I came across a quite annoying one: if _USD_ is inserted before _maya-usd_ in `PYTHONPATH`, the `UsdMaya` package cannot be imported. Changing the order of the paths fixed the issue. 

The problem resides in the fact that the _USD_ `pxr` package is not a Python namespace package but the _maya-usd_ `pxr` package tries to extend the `pxr` namespace as if it was part of a namespace package: https://github.com/Autodesk/maya-usd/blob/2766c88f153c78662a181f217c1ee03a90387212/plugin/pxr/cmake/macros/Public.cmake#L194

This is quite bad because if you start to use namespace packages somewhere, you have to use them everywhere, i.e. in `USD` too: https://packaging.python.org/guides/packaging-namespace-packages/

> Every distribution that uses the namespace package must include an identical __init__.py. If any distribution does not, it will cause the namespace logic to fail and the other sub-packages will not be importable. Any additional code in __init__.py will be inaccessible.

To make matter worse, the ordering of potentially dynamically generated `PYTHONPATH` entries is not reliable.

Cheers,

Thomas

**Comment by HamedSabri-adsk** [comment]
Hi Thomas,

That is a great observation and we are aware of that. What we have done in macros/Public.cmake by extending the pxr namespace is a temporary solution and we are planning to resolve this as we bring things slowly under maya-usd/lib.

Totally agree with you on ordering being very finicky. In fact, if you look at the mayaUSD.mod.template, we cunningly have the first entry to be named USD and the reason for that is because Mod files don't seem to read entities in order that are laid out. We wanted USD inserted after PXR_USDMAYA  :)

Currently mod reads things in alphabetical order which is not intuitive at all
+ A
+ B

vs

+B
+A

**Comment by KelSolaar** [comment]
> by extending the pxr namespace is a temporary solution and we are planning to resolve this as we bring things slowly under maya-usd/lib.

That would be great because I don't think it is long term sustainable :)

> Currently mod reads things in alphabetical order which is not intuitive at all

Relying on Dark Magic :) Feels like there should be a bold mention about the current importance of ordering in the README file, people will be bitten hard by this one and if you have never played with namespace packages in Python it might take a while to figure out.

**Comment by j0yu** [comment]
I feel this _might be_ similar to https://github.com/Autodesk/maya-usd/issues/747#issuecomment-687666055

**Comment by vlasovi** [comment]
@KelSolaar I'm wondering if this issue is still valid for you, or if we can close it?

**Comment by KelSolaar** [comment]
Hi @vlasovi,

I haven't looked at that in a while, so I'm not sure whether it is still a problem or not! Seems like there are a lot of commits referencing it, so I'm assuming it has been fixed?

Cheers,

Thomas

**Comment by santosg87** [comment]
closing this issue for the times being based on the comments. if this is still an issue, feel free to re-open, or log a new issue so we can track it there. :)
