### ISSUE TITLE
WIndows : Issue while compiling the dev branch

### ISSUE THREAD

**Issue by fdevic** [Autodesk/maya-usd#233]
Hello!

I tried to compiling with latest code in the dev branch.

Steps :
`set PATH=%PATH%;c:\Python27;c:\Python27\Scripts
`

In the x64 native prompt of Visual2017
Git
```
git clone https://github.com/PixarAnimationStudios/USD
cd USD
git checkout v19.11
```
compiling:
`python USD\build_scripts\build_usd.py --build-args=boost,"--with-date_time --with-thread --with-system --with-filesystem" --force-all --no-maya --python --no-houdini "e:\myproject\usd_19_11_boost_no_alembic"`

With the repo as is and modifying the D:\myproject\usd_19_11_boost_no_alembic\cmake\pxrTargets.cmake file
with : (see issue #86 : https://github.com/Autodesk/maya-usd/issues/86 )

```
# Loop over all imported files and verify that they actually existforeach(target ${_IMPORT_CHECK_TARGETS} )  foreach(file ${_IMPORT_CHECK_FILES_FOR_${target}} )#    if(NOT EXISTS "${file}" )#      message(FATAL_ERROR "The imported target \"${target}\" references the file   \"${file}\"# =============================================================================================    get_filename_component(barename "${file}" NAME_WE)    # HACK - the following are dynamic libs in Windows (no .lib) - these will be dll's only    set(skip_dynamic_libs "hdStream" "usdObj" "usdShaders")    list(FIND skip_dynamic_libs ${barename} _index)    if(NOT EXISTS "${file}" AND NOT ((${_index} GREATER -1) AND WIN32))# =============================================================================================      message(FATAL_ERROR "The imported target \"${target}\" references the file         \"${file}\"but this file does not exist.  Possible reasons include:* The file was deleted, renamed, or moved to another location.* An install or uninstall procedure did not complete successfully.* The installation package was faulty and contained   \"${CMAKE_CURRENT_LIST_FILE}\"but not all the files it references.")    endif()  endforeach()  unset(_IMPORT_CHECK_FILES_FOR_${target})endforeach()
--

```

Then compile maya-usd with :
`python build.py --maya-location="c:\Program Files\autodesk\Maya2020" --pxrusd-location="e:\myproject\usd_19_11_boost_no_alembic" --devkit-location="d:\myproject\external\Maya\sdk\2020\devkitbase" e:\\maya_usd_19_11`

And I have errors :
` 22>Génération du projet "E:\maya_usd_19_11_hamed\build\RelWithDebInfo\plugin\al\lib\AL_USDMaya\_AL_USDMaya.vcxproj" terminée (cibles par défaut).
     7>ClCompile:
         Unknown compiler version - please run the configure tests and report the results
         test_DiffPrimVar.cpp
         Unknown compiler version - please run the configure tests and report the results
         test_SelectabilityDB.cpp
         test_translators_AnimationTranslator.cpp
         Unknown compiler version - please run the configure tests and report the results
         test_translators_CameraTranslator.cpp
         Unknown compiler version - please run the configure tests and report the results
         Unknown compiler version - please run the configure tests and report the results
         test_translators_DgTranslator.cpp
         Unknown compiler version - please run the configure tests and report the results
         test_translators_MeshTranslator.cpp
         test_translators_NurbsCurveTranslator.cpp
         test_translators_PythonBindings.cpp
         Unknown compiler version - please run the configure tests and report the results
         Unknown compiler version - please run the configure tests and report the results
         Unknown compiler version - please run the configure tests and report the results
         test_translators_TransformTranslator.cpp
         test_translators_Translator.cpp
         test_usdmaya.cpp
         test_usdmaya_AttributeType.cpp
         Unknown compiler version - please run the configure tests and report the results
         Unknown compiler version - please run the configure tests and report the results
         Unknown compiler version - please run the configure tests and report the results
         Unknown compiler version - please run the configure tests and report the results
       Link:
         C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.16.27023\bin\HostX86\x64\link.exe /ERRORREPORT:QUEUE /OUT:"E:\maya_usd_19_11_hamed\build\RelWithDebInfo\plugin\al\plugin\AL_USDMayaTestPlugin\RelWithDebInfo\AL_USDMayaTestPlugin.mll" /INCREMENTAL /NOLOGO ..\..\lib\AL_USDMaya\RelWithDebInfo\AL_USDMaya.lib ..\..\mayatest\AL\maya\test\RelWithDebInfo\AL_MayaTest.lib ..\..\schemas\AL\usd\schemas\maya\RelWithDebInfo\AL_USDMayaSchemas.lib ..\..\schemas\AL\usd\schemas\mayatest\RelWithDebInfo\AL_USDMayaSchemasTest.lib "..\..\..\..\googletest-install\lib\gtest.lib" ..\..\usdmayautils\AL\usdmaya\utils\RelWithDebInfo\AL_USDMayaUtils.lib ..\..\mayautils\AL\maya\RelWithDebInfo\AL_MayaUtils.lib ..\..\utils\AL\RelWithDebInfo\AL_EventSystem.lib ..\..\usdutils\AL\usd\utils\RelWithDebInfo\AL_USDUtils.lib ..\..\usdtransaction\AL\usd\transaction\RelWithDebInfo\AL_USDTransaction.lib "D:\myproject\usd_19_11_boost_no_alembic\lib\boost_thread-vc141-mt-1_65_1.lib" "D:\myproject\usd_19_11_boost_no_alembic\lib\boost_chrono-vc141-mt-1_65_1.lib" "D:\myproject\usd_19_11_boost_no_alembic\lib\boost_date_time-vc141-mt-1_65_1.lib" ..\..\..\..\lib\RelWithDebInfo\mayaUsd.lib D:\myproject\usd_19_11_boost_no_alembic\lib\usdUtils.lib D:\myproject\usd_19_11_boost_no_alembic\lib\usdImagingGL.lib D:\myproject\usd_19_11_boost_no_alembic\lib\usdImaging.lib D:\myproject\usd_19_11_boost_no_alembic\lib\usdVol.lib D:\myproject\usd_19_11_boost_no_alembic\lib\usdHydra.lib D:\myproject\usd_19_11_boost_no_alembic\lib\hdx.lib D:\myproject\usd_19_11_boost_no_alembic\lib\hdSt.lib D:\myproject\usd_19_11_boost_no_alembic\lib\hd.lib D:\myproject\usd_19_11_boost_no_alembic\lib\pxOsd.lib D:\myproject\usd_19_11_boost_no_alembic\lib\cameraUtil.lib D:\myproject\usd_19_11_boost_no_alembic\lib\hio.lib D:\myproject\usd_19_11_boost_no_alembic\lib\glf.lib D:\myproject\usd_19_11_boost_no_alembic\lib\garch.lib D:\myproject\usd_19_11_boost_no_alembic\lib\hf.lib D:\myproject\usd_19_11_boost_no_alembic\lib\osdCPU.lib D:\myproject\usd_19_11_boost_no_alembic\lib\osdGPU.lib D:\myproject\usd_19_11_boost_no_alembic\lib\hgiGL.lib opengl32.lib glu32.lib D:\myproject\usd_19_11_boost_no_alembic\lib\glew32.lib D:\myproject\usd_19_11_boost_no_alembic\lib\hgi.lib D:\myproject\usd_19_11_boost_no_alembic\lib\usdRi.lib D:\myproject\usd_19_11_boost_no_alembic\lib\usdLux.lib D:\myproject\usd_19_11_boost_no_alembic\lib\usdShade.lib D:\myproject\usd_19_11_boost_no_alembic\lib\sdr.lib D:\myproject\usd_19_11_boost_no_alembic\lib\ndr.lib D:\myproject\usd_19_11_boost_no_alembic\lib\usdSkel.lib D:\dxm\external\Maya\sdk\2020\devkitBase\devkit\ufe\lib\ufe_1.lib "D:\myproject\usd_19_11_boost_no_alembic\lib\boost_filesystem-vc141-mt-1_65_1.lib" "D:\myproject\usd_19_11_boost_no_alembic\lib\boost_system-vc141-mt-1_65_1.lib" "C:\Program Files\Autodesk\Maya2019\lib\OpenMaya.lib" "C:\Program Files\Autodesk\Maya2019\lib\OpenMayaAnim.lib" "C:\Program Files\Autodesk\Maya2019\lib\OpenMayaFX.lib" "C:\Program Files\Autodesk\Maya2019\lib\OpenMayaUI.lib" "C:\Program Files\Autodesk\Maya2019\lib\OpenMayaRender.lib" "C:\Program Files\Autodesk\Maya2019\lib\Image.lib" "C:\Program Files\Autodesk\Maya2019\lib\Foundation.lib" "C:\Program Files\Autodesk\Maya2019\lib\IMFbase.lib" "C:\Program Files\Autodesk\Maya2019\lib\tbb.lib" "C:\Program Files\Autodesk\Maya2019\lib\cg.lib" "C:\Program Files\Autodesk\Maya2019\lib\cgGL.lib" D:\myproject\usd_19_11_boost_no_alembic\lib\usdGeom.lib D:\myproject\usd_19_11_boost_no_alembic\lib\usd.lib D:\myproject\usd_19_11_boost_no_alembic\lib\kind.lib D:\myproject\usd_19_11_boost_no_alembic\lib\pcp.lib D:\myproject\usd_19_11_boost_no_alembic\lib\sdf.lib D:\myproject\usd_19_11_boost_no_alembic\lib\ar.lib D:\myproject\usd_19_11_boost_no_alembic\lib\plug.lib D:\myproject\usd_19_11_boost_no_alembic\lib\vt.lib D:\myproject\usd_19_11_boost_no_alembic\lib\gf.lib D:\myproject\usd_19_11_boost_no_alembic\lib\work.lib D:\myproject\usd_19_11_boost_no_alembic\lib\trace.lib D:\myproject\usd_19_11_boost_no_alembic\lib\js.lib D:\myproject\usd_19_11_boost_no_alembic\lib\tf.lib D:\myproject\usd_19_11_boost_no_alembic\lib\arch.lib Ws2_32.lib Dbghelp.lib Shlwapi.lib "D:\myproject\usd_19_11_boost_no_alembic\lib\boost_python-vc141-mt-1_65_1.lib" C:\Python27\libs\python27.lib D:\myproject\usd_19_11_boost_no_alembic\lib\tbb.lib C:\Python27\libs\Python27.lib kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /DEBUG /PDB:"E:/maya_usd_19_11_hamed/build/RelWithDebInfo/plugin/al/plugin/AL_USDMayaTestPlugin/RelWithDebInfo/AL_USDMayaTestPlugin.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:"E:/maya_usd_19_11_hamed/build/RelWithDebInfo/plugin/al/plugin/AL_USDMayaTestPlugin/RelWithDebInfo/AL_USDMayaTestPlugin.lib" /MACHINE:X64  /machine:x64 /DLL AL_USDMayaTestPlugin.dir\RelWithDebInfo\plugin.obj
         AL_USDMayaTestPlugin.dir\RelWithDebInfo\test_DiffCore.obj
         AL_USDMayaTestPlugin.dir\RelWithDebInfo\test_EventHandler.obj
         AL_USDMayaTestPlugin.dir\RelWithDebInfo\test_MatrixToSRT.obj
         AL_USDMayaTestPlugin.dir\RelWithDebInfo\test_MayaEventManager.obj
         AL_USDMayaTestPlugin.dir\RelWithDebInfo\test_ExportCommands.obj
         AL_USDMayaTestPlugin.dir\RelWithDebInfo\test_InternalProxySelection.obj
         AL_USDMayaTestPlugin.dir\RelWithDebInfo\test_LayerCommands.obj
         AL_USDMayaTestPlugin.dir\RelWithDebInfo\test_LayerManagerCommands.obj
         AL_USDMayaTestPlugin.dir\RelWithDebInfo\test_ProxyShapeImport.obj
         AL_USDMayaTestPlugin.dir\RelWithDebInfo\test_ProxyShapeSelect.obj
         AL_USDMayaTestPlugin.dir\RelWithDebInfo\test_TranslateCommand.obj
         AL_USDMayaTestPlugin.dir\RelWithDebInfo\export_blendshape.obj
         AL_USDMayaTestPlugin.dir\RelWithDebInfo\export_constraints.obj
         AL_USDMayaTestPlugin.dir\RelWithDebInfo\export_ik.obj
         AL_USDMayaTestPlugin.dir\RelWithDebInfo\export_import_instancing.obj
         AL_USDMayaTestPlugin.dir\RelWithDebInfo\export_lattice.obj
         AL_USDMayaTestPlugin.dir\RelWithDebInfo\export_multiple_shapes.obj
         AL_USDMayaTestPlugin.dir\RelWithDebInfo\export_nonlinear.obj
         AL_USDMayaTestPlugin.dir\RelWithDebInfo\export_unmerged.obj
         AL_USDMayaTestPlugin.dir\RelWithDebInfo\import_instances.obj
         AL_USDMayaTestPlugin.dir\RelWithDebInfo\test_activeInActiveTranslators.obj
         AL_USDMayaTestPlugin.dir\RelWithDebInfo\test_PrimFilter.obj
         AL_USDMayaTestPlugin.dir\RelWithDebInfo\test_ActiveInactive.obj
         AL_USDMayaTestPlugin.dir\RelWithDebInfo\test_ExtraDataPlugin.obj
         AL_USDMayaTestPlugin.dir\RelWithDebInfo\test_LayerManager.obj
         AL_USDMayaTestPlugin.dir\RelWithDebInfo\test_ProxyShape.obj
         AL_USDMayaTestPlugin.dir\RelWithDebInfo\test_ProxyShapeSelectabilityDB.obj
         AL_USDMayaTestPlugin.dir\RelWithDebInfo\test_ProxyUsdGeomCamera.obj
         AL_USDMayaTestPlugin.dir\RelWithDebInfo\test_Transform.obj
         AL_USDMayaTestPlugin.dir\RelWithDebInfo\test_TransformMatrix.obj
         AL_USDMayaTestPlugin.dir\RelWithDebInfo\test_ScopeMatrix.obj
         AL_USDMayaTestPlugin.dir\RelWithDebInfo\test_TranslatorContext.obj
         AL_USDMayaTestPlugin.dir\RelWithDebInfo\test_DiffGeom.obj
         AL_USDMayaTestPlugin.dir\RelWithDebInfo\test_DiffPrimVar.obj
         AL_USDMayaTestPlugin.dir\RelWithDebInfo\test_SelectabilityDB.obj
         AL_USDMayaTestPlugin.dir\RelWithDebInfo\test_translators_AnimationTranslator.obj
         AL_USDMayaTestPlugin.dir\RelWithDebInfo\test_translators_CameraTranslator.obj
         AL_USDMayaTestPlugin.dir\RelWithDebInfo\test_translators_DgTranslator.obj
         AL_USDMayaTestPlugin.dir\RelWithDebInfo\test_translators_MeshTranslator.obj
         AL_USDMayaTestPlugin.dir\RelWithDebInfo\test_translators_NurbsCurveTranslator.obj
         AL_USDMayaTestPlugin.dir\RelWithDebInfo\test_translators_PythonBindings.obj
         AL_USDMayaTestPlugin.dir\RelWithDebInfo\test_translators_TransformTranslator.obj
         AL_USDMayaTestPlugin.dir\RelWithDebInfo\test_translators_Translator.obj
         AL_USDMayaTestPlugin.dir\RelWithDebInfo\test_usdmaya.obj
         AL_USDMayaTestPlugin.dir\RelWithDebInfo\test_usdmaya_AttributeType.obj
            Creating library E:/maya_usd_19_11_hamed/build/RelWithDebInfo/plugin/al/plugin/AL_USDMayaTestPlugin/RelWithDebInfo/AL_USDMayaTestPlugin.lib and object E:/maya_usd_19_11_hamed/build/RelWithDebInfo/plugin/al/plugin/AL_USDMayaTestPlugin/RelWithDebInfo/AL_USDMayaTestPlugin.exp
         AL_USDMayaTestPlugin.vcxproj -> E:\maya_usd_19_11_hamed\build\RelWithDebInfo\plugin\al\plugin\AL_USDMayaTestPlugin\RelWithDebInfo\AL_USDMayaTestPlugin.mll
       FinalizeBuildStatus:
         Suppression du fichier "AL_USDMayaTestPlugin.dir\RelWithDebInfo\AL_USDMa.2BA446DB.tlog\unsuccessfulbuild".
         Mise à jour de l'horodatage "AL_USDMayaTestPlugin.dir\RelWithDebInfo\AL_USDMa.2BA446DB.tlog\AL_USDMayaTestPlugin.lastbuildstate".
     7>Génération du projet "E:\maya_usd_19_11_hamed\build\RelWithDebInfo\plugin\al\plugin\AL_USDMayaTestPlugin\AL_USDMayaTestPlugin.vcxproj" terminée (cibles par défaut).
     3>Génération du projet "E:\maya_usd_19_11_hamed\build\RelWithDebInfo\ALL_BUILD.vcxproj" terminée (cibles par défaut) -- ÉCHEC.
     1>Génération du projet "E:\maya_usd_19_11_hamed\build\RelWithDebInfo\install.vcxproj" terminée (cibles par défaut) -- ÉCHEC.

ÉCHEC de la build.

       "E:\maya_usd_19_11_hamed\build\RelWithDebInfo\install.vcxproj" (cible par défaut) (1) ->
       "E:\maya_usd_19_11_hamed\build\RelWithDebInfo\ALL_BUILD.vcxproj" (cible par défaut) (3) ->
       "E:\maya_usd_19_11_hamed\build\RelWithDebInfo\plugin\al\usdtransaction\AL\usd\transaction\tests\AL_USDTransactionTests.vcxproj" (cible par défaut) (21) ->
       (Link cible) ->
         LINK : warning LNK4044: unrecognized option '/lpthread'; ignored [E:\maya_usd_19_11_hamed\build\RelWithDebInfo\plugin\al\usdtransaction\AL\usd\transaction\tests\AL_USDTransactionTests.vcxproj]
         LINK : warning LNK4044: unrecognized option '/lm'; ignored [E:\maya_usd_19_11_hamed\build\RelWithDebInfo\plugin\al\usdtransaction\AL\usd\transaction\tests\AL_USDTransactionTests.vcxproj]

       "E:\maya_usd_19_11_hamed\build\RelWithDebInfo\install.vcxproj" (cible par défaut) (1) ->
       "E:\maya_usd_19_11_hamed\build\RelWithDebInfo\ALL_BUILD.vcxproj" (cible par défaut) (3) ->
       "E:\maya_usd_19_11_hamed\build\RelWithDebInfo\plugin\al\plugin\AL_USDMayaPlugin\AL_USDMayaPlugin.vcxproj" (cible par défaut) (11) ->
       (ClCompile cible) ->
         D:\myproject\usd_19_11_boost_no_alembic\include\boost-1_65_1\boost/date_time/dst_rules.hpp(330): warning C4002: too many arguments for function-like macro invocation 'fsin' [E:\maya_usd_19_11_hamed\build\RelWithDebInfo\plugin\al\plugin\AL_USDMayaPlugin\AL_USDMayaPlugin.vcxproj]

       "E:\maya_usd_19_11_hamed\build\RelWithDebInfo\install.vcxproj" (cible par défaut) (1) ->
       "E:\maya_usd_19_11_hamed\build\RelWithDebInfo\ALL_BUILD.vcxproj" (cible par défaut) (3) ->
       "E:\maya_usd_19_11_hamed\build\RelWithDebInfo\plugin\al\plugin\AL_USDMayaPlugin\AL_USDMayaPlugin.vcxproj" (cible par défaut) (11) ->
       (ClCompile cible) ->
         D:\myproject\usd_19_11_boost_no_alembic\include\boost-1_65_1\boost/date_time/dst_rules.hpp(330): error C2220: warning treated as error - no 'object' file generated [E:\maya_usd_19_11_hamed\build\RelWithDebInfo\plugin\al\plugin\AL_USDMayaPlugin\AL_USDMayaPlugin.vcxproj]

    3 Avertissement(s)
    1 Erreur(s)

Temps écoulé 00:06:49.80

Traceback (most recent call last):
  File "build.py", line 564, in <module>
    BuildAndInstall(context, context.buildArgs, context.stagesArgs)
  File "build.py", line 341, in BuildAndInstall
    RunCMake(context, extraArgs, stagesArgs)
  File "build.py", line 257, in RunCMake
    multiproc=FormatMultiProcs(context.numJobs, generator)))
  File "build.py", line 140, in Run
    .format(cmd=cmd, log=os.path.abspath(context.logFileLocation)))
RuntimeError: Failed to run 'cmake --build . --config RelWithDebInfo --target install -- /M:12'
See e:\maya_usd_19_11_hamed\build\RelWithDebInfo\build_log.txt for more details.`

[build_log.txt](https://github.com/Autodesk/maya-usd/files/4140606/build_log.txt)

I don't know if you can help.

**Comment by HamedSabri-adsk** [comment]
Hi @fdevic, 

We can't reproduce this issue on our side. Can you please try these steps to see if it helps:

1- do a clean build of USD with following arguments:
`- python USD\build_scripts\build_usd.py "e:\myproject\usd_19_11_boost_no_alembic" --build args=boost,"--with-date_time --with-thread --with-system --with-filesystem" `

2- do a clean build of maya-usd with PXR_STRICT_BUILD_MODE set to OFF
`python build.py --maya-location="c:\Program Files\autodesk\Maya2020" --pxrusd-location="e:\myproject\usd_19_11_boost_no_alembic" --devkit-location="d:\myproject\external\Maya\sdk\2020\devkitbase" e:\\maya_usd_19_11 --build-args="-DPXR_STRICT_BUILD_MODE=OFF" `

**Comment by fdevic** [comment]
Hello Hamed!

So the compilation worked like a charm (well nearly;) `C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\VC\VCTargets\Microsoft.CppBuild.targets(321,5): error MSB3491: Impossible d'écrire des lignes dans le fichier "x64\Release\usdRecursivePayloadsExample_headerfiles\usdRecur.BEAF2291.tlog\usdRecursivePayloadsExample_headerfiles.lastbuildstate". Le chemin d'accès spécifié, le nom de fichier ou les deux sont trop longs. Le nom de fichier qualifié complet doit comprendre moins de 260 caractères et le nom du répertoire moins de 248 caractères. [E:\github\usd\args=boost,--with-date_time --with-thread --with-system --with-filesystem\USD\extras\usd\examples\usdRecursivePayloadsExample\usdRecursivePayloadsExample_headerfiles.vcxproj]`)

SO I changed the folder name and it worked!

`E:\github\usd>python USD\build_scripts\build_usd.py "e:\myproject\usd_19_11_3" --build-args=boost,"--with-date_time --with-thread --with-system --with-filesystem"

Building with settings:
  USD source directory          E:\github\usd\USD
  USD install directory         e:\myproject\usd_19_11_3
  3rd-party source directory    e:\myproject\usd_19_11_3\src
  3rd-party install directory   e:\myproject\usd_19_11_3
  Build directory               e:\myproject\usd_19_11_3\build
  CMake generator               Default
  Downloader                    curl

  Building                      Shared libraries
    Config                      Release
    Imaging                     On
      Ptex support:             Off
      OpenImageIO support:      Off
      OpenColorIO support:      Off
      PRMan support:            Off
    UsdImaging                  On
      usdview:                  On
    Python support              On
    Documentation               Off
    Tests                       Off
    Alembic Plugin              Off
      HDF5 support:             Off
    Draco Plugin                Off
    MaterialX Plugin            Off
    Maya Plugin                 Off
    Katana Plugin               Off
    Houdini Plugin              Off

  Dependencies                  zlib, boost, TBB, OpenEXR, GLEW, OpenSubdiv
  Build arguments               boost: --with-date_time --with-thread --with-system --with-filesystem
STATUS: Installing zlib...
STATUS: Installing boost...
STATUS: Installing TBB...
STATUS: Installing OpenEXR...
STATUS: Installing GLEW...
STATUS: Installing OpenSubdiv...
STATUS: Installing USD...

Success! To use USD, please ensure that you have:

    The following in your PYTHONPATH environment variable:
    e:\myproject\usd_19_11_3\lib\python

    The following in your PATH environment variable:
    e:\myproject\usd_19_11_3\bin
    e:\myproject\usd_19_11_3\lib


E:\github\usd>cd..

E:\github>cd maya-usd

E:\github\maya-usd>python build.py --maya-location="c:\Program Files\autodesk\Maya2020" --pxrusd-location="e:\myproject\usd_19_11_3" --devkit-location="d:\myproject\external\Maya\sdk\2020\devkitbase" e:\\maya_usd_19_11_3 --build-args="-DPXR_STRICT_BUILD_MODE=OFF"

    Building with settings:
      Source directory          E:\github\maya-usd
      Workspace directory       e:\maya_usd_19_11_3
      Build directory           e:\maya_usd_19_11_3\build\RelWithDebInfo
      Install directory         e:\maya_usd_19_11_3\install\RelWithDebInfo
      Variant                   RelWithDebInfo
      Python Debug              Off
      CMake generator           Default
      Build Log                 e:\maya_usd_19_11_3\build\RelWithDebInfo\build_log.txt
      Build arguments           ['-DPXR_STRICT_BUILD_MODE=OFF']
      Stages arguments          ['clean', 'configure', 'build', 'install']
Success MayaUSD build and install !!!!`

UNfortunatelly, once in Maya :
`// Error: file: C:/Program Files/Autodesk/Maya2020/scripts/others/pluginWin.mel line 317: Unable to dynamically load : E:/maya_usd_19_11_3/install/RelWithDebInfo/plugin/pxr/maya/plugin/pxrUsd.mll
La procédure spécifiée est introuvable.
 // 
// Error: file: C:/Program Files/Autodesk/Maya2020/scripts/others/pluginWin.mel line 317: La procédure spécifiée est introuvable.
 (pxrUsd) // 
// Error: file: C:/Program Files/Autodesk/Maya2020/scripts/others/pluginWin.mel line 317: Unable to dynamically load : E:/maya_usd_19_11_3/install/RelWithDebInfo/plugin/pxr/maya/plugin/pxrUsdPreviewSurface.mll
La procédure spécifiée est introuvable.
 // 
// Error: file: C:/Program Files/Autodesk/Maya2020/scripts/others/pluginWin.mel line 317: La procédure spécifiée est introuvable.
 (pxrUsdPreviewSurface) // 
// Error: file: C:/Program Files/Autodesk/Maya2020/scripts/others/pluginWin.mel line 317: Unable to dynamically load : E:/maya_usd_19_11_3/install/RelWithDebInfo/plugin/adsk/plugin/mayaUsdPlugin.mll
La procédure spécifiée est introuvable.
 // 
// Error: file: C:/Program Files/Autodesk/Maya2020/scripts/others/pluginWin.mel line 317: La procédure spécifiée est introuvable.
 (mayaUsdPlugin) // 
// Error: file: C:/Program Files/Autodesk/Maya2020/scripts/others/pluginWin.mel line 317: Unable to dynamically load : E:/maya_usd_19_11_3/install/RelWithDebInfo/plugin/al/plugin/AL_USDMayaPlugin.mll
La procédure spécifiée est introuvable.
 // 
// Error: file: C:/Program Files/Autodesk/Maya2020/scripts/others/pluginWin.mel line 317: La procédure spécifiée est introuvable.
 (AL_USDMayaPlugin) // 
// Error: file: C:/Program Files/Autodesk/Maya2020/scripts/others/pluginWin.mel line 317: Unable to dynamically load : E:/maya_usd_19_11_3/install/RelWithDebInfo/plugin/al/plugin/AL_USDMayaPxrTranslators.mll
La procédure spécifiée est introuvable.
 // 
// Error: file: C:/Program Files/Autodesk/Maya2020/scripts/others/pluginWin.mel line 317: La procédure spécifiée est introuvable.
 (AL_USDMayaPxrTranslators) // 
// Error: file: C:/Program Files/Autodesk/Maya2020/scripts/others/pluginWin.mel line 317: Unable to dynamically load : E:/maya_usd_19_11_3/install/RelWithDebInfo/plugin/al/plugin/AL_USDMayaTestPlugin.mll
La procédure spécifiée est introuvable.
 // 
// Error: file: C:/Program Files/Autodesk/Maya2020/scripts/others/pluginWin.mel line 317: La procédure spécifiée est introuvable.
 (AL_USDMayaTestPlugin) // `
I maybe forgot to setup a path in the environment

**Comment by emilche** [comment]
I am also getting the same error message and upon using --build-args="-DPXR_STRICT_BUILD_MODE=OFF" I also get successful build but end up in the exact same position as fdevic with Unable to dynamically load and maya crashes when i try to load.

**Comment by HamedSabri-adsk** [comment]
We had a closer look at the reported issues today:

**1- Compilation issue: warning treated as error**

We do hit this problem on certain Maya 2019.x versions but not Maya2020.x It is unclear to us at the moment what exactly the issue is here. For now, the suggested workaround is to build the project with PXR_STRICT_BUILD_MODE set to OFF.

**2- Plugins load issues**

We were able to load all the plugins on both Maya2019.x and Maya2020.x on Windows. 

In Maya2019.x only, we get this error that are investigating:

`# ImportError: No module named mayaUsd.lib`

I was able to reproduce the errors reported in this ticket when I didn't use the correct UFE versions:

For Maya2019.x and Maya2020, one must use **UFE v1.0.0**
For Maya2020 PR112, one must use **UFE v0.2.5**

Also, we recommend switching to **USD v20.02**. I will update the build doc sometimes this week.

@emilche I can't see why maya crashes.  Can you please upload your build_log.txt?

**Comment by HamedSabri-adsk** [comment]
**Update:** This issue with `# ImportError: No module named mayaUsd.lib` is now resolved with PR #282 and is now part of dev branch.

**Comment by HamedSabri-adsk** [comment]
@fdevic  can you close this ticket if you longer see any issues? 
Thanks.

**Comment by fdevic** [comment]
Hello @HamedSabri-adsk.
As I won't be able to test it in Maya but the compilation works, I am closing it ;)
