### ISSUE TITLE
[MAYA-122712] Selection Color not Respecting Color Settings for USD Data, Causing Multiple Issues

### ISSUE THREAD

**Issue by Ziethriel** [Autodesk/maya-usd#2330]
**Describe the bug**
After installing and using version 0.17 when selecting referenced USD content the warnings below occur:
```
// Error: line 1: 'lead' is an unknown RGB display color name // 
// Warning: Failed to obtain selection highlight color for 'lead' objects // 
```

**Steps to reproduce**
1. Install Version 0.17 on Maya 2022.3
2. Create Cube
3. Assign USDPreviewSurface and change the display color
4. Export as USD
5. Import USD as new stage in new file
6. Create Maya Cube next to original
7. Change Color Settings > Active > Lead object to a new color
8. Select Maya Cube
9. Observe Wireframe selection color is new color
10. Select USD Cube
11. Observe Original selection color and errors in description

**Expected behavior**
When selecting the USD Cube the wireframe will be the color selected in Color Settings and no errors will occur.

**Specs (if applicable):**
 - Windows 10
 - Maya version 2022.3
 - Maya USD Release 0.17.0
 - VRAY Version 5.20.01

**Additional context**
It is unclear how this bug started, but it was shortly after installing version 0.17. Clearing player prefs and reinstalling Maya both do not fix the issue. After this bug showed up I am also unable to render USD data in VRAY viewport rendering.

**Comment by neilrubie** [comment]
We are encountering this bug as well. Any kind of selection on loaded usd geo throws the error. It seems the "lead" displayRGBColor name is not defined inside maya out of the box. I was able to fixthis by manually defining it as follows in the script editor:

`color_index = cmds.displayColor("lead", query=True, active=True)
lead_color = cmds.colorIndex(color_index, query=True)
cmds.displayRGBColor("lead", lead_color[0], lead_color[1], lead_color[2], create=True)
`
I grabbed the color values from the "lead" displayColor in maya (note this is different than displayRGBColor). Though I'm not sure the values matter all that much as I don't see any difference in selection color when I put in different values.

**Comment by Ziethriel** [comment]
> We are encountering this bug as well. Any kind of selection on loaded usd geo throws the error. It seems the "lead" displayRGBColor name is not defined inside maya out of the box. I was able to fix this by manually defining it as follows in the script editor:
> 
> ```
> color_index = cmds.displayColor("lead", query=True, active=True)
> lead_color = cmds.colorIndex(color_index, query=True)
> cmds.displayRGBColor("lead", lead_color[0], lead_color[1], lead_color[2], create=True)
> ```
> 
> I grabbed the color values from the "lead" displayColor in maya (note this is different than displayRGBColor). Though I'm not sure the values matter all that much as I don't see any difference in selection color when I put in different values.

I tried this and got the message `// Error: Line 1.64: Invalid use of Maya object "True". //`

Any insight?

**Comment by neilrubie** [comment]
> > We are encountering this bug as well. Any kind of selection on loaded usd geo throws the error. It seems the "lead" displayRGBColor name is not defined inside maya out of the box. I was able to fix this by manually defining it as follows in the script editor:
> > ```
> > color_index = cmds.displayColor("lead", query=True, active=True)
> > lead_color = cmds.colorIndex(color_index, query=True)
> > cmds.displayRGBColor("lead", lead_color[0], lead_color[1], lead_color[2], create=True)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I grabbed the color values from the "lead" displayColor in maya (note this is different than displayRGBColor). Though I'm not sure the values matter all that much as I don't see any difference in selection color when I put in different values.
> 
> I tried this and got the message `// Error: Line 1.64: Invalid use of Maya object "True". //`
> 
> Any insight?

It sounds like you're attempting to execute this as a mel script. This is python code, try executing in the python tab of the script editor.

**Comment by Ziethriel** [comment]
Oops, yeah, I was running it in a MEL window. This fix resolves the issue when selecting individual USD Prims, but I still get the error below when shift-selecting any two USD Prims.

**Comment by Ziethriel** [comment]
Misclicked the close with comment button instead of Comment... Sorry


Anyways, thanks for the workaround, however this seems to only work for individual prim selections one at a time, but still having the issue when shift-click selecting multiple prims.

`select -r |Scene|Shape,/Assets/Toolbox ;
select -tgl |Scene|Shape,/Assets/Data_Analysis_Table ;
// Error: line 1: 'polymeshActive' is an unknown RGB display color name // 
`

**Comment by santosd** [comment]
I know that since the release you originally saw this issue in there have been some updates in the preferences for lead color and USD awareness of that Maya setting. Wondering if you could test the latest 2023 update with the latest Maya USD release to see if you are still seeing the issue.

**Comment by Ziethriel** [comment]
As absurd as it sounds (and is), my org is still vetting Maya 2023 for deployment. I anticipate based on how previous approvals have gone, I should have access to it by the end of the month.

**Comment by fabal** [comment]
Hi @santosd , this issue doesn't happen in Maya 2023 as far as I can tell but definitely does in 2022 in our case too. I've silent it internally but I'm not familiar enough with the intricacies of the mel commands used in that portion of the code to submit a formal PR. I think it is worthwhile addressing the issue for Maya versions older than 2023.

**Comment by Ziethriel** [comment]
I can confirm this is fixed in Maya 2023. Thank You! (I know, my org took ten months to get a software we have a maintenance agreement for approved internally)

**Comment by santosd** [comment]
> Hi @santosd , this issue doesn't happen in Maya 2023 as far as I can tell but definitely does in 2022 in our case too. I've silent it internally but I'm not familiar enough with the intricacies of the mel commands used in that portion of the code to submit a formal PR. I think it is worthwhile addressing the issue for Maya versions older than 2023.

Hi @fabal , unfortunately, the fix seems to be on the Maya code side and not on the Maya USD plugin side so a fix in a previous version is more difficult to get.
