### ISSUE TITLE
[MAYA-128599] Modify > Center Pivot does not work with Point Instancers

### ISSUE THREAD

**Issue by dj-mcg** [Autodesk/maya-usd#2332]
**Describe the bug**
Modify > Center Pivot should center the pivot at the centroid of all the instancers when a Point Instancer is selected. It currently appears to do nothing.

**Steps to reproduce**
1. Rename the attached file from pi.txt to pi.usda and save
2. Open the usda file by choosing Create > USD > From File 
3. Select the point instancer
4. Hit W to see the translate manip
5. Modify > Center Pivot
6. Observe the pivot has not moved from the origin

**Expected behavior**
The transform should be updated, compensating the other point instancer attributes accordingly, so that the pivot is now positioned at the centroid of the instances.

**Specs (if applicable):**
 - Linux 64bit
 - Maya 2022
 - Latest MayaUsd dev
 - Latest USD dev
[pi.txt](https://github.com/Autodesk/maya-usd/files/8636276/pi.txt)

**Comment by dj-mcg** [comment]
This is pixar internal jira MAYA-3298

**Comment by santosg87** [comment]
@dj-mcg we have this currently working internally. are you able to try this on the most recent mayausd build? :)

**Comment by dj-mcg** [comment]
Just FYI, I pulled down the latest and built. I'm running against 2023.1 and it doesn't seem to work. I see this in my transcript:

`// Warning: Illegal call to unimplemented UsdSetXformOpUndoableCommandBase::execute()
// Warning: Illegal call to unimplemented UsdSetXformOpUndoableCommandBase::redo()`

**Comment by santosg87** [comment]
@dj-mcg we have made a fix for this issue, but there were some changes required on the maya side. we have this currently working on our internal builds.

**Comment by santosg87** [comment]
@dj-mcg small update on this issue.

the center pivot function does center the pivot, but it is not persistent. we have logged MAYA-128599 to track this second behavior.

**Comment by dj-mcg** [comment]
Hi @santosg87 - I was able to confirm the behavior you last described in 2023.3 (centers but not persistent) - thanks for the update
