### ISSUE TITLE
Maya 2022: Extra __Prototype# scopes created when deactivating instances

### ISSUE THREAD

**Issue by dj-mcg** [Autodesk/maya-usd#2338]
**Describe the bug**
Sometimes when you deactivate or reactivate instanced prims it will create these weird zombie __Prototype# scopes under the proxyShape scope that can't be deleted, deactivated or moved.

**Steps to reproduce**
1. Create > Universal Scene Description > Stage From File... open Kitchen_set_instanced.usd
2. expand the group with the cheerios
3. deactivate the last cheerio in the list -> creates a __Prototype# scope
4. deactivate the next visible scope, BowlD_1. nothing happens. reactivate it -> creates another __Prototype# scope
5. deactivate and reactivate the next visible scope, Ceiling_grp -> creates another __Prototype# scope

**Expected behavior**
These _Prototype scopes do not appear

**Specs (if applicable):**
 - Linux 64 bit
 - Maya 2022
 - Latest MayaUsd dev
 - Latest USD dev

This is internal Pixar Jira MAYA-3309

![mayaUsd_deactivatePrim](https://user-images.githubusercontent.com/48066546/167309553-064fe699-c748-45bd-9300-ced16c548d57.gif)

**Comment by santosd** [comment]
Thank you @dj-mcg,

I took a look at this on Windows and Linux in Maya 2023 using 0.18.0 which we recently released and I was not able to reproduce the error. I tested in Maya 2022 using MayaUSD 0.18.0 and I was able to repro the error there. It seems this was an issue that was fixed with a Maya side change unfortunately.

**Comment by dj-mcg** [comment]
Sorry for the delay, @santosd - it looks like it's fixed in 2023 for us! Thank you!

**Comment by santosd** [comment]
No problem at all, thank you for confirming :)
