### ISSUE TITLE
[MAYA-123815] Crash when reparenting to a deactivated scope

### ISSUE THREAD

**Issue by dj-mcg** [Autodesk/maya-usd#2339]
**Describe the bug**
If you try to (or accidentally) reparent a scope under a deactivated scope, maya will crash

**Steps to reproduce**
1. Replace the suffix on the attached txt file to usd
2. Open the usd file with Create > USD > Stage From File...
3. Middle mouse drag Capsule1 to Xform1, which is deactivated
4. Observe the crash

**Expected behavior**
Reparenting under a deactivated transform should ideally be allowed and automatically deactivate the child. Short of that, it should not be allowed.

**Specs (if applicable):**
 - Linux 64 bit
 - Maya 2022
 - Latest MayaUsd dev
 - Latest USD dev

This is internal Pixar Jira MAYA-3308

[reparentDeactivated.txt](https://github.com/Autodesk/maya-usd/files/8653474/reparentDeactivated.txt)

![repro](https://user-images.githubusercontent.com/48066546/167456107-26e4f98f-dccc-4383-8e8a-ee3121c650e2.gif)

**Comment by santosg87** [comment]
I can also reproduce this on our side. logged internally as MAYA-123815

**Comment by santosg87** [comment]
@dj-mcg the fix for this issue is now available, but it requires Maya 2023.2, as the changes needed to be on the maya side as well. marking this as closed for now. :)
