### ISSUE TITLE
USD Export "Export All" seg-faults Maya

### ISSUE THREAD

**Issue by ColinKennedy** [Autodesk/maya-usd#2341]
**Describe the bug**
File > Export All seg-faults a specific Maya scene file.

**Steps to reproduce**
1. Open the attached .ma file
2. Run `from maya import cmds; cmds.file(exportAll=True, type="USD Export")` in the command-line / script editor

Maya will crash midway during export

2b. If you run  `from maya import cmds; cmds.file(exportAll=True, type="Arnold-USD")` it doesn't crash. I wonder if the presence of Arnold DG nodes in the scene caused the problem?

**Expected behavior**
I expected USD to export or fail with a pop-up if the export could not be complete.

**Attachments**
[Use this link](https://www.dropbox.com/s/m20egbm4n7yev4e/simple_shader_test.ma?dl=0) to download a reproduction .ma file

**Specs (if applicable):**
 - OS & version [e.g. Windows 10]: Version	10.0.19043 Build 19043
 - Maya version [e.g. Maya 2020]: Maya 2023
 - Maya USD commit SHA [e.g. dev at caa921c1]:  005eca8a94777b407c4e4b8b4f28dd962c80ea11 (v0.17.0)

**Comment by santosg87** [comment]
Hi @ColinKennedy,

is it ok to close this issue for now?

**Comment by ColinKennedy** [comment]
I don't have a regular Maya license so I'm unable to load and reproduce this at this time. You can close if you wish
