### ISSUE TITLE
[MAYA-125142] Chaser factory context GetDagToUsdMap() raises error

### ISSUE THREAD

**Issue by cgboffin** [Autodesk/maya-usd#2365]
**Describe the bug**
# TypeError: No Python class registered for C++ class std::map<Autodesk::Maya::OpenMaya20220000::MDagPath, pxrInternal_v0_21__pxrReserved__::SdfPath, pxrInternal_v0_21__pxrReserved__::UsdMayaUtil::_CmpDag, std::allocator<std::pair<Autodesk::Maya::OpenMaya20220000::MDagPath const, pxrInternal_v0_21__pxrReserved__::SdfPath> > > # 

**Steps to reproduce**
1. Create python wrapped export chaser
2. attempt to call factory context data "GetDagToUsdMap"

**Expected behavior**
Return a python dict() of {MDagPath: SdfPath}.

**Comment by willis102** [comment]
Hi, is there any update on this?  I'm also running into this bug in v0.19.0

**Comment by pierrebai-adsk** [comment]
A fix for it was merged in the dev branch. See: https://github.com/Autodesk/maya-usd/pull/2584/files.

**Comment by oumad** [comment]
was this fixed in mayaUSD 0.20.0 ? whenever I try to call 

```py
mayaUsdLib.UsdMayaExportChaserRegistryFactoryContext.GetDagToUsdMap()
```
in an export chaser I just get
```
Error: RuntimeError: Tf Python Exception
```

Is there an example of a working export chaser done with python that traverses the dagnodes/prims ? the one in the `testExportChaser.py` is very simple and doesn't use the `GetDagToUsdMap` method.

**Comment by oumad** [comment]
> Yes, it was fixed in the PR that is linked above and is part of 0.20. A Python unit test was added that calls it. Please report back if the fix somehow does not work for you.

Yes I confirm it works fine for me in 0.20.0, it's a different syntax than the way I tried before, I was looking at an older version of the unit test.
I was trying to retrieve the context with this line : 
```py
mayaUsdLib.UsdMayaExportChaserRegistryFactoryContext.GetDagToUsdMap()
```
That fails, so after following the more recent test unit example `testExportChaser.py`, I'm doing it this way, and it works : 
```py
class myExportChaser(mayaUsdLib.ExportChaser):
    dagToUsd = {}
    stage = {}

    def __init__(self, factoryContext, *args, **kwargs):
        super(gearExportChaser, self).__init__(factoryContext, *args, **kwargs)
        myExportChaser.dagToUsd = factoryContext.GetDagToUsdMap()
        myExportChaser.stage = factoryContext.GetStage()

    def ExportDefault(self):
        stage = myExportChaser.stage
        for p in myExportChaser.dagToUsd:
                prim_path = p.data()
                dag_path = p.key()
                # the process...
        return self.ExportFrame(Usd.TimeCode.Default())
    
    def ExportFrame(self, frame):
        exportChaserTest.ExportFrameCalled = True
        return True

    def PostExport(self):
        exportChaserTest.PostExportCalled = True
        return True
```

Thank you.

Just debugging the code can be difficult since we don't see the actual error in the chaser, we only get :
```
Error: RuntimeError: Tf Python Exception
```

**Comment by pierrebai-adsk** [comment]
Ah, I did not notice the exception messages were so devoid of any helpful content. You can file a request for enhancement to ask for better error messages. Even better if you could submit a pull request that improves them! :)

**Comment by oumad** [comment]
> Ah, I did not notice the exception messages were so devoid of any helpful content. You can file a request for enhancement to ask for better error messages. Even better if you could submit a pull request that improves them! :)

I would love to submit a pull request if I know where to go about this :D I believe this must be handled in the C++ function right, using boost ?
I also never built this project on my side but I can try !
I would love to also add some info in the docs for other people like me, especially related to transferring custom attributes between maya and USD and I think many people might be confused same as I was on how to do that easily in their pipeline,.

**Comment by pierrebai-adsk** [comment]
Documentation is a good idea. We have some technical docs but currently none that give a complete example of the chaser API. We write such docs in markdown.

The existing docs are here: https://github.com/Autodesk/maya-usd/blob/dev/README_DOC.md
