### ISSUE TITLE
Outliner: Duplicating a prim collapses the hierarchy (MAYA-114344 should be the same cause)

### ISSUE THREAD

**Issue by gracekumagai** [Autodesk/maya-usd#2375]
**Describe the bug**
Duplicating a prim in the outliner collapses the hierarchy.

**Steps to reproduce**
1. Open `kitchen_set_instanced`
2. Select `|Kitchen_set_instanced|Kitchen_set_instancedShape,/Kitchen_set/Props_grp/Ceiling_grp/CeilingLight_1`
3. **BUG** Press Ctrl+D to duplicate - notice that the outliner hierarchy collapses to the Kitchen set node

There's also a Tf Python Exception in the Script Editor when undoing the duplicate.

**Expected behavior**
We would expect the same behaviour as native Maya where the hierarchy does not collapse when duplicating nodes.

**Attachments**
![duplicate_outliner](https://user-images.githubusercontent.com/12554015/170112809-4e2f1ebd-19bc-466c-ac59-de69e2b0135e.gif)

**Specs (if applicable):**
 - Linux
 - maya2023.base
Pixar Internal Jira MAYA-3344

**Comment by santosg87** [comment]
@gracekumagai after some investigating, this seems to be an issue on the maya side as well as mayaUSD. the fix will require to be in a new maya version. 

this should be fixed by the same changes in #1767 :)

**Comment by santosg87** [comment]
@gracekumagai this should be fixed on Maya 2023.2 - are you able to test and confirm?

**Comment by santosg87** [comment]
marking this one as closed for the time being. Feel free to re-open it if this issue is still persisting on your side. :)

**Comment by gracekumagai** [comment]
I tested in 2023.2 and it's fixed! thank you!
