### ISSUE TITLE
AL test failure: AL_MayaUtilsTests (SEGFAULT)

### ISSUE THREAD

**Issue by elrond79** [Autodesk/maya-usd#238]
Don't have too much more info on this one, but I get a segfault when running this test. This is the only output:

```
 1/77 Test #69: AL_MayaUtilsTests ...............................***Exception: SegFault  3.68 sec
```

This crashes in both debug and release builds.  It seems to finish successfully - I see the happy green dino - but then it segfaults on python exit (with no stack trace):

```
[  PASSED  ] 36 tests.
               __
              /"_)
     _.----._/ /
    /         /
 __/ (  | (  |
/__.-'|_|--|_|
Stack trace:


0% tests passed, 1 tests failed out of 1

```

Does anyone else see this behavior on Linux?

**Comment by elrond79** [comment]
Also, I noticed that the return code from the test isn't used / returned:

https://github.com/Autodesk/maya-usd/blob/a29704fbab510e76667c25c7d528649540113c00/plugin/al/mayautils/AL/maya/tests/mayaplugintest/CMakeLists.txt#L104

**Comment by HamedSabri-adsk** [comment]
> sts/mayaplugintest/CMakeLists.txt

we don't need the ret= , I already have it removed locally with some other changes for the next PR. not a big deal for now.

As for Linux, I don't see this problem either in debug or release. The SegFault rings a bell and it was a case on MacOSX when we were linking statically against gtest.  After we switched to linking dynamically to gtest, SegFault went away... That's all I know....

**Comment by ppt-adsk** [comment]
I've seen the Python crash on exit problem in our mayaUsd lib tests, and I fixed it here:
https://github.com/Autodesk/maya-usd/pull/210/commits/6cf32fbdc9334741bf83de3423cbbe59a7fca5a6
Not sure if that's what you're hitting, but if the renderSetup plugin is loaded, might be worth a try unloading it before exit.

**Comment by elrond79** [comment]
closing this since it's a dupe of #316, and that one has a bit more details...
