### ISSUE TITLE
[MAYA-125054] USD layerEditor dropdown list doesn't update when renaming namespace.

### ISSUE THREAD

**Issue by lucasIllusorium** [Autodesk/maya-usd#2381]
**Describe the bug**
When you add a namespace to a usdProxyShape, and then rename the namespace from the NS editor. The usdStage dropdown in the USD layer editor does not update. 

**Steps to reproduce**
1. Create a usdProxyShape. Create->usd->stage from file
2. Open the NS editor, and add the usdProxyShape to a NS.
At this step, the usdStage dropdown in the USD layer editor does update as expected.
3. Rename the NS from the NS editor.
4. The usdStage dropdown in the USD layer editor does not update. 

**Expected behavior**
The usdStage dropdown in the USD layer editor should be updating with the scene data.

**Attachments**
steps 1 and 2
![maya_E1eHx1HCAC](https://user-images.githubusercontent.com/102531374/170467426-ad1b7bf3-c2e5-4f2b-ba53-5a5eb21839ff.png)
step 3
![maya_VBIVCg3AIh](https://user-images.githubusercontent.com/102531374/170467436-35c440c6-9103-49f6-a656-1c762493a872.png)
![maya_K35y0FMRqG](https://user-images.githubusercontent.com/102531374/170467447-78ab6bc5-d59e-4a6e-8d3b-73e6f2bc934d.png)
step 4
![maya_KIq2vSn1lh](https://user-images.githubusercontent.com/102531374/170467459-73164dc1-062a-45ed-8b14-59e362f97c6e.png)

**Specs (if applicable):**
 - OS Windows 11
 - Maya 2022.3 py2
 - Maya USD 0.18.0

**Comment by lucasIllusorium** [comment]
Also, this happens all the time and is pretty annoying... This is not related to the issue NS or the usdStage dropdown.

select -r sh0020:shot ;
# Error: Failed verification: ' handle.isValid() ' -- Cannot get path from invalid object handle # 
# Error: Failed verification: ' handle.isValid() ' -- Cannot get path from invalid object handle # 
# Error: Failed verification: ' handle.isValid() ' -- Cannot get path from invalid object handle # 
# Error: Failed verification: ' handle.isValid() ' -- Cannot get path from invalid object handle # 
# Error: Failed verification: ' handle.isValid() ' -- Cannot get path from invalid object handle # 
# Error: Failed verification: ' handle.isValid() ' -- Cannot get path from invalid object handle # 
# Error: Failed verification: ' handle.isValid() ' -- Cannot get path from invalid object handle # 
# Error: Failed verification: ' handle.isValid() ' -- Cannot get path from invalid object handle # 
# Error: Failed verification: ' handle.isValid() ' -- Cannot get path from invalid object handle # 
# Error: Failed verification: ' handle.isValid() ' -- Cannot get path from invalid object handle # 
# Error: Failed verification: ' handle.isValid() ' -- Cannot get path from invalid object handle # 
# Error: Failed verification: ' handle.isValid() ' -- Cannot get path from invalid object handle # 
# Error: Failed verification: ' handle.isValid() ' -- Cannot get path from invalid object handle # 
# Error: Failed verification: ' handle.isValid() ' -- Cannot get path from invalid object handle # 
# Error: Failed verification: ' handle.isValid() ' -- Cannot get path from invalid object handle # 
// Error: Failed verification: ' handle.isValid() ' -- Cannot get path from invalid object handle // 
// Error: Failed verification: ' handle.isValid() ' -- Cannot get path from invalid object handle // 
// Error: Failed verification: ' handle.isValid() ' -- Cannot get path from invalid object handle // 
// Error: Failed verification: ' handle.isValid() ' -- Cannot get path from invalid object handle // 
// Error: Failed verification: ' handle.isValid() ' -- Cannot get path from invalid object handle // 
// Error: Failed verification: ' handle.isValid() ' -- Cannot get path from invalid object handle // 
// Error: Failed verification: ' handle.isValid() ' -- Cannot get path from invalid object handle // 
// Error: Failed verification: ' handle.isValid() ' -- Cannot get path from invalid object handle // 
// Error: Failed verification: ' handle.isValid() ' -- Cannot get path from invalid object handle // 
// Error: Failed verification: ' handle.isValid() ' -- Cannot get path from invalid object handle // 
// Error: Failed verification: ' handle.isValid() ' -- Cannot get path from invalid object handle // 
// Error: Failed verification: ' handle.isValid() ' -- Cannot get path from invalid object handle // 
// Error: Failed verification: ' handle.isValid() ' -- Cannot get path from invalid object handle // 
// Error: Failed verification: ' handle.isValid() ' -- Cannot get path from invalid object handle // 
// Error: Failed verification: ' handle.isValid() ' -- Cannot get path from invalid object handle // 
// Error: Failed verification: ' handle.isValid() ' -- Cannot get path from invalid object handle // 
// Error: Failed verification: ' handle.isValid() ' -- Cannot get path from invalid object handle // 
// Error: Failed verification: ' handle.isValid() ' -- Cannot get path from invalid object handle // 
// Error: Failed verification: ' handle.isValid() ' -- Cannot get path from invalid object handle // 
// Error: Failed verification: ' handle.isValid() ' -- Cannot get path from invalid object handle // 
// Error: Failed verification: ' handle.isValid() ' -- Cannot get path from invalid object handle // 
// Error: Failed verification: ' handle.isValid() ' -- Cannot get path from invalid object handle // 
// Error: Failed verification: ' handle.isValid() ' -- Cannot get path from invalid object handle // 
// Error: Failed verification: ' handle.isValid() ' -- Cannot get path from invalid object handle //

**Comment by Lucas3Dspain** [comment]
I can confirm this is not happening any more.

Using:
Windows 10
Maya 2023.3
mayaUsd 0.22.0
