### ISSUE TITLE
Broadcast/Document the USD, MAyaUSD tags that are officially used by each version of Maya. 

### ISSUE THREAD

**Issue by ansuter** [Autodesk/maya-usd#2392]
**Is your feature request related to a problem? Please describe.**
I recently just built MayaUSD against USD 21.08 with python 3.9 to start migrating our toolsets to Maya 2023. It wasn't until I built it that I realized plugins like Bifrost have a set version (I knew Arnold did, but wasn't aware with Bifrost), but it seems not building MayaUSD against the same version as Bifrost will result in some incompatibility. Turns out Bifrost uses 0.21.11.

![image](https://user-images.githubusercontent.com/16786318/171228129-d4521786-a475-44e1-8e27-b3b15a63c778.png)

![image](https://user-images.githubusercontent.com/16786318/171230451-f7f8adc7-6b95-45f6-936f-9cd931690159.png)

**Describe the solution you'd like**
An update to documentation would look nice. The tagged versions in the docs stop at 21.08, so it's not clear to me that 0.21.11 was ever used anywhere.

**Describe alternatives you've considered**
I'll try and build 0.21.11, but it might be useful to have a matrix of what official versions of USD/MayaUSD are used with which version of Maya.

**Additional context**
N/a

**Comment by ansuter** [comment]
https://help.autodesk.com/view/BIFROST/ENU/?guid=Bifrost_ReleaseNotes_release_notes_release_notes_2_4_0_0_html - the compatibility notes are tucked away here, but might be good to broadcast this on github too so people don't waste time building a version that won't work.

**Comment by santosg87** [comment]
thanks for bringing this up @ansuter.

we usually mention the latest USD version used on the release tags:
https://github.com/Autodesk/maya-usd/releases/tag/v0.18.0

I will bring this discussion up to them team though, and we will see if there are maybe better places to mention that info so its more clear :)
