### ISSUE TITLE
[MAYA-123876] "Save the Maya scene file and USD files" save option does not save the session layer

### ISSUE THREAD

**Issue by gracekumagai** [Autodesk/maya-usd#2399]
**Describe the bug**
[Save USD Option](https://help.autodesk.com/view/MAYAUL/2023/ENU/?guid=GUID-EEBC1C65-0805-4488-80C7-3C061B316294): "Save the Maya scene file and USD files (recommended)" does not save the session layer. Any edits made to it are lost after saving with this option.

A workaround is to save with option 2 at the start (Save all edits, including USD, to the Maya scene file). Then, saving with option 1 seems to save the session layer as expected.

**Steps to reproduce**
Open a new file in Maya 2023
1. Navigate to Create -> Universal Scene Description (USD) -> Stage with new layer
2. Right click on the proxy shape -> Add new prim -> Capsule
3. Right click in Outliner and open the USD Layer Editor
4. Set the session layer as the edit target
5. Select Capsule1 and navigate to Display -> Hide Selection
6. Navigate to File -> Save As, enter a scratch file name
7. In Save USD options window, select the first option and in the next pop-up select Save Stage(s) button

Notice that the capsule reappears after saving. The session layer edits were not saved.

**Expected behavior**
We would expect the first save option to also save the session layer. We would expect all save options to save it.

**Specs (if applicable):**
 - Linux
 - Maya2023.base

Pixar internal JIRA MAYA-3364

**Comment by santosg87** [comment]
@gracekumagai the fix for this is available on 0.19.0. are you able to test and confirm?

**Comment by gracekumagai** [comment]
Hey @santosg87 - I can no longer repro! Thank you!
