### ISSUE TITLE
Building latest release advice

### ISSUE THREAD

**Issue by Liametc** [Autodesk/maya-usd#24]
Hi there, 

Just trying to build from the most up-to-date master branch and getting some compilation errors. I've attached the log file.
[build_log.txt](https://github.com/Autodesk/maya-usd/files/3524907/build_log.txt)
I have been following your build instructions to the letter (although not using Ninja). Pixar USD has been built using the boost flags specified, and the environment is set up correctly as far as I can tell. 
I'm very much a noob at compiling from source still, and my knowledge of C++ is limited. I am assuming that the current master branch is compiling for you, so it must be something my end. Any help would be appreciated.

This is on a centos 7 system, with maya 2019, devkit update 2 and usd 19.07

Thanks

Liam

**Comment by Liametc** [comment]
The previous build_log was without the AL plugin. Here's one with the whole shebang 
[build_log_with_AL.txt](https://github.com/Autodesk/maya-usd/files/3525010/build_log_with_AL.txt)

**Comment by kxl-adsk** [comment]
For `master` branch, we are using USD 19.05. It's documented in https://github.com/Autodesk/maya-usd/blob/master/doc/build.md, but not as easy to find as it should be.

**Comment by Liametc** [comment]
I did see that, but as you're latest release was tagged 19.07 (and behind the master branch), I thought it hadn't been updated for some reason. I will attempt to build against this now. 
Thanks

**Comment by kxl-adsk** [comment]
Tags came in from Pixar & AL repository...we thought about renaming them to avoid confusion but for now, we try to limit what gets renamed until everything is moved and we don't have to merge new changes from both AL & PXR.

**Comment by Liametc** [comment]
That makes sense, if a little confusing. 
It still fails, for slightly different reasons, but still during compilation. I've attached the logs once more
[build_log_19_05.txt](https://github.com/Autodesk/maya-usd/files/3525629/build_log_19_05.txt)

**Comment by seando-adsk** [comment]
From your build log it looks as though you are building with gcc 4.8.5. Building with some of the components enabled (such as UFE) requires at least gcc 6.3.1. Since you're on CentOS7 you should already have that in the devtoolsets. In your shell, use this command to enable:

scl enable devtoolset-6 bash

**Comment by Liametc** [comment]
Took me a while to get that working properly in docker, but it's at least built the AL plugin now. I'm enabling the PXR_VALIDATE_GENERATED_CODE flag as it appears to skip the pxr plugin if this is not set. Will report back. Thanks for the help

**Comment by Liametc** [comment]
No, the pxr plugin won't build 
[build_log_gcc_6.txt](https://github.com/Autodesk/maya-usd/files/3526421/build_log_gcc_6.txt)
Any ideas?

**Comment by Liametc** [comment]
Update, this all built fine and with a little tweaking of some environment paths worked fine too. Thanks for the tool and the help. Much appreciated
