### ISSUE TITLE
Unable to load plugins Maya 2020 /dev branch/usd 19.11

### ISSUE THREAD

**Issue by Xaia** [Autodesk/maya-usd#241]
Just successfully compiled dev branch and usd 19.11 
Maya 2020
Windows 10
Python 2.7

my env var
``` C:/Users/xaia/Documents/maya/2020/plug-ins;C:/Usersxaia/Documents/maya/plug-ins;C:/Program Files/Autodesk/Maya2020/bin/plug-ins;C:/MayaUSD/plugin/al/plug-ins;C:/Program Files/Autodesk/Maya2020/plug-ins/ATF/plug-ins;C:/Program Files/Autodesk/Bifrost/Maya2020/2.0.3.0/bifrost/plug-ins;C:/Program Files/Autodesk/Maya2020/plug-ins/MASH/plug-ins;C:/MayaUSD/plugin/adsk/plug-ins;C:/MayaUSD/plug-ins;C:/MayaUSD/plugin/pxr/plug-ins;C:/ProgramData/Autodesk/ApplicationPlugins/QuadRemesher/Contents/plug-ins;C:/USD/plug-ins;C:/Program Files/Autodesk/Maya2020/plug-ins/fbx/plug-ins;C:/Program Files/Autodesk/Maya2020/plug-ins/camd/plug-ins;C:/solidangle/mtoadeploy/2020/plug-ins;C:/Program Files/Allegorithmic/Substance in Maya/2020/plug-ins;C:/Program Files/Autodesk/Bifrost/Maya2020/2.0.3.0/vnn/plug-ins;C:/Program Files/Autodesk/Maya2020/plug-ins/xgen/plug-ins;C:/MayaUSD/plugin/al/plugin;C:/MayaUSD/plugin/adsk/plugin;C:/MayaUSD/plugin/pxr/maya/plugin ```

getting those errors when I try to enable the plugins
![usd](https://user-images.githubusercontent.com/60515654/73584720-9a252780-449a-11ea-8b51-8d294f68bc1a.png)
```

// Error: file: C:/Program Files/Autodesk/Maya2020/scripts/others/pluginWin.mel line 317: initializePlugin function failed (AL_USDMayaTestPlugin) // 
# Traceback (most recent call last):
#   File "C:\MayaUSD\plugin\al\lib\python\AL\usd\schemas\mayatest\__init__.py", line 1, in <module>
#     from . import _AL_USDMayaSchemasTest
# ImportError: DLL load failed: A dynamic link library (DLL) initialization routine failed.
// Error: file: C:/Program Files/Autodesk/Maya2020/scripts/others/pluginWin.mel line 317: Unable to dynamically load : C:/MayaUSD/plugin/pxr/maya/plugin/pxrUsd.mll
A dynamic link library (DLL) initialization routine failed.
 // 
// Error: file: C:/Program Files/Autodesk/Maya2020/scripts/others/pluginWin.mel line 317: A dynamic link library (DLL) initialization routine failed.
 (pxrUsd) // 
```

**Comment by emilche** [comment]
I am also getting this on Maya 2019.

**Comment by HamedSabri-adsk** [comment]
@Xaia  Please see https://github.com/Autodesk/maya-usd/issues/233

**Comment by HamedSabri-adsk** [comment]
@Xaia can you close this ticket if you longer see any issues? 
Thanks.
