### ISSUE TITLE
[MAYA-125953] Add -worldspace flag mayaUSDExport

### ISSUE THREAD

**Issue by daviddeacon** [Autodesk/maya-usd#2430]
Hi,

I would like to export part of a Maya hierarchy to USD, excluding the parent transforms, this works with exportRoots flag, but any translation/rotation/scale that are on the parent transforms are lost. I would really need these to be applied as part of the export.

Could a world space flag be added to mayaUSDExport command? This ideally would just be like the one that's included in the alembic exporter.

David.

**Comment by SelivanovaLera** [comment]
Are there any any updates regarding this issue?
We are also interested in it.

**Comment by tanant** [comment]
Heya @SelivanovaLera / @daviddeacon - I'm doing some internal planning here and have tagged this issue. No promises, but wanted to at least mention it's one that I've earmarked out.

**Comment by tanant** [comment]
admin action - logged internally as MAYA-125953

**Comment by santosg87** [comment]
this should be available on the most recent builds of MayaUSD.

Marking this issue as closed. :)
