### ISSUE TITLE
Disable Material calculation in Viewport

### ISSUE THREAD

**Issue by KoljaHuebschmann** [Autodesk/maya-usd#2452]
**Is your feature request related to a problem? Please describe.**

The issue mentioned in here:
https://github.com/Autodesk/maya-usd/issues/2312
https://github.com/Autodesk/maya-usd/issues/2330

```
// Error: line 1: 'lead' is an unknown RGB display color name // 
// Warning: Failed to obtain selection highlight color for 'lead' objects // 
```

If there is a proxyAccessor connection into the stage (or out of the stage), these material errors makes scrubbing though the timeline very slow, so you can not "animate" in that scene.

**Describe the solution you'd like**

First I was thinking of just turning of the error logs would be enough. 
But I think having a way to turn of the calculation of materials in general per stage would be the better solution.

So just having a bool property on the USDShape that turns of materials for the viewport would be a nice.

**Describe alternatives you've considered**

I added for every asset/bundle a "util" material variant, that turns the asset into a simple grey shaded asset. If working on a shot context I switch with an layer all assets to this util material and the scene will not be slow anymore. If this scene gets renderd, I disable this layer.

**Comment by santosg87** [comment]
@KoljaHuebschmann I believe this is now the default behavior on MayaUSD. loading a stage will follow the maya Standard with a default gray look for everything, and if the user would like to see the materials on it, they would press 6/turn on mateirals on the viewport.

it worth noting that the errors might still show up, but the performance  of scenes should be much better now.

closing this issue for the time being. feel free to re-open/log something else if you find this is not working as expected. :)
