### ISSUE TITLE
[MAYA-125057] MayaUsdProxy node not refreshing properly

### ISSUE THREAD

**Issue by neilrubie** [Autodesk/maya-usd#2465]
**Describe the bug**
I am attempting to load a usd stage inside a MayaUsdProxy node using python code, however the stage doesn't appear to load under certain circumstances. Specifically when the anonymous  session/root layer has unsaved edits, and you perform a save operation directly prior to setting the proxy filePath attribute.

**Steps to reproduce**
1) Create an empty MayaUsdProxy node in the scene root (Create->USD->Stage with New Layer)
2) Expand the proxy to its shape and add an xform (right-click on stageShape1->Add New Prim->Xform
3) Run this code all in one execution. (saves the file out then sets the proxy filepath to a predefined usd file, which I've attached)

```
cmds.file(
    "/tmp/save_test.ma",
    type="mayaAscii",
    force=True,
    exportAll=True,
    preserveReferences=True,
    exportUnloadedReferences=True
)

cmds.setAttr("stageShape1.filePath", "/tmp/cube.usda", type="string")
```

After doing this, the proxy filepath attribute appears to be populated, but the usd file itself did not get loaded. The proxy's root layer is still pointing to an anonymous layer:
![image](https://user-images.githubusercontent.com/83896816/177873456-d01fe6fb-bec5-4421-8bae-17467f09ee4e.png)

**Expected behavior**
I expect that any existing root layer (anonymous or not) gets cleared out and replaced by the layer specified by the filepath.

**Attachments**
[cube.zip](https://github.com/Autodesk/maya-usd/files/9067477/cube.zip)

**Specs (if applicable):**
 - CentOS 7.9
 - Maya version 2022.3
 - Maya USD commit: 0.18
 - Pixar USD commit: 21.08

**Additional context**
Things seem to work fine when I omit the save operation in the code. And they work fine when I execute the code separately and sequentially. And it works fine if there are no edits on the anonymous session or root layer. It just so happens that I need it to work under this perfect storm of a scenario..

**Comment by santosg87** [comment]
I was able to reproduce this on our side as well. it seems to only happen when the user saves all edits to the Maya scene, which is likely causing the "stuck" state of the layers. I logged this internally so we can investigate further and discuss next steps

**Comment by santosg87** [comment]
@neilrubie I was not able to reproduce this issue on the latest build of mayausd and Maya.

I am closing this as "cannot reproduce" for the time being, feel free to re-open if you can still reproduce this or if you have any more information. 

cheers!

**Comment by DanGroverUK** [comment]
This issue still occurs for me using Maya 2022, MayaUSD 0.26.0 on Windows 10. 

However (and I'm not sure if you're still looking for a solution @neilrubie ) but I found that by adding these lines...

`import AETemplateHelpers  
# That assumes "MayaUSD3/plugin/asdk/scripts" is on your system path as per the default .mod file I believe
cmds.file(
    "/tmp/save_test.ma",
    type="mayaAscii",
    force=True,
    exportAll=True,
    preserveReferences=True,
    exportUnloadedReferences=True
)

cmds.setAttr("stageShape1.filePath", "/tmp/cube.usda", type="string")
AETemplateHelpers.ProxyShapeFilePathRefresh("stageShape1.filePath")`

This has allowed me to re-path a stage successfully *if* - like in the above example - doing so is the last thing to happen in the code block. If you have more 'stuff' going on afterwards (and in my case I do, as this happens half way through a Shotgrid Publish), it still doesn't work unfortunately.

**Comment by neilrubie** [comment]
Thanks @DanGroverUK, I did end up finding solution that seems to work for me. It's pretty hacky, and don't ask me why it works, but it seems to get around the bug. Directly after you do your file export, perform another dummy export before setting the filepath on your proxy node:

```
# Perform normal file export.
cmds.file(
    "/tmp/save_test.ma",
    type="mayaAscii",
    force=True,
    exportAll=True,
    preserveReferences=True,
    exportUnloadedReferences=True
)

# Perform dummy export (don't export anything with a proxy node)
cmds.select("time1")
cmds.file(
    "/usr/tmp",
    type="mayaAscii",
    exportSelectedStrict=True,
    force=True,
    preview=True,
)

# Now the proxy node should refresh properly (fingers crossed)
cmds.setAttr("stageShape1.filePath", "/tmp/cube.usda", type="string")
```

Give that a try.

**Comment by neilrubie** [comment]
@DanGroverUK Haha a lot of trial and error and banging my head against the wall! Did it work for you as well? @santosg87 Can you reopen this ticket? I don't see any option to do so myself.

**Comment by renaudll** [comment]
This still happen in maya_usd-0.33.0 on maya-2026 (Linux Rocky-9).

Here's a simple reproduction script:

```
from maya import cmds

# Load plugin before importing mayaUsd.
cmds.loadPlugin("mayaUsdPlugin", quiet=True)

import mayaUsd.lib as mayaUsdLib

# Create two simple USD files.
def write_usd(path: str) -> str:
    """Write a minimal USD file to path and return path."""
    with open(path, "w", encoding="utf-8") as fp:
        fp.write('#usda 1.0\n(\n    defaultPrim = "Root"\n)\n\ndef Xform "Root"\n{\n}\n')
    return path

path1 = write_usd("/tmp/old.usda")
path2 = write_usd("/tmp/new.usda")

# New scene and create proxy.
cmds.file(new=True, force=True)
shape = cmds.createNode("mayaUsdProxyShape")
cmds.setAttr(f"{shape}.filePath", path1, type="string")

# Author an override.
stage = mayaUsdLib.GetPrim(shape).GetStage()
stage.GetDefaultPrim().SetActive(False)

# Save scene so outStageRootLayerId gets written.
cmds.file(rename="/tmp/test.ma")
cmds.file(save=True, force=True, type="mayaAscii")

# Switch to a different USD file.
cmds.setAttr(f"{shape}.filePath", path2, type="string")

# Show mismatch: filePath vs cached outStageRootLayerId.
print("filePath:", cmds.getAttr(f"{shape}.filePath"))
print("outStageRootLayerId:", cmds.getAttr(f"{shape}.outStageRootLayerId"))
```

For our use cases, it seem clearing `outStageRootLayerId` before setting `filePath` workaround the issue. 

```
cmds.setAttr(f"{shape}.outStageRootLayerId", "", type="string")
cmds.setAttr(f"{shape}.filePath", path, type="string")
```

Please don't hesitate to reach out if you need additional information.
