### ISSUE TITLE
[MAYA-124896] Shot node doesnt work with usd camera's

### ISSUE THREAD

**Issue by suekieza** [Autodesk/maya-usd#2474]
**Describe the bug**
Hey there, I would like to attach a shot node to my usd camera via the camera sequencer.

At the moment if I make the camera editable I can attach the shot node but when I merge back into my usd the shot node info/connection is lost.

**Steps to reproduce**
1. create a camera/ save it out to usd
2. import usd camera 
3. make a shot node in the camera sequencer try attach to usd camera(wont see usd camera at all)
4. make usd camera editable(by right clicking on it)
5. attach editable usd camera to shot node via the camera sequencer
6.merge back into usd
7. print usd from the layer editor
8. you will see no info about the shot node

**Expected behavior**
to be able to add a shot node to a usd camera

**Specs (if applicable):**
 - OS & version [e.g. Windows 11]
 - Maya version [e.g. Maya 2023]

Thanks Sue

**Comment by santosd** [comment]
Hi @suekieza, unfortunately we currently don't have sequencer shot support for USD cameras at this time. I will log this internally, but I am not sure where this lies in regards to our future priorities.

**Comment by santosd** [comment]
I have logged this internally as MAYA-124896.

**Comment by suekieza** [comment]
Thanks for the feedback

**Comment by santosd** [comment]
One possible workflow would be to save your Maya files with the cameras in the state where they are editable in Maya and add the Shot node to them there and then cache your camera out to USD. That way you have your Maya file with the shot node that you can always revert back to but only in the end would you go back to USD with the cameras themselves. I know it may not be ideal, but may be something you would work with in the mean time.
