### ISSUE TITLE
Bifrost USD 22.8 support

### ISSUE THREAD

**Issue by dgovil** [Autodesk/maya-usd#2522]
We're trying to use Bifrost in Maya 2023.1 and see no USD nodes.
The documentation for Bifrost says: "Bifrost-USD is included with Bifrost 2.4.0.0 and later versions, so no further set-up is required. However, the USD nodes are not available in the graph editor unless a compatible version of USD for Maya is also installed." 

However it doesn't specify what makes a Maya USD version compatible with Bifrost.  We've built with USD 22.8 and against 087df913730 , however we see no Bifrost USD nodes, which leads me to believe there's some kind of incompatibility. However I don't see anything that points to something actionable

The Script editor just mentions:

```
// Loading Bifrost version 2.4.0.0-202202121141-d3627ed
// Warning: Bifrost: Failed to read library config file /usr/local/apps/maya/2023.1/platform-osx/Applications/Autodesk/bifrost/maya2023/2.4.0.0/bifrost/packs/packs_plugin_config.json.
// Error: Error: Failed to locate Json doc 'bifrost:/usr/local/apps/maya/2023.1/platform-osx/Applications/Autodesk/bifrost/maya2023/2.4.0.0/bifrost/packs/usd_pack/0.22.8/plugin_config.json'.
```

I only see a USD 21.11 usd_pack in there. Is there a way to generate this for newer USD versions?  We're unable to use this old a USD version in our pipeline.

**Comment by santosd** [comment]
Hi @dgovil, we should probably specify better what version of Maya USD is compatible with which version of Bifrost USD. Bifrost USD is built against a particular USD version and if that doesn't match up with Maya USD then they will not sync and the nodes will not be available. Basically you would need to use the same build of Maya USD that shipped alongside that version of Bifrost USD in order for them to work together. If I am not mistaken that would be [0.18.0](https://github.com/Autodesk/maya-usd/releases/tag/v0.18.0). Unfortunately if you build it yourself and build with a different USD version, it will not be compatible with Bifrost USD. I hope that information is helpful. Let me know if you have other questions.

**Comment by dgovil** [comment]
I think that unfortunately makes Bifrost quite unusable for any pipelines that need custom builds for a variety of reasons (studio schemas, bug fixes, etc...)

Doesn't that also mean that users of Maya USD are at risk of breaking bifrost if they update their Maya usd plugin using the distribution here?

Would there be a possibility of open sourcing the bifrost USD nodes so users can build it against their cuts of USD?

**Comment by jonahfriedman** [comment]
Hello Dhruv (@dgovil)

Compatibility of the shipped BifrostUSD with MayaUSD is documented here. We are operating with this in mind, making sure that the Maya-USD ecosystem works together. 
https://knowledge.autodesk.com/support/maya/learn-explore/caas/simplecontent/content/maya-usd-bifrost-and-arnold-compatibility.html

As for using a custom build, we intend for Bifrost-USD to be an open source project. I can't say when this will happen as we can't talk about release dates. However, we are working toward this in a three step plan, two of which are already completed. Those were Bifrost-USD release in Bifrost 2.4, Bifrost operator SDK release in Bifrost 2.5 (whose scope is such that we can internally build Bifrost-USD with it), and the last step is an open source Bifrost-USD release.

**Comment by dgovil** [comment]
Ah thank you @jonahfriedman , my Google fu failed to find that page and it's quite useful. 

Totally understand on not being able to talk about release dates but I look forward to it. Thank you!

**Comment by tanant** [comment]
@jonahfriedman - if we referenced/linked that knowledge page into the rel notes or the top level readme.md think that'd help?

**Comment by santosg87** [comment]
closing this issues, based on the above discussion - as most of the answers are there, and there isn't much we can do on our side. :)
