### ISSUE TITLE
Maya crashes when loading the mtoh plug-in, Maya 2023

### ISSUE THREAD

**Issue by ChangCalvin** [Autodesk/maya-usd#2540]
Issue:
- Maya crashes when loading the mtoh plug-in. 
![image](https://user-images.githubusercontent.com/35354621/183498156-01bb0412-7e85-4d03-960f-fbfc5b2c595d.png)

To reproduce:
- Load mtoh plug-in under Windows -> settings/preferences -> plugin-in manager.
- The option to load mtoh should be under:
- ...\Autodesk\MayaUSD\Maya2023\0.18.0\mayausd\MayaUSD\lib\maya
- checking "loaded" will result in Maya 2023 crashing and going back in to the plugin-in manager will show that mtoh was not loaded/not checked,

note: mtoh.mll is not missing:
![image](https://user-images.githubusercontent.com/35354621/183734452-a35bae29-dbc6-4ce2-928b-51b20c1d59ed.png)

Specs:
- Windows 11
- Maya 2023.1, educational license 

Goal: 
- To enable additional hydra renderers to show up here: 
 ![image](https://user-images.githubusercontent.com/35354621/183496102-260d6e65-75ae-4e76-8daf-270b52b06d47.png)

I desire for the following to show up: 
- Hydra GL
- Hydra Arnold
- hdStorm
- etc.

Video Proof: 
https://user-images.githubusercontent.com/35354621/183724013-5c38cdd5-062d-448e-b24d-08a27d8c4cae.mp4

**Comment by santosg87** [comment]
Hi @ChangCalvin thank you for reporting this issue.

I am trying to reproduce this issue on my side. I don't see it happening. would you be able to send a bit more info on your system? things like your graphics card and windows 11 build. 

thank you!

**Comment by ChangCalvin** [comment]
Hi, 
For context:
I was working with multiple applications and I had setup USD with nvidia's prebuilt binaries. Following their install directions I had inadvertently setup "hardcoded" system level env variables. Sadly there was no guidance online or any tutorial videos at all. The best one I could find was this: https://www.youtube.com/watch?v=3QZCT6y2iXc&t=641s.

Current Date 8/15/22:
I fixed the issue, it seems that there was "some cross talk between my python versioning in my path variables. By isolating my env variables to be instanced per shell and removing all added path vars, maya began to work again. 

Thank you for your assistance and sorry about any stress or inconvenience this might have caused!

**Comment by santosd** [comment]
Thank you for letting us know and glad you were able to track down the issue and resolve it.
