### ISSUE TITLE
Enable MtoH on macOS for Storm - Metal (USD 22.5 and higher)

### ISSUE THREAD

**Issue by dgovil** [Autodesk/maya-usd#2545]
Since USD 22.5 has added Storm for Metal, it would be great if Maya USD could support the new Metal Storm renderer. I believe MtoH was previously disabled on macOS since Storm didn't work on that platform, but now that it's there, I think it would be really awesome to have that support.

I'm unsure if Autodesk is already planning this work, otherwise I'll try and free up some resources on my end to implement this, but I just wanted to make this issue to have a common basis to refer to in case we need to coordinate in any way.

Cheers!

**Comment by tanant** [comment]
Heya @dgovil - thanks for the note - lemme chase down internally for you and get back to you on what we're planning and have a chat. We've got people doing the post-siggraph phase of things right now and taking a quick break and so might be next week or next next - if you need something concrete sooner though, sing out and I'll make sure to jump on it.

**Comment by tanant** [comment]
@dgovil probably a dumb question - do you have a staged stacking of validation points around Storm/Metal? I had a couple in my head, but they start at "option available", "can select option and doesn't crash", "can show sphere with standard shader" and then leaps to "no problem showing kitchen set" with very little in between.

**Comment by dgovil** [comment]
Not a dumb question at all! It's one I wrack my brain about too.
I think those are generally the same steps I would have as well, for milestones. 
I'm not sure if there are test scenes for the MtoH capabilities for Windows/Linux that could be borrowed? That would be a good intermediate between sphere+shader and kitchen set perhaps

**Comment by santosg87** [comment]
we currently have metal working with MayaHydra, which should cover this. closing for now.
