### ISSUE TITLE
[MAYA-114188] Remember Edit Target on Saving

### ISSUE THREAD

**Issue by ZimuQin** [Autodesk/maya-usd#2556]
**Is your feature request related to a problem? Please describe.**
Each time when we re-opened a Maya scene file with USD, the edit target on each USD stage would be the root layer, so the artists need to make sure they are working on the correct layer. Also, when we save a Maya scene file with USD, if the edit target is an anonymous layer to be saved on disk, the edit target would be lost after saving.

**Describe the solution you'd like**
When a Maya file is saved, the current edit targets on all stages would be stored in the scene file, so that next time when the file is reopened, there's no need to check if we have set the correct edit target. If the edit target is an anonymous layer to be saved on disk, the edit target should be auto re-set to the saved USD file.

**Describe alternatives you've considered**
Our alternative solution is using multiple callbacks to save the layer's index in layer stack when saving a file, and use this information to set the edit target to the saved one while opening a scene. We chose to use index, not the identifier of the layer, because the identifier of the anonymous layer would be changed when it is saved to disk. This solution is far from perfect, because the USD file might be changed by other applications causing the layer stack to be modified, and the original index may become invalid or incorrect.

**Comment by womanyoyoyo-adsk** [comment]
Hi @ZimuQin , we have this issue logged internally as MAYA-114188 and here #1893. We see that this is affecting many customers.

**Comment by santosg87** [comment]
this fix should be avaialble now on mayausd 0.23.0

marking this as closed for the time being. :)
