### ISSUE TITLE
Solaris Arnold ignores some light parameters

### ISSUE THREAD

**Issue by Ahmed-Hindy** [Autodesk/maya-usd#2560]
**Describe the bug**
settings some primvars like "primvars:arnold:cast_shadows = 0" or "primvars:arnold:shadow_color = {0,1,0}" wont result in an update to the hydra viewer. restarting the hydra viewer doesnt solve it.

**Steps to reproduce**
1. use the "light" LOP to add some arnold light parameters like disabling "cast shadows" and setting "shadow color" to {0,1,0}
2. start the Arnold hydra delegate

**Expected behavior**
no shadows from lights, or if shadows are enabled then the shadows should be green.

**Attachments**
If applicable, add screenshots, sample files, etc to help explain your problem.

**Specs (if applicable):**
 - win 10, multiple builds across different machines
 - version Arnold 7.1.3.0
 - multiple PCs, first is "2 x Intel(R) Xeon(R) CPU E5-2680 v2", 2nd is "Ryzen 9 5950x"

First screenshot: Hydra viewer not respecting the "disable shadows"
2nd screenshot: Arnold USD procedural rendering the plain baked usd scene without any extras. Note how the shadows arent there !!

![Untitled](https://user-images.githubusercontent.com/23151881/186001548-dcba93ed-fef3-47df-b524-5ca94411f60e.png)
![Screenshot_14](https://user-images.githubusercontent.com/23151881/186001581-7ed92171-7eb9-42e4-9668-0b85a7b1fffd.png)

**Comment by sebastienblor** [comment]
Hi Ahmed, this ticket should really be in [arnold-usd](https://github.com/Autodesk/arnold-usd/) , it's not related to maya-usd at all. If this is with Houdini 19.5 then we have several open tickets about this in arnold-usd , that are currenly beig fixed. They seem to be caused by a change of behaviour after usd 21.08

Cheers

**Comment by Ahmed-Hindy** [comment]
yeah sorry wrong repository :)
the behavior was first noticed in H19.0 btw

**Comment by Ahmed-Hindy** [comment]
also submitted the issue there, you can close this one here,

link: https://github.com/Autodesk/arnold-usd/issues/1274
