### ISSUE TITLE
UsdUVTexture with UDIM Tag super slow to load

### ISSUE THREAD

**Issue by skarone** [Autodesk/maya-usd#2563]
**Is your feature request related to a problem? Please describe.**
When using <UDIM> on textures paths, slows down the loading of the USD file a lot (From less than a second, with no UDIM, to 10 seconds). This is per UsdUVTexture. 

**Describe the solution you'd like**
Reduce, slowness when loading, maybe use: 
[udimTexture](https://github.com/PixarAnimationStudios/USD/blob/4b1162957b2ad219e1635c81de8343be490e41fc/pxr/imaging/lib/glf/udimTexture.cpp)

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by santosg87** [comment]
hi @skarone thank you for logging this, would you be able to provide a bit more info on your findings? if you have a simple file showing the performance drop, that would be helpful. 

we have had improvements texture loading and performance on our last releases, which version of mayausd are you using?

**Comment by skarone** [comment]
Hi @santosg87,

Thanks for the quick feedback.
We are using version 0.13.0_202110191046-3a94a0f py2 on Maya2022.3, Centos 7.

I'm uploading a zip with 2 usda that are exactly the same, the only difference is the path to the texture, one uses <UDIM> and the other one no.
Loading UDIM vs No UDIM is a 5 seconds difference. 
This became a real problem for us, because we have to disable textures (active=false) before loading the usd assets. 

Cheers

[cube_udim.zip](https://github.com/Autodesk/maya-usd/files/9435464/cube_udim.zip)

**Comment by skarone** [comment]
@santosg87,
I tested with version: https://github.com/Autodesk/maya-usd/releases/tag/v0.19.0
And for sure there is a big improvement!, when loading assets with 10 textures.
v0.13 => 60 seconds.
v0.19 => 22 seconds.

I will close this ticket. Not sure if this can be improved more, but at least is a big difference

Cheers,
Ignacio
