### ISSUE TITLE
[MAYA-125028] Muted sublayers do not persist between sessions

### ISSUE THREAD

**Issue by yantor3d** [Autodesk/maya-usd#2567]
**Describe the bug**
Layers that are muted when the file is saved are not muted the next time you open the scene.

**Steps to reproduce**
1. Load a USD layer with one or more sublayers (attached)
2. Mute sublayer(s) in the UDS Layer Editor, or using the `mayaUsdLayerEditor` command.
3. Save the scene.
4. Re-open the scene.
5. Observe that the sublayer(s) are not muted.

**Attachments**
[mute.zip](https://github.com/Autodesk/maya-usd/files/9428237/mute.zip)

**Expected behavior**
Layers that are muted when the file is saved should still be muted the next time you open the scene.

**Specs (if applicable):**
 - OS - CentOS 7
 - Maya version(s)
   - Maya 2020.4 with MayaUSD 0.10.0 and USD 0.20.8
   - Maya 2022 with MayaUSD 0.18.0 and USD 0.20.11

**Comment by santosg87** [comment]
Thank you for logging this,

I am also able to reproduce it on our side, and have it logged internally as MAYA-125028
