### ISSUE TITLE
Linux (Ubuntu): Scroll bar is missing in "Merge Maya Edtis to USD Options" dialog

### ISSUE THREAD

**Issue by hamedsabri** [Autodesk/maya-usd#2586]
Tiny bug for @seando-adsk :) 

**Describe the bug**
The scroll bar is missing in "Merge Maya Edits to USD Options" dialog on Linux. 

**Steps to reproduce**
Steps to reproduce the behaviour:
1. Go to Merge Maya Edits to USD Options
2. Notice that Scroll bar is missing

**Specs (if applicable):**
 - OS & version:  **Ubuntu 18.04.6 LTS**
 - Maya version:  **Maya 2023.1**
 - Maya USD version:  **0.18.0**

**Additional context**

Linux:

![image](https://user-images.githubusercontent.com/13695234/189110457-d82c0d67-d67c-4ea4-be6d-c071bd3cfaea.png)

Windows:

![image](https://user-images.githubusercontent.com/13695234/189110581-ac4409fb-dbcd-46d2-a329-bd8aaa7d66c0.png)

**Comment by santosg87** [comment]
Hi @hamedsabri! 

thanks for logging this issue!
we have an internal ticket logged for that issue, and it should be fixed with 0.19.0  - would you be able to test and confirm?

**Comment by hamedsabri** [comment]
Hi George,

Tried this out with 0.19.0 and it works as expected. 

Cheers
