### ISSUE TITLE
[MAYA-122480] Selection Highlighting Broken with Instanced BasisCurves

### ISSUE THREAD

**Issue by cfmoore007** [Autodesk/maya-usd#259]
**Describe the bug**
In the latest maya beta with PR#228, when selecting BasisCurves that instanced, selection highlight is broken in shaded mode.  Either you see no selection highlighted, or > 1 instanced prim

**Steps to reproduce**
1. load maya beta
2. import the attached basisCurves.usdc
3. select, any of the instanced prims - instanced_1,2 or 3 in shaded mode
4. notice no selection highlight
5. now switch to wireframe mode, witness selection highlight ( correct )

**Expected behavior**
We expect selection highlighting to work

**Attachments**
USD File
[basisCurves.zip](https://github.com/Autodesk/maya-usd/files/4168352/basisCurves.zip)

Shaded Mode Results ( incorrect )
![basisCurve_instanced_selection_shaded](https://user-images.githubusercontent.com/2152250/73989540-1cd33a00-4914-11ea-9886-3dceb5188e49.png)

Wire Frame Mode Results ( correct )
![basisCurve_instanced_selection_wireframe](https://user-images.githubusercontent.com/2152250/73989541-1d6bd080-4914-11ea-8e1d-5a656a107b0f.png)

**Specs (if applicable):**
 - OS & version [Windows 10]
 - Compiler & version [VS2017]
 - Maya version [Maya Beta and 2020.0 tested]
 - Maya USD commit SHA [dev at a29704f with PR#228 merged in]
 - Pixar USD commit SHA [master v20.02 compiled against rman23]

**Additional context**

**Comment by HdC-adsk** [comment]
I tried to avoid a dedicated selection highlight item for basisCurves, but from this issue we still need it. When being selected, the dedicated selection highlight item will be drawn closer to the camera so it can cover the shaded drawing.

**Comment by santosg87** [comment]
closing this issue for the time being, as this is not in our current roadmap.
