### ISSUE TITLE
USD Preview Surface renders darker than expected

### ISSUE THREAD

**Issue by dgovil** [Autodesk/maya-usd#2591]
There's a shading discrepancy with luminance that we notice in Maya when using USD Preview Surface instead of Lambert or Phong, where the shaders are quite dark in the viewport by about 𝝅 

In the attached screenshot , we have four planes with the same diffuse values on (left to right):
usdPreviewSurface standardSurface phong lambert

<img width="529" alt="Screen Shot 2022-09-07 at 5 59 14 PM" src="https://user-images.githubusercontent.com/4443090/189450587-c8fe511a-531b-414e-9665-028e4b09df9f.png">

I realize that some of these are PBR and others aren't but the luminance difference seems quite stark. Is this intentional or something we can work around somehow? it is quite a bit darker than the results appear when exported out of Maya and viewed in other renderers like QuickLook , though those renderers also have lighting that help compensate.

Is the luminance correct or should the shader be brightened up to be more accurate?

**Specs **
 - OS & version macOS 13
 - Maya 2020
 - Maya USD 0.19

[maya_viewport_lighting_response_shadertype.ma.zip](https://github.com/Autodesk/maya-usd/files/9538931/maya_viewport_lighting_response_shadertype.ma.zip)

**Comment by JGamache-autodesk** [comment]
Hi @dgovil, the reflected intensity difference is known and makes it almost impossible to mix legacy surfaces like Phong and Lambert with modern PBR surfaces like Standard Surface, glTf, or USD preview surface. If we light so Lambert looks nice, then the PBR will be too dark, and if we light the PBR surfaces correctly, the legacy ones will end up too bright. It is best to decide between legacy and PBR as early as possible and choose only the appropriate surface shaders and light environments.

This is also quite visible when exporting Lambert/Phong/Blinn to MaterialX. The [NodeGraphs](https://github.com/Autodesk/maya-usd/blob/dev/lib/mayaUsd/render/MaterialXGenOgsXml/libraries/maya_surfaces.mtlx#L82) introduced in MayaUSD to represent these surfaces use basic PBR primitives, so they will also be dimmer when shown as USD stage with MaterialX shading.

**Comment by dgovil** [comment]
Thanks for confirming that it's expected and there aren't any mitigations towards it! 
 That makes sense that the lighting would be so stark if they're feeding off the same lighting system without mitigations.

I'll close this out
