### ISSUE TITLE
USD for Maya plugin not able to load

### ISSUE THREAD

**Issue by vanlicht** [Autodesk/maya-usd#26]
### I build the plugin using the build_usd.py, installed/ tried on both Maya 2018 and 2019
Windows10 64bit
Python 2.7

### The command I used to install:
C:\Users\xxx\Desktop\maya-usd-19.07\build_scripts>build_usd.py --force-all --no-doc --python --maya --maya-location "C:\Program Files\Autodesk\Maya2018" "C:\Users\xxx\Git\USDAD"

### In the plugin manager it the options showed up, but whenever I tried to load, Maya gives the following messages:
// Error: file: C:/Program Files/Autodesk/Maya2018/scripts/others/pluginWin.mel line 290: Unable to dynamically load : C:/Users/xxx/Git/USDAD/third_party/maya/plugin/pxrUsd.mll
The specified module could not be found.
 // 
// Error: file: C:/Program Files/Autodesk/Maya2018/scripts/others/pluginWin.mel line 290: The specified module could not be found.
 (pxrUsd) // 
// Error: file: C:/Program Files/Autodesk/Maya2018/scripts/others/pluginWin.mel line 290: Unable to dynamically load : C:/Users/xxx/Git/USDAD/third_party/maya/plugin/pxrUsdPreviewSurface.mll
The specified module could not be found.
 // 
// Error: file: C:/Program Files/Autodesk/Maya2018/scripts/others/pluginWin.mel line 290: The specified module could not be found.
 (pxrUsdPreviewSurface) // 
// Error: file: C:/Program Files/Autodesk/Maya2018/scripts/others/pluginWin.mel line 290: Unable to dynamically load : C:/Users/xxx/Git/USDAD/third_party/maya/plugin/pxrUsdTranslators.mll
The specified module could not be found.
 // 
// Error: file: C:/Program Files/Autodesk/Maya2018/scripts/others/pluginWin.mel line 290: The specified module could not be found.
 (pxrUsdTranslators) // 

### Thomas

**Comment by dtlindsey** [comment]
@vanlicht  the Pixar USD plugin only works in 2016.  It's in their docs.
The maya-usd repo works with USD 19.05 for now.
in your USD repo do
git checkout tags/v19.05
and build that to start

**Comment by vanlicht** [comment]
@dtlindsey, thanks for the response!
I am happy to report that I successfully installed the USD and able to activate the Maya plug-ins on Maya 2018! 
I didn't specify the tag using v19.05, so I assume I installed with v19.07.

**Comment by kxl-adsk** [comment]
@vanlicht Can this issue be closed?
