### ISSUE TITLE
Transform Manips missing on Windows

### ISSUE THREAD

**Issue by hamedsabri** [Autodesk/maya-usd#2608]
**Describe the bug**

Transformation Manip is missing on Windows when opening attached **butterfly.usd**. 

**Steps to reproduce**
1. Create stage from file
2. Select  butterfly usd. 
3. Select myosotis mesh
4. Select Move tool ( W )
5. Notice Tranform manip is missing

**Windows**
![Windows_missing_manip](https://user-images.githubusercontent.com/13695234/190913419-3c0e035e-6af3-437d-b804-371da31e3480.png)

**Linux**
![Linux_manip](https://user-images.githubusercontent.com/13695234/190913418-a5c099f5-4fd2-4d17-a717-2d0059046e50.png)

**Expected behavior**
 Tranform manip should be displayed.

**Attachments**
Get the USD files in the description of Bifrost USD demo video: 
https://www.youtube.com/watch?v=5hSx6PfXfg8&t=536s

**Specs (if applicable):**
 - OS & version [e.g. Windows 10]
 - Maya version [e.g. Maya PR 135]
 - Maya USD commit SHA [e.g. 0.19.0]

**Comment by santosd** [comment]
Hi @hamedsabri , I tested in the latest PR138 that just went out last week and I am seeing the transform on the Windows side. Could you test in that version and see if you are still not seeing the transform handles?

**Comment by hamedsabri** [comment]
Hi David, switching to PR138 fixes the issue for me. Closing this ticket.

Cheers
