### ISSUE TITLE
Option to disable MaterialX

### ISSUE THREAD

**Issue by daviddeacon** [Autodesk/maya-usd#2637]
I need to use MaterialX shaders for rendering in solaris, but as soon as I include them in a USD file, the geometry doesn't render in the Maya viewport. Basically making it impossible to work with assets with MaterialX shaders on in Maya.

I would like an option to fall back to the USD surface preview shader in a material if it exists in a USD file, rather than prioritising the materialX shader. This could be an ENV var set before launching Maya or an option on the mayaUsdProxyShape.

This could also be useful when materialX shaders are overly complex for the viewport and a simple diffuse would work.

Hopefully this isn't particularly difficult to implement as it's really blocking our Usd maya adoption.

**Comment by santosd** [comment]
Hi David, wondering if you could provide a sample file that has materialX that is not rendering in the Maya viewport. Are the MaterialX files being created in Solaris or in Maya? When I have tried it in the past from Maya, MaterialX would come in as a stage and render in the Maya viewport without issues. This could be a Mac related issue so I will see about testing on that OS on my end.

**Comment by daviddeacon** [comment]
Hi,

Sure, here is a simple materialX setup, created in solaris.  I'm testing on an 2019 MacPro and M1 Max MacBook Pro, with Maya 2023.2, MayaUsd 0.19.0.

[https://www.dropbox.com/sh/fm7xykjvn8gidue/AADLjy8k30UyD1FDVo8qaFH9a?dl=0](url)

Our plan is to do all our look dev shader setup in solaris. 

I still stand by my request to allow an option to prioritise UsdPreviewSurface shaders over materialX for viewport performance. As production materialX shaders can be quite complex and contain multiple texture channels often with many UDIM tiles. When working on shots, that contain many assets loading all that data is a massive over head when 99% of the time all we would like to load is a diffuse texture or even just a single colour.

Just to prioritise UsdPreviewSurface shaders over materialX would be the perfect fix for us, as it's easy to author a simple UsdPreviewSurface along side the materialX shader. This could be a 'Use simplified shaders' toggle on the UsdProxyShape.

Cheers,
David.

**Comment by IgorDmytrenko** [comment]
> Hi David, wondering if you could provide a sample file that has materialX that is not rendering in the Maya viewport. Are the MaterialX files being created in Solaris or in Maya? When I have tried it in the past from Maya, MaterialX would come in as a stage and render in the Maya viewport without issues. This could be a Mac related issue so I will see about testing on that OS on my end.

Hello David, i've tested on my end the usd files what David D. provide above with maya 2023.2 on a Windows and getting the same issue what D.D describe. I hope it will get fix relative soon.

The same errors and performance inssues:
```
// Error: Failed verification: ' nodeDef ' -- Could not find MaterialX NodeDef for Node 'NG_Maya/N4'. Please recheck library paths.
// Error: Caught exception 'Could not find a nodedef for node 'N4'' while processing '/Proxy_chess_materialXShape_0000019D3D932290/materials/KING_MTLX'
```

![usd](https://user-images.githubusercontent.com/47521478/194760136-edbef28b-cf43-46a8-88ad-459aa6ed46d4.png)

**Comment by santosd** [comment]
Hi @IgorDmytrenko, I tested this on my end using Maya USD 0.19.0 and Maya 2023.2 and it is working as expected on my end without errors. Are you using 0.19.0?
![image](https://user-images.githubusercontent.com/29235905/195203951-98bdf1a8-5f61-405d-8114-3d69839b490c.png)

**Comment by IgorDmytrenko** [comment]
Hi @santosd , Yeah i'm using the same version of USD 0.19.0 and Maya 2023.2. As you can see it isn't working for me, not sure why we have different results from each other. If you have idea let me know, I can test it for you.
![image](https://user-images.githubusercontent.com/47521478/195204736-d70697f6-17f6-4b42-9c01-2ada398245d5.png)

**Comment by daviddeacon** [comment]
@santosd I noticed you had closed the issue, for me this was a feature request about having an option to prioritise the UsdPreviewSurface over materialX shaders for simplified shading in the viewport. 

The example files may have confused the real request. 

A simplified shading option is really important to us, as we want to use matX for rendering but don’t want or need them to be visible in Maya’s viewport. 

Thanks,
David

**Comment by IgorDmytrenko** [comment]
@santosd Seems to be I know why it's working for you. You was imported model trought context menu file > import usd. But it's not proper usd workflow and destructive, insted of that you have to use **USD stage manager** and you'll see so it's has problem.

**Comment by santosd** [comment]
My apologies @daviddeacon, I definitely didn't mean to close the issue. I accidentally hit the close with comment button instead of the Comment button.

@IgorDmytrenko, I created a stage from the file using the Create > Universal Scene Description option I did not import the file. This could be related to OS are you on Mac like @daviddeacon is? There are some known issues that we are working on in regards to Mac M1 machines.

**Comment by santosd** [comment]
I will put this in our backlog for the request to have an option to prioritize the UsdPreviewSurface over materialX shaders for simplified shading in the viewport.

**Comment by IgorDmytrenko** [comment]
@santosd i'm not sure if it depend from OS, my system has Windows 11 Pro 21H2 ( 22000.978)

**Comment by Lucas3Dspain** [comment]
Hi @santosd !
Shouldn't you be able to use display proposes to handle what material is used at what time? 
so that the materialX Shader is for final render and the usdPreviewSurface for viewport only.

If not maybe you could try to compose assets with this:
token outputs:surface.connect </pathTo/usdPreviewSurface>
token outputs:arnold:surface.connect </pathTo/mtxStandardSurface>

like [here](https://github.com/Autodesk/maya-usd/discussions/2272):

**Comment by daviddeacon** [comment]
Hi Lucas,
> Hi @daviddeacon ! Shouldn't you be able to use display proposes to handle what material is used at what time? so that the materialX Shader is for final render and the usdPreviewSurface for viewport only.

Initially I thought the same thing, but prim purpose only works on prims and don't affect material assignment. The only option would be to duplicate all of our geometry and assign a viewport material on the proxy and the render material on the render prim. This is impractical and adds a lot of extra complexity in asset setup and shading, and it is possible to move the proxy model in the viewport and leave the render model in place without the artist knowing.

> 
> If not maybe you could try to compose assets with this: token outputs:surface.connect </pathTo/usdPreviewSurface> token outputs:arnold:surface.connect </pathTo/mtxStandardSurface>
> 
> like [here](https://github.com/Autodesk/maya-usd/discussions/2272):

This is how I have the asset currently setup, as MayaUSD sees the mtlx shader as a valid shader for it's viewport delegate so priorities the mtlx material and ignores the UsdPreviewSurface unfortunately. I've also tried manually reordering the shader outputs but it makes no difference to which is selected.

I just need to be able to make MayaUsd ignore the mtlx shaders, It's so frustrating as I didn't have any of these issues before mtlx was added to MayaUsd.

**Comment by Lucas3Dspain** [comment]
Oh I see, yeah its probably good to have that control in a env bar or something.

**Comment by daviddeacon** [comment]
An environment variable would totally work for us, and require no extra UI developer time on the plugin team.

**Comment by paulbaa** [comment]
Ho poking this - would love to see an equivalent of sidefx `HOUDINI_GL_USE_MATERIALX `.

**Comment by daviddeacon** [comment]
> Ho poking this - would love to see an equivalent of sidefx `HOUDINI_GL_USE_MATERIALX `.

🤞

**Comment by daviddeacon** [comment]
Amazing, thank you for adding this.

**Comment by sharktacos** [comment]
Trying to get the MAYAUSD_VP2_USE_ONLY_PREVIEWSURFACE working. Could someone go over the steps? Can this be set in Maya.env or in the Maya script editor? 

Workflow: stage with geo sublayer containing geo assigned USDPreviewSurface, sublayer above this with for lookdev with MaterialX shader assigned. 
Expecting to have it render MaterialX and display the PreviewSurface in the VP2 with the env var set. It is not. I'm seeing the materialX shader both in the viewport and render.

**Comment by seando-adsk** [comment]
@JGamache-autodesk could you help with this question?

**Comment by JGamache-autodesk** [comment]
I have checked and it works fine when used in [Maya.env](https://help.autodesk.com/view/MAYAUL/2023/ENU/?guid=GUID-8EFB1AC1-ED7D-4099-9EEE-624097872C04). The value is read once when USD stage is first drawn in the viewport, You can not change it afterwards using `putenv` in the script editor.
