### ISSUE TITLE
Fatal Error using MayaReference and multi-proxy AL workflow

### ISSUE THREAD

**Issue by yantor3d** [Autodesk/maya-usd#2639]
**Describe the bug**
Loading a MayaReference prim crashes Maya when multiple copies of the same file are loaded via the AL proxy.

**Steps to reproduce**
1. Use  `AL_usdmaya_ProxyShapeImport -f` to load two or more copies of the same file (attached).
2. Switch the `payload` variant set to `maya` to load the MayaReference prim
3. Fatal Error

**Expected behavior**
Loading a MayaReference prim should not crash Maya when multiple copies of the same file are loaded via the AL proxy.

**Attachments**
[asset.zip](https://github.com/Autodesk/maya-usd/files/9708761/asset.zip)
[crash.log](https://github.com/Autodesk/maya-usd/files/9708762/crash.log)

**Specs (if applicable):**
 - CentOS 7
 - Maya 2020.4, Maya USD 0.19.0, USD 0.20.11
 - Maya 2022.3, Maya USD 0.19.0, USD 0.21.2
 - Maya 2023, Maya USD 0.19.0, USD 0.21.2

**Comment by santosd** [comment]
Hi @yantor3d, I gave this a try using the Maya USD plugin and am not getting the crash. Unfortunately, we are not developing the AL plugin so wouldn't be able to provide a fix.

**Comment by yantor3d** [comment]
Hi @santosd - thank you for looking into this. It's ... concerning that the repro doesn't work on your end. 

Can you elaborate on what you mean by "we're not developing the AL plugin"? The source code to build it is part of this repo - is it no longer supported?

**Comment by fabal** [comment]
Hi @yantor3d , we (Animal Logic) will look into this issue and get back to you.

**Comment by santosd** [comment]
Hi @yantor3d, what I meant was that (Autodesk) specifically is not working on the AL USD Plugin, we are focusing on the Maya USD plugin and working on that. As @fabal said though Animal Logic will take a look on their end, thank you.

**Comment by NickWu** [comment]
Hey @yantor3d,  we (Animal Logic) have confirmed that we can reproduce the crashes with Maya USD 0.19. However, we also found Maya USD 0.18 doesn't produce the crashes with the same steps. We are continuing the investigation and will keep you posted.

**Comment by NickWu** [comment]
Thanks @yantor3d . Glad to know you have made it working for you. We are currently discussing some different solutions internally.   I'll report back at some point.

**Comment by fabal** [comment]
Hi @yantor3d , technically the crash happens here https://github.com/Autodesk/maya-usd/blob/07103a39247b0108b73730f41ad7742a1d20d75f/lib/mayaUsd/fileio/translators/translatorMayaReference.cpp#L180
Although we could modify this code, we think it would give you a false sense of a supported scenario, i.e., multiple proxyShapes sharing the same stage (keep in mind that I am talking about AL's proxyShapes here). That scenario is something which AL never uses, and thus, not much thinking was never put into it. Unfortunately, you can see it by yourself with that crash.
As we are in the process of transitioning toward the Autodesk plugin (we will communicate publicly about it later during the year), it is going to be difficult to find the resources needed to properly support the use case of 1 stage / multiple (AL) proxyShapes.
I understand I'm not helping you out much here but, at least, you can get a better understanding of the state of play.

**Comment by yantor3d** [comment]
Thanks for the info @fabal. I get the feeling that I am the only TD in the industry who tried to do a multi-proxy workflow.

We, too, are planning to transition to the mayaUSDProxy. Since my crude patch was able to fix this for us, and the prevailing winds have always been to single proxy, let's close this issue.
