### ISSUE TITLE
Freeze on exit in Maya 2020 but not Maya 2022

### ISSUE THREAD

**Issue by nicolaspopravka** [Autodesk/maya-usd#2642]
**Describe the bug**
On Windows 10, and using our own builds of Maya USD v0,13 for 2020 + Pixar USD v21.08, to match what ships with Maya 2022, we are experiencing the issue described below where Maya 2020 freezes on exit. We are not experiencing this problem using Maya USD that ships with 2022.

**Steps to reproduce**

1. Click Create->USD->Stage from File and select some test asset, for example a local copy of the [USD Cookie](https://github.com/usd-wg/assets/blob/main/full_assets/cookie/usd_cookie.usdz) and click Create.
2. Click File->Exit, then click Don't Save
3. Maya becomes unresponsive

**Expected behavior**
Maya to exit ;-)

**Attachments**
Here's a screenshot of Visual Studio where the debugger reports an exception thrown while exiting, inside `HdVP2ShaderDeleter::operator()()`:
![image](https://user-images.githubusercontent.com/70967643/194435991-4beb84b5-78fd-4144-9262-5eeb3c974197.png)
 
**Specs (if applicable):**
 - Windows 10
 - Visual Studio 2017
 - Maya 2020
 - Maya USD v0,13
 - Pixar USD v21.08

**Additional context**
`MAYAUSD_VP2_USE_V1_LIGHT` needs to be set otherwise assets are rendered in a flat white color in the viewport.

It's such basic workflow that we suspect something wrong on our side. But what ? It's hard to tell. Maybe other folks could try to reproduce this in their environments and report back their own experience ?  Our plan is to move to 2022 of course. In the meantime, any workaround or debugging tip would be much appreciated.

Thanks!

**Comment by santosg87** [comment]
@nicolaspopravka would you be able to test this on our latest build of MayaUSD? we had a fix for an issue that might have solved this as well.

thank you!

**Comment by nicolaspopravka** [comment]
You're correct. It's not an issue in Maya 2020 using builds at current HEAD of Maya USD against current HEAD of USD. 

Would it have been fixed by https://github.com/Autodesk/maya-usd/pull/2529 ?

**Comment by santosg87** [comment]
Closing this one based on the conversation above. :)
