### ISSUE TITLE
[MAYA-121197] File->Save As overwrites the USD file

### ISSUE THREAD

**Issue by gracekumagai** [Autodesk/maya-usd#2653]
**Describe the bug**
When using File->Save As with the first save option checked ("Save the Maya scene file and USD files"), it prompts the user to save a new Maya file. However, it overwrites the current USD file and does not provide the option to "Save As"

We found this behaviour unexpected and in our single layer case, we would like a way of being able to save a copy of the Maya file and USD file. Atm, we would need to navigate to the directory of the USD file & make a copy, then in Maya, we'd need to create a new  file with a new stage with this new copied file.

**Expected behavior**
We would like to have a workflow to save a copy of the Maya file and USD file.

**Specs (if applicable):**
- Linux
- maya2023.2
- Maya USD commit SHA [dev at 302f393]
- Pixar USD commit SHA [dev at 60ed06c]

Pixar Internal JIRA MAYA-3502

**Comment by tanant** [comment]
Replicated here just now (I was literally in maya testing something else when I saw this pop up) - an initial spitball question, the single layer case is relatively straightforward, you could have a dialog up that does the copy+save to a new USD file. Would you expect something similar for multi-layer workflows or is that more likely to be a "force user to manually resolve"? (the main thing i'm spinning in my head is the repathing of references)

**Comment by gracekumagai** [comment]
On our side, I think what you suggested would work well - for ex, a similar dialog to the Maya file "Save As". 

We are focusing on the single layer workflow so we don't want to misdirect multi-layer workflows. Although, for context, our artists want to spin-off a copy of their maya set file to try something out and ultimately, if they liked the changes in the spin-off copy, they would save it over the original.

**Comment by santosg87** [comment]
some housekeeping: we have this issue logged internally as MAYA-121197

**Comment by santosg87** [comment]
@gracekumagai a quick question on the workflow here - as  i managed to reproduce it, but also found a relatively simple workaround (although still not preferable. :) )

when your artists are saving the maya scene, do they have an empty layer? I found that adding anything to the only layer  fixes the behavior and forces the expected pop-up window,

with that said, there is a different issue we found recently, where the root layer gets saved, but not used, so you would need to point to the saved file again afterwards. we are investigating solutions. :)

**Comment by gracekumagai** [comment]
Hey @santosg87 - apologies for the delay in getting back to you!

We have a pretty simple layer stack for sets where we'd only be managing 1 layer which represents the set (+ session layer). Thank you for the workaround! We do not currently have artists working in this environment yet but will pass it along if needed.

Thanks!

**Comment by wallworm** [comment]
@gracekumagai Would it be good enough to have a new save as option that will copy just the root layer into an anonymous layer and save that into the new Maya file? This would allow the user to then make decide, after the fact, then save the layers from the new Maya scene (or not) depending on whether or not they like their new changes.

**Comment by gracekumagai** [comment]
Hi @wallworm ! Thanks for the follow up and apologies for the delay. The workflow you mentioned, is that available to test in Maya 2023?

**Comment by wallworm** [comment]
@gracekumagai No, it's not available yet. I was asking you if that would be a viable solution that serves your purpose? It seems that would be a way to solve your scenario and avoid the more complex question of stages that have an arbitrarily deep nested array of sublayers and references and what to do in that case. I didn't want to send the devs down this road unless you thought it could work for you.

**Comment by dj-mcg** [comment]
Hey @wallworm - I'm fairly certain in normal production workflows, our users would typically save the usd file separately. I understand the concern regarding sublayers and references. I think we are in somewhat of a unique situation in that most of our users will only have a single USD stage - typically with only a single authoring layer - per maya file, and our users would anticipate any external references to the usd stage not to update if they were to save it under a different name, so in our case I think we'd be safe blindly saving an existing stage under a different name as if it hadn't been saved before. However, I understand we can't assume that is at all typical workflow. So, I'm not sure whether it makes sense to check for this scenario.
