### ISSUE TITLE
ArResolver Context external Context File

### ISSUE THREAD

**Issue by jonassorgenfrei** [Autodesk/maya-usd#2656]
**Is your feature request related to a problem? Please describe.**
We are trying to get the asset resolution in the Maya USD Plugin working in a similar behaviour as the houdini implementation is. 
The USD implementation in Houdini supports that the context can be controlled by a different file.
(see: https://www.sidefx.com/forum/topic/86251/)

In Houdini the context can then be controlled via the resolvercontext parameter on the stage node.
So it's possible to pass a file to the Stage Open with which we can control the behaviour of the asset resolver.

Currently the implementation tries to create the Context from the file itself. 
https://github.com/Autodesk/maya-usd/blob/c610a03ff7b333b4c04fac4333076896023289f2/lib/mayaUsd/nodes/proxyShapeBase.cpp#L848-L860
But we can not pass or load a differnt context file

**Describe the solution you'd like**
Is there already a mechanism in place or possible to add this feature to have a control 

**Workaround**
The workaround currently would be to use environment variables and pass that infromation to our custom ArResovler CreateDefaultContextForAsset method to find the context (asset-pinning) file.

**Additional context**

Note: this might be a duplicate to the issue:
#2655  by @ColinKennedy

**Comment by jonassorgenfrei** [comment]
Hey @ColinKennedy thanks for your answer and the explanation. 
Yeah an even more direct control would be even better. Yep thats right, we try to at least have a kind of similiar behaviour/control as we have in Houdini. Oh i didnt see that the Houdini Forum's post was written by you too, very cool, it helped me understand the behaviour in Houdini a little better!

Oh yeah thats right, we do have a custom asset resolver which follows the logic of the rodeo resolver. So we load a usd file and extract the CustomLayerData from an SDF Layer to create Replace pairs. 
Yeah that sounds definitely really cool to avoid the need to haave a custom resolver.

It looks like the Maya implementation currently only supports AR1.0 and is not yet updated to AR2.0 so the functions CreateContextFromString(s) don't exist yet and would probably have to be added manually or the implementation needs to be switch to AR2.

Thanks for the offer, i will write you a mail in a sec. Happy to hear that and thank you so much for the offer. 

Yeah as the requests are quit similar, we can close this ticket and i will add the request for the CreateDefaultContextForAsset control your ticket (2655).

**Comment by tanant** [comment]
@jonassorgenfrei doing some admin, as you mentioned I'll close this in favour of #2655 and we can there to keep the convo in the one place
