### ISSUE TITLE
Viewport 2.0 Render Delegate produces considerably darker images when color management is disabled

### ISSUE THREAD

**Issue by dj-mcg** [Autodesk/maya-usd#266]
**Describe the bug**
When color management is enabled, the Viewport 2.0 Render Delegate produces images similar to those produced by the Pixar batch renderer. When color management is disabled, the results are considerably darker.

**Steps to reproduce**
1. Run testProxyShapeDrawColors with color management enabled. 
2. Observe result
3. Run testProxyShapeDrawColors with color management disabled
4. Compare result with previous

**Expected behavior**
The images more closely match with regards to brightness

**Comment by santosd** [comment]
This is something that can be seen in the viewport:

1. Bring in a usd file into Maya (Create > USD)
2. Create a polygon primitive.
3. Already there should be a noticeable difference in the shading between the polygon object and the usd proxy.
4. ![image](https://user-images.githubusercontent.com/29235905/76999982-f4d0f080-692d-11ea-999d-16da7851d8a4.png)
5. Turn off color management and things get even darker the proxy looks almost black.
6. ![image](https://user-images.githubusercontent.com/29235905/77000010-00bcb280-692e-11ea-99cb-ee0f82afac1d.png)
7. Switch to Hydra renderer (Renderer > Hydra) notice that the polygon primitive is now the darker of the two objects.

**Comment by santosd** [comment]
I retested this issue and I am no longer seeing it. The following are screen captures, the sphere on the left is a USD proxy and the one on the right is Maya data. Turning color management on or off doesn't make a difference in shading between the two spheres:

![image](https://user-images.githubusercontent.com/29235905/137781422-480b12e6-bb37-4bd6-a686-deffb9736322.png)
![image](https://user-images.githubusercontent.com/29235905/137781445-2dab7cb8-2d56-4593-9546-0422e15c9034.png)

I am going to close this out for now, but feel free to test and let us know if you are still seeing the issue on your end.
