### ISSUE TITLE
AE : Transform Attributes in Several Sections

### ISSUE THREAD

**Issue by cfmoore007** [Autodesk/maya-usd#268]
**Describe the bug**
In the latest Maya Beta it seems that the Transform Attributes split between here in xformOpOrder and the actual xformOp down in the Extra Attributes section ?

**Steps to reproduce**
1. open latest maya beta
2. load usd through proxyShape
3. select prim
4. see attributes scattered in AE

**Expected behavior**
It seems more intuitive if they're grouped together ( same if pivots or other xformOps would be present )

**Attachments**
![XformAttrsScattered_AE](https://user-images.githubusercontent.com/2152250/74169309-1a652e80-4bf9-11ea-8f94-02a491037408.png)

**Specs (if applicable):**
- OS & version [Windows 10]
- Compiler & version [VS2017]
- Maya version [Maya Beta and 2020.0 tested]
- Maya USD commit SHA [dev at a29704f with PR#228 merged in]
- Pixar USD commit SHA [master v20.02 compiled against rman23]

**Additional context**

**Comment by wtelford** [comment]
The current python AE templating requires each attribute to be categorized explicitly. 
The fact that this attribute has been labled with ":anim" prevents it from matching the current categorization rules.
We likely need to expand the python templating to match against wildcard or regex expressions to prevent split categorizations like this.

**Comment by cfmoore007** [comment]
Thanks for the info, Will.

opSuffix's seem to be common practice, at least from consuming USD assets created from Houdini LOPS.  By default that software adds unique opSuffixes per override.

We try to limit the # of opSuffixes in use, but it is engrained into our new pipeline.

**Comment by wtelford** [comment]
Yes we absolutely should embrace the suffixes, it’s just the current implementation is limited to explicit name matching. We’ll need to make that more flexible so all transform attributes get categorized.

**Comment by kxl-adsk** [comment]
The fix will require changes in https://github.com/Autodesk/maya-usd/blob/dev/lib/ae/base/ae_template.py

**Comment by mdelasa** [comment]
This has been logged internally as MAYA-104008

**Comment by seando-adsk** [comment]
This will be fixed in the next Maya beta.

**Comment by pilarmolinalopez** [comment]
I can confirm this is fixed now. Thanks!
