### ISSUE TITLE
[MAYA-126068] MayaUSD export `preserveUVSetNames` export flag is not order-preserving for the st maps

### ISSUE THREAD

**Issue by tanant** [Autodesk/maya-usd#2696]
**Describe the bug**
When using this export flag (preserveUVSetNames) the order of the uvSets is not retained, it's set to be alphasorted.

**Steps to reproduce**
attached is a cube with four uvSets - in the original .ma they are ordered
- durian1 (as it is the 👑 of fruits)
- cherry2
- blackberry3
- apple4
```
# exporting the same setup, using these two commands that differ by just the one flag
cmds.mayaUSDExport(file=r"e:/preserve.usda", exportUVs=True, preserveUVSetNames=True)
cmds.mayaUSDExport(file=r"e:/no_preserve.usda", exportUVs=True, preserveUVSetNames=False)
```
Inspect the USDA, or reimport the two usd-exported cubes. 
- `preserve` will have them sorted apple > blackberry > cherry > durian
- `no_preserve` will retain the original durian > cherry > blackberry > apple user order.

**Expected behaviour**
I expect that the flag should not permute the order, it should only change the variable naming within the file (and people chuckle at my dumb fruit humour)

**Attachments**
[uvSet_order_permute_demo.zip](https://github.com/Autodesk/maya-usd/files/9921666/uvSet_order_permute_demo.zip)

**Comment by santosd** [comment]
Edited the title and added the ticket number and also edited the title of the internal ticket for tracking purposes.

**Comment by tanant** [comment]
Marking as wontfix, as this looks like it's a performance-based USD-underlying implementation characteristic - from the 22.11 release https://github.com/PixarAnimationStudios/USD/blob/v22.11/pxr/usd/usd/prim.h#L319 - it looks like the properties are default returned by `TfDictionaryLessThan` order, (which is string comp based, and alphabetical) or a custom `PropertyOrder` (and those are hoped to be relatively rare)
