### ISSUE TITLE
pthreads.h not found on Windows

### ISSUE THREAD

**Issue by dtlindsey** [Autodesk/maya-usd#27]
New error when building the current master on Windows 10, CMakeError.log shows pthreads.h not being found, and not sure why it's looking for that on windows.

See also "C:/Users/lindd067/dev/external/install/maya-2018-usd-19.05/build/Release/CMakeFiles/CMakeOutput.log".
See also "C:/Users/lindd067/dev/external/install/maya-2018-usd-19.05/build/Release/CMakeFiles/CMakeError.log".

Traceback (most recent call last):
  File "build.py", line 482, in <module>
    InstallMayaUSD(context, context.buildArgs, context.stagesArgs)
  File "build.py", line 319, in InstallMayaUSD
    RunCMake(context, extraArgs, stagesArgs)
  File "build.py", line 283, in RunCMake
    extraArgs=(" ".join(extraArgs) if extraArgs else "")))
  File "build.py", line 189, in Run
    .format(cmd=cmd, log=os.path.abspath(context.logFileLocation)))
RuntimeError: Failed to run 'cmake -DCMAKE_INSTALL_PREFIX="C:\Users\lindd067\dev\external\install\maya-2018-usd-19.05\install\Release" -DCMAKE_BUILD_TYPE=Release -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -G "Visual Studio 14 2015 Win64" -DMAYA_LOCATION="C:\Program Files\Autodesk\Maya2018" -DPXR_USD_LOCATION="C:\Users\lindd067\dev\external\install\USD" "C:\Users\lindd067\dev\external\git\maya-usd"'
See C:\Users\lindd067\dev\external\install\maya-2018-usd-19.05\build\Release\build_log.txt for more details.

**********************************CMakeError.log:**********************************
Determining if the include file pthread.h exists failed with the following output:
Change Dir: C:/Users/lindd067/dev/external/install/maya-2018-usd-19.05/build/Release/CMakeFiles/CMakeTmp

Run Build Command(s):C:/Program Files (x86)/MSBuild/14.0/bin/MSBuild.exe cmTC_3482c.vcxproj /p:Configuration=Debug /p:Platform=x64 /p:VisualStudioVersion=14.0 /v:m && Microsoft (R) Build Engine version 14.0.25420.1

Copyright (C) Microsoft Corporation. All rights reserved.

  Microsoft (R) C/C++ Optimizing Compiler Version 19.00.24234.1 for x64

  Copyright (C) Microsoft Corporation.  All rights reserved.

  

  cl /c /Zi /W3 /WX- /Od /Ob0 /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\"Debug\"" /D _MBCS /Gm- /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"cmTC_3482c.dir\Debug\\" /Fd"cmTC_3482c.dir\Debug\vc140.pdb" /Gd /TC /errorReport:queue "C:\Users\lindd067\dev\external\install\maya-2018-usd-19.05\build\Release\CMakeFiles\CMakeTmp\CheckIncludeFile.c"

  

  CheckIncludeFile.c

C:\Users\lindd067\dev\external\install\maya-2018-usd-19.05\build\Release\CMakeFiles\CMakeTmp\CheckIncludeFile.c(1): fatal error C1083: Cannot open include file: 'pthread.h': No such file or directory [C:\Users\lindd067\dev\external\install\maya-2018-usd-19.05\build\Release\CMakeFiles\CMakeTmp\cmTC_3482c.vcxproj]

**Comment by HamedSabri-adsk** [comment]
@dtlindsey  I see that you are using VS 2015. Can you reproduce this issue with Vs2017 as well? 
Can you please share your build_log.txt?

**Comment by dtlindsey** [comment]
@HamedSabri-adsk  I attempted using visual studio 2017, with the --generator "Visual Studio 14 2015 Win64" arg, and it built without issue.  I'll close this issue.

**Comment by AlexGaida** [comment]
Hi, I've encountered the very same issue this thread is experiencing, the pthread.h error, I'm now using a Visual Studo 15 generator and now it's throwing a CMake GTest error:

CMake Error at C:/Program Files/CMake/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:146 (message):
  Could NOT find GTest (missing: GTEST_LIBRARY GTEST_INCLUDE_DIR
  GTEST_MAIN_LIBRARY)
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:393 (_FPHSA_FAILURE_MESSAGE)
  C:/Program Files/CMake/share/cmake-3.16/Modules/FindGTest.cmake:205 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  plugin/al/mayatest/AL/maya/test/CMakeLists.txt:5 (find_package)

How should I proceed from here?
