### ISSUE TITLE
maya-usd camera unit test fails in interactive Maya, succeeds in prompt mode

### ISSUE THREAD

**Issue by elenadBlueSky** [Autodesk/maya-usd#270]
When I run the maya-usd camera unit test, it fails in interactive Maya but succeeds in prompt mode. Note that this happens in my build of the dev branch for Maya 2019.  In my build for Maya 2020 the test succeeds.

**To reproduce:**
- Unload AL_USDMayaPlugin.so, if loaded
- Load AL_USDMayaTestPlugin.so if not loaded
- Run the camera test:
   `AL_maya_test_UnitTestHarness -ktf -f ProxyUsdGeomCamera.cameraProxyReadWriteAttributes`

**In the script editor, a bunch of messages like the following are printed:**

`// Error: line 1: Connection not made: 'AL_usdmaya_ProxyShape1.outStageData' -> 'AL_usd_ProxyUsdGeomCamera1.stage'.  Data types of source and destination are not compatible. // 
// Error: line 1: The attribute 'AL_usdmaya_ProxyShape1.outStageData' cannot be connected to 'AL_usd_ProxyUsdGeomCamera1.stage'. // 
// Error: /bluesky/design/users/elenad/dev/PACKAGES/maya-usd/plugin/al/lib/AL_USDMaya/AL/usdmaya/nodes/ProxyUsdGeomCamera.cpp:79 (kFailure): Unexpected Internal Failure : Failed to get 'stage' attr // 
...
` 

**In the shell window where I ran Maya, the following is printed:**

`
Note: Google Test filter = ProxyUsdGeomCamera.cameraProxyReadWriteAttributes
[==========] Running 1 test from 1 test case.
[----------] Global test environment set-up.
[----------] 1 test from ProxyUsdGeomCamera
[ RUN      ] ProxyUsdGeomCamera.cameraProxyReadWriteAttributes
/bluesky/design/users/elenad/dev/PACKAGES/maya-usd/plugin/al/plugin/AL_USDMayaTestPlugin/AL/usdmaya/nodes/test_ProxyUsdGeomCamera.cpp:109: Failure
      Expected: UsdGeomTokens->orthographic
      Which is: orthographic
To be equal to: projection
      Which is: perspective
/bluesky/design/users/elenad/dev/PACKAGES/maya-usd/plugin/al/plugin/AL_USDMayaTestPlugin/AL/usdmaya/nodes/test_ProxyUsdGeomCamera.cpp:110: Failure
      Expected: true
To be equal to: proxyCamera->orthographicPlug().asBool()
      Which is: false
/bluesky/design/users/elenad/dev/PACKAGES/maya-usd/plugin/al/plugin/AL_USDMayaTestPlugin/AL/usdmaya/nodes/test_ProxyUsdGeomCamera.cpp:114: Failure
      Expected: static_cast<uint16_t>(ProxyUsdGeomCamera::Projection::Perspective)
      Which is: 0
To be equal to: proxyCamera->projectionPlug().asShort()
      Which is: 1
/bluesky/design/users/elenad/dev/PACKAGES/maya-usd/plugin/al/plugin/AL_USDMayaTestPlugin/AL/usdmaya/nodes/test_ProxyUsdGeomCamera.cpp:119: Failure
      Expected: true
To be equal to: proxyCamera->orthographicPlug().asBool()Note: Google Test filter = ProxyUsdGeomCamera.cameraProxyReadWriteAttributes
[==========] Running 1 test from 1 test case.
[----------] Global test environment set-up.
[----------] 1 test from ProxyUsdGeomCamera
[ RUN      ] ProxyUsdGeomCamera.cameraProxyReadWriteAttributes
/bluesky/design/users/elenad/dev/PACKAGES/maya-usd/plugin/al/plugin/AL_USDMayaTestPlugin/AL/usdmaya/nodes/test_ProxyUsdGeomCamera.cpp:109: Failure
      Expected: UsdGeomTokens->orthographic
      Which is: orthographic
To be equal to: projection
      Which is: perspective
/bluesky/design/users/elenad/dev/PACKAGES/maya-usd/plugin/al/plugin/AL_USDMayaTestPlugin/AL/usdmaya/nodes/test_ProxyUsdGeomCamera.cpp:110: Failure
      Expected: true
To be equal to: proxyCamera->orthographicPlug().asBool()
      Which is: false
/bluesky/design/users/elenad/dev/PACKAGES/maya-usd/plugin/al/plugin/AL_USDMayaTestPlugin/AL/usdmaya/nodes/test_ProxyUsdGeomCamera.cpp:114: Failure
      Expected: static_cast<uint16_t>(ProxyUsdGeomCamera::Projection::Perspective)
      Which is: 0
To be equal to: proxyCamera->projectionPlug().asShort()
      Which is: 1
/bluesky/design/users/elenad/dev/PACKAGES/maya-usd/plugin/al/plugin/AL_USDMayaTestPlugin/AL/usdmaya/nodes/test_ProxyUsdGeomCamera.cpp:119: Failure
      Expected: true
To be equal to: proxyCamera->orthographicPlug().asBool()
      Which is: false
/bluesky/design/users/elenad/dev/PACKAGES/maya-usd/plugin/al/plugin/AL_USDMayaTestPlugin/AL/usdmaya/nodes/test_ProxyUsdGeomCamera.cpp:126: Failure
      Expected: UsdGeomTokens->left
      Which is: left
To be equal to: stereoRole
      Which is: mono
/bluesky/design/users/elenad/dev/PACKAGES/maya-usd/plugin/al/plugin/AL_USDMayaTestPlugin/AL/usdmaya/nodes/test_ProxyUsdGeomCamera.cpp:134: Failure
      Expected: static_cast<uint16_t>(ProxyUsdGeomCamera::StereoRole::Left)
      Which is: 1
To be equal to: proxyCamera->stereoRolePlug().asShort()
      Which is: 0
/bluesky/design/users/elenad/dev/PACKAGES/maya-usd/plugin/al/plugin/AL_USDMayaTestPlugin/AL/usdmaya/nodes/test_ProxyUsdGeomCamera.cpp:144: Failure
      Expected: 8.0f
      Which is: 8
To be equal to: fStop
      Which is: 0
/bluesky/design/users/elenad/dev/PACKAGES/maya-usd/plugin/al/plugin/AL_USDMayaTestPlugin/AL/usdmaya/nodes/test_ProxyUsdGeomCamera.cpp:148: Failure
      Expected: 5.6f
      Which is: 5.6
To be equal to: proxyCamera->fStopPlug().asFloat()
      Which is: 8
/bluesky/design/users/elenad/dev/PACKAGES/maya-usd/plugin/al/plugin/AL_USDMayaTestPlugin/AL/usdmaya/nodes/test_ProxyUsdGeomCamera.cpp:155: Failure
      Expected: 10.0f
      Which is: 10
To be equal to: focusDistance
      Which is: 0
/bluesky/design/users/elenad/dev/PACKAGES/maya-usd/plugin/al/plugin/AL_USDMayaTestPlugin/AL/usdmaya/nodes/test_ProxyUsdGeomCamera.cpp:159: Failure
      Expected: 100.0f
      Which is: 100
To be equal to: proxyCamera->focusDistancePlug().asFloat()
      Which is: 10
/bluesky/design/users/elenad/dev/PACKAGES/maya-usd/plugin/al/plugin/AL_USDMayaTestPlugin/AL/usdmaya/nodes/test_ProxyUsdGeomCamera.cpp:166: Failure
      Expected: 200.0f
      Which is: 200
To be equal to: focalLength
      Which is: 50
/bluesky/design/users/elenad/dev/PACKAGES/maya-usd/plugin/al/plugin/AL_USDMayaTestPlugin/AL/usdmaya/nodes/test_ProxyUsdGeomCamera.cpp:170: Failure
      Expected: 50.0f
      Which is: 50
To be equal to: proxyCamera->focalLengthPlug().asFloat()
      Which is: 200
/bluesky/design/users/elenad/dev/PACKAGES/maya-usd/plugin/al/plugin/AL_USDMayaTestPlugin/AL/usdmaya/nodes/test_ProxyUsdGeomCamera.cpp:177: Failure
      Expected: 200.0
      Which is: 200
To be equal to: shutterOpen
      Which is: 0
/bluesky/design/users/elenad/dev/PACKAGES/maya-usd/plugin/al/plugin/AL_USDMayaTestPlugin/AL/usdmaya/nodes/test_ProxyUsdGeomCamera.cpp:181: Failure
      Expected: 50.0
      Which is: 50
To be equal to: proxyCamera->shutterOpenPlug().asDouble()
      Which is: 200
/bluesky/design/users/elenad/dev/PACKAGES/maya-usd/plugin/al/plugin/AL_USDMayaTestPlugin/AL/usdmaya/nodes/test_ProxyUsdGeomCamera.cpp:188: Failure
      Expected: 200.0
      Which is: 200
To be equal to: shutterClose
      Which is: 0
/bluesky/design/users/elenad/dev/PACKAGES/maya-usd/plugin/al/plugin/AL_USDMayaTestPlugin/AL/usdmaya/nodes/test_ProxyUsdGeomCamera.cpp:192: Failure
      Expected: 50.0
      Which is: 50
To be equal to: proxyCamera->shutterClosePlug().asDouble()
      Which is: 200
/bluesky/design/users/elenad/dev/PACKAGES/maya-usd/plugin/al/plugin/AL_USDMayaTestPlugin/AL/usdmaya/nodes/test_ProxyUsdGeomCamera.cpp:199: Failure
      Expected: 18.0f
      Which is: 18
To be equal to: horizontalAperture
      Which is: 20.955
/bluesky/design/users/elenad/dev/PACKAGES/maya-usd/plugin/al/plugin/AL_USDMayaTestPlugin/AL/usdmaya/nodes/test_ProxyUsdGeomCamera.cpp:203: Failure
      Expected: 36.0f
      Which is: 36
To be equal to: proxyCamera->horizontalAperturePlug().asFloat()
      Which is: 18
/bluesky/design/users/elenad/dev/PACKAGES/maya-usd/plugin/al/plugin/AL_USDMayaTestPlugin/AL/usdmaya/nodes/test_ProxyUsdGeomCamera.cpp:210: Failure
      Expected: 12.0f
      Which is: 12
To be equal to: verticalAperture
      Which is: 15.2908
/bluesky/design/users/elenad/dev/PACKAGES/maya-usd/plugin/al/plugin/AL_USDMayaTestPlugin/AL/usdmaya/nodes/test_ProxyUsdGeomCamera.cpp:214: Failure
      Expected: 24.0f
      Which is: 24
To be equal to: proxyCamera->verticalAperturePlug().asFloat()
      Which is: 12
/bluesky/design/users/elenad/dev/PACKAGES/maya-usd/plugin/al/plugin/AL_USDMayaTestPlugin/AL/usdmaya/nodes/test_ProxyUsdGeomCamera.cpp:221: Failure
      Expected: 3.0f
      Which is: 3
To be equal to: horizontalApertureOffset
      Which is: 0
/bluesky/design/users/elenad/dev/PACKAGES/maya-usd/plugin/al/plugin/AL_USDMayaTestPlugin/AL/usdmaya/nodes/test_ProxyUsdGeomCamera.cpp:225: Failure
      Expected: 6.0f
      Which is: 6
To be equal to: proxyCamera->horizontalApertureOffsetPlug().asFloat()
      Which is: 3
/bluesky/design/users/elenad/dev/PACKAGES/maya-usd/plugin/al/plugin/AL_USDMayaTestPlugin/AL/usdmaya/nodes/test_ProxyUsdGeomCamera.cpp:232: Failure
      Expected: 2.0f
      Which is: 2
To be equal to: verticalApertureOffset
      Which is: 0
/bluesky/design/users/elenad/dev/PACKAGES/maya-usd/plugin/al/plugin/AL_USDMayaTestPlugin/AL/usdmaya/nodes/test_ProxyUsdGeomCamera.cpp:236: Failure
      Expected: 4.0f
      Which is: 4
To be equal to: proxyCamera->verticalApertureOffsetPlug().asFloat()
      Which is: 2
/bluesky/design/users/elenad/dev/PACKAGES/maya-usd/plugin/al/plugin/AL_USDMayaTestPlugin/AL/usdmaya/nodes/test_ProxyUsdGeomCamera.cpp:244: Failure
      Expected: 0.1f
      Which is: 0.1
To be equal to: clippingRange[0]
      Which is: 1
/bluesky/design/users/elenad/dev/PACKAGES/maya-usd/plugin/al/plugin/AL_USDMayaTestPlugin/AL/usdmaya/nodes/test_ProxyUsdGeomCamera.cpp:245: Failure
      Expected: 1000.0f
      Which is: 1000
To be equal to: clippingRange[1]
      Which is: 1e+06
/bluesky/design/users/elenad/dev/PACKAGES/maya-usd/plugin/al/plugin/AL_USDMayaTestPlugin/AL/usdmaya/nodes/test_ProxyUsdGeomCamera.cpp:249: Failure
      Expected: 1.0f
      Which is: 1
To be equal to: proxyCamera->nearClipPlanePlug().asFloat()
      Which is: 0.1
/bluesky/design/users/elenad/dev/PACKAGES/maya-usd/plugin/al/plugin/AL_USDMayaTestPlugin/AL/usdmaya/nodes/test_ProxyUsdGeomCamera.cpp:250: Failure
      Expected: 10000.0f
      Which is: 10000
To be equal to: proxyCamera->farClipPlanePlug().asFloat()`
      Which is: 1000
[  FAILED  ] ProxyUsdGeomCamera.cameraProxyReadWriteAttributes (265 ms)
[----------] 1 test from ProxyUsdGeomCamera (265 ms total)

[----------] Global test environment tear-down
[==========] 1 test from 1 test case ran. (266 ms total)
[  PASSED  ] 0 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] ProxyUsdGeomCamera.cameraProxyReadWriteAttributes

 1 FAILED TEST

**Comment by vlasovi** [comment]
The issue seems obsolete, closing.
