### ISSUE TITLE
Test File Vaccine

### ISSUE THREAD

**Issue by aaronmack** [Autodesk/maya-usd#2711]
![image](https://user-images.githubusercontent.com/43235864/200726577-b0f32cee-ed30-411a-90e6-9a243261c03a.png)

**Describe the bug**
Antivirus software says it's a virus

**Specs (if applicable):**
 - OS & version Windows 10

**Comment by aaronmack** [comment]
`maya-usd/test/lib/usd/translators/UsdExportRfMLightTest/RfMLightsTest.ma`

![image](https://user-images.githubusercontent.com/43235864/200728595-9f1d69a2-32fe-401d-849e-c93ce1ce3a4e.png)

**Comment by tanant** [comment]
Looks like it was introduced in 9ee7aef

**Comment by santosg87** [comment]
thanks for logging this @aaronmack. This is indeed a virus of sorts, it replicates through the maya preferences and write that attribute on other files.  

this looks like it was something introduced while creating a test file from an infected machine.

for a bit more info on that virus:
https://forums.autodesk.com/t5/maya-forum/maya-virus/td-p/10028053
