### ISSUE TITLE
undefined symbol in libpxOsd.so

### ISSUE THREAD

**Issue by sjt-rvx** [Autodesk/maya-usd#2712]
We are running maya2022.4 on RockyLinux 8.6 and using the maya-usd version 0.20.0 build for 2022.4, and when I try and load the plugin in the plugin manager I get this error:

```
// Error: file: /usr/autodesk/maya2022/scripts/others/pluginWin.mel line 316: Unable to dynamically load : /usr/autodesk/mayausd/maya2022/0.20.0_202210201313-b84fd36/mayausd/MayaUSD3/plugin/adsk/plugin/mayaUsdPlugin.so
/usr/autodesk/mayausd/maya2022/0.20.0_202210201313-b84fd36/mayausd/MayaUSD3/plugin/adsk/plugin/../../../../USD3/lib/libpxOsd.so: undefined symbol: _ZN32pxrInternal_v0_21__pxrReserved__11TfSingletonINS_20TfScriptModuleLoaderEE9_instanceE // 
// Error: file: /usr/autodesk/maya2022/scripts/others/pluginWin.mel line 316: /usr/autodesk/mayausd/maya2022/0.20.0_202210201313-b84fd36/mayausd/MayaUSD3/plugin/adsk/plugin/../../../../USD3/lib/libpxOsd.so: undefined symbol: _ZN32pxrInternal_v0_21__pxrReserved__11TfSingletonINS_20TfScriptModuleLoaderEE9_instanceE (mayaUsdPlugin) //
```

Any ideas as to what might cause this?

**Comment by seando-adsk** [comment]
@sjt-rvx Have you successfully loaded previous versions of the MayaUsd plugin? Can you verify (especially in LD_LIBRARY_PATH) that you don't have another USD that could be conflicting.

Sean

**Comment by sjt-rvx** [comment]
Ah, there seems to have been a misunderstanding between myself and IT - we did in fact NOT have maya2022.4 installed, just maya2022.0, updating maya fixed this issue. Sorry about this. :sheep:
