### ISSUE TITLE
Unable to load plugin in Maya 2020, "The specified procedure could not be found"

### ISSUE THREAD

**Issue by benjysugi** [Autodesk/maya-usd#2719]
**Describe the bug**
Whenever I try enable the plugin, it just says "The specified procedure could not be found"

**Steps to reproduce**
1. Install the plugin
2. Enable from plugin manager

**Attachments**
![image](https://user-images.githubusercontent.com/61796469/201550436-1862a7a9-b310-43a1-813c-cca943ea06ff.png)

**Specs (if applicable):**
 - OS & version: Windows 10 Pro
 - Maya version: Maya 2020
 - Maya USD commit SHA: 734b6cf7d264f3df37bb2703dd47d9332ed6b1cb

**Comment by seando-adsk** [comment]
@benjysugi This issue is usually caused by a conflicting USD being found in your PATH or PYTHONPATH. Please check both of these and make sure the only USD in them is the one from MayaUsd. You can check these from within Maya using the following MEL code:
```getenv "PATH"```

**Comment by benjysugi** [comment]
> @benjysugi This issue is usually caused by a conflicting USD being found in your PATH or PYTHONPATH. Please check both of these and make sure the only USD in them is the one from MayaUsd. You can check these from within Maya using the following MEL code: `getenv "PATH"`

Path is as follows:
```
C:/Program Files/Autodesk/Maya2020/Python/lib/site-packages/PySide2
C:/Program Files/Autodesk/Maya2020/plug-ins/ATF/ATF
C:/Program Files/Autodesk/Maya2020/plug-ins/ATF/ATF/alias
C:/Program Files/Autodesk/Maya2020/bin/Cg
C:/Program Files/Autodesk/Maya2020/bin
C:/Program Files (x86)/Common Files/Intel/Shared Libraries/redist/intel64/compiler
C:/Windows/system32
C:/Windows
C:/Windows/System32/Wbem
C:/Windows/System32/WindowsPowerShell/v1.0/
C:/Windows/System32/OpenSSH/
C:/Program Files/PuTTY/
C:/Program Files/Microsoft VS Code/bin
C:/Program Files/Microsoft SQL Server/150/Tools/Binn/
C:/Program Files/Microsoft SQL Server/Client SDK/ODBC/170/Tools/Binn/
C:/Program Files/dotnet/
C:/Program Files/Git/cmd
C
C:/Program Files/Microsoft SQL Server/130/Tools/Binn/
C:/Program Files/010 Editor
C:/Program Files/Common Files/Autodesk Shared/
C:/Program Files (x86)/Autodesk/Backburner/
C:/Program Files/NVIDIA Corporation/NVIDIA NvDLISR
C:/Program Files (x86)/NVIDIA Corporation/PhysX/Common
C:/Program Files/CMake/bin
C:/Users/bsugiyama/AppData/Local/Microsoft/WindowsApps
C:/Users/bsugiyama/.dotnet/tools
C:/Users/bsugiyama/AppData/Local/GitHubDesktop/bin
C:/PTOOLS
C:/VAVE/SDK
D:/VAVE/VDev/bin
D:/VAVE/ATS/bin/ATS_EDITOR_NIGHTLY/2022/windows/final
C:/Program Files/Autodesk/Maya2020/plug-ins/MASH/bin
C:/Program Files/Autodesk/MayaUSD/Maya2020/0.20.0_202210201313-b84fd36/mayausd/MayaUSD/lib
C:/Program Files/Autodesk/MayaUSD/Maya2020/0.20.0_202210201313-b84fd36/mayausd/USD/bin
C:/Program Files/Autodesk/MayaUSD/Maya2020/0.20.0_202210201313-b84fd36/mayausd/USD/lib
C:/Program Files/Autodesk/MayaUSD/Maya2020/0.20.0_202210201313-b84fd36/mayausd/USD/plugin/usd
C:/Program Files/Autodesk/Arnold/maya2020/bin
C:/Program Files/Autodesk/Maya2020/plug-ins/xgen/bin```

**Comment by benjysugi** [comment]
> @benjysugi This issue is usually caused by a conflicting USD being found in your PATH or PYTHONPATH. Please check both of these and make sure the only USD in them is the one from MayaUsd. You can check these from within Maya using the following MEL code: `getenv "PATH"`

@seando-adsk 
Path is as follows:
```
C:/Program Files/Autodesk/Maya2020/Python/lib/site-packages/PySide2
C:/Program Files/Autodesk/Maya2020/plug-ins/ATF/ATF
C:/Program Files/Autodesk/Maya2020/plug-ins/ATF/ATF/alias
C:/Program Files/Autodesk/Maya2020/bin/Cg
C:/Program Files/Autodesk/Maya2020/bin
C:/Program Files (x86)/Common Files/Intel/Shared Libraries/redist/intel64/compiler
C:/Windows/system32
C:/Windows
C:/Windows/System32/Wbem
C:/Windows/System32/WindowsPowerShell/v1.0/
C:/Windows/System32/OpenSSH/
C:/Program Files/PuTTY/
C:/Program Files/Microsoft VS Code/bin
C:/Program Files/Microsoft SQL Server/150/Tools/Binn/
C:/Program Files/Microsoft SQL Server/Client SDK/ODBC/170/Tools/Binn/
C:/Program Files/dotnet/
C:/Program Files/Git/cmd
C
C:/Program Files/Microsoft SQL Server/130/Tools/Binn/
C:/Program Files/010 Editor
C:/Program Files/Common Files/Autodesk Shared/
C:/Program Files (x86)/Autodesk/Backburner/
C:/Program Files/NVIDIA Corporation/NVIDIA NvDLISR
C:/Program Files (x86)/NVIDIA Corporation/PhysX/Common
C:/Program Files/CMake/bin
C:/Users/bsugiyama/AppData/Local/Microsoft/WindowsApps
C:/Users/bsugiyama/.dotnet/tools
C:/Users/bsugiyama/AppData/Local/GitHubDesktop/bin
C:/PTOOLS
C:/VAVE/SDK
D:/VAVE/VDev/bin
D:/VAVE/ATS/bin/ATS_EDITOR_NIGHTLY/2022/windows/final
C:/Program Files/Autodesk/Maya2020/plug-ins/MASH/bin
C:/Program Files/Autodesk/MayaUSD/Maya2020/0.20.0_202210201313-b84fd36/mayausd/MayaUSD/lib
C:/Program Files/Autodesk/MayaUSD/Maya2020/0.20.0_202210201313-b84fd36/mayausd/USD/bin
C:/Program Files/Autodesk/MayaUSD/Maya2020/0.20.0_202210201313-b84fd36/mayausd/USD/lib
C:/Program Files/Autodesk/MayaUSD/Maya2020/0.20.0_202210201313-b84fd36/mayausd/USD/plugin/usd
C:/Program Files/Autodesk/Arnold/maya2020/bin
C:/Program Files/Autodesk/Maya2020/plug-ins/xgen/bin```

**Comment by seando-adsk** [comment]
I don't see anything obvious in you PATH that would conflict. If you are able you could try starting a Windows command prompt and then from there set your PATH by removing items you don't need for Maya, such as Nvidia, PTOOLS, VAVE, etc. Then run your Maya 2020 from this command prompt.

Can you also send your PYTHONPATH:
```getenv "PYTHONPATH"```

Sean

**Comment by benjysugi** [comment]
@seando-adsk 

> I don't see anything obvious in you PATH that would conflict. If you are able you could try starting a Windows command prompt and then from there set your PATH by removing items you don't need for Maya, such as Nvidia, PTOOLS, VAVE, etc. Then run your Maya 2020 from this command prompt.
> 
> Can you also send your PYTHONPATH: `getenv "PYTHONPATH"`
> 
> Sean

I need those as they're internal tools at my studio.
Here's python path as requested:
```
C:/Program Files/Autodesk/Maya2020/plug-ins/ATF/scripts
C:/Program Files/Autodesk/Maya2020/plug-ins/MASH/scripts
C:/Program Files/Autodesk/MayaUSD/Maya2020/0.20.0_202210201313-b84fd36/mayausd/MayaUSD/plugin/adsk/scripts
C:/Program Files/Autodesk/MayaUSD/Maya2020/0.20.0_202210201313-b84fd36/mayausd/MayaUSD/lib/scripts
C:/Program Files/Autodesk/Maya2020/plug-ins/fbx/scripts
C:/Program Files/Autodesk/Maya2020/plug-ins/camd/scripts
C:/Program Files/Autodesk/Arnold/maya2020/scripts
C:/Program Files/Autodesk/Maya2020/plug-ins/xgen/scripts
C:/Program Files/Autodesk/MayaUSD/Maya2020/0.20.0_202210201313-b84fd36/mayausd/MayaUSD/lib/python
C:/Program Files/Autodesk/MayaUSD/Maya2020/0.20.0_202210201313-b84fd36/mayausd/USD/lib/python```

**Comment by seando-adsk** [comment]
@benjysugi Removing the items from your path would just be for a test to rule them out as the cause of the plugin failure. That is why I suggested doing them from a command prompt. You wouldn't be affecting the path of your system, just that single command prompt.

There is nothing suspicious in your PYTHONPATH, everything seems okay there.

Can you verify the exact Maya 2020 version you are using? The plugin build we provided was built specifically for Maya 2020 **Update 4**. It is not guaranteed to work in earlier versions.

Sean

**Comment by benjysugi** [comment]
@seando-adsk 

> @benjysugi Removing the items from your path would just be for a test to rule them out as the cause of the plugin failure. That is why I suggested doing them from a command prompt. You wouldn't be affecting the path of your system, just that single command prompt.
> 
> There is nothing suspicious in your PYTHONPATH, everything seems okay there.
> 
> Can you verify the exact Maya 2020 version you are using? The plugin build we provided was built specifically for Maya 2020 **Update 4**. It is not guaranteed to work in earlier versions.
> 
> Sean

How do I check the exact version?

**Comment by santosd** [comment]
@benjysugi, to check the Maya version go to Help > About Maya. At the Top you have the Cut ID and the version. To find the Maya USD version go to Windows > Settings\Preferences > Plugin Manager > Look for Maya USD and in the Path you will see a version that looks like 0.20.0_202210201313-b84fd36.
Did you build Maya USD yourself? If so, you may want to try the installer we provide to see if that works.
![MayaVersionUSDVersion](https://user-images.githubusercontent.com/29235905/202227063-4d49fdcd-e0ec-491e-9ab2-66afe3efab46.gif)

**Comment by benjysugi** [comment]
@santosd I used the precompiled binary from the Releases section, 
![image](https://user-images.githubusercontent.com/61796469/202303842-19dfa3af-af52-483e-a1f3-10d0bb654ca6.png)
![image](https://user-images.githubusercontent.com/61796469/202303929-a8b85bb1-80b5-4527-8ccc-956941713e91.png)

**Comment by santosd** [comment]
Hi @benjysugi it looks like you may not have Maya 2020.4 installed. In the version section of Help > About Maya, does it show "Maya 2020 Update 4"? If you you will need to log into your account manage.autodesk.com and then download and install Maya 2020.4

**Comment by benjysugi** [comment]
> Hi @benjysugi it looks like you may not have Maya 2020.4 installed. In the version section of Help > About Maya, does it show "Maya 2020 Update 4"? If you you will need to log into your account manage.autodesk.com and then download and install Maya 2020.4

Alright, I'll update
