### ISSUE TITLE
[MAYA-125727] Display Layer Editor: Template & Reference toggle button does not work for instanced prims

### ISSUE THREAD

**Issue by gracekumagai** [Autodesk/maya-usd#2723]
**Describe the bug**
When testing the Display Layer updates (#319), we noticed that when prims are added to a display layer and are marked as instaneable, the template and reference buttons do not work as expected.

When template is enabled, the prims remain selectable and are not drawn with a wireframe.
When reference is enabled, the prims remain selectable in the viewport.

**Steps to reproduce**

1. Open `Kitchen_Set_instanced`
2. Navigate to Create -> Polygon Primitives -> Sphere
3. Select `|Kitchen_set_instanced|Kitchen_set_instancedShape,/Kitchen_set/Props_grp/DiningTable_grp/ChairB_1` and `pSphere1`
4. Create a new layer in Display Layer editor 
5. Right click on layer and use "Add Selected Objects"
6. Toggle the 3rd button from the left

When the button is toggled to "T" (Template), notice that the sphere has a wireframe and cannot be selected in the viewport - as expected. However, the chair can be selected in the viewport and is not drawn with a wireframe. 

When the button is toggled to "R" (Reference), notice that the sphere has uses the current display mode (smooth shade) and cannot be selected in the viewport - as expected. However, the chair can be selected in the viewport. 

With #2652, it is challenging to test the behaviour when a prim marked as instanceable is unmarked as instanceable and vice-versa.

When using the `Kitchen_set` and following the same steps as above, the chair behaves as expected in template and reference mode.

**Expected behavior**
We would expect the same behaviour as native maya and when the prim is not marked as instanceable.

**Specs (if applicable):**
 - Linux
 - Maya version 2023.2
 - Maya USD commit SHA [dev at d1ae8fe] 
 - Pixar USD commit SHA [dev at 9d21755]

Pixar Internal JIRA MAYA-3533

**Comment by santosg87** [comment]
Hi @gracekumagai!

that is correct - its currently just an unsupported workflow, as it is with point instanced prims as well. we have a couple of internal issues logged regarding the workflow.

**Comment by womanyoyoyo-adsk** [comment]
This is currently in progress.

**Comment by santosg87** [comment]
this should be available now on Maya 0.23.0

note though, that the fix for this requires Maya changes, so Maya 2024 will be needed in order to to see the fix.

**Comment by dj-mcg** [comment]
Hi @santosg87 - I'm seeing this working in 2023.3 with latest MayaUsd, just FYI. Let me know if that's surprising!
