### ISSUE TITLE
[MAYA-126310] Display Layer Editor: Template toggle button discrepancy between docs and behaviour

### ISSUE THREAD

**Issue by gracekumagai** [Autodesk/maya-usd#2724]
**Describe the bug**
When testing the Display Layer updates (https://github.com/Autodesk/maya-usd/issues/319), we checked out the Display Layer documentation (https://help.autodesk.com/view/MAYAUL/2023/ENU/?guid=GUID-C52465E4-FA5F-46AF-A186-E20ABEDD9BF2) and on this page under "Display Layer toggle buttons", under "template", it mentions that the prims should not be selectable in the viewport **or outliner** when template is enabled. 

However, when template is enabled, I am able to select the prims in the outliner. I am also able to select native maya objects from the outliner too.

I am unsure if this is a bug or an error in the documentation since I'm able to select prims and nodes in the outliner.

**Steps to reproduce**

1. Open `Kitchen_Set`
2. Navigate to Create -> Polygon Primitives -> Sphere
3. Select `|Kitchen_set|Kitchen_setShape,/Kitchen_set/Props_grp/DiningTable_grp/ChairB_1` and `pSphere1`
4. Create a new layer in Display Layer editor
5. Right click on layer and use "Add Selected Objects"
6. Toggle the 3rd button from the left to "Template"

Notice that I can select both the sphere and chair from the outliner.

**Expected behavior**
We'd expect parity between the behaviour in Maya and the docs

**Specs (if applicable):**
Linux
Maya version 2023.2
Maya USD commit SHA [dev at https://github.com/Autodesk/maya-usd/commit/d1ae8fe0d704755cf941eeb691527ba0151102e1]
Pixar USD commit SHA [dev at 9d21755]

Pixar Internal Jira MAYA-3535

**Comment by womanyoyoyo-adsk** [comment]
Hi @gracekumagai, that's an error in our docs. Thank you for bringing this to our attention!

**Comment by santosd** [comment]
An internal ticket was logged to fix the docs.

**Comment by santosd** [comment]
@gracekumagai the docs issue has been fixed internally and will be updated with the next Maya release. I will go ahead and close this ticket out for the time being. Let me know if it needs reopened or if you have any questions.

**Comment by gracekumagai** [comment]
Thank you!
