### ISSUE TITLE
[MAYA-110448] Maya File Referencing fails use correct "USD Import" MPxFileTranslator

### ISSUE THREAD

**Issue by gelshoffNV** [Autodesk/maya-usd#2727]
**Describe the bug**
When creating a maya reference to a USD file, the "USD Import" type is used, but when the maya scene is saved, the type changes to "USD Export". This results in the saved file not loading the reference in the correct namespace.

This appears to be the same issue that was in the AL plugin: 
https://github.com/Autodesk/maya-usd/issues/107

which was supposed to be resolved by MAYA-101980 which was part of the 0.8.0 release:
https://help.autodesk.com/view/MAYAUL/2022/ENU/?guid=GUID-21318687-5F97-4633-99F0-C73F8213A5F9

But I can't see what the fix was, if that fix could be put into the adsk plugin, that would probably fix the issue. 

There is a comment in the AL plugin about not using the base MPxFileTranslator::read / write methods, possibly they don't return the correct MStatus and result in "USD Export" getting handled when it shouldn't be...but this code seems to have been in before 0.8.0, so maybe it's not that: https://github.com/Autodesk/maya-usd/blob/f8f82abae34a4040f21375c11bc5398d25b4c2b1/plugin/al/mayautils/AL/maya/utils/FileTranslatorBase.h#L178

**Steps to reproduce**
1. Create a maya reference to a USD file, using namespaces
2. Save scene as MayaAscii
3. Open the saved .ma in a txt editor and notice at the top, the reference says: -typ "USD Export"

**Expected behavior**
The type should remain "USD Import"
The saved scene should load the usd reference into the correct namespace, the current behavior creates no namespace until you "reload" the reference.

**Comment by santosg87** [comment]
Hi @gelshoffNV thank you for logging this.

The behavior you mention is something that was done during our initial refactoring of the mayausd and al worfklows. the change was from a AL specific variable, to USD Export. so this would be a different issue.

**Comment by santosg87** [comment]
after some more testing, note that this will break namespacing on a USD reference.

for example:
* creating a reference to a USD file under a "foo" namespace will make a scene with your nodes named "foo:USDdata". Saving that Maya scene will remove the namespace.
* Reloading the scene will allow the user to get a namespace, but "foo" is lost.

**Comment by tanant** [comment]
This reminds me a lot of #1244 to be honest, @santosg87 is this the same thing?

**Comment by santosg87** [comment]
it is indeed! #107 #1244 and this issue are pretty much all pointing to the same culprit here. the "-typ" is not correct and it causes a few different visible issues on referencing.

**Comment by willis102** [comment]
@santosg87, do you have an idea of timeline for this ticket?  It's actually fairly disruptive to our intended rigging and animation workflows, it would be fantastic to get it resolved.  Thanks!

**Comment by santosg87** [comment]
@willis102 after some investigation on this, the problem seems to be something that would require Maya code changes, so in order to get this fixed, we would need to include the fix onto a future version of Maya.

we are working on having this fixed on future maya versions, however, with the fact that this will require a maya fix, this is not something that can be ported to the plugin itself.

**Comment by santosg87** [comment]
this issue is fixed now on the latest mayausd build.

note that this fix required changes on the maya code itself, so maya 2024 is necessary in order to see the fix/
