### ISSUE TITLE
Relationship Editor: Crashes Maya on close if a prim added to a display layer is exposed on the RHS

### ISSUE THREAD

**Issue by gracekumagai** [Autodesk/maya-usd#2739]
**Describe the bug**
The Relationship Editor is not a tool that is commonly used by the set dressers and therefore, bugs in this tool do not block their work. However, we noticed a crash when testing and wanted to report it for completeness! 

**Steps to reproduce**
1. Open `Kitchen_Set_instanced` or `Kitchen_set`
3. Select `|Kitchen_set_instanced|Kitchen_set_instancedShape,/Kitchen_set/Props_grp/DiningTable_grp/ChairB_1` 
4. Create a new layer in Display Layer editor
5. Right click on layer and use "Add Selected Objects"
6. Right click on the layer and select "Membership" to open the "Relationship Editor"
7. On the RHS of the "Relationship Editor", expand the hierarchy until `ChairB_1` is exposed and its parent is expanded
8. On the LHS of the "Relationship Editor", click the layer that you created and contains `ChairB_1`
9. Close the "Relationship Editor"

Closing the editor will cause Maya to crash. Maya does not crash if you skip step 7.

```
Stack trace:
  /dist/sw/maya/2023.update2/lib/libSharedUI.so(+0x4028d1) [0x7f4a63faf8d1]
  /dist/sw/maya/2023.update2/lib/libSharedUI.so(+0x3feedd) [0x7f4a63fabedd]
  /dist/sw/maya/2023.update2/lib/libSharedUI.so(+0x3f71cc) [0x7f4a63fa41cc]
  /dist/sw/maya/2023.update2/lib/libSharedUI.so(+0x405e63) [0x7f4a63fb2e63]
  QmayaOutlineItem::~QmayaOutlineItem()
  QmayaBaseNodeOutlineItem::~QmayaBaseNodeOutlineItem()
  TdagPathOutlineItem::~TdagPathOutlineItem()
  QmayaOutlineControl::removeAll()
  QmayaOutlineControl::~QmayaOutlineControl()
  /dist/sw/maya/2023.update2/lib/libSharedUI.so(+0x3cd295) [0x7f4a63f7a295]
  /dist/sw/maya/2023.update2/lib/libSharedUI.so(+0x52a81a) [0x7f4a640d781a]
  TbasePanelEditorCmd::doEditFlags()
  /dist/sw/maya/2023.update2/lib/libSharedUI.so(+0x52c1b5) [0x7f4a640d91b5]
  TiceBaseCmd::doEdit()
  TiceBaseCmd::doCommand(TargList&)
  /dist/sw/maya/2023.update2/lib/libCommandEngine.so(+0x9e464) [0x7f4a5d492464]
  /dist/sw/maya/2023.update2/lib/libCommandEngine.so(+0xc8809) [0x7f4a5d4bc809]
  /dist/sw/maya/2023.update2/lib/libCommandEngine.so(+0xeb3fd) [0x7f4a5d4df3fd]
  /dist/sw/maya/2023.update2/lib/libCommandEngine.so(+0xc8809) [0x7f4a5d4bc809]
  /dist/sw/maya/2023.update2/lib/libCommandEngine.so(+0xeb3fd) [0x7f4a5d4df3fd]
  /dist/sw/maya/2023.update2/lib/libCommandEngine.so(+0xc8809) [0x7f4a5d4bc809]
  /dist/sw/maya/2023.update2/lib/libCommandEngine.so(+0xc89e1) [0x7f4a5d4bc9e1]
  SophiaExecutable::evaluate(void*)
  TcommandEngine::executeCommand(Tstring const&, bool, bool, TmelCmdResult*, unsigned int)
  TscriptedPanel::removeFromLayout()
  QmayaWindowEventFilterObject::processWindowDeleteOnClose(QObject*)
  QmayaWindowEventFilterObject::eventFilter(QObject*, QEvent*)
  QCoreApplicationPrivate::sendThroughApplicationEventFilters(QObject*, QEvent*)
  QApplicationPrivate::notify_helper(QObject*, QEvent*)
  QApplication::notify(QObject*, QEvent*)
  /dist/sw/maya/2023.update2/lib/libExtensionLayer.so(+0x33ec1a) [0x7f4a5d9eec1a]
  QCoreApplication::notifyInternal2(QObject*, QEvent*)
  QWidgetPrivate::close_helper(QWidgetPrivate::CloseMode)
  TworkspaceTabWidget::handleWorkspaceControlClose(TworkspaceControl*, bool)
  TworkspaceSplitter::closeAllWorkspaceControls()
  TworkspaceDockingPanel::closePanel()
  TworkspaceDockingPanel::closeEvent(QCloseEvent*)
  QWidget::event(QEvent*)
  TworkspaceDockingPanel::event(QEvent*)
  QApplicationPrivate::notify_helper(QObject*, QEvent*)
1Writing crash report in /scratch/tmp/untitled[Recovered-gracek.2022-11-14-16.31].crash
/dist/sw/maya/2023.update2/bin/maya: line 203:  6404 Segmentation fault      (core dumped) /dist/sw/maya/2023.update2/bin/maya.bin
```

**Expected behavior**
We'd expect there not to be a crash. Ideally, the Relationship Editor would be updated to support UFE objects in object sets, however, atm, this is not necessary for our workflows.

**Specs (if applicable):**
- Linux
- Maya version 2023.2
- Maya USD commit SHA [dev at d1ae8fe]
- Pixar USD commit SHA [dev at 9d21755]

Pixar Internal JIRA MAYA-3534

**Comment by santosd** [comment]
Hello @gracekumagai, We hit the crash too and did some work so that the relationship editor won't show USD information because that information is not currently supported through the Relationship Editor. I tested in a recent build and when I open the relationship editor, I can only see the Maya transform data and none of the USD data is available:
![image](https://user-images.githubusercontent.com/29235905/211081952-7081f7ef-441f-4e42-92ed-36d9a6b3b3c0.png)
Can you rebuild the plugin at a more recent state and see if you are still hitting this?

**Comment by santosd** [comment]
Internally this issue is logged as MAYA-124484 (the ticket is closed and fixed.

**Comment by santosg87** [comment]
marking this one as closed, as we have it working internally for us. :)

**Comment by gracekumagai** [comment]
Hey @santosd & @santosg87, apologies for the delay in testing.

I wanted to let you know that I can still reproduce. 

I'm testing in maya 2023.2 and with maya-usd commit sha (dev at abf2928). I'll add this ticket to my list of issues to test when we get a new update of Maya on our side. Thanks!

**Comment by santosd** [comment]
Thank you @gracekumagai it look like this did require a fix in Maya so it will be something that will be fixed in a future release of Maya. Thank you.

**Comment by Ziethriel** [comment]
Just a note since I found this, maybe others will too. I'm having issues with adding objects to display layers without USD. Maybe 1/50adds will crash Maya. This might not be a USD issue at all. This has been going on for a few versions.
