### ISSUE TITLE
[MAYA-128594] Imported displayOpacity are not interpreted correctly

### ISSUE THREAD

**Issue by charlesfleche** [Autodesk/maya-usd#2753]
**Describe the bug**
When importing a simple USD object with displayOpacity, reexporting it as-is stores different values.

**Steps to reproduce**
1. Import the attached USD that has displayOpacity as [.25, .5, .75, 1]
2. Export the imported plane to USD
3. Open the exported USD
4. See that the displayOpacity is [0.25, 0.25, 0.25, 0.25]

**Expected behavior**
The exported displayOpacity should be  [.25, .5, .75, 1]

**Attachments**
- `to-import.usda` the USD to import into Maya

```
#usda 1.0
(
    metersPerUnit = 1
    upAxis = "Z"
)

def Mesh "Plane"
{
	int[] faceVertexCounts = [4]
	int[] faceVertexIndices = [0, 1, 3, 2]
	point3f[] points = [(-1, -1, 0), (1, -1, 0), (-1, 1, 0), (1, 1, 0)]
	uniform token subdivisionScheme = "none"
	
	color3f[] primvars:displayColor = [(1, 0, 0), (0, 1, 0), (0, 0, 1), (1, 0, 1)] (
		interpolation = "vertex"
	)
	float[] primvars:displayOpacity = [.25, .5, .75, 1] (
		interpolation = "vertex"
	)
}
```

- `exported-from-maya.usda` , the USD exported from Maya

```
#usda 1.0
(
    defaultPrim = "plane_vcolors_Plane"
    metersPerUnit = 0.01
    upAxis = "Z"
)

def Mesh "plane_vcolors_Plane" (
    kind = "component"
)
{
    float3[] extent = [(-1, -1, 0), (1, 1, 0)]
    int[] faceVertexCounts = [4]
    int[] faceVertexIndices = [0, 1, 3, 2]
    normal3f[] normals = [(0, 0, 1), (0, 0, 1), (0, 0, 1), (0, 0, 1)] (
        interpolation = "faceVarying"
    )
    point3f[] points = [(-1, -1, 0), (1, -1, 0), (-1, 1, 0), (1, 1, 0)]
    color3f[] primvars:displayColor = [(1, 0, 0), (0, 1, 0), (1, 0, 1), (0, 0, 1)] (
        interpolation = "vertex"
    )
    int[] primvars:displayColor:indices = [0, 1, 3, 2]
    float[] primvars:displayOpacity = [0.25, 0.25, 0.25, 0.25] (
        customData = {
            dictionary Maya = {
                bool generated = 1
            }
        }
        interpolation = "vertex"
    )
    int[] primvars:displayOpacity:indices = [0, 1, 3, 2]
    uniform token subdivisionScheme = "none"
}
```

- `to-import.usda` in usdview

<img width="1025" alt="image" src="https://user-images.githubusercontent.com/2563098/204649188-bcc070e3-45bb-415c-9422-2d5c47085112.png">

**Specs (if applicable):**
 - Windows 10
 - Maya 2023, no point release
 - maya-usd 0.19.0_202208181606-508c93f

**Comment by santosd** [comment]
Hi @charlesfleche, thank you for reporting this, at this point we don't have a fully lossless import\export translation. However, this file should be read in properly when brining it into Maya as USD data through a Create > Universal Scene Description > Stage from File... and using the .usda file. I will bring this up to the team and see if it is something we can fix in the near future.

**Comment by santosd** [comment]
I logged this internally as MAYA-128594 for the team to have a look and prioritize.

**Comment by charlesfleche** [comment]
Great, thank you !

**Comment by santosd** [comment]
Hi @charlesfleche, I wanted to let you know that this issue has been fixed with the following commit: https://git.autodesk.com/maya3d/maya-usd/commit/f1ab078e91c438630fb1ea61061834687f801ce4
If you are able to build MayaUSD on your own you can test it out. Otherwise the fix should be available in our next release. I have validated the fix on my end and it looks good on my end. Going to be closing this for now, but if you hit any issues let us know.
