### ISSUE TITLE
How can I export usd without materials with cmds.mayaUSDExport?

### ISSUE THREAD

**Issue by SelivanovaLera** [Autodesk/maya-usd#2763]
Hello, I need export usd from animation scene (with animation, no materials). I try to export usd with this command and get usd with materials (Looks) but it is not what i expected:

cmds.mayaUSDExport(file=path, selection=True, stripNamespaces=True, shadingMode=None, eulerFilter=True, exportUVs=False, frameRange=(start_frame, end_frame))

I also try other flags: exportMaterialCollections=False, exportColorSets=False , but result is the same. 

Maya 2023.2
Usd v19, v20

**Comment by jcoelho88** [comment]
Hi @SelivanovaLera,

Try this:

```python
path = "C:/YOUR PATH"
start_frame = 1
end_frame = 24

cmds.file(
        path, force=True, exportSelected=True, preserveReferences=True, type='USD Export',
        options=
        ";exportUVs=1;exportSkels=none;exportSkin=none;exportBlendShapes=0;exportColorSets=1;"
        "defaultMeshScheme=catmullClark;defaultUSDFormat=usdc;animation=1;eulerFilter=0;staticSingleSample=0;"
        "startTime={0};endTime={1};frameStride=1;frameSample=0.0;parentScope=;exportDisplayColor=0;shadingMode=none;"
        "exportInstances=1;exportVisibility=1;mergeTransformAndShape=1;stripNamespaces=1".format(
            start_frame, end_frame
        )
    )
```
There might be a few options you will want to change but test it out first. I'm guessing you are seeing the display color on the exported USD layer, this command should not have any "Look".

Cheers,

Jason Coelho

**Comment by SelivanovaLera** [comment]
Thank you, @jcoelho88. It works now)
