### ISSUE TITLE
mayaUsd.ufe.stagePath() returns incorrect value

### ISSUE THREAD

**Issue by willis102** [Autodesk/maya-usd#2765]
**Describe the bug**
When calling stagePath() and passing a UsdStage the returned value does not match the expected return value

**Steps to reproduce**
Run the following script:
```
import maya.cmds
import mayaUsd
import mayaUsd_createStageWithNewLayer

proxy_shape_path = mayaUsd_createStageWithNewLayer.createStageWithNewLayer()
print(f"Created stage at \"{proxy_shape_path}\"")
print(f"Parents query returns: {maya.cmds.listRelatives(proxy_shape_path, allParents=True)}")
stage = mayaUsd.ufe.getStage(proxy_shape_path)
stagePath_return = mayaUsd.ufe.stagePath(stage)
print(f"stagePath returned: \"{stagePath_return}\"")
print(f"Parents query returns: {maya.cmds.listRelatives(stagePath_return, allParents=True)}")
```

![image](https://user-images.githubusercontent.com/5922577/205482436-4edc131b-981e-42cd-9ed5-2e44961b90db.png)

Note that the string returned by `mayaUsd.ufe.stagePath()` is prepended by `|world` compared to the actual mayaUsdProxyShape path, and thus the call to `listRelatives()` raises an exception complaining that "No object matches name"

**Expected behavior**
`stagePath()` returns the DAG path to the mayaUsdProxyShape corresponding to the UsdStage passed to it.

**Specs (if applicable):**
Windows 10 / Maya 2022.3 / maya-usd 0.20.0 (python 3)

**Comment by willis102** [comment]
If I'm misunderstanding the purpose of `stagePath()` please let me know -- I've only found limited documentation / examples of the ufe module and realize this may just be operator error.

**Comment by seando-adsk** [comment]
@willis102 Thank you for reporting this as you have actually discovered a bug with the `stagePath()` method. It should be returning a Ufe path string which should not have "|world" in it.

@santosg87 Can you please log a new JIRA ticket for this.

Sean

**Comment by santosd** [comment]
I logged this internally as MAYA-126653.

**Comment by willis102** [comment]
Thanks @seando-adsk, @santosg87.  Will you update here as that internal ticket progresses?

**Comment by seando-adsk** [comment]
@willis102 I just merged the fix for this. Thanks for finding and reporting it.

**Comment by santosd** [comment]
I tested the merge on My end and now I am getting the correct path without mayaUsd.ufe.stagePath() returning a value that is prepended by |world. @willis102 could you build from the latest and give it a try to see if that works for you?

**Comment by willis102** [comment]
@santosd @seando-adsk Thank you and sorry for the delayed response on my part.  I just built `dev` and tested in Maya 2022.4 -- all looks good on my end, and the code posted above no longer raises an exception.  Thanks for the quick turnaround on this one, looking forward to the release!
