### ISSUE TITLE
Build Issue in windows10 and maya 2018

### ISSUE THREAD

**Issue by arunpillaii** [Autodesk/maya-usd#279]
The USD 19.11 with maya 2018 in windows 10 is failing with the below error.
 python build.py --maya-location "C:\Program Files\Autodesk\Maya2018" --pxrusd-location "C:\USD\19.11" "C:\USD\maya_usd\2018"

**Build log**
  test_usdmaya_AttributeType.cpp
  Unknown compiler version - please run the configure tests and report the results
     Creating library C:/USD/maya_usd/2018/build/RelWithDebInfo/plugin/al/plugin/AL_USDMayaTestPlugin/RelWithDebInfo/AL_USDMayaTestPlugin.lib and object C:/USD/maya_usd/2018/build/RelWithDebInfo/plugin/al/plugin/AL_USDMayaTestPlugin/RelWithDebInfo/AL_USDMayaTestPlugin.exp
  AL_USDMayaTestPlugin.vcxproj -> C:\USD\maya_usd\2018\build\RelWithDebInfo\plugin\al\plugin\AL_USDMayaTestPlugin\RelWithDebInfo\AL_USDMayaTestPlugin.mll

Traceback (most recent call last):
  File "build.py", line 584, in <module>
    BuildAndInstall(context, context.buildArgs, context.stagesArgs)
  File "build.py", line 354, in BuildAndInstall
    RunCMake(context, extraArgs, stagesArgs)
  File "build.py", line 266, in RunCMake
    multiproc=FormatMultiProcs(context.numJobs, generator)))
  File "build.py", line 156, in Run
    .format(cmd=cmd, log=os.path.abspath(context.logFileLocation)))
RuntimeError: Failed to run 'cmake --build . --config RelWithDebInfo --target install -- /M:8'
See C:\USD\maya_usd\2018\build\RelWithDebInfo\build_log.txt for more details.
[build_log.txt](https://github.com/Autodesk/maya-usd/files/4192550/build_log.txt)
**Specs:**
 - OS & version [e.g. Windows 10]
 - Maya version 2018

**Comment by fowlertADSK** [comment]
I'm not 100% sure about the "Unknown compiler version" error you're getting, but you need to use the compiler version that matches the version of Maya you are building against.  I believe Maya 2018 and 2019 both used Visual Studio 2015, not 2017, so I think you're going to have to switch (the Build docs were updated recently to hopefully make this more clear).  Give that shot and see if it helps.

**Comment by HamedSabri-adsk** [comment]
Hi @arunpillaii  
Please do the following steps:

1- Grab this PR  https://github.com/Autodesk/maya-usd/pull/283
2- Set PXR_STRICT_BUILD_MODE to OFF

The compiler error ( dst_rules.hpp(330): error C2220: warning ) you are getting is a known issue and is related to boost.

Please see my comment in https://github.com/Autodesk/maya-usd/issues/233

**Comment by HamedSabri-adsk** [comment]
@arunpillaii can you close this ticket if you longer see any issues? Thanks.
