### ISSUE TITLE
Difference with UI "export selected" and python command

### ISSUE THREAD

**Issue by sanders3d** [Autodesk/maya-usd#2795]
I'm trying to export an animation where I don't want to include "Looks" as the material assignment is overriding the asset when I use it. So this works when I use "export selected" and maya uses this MEL command to export

`file -force -options ";exportUVs=1;exportSkels=none;exportSkin=none;exportBlendShapes=0;exportDisplayColor=0;;exportColorSets=0;exportComponentTags=1;defaultMeshScheme=catmullClark;animation=1;eulerFilter=0;staticSingleSample=0;startTime=1;endTime=120;frameStride=1;frameSample=0.0;defaultUSDFormat=usdc;parentScope=/ASSET;shadingMode=none;exportInstances=1;exportVisibility=0;mergeTransformAndShape=1;stripNamespaces=1;materialsScopeName=mtl" -typ "USD Export" -pr -es "/tmp/test/anim.usdc";`

If I translate this into python to export (so I can have a fighting chance to implement it as a tool). And "exportRoots" is only available when using the pyhon command.

```
import maya.cmds as cmd

path = "/tmp/test"

cmd.mayaUSDExport(
    file="{}/anim.usdc".format(path),
    exportRoots="fake_rig:geometry_grp",
    exportUVs=True,
    exportSkels=None,
    exportSkin=None,
    exportBlendShapes=False,
    exportDisplayColor=False,
    exportColorSets=False,
    exportComponentTags=True,
    defaultMeshScheme="catmullClark",
    eulerFilter=False,
    staticSingleSample=False,
    frameRange=( 1.0, 120.0),
    defaultUSDFormat="usdc",
    parentScope="/ASSET",
    shadingMode=None,
    exportInstances=True,
    exportVisibility=False,
    mergeTransformAndShape=True,
    stripNamespaces=True,
    materialsScopeName="mtl",
)
```
The difference here is that the python command actually exports the shading where as the UI/MEL command doesn't. I've tried countless variations of the Python command but I can't figure out how to export without material assignments. If I remove materialsScopeName="mtl" it creates a Scope called "Looks" and the materials are exported. 

maya_usd: 0.20 (linux)
Maya 2023.3 (linux)

regards
stefan

**Comment by santosd** [comment]
Thanks for reporting the answer @sanders3d I will go ahead and close this one out. Let us know if anything else comes up.
