### ISSUE TITLE
failing to build ADSK USD plugin

### ISSUE THREAD

**Issue by DanEnglesson** [Autodesk/maya-usd#28]
Hi,

I'm trying to build maya-usd with the following settings:
branch: refactoring_sandbox
USD version: 19.05
OS: Centos7
maya version: 2018
Using cmake3

Most of it builds fine, but I'm currently getting errors when building the ADSK USD plugin where it fails on a strongly typed enum if I'm reading this correctly. See build log here: [build_log.txt](https://github.com/Autodesk/maya-usd/files/3530615/build_log.txt)

This is how I've built it if it might help debug this:

**build steps USD-core:**
```bash
export USD_VERSION=19
export USD_ROOT=/usr/local/USD.$USD_VERSION
export tbb_os=linux
python build_usd.py -v -v --build-args boost,"--with-date_time --with-thread --with-system --with-filesystem" --no-maya $USD_ROOT/USD-core
```
**build steps maya-usd:**
```bash
python build.py --maya-location /usr/autodesk/maya2018 --pxrusd-location /usr/local/USD.19/USD-core /usr/local/workspace -v 3 --install /usr/local/USD.19/maya-usd
```

Any help would be much appreciated.
Many thanks,
Dan

**Comment by HamedSabri-adsk** [comment]
@DanEnglesson  what version of gcc are you using?

**Comment by DanEnglesson** [comment]
Hi,
Thanks for the reply. Good point, I checked the version and it said 7.3.1, using scl enable devtoolset-7. But looking closer at the log I saw that it actually picked up devtoolset-6. Removed it and it now picks up the correct version, however, I'm still getting the same error as you can see in the log.

[build_log.txt](https://github.com/Autodesk/maya-usd/files/3533396/build_log.txt)
```
gcc --version
gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
```

**Comment by DanEnglesson** [comment]
Hi,

Has anyone been able to build this on Centos 7 and maya 2018 with refactoring_sandbox branch?

I Seem to be able to build with master, but not with the refactoring_sandbox branch. To me it seems like there are some includes that are stomping on each-other but I haven't been able to figure it out yet. Any ideas?

Some info on the build process.
cmake3 version 3.13.5

``` bash
scl enable devtoolset-7
git checkout tags/v19.05
python build_usd.py -v -v --build-args boost,"--with-date_time --with-thread --with-system --with-filesystem" --no-maya /usr/local/USD.19/USD-core
```

``` bash
scl enable devtoolset-7
git checkout refactoring_sandbox
python build.py --maya-location /usr/autodesk/maya2018 --pxrusd-location /usr/local/USD.19/USD-core /usr/local/workspace -v 3 --install /usr/local/USD.19/maya-usd 
```

Cheers,
Dan

**Comment by seando-adsk** [comment]
@DanEnglesson Can you post the error from your build log.

**Comment by seando-adsk** [comment]
I don't think any of us has tried using devtool-7. We all use 6. Can you try with 6 instead?

Looking at your build log, my guess is that some other header being included has defined "Always" to be something else. We've seen these kind of errors before. What we've done is something like this:

#ifdef Always
#undef Always
#include <header that has problems>
#endif

**Comment by DanEnglesson** [comment]
Hi Sean thanks for the quick reply!

I tried building with 6 instead; getting the same error;
[build_log.txt](https://github.com/Autodesk/maya-usd/files/3541478/build_log.txt)

Will try the #idef fix. Not sure where that define would come from though.

**Comment by DanEnglesson** [comment]
Thanks for the help debugging this. The registeredVariantSet is brought in from pipeline.h so setting #ifdef Always
#undef Always
#endif
above it in referenceAssembly.cpp made it compile correctly.

Many thanks!
Dan

**Comment by kxl-adsk** [comment]
@DanEnglesson Can this be closed?

**Comment by DanEnglesson** [comment]
Yes, thanks for the help. It built fine with the ifdef fix.

Cheers,
Dan
