### ISSUE TITLE
[MAYA-127101] VP2 crashes when rendering pointInstancer with unused prototypes since maya-usd 0.21

### ISSUE THREAD

**Issue by jufrantz** [Autodesk/maya-usd#2812]
**Describe the bug**

Using maya-usd 0.21.0, we are experiencing maya crashes when VP2 rendering USD pointInstancers.
They occur when the pointInstancer has at least an invisible prototype, such as when it does not appear in `protoIndices` attrib. 
This is a very typical case in our production scenes.

**Steps to reproduce**

1. Execute following python script in maya. It will create a maya-usd proxyShape, its stage is definining a pointInstancer with an unused prototype (`Sphere`)
```python
import pxr.Sdf
import maya.cmds

# Create a layer defining a PointInstancer with 2 prototypes but only Cube is used.
layer = pxr.Sdf.Layer.CreateAnonymous(".usd")
layer.ImportFromString("""#usda 1.0
def PointInstancer "PI"
{
    point3f[] positions = [(0, 0, 0), (2, 0, 2), (2, 0, -2), (-2, 0, -2), (-2, 0, 2)]
    int[] protoIndices = [1, 1, 1, 1, 1]
    rel prototypes = [</PI/Protos/Sphere>, </PI/Protos/Cube>]

    def Scope "Protos"
    {
        def Sphere "Sphere" 
        {
        }
        
        def Cube "Cube"
        {
        }
    }
}""")

# Render the stage using maya-usd proxShape
maya.cmds.loadPlugin("mayaUsdPlugin", quiet=True)
proxyShape = maya.cmds.createNode("mayaUsdProxyShape")
maya.cmds.setAttr(".filePath", layer.identifier, type="string")
```

2. Notice the crash, in our case a floating point exception is raised.

**Expected behavior**
VP2 should render the 5 instanced cubes without crash.

**Specs (if applicable):**
 - CentOS 7.8
 - gcc 9.3
 - maya 2022.4 / maya 2023.3
 - maya-usd 0.21.0
 - USD 22.11

**Additional context**
- With maya-usd 0.20, the crash does not occur.
- When all protos of pointInstancers are used, the crash does not occur.

**Comment by santosg87** [comment]
after a bit of investigating on this, this seems to be specific to the first item on the index array. if i have the same setup - but with only the sphere as my prototype, i don't get a crash.

it might be an issue with indexing needing to have 0 on the array in order to find the beginning of the index for the prototypes.

**Comment by jufrantz** [comment]
Thank you @santosg87 for the clarification.
FWIW we applied this patch on our side as workarround:
``` diff
--- a/lib/mayaUsd/render/vp2RenderDelegate/mayaPrimCommon.cpp
+++ b/lib/mayaUsd/render/vp2RenderDelegate/mayaPrimCommon.cpp
@@ -836,7 +836,8 @@ void MayaUsdRPrim::_SyncSharedData(
 
     // If instancer is dirty, update instancing map
     if (HdChangeTracker::IsInstancerDirty(*dirtyBits, id)) {
-        bool instanced = !refThis.GetInstancerId().IsEmpty();
+        bool instanced = !refThis.GetInstancerId().IsEmpty() 
+            && !delegate->GetInstanceIndices(refThis.GetInstancerId(), id).empty());
 
         // UpdateInstancingMapEntry is not multithread-safe, so enqueue the call
         _delegate->GetVP2ResourceRegistry().EnqueueCommit([this, id, instanced]() {
```

**Comment by santosg87** [comment]
@jufrantz awesome, good to know!

from more info on other issues, this might be something on the pixar USD code. #2804 has a very similar crash to yours, although hitting it from a different code path. 

someone pointed out they logged a bug with pixar already https://github.com/PixarAnimationStudios/USD/issues/2149

**Comment by santosg87** [comment]
@jufrantz given that you have a workaround for the crash - would that be something you would want to contribute the code base? feel free to push a PR for it if you'd like :)

**Comment by DanEnglesson** [comment]
We are still hitting this in:
```
Centos 7.9
maya 2022.4
maya-usd 0.23.0
Own build of USD 21.11
```
Works fine in usdview. What is the status of this bug? It says in MAYA-126933 that this is fixed too but seems like it is not.

**Comment by jufrantz** [comment]
We tested it with maya-usd 0.25 and this is fixed on our side. 
Thank you.
