### ISSUE TITLE
[MAYA-104542] proxyShape does not draw nodes with assigned purpose

### ISSUE THREAD

**Issue by ablev-dwa** [Autodesk/maya-usd#285]
**Describe the bug**
Any USD prim that has a purpose (proxy, render, guide) does not draw in VP2 as a proxyShape using the dev branch build of maya-usd

**Steps to reproduce**
1. usdMaya_CreateUsdProxyShape;
2. Select triangle_proxy.usd
3. It doesn't draw in VP2
4. usdMaya_CreateUsdProxyShape;
5. Select triangle_nopurpose.usd
6. It renders fine in VP2

[triangles.zip](https://github.com/Autodesk/maya-usd/files/4202146/triangles.zip)

**Expected behavior**
Whatever purposes are selected on the proxyShape node should be displayed in VP2

**Specs (if applicable):**
 - Linux CentOS7
 - Maya 2020 (released version)
 - maya-usd commit 567b470a34e690b71adb84ae5628c81ff944697c

**Comment by mattyjams** [comment]
Hey @ablev-dwa! :)

I'm assuming this is when using the VP 2.0 render delegate (`HD_VP2_RENDER_DELEGATE=1`)? If you set `HD_VP2_RENDER_DELEGATE=0`, which should switch you to using the Pixar batch renderer, do you see purpose being respected?

I suspect this may be either related to or the same issue as #261 that we ran into when starting to test the new render delegate.

**Comment by ablev-dwa** [comment]
Ah yes! Setting ```HD_VP2_RENDER_DELEGATE=0``` gets everything to appear. I assumed that was important since it was set in usdMaya.mod but I don't really know what I'm doing here so I didn't think to change it. All of our geometry has a purpose so I was pretty confused when nothing was showing up! Thanks @mattyjams

**Comment by kxl-adsk** [comment]
Indeed this looks very similar to #261. We currently don't support render tags in VP2RenderDelegate, but it should be something not too hard to add given we use HdEngine for the population of VP2 render items.

**Comment by santosd** [comment]
Took a look at this in PR113 and am able to reproduce the issue which doesn't show the proxy with purpose. However, setting the `HD_VP2_RENDER_DELEGATE=0` env doesn't work for me. Switching to Hydra as the renderer in the viewport doesn't work either. @kxl-adsk I am wondering do I need to have the pxr usd plugin installed for that to work?

**Comment by mattyjams** [comment]
Hey @santosd, sorry for the confusion. I'm not sure where I pulled that variable name from, maybe mistakenly from a lazy grep that found an include guard rather than the actual env var name, but it should have been:

`VP2_RENDER_DELEGATE_PROXY=0`

Since the Pixar batch renderer moved to mayaUsd, I don't *think* you'll need the pxr plugin built.

**Comment by santosg87** [comment]
@santosd this one can be reproduced in maya as well, but it takes a few more steps. :)
you can see this behavior by selecting the "triangle" prim and changing the purpose on the AE in maya. note that you might need to run "ogs -reset", as it you will need to force the viewport to update to see the changes. 

I can reproduce this as well on the latest Maya beta. the only purpose that seems to draw on the viewport is "default".

**Comment by santosg87** [comment]
![nodraw_purpose](https://user-images.githubusercontent.com/3026529/76794535-96750800-679d-11ea-8daa-7d080197a7c3.gif)

**Comment by santosd** [comment]
Thank you @mattyjams and @santosg87 for the help in replicating.

**Comment by kxl-adsk** [comment]
@ablev-dwa PR #517 and PR #558 should have fixed it. Can you validate and close this issue?

**Comment by ablev-dwa** [comment]
That is great news, thanks! I'll make a new build and try it out and report back.

**Comment by ablev-dwa** [comment]
I can now see geometry with an assigned purpose.
Verified on PR115 and a build from today's dev branch.
