### ISSUE TITLE
[MAYA-127818] Incorrect rest transform for joints that are not skinned (when exporting scene to USD)

### ISSUE THREAD

**Issue by ChristophePlourde** [Autodesk/maya-usd#2857]
**Describe the bug**
Hello!
I stumbled across a bug regarding rest transform when a joint is not skinned. It happens when exporting the scene from maya to usd file. Since their bind pose is identity, the resulting rest transform (skel:resttransform usd attribute) is the inverse of their parent joint bind transform. I would expect the rest transform to be the local deformation, kind of like how non-skinned bones keep their local transform when we put the asset in "Go to Bind Pose".
The following example will make this issue clearer.

**Steps to reproduce**

1. Extract the zip file
2. Open the scene "cylinder-new-bones.mb" in maya. Notice that "new_bone_long" and "new_bone_short" don't have bind pose.
![image](https://user-images.githubusercontent.com/54908966/215872491-a990cab4-8bff-4d26-b9d5-aab7f677f176.png)

3. Export all to usd (example result in cylinder-new-bones.usda)
4. Open the asset in USD view, you can see that the bones are not properly displayed.
![image](https://user-images.githubusercontent.com/54908966/215872248-be77bb02-0263-44c8-86f2-5df8d955e997.png)
The bone "new_bone_short" is invisible. You can also see that the rest transform of "new_bone_long" is the inverse of the bind transform of its parent ("cylinder_joint3"):
![image](https://user-images.githubusercontent.com/54908966/215886915-204320b8-edb0-4e4b-917d-a5fc02dbd6ae.png)
And, the rest transform of "new_bone_short" is identity (because its parent, "new_bone_long", as an identity bind transform).
![image](https://user-images.githubusercontent.com/54908966/215887111-d9c959a1-0d9c-4952-94dc-267efa8136b7.png)

5. Clear your maya scene.
6. Import the usd file you created previously.
7. Notice that the bones are not displayed like they were on import.
![image](https://user-images.githubusercontent.com/54908966/215873090-a20881a4-1a99-4683-a08e-cb9471d84199.png)

**Expected behavior**
I would expect the rest transform to be the local transform of the joints, as seen in "cylinder-new-bones.mb". This way, the scene obtained by importing "cylinder-new-bone.usda" would be the same as "cylinder-new-bones.mb". The expected usda file is then "cylinder-new-bones-expected.usda".

This second point is debatable: I would also expect the bones to be properly displayed in usdview, but that would require defining a value other than identity for the bind pose of a non-skinned joint. I am mentioning it in case you agree and want to change it, but I don't necessarily consider it a bug.

**Attachments**
Here is the zip:
[cylinder-files.zip](https://github.com/Autodesk/maya-usd/files/10551152/cylinder-files.zip)
Only "cylinder-new-bones.*" are used in the steps to reproduce, but I linked the other files in case they are usefull for the investigation. What I did to obtain "cylinder-new-bones.usda" is: "cylinder.mb" -> "cylinder.usda" -> import and edit to get "cylinder-new-bones.mb" -> "cylinder-new-bones.usda".

**Specs (if applicable):**
 - Windows 10
 - Maya 2022.4
 - Maya USD 0.20.0

Thank you in advance!

**Comment by santosg87** [comment]
@ChristophePlourde thanks for reporting this. USDskel support is still limited, so this might be something we need better implementations entirely. 

I logged an issue internally so we can investigate a bit deeper and figure out next steps on this! :)

**Comment by ChristophePlourde** [comment]
Thank you for the update!
