### ISSUE TITLE
[MAYA-127817] mayaUsdProxyShape fails to load the stage when reopening the previous saved maya file with stage loaded by mayaUsdProxyShape via stageID.

### ISSUE THREAD

**Issue by NickWu** [Autodesk/maya-usd#2872]
**Describe the bug**
Hi, I found mayaUsdProxyShape fails to load the stage when opening the previous saved maya file with stage loaded by mayaUsdProxyShape via stageID. 

**Steps to reproduce**
1. Run the following code to load the a simple attached USD file:
code:
```python
from pxr import Usd, UsdUtils
from mayaUsd import lib as mayaUsdLib 
from maya import cmds 

filePath = './sphere.usda'

stageCache = UsdUtils.StageCache.Get()
with Usd.StageCacheContext(stageCache):
    cachedStage = Usd.Stage.Open(filePath)
    
stageId = stageCache.GetId(cachedStage).ToLongInt()
shapeNode = cmds.createNode('mayaUsdProxyShape')
cmds.setAttr('{}.stageCacheId'.format(shapeNode), stageId)
```

2. Save the maya file and open a new scene. 
3. Open the saved maya file.
4. You will see mayaUsdProxyShape, but stage is not loaded. 

I think the root cause for this maybe because when mayaUsdProxyShape opens a stage via stageID, so the maya file is saved with mayaUsdProxyShape only has stageID. When reopening the saved maya file, the stageID that mayaUsdProxyShape has would become invalid. 

I found AL_usdmaya_ProxyShape doesn't have this issue because it sets the filePath attribute when the stage is opened via stageID:
https://github.com/Autodesk/maya-usd/blob/d462ff20f9bc9c2eab24183a4d5497d5fab0dc25/plugin/al/lib/AL_USDMaya/AL/usdmaya/nodes/ProxyShape.cpp#L1245
When reopening the saved maya file, AL_usdmaya_ProxyShape would then be able to load the stage via filePath attribute. 

**Expected behavior**
mayaUsdProxyShape should be able to load the stage when reopening from the saved maya file again even the stage was loaded via stageID.

**Attachments**
sphere.usda file:
```usd
#usda 1.0
(
)

def Sphere "pSphere"
{
    double3 xformOp:translate = (0, 1, 0)
    uniform token[] xformOpOrder = ["xformOp:translate"]
}
```

**Specs (if applicable):**
 - OS & version : CentOS 7.8
 - Compiler & version : GCC 9.3.1
 - Maya version: Maya-2023.2.0-11.0.PFIX & Maya 2022.4.0-24.0.PFIX
 - Maya USD commit SHA: latest dev at https://github.com/Autodesk/maya-usd/commit/4bbc17f27d79e35d70536d3779086ffcf27594f7
 - Pixar USD: official 22.11

**Comment by santosg87** [comment]
@NickWu thanks for reporting this. I am also able to reproduce this on our side. I logged it internally as MAYA-127817 as we investigate more and figure out the next steps on this issue.

**Comment by santosg87** [comment]
@NickWu we are trying to understand the usage on this workflow a bit better. using the stageCache to load a stage is not quite recommended, since nothing gets written to disk - would you be able to give us a bit more info on the usage for you guys?

we have an internal issue to track any work needed for this, but it is not a high priority issue for the time being.

Cheers!

**Comment by NickWu** [comment]
Hey @santosg87 , thank you for taking a look. 

At Animal Logic, before creating a proxy shape, our pipeline would load a stage with Load Rule set to `Usd.Stage.LoadNone` so that payloads are not loaded. For instance:
```python
SC = UsdUtils.StageCache.Get()
with Usd.StageCacheContext(SC):
    cachedStage = Usd.Stage.Open(usdfilePath, load=Usd.Stage.LoadNone)
```
This way, our tool can show loaded prims in a GUI and artists can select which prims they want to load into the proxy shape before loading any heavy payloads as sometimes artists don't want to see everything in a stage. Once artists have decided, our pipeline tool would build the stage (load the payloads, only the ones artists want to work with, by calling `cachedStage.SetLoadRules(loadRules)`) and create the proxy shape with the stageID retrieved from the stage cache. 

Hope that makes sense.

**Comment by pierrebai-adsk** [comment]
@NickWu Is there any reason why you could not provide the stage via the proxy shape `filePath` attribute? Is it because the stage is not in the MayaUSD cache and the proxy shape would not find the stage in the cache?

Also, the MayaUSD proxy shape has a `loadPayloads` boolean attribute which can be set to false to not load any payload. Would that not be a simpler approach than the pre-load you are doing?

**Comment by NickWu** [comment]
Hi @pierrebai-adsk , at first, I thought I could use the following approach to use `Usd.StageCacheContext` to force mayaUsdProxyShape's filePath open to use the existing opened stage in the cache instead of opening a new stage with the same file path: 
```python
SC = UsdUtils.StageCache.Get()
with Usd.StageCacheContext(SC):
    shapeNode = cmds.createNode('mayaUsdProxyShape')
    cmds.setAttr('{}.filePath'.format(shapeNode), cachedStage.GetRootLayer().identifier, type='string') 
   
print(SC.GetAllStages())  # we would have two stages 
```
But it didn't work as the proxy shape still opened another new stage judging from the SC.GetAllStages() call. However, I found I could set the proxy shape's `stageCacheId` attribute first followed by setting `filePath` attribute and it'd work: 
```python
SC = UsdUtils.StageCache.Get()
with Usd.StageCacheContext(SC):
    shapeNode = cmds.createNode('mayaUsdProxyShape')
    cmds.setAttr('{}.stageCacheId'.format(shapeNode), stageId)
    cmds.setAttr('{}.filePath'.format(shapeNode), cachedStage.GetRootLayer().identifier, type='string') 
   
print(SC.GetAllStages())  # we would now have only one stage!
```
With this approach, filePath will be saved with the Maya file and it'd be working fine when reopening the saved file again.

**Comment by NickWu** [comment]
Hi @pierrebai-adsk , I notice this PR https://github.com/Autodesk/maya-usd/pull/3010 has been merged which address the issue related to the conversation here. Therefor, I'll close this issue now. Thank you for looking into it.
