### ISSUE TITLE
[MAYA-127812] MaterialX export uses MayaND_ prefixes on texture nodes

### ISSUE THREAD

**Issue by dgovil** [Autodesk/maya-usd#2874]
**Describe the bug**
When exporting a scene with USDPreviewSurface converted to MaterialX on export, the exported asset includes several nodes with a non-standard MaterialX definition, e.g `MayaND_fileTexture_color3` instead of `ND_Image_color3`.

This makes it so other MaterialX editors don't really know what to do with these assets, so the models end up not being able to be used anywhere except Maya. e.g when used in Storm, they just render grey shaded since the materialx libraries don't know what this is.

It would be great to replace all the uses of MayaND with equivalent vanilla MaterialX node names to make this usable in non Maya contexts.

See the attached USDZ as an example where I think all the `MayaND` nodes could be replaced with standard node types.

**Specs (if applicable):**
 - Maya version Maya 2023.2
 - Maya USD commit SHA 4bbc17f27d79e35d70536d3779086ffcf27594f7

[plane_matx.usdz.zip](https://github.com/Autodesk/maya-usd/files/10711506/plane_matx.usdz.zip)

**Comment by swillisart** [comment]
I agree with this. My main intent and interest with MaterialX are harnessing a "Portable Shader Graph" where it can represent an agnostic, editable graph that can be retranslated faithfully across renderers and applications. To Dhruv's point it's not really useful only having nodes exclusive to the application / renderer that wrote it out.
 
I could be wrong, but the current design of application-specific nodes seems to go against the problem space that both MaterialX and USD are designed to address.

**Comment by dgovil** [comment]
Also, while looking through the `maya_utilties_ng.mtlx` , I do see that the MayaND nodes have parameters not present on the roughly equivalent `ND_image_float` node. 

That said, perhaps there's room to make things more portable? I'm just thinking out loud, but a few things came to mind.


1) If the attributes in question aren't used, maybe it could fallback to the vanilla Image node?
2) Some of the attributes might be handled by math nodes external to the Image node: e.g invert should be doable with a math node
3) Maybe some kind of compatibility option on export to make sure the exports only use the materialx nodes specified in the vanilla library?

**Comment by santosg87** [comment]
after some discussion on scope, this issue is not something we are planning on working on for the time being. 

for the purposes of maintaining the backlog, we are marking this as closed. if this issue changes priorities or proves to cause other problems, we can re-open it when revisiting. :)

**Comment by dgovil** [comment]
Understood. I have something going locally that I'll post as a PR in the coming months which hopefully will be considered. 

Basically it  will introduce a compatibility mode so that users can choose between compatibility or maya nodes.
