### ISSUE TITLE
[MAYA-127905] Lasso selection does not support USD prims

### ISSUE THREAD

**Issue by gracekumagai** [Autodesk/maya-usd#2893]
**Describe the bug**
Lasso selection does not support USD prims, only native maya nodes.

**Steps to reproduce**
1. Open `Kitchen_Set_instanced` or `Kitchen_set`
2. Click on "Lasso Selection" tool
3. Try to select USD prims in the outliner. Notice that nothing is selected. However, if you try to select native maya nodes, they are selected as expected.

**Expected behavior**
We'd expect the Lasso Selection tool to work with USD prims.

**Attachments**
![lassoSelection](https://user-images.githubusercontent.com/12554015/220493957-af669f6e-67ad-4789-8095-429b669aedd1.gif)

**Specs (if applicable):**
 - OS & version Linux
 - maya2023.update2
- maya-usd commit sha (dev at https://github.com/Autodesk/maya-usd/commit/abf29285ab463b87e89d56a22631afb2ae605a63)

Pixar Internal JIRA MAYA-3586

**Comment by santosg87** [comment]
Hi @gracekumagai!

thank you for reporting this!
I believe this is just a lack of support for the tool. we never made the lasso tool UFE aware, so as far as maya understands there's nothing there to select. :) i will log something internally so we can track the work, but this would most likely fall into an improvement request to add the proper support :)

**Comment by santosd** [comment]
Hi @gracekumagai, Just wanted to let you know that we recently added support for this. However, this is a Maya specific change so it will be coming out with the next release of Maya. It could also be something to contact the consulting team about. Let me know if you have any questions. We did internal testing on this so going to go ahead and close it for now.

**Comment by gracekumagai** [comment]
Thank you for the update @santosd!

**Comment by dj-mcg** [comment]
Hi @santosd - what version of Maya can we expect this to work in? Thanks

**Comment by santosg87** [comment]
the fix here required changes in the maya code to make the lasso tool UFE aware - so the fix should be available on Maya 2024.2 builds :)
