### ISSUE TITLE
shadingMode is exported even when defined as None

### ISSUE THREAD

**Issue by sanders3d** [Autodesk/maya-usd#2920]
Hello,
It seems that the python command is exporting material bindings even if I try and tell it to not do this. I have a test character which as some preview material assigned to it. But I just want to export the animated mesh and not the shading.

```
import maya.cmds as cmds

cmds.mayaUSDExport(
    file="/tmp/test.usdc",
    exportRoots=cmds.ls(sl=True),
    exportDisplayColor=False,
    shadingMode=None,
    frameRange=( 1.0, 10.0),
    mergeTransformAndShape=True,
    verbose=True,
    materialsScopeName="mtl",
    parentScope="/ROOT/geo",
    renderableOnly=True,
)
```

This will still export with Shading and override it when I layer the animation onto the lookdev asset. Even if I can force the layers with specific opinion index, I don't want to export with shading assignments. The lookdev contains both preview and render assignments.

Any idea on how to get around this?

regards
stefan

**Comment by santosd** [comment]
Hi @sanders3d ,
The following command worked for me:
`import maya.cmds as cmds

cmds.mayaUSDExport(
    file="C:/tmp/testNoMat.usda",
    exportRoots=cmds.ls(sl=True),
    exportDisplayColor=False,
    shadingMode='none',
    frameRange=( 1.0, 10.0),
    mergeTransformAndShape=True,
    verbose=True,
    materialsScopeName="mtl",
    parentScope="/ROOT/geo",
    renderableOnly=True,
)`

Let me know if that works for you.

**Comment by sanders3d** [comment]
Ahhh.. so the difference was

`shadingMode='none'`

vs

`shadingMode=None`

I would not have figured that out. 

thank you
stefan

**Comment by santosd** [comment]
Yes, that was the only difference. No problem at all.
