### ISSUE TITLE
When executing "Merge Maya Edits to USD" to convert an animated Maya object back to USD, the converted prim is not animating

### ISSUE THREAD

**Issue by NickWu** [Autodesk/maya-usd#2947]
**Describe the bug**
Hi, I found when executing **"Merge Maya Edits to USD"** to convert an animated Maya object back to USD, the converted prim is not animating even though we can see animation data is present in USD. 

**Steps to reproduce**

1.Executing the following code to load the attached USD file `mesh.usda` in a proxy shpae:
```python
from maya import cmds
from mayaUsd import lib as mayaUsdLib

filePath = '/path/to/your/directory/mesh.usda'
shapeNode = cmds.createNode('mayaUsdProxyShape')
cmds.setAttr('{}.filePath'.format(shapeNode), filePath, type='string')
stage = mayaUsdLib.GetPrim(shapeNode).GetStage()
stage.SetEditTarget(stage.GetSessionLayer())
```

2. Select `box` prim then right-click run **"Edit As Maya Data"**. 
<img width="500" alt="Screenshot 2023-03-15 at 15 57 45" src="https://user-images.githubusercontent.com/935278/225461671-d6298491-2e93-4236-9131-5f5d650a3a55.png">

3. Set some keyframes (in this example, I set 3 keyframes at frame 0, 8 and 16) to the converted maya object `box`. 
<img width="800" alt="Screenshot 2023-03-15 at 15 59 50" src="https://user-images.githubusercontent.com/935278/225462092-d670641c-234e-4d21-b3b8-ab907530931b.png">

4. Right-click run **"Merge Maya Edits to USD"** to convert it back to USD. Make sure Animation Data checkbox is checked in the Merge Maya Edits to USD Option Window:
<img width="800" alt="Screenshot 2023-03-15 at 16 03 07" src="https://user-images.githubusercontent.com/935278/225462461-dc5398a4-228b-4b1c-8d14-2f7674b0aa5a.png">

5. Scroll the Maya Timeline, you will see the `box` prim is not moving. Run the following code to check its edit target layer: 
```python
print(stage.GetEditTarget().GetLayer().ExportToString())
```
And you will see the animation data does exist in USD: 
```
#usda 1.0

over "root"
{
    over "house"
    {
        over Xform "box" (
            kind = "group"
        )
        {
            double3 xformOp:translate.timeSamples = {
                0: (0, 0, 0),
                1: (0, 0.10914582280246332, 0.10953786303172755),
                2: (0, 0.39689390109986655, 0.405522236480267),
                3: (0, 0.8037101497272299, 0.8390092968756535),
                4: (0, 1.270060483519573, 1.361055220747922),
                5: (0, 1.7364108173119164, 1.9227161846271084),
                6: (0, 2.1432270659392794, 2.475048365043247),
                7: (0, 2.4309751442366827, 2.9691079385263732),
                8: (0, 2.5401209670391465, 3.355951081606521),
                9: (0, 2.430975144236683, 3.6722748986491545),
                10: (0, 2.1432270659392794, 3.9804198853061044),
                11: (0, 1.7364108173119166, 4.269907305036959),
                12: (0, 1.270060483519573, 4.5302584213013075),
                13: (0, 0.8037101497272305, 4.750994497558739),
                14: (0, 0.39689390109986666, 4.9216367972688415),
                15: (0, 0.10914582280246377, 5.0317065838912045),
                16: (0, 0, 5.070725120885417),
            }
            uniform token[] xformOpOrder = ["xformOp:translate"]

            def Mesh "Mesh1" (
                kind = "component"
            )
            {
                int[] primvars:displayColor:indices = [0]
            }
        }
    }
}
```
Additionally, I notice the animation data (timesamples) is at every frame rather than at the frames I set keys in Maya. Do you know whether it's possible to have timesamples reflect the keyframes in Maya? 

**Expected behavior**
When executing **"Merge Maya Edits to USD"** to convert an animated Maya object back to USD, the converted prim should have the same animation and movement as it did when it was a Maya native object. 

**Attachments**
`mesh.usda`
```
#usda 1.0

def Xform "root"
{
    def Xform "house" (
        kind = "environment"
    )
    {
        def Xform "box" (
           kind = "group"
        )
        {
            def Mesh "Mesh1" (
                kind = "component"
            )
            {
                float3[] extent = [(-0.5, -0.5, -0.5), (0.5, 0.5, 0.5)]
                token faceVaryingLinearInterpolation = "all"
                int[] faceVertexCounts = [4, 4, 4, 4, 4, 4]
                int[] faceVertexIndices = [0, 1, 3, 2, 2, 3, 5, 4, 4, 5, 7, 6, 6, 7, 1, 0, 1, 7, 5, 3, 6, 0, 2, 4]
                token interpolateBoundary = "edgeOnly"
                point3f[] points = [(-0.5, -0.5, 0.5), (0.5, -0.5, 0.5), (-0.5, 0.5, 0.5), (0.5, 0.5, 0.5), (-0.5, 0.5, -0.5), (0.5, 0.5, -0.5), (-0.5, -0.5, -0.5), (0.5, -0.5, -0.5)]
                color3f[] primvars:displayColor = [(0.13320851, 0.13320851, 0.13320851)]
                texCoord2f[] primvars:st = [(0.375, 0), (0.625, 0), (0.625, 0.25), (0.375, 0.25), (0.625, 0.5), (0.375, 0.5), (0.625, 0.75), (0.375, 0.75), (0.625, 1), (0.375, 1), (0.875, 0), (0.875, 0.25), (0.125, 0), (0.125, 0.25)] (
                    interpolation = "faceVarying"
                )
                int[] primvars:st:indices = [0, 1, 2, 3, 3, 2, 4, 5, 5, 4, 6, 7, 7, 6, 8, 9, 1, 10, 11, 2, 12, 0, 3, 13]
            }
        }
     }  
}
```

**Specs (if applicable):**
- OS & version: CentOS 7.8
- Compiler & version: GCC 9.3.1
- Maya version: Maya-2023.2.0-11.0.PFIX
- Maya USD commit SHA: latest dev at https://github.com/Autodesk/maya-usd/commit/91a5ff052dae1d3f3c8acc9aac0e3d4cfe64fe60

**Comment by jcoelho88** [comment]
Hi @NickWu 

I took a look and the "mayaUsdProxyShape" is missing a connection.

Add this line to your script after you create the node.

```python
cmds.connectAttr('time1.outTime', '{0}.time'.format(shapeNode))
```

I've tested with your exact steps and the block will animate after you set the connection.

Cheers,

Jason Coelho

**Comment by NickWu** [comment]
Thank you for looking into it. Yeah, I realised I'd need to plug in time node as well.
