### ISSUE TITLE
Rename operation spans references and inherits

### ISSUE THREAD

**Issue by dj-mcg** [Autodesk/maya-usd#2953]
**Describe the bug**
Rename operations fail when applied to a prim that references a show asset because the rename operation is attempted on the reference and classes it inherits.

**Steps to reproduce**
1. Create a test asset that inherits from one or more classes
2. Create a prim within a Maya Usd scene that references this asset
3. Attempt to rename the prim
4. Observe the failure due to Sdf policy

**Expected behavior**
The rename operation only applies to the defined prim in the authoring layer and any overs in session layers.

**Specs (if applicable):**
 - Linux RHEL 7.9
 - Maya 2022
 - Maya USD commit SHA [dev at 5c01103]
 - Pixar USD commit SHA [dev at 84bd5a9]

**Additional context**
It looks like [applyToAllPrimSpecs](https://github.com/Autodesk/maya-usd/blob/e87e10dab08af4364f38e87f74bc41c2e6f0c9a1/lib/mayaUsd/ufe/UsdUndoRenameCommand.cpp#L190) may be a little greedy for this operation.

**Comment by dj-mcg** [comment]
I have a potential fix for this - PR should land later today

**Comment by santosg87** [comment]
@dj-mcg is it ok to close this issue for now?

**Comment by dj-mcg** [comment]
Yeah this fixes our use cases, thanks!
