### ISSUE TITLE
mayaUSDExport with exportRoots issue

### ISSUE THREAD

**Issue by santosd** [Autodesk/maya-usd#2968]
### Discussed in https://github.com/Autodesk/maya-usd/discussions/2946

<div type='discussions-op-text'>

<sup>Originally posted by **neilrubie** March 15, 2023</sup>
We recently upgraded our MayaUsd plugin from v0.19 to v0.22 and I'm noticing some different behaviour in how the exportRoots flag is working. I used to be able to extract certain roots, while respecting a list of nodes requested for export. But this appears to no longer work properly. For example, here is what is in my maya scene:

```
-outer_group
    -master
        -group1
        -group2
        -group3
```
My end goal is to output a usd file with the following hierarchy:

```
-master
    -group1
```

I used to be able to accomplish this with:

```
nodes_to_export = ["|outer_group|master|group1"]
export_roots = ["|outer_group|master"]

cmds.mayaUSDExport(
    nodes_to_export,
    exportRoots=export_roots,
    file=output_filepath,
)
```

but now as of v0.22 it seems to be including the entire subtree beneath the roots, essentially ignoring the "nodes_to_export" list:

```
-master
    -group1
    -group2
    -group3
```

Is this a bug, or has this functionality changed?

Using:
Maya 2023.3
MayaUsd v0.22

</div>

**Comment by neilrubie** [comment]
Any update on this one?

**Comment by santosd** [comment]
Hi @neilrubie, this issue is currently in progress and being worked on internally. The internal ticket is MAYA-128511.

**Comment by neilrubie** [comment]
Great, thankyou!

**Comment by santosd** [comment]
Hi @neilrubie sorry for the late notice on this one, but the issue has been resolved for this. You should get the results you expect with the Latest Maya USD and the Latest Maya 2024.2. Give it a try and let me know if you run into any issues. I will go ahead and close this ticket out for the time being.

**Comment by santosd** [comment]
[export_roots.zip](https://github.com/Autodesk/maya-usd/files/15192937/export_roots.zip)
Attached are some tests files for this.
