### ISSUE TITLE
Build Maya_usd failed on maya2020

### ISSUE THREAD

**Issue by jackiezxt** [Autodesk/maya-usd#297]
**Describe the issue**
A description of what the issue is.

I built pxr_usd core on Win10 vs2017 for maya2020, but it failed in [x64 Native Tools Command Prompt for VS 2017]window, so I check that description on GitHub page(https://github.com/PixarAnimationStudios/USD/tree/master#windows), it says should be in x86, so I use it and succeeded in x86 native command prompt, but when I want to build maya_usd, I failed again. I used the code: 
`python build.py --generator Ninja --build-args=-DCMAKE_MAKE_PROGRAM=ninja.exe --maya-location "C:\Program Files\Autodesk\maya2020" --pxrusd-location c:\USD --devkit-location c:\devkitBase_maya2020 C:\USD_WorkSpace`

**Build log**
Please attach a build_log.txt
[build_log.txt](https://github.com/Autodesk/maya-usd/files/4238945/build_log.txt)

**Specs:**
 - Windows 10
 - Ninja
 - Maya 2020
 - Maya USD commit SHA[dev from fowlert/fix_compiler_errors]
 - PXR_USD [Master at :be1a80f}

**Additional context**

**Comment by HamedSabri-adsk** [comment]
Hi @jackiezxt 

1-
> Note if you're trying to build with Visual Studio 2017, use the "x86 Native Tools Command Prompt for VS 2017"

I believe this is a typo in Pixar's document. The sentence before indeed contradicts it.  

2-
When building USD, you also need to pass some additional flags for boost. Please see our build doc:
https://github.com/Autodesk/maya-usd/blob/dev/doc/build.md#boost

3- 
Your script for building maya-usd look good to me. One other thing I noticed is that you've checked into "fowlert/fix_compiler_errors" branch. If you are building against Maya2020, you don't really need those fixes. They only apply to 2019 and older.  However, it is Ok if you are already in that branch.

Hope this helps.

**Comment by jackiezxt** [comment]
Hi@HamedSabri-adsk
1- I rebuild the USD core with the additional flags for boost, in x64 native prompt, and it's success.
2- then I rebuild the maya-usd with "x64 native prompt", it failed again. 
[build_log.txt](https://github.com/Autodesk/maya-usd/files/4240730/build_log.txt)

**Comment by jackiezxt** [comment]
Hi ,@HamedSabri-adsk
I just checked #233 , and I used the flag  with PXR_STRICT_BUILD_MODE set to OFF  to build the project clean and that's OK, 
`python build.py --generator Ninja --build-args=-DCMAKE_MAKE_PROGRAM=ninja.exe --maya-location "C:\Program Files\Autodesk\maya2020" --pxrusd-location c:\USD --devkit-location c:\devkitBase_maya2020 C:\USD_WorkSpace --build-args="-DPXR_STRICT_BUILD_MODE=OFF"`

**Comment by HamedSabri-adsk** [comment]
@jackiezxt glad to hear things work. Please close this issue if you longer see any problems building the project.

@mattyjams  can you please review this PR: https://github.com/PixarAnimationStudios/USD/pull/1120
It is not clear to me why AppVeyor CI is failing?

**Comment by jackiezxt** [comment]
Hi, @HamedSabri-adsk ,
but I failed on macos , with
`python USD/build_scripts/build_usd.py /opt/local/USD`, 

the building process was successful, but when I use usdview, some issue hits me,

USD-20.02
PySide2-5.14.1
macOS-10.15 catalina

`johnnyzxt@zhongxingtians-MacBook-Pro ~ % usdview
dyld: warning, LC_RPATH @executable_path/../Frameworks in /Users/johnnyzxt/Library/Python/2.7/lib/python/site-packages/PySide2/Qt/lib/QtQml.framework/Versions/5/QtQml being ignored in restricted program because of @executable_path (Codesign main executable with Library Validation to allow @ paths)
dyld: warning, LC_RPATH @executable_path/../Frameworks in /Users/johnnyzxt/Library/Python/2.7/lib/python/site-packages/PySide2/Qt/lib/QtNetwork.framework/Versions/5/QtNetwork being ignored in restricted program because of @executable_path (Codesign main executable with Library Validation to allow @ paths)
dyld: warning, LC_RPATH @executable_path/../Frameworks in /Users/johnnyzxt/Library/Python/2.7/lib/python/site-packages/PySide2/Qt/lib/QtCore.framework/Versions/5/QtCore being ignored in restricted program because of @executable_path (Codesign main executable with Library Validation to allow @ paths)
dyld: warning, LC_RPATH @executable_path/../Frameworks in /Users/johnnyzxt/Library/Python/2.7/lib/python/site-packages/PySide2/Qt/lib/QtGui.framework/Versions/5/QtGui being ignored in restricted program because of @executable_path (Codesign main executable with Library Validation to allow @ paths)
dyld: warning, LC_RPATH @executable_path/../Frameworks in /Users/johnnyzxt/Library/Python/2.7/lib/python/site-packages/PySide2/Qt/lib/QtWidgets.framework/Versions/5/QtWidgets being ignored in restricted program because of @executable_path (Codesign main executable with Library Validation to allow @ paths)
Traceback (most recent call last):
  File "/Users/johnnyzxt/usd/bin/usdview", line 28, in <module>
    import pxr.Usdviewq as Usdviewq
  File "/Users/johnnyzxt/usd/lib/python/pxr/Usdviewq/__init__.py", line 26, in <module>
    from qt import QtWidgets
  File "/Users/johnnyzxt/usd/lib/python/pxr/Usdviewq/qt.py", line 26, in <module>
    from attributeValueEditorUI import QtCore
ImportError: cannot import name QtCore
`

**Comment by HamedSabri-adsk** [comment]
@jackiezxt not really sure if your latest post is related to this ticket but we haven't done much testing on Catalina. This is also mentioned in the build doc:

> NOTE: We haven't fully tested the plug-ins on Catalina and it is still at the experimental stage.

As for issues on Catalina, there are already some posts on usd-interest:

[usd-interest] Any luck compiling/running USDView using MacOS Catalina
[usd-interest] building usd-qt on macOS Catalina 10.15.1
[usd-interest] USD Build on Mac Fails

Have you already checked them out?

**Comment by jackiezxt** [comment]
@HamedSabri-adsk, thank you, I think I should wait for the right version for testing on Catalina.
