### ISSUE TITLE
Doesn't load plugin in Maya 2023

### ISSUE THREAD

**Issue by ArianRamos003** [Autodesk/maya-usd#2970]
Once the installation is done in Maya 2023, in the plug-ins manager section it does not let me load the plugin in loaded, I get the following error:
// Error: file: C:/Program Files/Autodesk/Maya2023/scripts/others/pluginWin.mel line 316: Unable to dynamically load : C:/Program Files/Autodesk/MayaUSD/Maya2023/0.22.0_202302061132-12c3665/mayausd /mayaUSD/plugin/adsk/plugin/mayaUsdPlugin.mll
// The specified process was not found.
// Error: file: C:/Program Files/Autodesk/Maya2023/scripts/others/pluginWin.mel line 316: The specified process was not found.
// (mayaUsdPlugin)
// Error: file: C:/Program Files/Autodesk/Maya2023/scripts/others/pluginWin.mel line 316: Unable to dynamically load : C:/Program Files/Autodesk/MayaUSD/Maya2023/0.22.0_202302061132-12c3665/mayausd /MayaUSD/lib/maya/mtoh.mll
// The specified process was not found.
// Error: file: C:/Program Files/Autodesk/Maya2023/scripts/others/pluginWin.mel line 316: The specified process was not found.
// (mtoh)

1. I execute the .exe of the usd
2. Mayan home
3. I go to plug in manager
4. View error

**Expected behavior**
start the plugin

**Attached files**
![test1](https://user-images.githubusercontent.com/128757846/227391326-32c3f631-55fd-4f6c-8341-72a4df7b9297.png)
![test2](https://user-images.githubusercontent.com/128757846/227391339-7b68c3bd-2104-48a4-baed-88a44bc5061b.png)

**Comment by santosg87** [comment]
Hi @ArianRamos003, 

I would recommend updating your version of Maya, as mayaUSD 0.22.0 was compiled with the latest update in mind. we develop and test using the most recent version of Maya, and it should work as expected in there. :)
