### ISSUE TITLE
[MAYA-128827] View bug on check toggle "purpose" 

### ISSUE THREAD

**Issue by kimuss** [Autodesk/maya-usd#2991]
**Describe the bug**
When I try to hide "proxy" or "Render"  on Stage Display-->Purpose , the objects doesn't disappear, if I click anywhere inside viewport, the view refreshed and the objects disappear

**Attachments**
![GIF 30-03-2023 13-13-05](https://user-images.githubusercontent.com/54888290/228819649-db58c8f0-d7b9-4e05-9029-2e51881e845e.gif)

**Specs (if applicable):**
 - OS & version [Windows 11 22H2]
 - Maya  2024
 - Maya USD 0.23 plugin

**Additional context**
on Maya 2022.4 (0.22 USD plugin) and 2023.3 (0.23 USD plugin) the toggle works fine.

**Comment by santosg87** [comment]
hi @kimuss thanks for reporting this! quick question on your workflow here - is the purpose you are checking on the prim the same as the proxyShape node? 

the behavior you mention seems similar to #2194, so i am wondering if it could be the same thing.

**Comment by kimuss** [comment]
Its similar but not the same.
In that case, the User check the property of single object, in my case I check the purpose on main stage node, and this problem is ONLY with Maya 2024.

**Comment by santosg87** [comment]
We have this logged internally as MAYA-128827.

**Comment by santosd** [comment]
Hi @kimuss, this issue should be resolved by this commit: https://git.autodesk.com/maya3d/maya-usd/commit/7e0704991a8250e676fada31ed59cf47179fbac9 and should be available in an upcoming release. If you would like to build your own up to date version you are welcome to test this or feel free to test this out when our next release comes out and let us know if you run into any issues. I have tested on my internal build and all was working as expected so closing this out for the time being.
