### ISSUE TITLE
Cannot open include file: 'pthread.h'

### ISSUE THREAD

**Issue by ben-hawkyard-saddington-baynes** [Autodesk/maya-usd#30]
Hello all, I'm encountering difficulties building maya-usd which seem to be similar to those already raised in https://github.com/Autodesk/maya-usd/issues/27.

I've tried building on windows 7 and on a virtual machine using windows 10. I built pixar usd using visual studio 14 2015 and I've tried building maya-usd using both vs 2015 and vs 2017, on both windows 7 and 10. 

I've attached the latest CMakeOutput and CMakeError files as well as the build log. In all permutations of os/vs version I've used the error in CMakeError is the same:
```
Y:\Users\ben.hawkyard\code\maya-usd\workspace\build\RelWithDebInfo\CMakeFiles\CMakeTmp\CheckIncludeFile.c(1): fatal error C1083: Cannot open include file: 'pthread.h': No such file or directory [Y:\Users\ben.hawkyard\code\maya-usd\workspace\build\RelWithDebInfo\CMakeFiles\CMakeTmp\cmTC_4fb8f.vcxproj]
```
Thank you for your time!

[build_log.txt](https://github.com/Autodesk/maya-usd/files/3535214/build_log.txt)
[CMakeError.log](https://github.com/Autodesk/maya-usd/files/3535215/CMakeError.log)
[CMakeOutput.log](https://github.com/Autodesk/maya-usd/files/3535217/CMakeOutput.log)

**Comment by ben-hawkyard-saddington-baynes** [comment]
These are the build commands I've been running, too:

**For vs 2017**
python build.py --maya-location "C:\Program Files\Autodesk\Maya2018" --pxrusd-location "C:\Program Files\USD" --devkit-location "C:\Program Files\Autodesk\Maya2018\devkitBase" --generator "Visual Studio 15 2017 Win64" .\workspace

**For vs 2015**
python build.py --maya-location "C:\Program Files\Autodesk\Maya2018" --pxrusd-location "C:\Program Files\USD" --devkit-location "C:\Program Files\Autodesk\Maya2018\devkitBase" --generator "Visual Studio 14 2015 Win64" .\workspace

**Comment by dtlindsey** [comment]
@ben-hawkyard-saddington-baynes 
I had the same issue.  I ended up having to rebuild USD with Visual Studio 2017, using the 
--generator "Visual Studio 14 2015 Win64" argument.
Then I was able to build the maya plugins, change the pathing in the .mod file, and load it successfully in Maya.  Give that a shot.

**Comment by ben-hawkyard-saddington-baynes** [comment]
Hi Daniel, what precisely do you mean by using Visual Studio 2017? Should I open the 2017 Developer command prompt and run the command there?

**Comment by dtlindsey** [comment]
Yes. Using the 2015 command prompt or a standard cmd didn't work.


Thanks,
-Daniel

On Aug 27, 2019 at 1:35 AM, ben-hawkyard-saddington-baynes <
notifications@github.com> wrote:

Hi Daniel, what precisely do you mean by using Visual Studio 2017? Should I
open the 2017 Developer command prompt and run the command there?

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/Autodesk/maya-usd/issues/30?email_source=notifications&email_token=AAXTVXZ57MOFLNJNWTV6JLTQGTRNVA5CNFSM4IPA7H5KYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD5G6ZZQ#issuecomment-525200614>,
or mute the thread

**Comment by ZhongLingXiao** [comment]
Hi 

I have change file : maya-usd\plugin\al\usdtransaction\AL\usd\transaction\tests\CMakeLists.txt
line 52 from

`set_tests_properties(${USDTRANSACTION_PYTHON_TEST_NAME}
  PROPERTIES
    ENVIRONMENT PYTHONPATH=${CMAKE_BINARY_DIR}/${INSTALL_DIR_SUFFIX}/usdtransaction:${CMAKE_BINARY_DIR}/src:$ENV{PYTHONPATH} 
)`

to
`set_tests_properties(${USDTRANSACTION_PYTHON_TEST_NAME}
  PROPERTIES
    ENVIRONMENT "PYTHONPATH=${CMAKE_BINARY_DIR}/${INSTALL_DIR_SUFFIX}/usdtransaction:${CMAKE_BINARY_DIR}/src:$ENV{PYTHONPATH}" 
)`

which only add **""** for the parameter and the problem solved

**Comment by samkenw** [comment]
@ZhongLingXiao This resolved the issue for me, thank you!

**Comment by fowlertADSK** [comment]
I believe this was finally fixed properly as part of a recent change to get the AL unit tests running on all platforms.  See:  https://github.com/Autodesk/maya-usd/pull/198
