### ISSUE TITLE
UDIM does not work on 0.23 plugin

### ISSUE THREAD

**Issue by zs0323** [Autodesk/maya-usd#3036]
Hello,
UDIM did not work when I used version 0.23 USD to create a preview shader in Maya2024. 
The result is as follows
![Snipaste_2023-04-26_15-00-22](https://user-images.githubusercontent.com/101910494/234495708-e2d5987f-6ebb-4c86-95b2-c4a0bfe7b864.jpg)
It can be seen that the texture is disordered
But when I used the 0.20 version of USD, the same USD file displayed correctly, as follows
![21244fee016df3867d910a133c7d255d](https://user-images.githubusercontent.com/101910494/234495924-570f24fb-7a72-4be8-b83b-368cdf3ea200.png)
![f8658bfb74c5de87db8563eeb549bb7c](https://user-images.githubusercontent.com/101910494/234495935-7f700923-c172-4a53-8c7d-9b0d1155cb53.png)
This is a simple test file

[test.zip](https://github.com/Autodesk/maya-usd/files/11329960/test.zip)

**Comment by santosg87** [comment]
looking at our repo, this one is a regression form #3016 :)
