### ISSUE TITLE
Cannot export SkelRoot with parentScope option

### ISSUE THREAD

**Issue by gelshoffNV** [Autodesk/maya-usd#3051]
**Describe the bug**
A proper setup including joints / mesh / with skinning under a group node fail to export if parentScope is set, resulting in the error:
`Error: Could not find an ancestor of the prim </Sphere/joint1> that can be converted to a SkelRoot. (USD requires that skinned meshes and skeletons be encapsulated under a SkelRoot.)`

**Steps to reproduce**
1. Create mesh and 3 joints then group them
2. bind the mesh to the joints
3. Export with "Create USD Parent Scope" set to "World", and set Skeletons / Skin Clusters to "All / Auto"

**Expected behavior**
I should get the same result as if I do when I don't set parent Scope

**Comment by santosd** [comment]
Hi @gelshoffNV Thank you for reporting this issue. I was able to reproduce the issue and agree that it should work. As far as your expectation is the hierarchy you would expect to get:

- ParentScope
      - Rig Group (skelRoot)
              - Mesh
              - Joint
That is what I would imagine the result would be, I just wanted to make sure to get your input before I log the issue internally.
Thank you.

**Comment by gelshoffNV** [comment]
Yeah, that looks right. In my maya scene, I wouldn't have the USD_ParentScope, but just the rigGroup...the result export I would expect would have the USD_ParentScope with the USD Skel below. Thanks

**Comment by wallworm** [comment]
Thanks for reporting. We will be looking into improving our USDSkel support in upcoming releases.

**Comment by barbalt** [comment]
This issue has been fixed on commit https://github.com/Autodesk/maya-usd/commit/927b3813bf0043a60898e0d58dff317534f487d6, using the `Create Root Prim` option on the Export dialog:
![image](https://github.com/Autodesk/maya-usd/assets/143224172/e7dd7164-b8dc-4291-b2a5-b50021edd4fc)
