### ISSUE TITLE
Usdz export texture with udim fail

### ISSUE THREAD

**Issue by DGaggio** [Autodesk/maya-usd#3084]
Hey,

I'm trying to export a Usdz file contain all my texture in there as I need to render in multiple machines and I want everything linked automatically when I'm opening the file.
I'm using Maya 2023.3 and plugin v0.22.
The materials are made in Maya Standard Surface and contain Udims.
Everytime I'm trying to export give me errors as Invalid Argument.
These are the setting I'm using to export
![01](https://github.com/Autodesk/maya-usd/assets/115561317/be7fb1b8-f93b-4313-9f6b-e3449b75b20e)

This is my Hypershade
![02](https://github.com/Autodesk/maya-usd/assets/115561317/ce79dfd4-0ad6-421b-bded-adfee8a30ec0)

And this is the error it give me in console
![03](https://github.com/Autodesk/maya-usd/assets/115561317/b596d1c7-f78c-49ed-a7a9-a1721a6da719)

I'm not mind to export in Usda but when I reference the file on Stage the texture are broken.

If anybody has an idea because mine are finished.

All the best,
Davide

**Comment by santosg87** [comment]
Hi @DGaggio, thank you for reporting this. I can also reproduce it on my side. 

i have logged this internally as MAYA-129449. and will bring it up to the team to discuss!

**Comment by dgovil** [comment]
UDIMs aren’t really resolvable by USD at this current time.

They’re resolved by the renderer instead. So it means that going to a usdz
that the packaging tools can’t find the textures.

**Comment by santosg87** [comment]
thank you for the Info @dgovil.
marking this issue as closed for the time being, as we don't have much we can do at this point. we can open a new issue for this with pixar once we have better support for UDIMs and USDZ.
