### ISSUE TITLE
[MAYA-95166] UFE : Duplicated Prim Position Incorrect When Edits Applied To Original

### ISSUE THREAD

**Issue by cfmoore007** [Autodesk/maya-usd#309]
**Describe the bug**

When editing a prims position in the USD stage, when duplicating the prim, the xformOp from the session layer is not applied to the duplicate.  Instead, the duplicated prim is created in the original position.

**Steps to reproduce**

1. open the included 3_Spheres example
2. select a sphere
3. move sphere to apply session layer edit
4. ctrl+d to duplicate sphere
5. notice it's in the original position and not where the original was moved to

**Expected behavior**

Duplicated prim shows up in the same position as the original.  This would mimic Maya's default behavior with DAG objects.

**Attachments**

[3_Spheres_Example.tar.gz](https://github.com/Autodesk/maya-usd/files/4257086/3_Spheres_Example.tar.gz)

![duplicateIssue](https://user-images.githubusercontent.com/2152250/75367922-083cee80-588f-11ea-8846-d02e47f6b1d3.png)

**Specs (if applicable):**
 - OS & version [e.g. Linux]
 - Compiler & version [e.g. gcc 6.3.1]
 - Maya version [e.g. Maya Beta]
 - Maya USD commit SHA [e.g. at 44e597f]
 - Pixar USD commit SHA [e.g. USD 19.11]

**Additional context**

**Comment by santosg87** [comment]
we can reproduce this on our side as well. 

it is logged as MAYA-95166

**Comment by pilarmolinalopez** [comment]
hi @santosg87 , we were planning to take a look at this too. is that okay?

**Comment by santosg87** [comment]
Definitely okay :)

**Comment by santosg87** [comment]
@cfmoore007. I have recently tested this internally, and cannot reproduce it anymore. are you able to confirm it?
