### ISSUE TITLE
Expose the mapping between the created Maya (dag) nodes and their corresponding prims in the ImportChaser in Python

### ISSUE THREAD

**Issue by BeardedPlatypus** [Autodesk/maya-usd#3094]
**Is your feature request related to a problem? Please describe.**

We use chasers to implement any post processing on specific IsA prims and Maya objects without having to completely rewrite existing readers and writers. In order to properly do this, we sometimes need to query data on the prims to update values on the Maya objects and vice-versa. The export chaser provides (in the constructor) a dag to prim map through the factory context:

```python
    def __init__(self, factoryContext, *args, **kwargs):  # pylint: disable=invalid-name
        super(MyExportChaser, self).__init__(factoryContext, *args, **kwargs)

        self._map = factoryContext.GetDagToUsdMap()
```

This allows us to reconstruct which dag nodes were responsible for creating which prims, and while it does not provide all
information (especially in regards to materials and other nodes that have non-dag node equivalents), it makes writing such
post-processing easier.

The `ImportChaser` does not expose this information in python. It does provide an import context, however the two functions
that seem to provide the relevant information do not have an equivalent python class registered:

```
context.GetImportedDagPaths()
Traceback (most recent call last):
  File "<string>", line 1, in <module>
TypeError: No Python class registered for C++ class class Autodesk::Maya::OpenMaya20230000::MDagPathArray
context.GetImportedPrims()
Traceback (most recent call last):
  File "<string>", line 1, in <module>
TypeError: No Python class registered for C++ class class std::vector<class pxrInternal_v0_22__pxrReserved__::SdfPath,class std::allocator<class pxrInternal_v0_22__pxrReserved__::SdfPath> >
```

The `PostImport` call also does not provide the necessary information. While it has two arguments, `sdfPaths` and `dagPaths`,
that could contain the necessary information, these seem to just contain the root prim/dag-node information, rather than the
full mapping.

In order to properly implement post-processing with an `ImportChaser` such a mapping is valuable as making guesstimates based
on names and reconstructing the hierarchy of prims is cumbersome and error-prone while this information should be available
during the import steps.

**Describe the solution you'd like**

The `ImportChaser` should provide a proper mapping of prims and their corresponding maya nodes. Ideally this mapping would
provide a mapping of `Usd.Prim` to `MObject` (or vice-versa) such that the source information can be found. If this is not
possible due to limitations of Maya-USD, providing a similar dag to usd (or vice-versa) mapping would already be a huge
improvement. This could be done by properly exposing the `GetImportedDagPaths` and `GetImportedPrims` in Python.

**Describe alternatives you've considered**

Currently, we either abuse Adaptors to register specific prim/mobject combinations in some python state, which can then be
used by the `ImportChaser` to perform the actual operations or we make a guesstimate of which prim should correspond with
which maya object based upon the name and path/hierarchy. Neither provides a satisfactory solution.

**Comment by wallworm** [comment]
Thanks for your feedback. We are actually already actively working on an updated mapping function that does exactly what you are asking. Perfect timing!

**Comment by BeardedPlatypus** [comment]
That's great to hear! That would help us out a lot! Is there anywhere, where the plans for those improvements are described? I would love to read up about them already, if possible :)

**Comment by santosd** [comment]
This was merged into our latest release https://github.com/Autodesk/maya-usd/releases/tag/v0.24.0. The following PR was merged for these changes https://git.autodesk.com/maya3d/maya-usd/commit/fc53171696e4cbd35558ec1f0cf37bf524904121 Feel free to take a look and try it out and let us know if you hit any issues. Thank you.
