### ISSUE TITLE
UsdSkel BlendShape and BlendShape Animation Import

### ISSUE THREAD

**Issue by gelshoffNV** [Autodesk/maya-usd#3101]
**Description**
Support importing blendShapes and additionally any animation assigned from SkelAnimation. 

**Additional context**
BlendShapes have been recently added to maya-usd export. It would be additionally good to support importing USD BlendShapes back into Maya. Goal would be to support full round-trip originating from Maya blendShape + animation -> USD Skel + BlendShape + SkelAnimation -> Maya blendShape + animation.

**Comment by wallworm** [comment]
Thank you for your input. This is on our roadmap and we intend to work on it for both Maya and Max.

**Comment by gelshoffNV** [comment]
I figured, but wanted to track it at least, is there a public roadmap I can review?

**Comment by santosg87** [comment]
Unfortunately, we don't currently have a public roadmap - we are still investigating the possible work around this, and we can update this when we have more information available.

**Comment by wallworm** [comment]
I wanted to give an update that we are currently working on blendshape import.
