### ISSUE TITLE
USD Preview Surface differences between Maya and Houdini

### ISSUE THREAD

**Issue by cchampet** [Autodesk/maya-usd#3108]
Hi all,

I hope this is not a duplicate of #2591 .  
At first we were surprised to see a noticable difference in render intensity when trying to mix lambert and USDPreviewSurface shaders in the viewport 2.  

Example:  
![image](https://github.com/Autodesk/maya-usd/assets/2589095/4901910f-5192-4de3-80cc-1e5f95b5bed2)  
The cube on the left has a lambert assigned, red (1,0,0), picked with color management unchecked.  
![image](https://github.com/Autodesk/maya-usd/assets/2589095/2c2abac4-93de-4560-856d-244b09030755)  

Then this cube is exported to usd, and imported back into maya. This is the cube on the right, with a USDPreviewSurface assigned. Its color is (0.8, 0, 0) and it does not look the same.  
![image](https://github.com/Autodesk/maya-usd/assets/2589095/5975d71b-b8af-457f-9017-895513c6e044)

As it was said in #2591, "it almost impossible to mix legacy surfaces like Phong and Lambert with modern PBR surfaces like Standard Surface".  

But the issue we are facing in production right now, makes me think about this...  
We are doing our surfacing in Houdini-19.0, by assigning USDPreviewSurfaces on shapes, and export the shaders to usd.  
Then this usd is imported into Maya, and we experienced the same "darker" shaders as described above. So we do not match the surfacing done in Houdini. I guess we should?  

Is there any chance that the **maya_usd** plugin interprets some USDPreviewSurface parameters differently than Houdini? Or a feature is may be supported by only one of them? If you are awared of any discussion about this somewhere, I will be galde to have a look at it.
Also, Ican provide here simple scenes next week if you want.

 - OS centos 7
 - Maya 2022.3
 - Maya USD 0.23.0

Thank you all for your amazing work here!
Cheers,

**Comment by santosg87** [comment]
Hi @cchampet, would you be able to share a couple sample files with us? I am investigating this issue, and when using USD Preview Surface as my material for everything, I am seeing the same colors/intensity.

when importing it into Maya, are you converting the materials by anychance? the materials should still look the same, as long as there is no conversion/translation having to be done. Maya itself does support displaying USDPreviewSurface sahders, so there should be no need for conversions.
