### ISSUE TITLE
Can't Build with UFE Support

### ISSUE THREAD

**Issue by Brithub77** [Autodesk/maya-usd#3111]
I've been receiving build errors, specifically relating to UFE support:

/Users/bryce/Downloads/BUILD/maya-usd/lib/mayaUsd/commands/PullPushCommands.cpp:460:18: error: no matching function for call to 'select'
            if (!UfeSelectionUndoItem::select("duplicate: select duplicate", sn)) {

Here is my build log:
[build_log.txt](https://github.com/Autodesk/maya-usd/files/11521416/build_log.txt)

How can I fix it? I'm on MacOS 13.2.1 (Ventura) and am using Maya 2023.3 and cmake 3.25.2.

**Comment by seando-adsk** [comment]
I think there is an error in the repo with regards to that line. It should only be called when building with Ufe. I see from your build_log.txt that Ufe was not found:
`-- UFE not found. UFE features will be disabled.`
Ufe is part of Maya 2023 so you should be able to build with Ufe. Did you specify Maya devkit location with the flag `--devkit-location`

Sean

**Comment by Brithub77** [comment]
Okay, I fixed that. However, since I'm building on ARM64, I'm now getting another error:

ld: symbol(s) not found for architecture arm64

**Comment by seando-adsk** [comment]
> Okay, I fixed that. However, since I'm building on ARM64, I'm now getting another error:
> 
> ld: symbol(s) not found for architecture arm64

Maya 2023 was Intel (x86_64) only.

**Comment by Brithub77** [comment]
Okay, I moved to an 64-bit system and am still getting error after error. Here's the latest one:

/Users/bryce/Downloads/maya-usd/lib/maya-usd/utils/util.h: fatal error: 'usdUfe/utils/Utils.h' file not found

**Comment by seando-adsk** [comment]
That file 'usdUfe/utils/Utils.h' is all part of very recent work to create a new project for UsdUfe. Can you please make to do a full clean build of maya-usd to make sure the cmake cache is correctly configured.

**Comment by Brithub77** [comment]
The same errors are present when I try to do a clean build.

**Comment by Brithub77** [comment]
Never mind. I just built it!

**Comment by Brithub77** [comment]
I'll close this issue since I solved it. Thank you for your help!
