### ISSUE TITLE
mtoh plugin crash

### ISSUE THREAD

**Issue by ChokmahBinah** [Autodesk/maya-usd#314]
Hello there, and thanks to everybody work trying to integrate USD in Maya.

Here Build for Maya 2020 worked like a charm.

Unfortunatly, mtoh maakes Maya crash everytime I try to activate it.
It worked only the first time I tried, but now I have systematic crashes.
And don't know why ..
Any idea here ?

Is there a way to get a crash log, or anything ? No message happen at Maya startup targeting any log file ...

Thanks in advance,

Florian.

System :

Windows 10
Maya 2020

**Comment by ChokmahBinah** [comment]
I finally manage to get a log file :

//=====================================================
Maya Crash Report
//=====================================================

Exception code: C0000005: ACCESS_VIOLATION - illegal read at address 0xFFFFFFFF
Fault address:  E216E15D in c:\Program Files\Pixar\RenderManProServer-23.1\lib\libprman.dll
0001:00C6D15D Logical offset (see .map file for location)

Call stack:
	Module:  c:\Program Files\Pixar\RenderManProServer-23.1\lib\libprman.dll (-exported-)
	Location: libprman.dllDspyMetadata + 1E703 bytes
	Module:  c:\Program Files\Pixar\RenderManProServer-23.1\lib\libprman.dll (-exported-)
	Location: libprman.dllDspyMetadata + 20F5C bytes
	Module:  c:\Program Files\Pixar\RenderManProServer-23.1\lib\libprman.dll (-exported-)
	Location: libprman.dllRixGetContextViaRMANTREE + 1F669 bytes
	Module:  c:\Program Files\Pixar\RenderManProServer-23.1\lib\libprman.dll (-exported-)
	Location: libprman.dllRixGetContextViaRMANTREE + 1F603 bytes
	Module:  c:\Program Files\Pixar\RenderManProServer-23.1\lib\libprman.dll (-exported-)
	Location: libprman.dllRendererBuild + 307B bytes
	Module:  c:\Program Files\Pixar\RenderManProServer-23.1\lib\libprman.dll (-exported-)
	Location: libprman.dllRixGetContextViaRMANTREE + 4A65B bytes
	Module:  c:\Program Files\USD\plugin\usd\hdxPrman.dll (-exported-)
	Location: hdxPrman.dllHdPrmanLoaderDeleteDelegate + 4D14 bytes
	Module:  c:\Program Files\USD\plugin\usd\hdxPrman.dll (-exported-)
	Location: hdxPrman.dllHdPrmanLoaderDeleteDelegate + 8C9E bytes
	Module:  C:\workspace\install\RelWithDebInfo\lib\maya\mtoh.mll (PDB)
	Location: mtoh.mllpxrInternal_v0_20__pxrReserved__::MtohInitializeRenderGlobals Line 304 
	Source: c:\maya-usd\lib\render\mayatohydra\renderglobals.cpp (304)
	Module:  C:\workspace\install\RelWithDebInfo\lib\maya\mtoh.mll (PDB)
	Location: mtoh.mllinitializePlugin Line 69 
	Source: c:\maya-usd\lib\render\mayatohydra\plugin.cpp (69)
	Module:  C:\Program Files\Autodesk\Maya2020\bin\OpenMaya.dll (-exported-)
	Location: OpenMaya.dllTplugin::primaryLoad + 2C7 bytes
	Decl: public: int __cdecl Tplugin::primaryLoad(class Tstring const & __ptr64,class Tstring * __ptr64) __ptr64
	Module:  C:\Program Files\Autodesk\Maya2020\bin\OpenMaya.dll (-exported-)
	Location: OpenMaya.dllTpluginPref::~TpluginPref + 5614 bytes
	Decl: public: virtual __cdecl TpluginPref::~TpluginPref(void) __ptr64
	Module:  C:\Program Files\Autodesk\Maya2020\bin\OpenMaya.dll (-exported-)
	Location: OpenMaya.dllTpluginPref::~TpluginPref + 3D07 bytes
	Decl: public: virtual __cdecl TpluginPref::~TpluginPref(void) __ptr64
	Module:  C:\Program Files\Autodesk\Maya2020\bin\OpenMaya.dll (-exported-)
	Location: OpenMaya.dllTpluginPref::~TpluginPref + 355B bytes
	Decl: public: virtual __cdecl TpluginPref::~TpluginPref(void) __ptr64
	Module:  C:\Program Files\Autodesk\Maya2020\bin\CommandEngine.dll (-exported-)
	Location: CommandEngine.dllTjournal::operator= + 616 bytes
	Decl: public: class Tjournal & __ptr64 __cdecl Tjournal::operator=(class Tjournal const & __ptr64) __ptr64
	Module:  C:\Program Files\Autodesk\Maya2020\bin\CommandEngine.dll (-exported-)
	Location: CommandEngine.dllTmelVariableList::`default constructor closure' + C3F7 bytes
	Decl: public: void __cdecl TmelVariableList::`default constructor closure'(void) __ptr64
	Module:  C:\Program Files\Autodesk\Maya2020\bin\CommandEngine.dll (-exported-)
	Location: CommandEngine.dllsetMelGlobalStackLevelPtr + 31 bytes
	Decl: void __cdecl setMelGlobalStackLevelPtr(unsigned int (__cdecl*)(void))
	Module:  C:\Program Files\Autodesk\Maya2020\bin\CommandEngine.dll (-exported-)
	Location: CommandEngine.dllTmelVariableList::`default constructor closure' + C3F7 bytes
	Decl: public: void __cdecl TmelVariableList::`default constructor closure'(void) __ptr64
	Module:  C:\Program Files\Autodesk\Maya2020\bin\CommandEngine.dll (-exported-)
	Location: CommandEngine.dllsetMelGlobalStackLevelPtr + 1C77 bytes
	Decl: void __cdecl setMelGlobalStackLevelPtr(unsigned int (__cdecl*)(void))
	Module:  C:\Program Files\Autodesk\Maya2020\bin\CommandEngine.dll (-exported-)
	Location: CommandEngine.dllTmelVariableList::`default constructor closure' + C3F7 bytes
	Decl: public: void __cdecl TmelVariableList::`default constructor closure'(void) __ptr64
	Module:  C:\Program Files\Autodesk\Maya2020\bin\CommandEngine.dll (-exported-)
	Location: CommandEngine.dllsetMelGlobalStackLevelPtr + 775 bytes
	Decl: void __cdecl setMelGlobalStackLevelPtr(unsigned int (__cdecl*)(void))
	Module:  C:\Program Files\Autodesk\Maya2020\bin\CommandEngine.dll (-exported-)
	Location: CommandEngine.dllTmelVariableList::`default constructor closure' + C3F7 bytes
	Decl: public: void __cdecl TmelVariableList::`default constructor closure'(void) __ptr64
	Module:  C:\Program Files\Autodesk\Maya2020\bin\CommandEngine.dll (-exported-)
	Location: CommandEngine.dllTmelVariableList::`default constructor closure' + C544 bytes
	Decl: public: void __cdecl TmelVariableList::`default constructor closure'(void) __ptr64
	Module:  C:\Program Files\Autodesk\Maya2020\bin\CommandEngine.dll (-exported-)
	Location: CommandEngine.dllSophiaExecutable::evaluate + 47 bytes
	Decl: public: union Value * __ptr64 __cdecl SophiaExecutable::evaluate(void * __ptr64) __ptr64
	Module:  C:\Program Files\Autodesk\Maya2020\bin\CommandEngine.dll (-exported-)
	Location: CommandEngine.dllTcommandEngine::executeCommand + 3C0 bytes
	Decl: public: int __cdecl TcommandEngine::executeCommand(class Tstring const & __ptr64,bool,bool,class TmelCmdResult * __ptr64,unsigned int) __ptr64
	Module:  C:\Program Files\Autodesk\Maya2020\bin\ExtensionLayer.dll (-exported-)
	Location: ExtensionLayer.dllTscriptActionMixin::execute + EF bytes
	Decl: protected: bool __cdecl TscriptActionMixin::execute(class Tevent const & __ptr64,class std::unique_ptr<class TinterpreterResult,struct std::default_delete<class TinterpreterResult> > * __ptr64) __ptr64
	Module:  C:\Program Files\Autodesk\Maya2020\bin\ExtensionLayer.dll (-exported-)
	Location: ExtensionLayer.dllTaction::performAction + 137 bytes
	Decl: private: void __cdecl Taction::performAction(class Tevent const & __ptr64,char const * __ptr64) __ptr64
	Module:  C:\Program Files\Autodesk\Maya2020\bin\ExtensionLayer.dll (-exported-)
	Location: ExtensionLayer.dllTaction::doIt + 32 bytes
	Decl: public: void __cdecl Taction::doIt(void) __ptr64
	Module:  C:\Program Files\Autodesk\Maya2020\bin\Qt5Core.dll (-exported-)
	Location: Qt5Core.dllQMetaObject::activate + 5D8 bytes
	Decl: public: static void __cdecl QMetaObject::activate(class QObject * __ptr64,int,int,void * __ptr64 * __ptr64)
	Module:  C:\Program Files\Autodesk\Maya2020\bin\ExtensionLayer.dll (-exported-)
	Location: ExtensionLayer.dllQmayaCheckBox::onOffChanged + 51 bytes
	Decl: private: void __cdecl QmayaCheckBox::onOffChanged(void) __ptr64
	Module:  C:\Program Files\Autodesk\Maya2020\bin\Qt5Core.dll (-exported-)
	Location: Qt5Core.dllQMetaObject::activate + 5D8 bytes
	Decl: public: static void __cdecl QMetaObject::activate(class QObject * __ptr64,int,int,void * __ptr64 * __ptr64)
	Module:  C:\Program Files\Autodesk\Maya2020\bin\Qt5Widgets.dll (-exported-)
	Location: Qt5Widgets.dllQCheckBox::nextCheckState + DA bytes
	Decl: protected: virtual void __cdecl QCheckBox::nextCheckState(void) __ptr64
	Module:  C:\Program Files\Autodesk\Maya2020\bin\Qt5Widgets.dll (-exported-)
	Location: Qt5Widgets.dllQAbstractButton::click + 140 bytes
	Decl: public: void __cdecl QAbstractButton::click(void) __ptr64
	Module:  C:\Program Files\Autodesk\Maya2020\bin\Qt5Widgets.dll (-exported-)
	Location: Qt5Widgets.dllQAbstractButton::mouseReleaseEvent + 8F bytes
	Decl: protected: virtual void __cdecl QAbstractButton::mouseReleaseEvent(class QMouseEvent * __ptr64) __ptr64
	Module:  C:\Program Files\Autodesk\Maya2020\bin\Qt5Widgets.dll (-exported-)
	Location: Qt5Widgets.dllQWidget::event + E4 bytes
	Decl: protected: virtual bool __cdecl QWidget::event(class QEvent * __ptr64) __ptr64
	Module:  C:\Program Files\Autodesk\Maya2020\bin\Qt5Widgets.dll (-exported-)
	Location: Qt5Widgets.dllQApplicationPrivate::notify_helper + 13D bytes
	Decl: public: bool __cdecl QApplicationPrivate::notify_helper(class QObject * __ptr64,class QEvent * __ptr64) __ptr64
	Module:  C:\Program Files\Autodesk\Maya2020\bin\Qt5Widgets.dll (-exported-)
	Location: Qt5Widgets.dllQApplication::notify + 8A9 bytes
	Decl: public: virtual bool __cdecl QApplication::notify(class QObject * __ptr64,class QEvent * __ptr64) __ptr64
	Module:  C:\Program Files\Autodesk\Maya2020\bin\ExtensionLayer.dll (-exported-)
	Location: ExtensionLayer.dllQmayaApplication::currentMousePos + 6FA bytes
	Decl: public: static class QPoint __cdecl QmayaApplication::currentMousePos(void)
	Module:  C:\Program Files\Autodesk\Maya2020\bin\Qt5Core.dll (-exported-)
	Location: Qt5Core.dllQCoreApplication::notifyInternal2 + B9 bytes
	Decl: private: static bool __cdecl QCoreApplication::notifyInternal2(class QObject * __ptr64,class QEvent * __ptr64)
	Module:  C:\Program Files\Autodesk\Maya2020\bin\Qt5Widgets.dll (-exported-)
	Location: Qt5Widgets.dllQApplicationPrivate::sendMouseEvent + 3E3 bytes
	Decl: public: static bool __cdecl QApplicationPrivate::sendMouseEvent(class QWidget * __ptr64,class QMouseEvent * __ptr64,class QWidget * __ptr64,class QWidget * __ptr64,class QWidget * __ptr64 * __ptr64,class QPointer<class QWidget> & __ptr64,bool,bool)
	Module:  C:\Program Files\Autodesk\Maya2020\bin\Qt5Widgets.dll (-exported-)
	Location: Qt5Widgets.dllQSizePolicy::QSizePolicy + 2C1D bytes
	Decl: public: __cdecl QSizePolicy::QSizePolicy(void) __ptr64
	Module:  C:\Program Files\Autodesk\Maya2020\bin\Qt5Widgets.dll (-exported-)
	Location: Qt5Widgets.dllQSizePolicy::QSizePolicy + A65 bytes
	Decl: public: __cdecl QSizePolicy::QSizePolicy(void) __ptr64
	Module:  C:\Program Files\Autodesk\Maya2020\bin\Qt5Widgets.dll (-exported-)
	Location: Qt5Widgets.dllQApplicationPrivate::notify_helper + 13D bytes
	Decl: public: bool __cdecl QApplicationPrivate::notify_helper(class QObject * __ptr64,class QEvent * __ptr64) __ptr64
	Module:  C:\Program Files\Autodesk\Maya2020\bin\Qt5Widgets.dll (-exported-)
	Location: Qt5Widgets.dllQApplication::notify + 1BA7 bytes
	Decl: public: virtual bool __cdecl QApplication::notify(class QObject * __ptr64,class QEvent * __ptr64) __ptr64
	Module:  C:\Program Files\Autodesk\Maya2020\bin\ExtensionLayer.dll (-exported-)
	Location: ExtensionLayer.dllQmayaApplication::currentMousePos + 6FA bytes
	Decl: public: static class QPoint __cdecl QmayaApplication::currentMousePos(void)
	Module:  C:\Program Files\Autodesk\Maya2020\bin\Qt5Core.dll (-exported-)
	Location: Qt5Core.dllQCoreApplication::notifyInternal2 + B9 bytes
	Decl: private: static bool __cdecl QCoreApplication::notifyInternal2(class QObject * __ptr64,class QEvent * __ptr64)
	Module:  C:\Program Files\Autodesk\Maya2020\bin\Qt5Gui.dll (-exported-)
	Location: Qt5Gui.dllQGuiApplicationPrivate::processMouseEvent + 911 bytes
	Decl: public: static void __cdecl QGuiApplicationPrivate::processMouseEvent(class QWindowSystemInterfacePrivate::MouseEvent * __ptr64)
	Module:  C:\Program Files\Autodesk\Maya2020\bin\Qt5Gui.dll (-exported-)
	Location: Qt5Gui.dllQWindowSystemInterface::sendWindowSystemEvents + 9B bytes
	Decl: public: static bool __cdecl QWindowSystemInterface::sendWindowSystemEvents(class QFlags<enum QEventLoop::ProcessEventsFlag>)
	Module:  C:\Program Files\Autodesk\Maya2020\bin\Qt5Core.dll (-exported-)
	Location: Qt5Core.dllQEventDispatcherWin32::processEvents + DE5 bytes
	Decl: public: virtual bool __cdecl QEventDispatcherWin32::processEvents(class QFlags<enum QEventLoop::ProcessEventsFlag>) __ptr64
	Module:  C:\WINDOWS\System32\USER32.dll (-exported-)
	Location: USER32.dllCallWindowProcW + 3BD bytes
	Module:  C:\WINDOWS\System32\USER32.dll (-exported-)
	Location: USER32.dllDispatchMessageW + 1F2 bytes
	Module:  C:\Program Files\Autodesk\Maya2020\bin\Qt5Core.dll (-exported-)
	Location: Qt5Core.dllQEventDispatcherWin32::processEvents + 5DB bytes
	Decl: public: virtual bool __cdecl QEventDispatcherWin32::processEvents(class QFlags<enum QEventLoop::ProcessEventsFlag>) __ptr64
	Module:  C:\Program Files\Autodesk\Maya2020\plugins\platforms\qwindows.dll (-exported-)
	Location: qwindows.dllqt_plugin_query_metadata + 1E99 bytes
	Module:  C:\Program Files\Autodesk\Maya2020\bin\Qt5Core.dll (-exported-)
	Location: Qt5Core.dllQEventLoop::exec + 1FB bytes
	Decl: public: int __cdecl QEventLoop::exec(class QFlags<enum QEventLoop::ProcessEventsFlag>) __ptr64
	Module:  C:\Program Files\Autodesk\Maya2020\bin\Qt5Core.dll (-exported-)
	Location: Qt5Core.dllQCoreApplication::exec + 15E bytes
	Decl: public: static int __cdecl QCoreApplication::exec(void)
	Module:  C:\Program Files\Autodesk\Maya2020\bin\ExtensionLayer.dll (-exported-)
	Location: ExtensionLayer.dllTapplication::start + D8 bytes
	Decl: public: void __cdecl Tapplication::start(void) __ptr64
	Module:  C:\Program Files\Autodesk\Maya2020\bin\maya.exe (-exported-)
	Location: maya.exeTiteratorWrapperFwd<TscenePartitions::ConstIteratorDescriptor,TiteratorWrapper<TscenePartitions::ConstIteratorDescriptor> >::operator++ + 10B8 bytes
	Decl: public: class TiteratorWrapper<struct TscenePartitions::ConstIteratorDescriptor> & __ptr64 __cdecl TiteratorWrapperFwd<struct TscenePartitions::ConstIteratorDescriptor,class TiteratorWrapper<struct TscenePartitions::ConstIteratorDescriptor> >::operator++
	Module:  C:\Program Files\Autodesk\Maya2020\bin\maya.exe (-exported-)
	Location: maya.exeTiteratorWrapperFwd<TscenePartitions::ConstIteratorDescriptor,TiteratorWrapper<TscenePartitions::ConstIteratorDescriptor> >::operator++ + 13887 bytes
	Decl: public: class TiteratorWrapper<struct TscenePartitions::ConstIteratorDescriptor> & __ptr64 __cdecl TiteratorWrapperFwd<struct TscenePartitions::ConstIteratorDescriptor,class TiteratorWrapper<struct TscenePartitions::ConstIteratorDescriptor> >::operator++
	Module:  C:\Program Files\Autodesk\Maya2020\bin\maya.exe (-exported-)
	Location: maya.exeTiteratorWrapperFwd<TscenePartitions::ConstIteratorDescriptor,TiteratorWrapper<TscenePartitions::ConstIteratorDescriptor> >::operator++ + 128CA bytes
	Decl: public: class TiteratorWrapper<struct TscenePartitions::ConstIteratorDescriptor> & __ptr64 __cdecl TiteratorWrapperFwd<struct TscenePartitions::ConstIteratorDescriptor,class TiteratorWrapper<struct TscenePartitions::ConstIteratorDescriptor> >::operator++
	Module:  C:\WINDOWS\System32\KERNEL32.DLL (-exported-)
	Location: KERNEL32.DLLBaseThreadInitThunk + 14 bytes
	Module:  C:\WINDOWS\SYSTEM32\ntdll.dll (-exported-)
	Location: ntdll.dllRtlUserThreadStart + 21 bytes
End of stack

//crash log file name = C:\Users\Chokmah\AppData\Local\Temp\MayaCrashLog200227.1933.log
//version     = 20.0.0.235
//cut            =  11/14/2019, 201911140446
//current scene = unDisclosed
//command history (most recent last):
//====================================================
//last tool: renderWindowSelectContextItem
//====================================================
//panel with focus: modelPanel4
//visible panels:
// modelPanel4 
//====================================================
//Memory usage:
// 15886.551 Mb	Free Memory
// 17768.852 Mb	Free Swap
// 1867.254 Mb	Current

//====================================================

This part got my attention : 


Exception code: C0000005: ACCESS_VIOLATION - illegal read at address 0xFFFFFFFF
Fault address:  E216E15D in c:\Program Files\Pixar\RenderManProServer-23.1\lib\libprman.dll
0001:00C6D15D Logical offset (see .map file for location)

**Comment by kxl-adsk** [comment]
It looks to be crashing in prman render delegate. The first step would be to remove this render delegate from the Pixar plugin search path. If mtoh will start working after and you will be able to switch to HdStorm...then I would suspect that your prman was built against different USD library than maya-usd.

**Comment by ChokmahBinah** [comment]
Hello kxl-adsk :)
Thanks a lot for your answer :)

I built USD plugin for Renderman, with Pixar USD build_usd.py script.
And, I add free Renderman ProServer and plugin for Maya installed.
Is there something wrong that ?

Second question,
By 'The first step would be to remove this render delegate from the Pixar plugin search path' do you mean with Windows PATH environment variable ? 

Anyway thanks a lot :)

**Comment by kxl-adsk** [comment]
Hmmm...ok. Does it work correctly in the usdview?

Given that you probably have both render delegates (storm and prman) in the same build location (i.e. <pixar_usd_folder>\plugin\usd) - can you move prman out of this folder?

**Comment by ChokmahBinah** [comment]
I try to get out hdxPrman folder out from <pixar_usd_folder>\plugin\usd.
Now mtoh plugin works. ;)

But for now, only GL(hydra) works, once I try to use Prman(Hydra) Maya crashes again.

Here is the Maya log after the crash :

[MayaCrashLog200228.0039.log](https://github.com/Autodesk/maya-usd/files/4264653/MayaCrashLog200228.0039.log)

**Comment by kxl-adsk** [comment]
Just to be sure I understand. When you remove hdxPrman folder (and dlls) out of `<pixar_usd_folder>\plugin\usd`, the mtoh plugin works and you have no crashes when using GL(hydra)? 

What did you do to get the crash after that?

**Comment by ChokmahBinah** [comment]
Hello,

Yes, indeed. Once I remove hdxPrman folder (and dlls) out of <pixar_usd_folder>\plugin\usd, the mtoh plugin works, and I have no crash with GL(Hydra).

But once I want to choose Prman(Hydra) viewpotr renderer, Maya crashes :
![Prman(Hydra)](https://user-images.githubusercontent.com/33164632/75605081-e4bcb280-5adf-11ea-8934-a08ea0c1a992.jpg)

![image](https://user-images.githubusercontent.com/33164632/75605104-0e75d980-5ae0-11ea-9d1f-aea649525573.png)

Thank you again for your help Krystian :)

**Comment by kxl-adsk** [comment]
We have PR open which helps filtering out invalid render delegates from the list - check https://github.com/Autodesk/maya-usd/pull/292

Now, all of this doesn't explain your original crash in hdxPrman
```
Call stack:
Module: c:\Program Files\Pixar\RenderManProServer-23.1\lib\libprman.dll (-exported-)
Location: libprman.dllDspyMetadata + 1E703 bytes
Module: c:\Program Files\Pixar\RenderManProServer-23.1\lib\libprman.dll (-exported-)
Location: libprman.dllDspyMetadata + 20F5C bytes
Module: c:\Program Files\Pixar\RenderManProServer-23.1\lib\libprman.dll (-exported-)
Location: libprman.dllRixGetContextViaRMANTREE + 1F669 bytes
Module: c:\Program Files\Pixar\RenderManProServer-23.1\lib\libprman.dll (-exported-)
Location: libprman.dllRixGetContextViaRMANTREE + 1F603 bytes
Module: c:\Program Files\Pixar\RenderManProServer-23.1\lib\libprman.dll (-exported-)
Location: libprman.dllRendererBuild + 307B bytes
Module: c:\Program Files\Pixar\RenderManProServer-23.1\lib\libprman.dll (-exported-)
Location: libprman.dllRixGetContextViaRMANTREE + 4A65B bytes
Module: c:\Program Files\USD\plugin\usd\hdxPrman.dll (-exported-)
Location: hdxPrman.dllHdPrmanLoaderDeleteDelegate + 4D14 bytes
Module: c:\Program Files\USD\plugin\usd\hdxPrman.dll (-exported-)
Location: hdxPrman.dllHdPrmanLoaderDeleteDelegate + 8C9E bytes
Module: C:\workspace\install\RelWithDebInfo\lib\maya\mtoh.mll (PDB)
```

The only thing I can do is continue guessing. Looking at the call stack - is it possible that you build USD (including hdxPrman) with a different version of render man pro server? (i.e. you are pointing Maya to c:\Program Files\Pixar\RenderManProServer-23.1, was this the same lib you used for building USD)?

**Comment by ChokmahBinah** [comment]
Yes I used same lib to build USD :

python build_scripts\build_usd.py --prman --prman-location "C:\Program Files\Pixar\RenderManProServer-23.1" "C:\Program Files\USD"

**Comment by kxl-adsk** [comment]
Ok. Let's see what will be the crash callstack with #292 (i.e. please merge it in and repeat the test with hdxPrman included in usd plugins)

**Comment by ChokmahBinah** [comment]
I have done like you said Krystian. 

With hdxPrman included in usd plugins, mtoh plugin crashes again.
Here is the log file :
[MayaCrashLog200229.1759.log](https://github.com/Autodesk/maya-usd/files/4270605/MayaCrashLog200229.1759.log)

**Comment by kxl-adsk** [comment]
There is nothing that stands out in this log file for me. It's hard to tell if the issue is related to mtoh or hdxPrman. One thing you could do is to install pdb's when building USD (use this patch for USD 
[patch_for_USD_for_pdb.txt](https://github.com/Autodesk/maya-usd/files/4277148/patch_for_USD_for_pdb.txt) and build USD again). This way we may know more about the crash inside of hdxPrman.

**Comment by ChokmahBinah** [comment]
Okay I'll do this Krystian.

Thanks you a lot, I know it can be difficult to help users like me who are new to all this technical stuff (I mainly create maya tools and plugins using python at this time).
Following and trying to participate to this maya usd project learns me a lot.

I'll build USd with this patch as soon as possible.

Thanks again :)

**Comment by santosg87** [comment]
I've also logged this information on our internal database, so we can keep track of it and do any work that might be needed on the Maya side of things. :)

it is currently logged as MAYA-103695

**Comment by ChokmahBinah** [comment]
I have rebuildt USD with patch_for_USD_for_pdb.txt.
Then rebuilt Maya USD. 
Then I launched Maya an dactivated mtoh plugin (with hdxPrman dll).
Maya crashed again.
I noticed that at the crash time it tried to launch It.
It seems strange to me. (This fact occured last times too, I forgot to give you this information)
Here the Maya crash log :

[MayaCrashLog200302.2249.log](https://github.com/Autodesk/maya-usd/files/4278090/MayaCrashLog200302.2249.log)

I dont know if it will help :
I am trying Maya USD on Maya 2020.
My graphic card is a GeForce GTX 750 Ti (Perhaps it could come from here).

**Comment by kxl-adsk** [comment]
Weird, I was hoping to see lines at which this crash is happening, but it's not there.
```
	Module:  c:\Program Files\USD\plugin\usd\hdxPrman.dll (-exported-)
	Location: hdxPrman.dllHdPrmanLoaderDeleteDelegate + 4D14 bytes
	Module:  c:\Program Files\USD\plugin\usd\hdxPrman.dll (-exported-)
	Location: hdxPrman.dllHdPrmanLoaderDeleteDelegate + 8C9E bytes
	Module:  C:\workspace\install\RelWithDebInfo\lib\maya\mtoh.mll (PDB)
	Location: mtoh.mllpxrInternal_v0_20__pxrReserved__::MtohInitializeRenderGlobals Line 304 
	Source: c:\maya-usd\lib\render\mayatohydra\renderglobals.cpp (304)
```

You can notice that for modules in maya-usd, you get a `Line XX`...but not for hdxPrman. Can you look in c:\Program Files\USD\plugin\usd\ and check if there are .pdb files?

BTW. When building USD, you are pointing it to build in c:\Program Files\USD ?

**Comment by ChokmahBinah** [comment]
Yes when building USD I am pointing it  to build in c:\Program Files\USD
And no .pdb files in c:\Program Files\USD\plugin\usd\

(I hope I don't do something wrong)

**Comment by kxl-adsk** [comment]
OK, this explains why we don't see the lines. You will have to investigate what went wrong since I'm using exactly the same patch and have .pdb files.

**Comment by ChokmahBinah** [comment]
Perhaps I don't use the patch correctly. I'll check about this.

**Comment by ChokmahBinah** [comment]
Sorry, I ha ve this error messages when checking the patch file :

![image](https://user-images.githubusercontent.com/33164632/75728888-764b4080-5ce9-11ea-89a0-5acec58a329f.png)

I feel a bit  lost °_° haha ^^

**Comment by ChokmahBinah** [comment]
Hello again Krystian,

I cloned a fresh USD-master, tried again your patch.

Patch check was fine.
But now I have two errors when applying it :
![image](https://user-images.githubusercontent.com/33164632/75811429-b3b4da00-5d8c-11ea-94f1-bc17b36efcac.png)

**Comment by kxl-adsk** [comment]
Just do `git status` and you will see that patch was applied, i.e.
```
ligenzk@MTLMJ06HN3A MINGW64 /e/Dev/usd/usd (dev)
$ git status
On branch dev
Your branch is up to date with 'origin/dev'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

        modified:   build_scripts/build_usd.py
        modified:   cmake/macros/Private.cmake
        modified:   cmake/macros/Public.cmake

no changes added to commit (use "git add" and/or "git commit -a")
```

I used dev branch, but should be ok as well with master (20.02)

**Comment by ChokmahBinah** [comment]
Indeed I get the same messages using git status.

No now I should rebuild USD using Prman plugin right ?

**Comment by kxl-adsk** [comment]
Yes, please. Now you should have pdb's in the folder and callstack should include `Line XX` for hdxPrman.dll.

**Comment by ChokmahBinah** [comment]
Hello again Krystian,

I found time to build usd with Prman.
I tested runnin mtoh plugin with prman and it crashed again.
And I have pdb files in ..\plugin\usd now.

But It seems I cannot read them. Do I need a specific tool to do that ? 

Here is the pdb file :

[hdxPrman.zip](https://github.com/Autodesk/maya-usd/files/4289591/hdxPrman.zip)

But, more strangely, the second time I tried to load mtoh plugin, It worked ! (I do nothing except what you asked me).

I tried one more time, it worked again.
(I have to note that it runs Pixar 'It' at the same time)

... And I feel confused ... I don't like when something works suddenly without reason lol

One last thing : The plugin loads successfully but when I choose Prman(Hydra) it renders nothing.
I don't know if it is normal ... 

I hope this pdb file is what you needed :$

**Comment by ChokmahBinah** [comment]
I noticed another fact :
I ran a viewport render with NC Renderman Plugin for Maya. (A torus to test something really simple).
And then when I ran Prman(Hydra) it rendered a torus in black (with or without RM light or standard Maya light). So It renders something.

I will continue to investigate, note another behaviors if it can help.

**Comment by kxl-adsk** [comment]
I was off the last two days. Now that you have pdb's...can you give me the crash log?

**Comment by ChokmahBinah** [comment]
Hello Krystian,
Don't worry Krystian, I understand now.
I thought we had to read the pdb file directly to see the log. Now you mention it I realize the pdb files add messages to Maya crash log. I can see them.

So here is the last one :

[MayaCrashLog200307.0943.log](https://github.com/Autodesk/maya-usd/files/4301583/MayaCrashLog200307.0943.log)

Thanks you I learned something new :)

**Comment by kxl-adsk** [comment]
Looking at the call stack and the place in HdxPrmanRenderDelegate where the crash happens (i.e. destructor) - you will have to bring this up on USD mailing list. 

Maya to hydra may have a different pattern than other applications, where it creates and destroys render delegates during its initialization. But there shouldn't be anything wrong in doing so, and render delegate destructor should properly handle it. As we see in the callstack you provided, prman render delegate doesn't like it (not sure what are the expectations around the shared context object which is in the center of this crash).

**Comment by ChokmahBinah** [comment]
OK, so I should transfert this log to Pixar USD mailing ?
I'll do so.

Thank you a lot ^^

**Comment by ChokmahBinah** [comment]
Hello Krystian,

I come back with very few news since I send a message on USD mailing list.
No answer for now except this :
Filed as internal issue #USD-5921

I 'll come with news if I have some, and still continue to investigate until then :)

**Comment by kxl-adsk** [comment]
@ChokmahBinah should we close the ticket here? We don't have much more to do for now. You can always reopen with new information if needed.

**Comment by ChokmahBinah** [comment]
I think you are right, I prefer coming back with real informations if i get some.

Thank you for all your help Krystian :)

**Comment by ChokmahBinah** [comment]
Hello again,

Here is the discussion copy on Pixar USD project:

Hello everybody, and thank for all the work done around.
Description of Issue

I builted Pixar USD and Maya USD plugin.
The AL_USDMayaPlugin or mayaUsdPlugin work fine. (As far as I know)
But when loading mtoh.mll Maya often craches.
I ask for some help on the Maya USD mailing list.
After searching for errors with pfb files, and giving them the maya crash log, they suggested me to ask here.
So here I am.

Here is the crash log :

MayaCrashLog200307.0943.log
Steps to Reproduce

    Load Maya
    Activate AL_USDMayaPlugin or mayaUsdPlugin in the Plug-in Manager.
    Activate mtoh plugin in Plug-in Manager
    Maya Crash

System Information (OS, Hardware)

Windows 10 x64
24 Go RAM
Intel(R) Core(TM) i7-4790 CPU
NVIDIA GeForce GTX 750 Ti
Package Versions

Merge release v20.02
Build Flags

python build_usd.py --prman --prman-location C:\Program Files\Pixar\RenderManProServer-23.1 --alembic --openvdb "C:\Program Files\USD" --build-args boost,"--with-date_time --with-thread --with-system --with-filesystem"

Thank you in advance for your help.

Florian.
@jilliene
jilliene commented 7 days ago

Filed as internal issue #USD-5921
@c64kernal
Contributor
c64kernal commented 2 hours ago

Thanks @ChokmahBinah -- we don't maintain mtoh here, please file an issue on the Autodesk project page here: https://github.com/Autodesk/maya-usd and hopefully someone there can help you out.

I hope it will help. 

Thank you again :)

**Comment by kxl-adsk** [comment]
Added more details to https://github.com/PixarAnimationStudios/USD/issues/1134#issuecomment-600674573

**Comment by ChokmahBinah** [comment]
Thanks you a lot @kxl-adsk 
I have read the message on Pixar Discussion Group. More precise indeed ! ^^
I will continue to investigate at my level ;)

**Comment by santosd** [comment]
Hi @kxl-adsk, should this one be closed at this point since Pixar is taking a look on their end? Thank you.

**Comment by kxl-adsk** [comment]
Yes, now is a good time. Thx for catching it @santosd
