### ISSUE TITLE
where did the AL MayaReference go?

### ISSUE THREAD

**Issue by DanEnglesson** [Autodesk/maya-usd#32]
Hi,

`from AL.usd.schemas.maya import MayaReference` does not work anymore and looking at all the `lib/python` libraries that is included in the `PYTHONPATH` it's not included there. It seems to have been moved to `maya-usd/lib` which is not added to the PYTHONPATH; I might be missing something here but from what I can see the MayaReference is never added to the PYTHONPATH envar in the mayaUSD.mod file. 

Cheers,
Dan

**Comment by DanEnglesson** [comment]
I should mentioned this is for the refactoring_sandbox. The master branch has the MayaReference in the AL plugin still.

**Comment by kxl-adsk** [comment]
Correct, it was moved as part of plugin merge. Now every plugin should be able to import USD file with Maya reference prims. But as you have discovered, we haven't yet finished python binding part of it. We are now in process of moving python bindings out of Pixar plugin into the core library and then we will add missing Maya Reference.

**Comment by kxl-adsk** [comment]
Logged as  MAYA-100476

**Comment by DanEnglesson** [comment]
OK, good to know. Thanks for the info.

**Comment by rhaleblian** [comment]
Yes, thanks for that info on intent. My shop was using that API, it's a current showstopper for migration to maya-usd away from the AL and Pixar sources.

**Comment by kxl-adsk** [comment]
You can still migrate to the dev branch since the move of Maya reference schema was only done in the refactoring_sandbox branch.

**Comment by DanEnglesson** [comment]
Yes, as Krystian said, this is only affecting the refactoring_sandbox branch. We have successfully switched to maya-usd and are currently using the master branch. You should be able to switch to either the master or dev branch. 

Thanks for clarifying this Krystian.

**Comment by rhaleblian** [comment]
You guys were clear about the affected branch, i am just fixated on `refactoring_sandbox` as I've used that branch for cherry-picking our site changes. Getting those changes onto `master` instead may be a better way to go.

**Comment by BigRoy** [comment]
Just for full clarity. The intended goal is that the `refactor_sandbox` branch at some point will become the new `master`. As it's the intermediate work of the full merge of the separare plug-ins. Correct?

As such, would he AL and Pixar side of plug-in nodes then get deprecated in favor of `maya-usd`'s own loader and proxy shapes? Or what exactly is the goal?

**Comment by kxl-adsk** [comment]
The goal is to build adsk and studio plugins on top of common modules. Some modules will be new (like UFE, base proxy shape, vp2renderdelegate or mtoh), others will be refactored from existing plugins (like MayaReference or Pixar Translation Framework + Translators). This work is visible refactoring_sandbox and will be moved in chunks to dev branch.

The main goal of starting in a separate branch was to ease the transition to a single repo (especially for AL and Pixar). Once transition is completed we will start integrations from refactoring_sandbox and moving development to dev.

**Comment by rhaleblian** [comment]
For closure on my side comment: I have moved our site changes to `master`, which as expected sidestepped this issue.

**Comment by kxl-adsk** [comment]
@DanEnglesson #255 was a backport of refactoring we did in refactoring sandbox to dev branch. It also added python bindings. Please close validate (in dev branch) and close this issue.

**Comment by DanEnglesson** [comment]
Thanks Krystian!
I haven't had time to check it out yet in dev, but this is great! Many thanks!

Dan

**Comment by DanEnglesson** [comment]
Just to follow up. This has been working fine for us for quite some time now, just make sure you switch to use the MayaReference from AL_MayaReference.

Cheers,
Dan

**Comment by kxl-adsk** [comment]
Thank you, Dan.
