### ISSUE TITLE
[MAYA-111175] Maya UFE : Isolate Selection Support

### ISSUE THREAD

**Issue by cfmoore007** [Autodesk/maya-usd#320]
**Is your feature request related to a problem? Please describe.**
Artists would like to be able to select USD Prims (and maybe some DAG objects as well) and press ctrl+1 to isolate / un-isolate select.

This workflow is used to both reduce visual clutter and for view port performance reasons.

Specific Use Case :

1. Artist references in shot.usda
2. Variant switches from USD Char -> Maya Rig
3. Artist needs to isolate some surrounding parts of the set & the character to remove visual clutter ( and maybe ... for performance reasons )
4. Artist wants to hit ctrl+1 like usual, so they can isolate selected shapes in the viewport

**Describe the solution you'd like**
It behaves like existing display layer workflows and feels native to Maya.

**Describe alternatives you've considered**
Custom USD Prim set / grouping management tools in our custom USD Outliner.  Don't really want to go there unless we have to.

**Additional context**
N/A.

**Comment by wtelford** [comment]
@santosg87, can you link this to the jira issue?

**Comment by williamkrick** [comment]
Isolate select for USD objects in MayaUSD with Vp2RenderDelegate is now supported in Maya Preview Release 130 & MayaUSD v0.14.0. The behavior should match Maya's isolate select behavior for regular Maya objects.
