### ISSUE TITLE
Missing Plug-in Configuration for USD Import

### ISSUE THREAD

**Issue by jcoelho88** [Autodesk/maya-usd#3226]
**Describe the bug**
Missing Plug-in Configuration drop down option when you are importing USD files.

I expected there to be at least an option for Arnold like there is for exporting.

Right now the option is not in the GUI:

![image](https://github.com/Autodesk/maya-usd/assets/88895104/c9547158-165c-44b2-aea1-c7c797bb8aba)

I was looking around and found a post from May of this year and it had a screen shot of the import where the Plug-in Configuration was present:
https://github.com/Autodesk/maya-usd/issues/3088
![image](https://github.com/Autodesk/maya-usd/assets/88895104/83d84f10-9157-4ca6-99cf-dad37067edcf)

Running the command to list the JobContexts available it returns "None" for import and "Arnold" for export

```python
print(cmds.mayaUSDListJobContexts(im=True))
print(cmds.mayaUSDListJobContexts(export=True))
```

**Steps to reproduce**
1. Make sure that the Maya-usd plug-in is loaded
2. Go to File->Import
3. Set file type to USD Import

**Expected behavior**
I expected there to be the option to choose a Plug-in Configuration for Imports like there is Exports, specifically an Arnold option.

**Specs (if applicable):**
Windows 10 Pro
Maya 2024.1
Maya-usd 0.24.0
MtoA 5.3.2.1

Im hoping someone might know what went wrong here or if there is something im missing, currently im unable to import assets with their Arnold materials.

Any insight into this would be very appreciated.

Cheers,

Jason Coelho

**Comment by santosd** [comment]
Hello @jcoelho88 ,

This issue usually happens when the plugins are not synched, but I tested this on my end and all seems to be working as expected:
![image](https://github.com/Autodesk/maya-usd/assets/29235905/b17e9285-da8f-48e5-86f9-264389570791)
Could you show the output for what you have listed in the Plugin Manager for MayaUSD and also so what you have in the about box for MtoA. Can you also provide the cutid you see in the Help > About menu of Maya. I want to make sure that we are using the same versions.

**Comment by jcoelho88** [comment]
Hi @santosd,

Thanks for the quick reply, Here is a screen shot with the requested windows open.

Please note that the Plug-in Configuration im having an issue with is the Import 
not the export as shown in the image you displayed.

First image with the Maya cutid
![image](https://github.com/Autodesk/maya-usd/assets/88895104/32489266-1d52-41f0-b916-1c0188333d0a)

Second showing the Import without the plug-in Configuration.
![image](https://github.com/Autodesk/maya-usd/assets/88895104/bbd3f0e3-7645-41a6-8db1-f171c0b8a6a7)

Thanks for looking into this.

Cheers,

Jason Coelho

**Comment by santosd** [comment]
Ah sorry, I didn't catch that you were talking about the import options. Arnold has not implemented any importer code and therefore no configuration shows up for MtoA on import at this point only for Export.

**Comment by jcoelho88** [comment]
Hi @santosd,

Thanks for the confirmation.

If this is the case does this mean there is currently no way to have the Arnold materials/shaders translated back into Maya data via an import?

Can a plug-in Configuration for Arnold import be expected in the near future?

I understand that LookDevX is available but its still in preview and we were hoping to have the option to import Arnold Materials back into Maya data to work with in the Hypershader.

If there are any option you know of I'd be happy to give them a try.

Cheers,

Jason Coelho

**Comment by santosd** [comment]
I spoke with a developer on the Arnold side and they said that they do have plans to support import of shaders, possibly without the use of a plugin configuration. Unfortunately, I don't have further details on when this might be available. You may be able to get some more information on the forums for Arnold: https://forums.autodesk.com/t5/arnold/ct-p/arnold

**Comment by santosd** [comment]
Let me know if you have any further questions on this, otherwise I can go ahead and close it out.

**Comment by jcoelho88** [comment]
Hi @santosd,

Thanks for the info. I'll close the issue and look for future updates.

Cheers,

Jason Coelho
