### ISSUE TITLE
[MAYA-111421] UFE Outliner Context : Add drag/drop capability 

### ISSUE THREAD

**Issue by cfmoore007** [Autodesk/maya-usd#324]
**Is your feature request related to a problem? Please describe.**
We have various drag/drop workflows in our existing in-house USD Outliner, we would like the capability of with the new Context feature from https://github.com/Autodesk/maya-usd/pull/303

**Describe the solution you'd like**
An ability to add a callback to handle drag and drops onto the outliner with specific mime types

**Describe alternatives you've considered**
Using our own outliner, but honestly we would like to use off-the-shelf where we can.

**Additional context**
N/A - will provide further details if needed.

**Comment by wtelford** [comment]
hey @santosd can you log this internally?

**Comment by santosd** [comment]
Logged internally.

**Comment by gracekumagai** [comment]
Hello! We were wondering if there have been any updates on this ticket? 

We saw that Sean had mentioned that there's a new hook in Maya to add new menu items to the context menu in the Outliner in the latest PR and we were wondering if there are any hooks to handle drag and drop?

Thank you!

**Comment by ppt-adsk** [comment]
Hi @gracekumagai, can you provide us with workflow details and examples of what you're trying to do?  We want to make sure we understand the requirements well.  For example, do we need to give the plugin a drag enter event, to provide feedback to the user for drop availability?  Given a single drag, will there ever be a need for more than one drop action that the user would need to select interactively, via a menu or some other UI device?  Currently, the Outliner only supports parent-child management as a drop action (reparent, child reorder), and clearly you are looking to expand on that.

Whatever we do will require a Maya change, which makes us want to be even more thorough and deliberate :)  Cheers.

**Comment by womanyoyoyo-adsk** [comment]
Hi @gracekumagai,

We have this issue as one of your adoption blockers and we'd like to unblock you but we need more information. Above, Pierre asked some questions that we are still wondering. Do you mind answering them? Here they are along with a few more:

- Do you need a drag enter even to provide feedback to user on drop availability?
- Given a single drag, will there ever be a need for more than one drop action that the user would need to select interactively, via a menu or some other UI device?
- Would you expect to drag and drop multiple items?
- Would you expect to drag and drop Maya objects?

Also, it would help greatly if you provided examples of workflows, as we might be working on them already or plan to.

Any info would help. Thanks!
Natalia

**Comment by wallworm** [comment]
We are looking at this for an upcoming update. Our current proposal is to provide a callback event that provides this information:

- Array of full file paths dropped in the case of files dropped from the operating system desktop or array of Maya nodes dropped in the case of Maya objects
- enum of whether the drop was files from desktop or Maya objects
- ProxyShape dropped onto
- Prim dropped onto

Does this fit your needs @gracekumagai  ?

**Comment by dj-mcg** [comment]
Hi folks, just catching up on the status of all of these open issues during a quiet holiday week. I'll circle back around to give you specific use cases we'll have in production, but from the last TSC meeting it sounds like you have made progress on this re: callbacks we can implement - thank you!

**Comment by wallworm** [comment]
This feature is now in 0.26+.

**Comment by santosg87** [comment]
closing this issue for the time being, as it is now in our released versions for some time.
