### ISSUE TITLE
Missing UFE api for Maya 2023

### ISSUE THREAD

**Issue by dgovil** [Autodesk/maya-usd#3244]
I'm trying to build from top of tree of the repo and hit this line that has a missing API in UFE when built for Maya 2023. ..

```
/Users/dhruvgovil/Projects/maya-usd/lib/usd/hdMaya/delegates/proxyDelegate.cpp:347:19: error: no member named 'usdPathToUfePathSegment' in namespace 'MayaUsd_v0::ufe'; did you mean simply 'usdPathToUfePathSegment'?
                = MayaUsd::ufe::usdPathToUfePathSegment(usdPath);
                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                  usdPathToUfePathSegment
/Users/dhruvgovil/Projects/maya-usd/lib/usdUfe/ufe/Utils.h:74:18: note: 'usdPathToUfePathSegment' declared here
Ufe::PathSegment usdPathToUfePathSegment(
                 ^
```

It looks like removing the namespace fixes it the symbol lookup

**Comment by seando-adsk** [comment]
@dgovil Right that method was moved to the new UsdUfe library (and namespace). The reason we didn't update this was because the `hdMaya` code is disabled now as it is replaced by the new mayaHydra code which you can find [here](https://github.com/Autodesk/maya-usd/tree/release/maya-hydra).

**Comment by dgovil** [comment]
Thanks, that would really help streamline things. I'll close this issue out then
