### ISSUE TITLE
[MAYA-109887] VP2RenderDelegate: support per-instance data via inheritance

### ISSUE THREAD

**Issue by cfmoore007** [Autodesk/maya-usd#327]
**Describe the bug**
It appears that inherited displayColors are not supported currently with the VP2 Delegate, while HdSt/Hydra ( mtoh ) seems to support this fine.

Attached is an example asset that uses PxrSurface shaders, but still has displayColor defined.  Another file inheritedDisplayColor_noPxrMtls.usda is included to rule out any influence from the PxrSurface definition.

We tested this w/ an AL_usdmaya_ProxyShape, but it also appears with the Maya proxyShape.

**Steps to reproduce**
1. load included usda file
2. witness blue vp2 fallback shader

**Expected behavior**
displayColor is reflected properly in the viewport that matches Hydra.

**Attachments**
All files :
- [inheritedDisplayColor.tar.gz](https://github.com/Autodesk/maya-usd/files/4288461/inheritedDisplayColor.tar.gz)

**Inherits Display Color (PxrSurface)**
inheritedDisplayColor_pxrSurface.usda
![inheritsDisplayColor](https://user-images.githubusercontent.com/2152250/75901239-35981800-5e0c-11ea-98df-b05592e49543.png)

**VP2 Delegate Result**
![blueApple](https://user-images.githubusercontent.com/2152250/75901272-40eb4380-5e0c-11ea-889b-4b8f91c89549.png)

Mtoh / Hydra Result
![properAppleColor](https://user-images.githubusercontent.com/2152250/75901311-4f395f80-5e0c-11ea-94c9-cfb7e3434911.png)

**Material definition removed - only displayColor**
inheritedDisplayColor_noPxrMtls.usda
![grayApple](https://user-images.githubusercontent.com/2152250/75901356-61b39900-5e0c-11ea-9519-617e54ffc00a.png)

**Specs (if applicable):**
 - OS & version [e.g. Linux]
 - Compiler & version [e.g. gcc 6.3.1]
 - Maya version [e.g. Maya 2020]
 - Maya USD commit SHA [e.g. dev at 44e597f]
 - Pixar USD commit SHA [e.g. 19.11]

**Additional context**

**Comment by HdC-adsk** [comment]
@cfmoore007 Thanks for reporting the issue. A quick look reveals two issues.

* The "payload" node is instanceable and in this case the instancer is where we can fetch the color data from, but not the mesh node. This is not implemented yet in HdVP2Instancer.

* The material requires color data from the mesh, and the current implementation doesn't pass the color to the shader, causing random draw issues.

**Comment by HdC-adsk** [comment]
@cfmoore007 Is this a scene that we can use to create internal render tests on our side?
