### ISSUE TITLE
Selection by Kind

### ISSUE THREAD

**Issue by cfmoore007** [Autodesk/maya-usd#330]
**Is your feature request related to a problem? Please describe.**
It would be great to have a different selection modes for USD prims, specifically by Kind ( i.e : component vs Xform ).

This is essential in the selection of large sets, and even out convenience with smaller assets such as the one attached.

**Describe the solution you'd like**
Option to change selection style ( similar to Maya's Hierarchy, Object, Component ).

In the very least, to have parity with USD View.

**Describe alternatives you've considered**
N/A

**Additional context**
![selectByKind](https://user-images.githubusercontent.com/2152250/75924359-cc78ca80-5e34-11ea-9ee1-86b1cd3c05d0.png)

Attached example file : 
[selectByKind.tar.gz](https://github.com/Autodesk/maya-usd/files/4289772/selectByKind.tar.gz)

Our example here is using the AL Plugin - so maybe this is a bug? @murphyeoin  / @robthebloke  we can file this separately as a bug.

But feature-wise this would be great to have w/ UFE.

**Comment by radon199** [comment]
I second this request. I brought it up as an option in one of the previous charter meetings.

Our current Maya plugin allows us to select by kind. This is important for us as layout artists work generally with a whole asset at once at first and they want to be able to select both individual meshes and assets in the viewport.

Currently in the maya plugin ( and just maya in general when working with references ) you have to select a mesh inside the asset and then walk up to the root to apply the transform.

**Comment by HdC-adsk** [comment]
PR #641 is in review.

@cfmoore007 @radon199 Can you build and test the branch and see if it works as what you expect? Note that the UI part is coming separately, so for now you can only override the selection behavior via an optionVar mentioned in the PR.

**Comment by radon199** [comment]
Working great for me, thank you for adding thi.
