### ISSUE TITLE
OSError: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by Acidpix** [Autodesk/maya-usd#331]
Hi i try to build maya plugins but i have an error and i try to fix this but i don't understand how it's wrong :

python build.py --maya-location /usr/autodesk/maya2020 --pxrusd-location /opt/USD  --devkit-location /opt/devkit/devkitBase  /usr/local/workspace

 Building with settings:
      Source directory          /root/maya-usd
      Workspace directory       /usr/local/workspace
      Build directory           /usr/local/workspace/build/RelWithDebInfo
      Install directory         /usr/local/workspace/install/RelWithDebInfo
      Variant                   RelWithDebInfo
      Python Debug              Off
      CMake generator           Default
      Build Log                 /usr/local/workspace/build/RelWithDebInfo/build_log.txt
      Stages arguments          ['clean', 'configure', 'build', 'install']
Traceback (most recent call last):
  File "build.py", line 597, in <module>
    BuildAndInstall(context, context.buildArgs, context.stagesArgs)
  File "build.py", line 366, in BuildAndInstall
    RunCMake(context, extraArgs, stagesArgs)
  File "build.py", line 268, in RunCMake
    extraArgs=(" ".join(extraArgs) if extraArgs else "")))
  File "build.py", line 137, in Run
    stderr=subprocess.STDOUT)
  File "/usr/lib64/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib64/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

**Comment by HamedSabri-adsk** [comment]
@Acidpix please follow the issue template. It is very hard to tell what the problem is without looking at the `build_log.txt`

**Comment by Acidpix** [comment]
Hi , Sorry i dont see the issue template. 
OS : Centos 7.7 
Compiler : gcc 6.3.1
Maya 2020
Maya USD commit : 176f60e217559f971cc961ef27f126cd52c60626
Pixar USD Commit : be1a80f8cb91133ac75e1fc2a2e1832cd10d91c8

[build_log.txt](https://github.com/Autodesk/maya-usd/files/4297508/build_log.txt)

**Comment by Acidpix** [comment]
I Found , sorry it my GCC and Cmake was wrong install
