### ISSUE TITLE
[MAYA-130726]'F' hotkey (outlinerEditor -showSelected) does not expand to 

### ISSUE THREAD

**Issue by ika-rporter** [Autodesk/maya-usd#3316]
**Describe the bug**
When you select Maya objects in the viewport referenced because of a MayaReference prim, mouse over the outliner, and press `F`, the outliner only expands to the MayaReference prim transform stand-in, not the selected object. 

**Steps to reproduce**
1. Load the `asset.usda` from the attached example.
2. Open the Outliner
3. Check `Display > Shapes`
4. Expand the USD Proxy and set the `rig` variant selection on `cube` to `anim`
5. Select the rig controls in the viewport.
6. Mouse over the outliner and press `F`
7. Observe the outliner only expands to the `rig` prim transform stand-in, not to the selected Maya object(s)

**Expected behavior**
When you select Maya objects in the viewport, mouse over the outliner, and press `F`, the outliner should expand to show the selected objects.

**Attachments**
[asset.zip](https://github.com/Autodesk/maya-usd/files/12552976/asset.zip)
![image](https://github.com/Autodesk/maya-usd/assets/68026610/59259995-daaf-40d6-bcdc-664d1398f40e)

**Specs (if applicable):**
 - CentOS 7
 - Maya 2023.3
 - MayaUSD 0.23.0
 - USD 0.21.8

**Comment by santosd** [comment]
I tested this and was able to repro the issue. We will discuss this with the team and see if it is something we can fix.

**Comment by santosg87** [comment]
just doing a bit of house cleaning. :) we have an internal ticket opened for this - MAYA-130726. 

after some investigation, the fix for this issue would require changes to the Maya code itself, so changes will only be visible on future maya versions.

**Comment by santosg87** [comment]
this issue should now be fixed on the latest mayaUSD versions.

note that the fix for this required changes within Maya code, so it will be available only on maya 2024.2. 

Closing this issue for now. :)
