### ISSUE TITLE
Skeletons without SkelBindingAPI do not import animation

### ISSUE THREAD

**Issue by dgovil** [Autodesk/maya-usd#3341]
**Describe the bug**
After we upgraded to USD 23.8, Maya USD no longer imports skeleton animation unless the SkelBindingAPI is applied to the Skeleton Prim.

I tried building the latest commit (b48151b889dc2241b91988d1daf6b468e2347bbc) and I see this issue.

This seems like some kind of incompatibility with USD 23.8 that I wanted to flag. I think skeleton animation should always import regardless of the binding. 

The docs on [UsdSkelBindingAPI](https://openusd.org/release/api/class_usd_skel_binding_a_p_i.html#details) also suggest it's only meant to be relevant to the geometry bindings. It's late so I didn't do a deep dive into the code, but it looks like it early exits if it can't get the bindings. 

I can understand if skinning/binding information didn't import (though I'd argue even in that case it should still import because it's not a runtime evaluation, and there are likely enough old files that would benefit from it)

**Steps to reproduce**
1. Import the attached file, it will have animation on the single joint
2. Edit the file and remove the SkelBindingAPI on line 46 and reimport. It will have no animation

**Expected behavior**
I think skeletons should still import animation regardless of whether SkelBindingAPI is applied or not. 

**Attachments**
[JumpingCube.usda.zip](https://github.com/Autodesk/maya-usd/files/12680290/JumpingCube.usda.zip)

**Comment by dgovil** [comment]
@spiffmon I think this might be a regression in USD 23.8.
I'll have to try and make a sample case before I report it to the USD repo (I'm not super familiar with the SkelCache API), but the Maya USD plugin is basically doing the following (slight pseudocode because it's spread out)

```
UsdSkelSkeletonQuery skelQuery = UsdSkelCache.GetSkelQuery(skel);
UsdSkelAnimQuery animQuery = skelQuery.GetAnimQuery();
animQuery.GetJointTransformTimeSamplesInInterval(args.GetTimeInterval(), times);
```

If `SkelBindingAPI` is not present, it always seems to return 0, whereas if skelBindingAPI is present, it returns the right number of samples

**Comment by spiffmon** [comment]
The documentation could and should be improved, @dgovil , but like **all** applied API schemas, no data encoded by the schema is considered "present" unless the API has been applied to the prim - all Hydra 2 behaviors are predicated on that.  So, while this _is_ a behavior regression from 23.05, the 23.05 (and earlier) `usdchecker` **will** have flagged it as an error, and `fixbrokenpixarschemas` will have fixed it.  I'd argue that if Hydra won't render it, Maya should not import it?

**Comment by dgovil** [comment]
In this case though the skeleton has no binding to a mesh, so there's no imageable for binding. 

Wouldn't that be a case where you don't need the schema , per the schema name/docs?

**Comment by spiffmon** [comment]
I'd still disagree, @dgovil : without the SkelBindingAPI applied, it should be as if the `skel:animationSource` does not exist.  Hydra is an example client, but the expectation is one that _all_ clients should be able to rely on.  We don't want any processing code needing to check for N different properties on every prim without an explicit declaration by the author that that related packet of data should be considered present.

And skeletons _can_ be imaged by Hydra also!

**Comment by dgovil** [comment]
Hmm fair enough. I'll close this issue out and maybe propose adding a warning message instructing users what to do when importing.
