### ISSUE TITLE
mtoh crashes maya when an empty proxyShape node is present

### ISSUE THREAD

**Issue by santosg87** [Autodesk/maya-usd#335]
**Describe the bug**
whenever a user tries to use GL (hydra) as a render delegate in Maya. if a ProxyShape node without a primPath exists, moth will crash maya. this does not happen on VP2.0.

**Steps to reproduce**
1. create an empty proxyShape ("createNode mayaUsdProxyShape")
2. without changing the prim path, switch the current viewport renderer to GL (Hydra)
3. Maya crashes.

alternatively, this can be easily repro by loading the attached scene to maya and switching renderer to GL(Hydra)

**Expected behavior**
The renderer should switch to GL (Hydra) without problems

**Attachments**
[empty_proxyShape.zip](https://github.com/Autodesk/maya-usd/files/4300011/empty_proxyShape.zip)
![mtoh_Crash](https://user-images.githubusercontent.com/3026529/76115952-0a9df780-5fb7-11ea-9bf0-77235747781f.gif)

**Specs (if applicable):**
- Maya beta
- Maya USD beta build (built with the PR113 beta)
- Pixar USD 20.05 Beta

**Additional context**
from the stack trace when crashing:
>	hdMaya.dll!pxrInternal_v0_20__pxrReserved__::HdMayaProxyAdapter::PreFrame	C++
 	hdMaya.dll!pxrInternal_v0_20__pxrReserved__::HdMayaProxyDelegate::PreFrame	C++
 	mtoh.mll!pxrInternal_v0_20__pxrReserved__::MtohRenderOverride::Render	C++
 	mtoh.mll!pxrInternal_v0_20__pxrReserved__::HdMayaRender::execute	C++

**Comment by santosd** [comment]
Marking as reproduced since this was logged by QA.

**Comment by santosg87** [comment]
this should be fixed now on PR115. :)
