### ISSUE TITLE
Distinguish the USD Shapes and regular Maya Shapes in the Outliner

### ISSUE THREAD

**Issue by stephanehoarau** [Autodesk/maya-usd#3357]
**Is your feature request related to a problem? Please describe.**
Actually, to see the prims of a Stage  in the Outliner, you need to check on the Outliner's menu option: Display > Shapes.
But, this option activates also the shapes for regular Maya DAG nodes, and sometimes this clutters the display.

**Describe the solution you'd like**
Would it possible to distinguish them, and have two options:
- one for regular Maya DAG nodes
- one specific for USD prims that you would name for example : Show Usd Prims

**Comment by seando-adsk** [comment]
Hi Stephane, this issue was actually fixed by #1454 but it requires Maya 2024. 

Sean

**Comment by stephanehoarau** [comment]
Thank you !
I close the ticket :)
