### ISSUE TITLE
[MAYA-105624] Wrong object translations after importing.

### ISSUE THREAD

**Issue by Xaia** [Autodesk/maya-usd#336]
**Describe the bug**
Weird translations on the Bot geometry after importing. Opening the same file as a Stage works just fine.

**Steps to reproduce**
1. Export Gaffer bot from Gaffer
2. Import bot.usd in maya

**Expected behavior**
No translations on the geometry.

**Attachments**
![hYqhWpXZPN](https://user-images.githubusercontent.com/60515654/76163505-ee30c500-6146-11ea-9d8d-931c8c78010d.gif)

**Specs (if applicable):**
 - Windows 10
 - Maya Beta PR113

**Comment by HamedSabri-adsk** [comment]
@Xaia Can you provide the ascii format(bot.usda) that was exported from Gaffer?  Thanks.

**Comment by Xaia** [comment]
@HamedSabri-adsk 
sure!
there you go

[gafferTest.zip](https://github.com/Autodesk/maya-usd/files/4303377/gafferTest.zip)

**Comment by HamedSabri-adsk** [comment]
@Xaia Great. Thank you!

**Comment by HamedSabri-adsk** [comment]
@Xaia @santosd  This issue should be fixed now. 
![import_fix](https://user-images.githubusercontent.com/48299423/108285497-34631680-7155-11eb-9fb8-04d110314c95.gif)

**Comment by HamedSabri-adsk** [comment]
Closing this issue as it is no longer reproducible.
