### ISSUE TITLE
[MAYA-122498] MTOH: Rotated mesh display issue

### ISSUE THREAD

**Issue by Xaia** [Autodesk/maya-usd#337]
**Describe the bug**
Hydra viewport rotates the shading back to original place. Model somehow stays in place. Check the GIF attached.

**Steps to reproduce**
1. Switch to MTOH
2. Open Kitchen as Stage
3. Rotate it 90 degrees
4. Turn on the lights

**Expected behavior**
Well, I would expect model to stay in place.

**Attachments**
![svUQ0USqTf](https://user-images.githubusercontent.com/60515654/76163618-ecb3cc80-6147-11ea-8bbb-f4d440843604.gif)

**Specs (if applicable):**
 -  Windows 10
 -  Maya Beta PR113

**Comment by santosd** [comment]
I took a look at this and was also able to replicate in PR113. It seems in hydra that the cage selection cage is moved but the shading doesn't update. Another thing to note is that rotating after shading is turned on or off updates the selection. However, if you switch between VP2 and Hydra after that it goes back to showing the issue.

**Comment by santosg87** [comment]
I retested this issue on MayaHydra and this seems to be working correctly now. closing this issue for the time being.
