### ISSUE TITLE
Hiding objects and Changing variants UfeCmd error

### ISSUE THREAD

**Issue by Xaia** [Autodesk/maya-usd#338]
**Describe the bug**
Getting this error while trying to hide or change the variants in the Kitchen set.

 `# Error: AttributeError: file C:\Program Files\Autodesk\Maya2021\Python\lib\site-packages\maya\internal\ufeSupport\ufeCmdWrapper.py line 39: 'module' object has no attribute 'ufeCmd' #
`

**Steps to reproduce**
1. Open Kitchen set stage
2. Try to hide / change variation

**Expected behavior**
I should be able to hide and change variations

**Specs (if applicable):**
 - OS & version [e.g. Windows 10]
 - Maya Beta PR113

**Comment by santosd** [comment]
I checked this in PR113 and I am able to Make Visible and Invisible. However, I am not able to change the Variance when I am using the Hydra Viewport renderer. If I am in VP2 I am able to change the variants without issues. The error I am seeing is one that is already logged:
`# Error: RuntimeError: file ...\Python\lib\site-packages\maya\app\ufe\outlinerSupport.py line 54: Collection not found, or no current collection. # `

I am not hitting the error reported here.

@Xaia could you check on your end to see if this is happening in VP2 or Hydra?

Thank you.

**Comment by Xaia** [comment]
@santosd 
Hi there!
I have installed fresh PR114. Same problem. It is not working on both Hydra and VP2. 
![sx2DDRSIeD](https://user-images.githubusercontent.com/60515654/78355722-78394580-75ae-11ea-98e6-b5b7bb224e0a.gif)

**Comment by santosd** [comment]
Hi @Xaia,
I tested again and on my end and am not seeing the issue in PR114 at all. I checked our backlog and it seems a similar issue to this was resolved recently.

One thing I would suggest trying incase it is causing any issues is to clear the Maya preferences to see if that helps in anyway. If it still fails, let's see if it is fixed in the next build we release with the fix that was recently implemented.

**Comment by santosg87** [comment]
Hi @Xaia, I am currently investigating this - we saw the same error you mentioned on a different scene recently, we are investigating a bit deeper to try and narrow down the issue here. 

Cheers!

**Comment by Xaia** [comment]
Once I run 

`from maya import cmds
cmds.ufeCmd`

I can change variants and make stuff invisible.

**Comment by ppt-adsk** [comment]
Can you check whether the ufeSupport plugin is loaded in Maya?

**Comment by Xaia** [comment]
yes, right now is loaded. I am guessing the plugin is not loading after fresh Maya installation, although my colleague has similar issue and this command does not help.

**Comment by kxl-adsk** [comment]
@Xaia it's unclear to me if there is still something for us to do here?
