### ISSUE TITLE
Arnold not rendering the stage

### ISSUE THREAD

**Issue by Xaia** [Autodesk/maya-usd#339]
**Describe the bug**
Arnold not rendering the stage. Only way to render with arnold at this point is through Standin procedural. 

**Steps to reproduce**
1. Open kitchen set as a stage
2. Add lights
3. Try to render

**Expected behavior**
Render object with shader assigned.

**Attachments**
![VAu9Lg38ZD](https://user-images.githubusercontent.com/60515654/76163817-c2fba500-6149-11ea-9ec4-aa787afe2516.gif)

**Specs (if applicable):**
 - Windows 10
 - Maya Beta PR113

**Comment by kxl-adsk** [comment]
@Xaia which version of `mtoa` you were using? FWIW. As a workaround, you can use arnold render delegate with `mtoh`.

**Comment by Xaia** [comment]
@kxl-adsk 
The one available for Maya Beta PR 113 which is MTOA 4.0.3 if I am not mistaken.

**Comment by santosg87** [comment]
@Xaia tthe current support for arnold indeed depends on the standin workflow in order to render. (or using the mtoh render delegate as @kxl-adsk mentioned). :)

with that said, I can see the workflow you mention as something useful for sure. thanks for bringing this up

**Comment by santosg87** [comment]
I was able to test this internally, and it is something we are working on. it should be fixed on the next beta :)

**Comment by santosg87** [comment]
@Xaia this one should be fixed on PR114, would you be able to validate and close it?

**Comment by santosg87** [comment]
marking this one as closed based on my last comment - @Xaia if this is still a problem, feel free to re-open. :)
