### ISSUE TITLE
[MAYA-105820] Exported Instances are not importing

### ISSUE THREAD

**Issue by Xaia** [Autodesk/maya-usd#340]
**Describe the bug**
Exported Instances as USD are not importing at all. Stage works just fine.

**Steps to reproduce**
1. Create instances
2. Export as USD
3. Import USD

**Expected behavior**
I should be able to import Instances as Maya native and be able to edit them.

**Specs (if applicable):**
 - Windows 10
- Maya Beta PR113

**Comment by santosg87** [comment]
thanks for logging this. I can also reproduce this on my side. it seems to be a problem on the import side specifically, as the geometry shows up as expected when using a proxyShape.

**Comment by mattyjams** [comment]
Just wanted to flag that I think this probably duplicates #310, which Luma had implemented a solution for a while ago.
