### ISSUE TITLE
Selected instanced object is slowing down 5x the viewport

### ISSUE THREAD

**Issue by Xaia** [Autodesk/maya-usd#341]
**Describe the bug**
Selected instanced object is slowing down the viewport (MTOH and VP2)

**Steps to reproduce**
1. Bring in instanced stage with or without animation
2. Select the object

**Expected behavior**
There should be no such big slowdowns. 

**Attachments**
![VhBB107mbt](https://user-images.githubusercontent.com/60515654/76163962-086ca200-614b-11ea-8e62-d89611d2345e.gif)

**Specs (if applicable):**
 - Windows 10
- Maya Beta PR113

**Comment by kxl-adsk** [comment]
@Xaia This is using VP2 render delegate? (not mtoh)

**Comment by Xaia** [comment]
@kxl-adsk 
It's both, MTOH and VP2

**Comment by kxl-adsk** [comment]
Selection is handled very differently in VP2RenderDelegate vs mtoh. We may decide to split this into two separate issues.

**Comment by HdC-adsk** [comment]
@Xaia Thanks for reporting the issue.

This is not selection performance but the selection highlight wireframe draw performance.

I notice that there is a USD point instancer in the scene in the recording. I don't think VP2 has the support yet. Is it possible to share us with the scene? Thanks.

**Comment by Xaia** [comment]
@HdC-adsk 
yes, this is an instanced animation. 
file is too big to upload here, link to gdrive instead:
https://drive.google.com/file/d/1KvqjAG3sXCgfrhnXkvUtiePpdIWmbRjf/view?usp=sharing

**Comment by HdC-adsk** [comment]
@Xaia Thanks for sharing.

**Comment by HdC-adsk** [comment]
On a NVIDIA Quadro M2000 card I can see a 2x slow down when displaying selection highlight. The scene drawing performance is bound on GPU according to Maya profiler, and when selection highlight is displayed there are nearly 2x GPU workloads (normal shaded + green wireframe), so I think the 2x slowdown makes sense.

@Xaia Can I ask about your machine config, esp. GPU? We will need this info to reproduce the issue.

@santosg87 Can you reproduce the 5x slowdown?

For record, here is the Maya [profile](https://github.com/Autodesk/maya-usd/files/4326690/InstancingSelectionHighlight.txt) I get from the scene using the following MEL script.

`profiler -reset;`
`profiler -sampling true;`

`select -cl;`

`for ($i=1; $i <= 10; $i++)`
`{`
`    refresh;`
`}`

`select -r Mash_instancer_animation_usdShape;`

`for ($i=1; $i <= 10; $i++)`
`{`
`    refresh;`
`}`

`select -cl;`

`profiler -sampling false;`

**Comment by Xaia** [comment]
@HdC-adsk 
I am running maya on 2x GTX 1070 8gb, Ryzen 9 3950x, 64gb 3600mhz memory and samsung gen3 m.2 hdd.

**Comment by santosd** [comment]
I took a look on a machine with an Nvidia Quadro 5000 and in the viewport when I turn on the frame rate, I am seeing a little more than 2x slower when I have the USD instanced object selected. Without selection I see a frame rate of about 15.2 and with the selection I see a frame rate of about 5.6 Here is the [profile](https://github.com/Autodesk/maya-usd/files/4331343/ds_instancingProfileTest.txt) I got using @HdC-adsk 's script.

**Comment by santosg87** [comment]
@Xaia are you able to test this on PR116 and close it? the PR is available for download and should contain the fix, as mentioned by williamkrick :)

**Comment by Xaia** [comment]
@santosg87 Just checked if something changed in the new version and I am getting worse results than in PR113. 
![34pVNI35iy](https://user-images.githubusercontent.com/60515654/86643502-0b827c80-bfdd-11ea-98ba-34b7e3165348.gif)

**Comment by Xaia** [comment]
Recreated the scene with 100k spheres and published fresh usd file and its actually much better. Getting 25 frames without selection and 10 with selection. 
I guess old file has issues.
Cheers!
