### ISSUE TITLE
Framing in outliner is not working

### ISSUE THREAD

**Issue by Xaia** [Autodesk/maya-usd#342]
**Describe the bug**
Framing in outliner is not working. Going straight to selected object in the viewport is impossible. 

**Steps to reproduce**
1. Bring the kitchen set
2. Select object in the viewport
3. Focus the outliner
4. Press F to frame the object in outliner

**Expected behavior**
I should be able to frame the object in outliner like normal maya native objects. 

**Specs (if applicable):**
- Windows 10
- Maya Beta PR113

**Comment by kxl-adsk** [comment]
Thank you for reporting. This is something we are currently working on.

**Comment by seando-adsk** [comment]
Internally this was logged as: MAYA-96174 - UFE: outliner framing doesn't behave properly
It will be fixed in the next Maya beta.

**Comment by santosg87** [comment]
@Xaia this should be fixed on our most recent beta - would you be able to validate and close it? :)

**Comment by Xaia** [comment]
@santosg87 yes! I already checked it. Working like charm!

**Comment by santosg87** [comment]
thank you! :)
