### ISSUE TITLE
Selection Mask to limit selection to specific kinds

### ISSUE THREAD

**Issue by philsloggett** [Autodesk/maya-usd#3425]
When doing layout work typically you're only interested in selecting the root prim of any referenced asset. This prim should be marked as a Component kind. Selecting specific children, (e.g. panels of a car, leaves of a tree, clothes of a character, etc) can lead to accidental offsets that can be difficult to undo or zero out, when all that was intended was to place the car, tree, character within the stage.

Some other applications allow you to choose which _kinds_ are available for viewport selection, which is incredibly important for artists to be able to select objects in the viewport they intend to be interacting with.

Ive been able to work around this with a selection-changed callback. As a user selects any prim we step up through the USD hierarchy until it hits a prim of kind "component" and manages the selection list to select this _instead_ of the prim the user clicked on. This works to an extent - the big limitation being that an object can't be _deselected_ in the viewport, as when a descendent prim is reselected there is no way of knowing the intent was to deselect its parent Component.

I believe this could only be correctly implemented in the plugin itself.

**Comment by santosg87** [comment]
@philsloggett we currently do have an implementation of a selection by kind, which i believe does what you are expecting to see:
![Screenshot 2023-10-31 at 1 09 03 PM](https://github.com/Autodesk/maya-usd/assets/3026529/463bbeb2-b874-46c0-87f8-25d2f936b12b)

is that selection not behaving as expected for you?

**Comment by philsloggett** [comment]
That works _perfectly_ thank you @santosg87 (possibly some bugs in the pointinstancer) embarassed I hadnt found that menu.

**Comment by womanyoyoyo-adsk** [comment]
Hi @philsloggett, don't be embarrassed. It just tells us that it's not intuitive to find. You can tear off the menu by clicking the dotted lines on top of the submenu and keep it handy. Out of curiosity, where would in the UI were you expecting to find it?

**Comment by philsloggett** [comment]
Hey good question @womanyoyoyo-adsk 

Im a reasonably experienced Maya user (~17 or so years) and truthfully I _never_ go in to the "Select" menu. The few menuitems in there I would actually use frequently (select inverse, object/component toggle, shrink/grow selection) I'd lean on hotkeys for.

To me the most analogous, pre-existing, maya concept is selection masking which I'd expect to see in the status bar something like these.
![image (72)](https://github.com/Autodesk/maya-usd/assets/9799332/144c66c8-fbb1-4c00-ad25-ac48959f3ea6)
![image (71)](https://github.com/Autodesk/maya-usd/assets/9799332/13967e0d-5551-4cab-8230-df544980fb19)

If Im being honest I dont find maya's "select by hierarchy: root" option all that intuitive either - but that _is_ where I looked just because I was aware there was similar maya feature there.

Its dumb and obvious but I just didnt think to look in the Select menu :) 

Im also clicking around the outliner on the proxy shape and various prims, and right clicking on shapes in the viewport to see what kind of options jump out at me there. 

Appreciate the question!

**Comment by womanyoyoyo-adsk** [comment]
Thanks for this info @philsloggett.
