### ISSUE TITLE
Can't switch over to mtoh in maya2020, instant crash

### ISSUE THREAD

**Issue by suesauer** [Autodesk/maya-usd#348]
**Describe the bug**
1.Installed usd for Maya 2020, mtoh crashes Maya see video and image, 
2.also the arnold delegate is missing completely 
3.and pxrusd.so fails to load

**Steps to reproduce**
Steps to reproduce the behaviour:
Open maya, load plugins then try to switch to the hydra delegate.

**Expected behavior**
To be able to switch to the hydra delegate and load Usdpxr.os

**Attachments**
Image:
![Screenshot from 2020-03-10 13-55-28](https://user-images.githubusercontent.com/58251706/76310353-4f879e00-62d7-11ea-9c32-36993ae17e71.png)
Video:
[2020-03-10 14-01-38.mkv.tar.gz](https://github.com/Autodesk/maya-usd/files/4312308/2020-03-10.14-01-38.mkv.tar.gz)

**Specs (if applicable):**
 - OS & version linux centos 7
 - Compiler & version gcc 6.3.1
 - Maya version Maya 2020
 - Maya USD commit dev at 631a291
 - Pixar USD commit dev at 893c8e4

**Additional context**
Built fresh today(10 March)
'// Error: file: /usr/autodesk/maya/scripts/others/pluginWin.mel line 317:  (mtoh) // '
not sure if this is related

**Comment by kxl-adsk** [comment]
@suesauer Any chance that you are pointing to a different USD version (in the mod file) than what you built maya-usd plugin with?

**Comment by santosg87** [comment]
@suesauer I also noticed that your MayaUsd seems to be quite old. it might be helful to buld it at a more recent commit. :)

**Comment by suesauer** [comment]
I will rebuild all this week this week to see if there is some environment issues, and report back

**Comment by santosd** [comment]
Hi @suesauer, I wanted to check back to see if you had any success with the rebuild. I also wanted to see if you had any luck with the [binaries](https://github.com/Autodesk/maya-usd/releases) we released for Maya USD.

**Comment by suesauer** [comment]
Yup all good now, loads and doesn't crash. Mind you I still need to add the Arnold delegate back into the mix ,so will see if that was what was causing issues.

**Comment by suesauer** [comment]
Seems totally fine now even when I add Arnold delegate in Thanks guy's
