### ISSUE TITLE
Unable to get all USD stages from mayaUsd.lib.StageCache

### ISSUE THREAD

**Issue by BigRoy** [Autodesk/maya-usd#3480]
**Describe the bug**

When running this code:
```python
import mayaUsd
cache = mayaUsd.lib.StageCache.Get(True, True)
stages = cache.GetAllStages()
print(stages)
```

I get an empty list; no matter whether I have active `mayaUsdProxyShape` instances in my scene or not.
However, asking around on ASWF slack `wg-usd` channel others were able make this work.

In their case, maya 2024.0 + maya usd 0.23.0, getting wit the same code e.g. the following result :

```python
[Usd.Stage.Open(rootLayer=Sdf.Find('anon:000001A25196DE40:anonymousLayer1'), sessionLayer=Sdf.Find('anon:000001A25196D1E0:anonymousLayer1-session.usda'), pathResolverContext=Ar.ResolverContext(Ar.DefaultResolverContext())), Usd.Stage.Open(rootLayer=Sdf.Find('d:/588/scene.usda'), sessionLayer=Sdf.Find('anon:000001A25196E680:scene-session.usda'), pathResolverContext=Ar.ResolverContext(Ar.DefaultResolverContext(['D:\\588\\'])))]
```

Is this a regression?

**Steps to reproduce**
1. Launch Maya
2. Create some proxies
3. Run the example code

**Expected behavior**

Be able to retrieve any of the current session's `Usd.Stage` from the cache.
I expect the code snippet to list all used stages by Maya's plugin.

**Specs (if applicable):**

 - OS & version: Windows 10
 - Maya version: 2024.2
 - Maya USD commit: 0.26.0 (release)

**Additional context**

I'm not entirely sure whether this cache is intended to be accessible, but since others did get output in an older version I figured it'd be good to report that I was unable to get any results from it.

**Comment by pierrebai-adsk** [comment]
I think it comes down to a change in our internal implementation. You now have to passs False, True to get the cache:
```
import mayaUsd
cache = mayaUsd.lib.StageCache.Get(False, True)
stages = cache.GetAllStages()
print(stages)
```

**Comment by BigRoy** [comment]
> I think it comes down to a change in our internal implementation. You now have to passs False, True to get the cache:
> 
> ```
> import mayaUsd
> cache = mayaUsd.lib.StageCache.Get(False, True)
> stages = cache.GetAllStages()
> print(stages)
> ```

This does indeed work.
