### ISSUE TITLE
USD Proxy's load "empty" Maya2020

### ISSUE THREAD

**Issue by suesauer** [Autodesk/maya-usd#349]
**Describe the bug**
Load a usd asset in Maya 2020, loads empty.

**Steps to reproduce**
1. Open Maya 2020
2. in USD dropdown menu import a proxy
3. Loads usd asset but its empty see video below

**Expected behavior**
To load a full asset like shown in houdini, this use to work in Maya 2019.1

**Attachments**
Video:
[2020-03-10 14-45-46.mkv.tar.gz](https://github.com/Autodesk/maya-usd/files/4312485/2020-03-10.14-45-46.mkv.tar.gz)

**Specs (if applicable):**
 - OS & version Linux centos 7
 - Compiler & version gcc 6.3.1
 - Maya version Maya 2020
 - Maya USD commit dev at 631a291
 - Pixar USD commit dev at 893c8e4

##### Also:
Import is pretty broken as well
[2020-03-10 15-10-13.mkv.tar.gz](https://github.com/Autodesk/maya-usd/files/4312573/2020-03-10.15-10-13.mkv.tar.gz)

Thanks

**Comment by fowlertADSK** [comment]
@suesauer Can you confirm that the commit you are using is correct?  You are using a dev branch build from last September?  

I was watching your videos but none of the text is visible to me so it was hard to make out a few things.  I thought I saw some things in the UI that hit the dev branch much later than last September so I just wanted to double check on what exactly you were using.

**Comment by suesauer** [comment]
Sorry at this point I had build against the latest commit, forgot to update that line.

**Comment by santosg87** [comment]
hi @suesauer, are you able able to share the barrel.usd file with us? any more info on how it was built? the fact you are getting an error on import as well points out it might be something more than just the proxyShape being empty. We would love to dive a bit deeper investigating this. :)

**Comment by suesauer** [comment]
weird this barrel asset worked yesterday in Maya 2019.1. I can share the asset yes, but I know it works in houdini 18.0.348 soooo not sure its an import issue because of the asset....
FYI:
It says the file is to big... where can I save the barrel for you?

**Comment by suesauer** [comment]
Heres me trying to import the kitchen set
[2020-03-10 16-33-14.mkv.tar.gz](https://github.com/Autodesk/maya-usd/files/4312960/2020-03-10.16-33-14.mkv.tar.gz)

**Comment by santosg87** [comment]
that's super strange! thanks for the kitchen set video. it does seem like it's something on the plugin side - that hard crash shouldn't be happening at all. I don't think we will need to test your asset in this case. 
one thing i noticed, is that your mayaUsd plugin is a bit out of date compared to your pixar USD. 

when you import your proxyshape - are you getting any messages on the terminal window? i see your script editor doesn't seem to show any error messages, but there is a chance something is getting shown at the terminal.

**Comment by suesauer** [comment]
### When loading the plugin:
AL_USD
// Error: file: /usr/autodesk/maya/scripts/others/pluginWin.mel line 317: initializePlugin function failed (AL_USDMayaTestPlugin)
PXR_USD
# Error: file: /usr/autodesk/maya/scripts/others/pluginWin.mel line 317: ImportError: file <maya console> line 1: No module named UsdMaya # 
// Error: file: /usr/autodesk/maya/scripts/others/pluginWin.mel line 317: initializePlugin function failed (pxrUsd) // 
MayaUSDPlugin
no error

### When trying to load assets:
AL_USD
No errors just crashes
PXR_USD
no errors just crashes
Maya_usd
no errors just crashes

#Re installed pxar usd and maya usd today
PXR USD
$ git status
# HEAD detached at 87e0dc5

Maya USD
$ git status
# On branch dev
nothing to commit, working directory clean
latest commit cloned down
commit 38185d27eb13e11398f420ced7e53f3852571a56
Merge: 1aab25c fb155cb
Author: Krystian Ligenza <krystian.ligenza@autodesk.com>
Date:   Fri Mar 13 10:30:15 2020 -0400

    Merge pull request #345 from mattyjams/pr/usdImaging_PopulateSelection_usdPath_param
    
    adapt to UsdImagingDelegate::PopulateSelection param change

**Comment by suesauer** [comment]
### some more info:

cmake version 3.15.4
Python 2.7.5 (default, Aug  7 2019, 00:51:29) 
gcc (GCC) 6.3.1 20170216 (Red Hat 6.3.1-3)
ninja-1.9.0.post1
pyyaml 3.10
pyside 1.2.4
pyopengl 3.1.0
jinja2 2.10.1

centos-release-7-7.1908.0.el7.centos.x86_64
Maya 2020
Maya devkit 2020

pixar master v19.11

**Comment by santosg87** [comment]
just to make sure I understand and I'm not assuming anything - after rebuilding, you are still seeing the problem. with the sync commit 38185d2 - is that correct?

**Comment by suesauer** [comment]
yup still seeing it.

**Comment by santosg87** [comment]
thanks for the info. we are still investigating this.

would you be able to give a try with the packaged release and see if the same is happening there for you too? 
it can be found here: 
https://github.com/Autodesk/maya-usd/releases/tag/v0.1.0


I'm wondering if there are any env vars that could be affecting it on your side.

cheers!

**Comment by suesauer** [comment]
I figured this one out. It was fighting with my Houdini env vars for pxr.  Just so you guy's know
