### ISSUE TITLE
Does the exporter support blendshapes?

### ISSUE THREAD

**Issue by emilche** [Autodesk/maya-usd#35]
When I export my character the blendshape animations does not export. When exporting with skeleton that is. it animates fine if I animate without skeleten as it goes into points mode.

**Comment by BigRoy** [comment]
@emilche could you describe which exporter you used and which branch/version?

Note: I am not sure whether it should work with any of the versions. But knowing exactly what you tried and which code base you were using might allow others to try and reproduce issues or see if the code is there.

**Comment by santosg87** [comment]
HI @emilche thanks for logging this - This might be something that is fixed on most recent builds. I was able to export my animation both on verts and blend shapes, and could confirm that the animation data was indeed exported. :)

would you be able to test this again using a more recent version of the mayaUsd plugin? 

Cheers!

**Comment by santosg87** [comment]
Closing this one based on the amount of information available, and considering this works in our testing. if needed we can re-open this later. :)
