### ISSUE TITLE
[MAYA-122481] Crash performing Preview Render with Hydra enabled

### ISSUE THREAD

**Issue by santosd** [Autodesk/maya-usd#350]
**Describe the bug**
When using Hydra in the viewport if you click the preview render button. Maya will crash.

**Steps to reproduce**
1. Open a USD Scene through the "Create > Universal Scene Description (USD) > Stage From Existing Layer..." menu.
2. Change the viewport renderer to Hydra. "Renderer > GL (Hydra)"
3. Click on the icon for "Render Current Frame" or go to the rendering menu and click on "Render > Render Current Frame"
4. Maya should crash.

**Expected behavior**
The Render Current Frame Should Render Black as it does when in VP2 and no crash should occur.

**Attachments**
![hydra_softwareRenderCrash](https://user-images.githubusercontent.com/29235905/76442709-b53b5f00-6397-11ea-9e1c-709d3a21d0a3.gif)

**Specs (if applicable):**
- Windows 10
- Nvidia Quadro 5000
- PR113
- 8 Gigs RAM

**Comment by santosd** [comment]
Even easier repro steps no need to open a USD scene:
1. Select Hydra as the Viewport renderer.
2. Render Current Frame and crash.

This is happening when running a Render Current Frame using Software Render and Maya Vector. It Doesn't occur with Arnold or Hardware renderers.

**Comment by santosg87** [comment]
marking this one as unassigned as we decided the next steps.

**Comment by santosg87** [comment]
I have tested this on the latest build of mayausd and it seems to be fixed now.
