### ISSUE TITLE
Update the readme for clarity on installing releases

### ISSUE THREAD

**Issue by capraMambrica** [Autodesk/maya-usd#3512]
**Is your feature request related to a problem? Please describe.**
A an artist who is an absolute beginner to GitHub, I would like clear steps to "Install" the "Releases", so that I can take advantage of USD in my workflows. 

**Describe the solution you'd like**
A simple line or two added to the Readme would suffice:
> **Installation**
> Download the and install the latest release for your platform [here](https://github.com/Autodesk/maya-usd/releases)!

**Describe alternatives you've considered**
I spent considerable time fumbling around, trying to build the code myself, but actually got blocked building openUSD on a silicon, which I feel blocked me from installing mayaUSD. When eventually learned that there releases available to me, I felt kinda silly. 

**Additional context**
As USD matures, we'll be seeing more artists wanting to update their Maya plugin the latest, and most will not event attempt to build. We should reduce all friction when getting the latest releases in their hands, so we'll get more hands on the tools.

**Comment by santosg87** [comment]
thank you for the recommendation! it definitely doesn't hurt to have helpful links with more visibility. I can update our documentation to reflect that. :)

**Comment by santosg87** [comment]
#3524 should take care of this. :)
