### ISSUE TITLE
Mesh Subsets not created when using Duplicate as USD Data

### ISSUE THREAD

**Issue by johnhable** [Autodesk/maya-usd#3525]
**Describe the bug**
When converting a mesh with multiple materials to USD, subsets are not getting created.

**Steps to reproduce**
1. Create a mesh (such as a sphere)
2. Apply a material to the mesh (in this case, a new USDPreview material)
3. Select several polys
4. Apply a different material to those polys.
5. Right click, and select Duplicate as USD data to add to a stage.

**Expected behavior**
The mesh should appear in the stage with two subsets.

**Attachments**
Here is a dropbox linke to the .mb file, just before applying to the stage.
https://www.dropbox.com/scl/fi/1iy2ydgsv5oaq95vba6pe/sphere-test.mb?rlkey=bql7um2j0tzz3gv9nf1q0zeff&dl=0

Here is the exported .usd file.
https://www.dropbox.com/scl/fi/heoycbkzbr1q3kskz4k6q/sphere-test.usd?rlkey=okgwgzhg033pmunrfxudm4tlw&dl=0

**Specs (if applicable):**
 - Windows 11
 --- using version included with released Maya 2024

**Additional context**
Note that if I export the scene to usd, and then import that file from the USD Layer Editor, the file loads as expected.

Here is a screenshot of the scene after using convert to USD data from the right-click menu.
<img width="1308" alt="convert-from-maya-data" src="https://github.com/Autodesk/maya-usd/assets/24649255/77aba742-ac55-4815-866e-8742a9045c3c">

Here is a screenshot of the scene after exporting to usd and importing again as a USD layer.
<img width="1308" alt="import-from-stage" src="https://github.com/Autodesk/maya-usd/assets/24649255/bd7cc58a-e805-4a68-b19c-d88604e8b4d0">

**Comment by santosd** [comment]
Hello @johnhable 
Thank you for reporting this issue. I took a look and it seems that what is going on is that the Material option in your Duplicate as USD Data is not selected. If you select a Material option such as USD Preview Surface and then apply the settings and try again you should get the same as when you export:

https://github.com/Autodesk/maya-usd/assets/29235905/10798e9f-6738-42a5-9476-6b460503aaa7

**Comment by johnhable** [comment]
Thanks for the info, and apologies for the late reply (holidays). That fixed it, and I'll close it out.
