### ISSUE TITLE
Any plan to offer compiled plugins?

### ISSUE THREAD

**Issue by fdan** [Autodesk/maya-usd#360]
Hi, just wondering, is there any plan to provide compiled versions of the plugins?

As we are now looking to increasingly support remote work, it would be really nice if it was comparitively easy for people to install these plugins at home.  

Is there a timeline for Maya to ship with these?  And also compiled versions here on gitub?  Cheers.

**Comment by kxl-adsk** [comment]
Something we are aware of and looking into. Hopefully, very soon you will see an update on this.

**Comment by fdan** [comment]
Awesome, sounds good!

**Comment by mrharris** [comment]
I just noticed 0.1.0 was released as a binary

I just want to confirm - this includes only the `adsk` plugin? I can only see the ability to 

- Create -> USD -> Stage from existing Layer
- File -> Import / Export USD 

So things like the AETemplate for mayaUsdProxyShape is empty, and there is no outliner context menu. Is this expected?

Upon loading the plugin, I also hit 
```
# Traceback (most recent call last):
#   File "C:\Users\lukeh\Documents\maya\2020\plug-ins\MayaUSD\lib\python\mayaUsd\schemas\__init__.py", line 16, in <module>
#     import _schemas
# RuntimeError: extension class wrapper for base class class pxrInternal_v0_20__pxrReserved__::UsdGeomXformable has not been created yet
```

Thanks for the binaries!

**Comment by wtelford** [comment]
Hey mrharris,

Thanks for pointing this out. The complete native integration of the Maya USD plugin depends on new API  (collectively know as UFE) built in to Maya. UFE first shipped in 2019 and also with 2020. The shipped versions of this api enables things like outliner and direct manipulation in the viewport.

The AE integration and Outliner context menu work requires additional UFE API's which are currently only testable in the Maya beta PR releases. If you are a part of the Maya Beta program, the most recent PR has a current Maya USD plugin compiled and installed.

I am currently working on a document to document what features may not be currently available in released versions of Maya.

**Comment by fdan** [comment]
Nice to see the release!

However, couple of questions.  For a variety of reasons we're stuck on Maya 2018 for now.  I take it the adsk plugin won't work with 2018 due to UFE.  

Is there any possibility of getting the Pixar an AL plugins built for download?  We compile these in-house already for linux, but now home users want them on Windows, and we don't have the infrastructure to investigate a new set of builds on a different OS.  

Presumably Autodesk builds these for testing?  It would be easy to release?

**Comment by kxl-adsk** [comment]
@fdan sorry for the delay in response. 

We currently have no plans to distribute Pixar and AL plugin binaries. While I understand that this is not ideal in the situation you are describing, we want to encourage the testing of a single plugin and collect feedback about gaps. This will help us prioritize the work.

**Comment by kxl-adsk** [comment]
@fdan Can we close this issue?

**Comment by fdan** [comment]
Hi, yes, sorry fine to close, cheers
