### ISSUE TITLE
mtoh crash when loading

### ISSUE THREAD

**Issue by ChokmahBinah** [Autodesk/maya-usd#363]
Hello there,

I posted a message here some times ago, about some crashes during mtoh loading.
After doing some test with pdb patch 
I was suggest to ask Pixar USD forum about it, but here is the answer I got :

Thanks @ChokmahBinah -- we don't maintain mtoh here, please file an issue on the Autodesk project page here: https://github.com/Autodesk/maya-usd and hopefully someone there can help you out.

So I don't know where to ask about it now. 

The steps to reproduce the crash :

1-Launch Maya
2-Load Maya USD plugin
3-Load mtoh plugin

Sometime it works but Maya crashes very often at this step.

Thank you in advance.

**Comment by kxl-adsk** [comment]
Let’s continue the conversation in the original issue you opened (it has all the details) and close this one. In that issue, please provide the information on how you reported this to Pixar (so I can help add more details to the discussion if necessary).

**Comment by ChokmahBinah** [comment]
OK I'll do that.

Thank again @kxl-adsk :)
