### ISSUE TITLE
[MAYA-102675] userExportedAttributesUI | cannot import name QStringListModel

### ISSUE THREAD

**Issue by mhamid3d** [Autodesk/maya-usd#366]
The ```userExportedAttributesUI``` python file is trying to import ```QStringListModel``` from ```PySide2.QtGui```. On PySide2 I found that this class in fact lives in ```QtCore``` instead.

1. Open any version of Maya using PySide2, open Script Editor
2. Run the following code in a python tab:
```
from pxr.UsdMaya import userExportedAttributesUI
```

This code yields the following error:

```# Error: ImportError: file /.../plugin/pxr/lib/python/pxr/UsdMaya/userExportedAttributesUI.py line 52: cannot import name QStringListModel # ```

SPECS -
 - Linux CentOs 7 x64
 - Maya 2020

**Comment by santosd** [comment]
I was able to reproduce this in PR114 with the Pixar plug. I think this one is definitely specific to the pxr plug-in. Maya USD doesn't contain userExportedAttributesUI from what I can see. Will speak with the team to see what we can do about this issue.

**Comment by santosg87** [comment]
it's worth giving a try on this with an older build that hasn't updated Qt to confirm.

**Comment by mattyjams** [comment]
Hi @mhamid3d, thanks for reporting this, and sorry it has languished so long. It somehow managed to slip by me earlier this year, and we've not yet tried to use this UI with Maya 2020+ which is where it starts to appear, so we hadn't tripped over it yet.

I just put up #812 which should address this.

**Comment by mattyjams** [comment]
This should be resolved in the dev branch with the merge of #812.

Thanks!
