### ISSUE TITLE
Textures are missing when using "Edit As Maya Data"

### ISSUE THREAD

**Issue by RichardFrangenberg** [Autodesk/maya-usd#3672]
**Describe the bug**
When rightclicking a USD prim and selecting "Edit As Maya Data" I get the following error and the material of the Maya object doesn't have any textures:
// Warning: Value 'Absolute' is not allowed for flag 'importRelativeTextures'; using fallback 'none' instead

**Steps to reproduce**
Create a stage with geo and assign a MaterialX Standard Surface material with a diffuse texture.
Rightclick the geo USD prim and select "Edit As Maya Data".

**Expected behavior**
The textures should be converted to the Maya material and be visible in the viewport.

**Specs (if applicable):**
 - Windows 10
 - Maya 2024.2
 - Maya USD 0.27.0

**Comment by wallworm** [comment]
Thank you for reporting. We will look into it.

**Comment by santosd** [comment]
Hi @RichardFrangenberg , I took a look at this and I was not able to reproduce your error. I was testing in Maya 2024.2 using Maya USD 0.27.0. Attached is a video of my workflow, I am using LookdevX to assign the materialX shader to the Maya USD prim torus and adding the texture file and connections through the LookdevX Editor. Do you have materials enabled in the Edit As Maya Data options? I think the warning about the relative vs absolute falling back to none is not what is causing the issue, though I do think it is a strange warning. I will need to look into why we are getting that.

https://github.com/Autodesk/maya-usd/assets/29235905/7a6ff7a3-efd4-4a93-83ff-6fef94972186

**Comment by RichardFrangenberg** [comment]
Hey @santosd thanks for having a look. I'm on a different workstation now and don't have the problem here. Probably there was something setup incorrectly in the env of that previous workstation. Sorry for bothering. Closing this now.
