### ISSUE TITLE
Optimally rendering the the USD content

### ISSUE THREAD

**Issue by BigRoy** [Autodesk/maya-usd#38]
### Discussion

_This is less of an issue, but more of a question/discussion regarding the `maya-usd` workflow and working towards rendering that optimally for heavy scenes._

I was wondering what others are doing to optimally load and render the USD scenes. We are most interested in USD with the proxy shapes (e.g. like the proxy shape from the Animal Logic plug-in) as it allows to load heavier scenes with many objects, instances and heavy dependencies without loading them into the local scene. Technically we could even load just bounding boxes and only have the actual renderer load the full content.

That's the workflow we're looking into with the maya-usd plug-in, however I'm wondering how others are tackling this. I noticed the Animal Logic proxy shape by default is not able to render with for example the now built-in Arnold renderer. Do others have custom Arnold procedurals to allow for that translation to the renderer and if so are they publicly available?

In the end we are least interested in yet another plug-in that requires to load *all* content into the local Maya scene as geometry and then have that being translated to the renderer. It's slow and has always been introducing more trouble than it's worth.

**Comment by kxl-adsk** [comment]
Rendering directly from the USD data model and avoiding translation is the way to go. Your Arnold example can be solved in at least two ways.
1) In refactoring_sandbox we introduced new base proxy shape which all USD proxy shape plugins will base on. This gives us access to USD stage and allows us to support workflows which are independent of the plugin. The next step is to teach mtoa about this base proxy shape (not yet done).
2) In refactoring_sandbox you will find "maya to hydra" plugin from Luma. This new render override plugin  will allow you to have both Maya's data model and USD (via again base proxy shape) rendered by the same render delegate (e.g. Arnold render delegate)

**Comment by BigRoy** [comment]
Thanks. 

I guess some focus would be on that `mtoa` relationship or have it implemented with e.g. V-Ray. Any rough estimate on when focus will shift to point 1) for having it implemented for Arnold within the repository?

Regarding 2), I haven't looked much at what Luma was doing in that regard. But would that mean that it would render it inside Viewport 2.0 using Hydra and merge it with any regular Viewport 2.0 data (e.g. zdepth merge) or will it be a new viewport renderer alltogether? Or is the goal that this _maya to hydra_ will also aid in getting it supported by third-party renderers?

Which makes me wonder to what extend features from for example [OpenWalter](https://github.com/rodeofx/OpenWalter) are intended to be part of the `maya-usd` repository or whether you'd still need something like Walter on the side.

**Comment by kxl-adsk** [comment]
Sorry for coming back to you late. 

Luma's work introduces a new scene delegate which brings Maya's data model to Hydra. This means things like meshes, curves, etc will not be composite but will fully be handled by selected render delegate (Arnold, Embree, Storm, etc) via render override API in Maya. Composition still happens for some things, like selection highlighting or manipulators. 

As for mtoa support - it's on our radar, but I can't give any estimates.

**Comment by BigRoy** [comment]
> Luma's work introduces a new scene delegate which brings Maya's data model to Hydra. This means things like meshes, curves, etc will not be composite but will fully be handled by selected render delegate (Arnold, Embree, Storm, etc) via render override API in Maya.

Is that currently present in one of the branches? :)

> As for mtoa support - it's on our radar, but I can't give any estimates.

Sweet. 👍 I wonder if somehow we need to push Chaosgroup too to make sure they adopt it as swiftly as possible, and Redshift and others. Or is that supposed to be a open-source public effort?

**Comment by kxl-adsk** [comment]
Thx for the reminder about other renderers! And Maya to Hydra is in refactoring_sandbox.

**Comment by kxl-adsk** [comment]
Arnold render delegate isn't part of maya-usd repo. Currently, the only public version can be found here https://github.com/LumaPictures/usd-arnold/tree/master/plugin/pxr/imaging/hdAi

**Comment by BigRoy** [comment]
Thanks. For anyone else interested I also wanted to link this repository for Arnold-USD from Autodesk that recently went public: https://github.com/Autodesk/arnold-usd

In the meantime, I was wondering regarding shader assignments to the USD stage in a proxy. Is there any plans to support this through UFE and have it visualized in the Outliner? Or do you envision it to be separate development in-house for studios and to be done in a custom system, e.g. like [`OpenWalter`](https://www.rodeofx.com/tech/walter/) (see Basic Maya Assignment video there)? 
Or is this something that the Bifrost Graph is planned to tackle and be used as a procedural graph also for shading, similar to Katana, Gaffer and Solaris?

**Comment by kxl-adsk** [comment]
It's something on our radar, but I can't share any details at this moment.

BTW. What is missing to close this issue?

**Comment by BigRoy** [comment]
> What is missing to close this issue?

Good question. Since it's more of a discussion or question as opposed to a bug or feature request (at this stage) I think seeing it clearly documented on how to approach the shading, e.g. procedurally.

However, with things being under such heavy development I'd be happy to close it to wait around. A "discussion" without a concrete answer might be more suited on a forum anyway.

I will close it now. Feel free to reopen if need arises.
