### ISSUE TITLE
Accessing JobExportArgs "referenceObjectMode" or "exportRelativeTextures" from Python would cause Maya to crash

### ISSUE THREAD

**Issue by csyshing** [Autodesk/maya-usd#3809]
**Describe the bug**

In our studio pipeline, we have setup export chaser in Python, we recently found that accessing the "referenceObjectMode" argument from Python would cause Python exception, if the exception is not caught, it would cause Maya to crash.

So far we have seen "referenceObjectMode" and "exportRelativeTextures" arguments could cause problem, other arguments are working fine.

**Steps to reproduce**
1. Launch Maya
2. Run following code snippet:
```Python
# Load Maya USD plugin
from maya import cmds
cmds.loadPlugin('mayaUsdPlugin')

# Define the export chaser in Python (minimum example):
class TestExportChaser(mayaUsd.lib.ExportChaser):
    def __init__(self, factoryContext, *args):
        print(factoryContext)
        print(factoryContext.GetJobArgs())
        try:
            print(factoryContext.GetJobArgs().referenceObjectMode)
        except Exception as exc:
            print(exc)
    def ExportDefault(self):
        return True
    def ExportFrame(self, frame):
        return True
    def PostExport(self):
        return True

# Register the chaser
mayaUsd.lib.ExportChaser.Register(TestExportChaser, 'TestExportChaser')

# Export to USD file to trigger the problem
filePath = '/path/to/export/location.usda'
cmds.file(filePath, force=True, type="USD Export", ea=True,
    options="chaser=[TestExportChaser];defaultUSDFormat=usda;referenceObjectMode=defaultToMesh;")
```
3. Maya script editor would have output like this:
```
<mayaUsd.lib.UsdMayaExportChaserRegistryFactoryContext object at 0x7ff8661d9540>
<mayaUsd.lib.JobExportArgs object at 0x7ff865eec220>
No Python class registered for C++ class pxrInternal_v0_23__pxrReserved__::TfToken
```
4. If the `try....except....` around `print(factoryContext.GetJobArgs().referenceObjectMode)` wasn't there, Maya would simply crash.

**Expected behavior**

Be able to access "referenceObjectMode" without any problem.

**Specs (if applicable):**
 - OS & version: CentOS 7.8
 - Compiler & version: GCC 6.3
 - Maya version: Maya-2023
 - Maya USD: Official v0.28.0
 - Pixar USD: Official v23.02, v22.05

**Additional context**

The problem seems to be fact that `TfToken` was exposed directly but it should behave like a Python string, there is one related comment in USD repo:
https://github.com/PixarAnimationStudios/OpenUSD/issues/1194#issuecomment-623588220

One of the potential fixes might be changing the way how to expose this "referenceObjectMode" argument and "exportRelativeTextures" argument in Python binding, e.g.:
Changing `.def_readonly(....)`:
https://github.com/Autodesk/maya-usd/blob/v0.28.0/lib/mayaUsd/python/wrapPrimWriter.cpp#L544
```C++
.def_readonly("referenceObjectMode", &UsdMayaJobExportArgs::referenceObjectMode)
```

To be something like:
```C++
.add_property(
    "referenceObjectMode",
    make_getter(&UsdMayaJobExportArgs::referenceObjectMode, return_value_policy<return_by_value>()))
```

**Comment by seando-adsk** [comment]
@csyshing Sorry for the delay. Would you be able to submit a PR with your fix and a unit test to verify that both these attributes can be properly accessed?

Thanks, Sean
