### ISSUE TITLE
Windows10 Maya 2018.5 build success but cannot load plugin

### ISSUE THREAD

**Issue by the2h-ljm** [Autodesk/maya-usd#385]
hi, I successed compiling pxrUSD and mayaUSD on VS2015, but cannot import plugin in Maya2018.5

**USD build command:**
python build_scripts\build_usd.py  D:\lib\USD-20.02-boost-vs2015  --build-args boost,"--with-date_time --with-thread --with-system --with-filesystem"

**mayaUSD build command:** 
python build.py --maya-location="C:\Program Files\Autodesk\Maya2018" --pxrusd-location="D:\lib\USD-20.02-boost-vs2015"  D:\lib\mayaUSD-2018-20.02 --build-args="-DPXR_STRICT_BUILD_MODE=OFF"

mayaUSD build log:
[build_log.txt](https://github.com/Autodesk/maya-usd/files/4384911/build_log.txt)

load plugin in 2018:
![image](https://user-images.githubusercontent.com/48666437/77608549-ea7fa980-6f60-11ea-8c13-ba8a736b1c82.png)

![image](https://user-images.githubusercontent.com/48666437/77608636-261a7380-6f61-11ea-9d9c-3b17474e7400.png)

running maya env:
echo %MAYA_MODULE_PATH%
D:\lib\mayaUSD-2018-20.02\install\RelWithDebInfo

echo %pythonpath%
C:\Python27\Lib\site-packages;

echo %path%
C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\CommonExtensions\Microsoft\TestWindow;C:\Program Files (x86)\MSBuild\14.0\bin;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\;C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\Tools;C:\Windows\Microsoft.NET\Framework\v4.0.30319;C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\VCPackages;C:\Program Files (x86)\HTML Help Workshop;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Team Tools\Performance Tools;C:\Program Files (x86)\Windows Kits\10\bin\x86;C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.6.1 Tools\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files (x86)\AOMEI Backupper;C:\Program Files\Git\cmd;C:\Program Files\Git LFS;C:\Program Files (x86)\QuickTime\QTSystem\;C:\Program Files\TortoiseGit\bin;C:\Python27\libs;C:\Program Files\dotnet\;C:\Users\ljm\.dnx\bin;C:\Program Files\Microsoft DNX\Dnvm\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Python27\Scripts;C:\Python27;C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\bin\HostX86\x86;C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCPackages;C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\CommonExtensions\Microsoft\TestWindow;C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer;C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\bin\Roslyn;C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Team Tools\Performance Tools;C:\Program Files (x86)\Microsoft Visual Studio\Shared\Common\VSPerfCollectionTools\;C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.6.1 Tools\;C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\CommonExtensions\Microsoft\FSharp\;C:\Program Files (x86)\Windows Kits\10\bin\10.0.17763.0\x86;C:\Program Files (x86)\Windows Kits\10\bin\x86;C:\Program Files (x86)\Microsoft Visu

**Comment by seando-adsk** [comment]
In your path "D:\lib\mayaUSD-2018-20.02\install\RelWithDebInfo" can you verify the contents of the mayaUsd.mod file. Make sure the paths (especially for USD) were configured and looked correct.

From within maya can you get the path (using getenv). Make sure your USD build is there.

**Comment by the2h-ljm** [comment]
Thanks for the reply. I was using Multiverse plugin and had a conflict with maya usd.
I will close this issue.
