### ISSUE TITLE
mtoh plugin wont load

### ISSUE THREAD

**Issue by suesauer** [Autodesk/maya-usd#386]
**Describe the bug**
moth Crashes Maya 2020 when I turn it on

**Steps to reproduce**
1. open maya 2020
2. try to load mtoh plugin in the plugin manager

**Expected behavior**
To be able to turn on the mtoh plugin

**Attachments**
`unable to register command AL::maya::utils::CommandGuiListGen: (kFailure): Unexpected Internal Failure
Stack trace:
  /home/suesauer/Documents/Maya_arnold-usd/plugin/hdArnold.so(+0xd704b) [0x7f7e8120e04b]
  tbb::internal::atomic_traits<4ul, (tbb::memory_semantics)0>::fetch_and_add(void volatile*, int)
  unsigned int tbb::internal::atomic_impl_with_arithmetic<unsigned int, unsigned int, char>::fetch_and_add<(tbb::memory_semantics)0>(unsigned int)
  tbb::internal::atomic_impl_with_arithmetic<unsigned int, unsigned int, char>::fetch_and_add(unsigned int)
  tbb::internal::atomic_impl_with_arithmetic<unsigned int, unsigned int, char>::fetch_and_decrement()
  pxrInternal_v0_20__pxrReserved__::intrusive_ptr_release(pxrInternal_v0_20__pxrReserved__::Sdf_PathNode const*)
  pxrInternal_v0_20__pxrReserved__::Sdf_PathNodeHandleImpl<pxrInternal_v0_20__pxrReserved__::Sdf_Pool<pxrInternal_v0_20__pxrReserved__::Sdf_PathPrimTag, 24u, 8u, 16384u>::Handle, true, pxrInternal_v0_20__pxrReserved__::Sdf_PathNode const>::_DecRef() const
  pxrInternal_v0_20__pxrReserved__::Sdf_PathNodeHandleImpl<pxrInternal_v0_20__pxrReserved__::Sdf_Pool<pxrInternal_v0_20__pxrReserved__::Sdf_PathPrimTag, 24u, 8u, 16384u>::Handle, true, pxrInternal_v0_20__pxrReserved__::Sdf_PathNode const>::~Sdf_PathNodeHandleImpl()
  pxrInternal_v0_20__pxrReserved__::SdfPath::~SdfPath()
  pxrInternal_v0_20__pxrReserved__::HdArnoldRenderDelegate::~HdArnoldRenderDelegate()
  pxrInternal_v0_20__pxrReserved__::HdArnoldRenderDelegate::~HdArnoldRenderDelegate()
  pxrInternal_v0_20__pxrReserved__::HdArnoldRendererPlugin::DeleteRenderDelegate(pxrInternal_v0_20__pxrReserved__::HdRenderDelegate*)
  /home/suesauer/Documents/WorkspaceRefractor/install/RelWithDebInfo/lib/maya/mtoh.so(+0x505f0) [0x7f7e819de5f0]
  pxrInternal_v0_20__pxrReserved__::MtohGetRendererDescriptions()
  initializePlugin(Autodesk::Maya::OpenMaya20200000::MObject)
  Tplugin::primaryLoad(Tstring const&, Tstring*)
  /usr/autodesk/maya2020/lib/libOpenMaya.so(+0x328546) [0x7f81f1e12546]
  /usr/autodesk/maya2020/lib/libOpenMaya.so(+0x329c05) [0x7f81f1e13c05]
  /usr/autodesk/maya2020/lib/libOpenMaya.so(+0x32a8a6) [0x7f81f1e148a6]
  /usr/autodesk/maya2020/lib/libCommandEngine.so(+0x5a271) [0x7f81e8afc271]
  /usr/autodesk/maya2020/lib/libCommandEngine.so(+0x89661) [0x7f81e8b2b661]
  /usr/autodesk/maya2020/lib/libCommandEngine.so(+0xaed6d) [0x7f81e8b50d6d]
  /usr/autodesk/maya2020/lib/libCommandEngine.so(+0x89661) [0x7f81e8b2b661]
  /usr/autodesk/maya2020/lib/libCommandEngine.so(+0xae2f1) [0x7f81e8b502f1]
  /usr/autodesk/maya2020/lib/libCommandEngine.so(+0x89661) [0x7f81e8b2b661]
  /usr/autodesk/maya2020/lib/libCommandEngine.so(+0xb0245) [0x7f81e8b52245]
  /usr/autodesk/maya2020/lib/libCommandEngine.so(+0x89661) [0x7f81e8b2b661]
  /usr/autodesk/maya2020/lib/libCommandEngine.so(+0x89831) [0x7f81e8b2b831]
  SophiaExecutable::evaluate(void*)
  TcommandEngine::executeCommand(Tstring const&, bool, bool, TmelCmdResult*, unsigned int)
  TscriptActionMixin::execute(Tevent const&, std::unique_ptr<TinterpreterResult, std::default_delete<TinterpreterResult> >*)
  TcontrolScriptAction::doIt(Tevent const&)
  Taction::performAction(Tevent const&, char const*)
  Taction::doIt()
  QMetaObject::activate(QObject*, int, int, void**)
  QmayaCheckBox::onOffChanged()
  /usr/autodesk/maya2020/lib/libExtensionLayer.so(+0x1e4af5) [0x7f81e9076af5]
  QMetaObject::activate(QObject*, int, int, void**)
  QCheckBox::stateChanged(int)
  /usr/autodesk/maya2020/lib/libQt5Widgets.so.5(+0x24ba0d) [0x7f81e7804a0d]
1Writing crash report in /usr/tmp/suesauer.20200326.1546.crash
/usr/local/bin/maya: line 194:  8359 Segmentation fault      (core dumped) /usr/autodesk/maya2020/bin/maya.bin
`

**Specs (if applicable):**
 - OS & version Linux Centos 7
 - Compiler & version gcc 6.3.1
 - Maya version Maya 2020
 - Maya USD dev commit e40ac820ea35c50a2bc4ce17920ec32d7ec89091
 - Pixar USD dev commit cdb1120a216769f249fbfe627293d3336b85e04e

**Additional context**
none

**Comment by santosg87** [comment]
@suesauer thanks for logging this. do you still see this behavior when using the pre-compiled binaries that were posted?

**Comment by suesauer** [comment]
Hey there, 
It seems this keeps happening because of Houdini envs and Mayas env fighting. I have separated all pathing now. (No USD in main env paths) And that seemed to solve the problems. Its a bit of a shame as usdview cant simply be called in the terminal.
