### ISSUE TITLE
mayaUsd.ufe.getAllStages cannot see stage after mayaUsdProxyShape was renamed (on the first execution)

### ISSUE THREAD

**Issue by p0las** [Autodesk/maya-usd#3860]
**Describe the bug**
when `mayaUsdProxyShape` is renamed then `mayaUsd.ufe.getAllStages` is not returning the stage from it in on the first run. It has to be executed twice to work.

**Steps to reproduce**

```
from maya import cmds
import mayaUsd

n = cmds.createNode('mayaUsdProxyShape')
cmds.connectAttr('time1.outTime', n + '.time')

maya_stage = cmds.listRelatives(n, pa=True, parent=True, ni=True)

stages_before = mayaUsd.ufe.getAllStages()

renamed_stage = cmds.rename(maya_stage, 'fooBar')

# mayaUsd.ufe.getAllStages() #without this line the assertion is going to fail

assert mayaUsd.ufe.getAllStages() == stages_before
```

**Expected behavior**
`mayaUsdProxyShape` should return the same stages everytime 

**Specs (if applicable):**
 - Windows 10
 - Maya 2024
 - maya USD plugin 0.28.0

**Comment by santosd** [comment]
Hello @p0las, I gave this a try on my end in Maya 2024.2 using 0.28.0 and I was not able to reproduce the error you are seeing. When I run your code the Assertion doesn't fail, it always passes regardless of whether I have line 13 commented out or not. The output of my get all stages is always the same:
`print(stages_before)
[Usd.Stage.Open(rootLayer=Sdf.Find('anon:00000267FF108010:anonymousLayer1'), sessionLayer=Sdf.Find('anon:00000267FF10A530:anonymousLayer1-session.usda'))]
print(mayaUsd.ufe.getAllStages())
[Usd.Stage.Open(rootLayer=Sdf.Find('anon:00000267FF108010:anonymousLayer1'), sessionLayer=Sdf.Find('anon:00000267FF10A530:anonymousLayer1-session.usda'))]
`

**Comment by p0las** [comment]
you are right. I executed it on another machine running the same versions and it works fine. I have two machines that are meant to run the same pipeline yet the results are different. I will investigate this further. Thank you for taking the time to test it.
