### ISSUE TITLE
My preferences to show the Node Library & "Connect Nodes on Creation" on the Bifrost Graph editor don't "stick."

### ISSUE THREAD

**Issue by pixelwash** [Autodesk/maya-usd#3931]
My preferences to show the Node Library & "Connect Nodes on Creation" on the Bifrost Graph editor don't "stick." between restarts of the application. I've tried saving them to the Maya workspace profile, and it makes no difference. Other preferences like showing showing the Node Types don't "stick" either.

I'm on windows 10, Maya 2025.2, MayaUSD_0.29.0_Maya2025.2_Windows.

I'm just starting out on Bifrost, so having the Node Library showing is important to me.

(I'm sorry if this does not directly apply to USD, if so perhaps you could direct me where to post this bug?)

**Comment by santosg87** [comment]
Hi @pixelwash!, thanks for reporting this. 

Unfortunately, we wouldn't be able to help much Regarding the Bifrost Graph Editor. 

the recommended place for Bifrost questions and bug reporting would be the bifrost forum:
https://forums.autodesk.com/t5/bifrost-forum/bd-p/6060

nonetheless, I forwarded the information on this to the team that works on bifrost, and asked them to investigate the issue. :)

**Comment by santosg87** [comment]
just for the purposes of maintaining a clean backlog, I am closing this issue, as it is not USD related.
