### ISSUE TITLE
Bifrost Graph Editor UI doesn't honor the lock windows setting in Maya.

### ISSUE THREAD

**Issue by pixelwash** [Autodesk/maya-usd#3932]
I see that the Bifrost UI features dragable and droppable windows in its layout, but it can be sometimes accidentally messed up because it does not respect the UI lock icon in the upper right hand corner of the main Maya UI.

Windows 10, Maya 2025.2, MayaUSD_0.29.0_Maya2025.2_Windows.

(I'm sorry if this does not directly apply to USD, if so perhaps you could direct me where to post this bug?)

**Comment by wallworm** [comment]
Thanks for sharing. I will forward your question.

**Comment by santosg87** [comment]
Hi @pixelwash! similar to my post on the other issue, this would be something the bifrost team would be much more apt to assist and report any bugs related to your issue. for bifrost issues, their forum is the best place to report:
https://forums.autodesk.com/t5/bifrost-forum/bd-p/6060

with that said, I reached out to the bifrost team for any information they might have. someone on the bifrost team should reach out soon. :)

For now, I am closing this ticket as it is not MayaUsd related.
