### ISSUE TITLE
Error: 'module' object has no attribute 'MayaReference'

### ISSUE THREAD

**Issue by suesauer** [Autodesk/maya-usd#399]
**Describe the bug**
Using 
`from Al.usd from schema`
No longer works to create MayaReference

**Steps to reproduce**
`
import logging
import os

import AL.usd
help(AL.usd.schemas.maya)

def _AddToVariantAsset(assetName, assetDir, VariantSetNames):
    #Add Variant
    assetFilePath = os.path.join(assetDir, assetName)
    stage = Usd.Stage.Open(assetFilePath) # Asset that will get variant
    ## TODO: Need to add a check for none USD format files here:
    primName = os.path.splitext(assetName)[0]
    assetPrim = stage.GetPrimAtPath('/' + primName)
    Reversed_VariantSetNames = sorted(VariantSetNames , reverse=True)
    print Reversed_VariantSetNames
    for variantset in Reversed_VariantSetNames:
        print variantset
        varSet = assetPrim.GetVariantSet(variantset)
        directory = assetDir + "/variants/" + variantset
        for filename in os.listdir(directory):
            variantName = filename[:-4]
            if variantName == "base":
                pass
            else:
                if variantset == "RiggingVariant":
                    rigging_dpt = "_rig"
                    varSet.SetVariantSelection(variantName)
                    varSet.AddVariant(variantName)
                    with varSet.GetVariantEditContext():
                        rig = maya.MayaReference.Define(stage, "/{0}/global_trs/master_trs/aux_trs/rig".format(assetName))
                        print "Rig: ", rig
                        print rig.CreateMayaNamespaceAttr().Set('{}{}'.format(assetName, rigging_dpt))
                        print rig.CreateMayaReferenceAttr().Set(os.path.join(assetDir, "{0}{1}.ma".format(assetName, rigging_dpt)))
                else:
                    varSet.SetVariantSelection(variantName)
                    varSet.AddVariant(variantName)
                    with varSet.GetVariantEditContext():
                        assetPrim.GetPayloads().AddPayload(directory +"/"+ filename)
                    varSet.SetVariantSelection(variantName)
                    stage.GetRootLayer().Save()

_AddToVariantAsset(assetName="pot.usd", assetDir="/home/suesauer/root/show/HBD/work/assets/elem/prop/pot", VariantSetNames=["ModelingVariant", "RiggingVariant", "ShadingVariant"])`

**Expected behavior**
for schema.maya.MayaReference to create a maya Reference with python for usd

**Specs (if applicable):**
 - OS & version Linux Centos 7
 - Compiler & version  gcc 6.3.1
 - Maya version Maya 2020
 - Maya USD commit -b dev 
 - Pixar USD commit SHA dev  893c8e4cc4d45fb3e7364369d7767602de411120

**Additional context**
If this process has changed how do I go about using MayaReference now ?

**Comment by kxl-adsk** [comment]
@suesauer MayaReference was moved to mayaUsd and is shared by all plugins. See following regression tests which show you how to include and use it https://github.com/Autodesk/maya-usd/blob/dev/test/lib/usd/schemas/testMayaUsdSchemasMayaReference.py#L21

**Comment by suesauer** [comment]
Thanks will check it out

**Comment by suesauer** [comment]
Works a treat thanks
