### ISSUE TITLE
Error: ProxyShapeUI.cpp:608:55 

### ISSUE THREAD

**Issue by HansBaldzuhn** [Autodesk/maya-usd#40]
Hi every one !

I'm trying to build maya-usd for use with maya 2019 on Centos 7 inside a docker.
The docker is build from the usd-docker repo from AnimalLogic.

I'm getting maya-usd source code from the master on github:
https://github.com/Autodesk/maya-usd/archive/master.zip

I'm executing the following command to build maya-usd:
```
RUN python build.py \
        -v 3 \
        --generator Ninja \
        --build-args="-DCMAKE_MAKE_PROGRAM=${NINJA}" \
        --maya-location ${MAYA_LOCATION} \
        --devkit-location ${MAYA_LOCATION}  \
        --pxrusd-location ${USD_BUILD_DIR} \
        --install-location ${USD_MAYA_INSTALL_DIR} \
        ${USD_MAYA_BUILD_DIR}
```

USD was build using the build.py script from the pixar/USD repository.

After multiple issue with the configuration of cmake, it finally started to build.
But I now have an error from the c++ code.

Here it is:
```
/tmp/usd-build/maya-usd-master/plugin/al/lib/AL_USDMaya/AL/usdmaya/nodes/ProxyShapeUI.cpp:608:55: error: base operand of '->' has non-pointer type 'std::initializer_list<std::shared_ptr<Ufe_v1::HierarchyHandler> >'
                 const Ufe::SceneItem::Ptr& si{ handler->createItem(proxyShape->ufePath() + ps_usd) };
                                                       ^
/tmp/usd-build/maya-usd-master/plugin/al/lib/AL_USDMaya/AL/usdmaya/nodes/ProxyShapeUI.cpp:608:100: error: invalid initialization of reference of type 'const Ptr& {aka const std::shared_ptr<Ufe_v1::SceneItem>&}' from expression of type '<brace-enclosed initializer list>'
                 const Ufe::SceneItem::Ptr& si{ handler->createItem(proxyShape->ufePath() + ps_usd) };
                                                                                                    ^
```

I don't know if this issue might be caused by a misconfiguration on my side.

There is also A LOT of the following verbosity, I don't know if it might be related:
`note:   template argument deduction/substitution failed:`

If any one have a clue on this issue,
Best Regards,
Hans

**Comment by HamedSabri-adsk** [comment]
@HansBaldzuhn can you please tell me your gcc version? Are you also using devtoolset?

**Comment by HansBaldzuhn** [comment]
Hi,
I'using the lastest available version for Centos 7 via yum: gcc 4.8.5 
At the begining of my test, I was using devtoolset-6, to match vfx reference CY2020
But when I started using a base docker from AnimaLogic I stopped using it since they don't. And I didn't find any request for a more recent version of gcc than the one I had.

**Comment by HansBaldzuhn** [comment]
I works when using devtoolset-6, with gcc 6.3.1 : )

**Comment by HamedSabri-adsk** [comment]
@HansBaldzuhn  Great, can you close this issue? Thanks.
