### ISSUE TITLE
[MAYA-96058] using mel command to Rotate/Translate/Scale USD data without creating a manipulator will wipe previous values

### ISSUE THREAD

**Issue by santosg87** [Autodesk/maya-usd#401]
we noticed this recently while testing other workflows with the proxyShape. 

It seems that when using mel commands to add to a transform operation, the mel command will clear previous value and overwrite it with the absolute value in the command, which is not expected. the proper behavior would be to have the command add the new values to the current existing values.

the workaround is fairly simple - use a transform tool to make sure a manipulator is drawn. it seems that the lack of a manipulator is the main cause of this issue

**Steps to reproduce**

1. create a USD stage using an existing layer.
2. select a USD object
3. run the following mel command: "rotate -r -os -fo 0 0 45;" 
    (this will rotate the selected object 45 degrees on Z from current position)
4. now run the following mel command: "rotate -r -os -fo 45 0 0;"
5. step 4 should rotate the selected object 45 degrees in the X axis and maintain the existing 45 degrees in the Z axis. However, the rotation resets the values on the Z axis and applies 0.

**Expected behavior**
the rotate/move/scale command, when not using the -a flag should always add to the existing current values.

**Additional context**
broken behavior:
![rotate_overwritingValues](https://user-images.githubusercontent.com/3026529/78174149-cae7f580-7426-11ea-9da3-99546559e4c1.gif)

working behavior - note that the only difference on this workflow is that the tools is activated once (which creates a manipulator)
![rotate_working](https://user-images.githubusercontent.com/3026529/78174258-f79c0d00-7426-11ea-9d8b-84bc226bec9c.gif)

**Comment by santosg87** [comment]
this one is logged internally as MAYA-96058. 

marking it as unassigned while we decide on the next steps.

**Comment by kxl-adsk** [comment]
Fixed internally. Closing.
