### ISSUE TITLE
PointInstancer issues in maya-usd

### ISSUE THREAD

**Issue by fdan** [Autodesk/maya-usd#403]
Hi, I've use the precompiled maya-usd plugin on OSX, Maya 2020 to open a usd stage that contains some referenced geo and also a point instancer.  The latter doesn't seem to be supporte?

**Comment by kxl-adsk** [comment]
@fdan By supported you mean it doesn't render correctly in the viewport or something else?

**Comment by fdan** [comment]
Yeah, it doesn’t show in the viewport, I just see the prototypes at the origin.

The set I’m using loads correctly in usdview, LOPs, Pxr Usd Maya, Renderman etc.

**Comment by fdan** [comment]
This is just from referencing the usd - I couldn’t find any documentation on this plugin so maybe I’m using it wrong.

**Comment by kxl-adsk** [comment]
Can you share with us your test file? I just tried with City set from Pixar (http://graphics.pixar.com/usd/downloads.html) and didn't notice any issue.

**Comment by fdan** [comment]
I just tried the City set, and I get the same issue.  Here's a screenshot, and the script editor output.  This is Maya2020 on OSX 10.14

```
file -r -type "USD Import"  -ignoreVersion -gl -mergeNamespacesOnClash false -namespace "PointInstancedMedCity" -options ";primPath=/;readAnimData=0;useCustomFrameRange=0;startTime=0;endTime=0" "/Users/dan/Downloads/usd/PointInstancedMedCity/PointInstancedMedCity.usd";
// Warning: line 0: The mesh |MediterraneanHills|Buildings|Prototypes|prototype_4|mesh_0|mesh_0Shape contains invalid or unused components.  These can be cleaned up using the Mesh Cleanup dialog. // 
// Warning: line 0: The mesh |MediterraneanHills|Buildings|Prototypes|prototype_5|mesh_0|mesh_0Shape contains invalid or unused components.  These can be cleaned up using the Mesh Cleanup dialog. // 
// Warning: line 0: The mesh |MediterraneanHills|Buildings|Prototypes|prototype_6|mesh_0|mesh_0Shape contains invalid or unused components.  These can be cleaned up using the Mesh Cleanup dialog. // 
// Warning: line 0: The mesh |MediterraneanHills|Buildings|Prototypes|prototype_7|mesh_0|mesh_0Shape contains invalid or unused components.  These can be cleaned up using the Mesh Cleanup dialog. // 
// Warning: line 0: Errors have occurred while reading this scene that may result in data loss.

Please check the Script Editor for details. // 
// File read in  0.13 seconds.
// /Users/dan/Downloads/usd/PointInstancedMedCity/PointInstancedMedCity.usd // 
updateRendererUI;
```

![image](https://user-images.githubusercontent.com/1701261/78401162-d6643800-7643-11ea-9dce-21c648a2525c.png)

**Comment by fdan** [comment]
Ah, I just realised the correct (?) way to load USD is via Create -> Universal Scene Description (USD) -> Stage from existing layer.  

That results in the point instancer being loaded correctly.  I'm not sure if it's supposed to or not, but referencing it via File -> CreateReferene does not.

**Comment by kxl-adsk** [comment]
`File -> CreateReference` will trigger an import of USD into the Maya data model. So what you have found is a current bug (or more likely limitation) in our USD import.

Viewing USD natively is done via `Create -> Universal Scene Description (USD) -> Stage from existing layer`.

**Comment by kxl-adsk** [comment]
Please update the description (we ask people to fill the template and provide full steps to reproduce the issue; this way we could reproduce it much easier).

**Comment by fdan** [comment]
Actually there's still issues.  Even with the Create option, the point instancer prototypes are visible

![image](https://user-images.githubusercontent.com/1701261/78402531-7327d500-7646-11ea-8002-4be421eca1bc.png)


Here's what it looks like in usdview
![image](https://user-images.githubusercontent.com/1701261/78402603-9783b180-7646-11ea-8076-3427d2f47cf0.png)

**Comment by kxl-adsk** [comment]
Let's log them separately and please provide a test file for us.

**Comment by fdan** [comment]
Sure, I'll open a new ticket for that.  

Couple more questions on this issue though, is there any documentation whatsoever for this plugin?  And the blue outliner icons that show the hierarchy, sometimes they show and sometimes they don't, how do I reveal them?  i.e. now I can't inspect the hierarchy

![image](https://user-images.githubusercontent.com/1701261/78403056-7374a000-7647-11ea-8de5-eac67923b353.png)

**Comment by kxl-adsk** [comment]
We have an issue in the outliner which was causing this refresh bug. This has been fixed and will be available in the next Maya beta build.

**Comment by ppt-adsk** [comment]
Until you get the fix, if you collapse then expand, there's a fair chance you'll get the Outliner display hierarchy back.

**Comment by fdan** [comment]
Ahah, cheers, yes that collapse/expand trick did bring it back.
