### ISSUE TITLE
[MAYA-105120] PointInstancer prototypes load as visible

### ISSUE THREAD

**Issue by fdan** [Autodesk/maya-usd#404]
**Describe the bug**
When I load a set with a point instancer, the instances show correctly in the viewport, but the prototypes are also visible.  They should not be. 

**Steps to reproduce**
1. Download and unzip my attache set
2. Bring into Maya via Create -> Universal Scene Description (USD) -> Stage From Existing Layer and navigate to `assets/set/world/model/model/assembly/world_model_model_assembly.v046.usd`
3. In the viewport, you will see a single giant tree which is one of the instancer prototypes that should be hidden

**Expected behavior**
Point instancer instances should be visible, but prototypes should not be.  

**Attachments**
In this image, you can see the prototypes are visible
![image](https://user-images.githubusercontent.com/1701261/78403560-45dc2680-7648-11ea-8f90-78166d7464e9.png)

Whereas in usdview they are not - I take this to be correct?
![image](https://user-images.githubusercontent.com/1701261/78403611-60160480-7648-11ea-8dc0-d53cd1a21550.png)

[world_set.zip](https://github.com/Autodesk/maya-usd/files/4429854/world_set.zip)

**Specs (if applicable):**
 - OSX 10.14
 - Apple LLVM version 10.0.1 (clang-1001.0.46.4)- (I used the prebuild binary in release 0.1.0)
 - Maya 2020
 - Maya USD commit SHA 00d651a8af3af752160531a0841579d1bc0f41ea

**Additional context**

**Comment by santosd** [comment]
Hello @fdan, thank you for posting this issue here. I took a look at it in PR114 and was able to reproduce the issue in the latest build of the Maya USD. I will set this issue as reproduced and will get one of our devs to take a look at it.

Thank you.

**Comment by williamkrick** [comment]
@fdan #570 which fixes this issue has been merged. Can you test it to verify?

**Comment by santosd** [comment]
@fdan I tested it out on my end with the new changes and this seems to be working well after the merged changes. Please give it a try and let me know or feel free to close this issue out.

**Comment by fdan** [comment]
Cheers, I haven’t had a chance to confirm unfortunately but trust you folks that it’s solved.
