### ISSUE TITLE
Fails to export animated visibility if animated visibility is connection from a loaded alembic

### ISSUE THREAD

**Issue by BigRoy** [Autodesk/maya-usd#4059]
**Describe the bug**

When loading an animated alembic (animated geometry with also animated visibilities) then for whatever reason Maya USD Export will fail to export that animated visibility - whereas with regular keys it exports fine.

**Steps to reproduce**

Here's a simple reproducable (see also attachment):

1. An example scene with an animated cube (cluster deform) and the parent group has keyed visibilities.
2. Export to Alembic
3. Reference the Alembic
4. Export both the original animated AND the referenced alembic hierarchy.

The exported loaded alembic is lacking the visibility keys? Even though the regular geometry does have it exported just fine.

**Expected behavior**

The exported animation data should match what I see in my viewport.

**Attachments**

[debug.zip](https://github.com/user-attachments/files/18214155/debug.zip)

**Specs (if applicable):**

 - OS & version : Windows 10/11
 - Maya version Maya 2025.3
 - Maya USD  0.30.0

**Additional context**

It seems that when it's a connection instead of regular keyframes it fails to export the visibility?

**Comment by santosg87** [comment]
Thank you for this report! I Believe this is the same issue as #3995. @BigRoy I am closing this issue as a Duplicate for now, but feel free to re-open if you feel like these are not the same issue. :)

cheers!
