### ISSUE TITLE
Boost filesystem not found in Pixar Usd core build

### ISSUE THREAD

**Issue by fdan** [Autodesk/maya-usd#406]
**Describe the issue**
I have built the Pixar Usd libraries (19.11 release) on Windows10 using their build script, as follows, which completes without issue. 

`python build_usd.py --no-imaging --no-alembic --no-draco --no-materialx --no-katana --no-houdini --no-tests "C:\usd\build"`

However when running the build script for the maya-usd repository, it seems to expect boost filesystem in the usd build dir?  I couldn't see anywhere that installing boost was necessary to build the maya-usd repo.  Here's how I'm trying to build it:

`python build.py --generator Ninja --maya-location "C:\Program Files\Autodesk\Maya2018" --pxrusd-location "C:\usd-19.11\build" --devkit-location "C:\maya_devkit_2018\Autodesk_Maya_2018_6_Update_DEVKIT_Windows\devkitBase" --build-args="-DBUILD_ADSK_PLUGIN=OFF,-DBUILD_PXR_PLUGIN=ON,-DBUILD_AL_PLUGIN=OFF,-DBUILD_TESTS=OFF,-DCMAKE_MAKE_PROGRAM=C:/Users/dan/git/ninja-win/ninja.exe" "C:\usdmaya-19.11"`

I didn't quite follow this big of the build docs:
https://github.com/Autodesk/maya-usd/blob/dev/doc/build.md#boost

> Currently the Animal Logic plugin has a dependency on some of the boost components ( e.g thread, filesystem ). When building Pixar USD, one needs to pass the following key,value paired arguments for boost to include those components: e.g
> 
> python build_usd.py ~/Desktop/BUILD --build-args boost,"--with-date_time --with-thread --with-system --with-filesystem"

I just want to build the Pixar USD plugin, if it's the AL plugin that requires filesystem, is there any way I can skip it?  

**Build log**
[build_log.txt](https://github.com/Autodesk/maya-usd/files/4432561/build_log.txt)

**Specs:**
 - Windows 10
 - VS 2015 update 3
 - Maya 2018
 - Maya USD commit SHA (0.1.0 release) 41409295ec063d4f72d49cd6894f03595fa8abc2
 - Pixar USD commit SHA (19.11 release) 4b1162957b2ad219e1635c81de8343be490e41fc

**Additional context**

**Comment by fdan** [comment]
After installing boost 1.61 (compiled libraries for windows), and setting $BOOST_ROOT manually, the build worked.  

```
C:\usdmaya-19.11" --build-args boost,"--with-date_time --with-thread --with-system --with-filesystem,-DBUILD_ADSK_PLUGIN=OFF,-DBUILD_PXR_PLUGIN=ON,-DBUILD_AL_PLUGIN=OFF,-DBUILD_TESTS=OFF,-DCMAKE_CXX_FLAGS=/w"

    Building with settings:
      Source directory          c:\Users\dan\git\maya-usd
      Workspace directory       C:\usdmaya-19.11
      Build directory           C:\usdmaya-19.11\build\RelWithDebInfo
      Install directory         C:\usdmaya-19.11\install\RelWithDebInfo
      Variant                   RelWithDebInfo
      Python Debug              Off
      CMake generator           Default
      Build Log                 C:\usdmaya-19.11\build\RelWithDebInfo\build_log.txt
      Build arguments           ['boost', '--with-date_time --with-thread --with-system --with-filesystem', '-DBUILD_ADSK_PLUGIN=OFF', '-DBUILD_PXR_PLUGIN=ON', '-DBUILD_AL_PLUGIN=OFF', '-DBUILD_TESTS=OFF', '-DCMAKE_CXX_FLAGS=/w']
      Stages arguments          ['clean', 'configure', 'build', 'install']
Success MayaUSD build and install !!!!
Elapsed time: 00:05:32
```

However I'm running into this problem trying to load the plugin in maya.  As per the docs, I have set MAYA_MODULE_PATH to point to the directory containing mayaUSD.mod.  When I try to load it maya, I get the following error:

```
// Error: file: C:/Program Files/Autodesk/Maya2018/scripts/others/pluginWin.mel line 290: Unable to dynamically load : C:/usdmaya-19.11/install/RelWithDebInfo/plugin/pxr/maya/plugin/pxrUsd.mll
The specified module could not be found.
 // 
// Error: file: C:/Program Files/Autodesk/Maya2018/scripts/others/pluginWin.mel line 290: The specified module could not be found.
 (pxrUsd) // 
```

The file `C:/usdmaya-19.11/install/RelWithDebInfo/plugin/pxr/maya/plugin/pxrUsd.mll` **does** exist however.  

![image](https://user-images.githubusercontent.com/1701261/78465056-49e57280-7734-11ea-84e1-3717499fb0a3.png)

**Comment by fdan** [comment]
Here's the mod file if it helps.  The directories all seem to contain the right files to me.  

I have very little experience debugging c++ builds in visual studio / windows so I'm at a bit of a loss how to investigate.  

```
+ USD 0.19.11 C:\usd-imaging-19.11\build
PYTHONPATH+:=lib/python
PATH+:=bin
PATH+:=lib

+ PXR_USDMAYA 0.19.11 C:/usdmaya-19.11/install/RelWithDebInfo/plugin/pxr
PYTHONPATH+:=lib/python
PATH+:=maya/lib
XBMLANGPATH+:=maya/lib/usd/usdMaya/resources
MAYA_SCRIPT_PATH+:=maya/lib/usd/usdMaya/resources
MAYA_PLUG_IN_PATH+:=maya/plugin
PXR_PLUGINPATH_NAME+:=lib/usd

+ MayaUSD_LIB 0.1.0 C:/usdmaya-19.11/install/RelWithDebInfo
PATH+:=lib
PYTHONPATH+:=lib/python
PXR_PLUGINPATH_NAME+:=lib/usd
VP2_RENDER_DELEGATE_PROXY=1


+ MayaUSD 0.1.0 C:/usdmaya-19.11/install/RelWithDebInfo/plugin/adsk
MAYA_PLUG_IN_PATH+:=plugin

+ AL_USDMaya  C:/usdmaya-19.11/install/RelWithDebInfo/plugin/al
PYTHONPATH+:=lib/python
PATH+:=lib
MAYA_PLUG_IN_PATH+:=plugin
PXR_PLUGINPATH_NAME+:=lib/usd
PXR_PLUGINPATH_NAME+:=plugin
MAYA_WANT_UFE_SELECTION=1

+ MTOH 0.1.0 C:/usdmaya-19.11/install/RelWithDebInfo/lib
MAYA_PLUG_IN_PATH+:=maya
```

**Comment by fdan** [comment]
It seems my other issue is answered here:

https://github.com/Autodesk/maya-usd/issues/26

If what I read is true, the pixar plugin is not supported for maya 2018?  Weird because we're using it in linux without issue.

**Comment by kxl-adsk** [comment]
We are not aware of any issue with Pixar plugin and Maya 2018. Even issue you referenced is closed and the user was able to build and run it - https://github.com/Autodesk/maya-usd/issues/26#issuecomment-524368619

We may have to tweak the docs a bit, but these build args are required when building USD:
> python build_usd.py ~/Desktop/BUILD --build-args boost,"--with-date_time --with-thread --with-system --with-filesystem"

It will be easiest for us to help if you can rebuild USD with it and then stop modifying $BOOST_ROOT when building maya-usd.

**Comment by fdan** [comment]
Ahah, thank you, that resolved the issue.  I was mistakenly passing on those boost build args to the maya-usd build, not the core usd build.  

I can now build and load the Pixar plugin fine in Maya2018, thanks!
