### ISSUE TITLE
Help with "WindowsError: [Error 2] The system cannot find the file specified"

### ISSUE THREAD

**Issue by AirWreckaStuff** [Autodesk/maya-usd#416]
**Describe the issue**
I'm stuck trying to figure out what the missing file is.  I have already built and successfully ran the usdview sphere.usda, so was working on bringing this into Maya 2019.

I have been combing through the call list to figure out what file is being called, but I can't figure it out for the life of me.  Am I missing environmental variables, or missing a pre-requisite?

Here is the output from the prompt:
c:\maya-usd>python build.py --maya-location "C:\Program Files\Autodesk\Maya2019" --pxrusd-location "C:\Program Files\USD" --devkit-location "C:\devkitBase" "C:\Program Files\MayaUSD" -v 2

    Building with settings:
      Source directory          c:\maya-usd
      Workspace directory       C:\Program Files\MayaUSD
      Build directory           C:\Program Files\MayaUSD\build\RelWithDebInfo
      Install directory         C:\Program Files\MayaUSD\install\RelWithDebInfo
      Variant                   RelWithDebInfo
      Python Debug              Off
      CMake generator           Default
      Build Log                 C:\Program Files\MayaUSD\build\RelWithDebInfo\build_log.txt
      Stages arguments          ['clean', 'configure', 'build', 'install']
INFO: Running "cmake -DCMAKE_INSTALL_PREFIX="C:\Program Files\MayaUSD\install\RelWithDebInfo" -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -G "Visual Studio 14 2015 Win64" -DMAYA_LOCATION="C:\Program Files\Autodesk\Maya2019" -DPXR_USD_LOCATION="C:\Program Files\USD" -DMAYA_DEVKIT_LOCATION="C:\devkitBase" -DMAYAUSD_DEFINE_BOOST_DEBUG_PYTHON_FLAG=OFF "c:\maya-usd""
Traceback (most recent call last):
  File "build.py", line 597, in <module>
    BuildAndInstall(context, context.buildArgs, context.stagesArgs)
  File "build.py", line 366, in BuildAndInstall
    RunCMake(context, extraArgs, stagesArgs)
  File "build.py", line 268, in RunCMake
    extraArgs=(" ".join(extraArgs) if extraArgs else "")))
  File "build.py", line 137, in Run
    stderr=subprocess.STDOUT)
  File "C:\Python27\lib\subprocess.py", line 394, in __init__
    errread, errwrite)
  File "C:\Python27\lib\subprocess.py", line 644, in _execute_child
    startupinfo)
WindowsError: [Error 2] The system cannot find the file specified

**Build log**
#####################################################################################
log date: 2020-04-09 16:11
commit sha: 6228fbca713e41c22c6a32f89b26215249cb7926
commit date: Mon Mar 2 04:49:13 2020 -0500
#####################################################################################

cmake -DCMAKE_INSTALL_PREFIX="C:\Program Files\MayaUSD\install\RelWithDebInfo" -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -G "Visual Studio 14 2015 Win64" -DMAYA_LOCATION="C:\Program Files\Autodesk\Maya2019" -DPXR_USD_LOCATION="C:\Program Files\USD" -DMAYA_DEVKIT_LOCATION="C:\devkitBase" -DMAYAUSD_DEFINE_BOOST_DEBUG_PYTHON_FLAG=OFF "c:\maya-usd"

**Specs:**
 - Windows 10 Pro 1903 Build 18362.720
 - MS Visual Studio 2015 Update 3
 - Maya 2019
 - Maya USD commit SHA 6228fbca713e41c22c6a32f89b26215249cb7926
 - Pixar USD 20.02

**Additional context**
I'm a developing developer, any assistance is greatly appreciated!

**Comment by HamedSabri-adsk** [comment]
Hi @AirWreckaStuff , can you upload the build_log.txt? Without the looking at the full log, it is hard to say what the problem is here. 

Also, do you see the same issue with VS 2017?

**Comment by AirWreckaStuff** [comment]
That was the entire log, what I copied and pasted, that's why I didn't attach the log.  Ironically, today I'm getting a little further.  I will loop back with my progress.  I did a couple windows updates last night.
