### ISSUE TITLE
Cannot see prim attributes with mayaUsd plugin, missing nodes

### ISSUE THREAD

**Issue by Thaelab** [Autodesk/maya-usd#418]
Hello,
I want to test the new maya-usd release (0.1.0) with usd-20.02 on linux, but I got some problems.

**Describe the bug**
After loading the mayaUsd plugin and creating a stage from an existing layer, it seems that some nodes (USDXform) are not really created in the scene. When I select an object in a scene, even though I see the shape in the outliner, I can’t access to its attributes in the attribute editor and I don’t see it in the node editor.
I also have a quite similar problem with AL_UsdMaya plugin: when I only have AL_UsdMayaPlugin enabled and when I load a proxy shape, I can’t select individual prims (I could do it in maya-usd-0.0.2), and the hierarchy doesn't appear in the outliner...

**Steps to reproduce**
1. In Maya, load the mayaUsdPlugin.so
2. Go to Create -> Universal Scene Description (USD) -> Stage From Existing Layer
3. Choose a USD scene (for example the Kitchen Set)
4. Click on an object in the scene and look at the attribute editor: nothing appears. Open the node editor: the node is not there. In the attribute editor, if you click on Selected, it says: "There is nothing selected". But the object appears in the scene and in the outliner, I can move it, for example.

**Expected behavior**
We should see the node in the node editor and its attributes in the attribute editor.

**Attachments**
![bug](https://user-images.githubusercontent.com/63449942/78982324-2babb800-7b22-11ea-948c-f370da5d47d4.PNG)

**Specs (if applicable):**
 - OS & version: Centos 7
 - Compiler & version: gcc 6.3.1
 - Maya version: maya 2019.2
 - Maya USD commit SHA: release v0.1.0 00d651a
 - Pixar USD commit SHA: release v20.02 be1a80f

**Additional context**
Here are the options I used in my CMakeLists:
BUILD_AL_PLUGIN ON
BUILD_PXR_PLUGIN ON
BUILD_ADSK_PLUGIN ON
BUILD_USDMAYA_PXR_TRANSLATORS ON
BUILD_MAYAUSD_LIBRARY ON
BUILD_HDMAYA ON
CMAKE_WANT_UFE_BUILD ON

Environment variables:
VP2_RENDER_DELEGATE_PROXY 1
MAYA_WANT_UFE_SELECTION 1

Am I missing something, or are there additional instructions I must follow to make the plugins fully work?

Thank you.

**Comment by santosd** [comment]
Hello @Thaelab, thank you for reaching out. Unfortunately, Maya 2019.2 doesn't have the required UFE version to support that functionality. V2 of UFE is required and that has only been implemented into the lastest version of Maya. If you would like, you can try out PR114 and it should be working there.
