### ISSUE TITLE
[MAYA-102232] HumanFemale.walk.usd crashes Maya on creating the stage

### ISSUE THREAD

**Issue by Xaia** [Autodesk/maya-usd#430]
**Describe the bug**
Creating the stage with HumanFemale.walk.usd kills Maya instantly.  

**Steps to reproduce**
1. Create stage with HumanFemale.walk.usd - provided by Pixar
2. Observe 

**Attachments**
![kf8YtxD7rf](https://user-images.githubusercontent.com/60515654/79241707-b3235f00-7e73-11ea-949c-d6acd038a52e.gif)

**Specs (if applicable):**
 - Windows 10
 -  Maya PR114

**Comment by santosg87** [comment]
thanks for logging this @Xaia !

we are currently investigating this behavior. we have it logged internally as MAYA-102232.

**Comment by HdC-adsk** [comment]
The fix for the crash is now being review. The general support for USDSkel will be implemented at some other time.

**Comment by kxl-adsk** [comment]
@Xaia Pull Request #514 fixed the issue. Please validate the fix and close this issue. FWIW. If you rely on Maya Preview Releases, then you will have to wait for the next beta release.

**Comment by kxl-adsk** [comment]
We validated this change internally. @Xaia Not sure how much time you will need to validate it, so I'm closing it for now. Feel free to reopen or log a new issue once you get a chance to try it.
