### ISSUE TITLE
boost filesystem

### ISSUE THREAD

**Issue by Sushant304** [Autodesk/maya-usd#435]
- ========== ...  GoogleTest installed. ==========
-- Found Boost 1.70.0 at C:/USD/lib/cmake/Boost-1.70.0
--   Requested configuration: QUIET REQUIRED COMPONENTS filesystem
-- Found boost_headers 1.70.0 at C:/USD/lib/cmake/boost_headers-1.70.0
CMake Error at C:/USD/lib/cmake/Boost-1.70.0/BoostConfig.cmake:95 (find_package):
  Could not find a package configuration file provided by "boost_filesystem"
  (requested version 1.70.0) with any of the following names:

    boost_filesystemConfig.cmake
    boost_filesystem-config.cmake

  Add the installation prefix of "boost_filesystem" to CMAKE_PREFIX_PATH or
  set "boost_filesystem_DIR" to a directory containing one of the above
  files.  If "boost_filesystem" provides a separate development package or
  SDK, be sure it has been installed.
Call Stack (most recent call first):
  C:/USD/lib/cmake/Boost-1.70.0/BoostConfig.cmake:124 (boost_find_dependency)
  C:/Program Files/CMake/share/cmake-3.17/Modules/FindBoost.cmake:444 (find_package)
  lib/mayaUsd/CMakeLists.txt:29 (find_package)

-- Configuring incomplete, errors occurred!
 I am getting this error while building
could you please help me...

**Comment by atkpln** [comment]
I am getting the same error,  how'd you fix this?

**Comment by HamedSabri-adsk** [comment]
@Sushant304 
Did you build USD with additional boost flags?
https://github.com/Autodesk/maya-usd/blob/dev/doc/build.md#boost

**Comment by atkpln** [comment]
That worked,  thanks!
