### ISSUE TITLE
Build with Visual Studio 2019?

### ISSUE THREAD

**Issue by YKdvd** [Autodesk/maya-usd#454]
**Describe the issue**
Support for building with Visual Studio 2019.

Recent Pixar USD releases seem to support building with Visual Studio 2019, but maya-usd still seems to require VS2017 (for Maya 2020).  Is there any support for VS 2019 compiling (with the v141/2017 toolchain) in the works?

**Comment by seando-adsk** [comment]
MayaUsd is a plugin for Maya, therefore it needs to build with the Maya devkit. That means ideally when compiling you should use the same compiler version as the Maya version you are targeting. For Maya 2020 that was Visual Studio 2017. See here for more info: http://help.autodesk.com/view/MAYAUL/2020/ENU/?guid=Maya_SDK_MERGED_Setting_up_your_build_Windows_environment_64_bit_html

However I think it should work compiling with Visual Studio 2019.

**Comment by YKdvd** [comment]
While VS 2019 comes with the current compiler toolchain (v142), it is also possible to install the v141 (VS 2017) and v140 (VS 2015) toolchains for situations like this, so that you don't need multiple versions of the full VS IDE application.

I don't have the output or logs any more, but I believe trying to build with VS2019 was giving a "Generator / Visual Studio 15 2017 Win64 / could not find any instance of Visual Studio" sort of error, running in an x64 Native Tools command prompt.   If I get a chance I'll try again and post the results.

In case VS2019 didn't like having VS2017 installed as well, I went to a different machine, installed VS2017, and compiled things up.  But it would be nice if VS2019 could be used.

**Comment by seando-adsk** [comment]
What version of cmake are you using? I believe cmake < 3.14 does not support VS 2019.

Another thing to be aware of when using VS2019. You'll need to build USD using it as well. As part of the USD build it downloads and builds boost. The boost libraries have the toolchain (vc141/vc142/etc) as part of the output file names.

**Comment by kxl-adsk** [comment]
@YKdvd Were you able to resolve this issue?

**Comment by YKdvd** [comment]
> @YKdvd Were you able to resolve this issue?

Sorry, I missed this.  I think I was rushed the last time I tried to build these and used my existing 2017 setup on a remote machine, rather than trying 2019 again on mine.  It was rather ironic, as something that came with the most recent 2017 (I think it was CMake?) was too old and prevented build, and had to be updated.

I think they may be getting back to looking at USD again around here, so I may try with 2019/v141 at some point, but I haven't again yet.

**Comment by kxl-adsk** [comment]
Let's close it for now...please re-open if you run into trouble again.
