### ISSUE TITLE
Fatal Error when loading 

### ISSUE THREAD

**Issue by AirWreckaStuff** [Autodesk/maya-usd#458]
**Describe the issue**
After successful completion of USD and Maya USD builds, I'm not able to actually load the plugins.  The AL_USDMayaPlugin.mll, AL_USDMayaTestPlugin.mll and the pxrUsd.mll individually cause a fatal error when loading, shutting down Maya entirely.  The others are no issue.  This is occurring on multiple workstations, so I know there is some error with the build, but I'm not able to hone in on the problem.  Also, I had moved the original folders that I built with to another location and Maya was looking for files in there, I think if they are supposed to stay in place and be referenced it should be clear in the build instructions.
![Annotation 2020-04-23 160640](https://user-images.githubusercontent.com/26884617/80144764-16507800-857d-11ea-8251-5be0caf41644.png)
![mayaerror](https://user-images.githubusercontent.com/26884617/80148375-f9b73e80-8582-11ea-8867-3fc8462136f4.png)

**Build log**
[build_log.txt](https://github.com/Autodesk/maya-usd/files/4524968/build_log.txt)

**Specs:**
 - Windows 10 Pro Version 1909 build 18363.778
 - Visual Studio 2017
 - Maya 2019
 - Maya USD commit not sure but HEAD says 6228fbca713e41c22c6a32f89b26215249cb7926 and I downloaded on March 2 2020
 - Pixar USD not sure but build 20.02

**Maya Output window:**
Initialized VP2.0 renderer {
  Version : 2016.11.44.12. Feature Level 5.
  Adapter : Quadro T1000/PCIe/SSE2
  Vendor ID: 4318. Device ID : 16027
  Driver : .
  API : OpenGL V.4.6.
  Max texture size : 16384 * 16384.
  Max tex coords : 32
  Shader versions supported (Vertex: 5, Geometry: 5, Pixel 5).
  Shader compiler profile : (Best card profile)
  Active stereo support available : 0
  GPU Memory Limit : 4096 MB.
  CPU Memory Limit: 30871 MB.
  MultiDraw consolidation: enabled
}
OpenCL evaluator is attempting to initialize OpenCL.
Detected 2 OpenCL Platforms: 
 0: NVIDIA Corporation. NVIDIA CUDA. OpenCL 1.2 CUDA 10.2.104.
 Supported extensions: cl_khr_global_int32_base_atomics cl_khr_global_int32_extended_atomics cl_khr_local_int32_base_atomics cl_khr_local_int32_extended_atomics cl_khr_fp64 cl_khr_byte_addressable_store cl_khr_icd cl_khr_gl_sharing cl_nv_compiler_options cl_nv_device_attribute_query cl_nv_pragma_unroll cl_nv_d3d10_sharing cl_khr_d3d10_sharing cl_nv_d3d11_sharing cl_nv_copy_opts cl_khr_gl_event cl_nv_create_buffer cl_khr_int64_base_atomics cl_khr_int64_extended_atomics 
 1: Intel(R) Corporation. Intel(R) OpenCL. OpenCL 2.1 .
 Supported extensions: cl_khr_3d_image_writes cl_khr_byte_addressable_store cl_khr_depth_images cl_khr_fp64 cl_khr_global_int32_base_atomics cl_khr_global_int32_extended_atomics cl_khr_icd cl_khr_image2d_from_buffer cl_khr_local_int32_base_atomics cl_khr_local_int32_extended_atomics cl_khr_spir 
OpenCL evaluator choosing OpenCL platform NVIDIA Corporation.
Choosing OpenCL Device Quadro T1000.  Device Type: GPU  Device is available.

#############################################################################
#  VP2_RENDER_DELEGATE_PROXY is overridden to 'true'.  Default is 'false'.  #
#############################################################################
***********here is what appear in script editor after trying to load pxrusd.mll***********
Stack trace:
  Foundation.dll!TbitFieldFixedN::setBit

**Script Editor:**
file -f -new;
// untitled // 
commandPort -securityWarning -name commandportDefault;
onSetCurrentLayout "Maya Classic";
updateRenderOverride;
// Warning: file: C:/Program Files/Autodesk/Maya2019/scripts/startup/autoLoadPlugin.mel line 35: Loading plug-in "mtoh" has resulted in changes to the scene that may need to be saved. // 
// Warning: file: C:\Users\econcolino\OneDrive - Microdesk\Documents\maya\2019\prefs\filePathEditorRegistryPrefs.mel line 4: filePathEditor: Attribute 'aiImage.filename' is invalid or is not designated 'usedAsFilename'. // 
// Warning: file: C:\Users\econcolino\OneDrive - Microdesk\Documents\maya\2019\prefs\filePathEditorRegistryPrefs.mel line 5: filePathEditor: Attribute 'aiPhotometricLight.aiFilename' is invalid or is not designated 'usedAsFilename'. // 
// Warning: file: C:\Users\econcolino\OneDrive - Microdesk\Documents\maya\2019\prefs\filePathEditorRegistryPrefs.mel line 6: filePathEditor: Attribute 'aiStandIn.dso' is invalid or is not designated 'usedAsFilename'. // 
// Warning: file: C:\Users\econcolino\OneDrive - Microdesk\Documents\maya\2019\prefs\filePathEditorRegistryPrefs.mel line 7: filePathEditor: Attribute 'aiVolume.filename' is invalid or is not designated 'usedAsFilename'. // 
// AbcExport v1.0 using Alembic 1.7.5 (built Feb  6 2018 18:28:08) // 
evalDeferred "shaderBallRendererMenuUpdate";
// Warning: line 1: filePathEditor: Attribute 'aiStandIn.dso' and label 'Standin' have been saved already. // 
// Warning: line 1: filePathEditor: Attribute 'aiVolume.filename' and label 'VDB' have been saved already. // 
// Warning: line 1: filePathEditor: Attribute 'aiImage.filename' and label 'Image' have been saved already. // 
// Warning: line 1: filePathEditor: Attribute 'aiPhotometricLight.aiFilename' and label 'IES' have been saved already. // 
import arnold
// Successfully imported python module 'arnold' // 
import mtoa
// Successfully imported python module 'mtoa' // 
import mtoa.cmds.registerArnoldRenderer;mtoa.cmds.registerArnoldRenderer.registerArnoldRenderer()
// Successfully registered renderer 'arnold' // 
updateRenderOverride;
// AbcImport v1.0 using Alembic 1.7.5 (built Feb  6 2018 18:28:08) // 
updateRendererUI;
updateRendererUI;
***********here is what appears in script editor after trying to load pxrusd.mll***********
file  -type mayaAscii;
//Result: untitled.ma //

**Comment by suesauer** [comment]
Do you perhaps also have Houdini Solaris running on these pc's? I find that if my build was successful but the Maya plugin doesn't want to load, it is usually an environment pathing issue.

**Comment by kxl-adsk** [comment]
@AirWreckaStuff When you move files, you have to update the mod file. Given that you are discovering the plugins, I'm guessing you did that. The crash could mean issues with discovered USD version (vs compiled one) OR devkit mismatch.

I see you have mtoa in the search path...could it be that you have another USD library in your search paths?

**Comment by kxl-adsk** [comment]
I'm closing this issue. @AirWreckaStuff please reopen if you continue to have issues after trying what was described in my previous comment (https://github.com/Autodesk/maya-usd/issues/458#issuecomment-641523706)

**Comment by satcar77** [comment]
I have the same issue with the same specs. I did the build using both the dev branch and the master branch, got the same result. I have recompiled with every devkit for maya 2019 and several versions of USD to no avail.
