### ISSUE TITLE
USD stage/import not loading Nvidia Attic correctly

### ISSUE THREAD

**Issue by Xaia** [Autodesk/maya-usd#459]
**Describe the bug**
Imported or created stage is empty, although the structure is visible.

**Steps to reproduce**
1. Download nvidia attic from https://developer.nvidia.com/usd 
2. Load as a stage or import 

**Attachments**
![EqCqSPuYSw](https://user-images.githubusercontent.com/60515654/80194909-667e1780-861b-11ea-8928-f17e87226acc.gif)

**Specs (if applicable):**
 - Windows 10
- Maya PR114

**Comment by Xaia** [comment]
My bad, it works. The references are absolute and pointing to  ../../atticwork/attic_v5/
once you set up the structure, everything loads fine.

**Comment by theGlaive** [comment]
> My bad, it works. The references are absolute and pointing to ../../atticwork/attic_v5/
> once you set up the structure, everything loads fine.

Could you please explain in more details what did you do to make it work?

**Comment by Xaia** [comment]
create folder structure  ../../atticwork/attic_v5/ that's it

**Comment by theGlaive** [comment]
Thanks. It works.
But how did you figure out that structure?

**Comment by fowlertADSK** [comment]
You'll see some errors in the Output Window when opening the file that mention that specific relative path.  I think NVidia was going to update the file, but what I did to fix it locally was just convert the top level .usd file to be ascii and then replaced "../../atticwork/attic_v5" with "."
