### ISSUE TITLE
Turning on and duplicating lights low performance 

### ISSUE THREAD

**Issue by Xaia** [Autodesk/maya-usd#461]
**Describe the bug**
It takes forver to turn on and duplicate lights, feels like viewport is having hard time figuring it out.

**Steps to reproduce**
1. Download nvidia attic scene
2. turn on lighting 
3. create and duplicate some area lights

**Attachments**
![nTk5GKBjGT](https://user-images.githubusercontent.com/60515654/80204292-e199fa80-8628-11ea-98c1-620ab8702874.gif)

**Specs (if applicable):**
 - Windows 10
- Maya PR114
- VP2

**Comment by santosd** [comment]
Hello @Xaia , thank you for reporting this, I have taken a look and was able to reproduce the issue. It also seems that the deletion of the lights seems to take quite sometime. However, I don't think this is so much related to USD as it is related to the textures in the scene. I noticed if I turn off the textures then things perform a lot better. I have similar results in a scene that doesn't contain USD data.

**Comment by Xaia** [comment]
Oh I see, so it is just Maya being Maya then :) The scene is so simple and "editing" performance is so poor. I guess I never notice that problem since in production we never have textures in the viewport.

**Comment by kxl-adsk** [comment]
I'm not sold on `Maya being Maya then` - we will understand the source of this slowdown. Thx for reporting @Xaia!

**Comment by Xaia** [comment]
No worries @kxl-adsk We all have the same goal here, make maya better.
I think there are hundreds of instances where VP2 is slowing down entire Maya so I am not surprised that something like this is happening here. I wish we had some performance improvements on that front since it can slow down even with simple things.

**Comment by kxl-adsk** [comment]
We are actively working on instancing and consolidation performance improvements with Subscene override which should land in the next beta build. This will result in big performance improvements for VP2RenderDelegate...but unfortunately, this light creation delay didn't change.

**Comment by santosd** [comment]
I have reported the issue to the team working on the Maya Viewport. They will be taking a look. Thanks @Xaia. Let us know if you run into any other issues we can help out with. Like you said we all have the same goal of making Maya better :)
