### ISSUE TITLE
Unable to compile ADSK plugin on Windows 10 (Missing Boost::system link)

### ISSUE THREAD

**Issue by gagnovski** [Autodesk/maya-usd#500]
**Describe the issue**
I'm currently trying to compile the plugin using all the recommended instructions, but can't seem to get passed an issue when it reaches to configure the Autodesk plugin. It mentions the mayaUsd target links to target "Boost::system" but the target is not found

I've attempted building USD on 20.05 and 19.11.

I've also tried building maya-usd with and without Ninja, and made sure I've set the appropriate system environment variables. I'm making sure to only have one compiled version of USD in the paths, and don't have any older paths laying around.

I'm trying to build with 19.11 as I'd like to build for Katana as well.

I've attached two build logs, showing the results from trying to use USD 19.11 & 20.05

Thanks!
Jason

**Build log**
Logs built using Visual Studio 2017
[build_log_19_11.txt](https://github.com/Autodesk/maya-usd/files/4647097/build_log.txt)
[build_log_20_05.txt](https://github.com/Autodesk/maya-usd/files/4647197/build_log.txt)

Log built using Visual Studio 2015 for both USD and maya-usd builds
[build_log_20_05_2015.txt](https://github.com/Autodesk/maya-usd/files/4647371/build_log.txt)

**Specs:**
 - Windows 10 Home 1909 (18363.836)
 - Visual Studio 2015/2017
 - Maya 2018
 - Maya USD commit SHA: master at  4140929
 - Pixar USD commit SHA: 
       19.11 master at 4b11629 
       20.05 master at ebac0a8

**Additional context**
Dependencies:
Jinja2 2.11.2
PyOpenGL 3.1.5
PySide 1.2.4
PyYAML 5.3.1
Python 2.7.18
CMake 3.17.2
Boost 1.70.0 (being downloaded via USD build)

USD build command:

When building with 19.11:
python build_usd.py --build-args boost,"--with-date_time --with-thread --with-system --with-filesystem" --no-maya "D:\tools\USD19_11"

When building with 20.05:
python build_usd.py "D:\tools\USD" --build-args boost,"--with-date_time --with-thread --with-system --with-filesystem"

maya-usd build command:
python build.py --maya-location "C:\Program Files\Autodesk\Maya2018" --pxrusd-location "D:\tools\USD" D:\tools\maya\usd\workspace

**Comment by HamedSabri-adsk** [comment]
Hi @gagnovski , this issue is already fixed in `dev` branch. Our master branch is currently way behind latest dev.

For now, please pass `system` to the list of Boost components:

https://github.com/Autodesk/maya-usd/blob/64782de5f2a3b30b69af510611528150e5879f10/lib/mayaUsd/CMakeLists.txt#L29

Hope this helps.

**Comment by gagnovski** [comment]
Thanks @HamedSabri-adsk,

I tried this by changing the file below and tried to compile, however, it comes up with quite a few errors when I try to build.

I should note, I'm using a compiled version of USD 20.05 with VS 2015 at the moment. Figured 2015 was the safer bet based on the recommendations.

[build_log.txt](https://github.com/Autodesk/maya-usd/files/4647670/build_log.txt)

https://github.com/Autodesk/maya-usd/blob/41409295ec063d4f72d49cd6894f03595fa8abc2/lib/CMakeLists.txt#L29

I did attempt just checking out the dev branch and compiling but came across an issue where it got stuck after building mayaToHydra by the looks of it. With the build log and the errors below.

[build_log.txt](https://github.com/Autodesk/maya-usd/files/4647723/build_log.txt)

Traceback (most recent call last):
  File "build.py", line 597, in <module>
    BuildAndInstall(context, context.buildArgs, context.stagesArgs)
  File "build.py", line 366, in BuildAndInstall
    RunCMake(context, extraArgs, stagesArgs)
  File "build.py", line 278, in RunCMake
    multiproc=FormatMultiProcs(context.numJobs, generator)))
  File "build.py", line 156, in Run
    .format(cmd=cmd, log=os.path.abspath(context.logFileLocation)))
RuntimeError: Failed to run 'cmake --build . --config RelWithDebInfo --target install -- /M:16'
See D:\tools\maya\usd\workspace\build\RelWithDebInfo\build_log.txt for more details.

Cheers!
Jason

**Comment by HamedSabri-adsk** [comment]
@gagnovski I had a closer state of master branch as well as the logs you posted and basically there are two separate issues here:

1- current master branch currently doesn't have some important changes from dev branch as it should have. looking at your master build log, there is an error around _snprintf

`D:\tools\USD20_05\include\boost-1_70\boost/system/detail/system_category_win32.hpp(52): error C2039: '_snprintf': is `

This can be fixed by adding `HAVE_SNPRINTF` to `maya-usd/cmake/defaults/msvcdefaults.cmake`:

```
# Needed to prevent Python from adding a define for snprintf
# since it was added in Visual Studio 2015.
_add_define(HAVE_SNPRINTF)
```
Keep in mind that a lot has changed since in dev. We have completely reworked how compiler configuration work:
e.g
https://github.com/Autodesk/maya-usd/blob/64782de5f2a3b30b69af510611528150e5879f10/cmake/compiler_config.cmake#L53

2- your second issue with dev branch is new to me. Would it be possible to build dev branch with VS2017 and see if you can reproduce the problem? You also need to rebuild USD with VS 2017.

**Comment by gagnovski** [comment]
Hi @HamedSabri-adsk,

I did manage to get it compiled without errors using VS 2017, and using the dev branch.

[build_log.txt](https://github.com/Autodesk/maya-usd/files/4650907/build_log.txt)

However, I do get errors in Maya when I try to use the plugins, minus the AL one. The AL plugins appear to work just fine.

This is the error I get when I try to load the Pxr plugin (pxrUsd.mll):

Error: file: C:/Program Files/Autodesk/Maya2018/scripts/others/pluginWin.mel line 290: ImportError: file <maya console> line 1: No module named UsdMaya

// Error: file: C:/Program Files/Autodesk/Maya2018/scripts/others/pluginWin.mel line 290: initializePlugin function failed (pxrUsd) // 

When I load the mayaUsdPlugin, it loads fine. However, when I attempt to import a USD file, such as the kitchen set, it crashes immediately. I think there is already an issue opened up for this one. 

Cheers,
Jason

**Comment by HamedSabri-adsk** [comment]
@gagnovski 
maya 2018 has very limited features for USD. Without UFE ( Universal Front End ), you won't be getting much from mayaUsdPlugin. 

If possible, I would recommend switching to Maya 2019 or above and build maya-usd project with UFE and QT for getting the full features.

We also have this message for developers in the log:
```
=========================================================================================
UFE is not available in Maya.  Maya2019 and later are supported only.
=========================================================================================
This warning is for project developers.  Use -Wno-dev to suppress it.

-- QT_LOCATION not set. Building Qt features will be disabled.
```
Hope this helps.
Cheers

**Comment by gagnovski** [comment]
Thanks @HamedSabri-adsk for your help!

I'll see about updating to Maya 2019 in that case and see how it goes. At the very least, I have something I can work with for the time being.

If anything else comes up, I can open a new issue, but I think you've helped me enough to continue on.

Cheers!
Jason

**Comment by kxl-adsk** [comment]
@gagnovski I believe this issue can be closed?

**Comment by gagnovski** [comment]
Hi @kxl-adsk,

Yep, we can close this one.

Thanks!
Jason
