### ISSUE TITLE
[MAYA-104978] Right click on a USD shape leads to an error when working with variants

### ISSUE THREAD

**Issue by devGitHub48** [Autodesk/maya-usd#504]
**Describe the bug**
After Creating a Stage from an existing layer, Try to change variants by right clicking on assets having variants.
An error just appears

**Steps to reproduce**
1. Go to 'Create'> USD > Stage From Existing Layer...
2. Import a Stage with assets with variants
3. Right Click on the asset with Variants
4. Go the Variants
5. See the error in the script Editor
 ```
Traceback (most recent call last):
  File "C:/Program Files/Autodesk/Maya2021/Python/lib/site-packages/maya/app/ufe/outlinerSupport.py", line 32, in buildMenuWrapper
    buildMenu(contextOps, itemPath)
  File "C:/Program Files/Autodesk/Maya2021/Python/lib/site-packages/maya/app/ufe/outlinerSupport.py", line 54, in buildMenu
    i = cmds.menuItem(**kw)
RuntimeError: Collection not found, or no current collection. 
```

You can workaround this error by selecting a non-Usd object, right clicking on it. And then select back your Usd-asset

**Expected behavior**
No error

**Specs (if applicable):**
 - Windows 10
 - 2021 (PR114)
 - Maya USD binaries from PR114

**Comment by santosd** [comment]
Hello @devGitHub48 , Thank you for reporting this, it was something that we had seen internally as well and had logged it as MAYA-104978.

**Comment by devGitHub48** [comment]
Thanks a lot @santosd

**Comment by santosd** [comment]
This issue has been fixed and the fix should be coming out in the next PR.  I will go ahead and close this issue for now.
