### ISSUE TITLE
Skeleton Not Saved in Exported USD file

### ISSUE THREAD

**Issue by stevkalinowski** [Autodesk/maya-usd#505]
**Describe the bug**
Exporting USD file does not appear to save skeleton's joints.  Or possible that the importer does not read them back in?

**Steps to reproduce**
* Open a file that contains a skeleton
* File > Export All
* Choose "USD Export" from file type
* Export
* File > New Scene
* File > Import
* Choose the exported file

**Expected behavior**
I would expect that the skeleton be exported in the usd file and should read back in exactly the same.

**Attachments**
[sphere_test.zip](https://github.com/Autodesk/maya-usd/files/4653734/sphere_test.zip)

**Specs:**
Windows 10
Maya PR114

**Comment by santosg87** [comment]
Hi @stevkalinowski thank you for logging this. we are currently working on the export commands. our export put out the default options from export, which don't usually include skel, if i am not mistaken.

one workaround here would be to run the file mel cmd and add the arguments through there.
the flags are:
exportSkels=[auto, explicit]
exportSkins=[auto, explicit]

where "auto" will try to automatically create SkelRoots, and "explicit" will only try to export only objects under SkelRoots. so you should have something like this for an export all:

file -force -options file -force -options ";exportSkels=auto;exportSkins=auto" -type "USD Export" -pr -ea "[your File export].usd";

**Comment by santosg87** [comment]
marking this one as closed, as it is supported on the commands. :)

**Comment by stevkalinowski** [comment]
I just tried the mel command in PR115.  Maya hard crashed.

**Comment by stevkalinowski** [comment]
Using a more simplified scene, I can get it to export without a crash.  However, when importing the bones don't come back in.  If I click on Hierarchy view in the Import options I can see that the joints are not there.

Not sure if this is also something only done in mel, I attempted this but still didn't work.

file -import -options ";importSkels=auto;importSkels=auto" -type "USD Import" "d:\\test.usd";

**Comment by stevkalinowski** [comment]
I tested in PR115 and there is no crash.  I have issues but I'll make a new case.

**Comment by TechArtistG** [comment]
I'm on Maya 2021 PR121 with USD plugin 0.6 and can't get skeletons to export, opened a new issue https://github.com/Autodesk/maya-usd/issues/1055
