### ISSUE TITLE
MTOH draws above camera guides and gate

### ISSUE THREAD

**Issue by marsupial** [Autodesk/maya-usd#525]
**Describe the bug**
When trying to show the camera resolution/gate in the viewport, any delegate will draw on top of whatever Maya did.

**Steps to reproduce**
1. Enable film or resolution gate for the viewport camera.
2. Load **mtoh**
3. Select a delegate

**Expected behavior**
Not to draw on top of the guides

**Comment by santosd** [comment]
@marsupial I tested this out in PR115 and I was not able to replicate the issue. However, I am occasionally hitting a crash when enabling mtoh after enabling the display of the resolution gate.

**Comment by marsupial** [comment]
If you're building from dev, this is no longer an issue and can be closed (#526 & #567).
Just started testing PR115 last week, and am not seeing a crash related to this.

**Comment by santosd** [comment]
Thank you @marsupial I will go ahead and close this out. I will see if others are hitting a crash on my end and if so I will log an issue for that.
