### ISSUE TITLE
proxyShape does not hold a strong pointer to it's UsdStage through MayaUsdStageData

### ISSUE THREAD

**Issue by williamkrick** [Autodesk/maya-usd#528]
**Describe the bug**
In `MayaUsdProxyShapeBase::computeInStageDataCached` we open or create a new `UsdStage`. The stage is saved into a MayaUsdStageData and stored in the node. `MayaUsdStageData` doesn't keep a strong reference to the stage (`UsdStageRefPtr`), instead it only holds `UsdStageWeakPtr` and relies on the stage cache keeping a strong reference to keep the `UsdStage` alive.

If something clears the `UsdStageCache` then all the proxyShapes will lose their stage data and break.

**Steps to reproduce**
1. In `MayaUsdProxyShapeBase::computeInStageDataCached` remove the calls which create `UsdStageCacheContext`. This disables the `UsdStageCache`.
2. Build and try to use the proxyShape. Nothing works.

**Expected behavior**
The proxyShape should not rely on the `UsdStageCache` to keep it's data alive.

**Additional context**
There's a big comment in `MayaUsdStageData` explaining the reasoning behind using a weak pointer.

> 
>         // The original Pixar code was the following:
>         //
>         // UsdStageRefPtr stage;
>         //
>         // Now using a weak pointer instead of a referencing pointer.  The AL
>         // plugin originally used a referencing pointer, but ran into problems.
>         // From a Rob Bateman @ AL e-mail, 7-Apr-2019:
>         // 
>         // "The reason for the weak pointer was that we found that Maya seemed
>         // to have a memory leak (as in, the MPxData derived objects were being
>         // created, but never deleted when we expected them to be - possibly by
>         // design?). We had originally used a direct mirror of the Pixar data
>         // object, but because the data objects were never freed (even after
>         // file new), the original stage would be retained. This meant the
>         // internal SdfLayerCache in USD would keep hold of the previously
>         // loaded layers. So we found we had this problem: 
>         // 
>         // 1. Import some.usda file into a proxy shape.
>         // 2. Make some modifications
>         // 3. File New
>         // 4. Import the same "some.usda" file into a proxy shape.
>         // 
>         // At this point, USD would essentially hand you back the stage
>         // composed of the modified layers, rather than a clean stage composed
>         // from the files on disk. Switching the type from a shared_ptr to a
>         // weak_ptr worked around this issue. Basically if we use a shared
>         // pointer here, the only way to reload a scene, would be to restart
>         // Maya."

We should make this workflow correct while having the `MayaUsdStageData` hold a strong pointer to the `UsdStage`.

**Comment by HamedSabri-adsk** [comment]
@williamkrick  
#1142 fixes the issue that you described here by changing the UsdStageWeakPtr back to UsdStageRefPtr. 

I removed your work around in this commit: 4b8947b158e47d0e2f00802d49e56e3faf9d3fa2

**Comment by santosg87** [comment]
can we close this one?

**Comment by kxl-adsk** [comment]
Yes, the change was made as part of 1422add5ab734ef22fb8cf1cd34ef1b1e8b891b6
