### ISSUE TITLE
Support exporting blendshapes

### ISSUE THREAD

**Issue by pmolodo** [Autodesk/maya-usd#542]
**Is your feature request related to a problem? Please describe.**
We want the ability to export usd blendshapes (using the UsdSkel schema).

**Describe the solution you'd like**
An option to enable blendshape export (similar to the option to enable skinning), which causes the appropriate attributes to be authoredin the UsdSkel schema.

**Describe alternatives you've considered**
There is an old PR against the pixar USD repo, before they migrated all maya code to this one:

https://github.com/PixarAnimationStudios/USD/pull/896 

I've made some initial attempts to port this, but have not finished.

**Comment by kxl-adsk** [comment]
Linking #1016 to this issue. 

@pmolodo I don't know if you made any progress on this issue on your end, but would be good to check if what's being reviewed addresses your issue as well.

**Comment by pmolodo** [comment]
#1016 is a much more thorough implementation than ours was, and should definitely cover our use cases!

**Comment by kxl-adsk** [comment]
Pull request has been merged. Based on @ysiewappl comments, the sample test file can be found in https://github.com/Autodesk/maya-usd/blob/dev/test/lib/usd/translators/UsdExportBlendShapesTest/blendShapesExport.ma and contains various test cases, which includes:
- Single base to single target, non-animated/animated
- Single base to multiple in-betweens, non-animated/animated
- Multiple bases to multiple targets, animated
- A setup where there is an extra squash deformer in the stack
- A setup with "baked" blendshape targets
- A setup with a skinned cube with "baked" blendshape targets

@santosg87 @santosd please log an internal ticket to validate this contribution.

**Comment by kxl-adsk** [comment]
@pmolodo #1016 is merged. Can you validate and close this issue?

**Comment by pmolodo** [comment]
Oops, didn't notice this... yup, this is done!
