### ISSUE TITLE
[MAYA-105623] The "orientation" flag on meshes appears to be ignored on import

### ISSUE THREAD

**Issue by koen-v** [Autodesk/maya-usd#561]
**Describe the bug**
When importing a mesh with the _uniform token orientation = "leftHanded"_ flag set, all the faces show up reversed in maya, ie they get imported as if they are right handed. 

**Steps to reproduce**
Unpack the attached box.zip
Import box.geo.usd into maya

**Expected behavior**
I would expect the face vert order to be reversed on import

**Attachments**
[box.zip](https://github.com/Autodesk/maya-usd/files/4730889/box.zip)

![image](https://user-images.githubusercontent.com/4185553/83773229-2148fe80-a639-11ea-90e5-91062aec9add.png)

**Specs (if applicable):**
Maya PR 115

**Comment by santosd** [comment]
Tested in the latest PR and I was also able to replicate the issue. When bringing it in as a USD it works as expected, but imported the faces look flipped.
