### ISSUE TITLE
Replace boost::filesystem/system with std::filesystem

### ISSUE THREAD

**Issue by ArcEarth** [Autodesk/maya-usd#562]
**Describe the issue**
USD is failed to build on my machine because it failed to locate `boost::filesystem`.
It is 2020, we should replace boost::filesystem and boost::system with C++17/11 standard.
The filesystem feature was already implemented in GCC 6.3 which is on the VFX platform.
And was there in Visual Studio / Clang for decades.
There is nothing blocking it from being used in Maya/USD.

**Build log**
```
CMake Error at C:/Users/Yupen/source/repos/maya/artifactory/Windows/USD/213fee2/lib/cmake/Boost-1.70.0/BoostConfig.cmake:95 (find_package):
  Found package configuration file:

    C:/Users/Yupen/source/repos/maya/artifactory/Windows/USD/213fee2/lib/cmake/boost_filesystem-1.70.0/boost_filesystem-config.cmake

  but it set boost_filesystem_FOUND to FALSE so package "boost_filesystem" is
  considered to be NOT FOUND.  Reason given by package:

  No suitable build variant has been found.

Call Stack (most recent call first):
  C:/Users/Yupen/source/repos/maya/artifactory/Windows/USD/213fee2/lib/cmake/Boost-1.70.0/BoostConfig.cmake:124 (boost_find_dependency)
  C:/Program Files/CMake/share/cmake-3.17/Modules/FindBoost.cmake:444 (find_package)
  lib/mayaUsd/CMakeLists.txt:29 (find_package)
```

**Comment by seando-adsk** [comment]
Yupeng, the use of boost comes from Pixar's [USD repo](https://github.com/PixarAnimationStudios/USD) 

We are compiling it and placing it in artifactory for use in the maya-usd repo. Boost places the toolset version in the file names, so they end up with "vc-141" since the artifact was compiled with Visual Studio 2017. Are you using Visual Studio 2019? 

I believe there is a boost flag that will allow checking for multiple toolsets.

**Comment by HamedSabri-adsk** [comment]
In addition to what Sean said, we currently have following dependencies to boost as well:
```
boost::python
boost::hash_combine
boost::filesystem
boost::system
boost::make_shared 
```
We have already discussed replacing these gradually in our internal meetings.

**Comment by ababak** [comment]
In my case, the error is the same but the full error text explains it a bit:
```
-- Found Boost 1.70.0 at C:/usd/lib/cmake/Boost-1.70.0
--   Requested configuration: QUIET REQUIRED COMPONENTS filesystem;system
-- Found boost_headers 1.70.0 at C:/usd/lib/cmake/boost_headers-1.70.0
-- Found boost_filesystem 1.70.0 at C:/usd/lib/cmake/boost_filesystem-1.70.0
-- No suitable boost_filesystem variant has been identified!
--   boost_filesystem-vc142-mt-x64-1_70.lib (64 bit, need 32)
CMake Error at C:/usd/lib/cmake/Boost-1.70.0/BoostConfig.cmake:95 (find_package):
  Found package configuration file:

    C:/usd/lib/cmake/boost_filesystem-1.70.0/boost_filesystem-config.cmake

  but it set boost_filesystem_FOUND to FALSE so package "boost_filesystem" is
  considered to be NOT FOUND.  Reason given by package:

  No suitable build variant has been found.
```
So the reason it fails is `boost_filesystem-vc142-mt-x64-1_70.lib (64 bit, need 32)`

Are there any more or less simple workarounds?

**Comment by ppt-adsk** [comment]
@ababak if you're compiling in a Windows cmd shell, please make sure you've sourced the proper compilation setup script from Visual Studio.  On my machine, this is
"C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Auxiliary\Build\vcvars64.bat"
Hope this helps.

**Comment by seando-adsk** [comment]
@ababak When you built USD did you pass in extra boost flags? For MayaUSD we build USD with the extra build args "boost, --with-date_time --with-thread --with-system --with-filesystem"

**Comment by ababak** [comment]
@ppt-adsk I am building inside a docker container and I am sourcing the same setup script I've been using when building the USD itself.
@seando-adsk No extra boost flags were used when I built the USD.

I've fixed this error by specifying `--generator="Visual Studio 16 2019"`
```
Success MayaUSD build and install !!!!
Elapsed time: 00:40:33
```

**Comment by seando-adsk** [comment]
@ababak I'm surprised you were able to build MayaUSD successfully if your USD build didn't have boost filesystem/system. You can see [here](https://github.com/Autodesk/maya-usd/blob/dev/lib/mayaUsd/CMakeLists.txt#L29) that they are required packages.

**Comment by ababak** [comment]
@seando-adsk It did. Just somewhy it requested a 32-bit variant while there was only a 64-bit one.

**Comment by ababak** [comment]
Here's my docker build project for reference: https://github.com/ababak/usd-build
