### ISSUE TITLE
WANT_UFE_BUILD scattered throughout build process

### ISSUE THREAD

**Issue by marsupial** [Autodesk/maya-usd#589]
**Describe the issue**
**WANT_UFE_BUILD** can wind up controlling vtable layout and availability of functions.
Currently it's usage is scattered throughout CMake and headers in mayaUsd, hdMaya, mayaToHydra, AL-usdmaya.  Usually as **PRIVATE** sometimes as **PUBLIC** (#583).

Seems better to be held in a spot where all sub-projects consume the value, and anyone building against a distribution can ingest the MACRO properly (i.e. in an installed CMake target).

**Comment by kxl-adsk** [comment]
@marsupial We discussed this internally and agreed that `WANT_UFE_BUILD` should be `PUBLIC` in https://github.com/Autodesk/maya-usd/blob/f2ccf7ae4012ba5a23a5b9cbe7e0947dd63160d9/lib/mayaUsd/CMakeLists.txt#L47

**Comment by kxl-adsk** [comment]
Fixed in dev branch.
