### ISSUE TITLE
Please add some features to make the uv / st primvars recognizable as such.

### ISSUE THREAD

**Issue by koen-v** [Autodesk/maya-usd#604]
Currently it is hard to filter out all the primvars that represent uv sets and impossible to know the order they had in maya in usd files exported from maya.

For the uv sets, would it be possible to set the type to "texCoord2f[]" instead of the float2[] they currently have, that would identify them as uv sets. Secondly would it be possible to add some customData to the primVar to know the index this set had in maya? 

For displayColor there is this:
color3f[] primvars:displayColor = [(0, 0, 0)] (
                            customData = {
                                dictionary Maya = {
                                    bool generated = 1
                                }
                            }
                            interpolation = "uniform"
                        )

Would be great if uv had something like this:

texCoord2f[] myUvSet = [(0, 0)] (
                            customData = {
                                dictionary Maya = {
                                    int UVSetIndex = 1
                                }
                            }
                            interpolation = "faceVarying"
                        )

That would allow us to later re-construct the uv set usage more easily.

Thanks,
Koen

**Comment by kxl-adsk** [comment]
@koen-v this was fixed by https://github.com/Autodesk/maya-usd/pull/618. I'm closing the issue but please feel free to reopen if you find that something is still missing.
