### ISSUE TITLE
Errors building the refactoring_sandbox against USD 19.05

### ISSUE THREAD

**Issue by eldiren** [Autodesk/maya-usd#61]
Is USD 19.05 still the current version to build aginst the refactoring sandbox? I get errors related to include\pxr\imaging\hdx\pickTask.h missing and a number of HDRenderdelgate errors, but 19.05 doesn't even have pickTask.h in it's repo, that's 19.07 thing. I've followed advice from this issue with no luck: https://github.com/Autodesk/maya-usd/issues/1. Compiling against 19.07 yields me these errors:
C:\dev\maya-usd\lib\render\pxrUsdMayaGL\batchRenderer.cpp(1015): error C2065: 'HdRenderTagTokens': undeclared identifier [C:\maya_usd\build\Release\lib\mayaUsd.vcxproj]
C:\dev\maya-usd\lib\render\pxrUsdMayaGL\hdRenderer.cpp(184): error C2660: 'pxrInternal_v0_19__pxrReserved__::UsdImagingGLEngine::SetCameraState': function does not take 2 arguments [C:\maya_usd\build\Release\lib\mayaUsd.vcxproj]
C:\dev\maya-usd\lib\render\pxrUsdMayaGL\hdRenderer.cpp(185): error C2039: 'SetRenderViewport': is not a member of 'pxrInternal_v0_19__pxrReserved__::UsdImagingGLEngine' [C:\maya_usd\build\Release\lib\mayaUsd.vcxproj]

Which are quite a few less the 19.05 but still no success.

**Comment by BigRoy** [comment]
The specific versions to compile against are stated in the [`DEVELOPER.md`](https://github.com/Autodesk/maya-usd/blob/refactoring_sandbox/doc/DEVELOPER.md#branch-versions). Note that it states a specific commit of the repositories and not solely the version, so make sure you check out that commit and build it.

**Comment by eldiren** [comment]
Ok I'm down to two linker errors now. 
 "C:\maya_usd\build\Release\plugin\al\lib\AL_USDMaya\_AL_USDMaya.vcxproj" (default target) (19) ->
       (Link target) ->
         wrapTranslatorContext.obj : error LNK2005: "class AL::usdmaya::nodes::ProxyShape const volatile * __cdecl boost::get_pointer<class AL::usdmaya::nodes::ProxyShape const volatile >(class AL::usdmaya::nodes::ProxyShape const volatile *)" (??$get_pointer@$$CDVProxyShape@nodes@usdmaya@AL@@@boost@@YAPEDVProxyShape@nodes@usdmaya@AL@@PEDV1234@@Z) already defined in wrapProxyShape.obj [C:\maya_usd\build\Release\plugin\al\lib\AL_USDMaya\_AL_USDMaya.vcxproj]
         C:\maya_usd\build\Release\plugin\al\lib\AL_USDMaya\Release\_AL_USDMaya.pyd : fatal error LNK1169: one or more multiply defined symbols found [C:\maya_usd\build\Release\plugin\al\lib\AL_USDMaya\_AL_USDMaya.vcxproj]

**Comment by BigRoy** [comment]
Perfect! I believe the fix for the first one is described here: https://github.com/Autodesk/maya-usd/issues/50#issuecomment-540115672

It might also resolve the second but am not sure. ;) (on my phone on vacation so can't take a thorough look)

**Comment by eldiren** [comment]
Yeah issue https://github.com/Autodesk/maya-usd/issues/50#issuecomment-540115672 fixed it. I completely removed the line like he did. In summary it was an issue of me not reading/not knowing about the https://github.com/Autodesk/maya-usd/blob/refactoring_sandbox/doc/DEVELOPER.md#branch-versions file, and combining the two fixed mentioned in previous issues. Thanks for the quick assistance.

**Comment by kxl-adsk** [comment]
FYI. Merged the fix https://github.com/Autodesk/maya-usd/pull/58

**Comment by BigRoy** [comment]
@kxl-adsk be aware that this exact if statement didn't fix it on my end at the time as described [here](https://github.com/Autodesk/maya-usd/issues/50#issuecomment-540485879).
