### ISSUE TITLE
Nested Variants not switching in Maya-USD(pxrUsdReferenceAssembly)

### ISSUE THREAD

**Issue by suesauer** [Autodesk/maya-usd#611]
Hey, guys.

**Describe the bug**
I was testing our nested references and noticed that the Maya-USD(pxrUsdReferenceAssembly) Wasnt working as expected - see attached zip -. It switches once then gets "stuck" and unable to switch any more.

Not sure if this is a bug or a known issue.

**Steps to reproduce**
See video

**Expected behavior**
As seen in usdview

**Attachments**
[2020-06-30 09-43-11.zip](https://github.com/Autodesk/maya-usd/files/4850268/2020-06-30.09-43-11.zip)

**Specs (if applicable):**
 - OS & version Linux centos 7.7
 - Compiler & version gcc 6.3.1
 - Maya version Maya 2020.2
 - Maya USD commit SHA fcdc32bfdc4961cdeafa3730d196a2f3b09b007e
 - Pixar USD commit SHA 20.05

**Additional context**
PS there is also a weird offset in the y-axis(the sword is slight off the grid)

Sue

**Comment by santosd** [comment]
Hello @suesauer, would it be possible to attach a file that we could use to replicate this issue?

**Comment by suesauer** [comment]
Hey there, this seems to have been just a glitch. Works fine now
