### ISSUE TITLE
pthread_create exist failed

### ISSUE THREAD

**Issue by suekieza** [Autodesk/maya-usd#62]
Hey there,

I am trying to build USD Maya on linux centos 7 

my build path is :
python build.py --maya-location /usr/autodesk/maya2019 --pxrusd-location /home/suesauer/Documents/USD --devkit-location /home/suesauer/Documents/devkitBase  /home/suesauer/Documents/Workspace 

Using maya 2019
linux centos 7 
Latest Devkit 2019.2 update devkit
Latest PXR USD cloned down today 21 oct 2019
Cloned down usd maya today 21 oct 2019

**CmakeError log**
> 
Determining if the pthread_create exist failed with the following output:
Change Dir: /home/suesauer/Documents/Workspace/build/RelWithDebInfo/CMakeFiles/CMakeTmp

Run Build Command(s):/usr/bin/gmake cmTC_2f4d8/fast 
/usr/bin/gmake -f CMakeFiles/cmTC_2f4d8.dir/build.make CMakeFiles/cmTC_2f4d8.dir/build
gmake[1]: Entering directory `/home/suesauer/Documents/Workspace/build/RelWithDebInfo/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_2f4d8.dir/CheckSymbolExists.c.o
/usr/bin/cc    -o CMakeFiles/cmTC_2f4d8.dir/CheckSymbolExists.c.o   -c /home/suesauer/Documents/Workspace/build/RelWithDebInfo/CMakeFiles/CMakeTmp/CheckSymbolExists.c
Linking C executable cmTC_2f4d8
/usr/bin/cmake3 -E cmake_link_script CMakeFiles/cmTC_2f4d8.dir/link.txt --verbose=1
/usr/bin/cc      -rdynamic CMakeFiles/cmTC_2f4d8.dir/CheckSymbolExists.c.o  -o cmTC_2f4d8 
CMakeFiles/cmTC_2f4d8.dir/CheckSymbolExists.c.o: In function `main':
CheckSymbolExists.c:(.text+0x16): undefined reference to `pthread_create'
collect2: error: ld returned 1 exit status
gmake[1]: *** [cmTC_2f4d8] Error 1
gmake[1]: Leaving directory `/home/suesauer/Documents/Workspace/build/RelWithDebInfo/CMakeFiles/CMakeTmp'
gmake: *** [cmTC_2f4d8/fast] Error 2

File /home/suesauer/Documents/Workspace/build/RelWithDebInfo/CMakeFiles/CMakeTmp/CheckSymbolExists.c:
/* */
#include <pthread.h>

int main(int argc, char** argv)
{
  (void)argv;
#ifndef pthread_create
  return ((int*)(&pthread_create))[argc];
#else
  (void)argc;
  return 0;
#endif
}

Determining if the function pthread_create exists in the pthreads failed with the following output:
Change Dir: /home/suesauer/Documents/Workspace/build/RelWithDebInfo/CMakeFiles/CMakeTmp

Run Build Command(s):/usr/bin/gmake cmTC_a803d/fast 
/usr/bin/gmake -f CMakeFiles/cmTC_a803d.dir/build.make CMakeFiles/cmTC_a803d.dir/build
gmake[1]: Entering directory `/home/suesauer/Documents/Workspace/build/RelWithDebInfo/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_a803d.dir/CheckFunctionExists.c.o
/usr/bin/cc   -DCHECK_FUNCTION_EXISTS=pthread_create   -o CMakeFiles/cmTC_a803d.dir/CheckFunctionExists.c.o   -c /usr/share/cmake3/Modules/CheckFunctionExists.c
Linking C executable cmTC_a803d
/usr/bin/cmake3 -E cmake_link_script CMakeFiles/cmTC_a803d.dir/link.txt --verbose=1
/usr/bin/cc  -DCHECK_FUNCTION_EXISTS=pthread_create    -rdynamic CMakeFiles/cmTC_a803d.dir/CheckFunctionExists.c.o  -o cmTC_a803d -lpthreads 
/usr/bin/ld: cannot find -lpthreads
collect2: error: ld returned 1 exit status
gmake[1]: *** [cmTC_a803d] Error 1
gmake[1]: Leaving directory `/home/suesauer/Documents/Workspace/build/RelWithDebInfo/CMakeFiles/CMakeTmp'
gmake: *** [cmTC_a803d/fast] Error 2
> 

Am I missing something?

Thanks Sue

**Comment by suekieza** [comment]
Hey all, 

So solved the above issue by installing with the boost flags in my USD Pixar build.

USD Pixar build script run:
python /home/suesauer/Documents/USDPXR/USD/build_scripts/build_usd.py /home/suesauer/Documents/USD --build-args boost,"--with-date_time --with-thread --with-system --with-filesystem"

Maya_USD build script run:

python build.py --maya-location /usr/autodesk/maya2019 --pxrusd-location /home/suesauer/Documents/USD --devkit-location /home/suesauer/Documents/devkitBase  /home/suesauer/Documents/Workspace

Now I am stuck on AL_USDMayaUtils. It gives about the same error but its in a completely different place in the build.

/home/suesauer/Documents/maya-usd/plugin/al/usdmayautils/AL/usdmaya/utils/DgNodeHelper.cpp:6057:13: warning: enumeration value ‘kFrame4d’ not handled in switch [-Wswitch]
/home/suesauer/Documents/maya-usd/plugin/al/usdmayautils/AL/usdmaya/utils/DgNodeHelper.cpp:6057:13: warning: enumeration value ‘kColor3h’ not handled in switch [-Wswitch]
/home/suesauer/Documents/maya-usd/plugin/al/usdmayautils/AL/usdmaya/utils/DgNodeHelper.cpp:6057:13: warning: enumeration value ‘kColor3f’ not handled in switch [-Wswitch]
/home/suesauer/Documents/maya-usd/plugin/al/usdmayautils/AL/usdmaya/utils/DgNodeHelper.cpp:6057:13: warning: enumeration value ‘kColor3d’ not handled in switch [-Wswitch]
/home/suesauer/Documents/maya-usd/plugin/al/usdmayautils/AL/usdmaya/utils/DgNodeHelper.cpp:6057:13: warning: enumeration value ‘kUnknown’ not handled in switch [-Wswitch]
gmake[2]: *** [plugin/pxr/maya/lib/usdMaya/CMakeFiles/usdMaya.dir/importCommand.cpp.o] Error 1
gmake[2]: *** [plugin/pxr/maya/lib/usdMaya/CMakeFiles/usdMaya.dir/exportTranslator.cpp.o] Error 1
[ 43%] Linking CXX executable testMayaSchemas
[ 43%] Built target testMayaSchemas
[ 43%] Linking CXX shared library _AL_USDMayaSchemas.so
[ 43%] Built target _AL_USDMayaSchemas
gmake[1]: *** [plugin/pxr/maya/lib/usdMaya/CMakeFiles/usdMaya.dir/all] Error 2
gmake[1]: *** Waiting for unfinished jobs....
[ 43%] Linking CXX shared library libAL_USDMayaUtils.so
[ 43%] Built target AL_USDMayaUtils
gmake: *** [all] Error 2

Traceback (most recent call last):
  File "build.py", line 482, in <module>
    InstallMayaUSD(context, context.buildArgs, context.stagesArgs)
  File "build.py", line 319, in InstallMayaUSD
    RunCMake(context, extraArgs, stagesArgs)
  File "build.py", line 293, in RunCMake
    multiproc=FormatMultiProcs(context.numJobs, generator)))
  File "build.py", line 189, in Run
    .format(cmd=cmd, log=os.path.abspath(context.logFileLocation)))
RuntimeError: Failed to run 'cmake --build . --config RelWithDebInfo --target install -- -j64'
See /home/suesauer/Documents/Workspace/build/RelWithDebInfo/build_log.txt for more details.
 

See new attached logs

[build_log.txt](https://github.com/Autodesk/maya-usd/files/3755965/build_log.txt)
[CMakeError.log](https://github.com/Autodesk/maya-usd/files/3755966/CMakeError.log)
[CMakeOutput.log](https://github.com/Autodesk/maya-usd/files/3755967/CMakeOutput.log)

Thanks Sue

**Comment by HamedSabri-adsk** [comment]
Hi @suekieza , from your log I see that you are using an older version of GCC:

gcc version 4.8.5 20150623 (Red Hat 4.8.5-39) (GCC) 

Try updating to a newer version ( e.g gcc 6.3.1 )

hope this helps.

**Comment by suekieza** [comment]
Hi guy's so installed gcc 6.3.1 , now I'm stuck again. Was on 43% now I'm on 44% of the build :D No Idea what could be wrong this time.
[build_log.txt](https://github.com/Autodesk/maya-usd/files/3760877/build_log.txt)
[CMakeError.log](https://github.com/Autodesk/maya-usd/files/3760880/CMakeError.log)

**Comment by suekieza** [comment]
Success!! Added the PATH, and PYTHONPATH to my .bashrc

![Uploading Screenshot from 2019-10-23 11-33-17.png…]()

**Comment by suekieza** [comment]
Hey there,
How do I load the plugin correctly(add to the .env), and how do I know its working as expected?

Thanks for all the help so far

**Comment by HamedSabri-adsk** [comment]
> Success!! Added the PATH, and PYTHONPATH to my .bashrc

Hi @suekieza you really don't need to set PATH and PYTHONPATH in order to build the project. These environment variables are automatically set in `cmake/usd.cmake`

master branch:

https://github.com/Autodesk/maya-usd/blob/876e619c3695807bcd627afe9e8be2e228835172/CMakeLists.txt#L45

refactoring_sandbox:

https://github.com/Autodesk/maya-usd/blob/d0bb624e3aba2906a9fe4a09d4972324b237a3e0/CMakeLists.txt#L75

**Comment by suekieza** [comment]
Hmmmm. See images below. If I don't set them, they simply are not there when i echo them in the terminal? Am I supposed to update the cmake with the correct paths and only then build USD Pixar?
![Screenshot from 2019-10-24 12-30-21](https://user-images.githubusercontent.com/53234220/67477540-93487680-f65a-11e9-8b9a-728874c0378e.png)
![Screenshot from 2019-10-24 12-31-31](https://user-images.githubusercontent.com/53234220/67477541-93487680-f65a-11e9-84b7-9aa7b87288d0.png)

Thanks
