### ISSUE TITLE
[MAYA-105317] Crash while using PR116

### ISSUE THREAD

**Issue by devGitHub48** [Autodesk/maya-usd#635]
**Describe the bug**
After using the USD Layer Editor, I tried to do a File new and it crashes

**Steps to reproduce**
Did the quick tutorial  (http://help-beta.autodesk.com/view/MAYAUL/2021/ENU/?guid=GUID-BD0B0870-728D-41DE-B255-C943AE90165D)
Then do a new scene
Load the USD plugins
Create an empty usd stage
Create another anonymous layer
Save both layers
select first layer
Add an XForm with the right click menu in the outliner
Add a cube under the xform
Save the first layer
Add a cone
Move it on top of the cube
Save the first layer (using Save Edits in the layer Editor)
Save the maya file
Create a new scene
Crash

**Expected behavior**
No crash :D

**Specs (if applicable):**
 - OS & version [Windows 10]
 - Maya version PR116
 - Maya USD commit SHA [e.g. dev at caa921c1] the one from PR116
 - Pixar USD commit SHA [e.g. dev at b85ddac2] the one from PR116

**Additional context**
mtoa was started

**Comment by devGitHub48** [comment]
There is a case : CaseNo:16724504.] 
And a CER : CER_222829040

It seems related to this issue :  MAYA-105317 "Crash on File > New after using Mute in Layer Editor"

**Comment by devGitHub48** [comment]
New crash, same repro:

`PR116
New scene
Having the USD scene Layor open
Adding a new layer
New scene
Crash`

New CER : CER_222893860

**Comment by santosd** [comment]
Hi @devGitHub48, This was something I ran into as well and had logged it internally as MAYA-105317. I have linked the issues together. I will report back once the internal issue has been fixed and see if you can test again.

**Comment by devGitHub48** [comment]
Thanks a lot.
I will continue filling the CER report in case there are new  way of crashing.

**Comment by santosd** [comment]
This has been fixed internally and the fix should be available in the next PR. I will go ahead and close this issue out.
