### ISSUE TITLE
Remove USD_VERSION_NUMBER and replace with PXR_VERSION

### ISSUE THREAD

**Issue by marsupial** [Autodesk/maya-usd#645]
**Is your feature request related to a problem? Please describe.**
The build system introduces a **USD_VERSION_NUMBER** when **PXR_VERSION** already exists since at least 19.11.
It just makes it more complicated and harder to read.

**Describe the solution you'd like**
Replace usage of **USD_VERSION_NUMBER** with **PXR_VERSION** and remove the CMake generation of this constant.

**Comment by kxl-adsk** [comment]
@marsupial When we first introduced `USD_VERSION_NUMBER`, `PXR_VERSION` was not available on all supported USD versions, i.e. we had to support 19.01 and up. With 19.11 being now a minimal supported version, we can rely on the pxr header file and `PXR_VERSION ` for code conditional compilation.
We still need something custom for CMake - this is where we will need to keep `USD_VERSION_NUMBER`

**Comment by mattyjams** [comment]
This should be addressed by #1181.
