### ISSUE TITLE
Problem building last version of maya-usd.

### ISSUE THREAD

**Issue by ChokmahBinah** [Autodesk/maya-usd#651]
**Describe the issue**
Hello maya-usd team.
Since few version from dev branch, I don't manage to build maya-usd.
I tried with --redirect-outstream-file=false argument on build.py and git this error message in the buikd process :

![maya-usd_build_bug](https://user-images.githubusercontent.com/33164632/87231613-e87b1280-c3b8-11ea-9eb4-526f553c3da1.jpg)

I hope i could have some help about this.
Thank you in advance :)

Florian.

**Build log**
[build_log.txt](https://github.com/Autodesk/maya-usd/files/4907475/build_log.txt)

**Specs:**
 - Windows 10
 - Compiler & version MSVC 19.16.27035.0
 - Maya 2020
 - Maya USD commit dev at 9e395a65d
 - Pixar USD commit dev at e06f9996d

**Additional context**

**Comment by seando-adsk** [comment]
I think you've gone too far in the USD dev branch. Internally we are at [7c888ac](https://github.com/PixarAnimationStudios/USD/commit/7c888acb362f48b089a5e13149a7e3f14167b0c3) which is from Jun 15. The commit you mention e06f9996d is from Jul 3. There is an open PR #617 which we'll merge in once we update to a new USD. Ideally you should use the commit mentioned in [build.md](https://github.com/Autodesk/maya-usd/blob/dev/doc/build.md)

**Comment by ChokmahBinah** [comment]
Hello @seando-adsk ,

Thanks a lot for your answer !
Reading other threads it seems I am part of those who didn't read build.md enough ! lol
I'll take care in the futrue.

Thank you again :)

**Comment by seando-adsk** [comment]
No problem. If you are able to build again can you close this issue.

**Comment by ChokmahBinah** [comment]
I'll do that as soon as possible :)

Le jeu. 16 juil. 2020 à 22:40, Sean Donnelly <notifications@github.com> a
écrit :

**Comment by ChokmahBinah** [comment]
Hello @seando-adsk ,

I stepped back to 7c888ac of USD dev branch ... And managed to build maya-usd ! ;)

Thank you for your help. I can close this issue then.

(ps : I'll look to #617 posted by @mattyjams to try building with USD 20.08 rc3 :) )
