### ISSUE TITLE
Proxyshape.cpp and Engine.cpp failed

### ISSUE THREAD

**Issue by xZAKHAMx** [Autodesk/maya-usd#654]
**Describe the issue**
I'm Trying to build maya-usd and it fails while building Engine or ProxyShape

**Build log**
[build_log.txt](https://github.com/Autodesk/maya-usd/files/4911698/build_log.txt)

**Specs:**
 - OS & version [Windows 10 Pro]
 - Compiler & version [e.g. gcc 6.3.1]
 - Maya version [Maya 2020.2]
 - Maya USD commit SHA [e.g. dev at 00d651a]
 - Pixar USD commit SHA [e.g. dev at ebac0a8]

**Comment by suesauer** [comment]
This is happening for me as well on Linux centos 7....

**Comment by kxl-adsk** [comment]
@xZAKHAMx Based on the description, more precisely commits SHA provided in specs - looks like you are trying to use an older version of Maya USD with unsupported at that time USD 20.05. It's always good to consult build.md file for supported versions of USD - https://github.com/Autodesk/maya-usd/blob/00d651a8af3af752160531a0841579d1bc0f41ea/doc/build.md#2-download-and-build-pixar-usd

If you want to adopt USD 20.05, please grab changes from dev branch.

@suesauer I believe you may be running into similar problem...but maybe you want to adopt USD 20.08? Keep in mind we have one open PR which is required to build against 20.08 release candidate (see #617 )

**Comment by suesauer** [comment]
Yup I'm building 20.08 to get texture speed improvements

**Comment by kxl-adsk** [comment]
@suesauer Then make sure to check PR #617

**Comment by kxl-adsk** [comment]
@suesauer Our `dev` branch should now build without any problems with USD 20.08.

@xZAKHAMx is there something left in this issue to resolve or we can close it now?

**Comment by suesauer** [comment]
can be closed thanks
