### ISSUE TITLE
 has no member named ‘SetTaskContextData’, :HdEngine>’ has no member named ‘Execute`

### ISSUE THREAD

**Issue by suesauer** [Autodesk/maya-usd#662]
**Describe the issue**
Failed to build usd maya

**Build log**
[build_log.txt](https://github.com/Autodesk/maya-usd/files/4924271/build_log.txt)

**Specs:**
 - OS & version Centos7
 - Compiler & version  gcc 6.3.1
 - Maya version Maya 2020.2
 - Maya USD commit SHA dev at 461668a75deeb46d36cf55566b119010ff491a7d
 - Pixar USD commit SHA master 44d66c531ef3bfddf88df6e54fdeaf4ac3aba086

**Additional context**
My previous working build was:
Pixar USD ebac0a8b6703f4fa1c27115f1f013bb9819662f4
Maya USD fcdc32bfdc4961cdeafa3730d196a2f3b09b007e

Thanks

**Comment by suesauer** [comment]
Also:
Cloning into 'maya-usd'...
remote: Enumerating objects: 207, done.
remote: Counting objects: 100% (207/207), done.
remote: Compressing objects: 100% (162/162), done.
remote: Total 101899 (delta 85), reused 102 (delta 45), pack-reused 101692
Receiving objects: 100% (101899/101899), 61.84 MiB | 14.06 MiB/s, done.
Resolving deltas: 100% (74778/74778), done.
Note: checking out 'fcdc32bfdc4961cdeafa3730d196a2f3b09b007e'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b new_branch_name

HEAD is now at fcdc32b... Merge pull request #557 from Autodesk/smithw/extend-timeout

    Building with settings:
      Source directory          /home/sue.sauer/Documents/maya-usd
      Workspace directory       /home/sue.sauer/Documents/WorkspaceRefractor
      Build directory           /home/sue.sauer/Documents/WorkspaceRefractor/build/RelWithDebInfo
      Install directory         /home/sue.sauer/Documents/WorkspaceRefractor/install/RelWithDebInfo
      Variant                   RelWithDebInfo
      Python Debug              Off
      CMake generator           Default
      Build Log                 /home/sue.sauer/Documents/WorkspaceRefractor/build/RelWithDebInfo/build_log.txt
      Stages arguments          ['clean', 'configure', 'build', 'install']
Traceback (most recent call last):
  File "build.py", line 600, in <module>
    BuildAndInstall(context, context.buildArgs, context.stagesArgs)
  File "build.py", line 369, in BuildAndInstall
    RunCMake(context, extraArgs, stagesArgs)
  File "build.py", line 281, in RunCMake
    multiproc=FormatMultiProcs(context.numJobs, generator)))
  File "build.py", line 144, in Run
    logfile.write(l)
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2018' in position 108: ordinal not in range(128)

**Comment by suesauer** [comment]
@kxl-adsk 3 of us or having this same issue on windows and on Linux

**Comment by kxl-adsk** [comment]
Commented in #654 . If this is a duplicate (as it appears), please close it.
