### ISSUE TITLE
Compile issue 

### ISSUE THREAD

**Issue by cfmoore007** [Autodesk/maya-usd#674]
**Describe the issue**
I tried compiling this, against f937f9c ( + this PR ) with Maya Beta PR116, and received this error :

F:\Repos\maya-usd\lib\mayaUsd\ufe\UsdContextOps.cpp(363): error C2653: 'UsdUndoAddNewPrimCommand': is not a class or namespace name [F:\APPLICATIONS\MayaUSD\f937f9c-selection_highlight\build\lib\mayaUsd\mayaUsd.vcxproj] F:\Repos\maya-usd\lib\mayaUsd\ufe\UsdContextOps.cpp(363): error C2660: 'MayaUsd_v0::ufe::UsdContextOps::create': function does not take 3 arguments [F:\APPLICATIONS\MayaUSD\f937f9c-selection_highlight\build\lib\mayaUsd\mayaUsd.vcxproj] F:\Repos\maya-usd\lib\mayaUsd\ufe\UsdContextOps.cpp(202): note: see declaration of 'MayaUsd_v0::ufe::UsdContextOps::create' utilFileSystem.cpp

Full build log :
build_log.txt

Last successful compile : 256d690
Breaks here : 324bff0

**Build log**
[build_log.txt](https://github.com/Autodesk/maya-usd/files/4953668/build_log.txt)

**Specs:**
 - OS & version [e.g. Windows 10]
 - Compiler & version [ VS 2017 ]
 - Maya version [ Maya PR 116 ]
 - Maya USD commit SHA [e.g. dev at 324bff0]
 - Pixar USD commit SHA [e.g. dev at e7ff8e8]

**Additional context**
Was trying to compile, here : https://github.com/Autodesk/maya-usd/pull/671 and noticed this issue.

**Comment by kxl-adsk** [comment]
Thank you for reporting @cfmoore007. I'm wondering if it could be related to #593? @fowlertADSK can you comment?

FWIW. Upcoming PR117 will resolve this issue.

**Comment by fowlertADSK** [comment]
My change alone should not have caused any problems, it correctly built against Maya's PR116 and 117.  So I have not seen any build issues, but if I had to guess then I think something might have happened when Hamed refactored my new command class.

In my change I took the AddPrim code from UsdContextOps.cpp (where it could not be seen from outside the class) and moved it into its own file (that's UsdUndoAddNewPrimCommand.h/.cpp), but I left the original code in UsdContextOps.cpp and included some ifdef's to use one or the other based on what version of Maya we were compiling against.  Hamed correctly noticed that we didn't need to keep around the old copy of the code, not matter what version of Maya, and made a change to remove it from UsdContextOps.cpp entirely (so not ifdef's).  Wondering if it's some combination of my original change, Hameds follow up refactoring, and the branches that Christopher is trying to put together to test.

**Comment by HamedSabri-adsk** [comment]
@cfmoore007 I believe your MayaUSD SHA (324bff0 ) that you have picked is not good. That particular commit won't compile. Please pick below commit:

Commit 8daa8f20
MAYA-104858: fix regression after UsdUndoAddNewPrimCommand was introduced.

**Comment by fowlertADSK** [comment]
@cfmoore007 We realized that there is a problem with UsdContextOps.cpp.  There is a conditional #include of UsdUndoAddNewPrimCommand.h up at the top of that .cpp file which should have been removed.  We'll push a fix soon, but if you are still hitting issues then you can make that change easily yourself.  Just remove the #ifdef around the include, that file works with any version and doesn't require the check.

**Comment by cfmoore007** [comment]
For what it's worth, I compiled against PR117 and had the same issue.  When you put in the fix for this, that is the Maya Beta version I will compile against.

Thanks, @fowlertADSK .

**Comment by cfmoore007** [comment]
I just compiled PR117 against dev @0ac0ce5 and it worked.  Thanks!
