### ISSUE TITLE
support of MASH instancer in Hydra

### ISSUE THREAD

**Issue by IM-001** [Autodesk/maya-usd#684]
**Is your feature request related to a problem? Please describe.**
Hi!  I don't see my mash instancer in the Hydra viewport of the 0.2.0 plugin

**Describe the solution you'd like**
would love to see them

**Describe alternatives you've considered**
trying to test with storm but not sure atm how to find it, will continue my search

Thanks!

**Comment by IM-001** [comment]
Any comment?...  Is this on your radar at some point?..  Did you read the post?

**Comment by santosg87** [comment]
Hi @IM-001 , I am testing this one internally, and my MASH instancer does seem to be visible when using MtoH:
![mtohMASH_instancer](https://user-images.githubusercontent.com/3026529/106786208-494f8e00-661c-11eb-86ee-77d530c0179d.gif)


what version of maya are you in? do you still see the issue with the latest plugin version?

**Comment by wtelford** [comment]
@IM-001 I've closed this issue as we can not reproduce it. Feel free to re-open and provide feedback. 
Cheers,
Will
