### ISSUE TITLE
refactoring_sandbox : VP2 Delegate : Duplicating ProxyShape Crash

### ISSUE THREAD

**Issue by cfmoore007** [Autodesk/maya-usd#69]
**Issue :**

Maya crashes when duplicating a proxyShape node when the VP2_RENDER_DELEGATE_PROXY is enabled.

**Steps to re-produce :**

1) open maya ( UFE does not need to be set, just the envar for VP2_RENDER_DELEGATE_PROXY )

**2) import an AL proxyShape :**

```
import maya.cmds as cmds
cmds.loadPlugin ("AL_USDMayaPlugin")

# import proxyShape
cmds.AL_usdmaya_ProxyShapeImport(file="3_Spheres.usda")

# select and duplicate
cmds.select("AL_usdmaya_Proxy",r=True)
cmds.duplicate()
```

( USD Debug Information )
```
ProxyShape::ProxyShape
ProxyShape::postConstructor
ProxyShapeSelection::onSelectionChanged 0
ProxyShapeSelection::onSelectionChanged 0
ProxyShape::getUsdStage
ProxyShape::compute AL_usdmaya_Proxy1Shape.outStageData
```

**3) Crash**

Stack Trace :
```
------------------------ 'maya.bin' is dying ------------------------
maya.bin crashed. FATAL ERROR: Used null prim
in Usd_IssueFatalPrimAccessError at line 243 of /pxr/usd/lib/usd/primData.cpp

The stack can be found in /usr/tmp/st_maya.bin.32238
done.
------------------------------------------------------------------

```

**Testing Environment :**
- (Linux) Maya 2019.2 
- refactoring_sandbox ( d0bb624 ) and Pixar USD dev ( b85ddac2 )

- ( Windows ) beta ( latest PR )
- refactoring_sandbox ( w/ PR#69 ) and Pixar USD-rc3 

( I can't seem to upload any files here, but the test was with a sphere usd file )

Side note : the crash did not occur w/ the Autodesk proxy shape

**Comment by cfmoore007** [comment]
[3_Spheres.zip](https://github.com/Autodesk/maya-usd/files/3773888/3_Spheres.zip)
Added file.

**Comment by fowlertADSK** [comment]
Thanks for reporting this.  I am able to reproduce it and we're investigating now.

**Comment by fowlertADSK** [comment]
Internally we're tracking this as MAYA-101680.

**Comment by cfmoore007** [comment]
The crash seems addressed in PR#112.  However, it still does not show the duplicate proxyShape's stage. Will check existing issues, and log that separately ...

**Comment by ppt-adsk** [comment]
I will look for your ticket, because I actually have that fixed here internally...

**Comment by cfmoore007** [comment]
Actually, I cannot repro this outside of refactoring sandbox.
This crash appears resolved with PR#91.

**Comment by cfmoore007** [comment]
Tested PR#162 and it seems to resolve this issue.

**Comment by ppt-adsk** [comment]
Hi @cfmoore007 ,
https://github.com/Autodesk/maya-usd/pull/162
fixes the root cause of the problem (proxy shape data not copied on duplication), now merged to dev branch, with unit test.  You may want to confirm your duplication workflows don't show any regression.  Cheers.
