### ISSUE TITLE
How do I change variants?

### ISSUE THREAD

**Issue by suesauer** [Autodesk/maya-usd#692]
**Describe the bug**
Is there a way to change variants with the new UFE/stage import?

What is actually available with the UFE? Is there a menu other then the one under the create drop-down menu? Thanks Sue

**Comment by ppt-adsk** [comment]
Hey @suesauer, thanks for writing, try right-clicking on an Outliner USD item, you should see variant switching there.  Don't hesitate to write back if you have more questions or comments.  Cheers.

**Comment by suesauer** [comment]
Don't see anything like that:

![barrel](https://user-images.githubusercontent.com/58251706/89053491-9134e600-d357-11ea-9c03-3a40698e89c8.png)

**Comment by ppt-adsk** [comment]
The proxy shape node isn't a USD node, it's pretty much the Maya container node for USD objects in a single stage, so it doesn't have variants itself.  Expand out the proxy shape node in the Outliner, go down to a USD prim that has variant(s), and try the right click there.

**Comment by suesauer** [comment]
ok so that doesn't work either.

So attaching video:
1. cant see variants no matter where we look.
2. lights don't seem to work on the usd maya stage asset. The usdpixar ref asset is also broken

[2020-07-31 18-10-24.zip](https://github.com/Autodesk/maya-usd/files/5007931/2020-07-31.18-10-24.zip)

Thanks Sue

**Comment by suesauer** [comment]
checking

**Comment by suesauer** [comment]
Nope no plugin called ufeSupport.py at all. searched for ufe found nothing

**Comment by suesauer** [comment]
`#!/bin/bash -e

#Please enable in terminal --- scl enable devtoolset-6 bash --- before running this bash script.
if [ "$(gcc -dumpversion)" != "6.3.1" ]; then 
	echo "Please enable in terminal --- scl enable devtoolset-6 bash --- before running this bash script."
else
	#DIR_PATH
	SCRIPT_DIR=$(readlink -f "$(dirname "$0")")

	####USD MAYA
	####DEV CLONE
	cd $SCRIPT_DIR/USDMAYA
	git clone -b dev https://github.com/Autodesk/maya-usd.git
	cd $SCRIPT_DIR/USDMAYA/maya-usd
	git checkout 5581cb36608d6176c5e6254a6d8eb3847c1f179c  #7/29/2020 built successfully against 20.08
	#git checkout 7e140670c46c333f46c1c6c81d0acbe2948b6b33 #7/15/2020 built successfully against 20.05
	#git checkout fcdc32bfdc4961cdeafa3730d196a2f3b09b007e #6/3/2020 built successfully against 20.05
	#git checkout 00d651a8af3af752160531a0841579d1bc0f41ea #v.0.1.0
	#git checkout 20aa4c0 #v.0.0.2
	#git checkout -b master origin/master
	###BUILD
	python build.py --maya-location /usr/autodesk/maya2020 --pxrusd-location $SCRIPT_DIR/USD --devkit-location $SCRIPT_DIR/USDMAYA/maya_devkit/devkitBase  $SCRIPT_DIR/USDMAYA/WorkspaceRefractor`

my build bash script

**Comment by ppt-adsk** [comment]
@suesauer sorry about that...  I always forget to check the Maya version number first.  You're on Maya 2020, which supports our Universal Front End (UFE) v1 features only.  You'll need a cut of the Maya next version Preview Release to get at UFE v2 supported features, including Outliner menus.  Hope that still works out for you.  Cheers.

**Comment by suesauer** [comment]
You'll need a cut of the Maya next version Preview Release? What? where do I get that?

**Comment by ppt-adsk** [comment]
Hey @suesauer if you're interested in our beta program you can sign up for an account on
https://feedback.autodesk.com/welcome/
then apply for the Maya beta program from your account.  We'll get your request approved once it comes in.

**Comment by dolivares-spinvfx** [comment]
Maybe autodesk could make the ufeSupport plugin available in the devkit?  It's needed for the unit tests as well.

**Comment by suesauer** [comment]
Ok I made a feedback account, now what do i do? I Dont see Maya beta in my feedback options list.

**Comment by harveyr-gh** [comment]
Hi @suesauer, you'll get an invite to the Maya Beta shortly.

Cheers,
Ryan

**Comment by suesauer** [comment]
sent you email, thanks

**Comment by suesauer** [comment]
Hey guys, thanks for all the help. Have maya beta up and running now. \:D/
