### ISSUE TITLE
Standard Surface support for USD export

### ISSUE THREAD

**Issue by bentoogood** [Autodesk/maya-usd#693]
Is 'Standard Surface' material export currently intended to work, or is it on the road map for support? My understanding is that Autodesk intend to retire the legacy shaders (lambert, blinn, etc ) in favour of the built in (as of 2020) Standard Surface.

My testing suggests that there is currently no support (even for displayColor inheritance from standard surface baseColor). Is that correct or have I encountered a bug? (simple repo scene attached. Export with 'Material Colors' enabled - lambert colour is passed through as displayColor, standard surface colour is ignored and displayColor defaults to 1,1,1 )

[standardSurfaceDisplayColor.zip](https://github.com/Autodesk/maya-usd/files/5010280/standardSurfaceDisplayColor.zip)

If it's still "to do", it would be great to have support for baseColor->displayColor as a first step as we are aiming to transition to the standard surface for basic viewport shading. Parity with lambert would be a big help.

thanks

**Comment by JGamache-autodesk** [comment]
We intend to fully support standard surface. 
The export of standard surface to USD Preview Surface was added in pull request 574.
The import from USD Preview Surface is currently under review in pull request 707. We also added, in the same pull, export and import of standard surface to/from display colors.
