### ISSUE TITLE
refactoring_sandbox : VP2 Delegate : Hiding ProxyShape Does Not Work

### ISSUE THREAD

**Issue by cfmoore007** [Autodesk/maya-usd#70]
**Issue :**

When VP2_RENDER_DELEGATE_PROXY is enabled, setting the visibility ( aka Hiding ) a proxyShape does not work.

The visibility state is not updated in the viewport, nor are any edits written to the session layer ( though I guess I would expect this, as we're not editing a prim's visibility state directly, rather the shape that represents the USD stage ).

Orbiting in the viewport, nor the 'ogs -reset' command seem to have any effect.

**Steps to re-produce :**

1) load the refactoring_sandbox
2) load proxyShape ( I used a simple usd file with 3 spheres )
3) select proxyShape and hide it
4) notice, no updates in the viewport

**Testing Environment :**
(Linux) Maya 2019.2
refactoring_sandbox ( d0bb624 ) and Pixar USD dev ( b85ddac )

( Windows ) beta ( latest PR )
refactoring_sandbox ( w/ PR#69 ) and Pixar USD-rc3

( having issues uploading example file, sorry! )

**Comment by cfmoore007** [comment]
[3_Spheres.zip](https://github.com/Autodesk/maya-usd/files/3773890/3_Spheres.zip)
added file

**Comment by HdC-adsk** [comment]
Tracked as MAYA-101852 internally.

**Comment by HdC-adsk** [comment]
The issue has been fixed by https://github.com/Autodesk/maya-usd/pull/112.

**Comment by cfmoore007** [comment]
Confirmed.  Closing.
