### ISSUE TITLE
Maya Beta and UFE v2

### ISSUE THREAD

**Issue by wjwilson** [Autodesk/maya-usd#701]
Apologies, this isn't really an issue but I'm not certain where else to make this request. I have seen a number of issues that mention that UFE v2 is required to get the entire feature set for maya-usd, and that to get UFE v2 I'd need a preview cut of Maya. However, the Maya beta program doesn't currently appear to be open. Is there some way I can access either UFE v2 or the preview version of Maya?

Cheer,
Will

**Comment by harveyr-gh** [comment]
Hey @wjwilson , we can add you to the Maya beta. Please send your name/email address to me at ryan.harvey@autodesk.com and we'll go from there.

Thanks,
Ryan

**Comment by santosg87** [comment]
is it ok to close this, as it seems its being taken care of? :)
