### ISSUE TITLE
Error building MAYAUSD_LIBRARY on Centos8 with Maya 2020.2

### ISSUE THREAD

**Issue by ericgd** [Autodesk/maya-usd#711]
**Describe the issue**
A description of what the issue is.

I get a ninja: build stopped: subcommand failed. when building. It fails with gcc as well
I get a lot of warning which I do not know what causes the problem:

During generation, I get many: "Cannot generate a safe linker search path for target mayaUsd because there
     is a cycle in the constraint graph".

Then while building, I get: many:

warning: ‘void* memcpy(void*, const void*, size_t)’ copying an object of type ‘class pxrInternal_v0_20__pxrReserved__::GfVec3f’ with ‘private’ member ‘pxrInternal_v0_20__pxrReserved__::GfVec3f::_data’ from an array of ‘const float’; use assignment or copy-initialization instead [-Wclass-memaccess]
     memcpy((GfVec3f*)points.data(), pointsData, sizeof(float) * 3 * numVertices);

 and 

error: ‘Autodesk::Maya::OpenMaya20200000::MHWRender::MSelectionInfo::~MSelectionInfo()’ is private within this context
 class OPENMAYARENDER_EXPORT MDrawContext : public MFrameContext

and finally:
ninja: build stopped: subcommand failed.

I do not know exactly what causes the builder to fail. 
 

*Build log**
Please attach a build_log.txt
[mayausd_log.txt](https://github.com/Autodesk/maya-usd/files/5071117/mayausd_log.txt)

**Specs:**
 - OS & version     Linux Centos 8
 - Compiler & version      gcc 8.3.1    and  ninja 1.8.2 
 - Maya version   Maya 2020 service pack 2
 - Maya USD commit SHA (can't find the version, but did a git clone https://github.com/Autodesk/maya-usd.git on Aug 13, 2020 at 15:00)
 - Pixar USD commit SHA  release v20.08 2020-07-21

**Additional context**

**Comment by seando-adsk** [comment]
We don't support gcc8. Because maya-usd is a plugin to Maya it must be built using the same compiler as the version of Maya you are using. Please refer to the section "Tools and System Prerequisites" in the [build.md](https://github.com/Autodesk/maya-usd/blob/dev/doc/build.md). For Maya 2020 you need to use gcc 6.3.1. We build using CentOS7. I'm not sure if it will work on CentOS8.

**Comment by ericgd** [comment]
Thank you.
I wrongly understood gcc 6.3.1 was the minimum version. My bad.
I am still trying to get the deprecated gcc 6.3.1 on my Centos 8... No success so far.

**Comment by HamedSabri-adsk** [comment]
@ericgd 

You could get gcc 6.3.1 from devtoolset-6 which is now moved into the vault. Follow this steps to install it:

```
# download the packages, install may fail with "no public key found"
sudo yum-config-manager --add-repo=http://vault.centos.org/7.6.1810/sclo/x86_64/rh/

# to fix "no public key found"
cd /etc/pki/rpm-gpg
ls # confirm RPM-GPG-KEY-CentOS-SIG-SCLo exists
sudo rpm --import RPM-GPG-KEY-CentOS-SIG-SCLo
rpm -qa gpg* # confirm key with substring f2ee9d55 exists

# to install devtoolset-6
sudo yum install devtoolset-6

# disable the vault after successful install
sudo yum-config-manager --disable vault.centos.org_7.6.1810_sclo_x86_64_rh_

```

**Comment by ericgd** [comment]
Thank you @HamedSabri-adsk 

I don't get the key error, but this one instead:
---
Error: 
 Problem: package devtoolset-6-6.1-1.el7.x86_64 requires devtoolset-6-runtime, but none of the providers can be installed
  - conflicting requests
  - nothing provides policycoreutils-python needed by devtoolset-6-runtime-6.1-1.el7.x86_64
(try to add '--skip-broken' to skip uninstallable packages or '--nobest' to use not only best candidate packages
---
I just cannot find a way to get policycoreutils-python work in order to get devtoolset-6  (which I think it is now called policycoreutils-python-utils in Centos8).

**Comment by HamedSabri-adsk** [comment]
@ericgd  can you please try installing policycoreutils from the rpm if not already and see if it helps? 

https://rpmfind.net/linux/rpm2html/search.php?query=policycoreutils-python&submit=Search+
https://rpmfind.net/linux/centos/7.8.2003/os/x86_64/Packages/policycoreutils-python-2.5-34.el7.x86_64.rpm
