### ISSUE TITLE
Windows : Issue when compiling dev branch

### ISSUE THREAD

**Issue by ederjagreda** [Autodesk/maya-usd#719]
Hello everyone!!

I am having some issues when compiling latest code in dev branch.

I could compile usd 20.08 with no issues using:

`python build_usd.py  --build-args=boost,"--with-date_time --with-thread --with-system --with-filesystem"  "D:\DEVELOPMENT\Builder\USD_20.08_compile"`

but, when I try to compile usd_maya using:

`python build.py --maya-location "C:\Program Files\Autodesk\Maya2019" --pxrusd-location="D:\DEVELOPMENT\Builder\USD_20.08_compile" --devkit-location "D:\DEVELOPMENT\Builder\devkitBase" "D:\DEVELOPMENT\Builder\USD_MAYA_RESULT" --build-args="-DPXR_STRICT_BUILD_MODE=OFF"`

I get this error:

d:\development\builder\maya-usd\lib\mayausd\render\px_vp20\utils.h(72): error C2220: warning treated as error - no 'object' file generated [D:\DEVELOPMENT\Builder\USD_MAYA_RESULT\build\RelWithDebInfo\lib\mayaUsd\mayaUsd.vcxproj]

d:\development\builder\maya-usd\lib\mayausd\render\px_vp20\utils.h(72): warning C4800: 'unsigned int': forcing value to bool 'true' or 'false' (performance warning) [D:\DEVELOPMENT\Builder\USD_MAYA_RESULT\build\RelWithDebInfo\lib\mayaUsd\mayaUsd.vcxproj]

Also, looking at "..\build\RelWithDebInfo\CMakeFiles\CMakeError.log"

I see this error:

  CheckIncludeFile.c
D:\DEVELOPMENT\Builder\USD_MAYA_RESULT\build\RelWithDebInfo\CMakeFiles\CMakeTmp\CheckIncludeFile.c(1): fatal error C1083: Cannot open include file: 'pthread.h': No such file or directory [D:\DEVELOPMENT\Builder\USD_MAYA_RESULT\build\RelWithDebInfo\CMakeFiles\CMakeTmp\cmTC_a58b2.vcxproj]

**Build logs**
[build_log.txt](https://github.com/Autodesk/maya-usd/files/5087494/build_log.txt)
[CMakeError.log](https://github.com/Autodesk/maya-usd/files/5087495/CMakeError.log)

**Specs:**
 - OS & version [Windows 10 19041]
 - Compiler  [Visual Studio 14 2015 Win64]
 - Maya version [2019]
 - Maya USD commit SHA [d4d9a89]
 - Pixar USD commit SHA [71b4baa]

any help would be greatly appreciated!

**Comment by seando-adsk** [comment]
@ederjagreda Are you using "VS 2015 **update 3**"? As per the "Tools" listed in [build.md](https://github.com/Autodesk/maya-usd/blob/dev/doc/build.md).

The flag `PXR_STRICT_BUILD_MODE` only affects the Pixar plugin. There is a separate flag `BUILD_STRICT_MODE` used for the core maya-usd stuff.

**Comment by ederjagreda** [comment]
Thank you for the answer.
About VS  I am using Visual Studio Community 2015 version 14.0.25431.01 Update 3, 

and I got the idea of using  `args="-DPXR_STRICT_BUILD_MODE=OFF"` from  [https://github.com/Autodesk/maya-usd/issues/233#issuecomment-585459692](url)

**Comment by seando-adsk** [comment]
Using the strict flag(s) is/are fine. For your specific error you just need to also disable BUILD_STRICT_MODE.

**Comment by seando-adsk** [comment]
So after some more digging I think this is due to a bug in Visual Studio 2017, where the warning for that line is not being shown.
https://developercommunity.visualstudio.com/content/problem/78259/visual-studio-2017-no-longer-generates-a-c4800-war.html

Since you are using VS2015 you have the warning. Until the warning is fixed you can simply disable the strict mode using `-DBUILD_STRICT_MODE=OFF`

**Comment by ederjagreda** [comment]
Thank you for your time  @seando-adsk 

I just compiled maya-usd  with no issues following your advice

**Comment by ederjagreda** [comment]
Well, like I said I compiled maya-usd, but I get some errores when trying to load the plugins in maya:

![image](https://user-images.githubusercontent.com/48255703/90724244-d7f56c00-e283-11ea-82a1-4231b046c636.png)
the error I see is:
`// Error: file: C:/Program Files/Autodesk/Maya2019/scripts/others/pluginWin.mel line 289: initializePlugin function failed (AL_USDMayaTestPlugin) // `

![image](https://user-images.github
usercontent.com/48255703/90724417-24d94280-e284-11ea-826b-a0c540801e5e.png)
the error I see is:
`# Error: file: C:/Program Files/Autodesk/Maya2019/scripts/others/pluginWin.mel line 289: No module named UsdMaya
# Traceback (most recent call last):
#   File "<maya console>", line 1, in <module>
# ImportError: No module named UsdMaya # 
// Error: file: C:/Program Files/Autodesk/Maya2019/scripts/others/pluginWin.mel line 289: initializePlugin function failed (pxrUsd) // 
`

any help would be greatly appreciated!

**Comment by robthebloke** [comment]
You may either load the AL_USDmaya plug in, or the AL_USDMayaTest plug in, but not both! 

The one you've loaded is the one you want (AL_USDMaya). The other one is exactly the same, however it also contains a load of unit tests for the developers to run, which is useless for anyone other than a developer.

**Comment by ederjagreda** [comment]
thank you for the answer!!

so now, the only issue I have is not be able to load pxrUsd.mll plugin
