### ISSUE TITLE
Models with a parent xform flagged as instanceable = true wont import into maya

### ISSUE THREAD

**Issue by koen-v** [Autodesk/maya-usd#723]
When importing a usd containing an mesh with an xform as a parent, and that parent has the flag instanceable = true the model wont import.

This is using file->import->usd.

Jerry Gamache has an example fir to illustrate this behavior.

Thanks,
Koen

**Comment by santosd** [comment]
Hi @koen-v, thank you for bringing this to our attention. I think this may be the same as #340 we have that logged internally and will be working on it.

**Comment by santosd** [comment]
Going to be closing this out since it is a duplicate.
