### ISSUE TITLE
Can't load usd plugin in maya2020: undefined symbol

### ISSUE THREAD

**Issue by 1xinghuan** [Autodesk/maya-usd#724]
**Describe the bug**
When I try to load usdmaya plugin in maya, there will be error:
undefined symbol: _ZNK6Ufe_v14Path6stringB5cxx11Ev

**Steps to reproduce**
1. Compile and install usdmaya plugin
2. Load the plugin in maya

**Specs (if applicable):**
 - OS & version Linux
 - Compiler & version gcc6.5
 - Maya version maya2020.2
 - Maya USD commit SHA 0.2.0
 - Pixar USD commit SHA 20.02

**Comment by seando-adsk** [comment]
That missing symbol resolves to `Ufe_v1::Path::string[abi:cxx11]() const` which is a UFE method that has been around for a very long time (part of UFE v1). Can you check your build logs and look for UFE to see if your build found UFE or not.

**Comment by 1xinghuan** [comment]
![20200820170332](https://user-images.githubusercontent.com/33982538/90750328-39aaea00-e307-11ea-8adc-017d8681994e.jpg)
It found ufe. Maybe it's because I'm using g++6.5.
I will try g++6.3.

**Comment by 1xinghuan** [comment]
I add the '-D_GLIBCXX_USE_CXX11_ABI=0' flag to both usd and maya-usd build then it's ok.
