### ISSUE TITLE
refactoring_sandbox : UFE : Center Pivot Does Not Work

### ISSUE THREAD

**Issue by cfmoore007** [Autodesk/maya-usd#73]
**Issue :**

While you can modify the pivot of a prim and manipulate it in UFE, it seems the Maya command to center the pivot does not apply.

**Steps to re-produce :**

1) open maya with UFE enabled ( refactoring_sandbox branch for the UFE code )
2) load AL and import a proxyShape
3) modify the pivot
4) Modify -> Center Pivot
5) Notice nothing happens ( without UFE, when it's an AL_usdmaya_Transform node, this works as expected )

**Testing Environment :**

(Linux) Maya 2019.2
refactoring_sandbox ( d0bb624 ) and Pixar USD dev ( b85ddac )

( Windows ) beta ( latest PR )
refactoring_sandbox ( w/ PR#69 ) and Pixar USD-rc3

**Comment by cfmoore007** [comment]
[3_Spheres.zip](https://github.com/Autodesk/maya-usd/files/3773893/3_Spheres.zip)
added file

**Comment by santosg87** [comment]
I can reproduce this issue on our side as well using PR113 Maya build on all platforms.

**Comment by santosg87** [comment]
this one is currently fixed on usd 0.10.0. Closing it for the time being
