### ISSUE TITLE
cannot load plugin 0.3.0 in Maya 2020 after installing.

### ISSUE THREAD

**Issue by JerryKon** [Autodesk/maya-usd#732]
**Describe the bug**
Got the error when loading the mayaUsdPlugin
// Error: file: C:/Program Files/Autodesk/Maya2020/scripts/others/pluginWin.mel line 317: Unable to dynamically load : C:/Program Files/Autodesk/MayaUSD/Maya2020/0.3.0_202008140050-b9aab68/mayausd/MayaUSD/lib/maya/mtoh.mll
The specified procedure could not be found.
 // 
// Error: file: C:/Program Files/Autodesk/Maya2020/scripts/others/pluginWin.mel line 317: The specified procedure could not be found.
 (mtoh) // 
// Error: file: C:/Program Files/Autodesk/Maya2020/scripts/others/pluginWin.mel line 317: Unable to dynamically load : C:/Program Files/Autodesk/MayaUSD/Maya2020/0.3.0_202008140050-b9aab68/mayausd/MayaUSD/plugin/adsk/plugin/mayaUsdPlugin.mll
The specified procedure could not be found.
 // 
// Error: file: C:/Program Files/Autodesk/Maya2020/scripts/others/pluginWin.mel line 317: The specified procedure could not be found.
 (mayaUsdPlugin) // 

**Steps to reproduce**
1. Install the latest version of maya-usd 0.3.0
2.Open maya 2020 and load the mayaUsdPlugin

**Expected behavior**

**Attachments**
If applicable, add screenshots, sample files, etc to help explain your problem.

**Specs (if applicable):**
 - Windows 10
 - Maya 2020
 - maya-usd 0.3.0

**Additional context**

**Comment by kxl-adsk** [comment]
Hi @JerryKon, MayaUSD 0.3.0 is compatible with Maya 2020.2 specifically. We rely on new additions to the API and thus it won't work with 2020 (without update 2).
