### ISSUE TITLE
Jinja Issue

### ISSUE THREAD

**Issue by zpyn** [Autodesk/maya-usd#733]
**Describe the issue**
First of all I will like to point out that besides the Pixar USD, I dont have any previous expereinces compiling plugins or stuff I tried to build the plugins and I get the following Error:
Make Error at cmake/jinja.cmake:27 (message):
  MARKUPSAFE_LOCATION not set
Call Stack (most recent call first):
  cmake/jinja.cmake:55 (init_markupsafe)
  CMakeLists.txt:94 (include)

I also would like to know If im running the command in the right way

**command:**
python D:\USD\maya-usd\build.py --generator Ninja  --maya-location "C:\Program Files\Autodesk\Maya2020" --pxrusd-location D:\USD\USD --devkit-location D:\Autodesk\Maya\devKit\2020\Autodesk_Maya_2020_DEVKIT_Windows_Hotfix_1\devkitBase D:\USD\maya-usd --build-args boost,"--with-date_time --with-thread --with-system --with-filesystem" 

**Build log**
[build_log.txt](https://github.com/Autodesk/maya-usd/files/5113385/build_log.txt)

**Specs:**
 - OS & version: Windows 10
 - Compiler & version visualStudio 2017 
 - Maya version  Maya 2020
 - Maya USD commit SHA dev at  14c4672b5
 - Pixar USD commit SHA dev at 71b4baace2044ea4400ba802e91667f9ebe342f0

**Additional context**
Ninja Version 1.10.1

Jinja2 2.11.2
pip 20.2.2
PyYaml 5.3.1
PyOpenGl 3.1.5

**Comment by takavfx** [comment]
I'm facing to the same issue. I also hope to know the right way to fix it.

**Comment by seando-adsk** [comment]
As of version 2.7 Jinjas depends on the MarkupSafe module. It is supposed to be installed automatically when you install Jinja2 using pip. How did you install Jinja2? You should be able to add MarkupSafe by running `python -m pip install MarkupSafe`

**Comment by zpyn** [comment]
Hey I already had MarkupSafe  1.1.1 installed,

**Comment by seando-adsk** [comment]
@zpyn Do you have two python's installed? From your build log I see that it found python in the folder: C:/Python**27.1**
`-- Found Python: C:/Python27.1/python.exe (found suitable exact version "2.7.14") found components: Interpreter` 
But the folders you list above for your requirements are for a different python in folder c:\python**27**.

**Comment by zpyn** [comment]
Yeah I have two Pythons, how can I solve this? Do i need to delete one?

**Comment by takavfx** [comment]
How about set the PATH value to the Python install dir used in the build to higher priority?
ex) Move up the value in Environment Variable settings or `set PATH=(python_install_dir);%PATH%` if you use bat file.

**Comment by seando-adsk** [comment]
You can look at the cmake FindPython.cmake file to determine the logic it uses to find python when more than one are installed. 

Our main cmake file accepts setting a specific python using cmake variables. See here: https://github.com/Autodesk/maya-usd/blob/dev/CMakeLists.txt#L71

By setting those 3 vars you will force the use of the specific python you have that has Jinja/markupsafe.

**Comment by zpyn** [comment]
Hey Sean! thanks a lot , I fix this issue but I get another one, can I write it here, or I need to raise another issue?

**Comment by zpyn** [comment]
-- Found Boost 1.70.0 at D:/USD/USD/lib/cmake/Boost-1.70.0
--   Requested configuration: QUIET REQUIRED COMPONENTS filesystem;system
-- Found boost_headers 1.70.0 at D:/USD/USD/lib/cmake/boost_headers-1.70.0
CMake Error at D:/USD/USD/lib/cmake/Boost-1.70.0/BoostConfig.cmake:95 (find_package):
  Could not find a package configuration file provided by "boost_filesystem"
  (requested version 1.70.0) with any of the following names:

    boost_filesystemConfig.cmake
    boost_filesystem-config.cmake

  Add the installation prefix of "boost_filesystem" to CMAKE_PREFIX_PATH or
  set "boost_filesystem_DIR" to a directory containing one of the above
  files.  If "boost_filesystem" provides a separate development package or
  SDK, be sure it has been installed.
Call Stack (most recent call first):
  D:/USD/USD/lib/cmake/Boost-1.70.0/BoostConfig.cmake:124 (boost_find_dependency)
  C:/Program Files/CMake/share/cmake-3.17/Modules/FindBoost.cmake:444 (find_package)
  lib/mayaUsd/CMakeLists.txt:29 (find_package)


-- Configuring incomplete, errors occurred!
See also "D:/USD/maya-usd/build/RelWithDebInfo/CMakeFiles/CMakeOutput.log".
See also "D:/USD/maya-usd/build/RelWithDebInfo/CMakeFiles/CMakeError.log".

**Comment by seando-adsk** [comment]
When you build **USD** you must pass some extra boost build flags:
`python build_usd.py ~/Desktop/BUILD --build-args boost,"--with-date_time --with-thread --with-system --with-filesystem" `

See the section "Additional Build Instruction" in our [build doc](https://github.com/Autodesk/maya-usd/blob/dev/doc/build.md#L203).

**Comment by zpyn** [comment]
thanks for your reply, I think that  I already sent that flags:

 python D:\USD\maya-usd\build.py --generator Ninja --maya-location "C:\Program Files\Autodesk\Maya2020" --pxrusd-location D:\USD\USD --devkit-location D:\Autodesk\Maya\devKit\2020\Autodesk_Maya_2020_DEVKIT_Windows_Hotfix_1\devkitBase D:\USD\maya-usd --build-args boost,"--with-date_time --with-thread --with-system --with-filesystem

**Comment by seando-adsk** [comment]
@zpyn Those flags are used when building **USD** (when calling the Pixar build_usd.py script), not the maya-usd plugin.

**Comment by zpyn** [comment]
Yeah I reinstall Pixar USD with those flags and it worked thanks Sean!
