### ISSUE TITLE
Unable to see attributes from any loaded USD

### ISSUE THREAD

**Issue by Dan-at-ProxiVP** [Autodesk/maya-usd#735]
**Describe the bug**
After opening a USD file, I can navigate around the scene, and select objects with no issue, however the pivot is incorrect, and when right clicking an object in the viewport I'm given no options, and the attributes editor is empty for all example USD files from Pixar and Nvidia.

**Steps to reproduce**
1. Install Maya 2020 update 2
2. Install Maya-USD 0.3.0
3. Import a USD file via Create > Universal Scene Description(USD) > Stage from File
4. Once the file has loaded, select anything in the scene and notice that the attribute editor shows nothing

**Expected behavior**
The attribute editor would display the information the same as any other maya object.

**Attachments**
![image](https://user-images.githubusercontent.com/63273784/91015281-40e73600-e62e-11ea-9a7b-3e4a22d05f09.png)

**Specs (if applicable):**
 - Windows 10 Home (10,0.19041 Build 19041)
 - Maya 2020.2
 - MayaUSD_0.3.0_Maya2020.2_Windows_202008140050_b9aab68

**Additional context**
I have only installed Maya and MayaUSD, additionally I have python 2.7 installed from a while beforehand.
In order to make the plugins work correctly I have not had to create any folders inside of My Documents.
Additionally I have not had to set any environment variables.
This is the first USD plugin for Maya I have installed, I did not previously install any USD plugin before **0.3.0_202008140050-b9aab68**.

The contents of the mayausd.mod file are as follows.
```
+ USD 0.20.8-gold C:\Program Files\Autodesk\MayaUSD\Maya2020\0.3.0_202008140050-b9aab68\mayausd/USD
icons: 
plug-ins: 
presets: 
scripts: 
resources: 
PYTHONPATH+:=lib/python
PATH+:=bin
PATH+:=lib

+ PXR_USDMAYA 0.20.8-gold C:\Program Files\Autodesk\MayaUSD\Maya2020\0.3.0_202008140050-b9aab68\mayausd/MayaUSD/plugin/pxr
icons: maya/lib/usd/usdMaya/resources
plug-ins: maya/plugin
scripts: maya/lib/usd/usdMaya/resources
PYTHONPATH+:=lib/python
PATH+:=maya/lib
PXR_PLUGINPATH_NAME+:=lib/usd

+ MayaUSD_LIB 0.3.0 C:\Program Files\Autodesk\MayaUSD\Maya2020\0.3.0_202008140050-b9aab68\mayausd/MayaUSD
icons: 
plug-ins: 
presets: 
scripts: 
resources: 
PATH+:=lib
PYTHONPATH+:=lib/python
PXR_PLUGINPATH_NAME+:=lib/usd
VP2_RENDER_DELEGATE_PROXY=1
PYTHONPATH+:=../../bin/USD/lib/python
PATH+:=../../bin/USD/bin
PATH+:=../../bin/USD/lib

+ MayaUSD 0.3.0 C:\Program Files\Autodesk\MayaUSD\Maya2020\0.3.0_202008140050-b9aab68\mayausd/MayaUSD/plugin/adsk
plug-ins: plugin
MAYA_PLUG_IN_PATH+:=plugin

+ AL_USDMaya ${AL_USDMAYA_VERSION} C:\Program Files\Autodesk\MayaUSD\Maya2020\0.3.0_202008140050-b9aab68\mayausd/MayaUSD/plugin/al
plug-ins: plugin
PYTHONPATH+:=lib/python
PATH+:=lib
PXR_PLUGINPATH_NAME+:=lib/usd
PXR_PLUGINPATH_NAME+:=plugin

+ MTOH 0.3.0 C:\Program Files\Autodesk\MayaUSD\Maya2020\0.3.0_202008140050-b9aab68\mayausd/MayaUSD/lib
plug-ins: maya
MAYA_PLUG_IN_PATH+:=maya
```

**Comment by seando-adsk** [comment]
USD in the Attribute Editor requires UFE v2, which is not available in Maya 2020. Please see the comments in issue #473

**Comment by Dan-at-ProxiVP** [comment]
> USD in the Attribute Editor requires UFE v2, which is not available in Maya 2020. Please see the comments in issue #473

I see, thankyou for your response. In this case, since all the USD installers support Maya 2020, it will be necessary to use the old method of manually building the USD plugin from scratch, is that correct? The setup for that is quite lengthy, and we don't have anyone in-house experienced enough to do it unfortunately.

**Comment by seando-adsk** [comment]
@Dan-at-ProxiVP Sorry maybe it wasn't clear enough. Maya 2018/2019/2020 only support UFE v1, so even if you were to rebuild the plugin yourself using any of these Maya versions you won't see the attributes in the attribute editor. This attribute editor feature is only supported in the Maya Beta PR's.

**Comment by Dan-at-ProxiVP** [comment]
@seando-adsk I see, when I viewed videos and tutorials on USD I noticed people were able to see the attributes editor, but I believe this was with the pixar version of USD and the Animal Logic version, though I may be mistaken.
What is the best way to get access to Maya Beta PR's, as I'd really like to incorporate USD into our workflow.

**Comment by seando-adsk** [comment]
@Dan-at-ProxiVP if you're interested in our beta program you can sign up for an account on
https://feedback.autodesk.com/welcome/
then apply for the Maya beta program from your account. We'll get your request approved once it comes in.

**Comment by Dan-at-ProxiVP** [comment]
@seando-adsk Thankyou for your response.
Unfortunately in the list of available opportunities there is no Maya Beta Program.
Only the following opportunities are available.
![image](https://user-images.githubusercontent.com/63273784/91311513-848c9c00-e7f6-11ea-975f-c8bc9fdab1ed.png)

**Comment by ppt-adsk** [comment]
Hi @Dan-at-ProxiVP , you should be receiving an invite for the Maya beta program shortly.

**Comment by harveyr-gh** [comment]
Hi @Dan-at-ProxiVP , do you mind sending me an email at ryan.harvey@autodesk.com? We'll get you set up on the Maya Beta.

Thanks,
Ryan

**Comment by Dan-at-ProxiVP** [comment]
@harveyr-gh I've just sent you over an email with the information you need, if there is anything else please let me know.
The email is coming from proxiVP.

**Comment by JColdrick** [comment]
Apologies for being a bit behind, I was excited to see the new installer and found out the hard way about this issue.  Am I correct in assuming there is currently no working build of maya-usd for any released version of Maya?  If I wanted to get USD I would need to manually compile the AL release?  This question was asked in another thread and I didn't see a clear answer.  We can't use beta Maya in production so this isn't an option.  Thanks.

**Comment by seando-adsk** [comment]
@JColdrick There is a MayaUSD installer for Maya 2020. However Maya 2020 only has UFE **v1** which does not have support for some of the newer features such as showing USD in the attribute editor. It won't matter if you compile the plugin yourself, Maya 2020 simply does not support this.

**Comment by JColdrick** [comment]
I understand, but isn't getting at those attributes critical in order to do any work such as altering a stage?  Am I just too early to the party and should be using the older code base for now?

**Comment by kxl-adsk** [comment]
Maya-usd repository has all the latest code base for Autodesk and Studio plugins (AnimalLogic and Pixar).

The attribute editor was never part of the AnimalLogic or Pixar plugin. You might have seen some tools used together with AnimalLogic plugin, like for example https://github.com/LumaPictures/usd-qt. Switching to "the older codebase" doesn't really make any difference in this case and you will lose access to components that are shared across these plugins - like VP2RenderDelegate, Outliner, Maya to Hydra.

We are building native USD workflows in Maya and this requires extending the capabilities of API. This is why certain features are not available in the released versions of Maya.

**Comment by JColdrick** [comment]
Cool, thanks for the straight dope!  I'll just go with the latest release, that at least let's me load and export USD, that will do for now.

**Comment by seando-adsk** [comment]
@Dan-at-ProxiVP Is there anything you still need help with regarding this issue? If not can you close it please.
