### ISSUE TITLE
[MAYA-103762] refactoring_sandbox : UFE : Outliner Syncing Issues ( Selection / Prims )

### ISSUE THREAD

**Issue by cfmoore007** [Autodesk/maya-usd#74]
**Issue :**

The first time you select a prim, the selection is not reflected in the outliner ( there's some syncing issue )

Once you toggle expanding the prims the outliner ( and collapsing again ), when you duplicate again, only the latest duplicate is visible in the outliner ( the original spheres are now missing )

**Steps to re-produce :**

1) open maya with UFE enabled ( refactoring_sandbox branch for the UFE code )
2) load AL and import a proxyShape
3) all prims seem to be properly reflected in the outliner :
4) select the sphere on the left, duplicate
5) expand outliner ( notice all prims are there )
6) if you collapse the hierarchy, and select something else, starts to go out of sync 

**Testing Environment :**

(Linux) Maya 2019.2
refactoring_sandbox ( d0bb624 ) and Pixar USD dev ( b85ddac )

( Windows ) beta ( latest PR )
refactoring_sandbox ( w/ PR#69 ) and Pixar USD-rc3

**Comment by mdelasa** [comment]
Logged internally as MAYA-103762

**Comment by santosg87** [comment]
this one is fixed internally now and should be available on the next PR. :)

**Comment by cfmoore007** [comment]
Excellent.  Thanks!  We'll try it out once the new beta is released.

**Comment by cfmoore007** [comment]
This is now fixed for us in the new beta ( using the MayaUsdProxyShape ).
Will re-test w/ the AL_usdmaya_proxyShape shortly ...
