### ISSUE TITLE
Can't load  pxrUSD.mll and AL_USDMayaTestPlugin

### ISSUE THREAD

**Issue by zpyn** [Autodesk/maya-usd#747]
**Describe the issue**

After I finish the maya-usd instalation, I add as enviroment variables MAYA_MODULE_PATH:  D:\USD\maya-usd\install\RelWithDebInfo and Tried to load all plugins from Plugin Manager and I get the following errors 

** Script Editor**
"# Error: file: C:/Program Files/Autodesk/Maya2020/scripts/others/pluginWin.mel line 317: ImportError: file <maya console> line 1: No module named UsdMaya # 
// Error: file: C:/Program Files/Autodesk/Maya2020/scripts/others/pluginWin.mel line 317: initializePlugin function failed (pxrUsd) // "

// Error: file: C:/Program Files/Autodesk/Maya2020/scripts/others/pluginWin.mel line 317: Unable to dynamically load : D:/USD/maya-usd/install/RelWithDebInfo/plugin/al/plugin/AL_USDMayaTestPlugin.mll
Error en una rutina de inicialización de biblioteca de vínculos dinámicos (DLL).
 // 
// Error: file: C:/Program Files/Autodesk/Maya2020/scripts/others/pluginWin.mel line 317: Error en una rutina de inicialización de biblioteca de vínculos dinámicos (DLL).
 (AL_USDMayaTestPlugin) // 

**Output Widnow**
error detected in ..\..\plugin\pxr\maya\plugin\pxrUsd\plugin.cpp at line 132
: (kFailure): Unexpected Internal Failure
Coding Error: in Define at line 150 of D:\USD\USD\pxr\base\tf\envSetting.cpp -- Multiple definitions of TfEnvSetting variable detected.  This is usually due to software misconfiguration.  Contact the build team for assistance.  (duplicate 'PIXMAYA_ENABLE_BOUNDING_BOX_MODE')
Coding Error: in Define at line 150 of D:\USD\USD\pxr\base\tf\envSetting.cpp -- Multiple definitions of TfEnvSetting variable detected.  This is usually due to software misconfiguration.  Contact the build team for assistance.  (duplicate 'PIXMAYA_USE_USD_ASSEM_NAMESPACE')

API error detected in ..\..\plugin\pxr\maya\plugin\pxrUsd\plugin.cpp at line 132
: (kFailure): Unexpected Internal Failure

// Error: file: C:/Program Files/Autodesk/Maya2020/scripts/others/pluginWin.mel line 317: initializePlugin function failed (AL_USDMayaTestPlugin) 

API error detected in ..\..\plugin\pxr\maya\plugin\pxrUsd\plugin.cpp at line 132
: (kFailure): Unexpected Internal Failure

**Build log**

**Specs:**
 - OS & version Windows 10
 - Compiler & version [e.g. gcc 6.3.1]
 - Maya version  Maya 2020

**Additional context**

**Comment by satcar77** [comment]
Things worked when I tried it the first time. But, now I have been getting this exact issue. 

My specs are : 

- Maya 2019.1
- Windows 10
- Visual Studio 2017 C++ compiler

**Comment by ederjagreda** [comment]
I had the some problem trying to load pxrUsd.mll . 

In my case, (hope it helps you) I had  usd-core path: 
`..\USD_20.08\lib\python` 
in PYTHONPATH, variable , since this was indicated when compiled.

so when , in Maya , tried to load pxrUsd.mll this plugin looks for a pxr library in :
`..\MayaUSD\plugin\pxr\lib\python`, but since there is another pxr library in `..\USD_20.08\lib\python` , there were errors.

short answer: delete  `..\USD_20.08\lib\python`  from your PYTHONPATH, and try to load pxrUsd.mll  again


About  AL_USDMayaTestPlugin, if you can load AL_USDMayaPlugin, then you are good to go. Yo can only load only one of AL_USDMayaPlugin or AL_USDMayaTestPlugin, but not the 2 of them at the same time

**Comment by satcar77** [comment]
> I had the some problem trying to load pxrUsd.mll .
> 
> In my case, (hope it helps you) I had usd-core path:
> `..\USD_20.08\lib\python`
> in PYTHONPATH, variable , since this was indicated when compiled.
> 
> so when , in Maya , tried to load pxrUsd.mll this plugin looks for a pxr library in :
> `..\MayaUSD\plugin\pxr\lib\python`, but since there is another pxr library in `..\USD_20.08\lib\python` , there were errors.
> 
> short answer: delete `..\USD_20.08\lib\python`(edit path
> according to your path names) from your PYTHONPATH, and try to load pxrUsd.mll again
> 
> About AL_USDMayaTestPlugin, if you can load AL_USDMayaPlugin, then you are good to go. Yo can only load only one of AL_USDMayaPlugin or AL_USDMayaTestPlugin, but not the 2 of them at the same time

This worked. Thank you very much.

**Comment by kxl-adsk** [comment]
@zpyn Were you able to get unblocked or there is still something we can help you with?

**Comment by hz32290** [comment]
Hi, I've tried the method mentioned above and I still got this error:

# Error: file: C:/Program Files/Autodesk/Maya2018/scripts/others/pluginWin.mel line 290: ImportError: file <maya console> line 1: No module named UsdMaya # 
// Error: file: C:/Program Files/Autodesk/Maya2018/scripts/others/pluginWin.mel line 290: initializePlugin function failed (pxrUsd) // 

Maya Version = 2018
MAYA_MODULE_PATH= <USD_projectFolder>/install/RelWithDebInfo

Is there anything I did wrong?

**Comment by kxl-adsk** [comment]
Can you describe how you built USD and share build log for MayaUSD?

As for these errors `Coding Error: in AddUnloader at line 301 of D:\maya-usd\lib\mayaUsd\fileio\registryHelper.cpp -- Couldn't add unload function (was this function called from outside a TF_REGISTRY_FUNCTION block?)` - they are already fixed in the dev branch - see https://github.com/Autodesk/maya-usd/pull/778

**Comment by zpyn** [comment]
I have just 2 paths
1) D:\USD\maya-usd\install\RelWithDebInfo\lib
2) D:\USD\maya-usd\install\RelWithDebInfo\plugin\pxr\maya\lib

which one is the one I need to delete?

**Comment by kxl-adsk** [comment]
Looks like this issue started to become `catch-all` for problems related to loading plugins. I will close it. 

 @zpyn, @hz32290 please log separate issues. In each of them, please provide build logs.
