### ISSUE TITLE
pxrInternal_v0_20__pxrReserved error while loading the plugins in Maya

### ISSUE THREAD

**Issue by ericgd** [Autodesk/maya-usd#752]
**Describe the issue**
I was able to build (not through the script but through cmake-gui ) the Autodesk, Pixar and AL plugins without any complaints. 
However, as soon as I am trying to load them in Maya, I get these errors:

// Error: file: /usr/autodesk/maya2020/scripts/others/pluginWin.mel line 935: Unable to dynamically load : /usr/local/plugin/adsk/plugin/mayaUsdPlugin.so
/usr/local/plugin/adsk/plugin/../../../lib/libmayaUsdUtils.so: undefined symbol: _ZNK32pxrInternal_v0_20__pxrReserved__8SdfLayer11GetRealPathB5cxx11Ev // 
// Error: file: /usr/autodesk/maya2020/scripts/others/pluginWin.mel line 935: /usr/local/plugin/adsk/plugin/../../../lib/libmayaUsdUtils.so: undefined symbol: _ZNK32pxrInternal_v0_20__pxrReserved__8SdfLayer11GetRealPathB5cxx11Ev (mayaUsdPlugin) // 
// Warning: file: /usr/autodesk/maya2020/scripts/others/pluginWin.mel line 938: Could not load /usr/local/plugin/adsk/plugin/mayaUsdPlugin.so as a plug-in // 

// Error: file: /usr/autodesk/maya2020/scripts/others/pluginWin.mel line 935: Unable to dynamically load : /usr/local/plugin/al/plugin/AL_USDMayaPlugin.so
/usr/local/plugin/al/plugin/../lib/libAL_USDTransaction.so: undefined symbol: _ZN32pxrInternal_v0_20__pxrReserved__6TfType7DeclareERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE // 
// Error: file: /usr/autodesk/maya2020/scripts/others/pluginWin.mel line 935: /usr/local/plugin/al/plugin/../lib/libAL_USDTransaction.so: undefined symbol: _ZN32pxrInternal_v0_20__pxrReserved__6TfType7DeclareERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE (AL_USDMayaPlugin) // 
// Warning: file: /usr/autodesk/maya2020/scripts/others/pluginWin.mel line 938: Could not load /usr/local/plugin/al/plugin/AL_USDMayaPlugin.so as a plug-in // 

// Error: file: /usr/autodesk/maya2020/scripts/others/pluginWin.mel line 935: Unable to dynamically load : /usr/local/plugin/pxr/maya/plugin/pxrUsd.so
/usr/local/plugin/pxr/maya/plugin/../lib/libusdMaya.so: undefined symbol: _ZN32pxrInternal_v0_20__pxrReserved__12SdfReferenceC1ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKNS_7SdfPathERKNS_14SdfLayerOffsetERKNS_12VtDictionaryE // 
// Error: file: /usr/autodesk/maya2020/scripts/others/pluginWin.mel line 935: /usr/local/plugin/pxr/maya/plugin/../lib/libusdMaya.so: undefined symbol: _ZN32pxrInternal_v0_20__pxrReserved__12SdfReferenceC1ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKNS_7SdfPathERKNS_14SdfLayerOffsetERKNS_12VtDictionaryE (pxrUsd) // 
// Warning: file: /usr/autodesk/maya2020/scripts/others/pluginWin.mel line 938: Could not load /usr/local/plugin/pxr/maya/plugin/pxrUsd.so as a plug-in // 

Any idea what may cause this?
My $PATH environment seems fine. My first entry is /usr/local/USD/lib

**Build log**
Please attach a build_log.txt

**Specs:**
 - OS & version:  Centos7
 - Compiler & version: gcc 6.3.0
 - Maya version: Maya 2020.2
 - Maya USD commit SHA : current
 - Pixar USD commit SHA: 20.08

**Additional context**

**Comment by ericgd** [comment]
Well, I am still working on building it, using the script this time.
I am including the log. The error seems very similar than my previous message 9 days ago when building with cmake.
It fails with:  undefined reference to `pxrInternal_v0_20__pxrReserved
Any idea what causes this?

[build_log (2).txt](https://github.com/Autodesk/maya-usd/files/5197897/build_log.2.txt)

**Comment by 1xinghuan** [comment]
You can try to add '-D_GLIBCXX_USE_CXX11_ABI=0' flag.
#724

**Comment by ericgd** [comment]
Thank you for the reply! 

I get the same problem, probably because I get this message before the build

CMake Warning:
  Manually-specified variables were not used by the project:

    _GLIBCXX_USE_CXX11_ABI

How can I force cmake to use it?

This is my command:
sudo python build.py --verbosity 3 --generator Ninja --build-args="-DCMAKE_MAKE_PROGRAM=/usr/bin/ninja,-DBUILD_STRICT_MODE=OFF,-D_GLIBCXX_USE_CXX11_ABI=0" --maya-location /usr/autodesk/maya2020 --pxrusd-location /usr/local/USD --devkit-location /usr/autodesk/maya2020/devkit --qt-location /usr/local/Qt-5.12.5/lib/cmake/Qt5 /usr/local/workbase

**Comment by ericgd** [comment]
Thank you @1xinghuan for the reply!

I get the same problem, probably because I get this message before the build

CMake Warning:
Manually-specified variables were not used by the project:

_GLIBCXX_USE_CXX11_ABI
How can I force cmake to use it?

This is my command:
sudo python build.py --verbosity 3 --generator Ninja --build-args="-DCMAKE_MAKE_PROGRAM=/usr/bin/ninja,-DBUILD_STRICT_MODE=OFF,-D_GLIBCXX_USE_CXX11_ABI=0" --maya-location /usr/autodesk/maya2020 --pxrusd-location /usr/local/USD --devkit-location /usr/autodesk/maya2020/devkit --qt-location /usr/local/Qt-5.12.5/lib/cmake/Qt5 /usr/local/workbase

**Comment by 1xinghuan** [comment]
I added this flag by setting env 'CXXFLAGS':
```
export CXXFLAGS="-D_GLIBCXX_USE_CXX11_ABI=0"
python ....
```

**Comment by rowanth-u** [comment]
Hi guys, I am having the exact same problem. Did you eventually figure out the issue? I am running Ubuntu 20, USD v22.08 and latest maya-USD. Please find log attached, any help would be great.
[build_log.txt](https://github.com/Autodesk/maya-usd/files/9809095/build_log.txt)
