### ISSUE TITLE
[MAYA-103876] refactoring_sandbox : UFE : Translating Prim in objectSpace does not take into account its local rotation changes

### ISSUE THREAD

**Issue by BigRoy** [Autodesk/maya-usd#76]
### Issue

Whenever the translate tool is in "object space" it will totally ignore any local scene rotations that were performed on the Prims in the USD scene. It will always move in the original local space direction that was stored in the USD scene prior to any local scene rotation changes to that Prim.

1. Load USD proxy shape.
2. Select a transform in it.
3. Rotate the objects around.
4. Translate along a single axis in objectSpace.

Note that now the translation is happening as if Step 3 never occurred.

### Specs

- Windows 10
- Maya 2019.2
- refactoring_sandbox ( `d0bb624` ) 
- Pixar USD dev ( `b85ddac` )

---

Mentioned in https://github.com/Autodesk/maya-usd/issues/51

**Comment by cfmoore007** [comment]
One of our layout artists here also ran into this problem.  They use object space manipulation all of the time.

**Comment by santosg87** [comment]
this is now fixed internally and should be available on the next PR :)

**Comment by cfmoore007** [comment]
This appears to be addressed in PR115 with our tests here.

@BigRoy is it also working for you?

**Comment by kxl-adsk** [comment]
This is already fixed for a while. @BigRoy please reopen if you find we missed something.
