### ISSUE TITLE
Maya 2020.2 and Release 0.3.0 (windows 10) - Plugin not loading

### ISSUE THREAD

**Issue by brycelynch** [Autodesk/maya-usd#766]
Clean install of Windows 10 Maya 2020.2 and maya-usd release version 0.3.0 fails to load plugin with following error:

**The specified procedure could not be found.**

Here is the output from console:

// Error: file: C:/Program Files/Autodesk/Maya2020/scripts/others/pluginWin.mel line 317: Unable to dynamically load : C:/Program Files/Autodesk/MayaUSD/Maya2020/0.3.0_202008140050-b9aab68/mayausd/MayaUSD/plugin/adsk/plugin/mayaUsdPlugin.mll
The specified procedure could not be found.
 // 
// Error: file: C:/Program Files/Autodesk/Maya2020/scripts/others/pluginWin.mel line 317: The specified procedure could not be found.
 (mayaUsdPlugin) // 
// Error: file: C:/Program Files/Autodesk/Maya2020/scripts/others/pluginWin.mel line 317: Unable to dynamically load : C:/Program Files/Autodesk/MayaUSD/Maya2020/0.3.0_202008140050-b9aab68/mayausd/MayaUSD/lib/maya/mtoh.mll
The specified procedure could not be found.
 // 
// Error: file: C:/Program Files/Autodesk/Maya2020/scripts/others/pluginWin.mel line 317: The specified procedure could not be found.
 (mtoh) // 

![Screenshot_11](https://user-images.githubusercontent.com/8460470/92420780-19ae5f80-f12a-11ea-8b68-d30530ca0866.jpg)

mod file located in autodesk shared common files appears to be mapped correctly to the plugin installation.

**Comment by santosg87** [comment]
HI @brycelynch do you have any environment variables from previous builds of usd? the error you have is a generic plugin load error, but it isn't uncommon for environment variables (from old usd builds, or python paths, etc) to affect this.

**Comment by santosg87** [comment]
@brycelynch we have mayaUSD 0.4.0 available now, feel free to give a try on it and see if that loads as expected for you. 

Cheers!

**Comment by DavidSpeicher** [comment]
hi im also having this issue. Maya 2020.3 i tried versions 0.3.0 , 0.4.0 and 0.5.0 all resulted with this error

**Comment by seando-adsk** [comment]
@DavidSpeicher Make sure that you don't have any versions of USD somewhere in your PATH. For instance the "Omniverse Connect plugin for Maya" will add USD to the path which conflicts with our plugin.

**Comment by DavidSpeicher** [comment]
this was my first time installing this plugin. so i dont think that would be the issue.

**Comment by santosg87** [comment]
@DavidSpeicher from the behavior you are describing, it does sounds like you might have something conflicting with the plugin.

I would recommend running the mel command
getenv "MAYA_MODULE_PATH"

and checking within the locations that maya returns to see if you have any "USD" or mayaUSD libraries/folders. 

cheers!
