### ISSUE TITLE
[MAYA-106867] Discarding Edits Can Crash Maya

### ISSUE THREAD

**Issue by wjwilson** [Autodesk/maya-usd#769]
**Describe the bug**
Discarding edits on a USD layer can crash Maya if it leads to a change in the hierarchy. In particular, if it leads to a reference being removed.

**Steps to reproduce**
1. Create a USD stage with at least one prim in it. I'm loading a simple USD file that looks like this:
```
#usda 1.0

def Xform "Xform1"
{
}
````
2. Reference a second USD file into the stage. I'm using a file that looks like this:
```
#usda 1.0
(
    defaultPrim = "top"
)

def Xform "top"
{
    def Cube "cube"
    {
    }
}

```
3. The viewport doesn't seem to redraw automatically so do something to jiggle it (click in the outliner or viewport, so long as the geometry becomes visible)
4. In the USD Layer Editor right-click and Discard Edits on whichever layer is active.
5. The geometry will disappear from the viewport, but the reference will still show in the hierarchy in the outliner.
6. Do something to jiggle the update again (click in the outliner, viewport, change selection, etc)
7. Maya will crash

**Expected behavior**
On clicking Discard Edits, USD stage will revert to the state on disk. The outliner and viewport will reflect this. Maya won't crash.

**Specs (if applicable):**
 - Windows 10
 - Maya PR118
 - Maya USD 0.3.0 bundled with PR
 - Pixar USD 20.08 bundled with PR

**Additional context**
I've crashed Maya about 300 times in the last 24 hours and sent a CER each time, if the information there is useful then CER_226117302 is one of them.

**Comment by santosg87** [comment]
thanks for logging this! we have it logged internally as well. this will add more info to help us narrow down the issue. :)

**Comment by santosd** [comment]
Hi @wjwilson, This has been resolved and the fix should be in the next PR.
