### ISSUE TITLE
refactoring_sandbox : UFE : Snapping Prims fails to perform correct snap translation

### ISSUE THREAD

**Issue by BigRoy** [Autodesk/maya-usd#77]
### Issue

When selecting something from the USD subscene and trying to snap it to regular Maya content, e.g. a locator in the scene. It will perform snapping but will be misaligned. It does not snap using the pivot point but just applies the "translation" of the local scene on top of the original offset of the USD subscene.

For example, when trying to snap a floor tile of the example Kitchen Set it will have a similar distance to the locator as it originally had to the origin. The maya MEL command being issued from the snapping is:

```
move -rpr -300 10 50;
```

The snapping makes use of the [`-rotatePivotRelative`](http://help.autodesk.com/cloudhelp/2019/ENU/Maya-Tech-Docs/Commands/move.html#flagrotatePivotRelative) flag which seems to fail to move correctly relative to the rotate pivot but instead just does a regular move like move -300 10 50; which gives the exact same result.

Once the `-rotatePivotRelative` flag will work the snapping should start to behave as expected.

#### To reproduce

1. Create a locator at a random position (that you can snap to)
2. Load USD proxy shape.
3. Select a Prim or multiple of them in the proxy.
4. Translate snap to the locator (default shortcut is `v `)

Note how the snapping behaves very odd.

### Specs

- Windows 10
- Maya 2019.2
- refactoring_sandbox ( `d0bb624` ) 
- Pixar USD dev ( `b85ddac` )

---

Mentioned in https://github.com/Autodesk/maya-usd/issues/51

**Comment by HdC-adsk** [comment]
@BigRoy This is a known issue which is already tracked internally. Nice analysis about "move -rpr"! We definitely need to fix it.

**Comment by HdC-adsk** [comment]
Tracked as MAYA-99888 internally.

**Comment by kxl-adsk** [comment]
@BigRoy Can you validate, this should be already fixed (and available in dev branch)

**Comment by kxl-adsk** [comment]
OK, I was too quick with this one. You will need to wait for the next update to Maya 2019.

**Comment by santosg87** [comment]
@BigRoy 2019.3 is now available, would you be able to validate and close this? :)

**Comment by BigRoy** [comment]
@santosg87 unfortunately I don't think I'll have the time to do this anytime soon. Maybe next week at the earliest. Thanks for pinging me (again) though! :) Will keep it in mind when I find myself with some time on my hands.

**Comment by santosg87** [comment]
Marking this one as closed based on our testing. @BigRoy, feel free to re-open it if it is still a problem for you. :)
