### ISSUE TITLE
[MAYA-99990] refactoring_sandbox : VP2RenderDelegate: Holding snap shortcut while dragging over USD proxy will keep adding Prims to selection

### ISSUE THREAD

**Issue by BigRoy** [Autodesk/maya-usd#78]
### Issue

When trying to snap (using snap shortcut) to the USD scene the UFE subscene selection thinks it needs to be active and will continuously add whatever you hover over to the selection. Plus the first object in the USD scene that was under the cursor at the time of starting the snapping will move along too. The rest is just added to selection, but not moving along.

#### To reproduce

1. Load USD proxy shape.
2. Create a locator.
3. Try and snap to the USD scene, e.g to one of its Prims while holding the snap shortcut (default shortcut is `v`).
4. Now as you drag over the USD proxy shape note how it's changing the selection.

### Specs

- Windows 10
- Maya 2019.2
- refactoring_sandbox ( `d0bb624` ) 
- Pixar USD dev ( `b85ddac` )

---

Mentioned in https://github.com/Autodesk/maya-usd/issues/51

**Comment by HdC-adsk** [comment]
Thanks for reporting the issue.

It is a known issue to us, and we are waiting for an API fix to be backported for this issue.

(If you try a Maya 2020 PR, it should be working.)

**Comment by HdC-adsk** [comment]
Logged as MAYA-99990 internally.

**Comment by santosg87** [comment]
HI @BigRoy, are you able to validate this? it should be fixed on the current dev branch with the PR113 maya build. :)

**Comment by santosg87** [comment]
marking this one as closed based on our internal testing. if this is still a problem, feel free to re-open it. :)
