### ISSUE TITLE
[ERROR] mayaUsd\fileio\registryHelper.cpp -- Couldn't add unload function (was this function called from outside a TF_REGISTRY_FTF_REGISTRY_FUNCTION block?)

### ISSUE THREAD

**Issue by shdwdln** [Autodesk/maya-usd#784]
**Describe the issue**
A description of what the issue is.

I get thiserror:
maya-usd\lib\mayaUsd\fileio\registryHelper.cpp -- Couldn't add unload function (was this function called from outside a TF_REGISTRY_FUNCTION block?)

When I run the test
`mayapy D:\BUILD_USD_FOR_MAYA\INSTALL\build\RelWithDebInfo\test\lib\usd\pxrUsdPreviewSurface\testPxrUsdPreviewSurfaceExport.py`

**Build log**
Please attach a build_log.txt

**Specs:**
 - OS & version [e.g. Windows 10]
 - Compiler & version [e.g. gcc 6.3.1]
 - Maya version [e.g. Maya 2018]
 - Maya USD commit SHA [e.g. master at c6483ce68c]
[build_log.txt](https://github.com/Autodesk/maya-usd/files/5250598/build_log.txt)
caa921c1]
 - Pixar USD commit SHA [e.g. master at 71b4baa]

**Additional context**

**Comment by kxl-adsk** [comment]
PR #778 should address your issue.

**Comment by kxl-adsk** [comment]
@shdwdln Fix was merged to dev branch - please validate and close this issue.

**Comment by shdwdln** [comment]
looks good!!! Thanks
