### ISSUE TITLE
Where is mayaUsdLayerEditor

### ISSUE THREAD

**Issue by plboily** [Autodesk/maya-usd#792]
Hi, I am trying to get the layer editor in the latest "0.4.0" release.
In the plugin manager, we can see under info from "mayaUsdPlugin.mll" --> mayaUsdLayerEditor
So can i show this Usd Layer Editor?

Just install the latest 0.4 maya-usd and cant find it.

Windows 10
Maya 2020.2

Thanks.

**Comment by wtelford** [comment]
Thanks for logging this issue with us. Currently the layer editor lives in the Maya code-base and not in the plugin. In order to access this particular interface you'll need to be using the Maya Beta PR releases.
