### ISSUE TITLE
[MAYA-107167] USDZ export writes paths that aren't inclusive to the usdz

### ISSUE THREAD

**Issue by dgovil** [Autodesk/maya-usd#795]
**Describe the bug**
There was a regression to this repo that caused usdz files to write references that aren't inclusive to the zip file.
Previously, the paths would be written relative to the internals of the usdz and would include the referenced dependencies into the usdz file, however this no longer works.

This was due to a change in [cb77d92c63](https://github.com/Autodesk/maya-usd/commit/cb77d92c63) `lib/usd/translators/shading/usdFileTextureWriter.cpp`
**Steps to reproduce**
1. Export asset as a usdz
2. Check the file path reference on the Shader file1 prim.

**Expected behavior**
Prior to this change, the filepath would resolve as `0/checkerboard.png` since the path and texture would be inlined into the usdz.
After this change, the path is relative to the workspace and no longer inlines the texture into the zip.

We disabled this block of code, and it's back to the expected behaviour, so I think revisiting this code will resolve the issue.

**Attachments**
I've attached the Maya workspace this is generated from, and the usdz is inside it as well

[bugreports.zip](https://github.com/Autodesk/maya-usd/files/5272256/bugreports.zip)

**Specs (if applicable):**
 - macOS Catalina and Big Sur
 - Compiler version: Apple clang version 12.0.0 (clang-1200.0.32.5) (reproducible on older clang versions too)
 - Maya 2018.5 and 2020.0
 - Maya USD commit SHA 4365cc6675f666ee8ec23bc21c12ef68b3a5d5c7
 - Pixar USD commit SHA 71b4baace2044ea4400ba802e91667f9ebe342f0

**Additional context**
We are still using `pxrUSD.bundle` to do our exporting.

**Comment by kxl-adsk** [comment]
Thanks for reporting @dgovil. We knew we are taking shortcuts here. I will let @JGamache-autodesk investigate and comment.
