### ISSUE TITLE
Changing variant selection on an instanced prim will crash

### ISSUE THREAD

**Issue by marsupial** [Autodesk/maya-usd#798]
**Describe the bug**
If a prim is instanced and has variants, changing the variant selection via UFE/outliner will consistently crash Maya.

**Steps to reproduce**
1. create a usdProxy, and load the usda file below
2. In the outliner select "THING"
3. Right click and change the variant to "LO" 
4. See crash

**Expected behavior**

**Attachments**
```
#usda 1.0
(
    defaultPrim = "THING"
    metersPerUnit = 0.01
)
def Xform "THING" (
    kind = "component"
    variants = { string lod = "HI" }
    variantSets = "lod"
    instanceable = true
)
{
    variantSet "lod" = {
        "LO" {
            def Cube "cube1"
            {
                float3[] extent = [(-0.25, -0.25, -0.25), (0.25, 0.25, 0.25)]
                double size = 0.5
            }
        }
        "HI" {
            def Cube "cube2"
            {
                float3[] extent = [(-1,-1,-1), (1,1,1)]
                double size = 2
            }
        }
    }
}
```

**Specs (if applicable):**
 - OS & version: Linux
 - Compiler: gcc-6.3
 - Maya version :2021-PR118/2021-PR119
 - Maya USD commit SHA: b4b29b316c6f1fd0eb234eca1cd00a3976a5fd69
 - Pixar USD commit SHA: 533030f94bab9e4b2df5e8896b867b3379bfeafc

**Comment by cfmoore007** [comment]
[apples_and_inherits_workflows.zip](https://github.com/Autodesk/maya-usd/files/5284523/apples_and_inherits_workflows.zip)

I have included another scene, with a similar issue.  You can load apple.usda and witness the same problem.  There are a few different variation of the same setup included.

**Comment by marsupial** [comment]
Same stack trace for me, yeah.

**Comment by santosd** [comment]
Hi @cfmoore007, I gave this a try using PR120 using Windows 10 and I was not able to replicate the crash. @santosg87 maybe you can give it a try on Linux.

**Comment by marsupial** [comment]
On master, Linux, and PR-120 this has been fixed.  I'll close this out unless any objections.
