### ISSUE TITLE
error C2039: 'pointSnapping': is not a member of 'Autodesk::Maya::OpenMaya20200000::MHWRender::MSelectionInfo'

### ISSUE THREAD

**Issue by cfmoore007** [Autodesk/maya-usd#811]
**Describe the issue**
F:\Repos\maya-usd\lib\usd\hdMaya\delegates\proxyDelegate.cpp(330): error C2039: 'pointSnapping': is not a member of 'Autodesk::Maya::OpenMaya20200000::MHWRender::MSelectionInfo' [F:\APPLICATIONS\MayaUSD\dev-f94bcfa\build\lib\usd\hdMaya\hdMaya.vcxproj]
  F:\APPLICATIONS\Autodesk\Maya2021\include\maya/MSelectionContext.h(113): note: see declaration of 'Autodesk::Maya::OpenMaya20200000::MHWRender::MSelectionInfo'

**Build log**
[build_log.txt](https://github.com/Autodesk/maya-usd/files/5315166/build_log.txt)

**Specs:**
 - OS & version [ Windows 10 ]
 - Compiler & version [ Visual Studio 2017 ]
 - Maya version [ Maya Beta PR 119 ]
 - Maya USD commit SHA [ dev at f94bcfa ]
 - Pixar USD commit SHA [ 20.08 ]

**Additional context**

**Comment by kxl-adsk** [comment]
@cfmoore007 Are you sure you updated both Maya Preview Release and the devkit? I just checked and pointSnapping is in MSelectionInfo.

**Comment by cfmoore007** [comment]
Appologies.  It now works!  Thanks!
