### ISSUE TITLE
crash when discarding edits

### ISSUE THREAD

**Issue by cfmoore007** [Autodesk/maya-usd#813]
**Describe the bug**
Discarding edits from the session layer is resulting in a Maya Crash 

`Exception code: C0000005: ACCESS_VIOLATION - illegal read at address 0x00000010
Fault address:  63291400 in F:\APPLICATIONS\Autodesk\Maya2021\bin\ufe_0.dll
0001:00040400 Logical offset (see .map file for location)

Call stack:
End of stack`

**Steps to reproduce**
1. Create Stage from File ( choose 3 spheres example )
2. In Layer Editor unhide session layer and make it the edit target
3. In the Maya Outliner, right-click on the usdStageShape -> Add New Prim -> Def
4. select all 3 spheres, middle mouse drag onto Def prim ( this did not work b/c spheres are in another layer )
5. in Layer Editor, right-click on session layer -> discard edits
6. fatal error

**Expected behavior**
Maya does not crash

**Attachments**
[3_Spheres.zip](https://github.com/Autodesk/maya-usd/files/5317632/3_Spheres.zip)
[MayaCrashLog201002.0728.log](https://github.com/Autodesk/maya-usd/files/5317640/MayaCrashLog201002.0728.log)

**Specs (if applicable):**
 - OS & version [ Windows 10 ]
 - Compiler & version [ Visual Studio 2017 ]
 - Maya version [ Maya Beta PR 119 ]
 - Maya USD commit SHA [ dev at f94bcfa ]
 - Pixar USD commit SHA [ 20.08 ]

**Additional context**

**Comment by cfmoore007** [comment]
**Update :** this same fatal error will occur even if I try to discard the edits of the file layer itself.  This is not limited to the session layer.

**Comment by cfmoore007** [comment]
Also note, this seems to be a slightly different use case than : https://github.com/Autodesk/maya-usd/issues/769

**Comment by santosd** [comment]
@cfmoore007 thank you for posting this. There are some recent changes that no longer allow the parenting of the 3 spheres under the def in the session layer because they were not defined in the session layer so this workflow is no longer possible and therefore no fatal error. The changes will be in the next PR. Also the fix for #813 will be in there aswell.
