### ISSUE TITLE
Error building on Windows 10

### ISSUE THREAD

**Issue by ollied-xx** [Autodesk/maya-usd#820]
**Describe the issue**
I am attempting to build this plugin on windows.  Following the instructions on the build page, I have cloned the repo and on attempting to run the build.py file, it errors with the following.

```
E:\files\USD\maya-usd>python build.py --maya-location "C:\Program Files\Autodesk\Maya2020" --pxrusd-location E:\downloads\usd-20-08-win64_py27_release --devkit-location E:\downloads\Autodesk_Maya_2020_2_Update_DEVKIT_Windows E:\files\USD\maya-usd\workspace

    Building with settings:
      Source directory          E:\files\USD\maya-usd
      Workspace directory       E:\files\USD\maya-usd\workspace
      Build directory           E:\files\USD\maya-usd\workspace\build\RelWithDebInfo
      Install directory         E:\files\USD\maya-usd\workspace\install\RelWithDebInfo
      Variant                   RelWithDebInfo
      Python Debug              Off
      CMake generator           Default
      Build Log                 E:\files\USD\maya-usd\workspace\build\RelWithDebInfo\build_log.txt
      Stages arguments          ['clean', 'configure', 'build', 'install']
#####################################################################################
log date: 2020-10-06 21:16
commit sha: f94bcfaa2884b5955169b379a24e6979fc38ee2e
commit date: Wed Sep 30 15:30:26 2020 -0400
#####################################################################################

cmake -DCMAKE_INSTALL_PREFIX="E:\files\USD\maya-usd\workspace\install\RelWithDebInfo" -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -G "Visual Studio 14 2015 Win64" -DMAYA_LOCATION="C:\Program Files\Autodesk\Maya2020" -DPXR_USD_LOCATION="E:\downloads\usd-20-08-win64_py27_release" -DMAYA_DEVKIT_LOCATION="E:\downloads\Autodesk_Maya_2020_2_Update_DEVKIT_Windows" -DMAYAUSD_DEFINE_BOOST_DEBUG_PYTHON_FLAG=OFF "E:\files\USD\maya-usd"
-- Selecting Windows SDK version  to target Windows 10.0.19041.
CMake Error at CMakeLists.txt:18 (project):
  Failed to run MSBuild command:

    MSBuild.exe

  to get the value of VCTargetsPath:

    The system cannot find the file specified



-- Configuring incomplete, errors occurred!
See also "E:/files/USD/maya-usd/workspace/build/RelWithDebInfo/CMakeFiles/CMakeOutput.log".

Traceback (most recent call last):
  File "build.py", line 602, in <module>
    BuildAndInstall(context, context.buildArgs, context.stagesArgs)
  File "build.py", line 371, in BuildAndInstall
    RunCMake(context, extraArgs, stagesArgs)
  File "build.py", line 277, in RunCMake
    extraArgs=(" ".join(extraArgs) if extraArgs else "")))
  File "build.py", line 165, in Run
    .format(cmd=cmd, log=os.path.abspath(context.logFileLocation)))
RuntimeError: Failed to run 'cmake -DCMAKE_INSTALL_PREFIX="E:\files\USD\maya-usd\workspace\install\RelWithDebInfo" -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -G "Visual Studio 14 2015 Win64" -DMAYA_LOCATION="C:\Program Files\Autodesk\Maya2020" -DPXR_USD_LOCATION="E:\downloads\usd-20-08-win64_py27_release" -DMAYA_DEVKIT_LOCATION="E:\downloads\Autodesk_Maya_2020_2_Update_DEVKIT_Windows" -DMAYAUSD_DEFINE_BOOST_DEBUG_PYTHON_FLAG=OFF "E:\files\USD\maya-usd"'
See E:\files\USD\maya-usd\workspace\build\RelWithDebInfo\build_log.txt for more details.
```

**Build log**
Build log and cmake output attached.  
[build_log.txt](https://github.com/Autodesk/maya-usd/files/5338267/build_log.txt)
[CMakeOutput.log](https://github.com/Autodesk/maya-usd/files/5338268/CMakeOutput.log)

**Specs:**
 - Windows 10
 - VS 2019
 - Maya 2020
 - Maya USD commit SHA
master d9f5bd5 

 - Pixar USD commit SHA 
binaries downloaded from https://developer.nvidia.com/usd

**Additional context**
I have USD up and running using the binaries from nvidia.  However I am not sure if that works with building this plugin for maya?  Do I need to have the source for USD cloned and build to be able to use this plugin, or is there a way that I can use it in conjunction with the binaries from nvidia?  I like to avoid having to go down the route of fully building USD on windows if I can.  I have heard it is quite to journey!

**Comment by HamedSabri-adsk** [comment]
Hi @ollied-xx ,

Your spec says VS 2019 but your log shows that you are generating for VS 2015 ( -G "Visual Studio 14 2015 Win64"  )? Also, I would check to make sure to have **MSBuild** installed under compilers, build tools which it should be installed by default:

![MSbuild](https://user-images.githubusercontent.com/48299423/95333134-5a5cde00-087a-11eb-9551-515caf80cc25.PNG)

As for USD, I wouldn't use the USD binaries from Nvidia. They are not build with boost filesystem and soon you will hit a compiler error when building the project. It is explained under **Additional Build Instruction**  section in the doc.

https://github.com/Autodesk/maya-usd/blob/dev/doc/build.md

Building USD is not a journey and fairly simple if you use "build_usd.py" and have the required python packages installed. See "Additional Build Instruction" in the doc.

Also, we provide the MayaUSD binaries with the installer that you can opt to and skip building the project. 

https://github.com/Autodesk/maya-usd/releases/tag/v0.4.0

**Comment by ollied-xx** [comment]
Hi @HamedSabri-adsk, thanks for the details.  Good to know about the releases, I actually wasnt aware they were available for download!

Atm it 
looks like I dont have a combination of Maya and USD that will work with these.  I'll have a go at the weekend at getting these aligned and see if I can get the plugin working that way.  If not, I'll go down the path of building it all from scratch.
