### ISSUE TITLE
[MAYA-107352] Maya crash when setting Translate tool to "Normal" mode

### ISSUE THREAD

**Issue by fabal** [Autodesk/maya-usd#824]
**Description**
Instant crash when switching Translate tool to "Normal" mode after selecting a USD prim

**Steps to reproduce**
1. Create a `mayaProxyShape` and load any USD stage (tested with pixar's Kitchen_set)
2. Select any prim
3. Activate the Transform tool
4. Set `Axis orientation` to `Normal` in the Transform tool's option

**Specs (if applicable):**
 - CentOS 7.4
 - gcc 6.3.1
 - Maya 2020
 - Maya USD 0.4.0 (**UFE** build)
 - Pixar USD dev @ [f4aac5a147b7837f33a7402225742cd2634cd396](https://github.com/PixarAnimationStudios/USD/commit/f4aac5a147b7837f33a7402225742cd2634cd396)

**Comment by santosg87** [comment]
thank you for logging this! I was able to reproduce this internally as well, and linked it to our database.

**Comment by santosg87** [comment]
@fabal this should be fixed on the last Maya beta, are you able to test and close once confirmed? cheers!

**Comment by fabal** [comment]
Thanks @santosg87 :+1:  I can confirm this is fixed.
