### ISSUE TITLE
refactoring_sandbox : Proxy shape local Prim changes remain even after delete/recreate or new scene

### ISSUE THREAD

**Issue by BigRoy** [Autodesk/maya-usd#83]
### Issue

If you create a USD Proxy shape and move Prims around using UFE these changes will persist as if stored globally. Deleting the proxy and loading the same USD scene will directly show the same changes. Even *New Scene* will have the local USD changes you did persist. *Even* if you unload the plug-in and reload the plug-in the change persists.

Only restarting Maya seems to resolve it.

Note that I'm create the proxy shapes with:
```python
from maya import cmds

path = "path/to/Kitchen_set.usd"
node = cmds.createNode("mayaUsdProxyShape")
cmds.setAttr(node + ".filePath", path, type="string")
```

#### To reproduce

1. Create a proxy shape and load USD file.
2. Move Prims around in the USD Proxy.
3. Delete the Proxy (or New Scene)
4. Recreate the proxy shape and load the USD file.

Note how the changes done in Step 2 also still exist in the new shape with Step 4.

### Specs

- Windows 10
- Maya 2019.2
- refactoring_sandbox ( [`d0bb624`](https://github.com/Autodesk/maya-usd/commit/caa921c1cb3b59ea6acc84540ebea9a05b1fedf9) ) 
- Pixar USD dev ( `b85ddac2` )

---

Mentioned in https://github.com/Autodesk/maya-usd/issues/51

**Comment by BigRoy** [comment]
I can confirm this issue also happens in the [latest state of the `dev` branch](https://github.com/Autodesk/maya-usd/commit/aa41c5554e4a3c420989350b2503fc3ca6027421) however the issue does not happen when using the `AL_USDMayaPlugin` through the `USD > Proxy > Import` menu. I believe this is due to the `Stage cache Id` being applied as `-1`, likely meaning it's forced to a new unique identifier.

However I can't seem to find that similar functionality for the `mayaUsdProxyShape` or how to exactly reproduce the behavior through code to create the nodes.

**Comment by BigRoy** [comment]
Just checking back in. Is there currently any way to force/set the Stage cache Id for the `mayaUsdProxyShape`, e.g. passing it `-1` as described above to avoid this "shared state" even across scenes or throughout the whole maya session.

Also, with it currently being able to break like this, could this behavior turn out dangerous? For example, if you have a scene that has stage id 1 and 2. Then you open another file that was saved with two USD proxies with stage ids 2 and 3. What happens with the changes of stage id 2? Does it preserve them and try to apply them in the other scene?

**Comment by kxl-adsk** [comment]
Indeed we have two different stage caches at this point. AL plugin is wrapping around UsdUtilsStageCache (https://github.com/PixarAnimationStudios/USD/blob/master/pxr/usd/lib/usdUtils/stageCache.h) and the base proxy has its own stage cache. Something to unify.

I do not have an answer to your question, maybe @mattyjams can chime in?

**Comment by mattyjams** [comment]
At the USD level, if you have layers being held open by stage caches across Maya scene changes (File->Open, File->New, etc.), then that would probably explain it. You could check this in Maya by making some edits, then doing a File->New and checking whether there are still layers loaded in the layer registry:

```
Sdf.Layer.GetLoadedLayers()
```

If that returns any layers after switching to a new scene, then there is probably a stage cache not getting reset and holding those layers open. Re-opening one of those layers is going to return you the version in the stage cache.

We should hopefully be accounting for this in the pxr nodes and the `mayaUsdProxyShape` with a listener:

https://github.com/Autodesk/maya-usd/blob/5d5e2b7efb9d6c707abc8a39698271066b6c4931/lib/utils/stageCache.cpp#L52

**Comment by kxl-adsk** [comment]
The issue has been fixed for a while - closing this ticket. @BigRoy please reopen if we missed something.
