### ISSUE TITLE
Ufe_v1 built with gcc 4.xx and old ABI. Can't link against it

### ISSUE THREAD

**Issue by mhamid3d** [Autodesk/maya-usd#830]
After building the maya-usd plugin successfully, I am getting the error when trying to load the plugin:
`undefined symbol: _ZNK6Ufe_v14Path6stringB5cxx11Ev`
This is similar to Issue #724, but the solution there was to add the flag `D_GLIBCXX_USE_CXX11_ABI=0`. This did not work for me, it caused build error's that all look like this:

``` undefined reference to `pxrInternal_v0_20__pxrReserved__::SdfLayer:` ```

I've tried compiling USD and maya-usd with the same exact GCC version and I'm still having the same issue.

As for UFE, the correct libraries **are** being found from the maya-devkit directory as per CMAKE's output log, so I'm not sure what's causing the issue. When I built with `-DCMAKE_WANT_UFE_BULD=OFF` it worked fine and loaded in Maya, but of course I would like the UFE features. I even tried editing the CMAKE to use the ufe library from the /usr/autodesk/maya directory and still the same problem.

**Specs:**
 - OS & version: Ubuntu 20.04
 - Compiler & version: 6.4.0
 - Maya version: 2020
 - Maya USD commit SHA: v0.4.0
 - Pixar USD commit SHA: v20.08

**Comment by mhamid3d** [comment]
So after doing some digging, I found that the Ufe libraries that ship with the maya devkit are practically ancient. Built with GCC 4.x, and using an old CXXABI that makes it very difficult to link against. Not only did I have to disable CXX11ABI on maya-usd, but also my main usd build, all my boost libraries, and all other linkning dependencies of USD. 

Why isn't Ufe source included with the devkit so we can build our own? I can't find anything online about Ufe besides a short paragraph description.

**Comment by ppt-adsk** [comment]
Hey @mhamid3d, sorry you're having a rough time.  UFE is not open source, it's proprietary Autodesk code.  I would really suggest sticking to the recommended developer setup for Maya 2020:

https://help.autodesk.com/view/MAYAUL/2020/ENU/?guid=__developer_Maya_SDK_MERGED_Setting_up_your_build_MinimumRequirementsAllPlatforms_html

This is what we use to build and test maya-usd with UFE support on Maya 2020.  I assume you're already quite familiar with

https://github.com/Autodesk/maya-usd/blob/dev/doc/build.md

but many times it has happened that people run into trouble because they don't stick with the tried and true recipe :)  Hope this helps.

**Comment by mhamid3d** [comment]
@ppt-adsk Thank you for the response. Yes I am at fault for not using a RHEL operating system. But it does seem like Ufe is the only blocker for better Ubuntu support. Is Ufe_v2 at least going to be compiled with gcc 6.3.1 (or anything above 4) like Maya and most of its libraries are?

**Comment by seando-adsk** [comment]
@mhamid3d Yes its true that UFE v1 was built with an old gcc (4.4.7 I believe). We are currently building UFE v2 with gcc 6.3.1. I'm not sure why it won't build for you. We are using gcc 6.3.1 to build the plugin for Maya 2020, with UFE v1. I can suggest two options for you.
First, we provide pre-built binaries of the plugin for Maya 2020. See the [releases page](https://github.com/Autodesk/maya-usd/releases) and open the "Assets" for a plugin version you would like to try.
Second, you could apply for the Maya Beta program by sending an email to ryan.harvey@autodesk.com. This will give you access to the latest Maya version with UFE v2.

**Comment by mhamid3d** [comment]
@seando-adsk Im pretty sure the problem boils down to how libboost is built and provided between Debian and RHEL operating systems. When I disable CXX11ABI features in boost, usd, and maya-usd (in that order), it ends up working. Also that is fantastic news for Ufe_v2. Thanks for the options!
