### ISSUE TITLE
Error loading mayusd.so "No module named UsdMaya"

### ISSUE THREAD

**Issue by suekieza** [Autodesk/maya-usd#84]
Hey there,

Just built the sandbox branch and tried to load the plugin in: Maya 2019.1, Linuz Centos 7
It gives me the following error
`waitCursor -state on;										 $gIgnoreUpdateCallback = true;loadPluginCmd( "/home/suesauer/maya/2019/build/RelWithDebInfo/plugin/adsk/plugin/mayaUsdPlugin.so"); 		   updatePluginUI( "0" );waitCursor -state off;									   $gIgnoreUpdateCallback = false;
isPluginDisabled("mayaUsdPlugin");
// Result: 0 // 
// Error: file: /usr/autodesk/maya/scripts/others/pluginWin.mel line 317: initializePlugin function failed (mayaUsdPlugin) // 
updatePluginCallback();
// Result: 0 // `

my maya.env is
`## USD ##
MAYA_PLUG_IN_PATH=$MAYA_PLUG_IN_PATH:/home/suesauer/maya/2019/build/RelWithDebInfo/plugin/adsk/plugin:/home/suesauer/maya/2019/build/RelWithDebInfo/plugin/al/plugin:/home/suesauer/maya/2019/build/RelWithDebInfo/plugin/pxr/maya/plugin
MAYA_SCRIPT_PATH=$MAYA_SCRIPT_PATH:/home/suesauer/maya/2019/build/RelWithDebInfo/plugin/adsk/scripts/
XBMLANGPATH=$XBMLANGPATH:/home/suesauer/maya/2019/build/RelWithDebInfo/plugin/pxr/maya/lib/usd/usdMaya/resources:/home/suesauer/maya/2019/build/RelWithDebInfo/plugin/al/plugin/AL_USDMayaPxrTranslators/resources`

Am I doing this right?

Thanks
Sue

**Comment by BigRoy** [comment]
@suekieza the best example for the required environment to run the plug-in is the `.mod` file that is created along with compiling the plug-in. 

In practice that should actually mean that if you set `MAYA_MODULE_PATH` to the path of the directory that contains the valid `.mod` file and then run maya it should work flawlessly.

For completeness sake here's what mine looks like
```
+ USD 0.19.10 D:\dev\usd\build
PYTHONPATH+:=lib/python
PATH+:=bin
PATH+:=lib

+ PXR_USDMAYA 0.19.10 ./plugin/pxr
PYTHONPATH+:=lib/python
PATH+:=maya/lib
XBMLANGPATH+:=maya/lib/usd/usdMaya/resources
MAYA_SCRIPT_PATH+:=maya/lib/usd/usdMaya/resources
MAYA_PLUG_IN_PATH+:=maya/plugin
PXR_PLUGINPATH_NAME+:=lib/usd

+ MayaUSD_LIB 1.0 .
PATH+:=lib
PYTHONPATH+:=lib/python
PXR_PLUGINPATH_NAME+:=lib/usd
VP2_RENDER_DELEGATE_PROXY=1

+ MayaUSD 1.0 ./plugin/adsk
MAYA_PLUG_IN_PATH+:=plugin

+ AL_USDMaya 0.34.2 ./plugin/al
PYTHONPATH+:=lib/python
PATH+:=lib
MAYA_PLUG_IN_PATH+:=plugin
PXR_PLUGINPATH_NAME+:=lib/usd
PXR_PLUGINPATH_NAME+:=plugin
MAYA_WANT_UFE_SELECTION=1

+ MTOH 1.0 ./lib
MAYA_PLUG_IN_PATH+:=maya
```
_Note: I changed the folder paths relative to a `.` which refers to the folder of the `.mod` file._

Be aware that I'm on Windows so paths could differ, but since they are based on the same [`maya-usd/mayaUSD.mod.template`](https://github.com/Autodesk/maya-usd/blob/master/mayaUSD.mod.template) I guess it should be similar. The `.mod` should be in the compiled result in the `install/` folder. Note that you *can* do without the `.mod` file, but then you'd need to be setting all these paths in your environment correctly yourself.

Does that help?

**Comment by suekieza** [comment]
@BigRoy Thanks Roy, will check that out. Great help :D/

**Comment by suekieza** [comment]
Seems to have work exept the mtoh does want to load.

`waitCursor -state on;										 $gIgnoreUpdateCallback = true;loadPluginCmd( "/home/suesauer/Documents/WorkspaceRefractor/install/RelWithDebInfo/lib/maya/mtoh.so"); 		   updatePluginUI( "67" );waitCursor -state off;									   $gIgnoreUpdateCallback = false;
// Error: file: /usr/autodesk/maya/scripts/others/pluginWin.mel line 317: Unable to dynamically load : /home/suesauer/Documents/WorkspaceRefractor/install/RelWithDebInfo/lib/maya/mtoh.so
libhdMaya.so: cannot open shared object file: No such file or directory // 
// Error: file: /usr/autodesk/maya/scripts/others/pluginWin.mel line 317: libhdMaya.so: cannot open shared object file: No such file or directory (mtoh) // 
updatePluginCallback();
// Result: 0 // 
`

**Comment by BigRoy** [comment]
It seems to be missing dependencies. This could be either by the files not being there or your environment variables not having the right paths in it, in this case it might be that you just don't have that file whatsoever.

1. What branch of `maya-usd` did you compile? I believe it'll only be available in the `refactoring_sandbox` branch (and maybe the `dev` branch, but not sure).
2. Can you take a look if the `libhdMaya.so` file is anywhere among your compiled files?

**Comment by suekieza** [comment]
I can see i have it here:
/home/suesauer/Documents/WorkspaceRefractor/install/RelWithDebInfo/lib/libhdMaya.so

how do i check the path variables?

**Comment by BigRoy** [comment]
Ah, then it seems very similar to what I found in [this comment](https://github.com/Autodesk/maya-usd/issues/68#issuecomment-546328596) which seems the Windows equivalent of this issue, that got resolved with #79.

I'll leave it to someone else who probably knows more about this to see if they can help you out with a fix.

**Comment by suekieza** [comment]
Thanks Roy :D

**Comment by BigRoy** [comment]
@HamedSabri-adsk any reason for closing this? Going by the comments I'm not sure @suekieza was able to resolve the problem.

**Comment by HamedSabri-adsk** [comment]
I must have closed it by accident. Sorry about that.

**Comment by HamedSabri-adsk** [comment]
As for the error, The windows fix in #79 doesn't really have anything to do with this error.  I believe we have seen mtoh loading issue on both MacOSx and Linux before. Let me check a few things today and will get back to you on this.

**Comment by HamedSabri-adsk** [comment]
@suekieza I didn't have access to my Linux machine today but managed to fix all the issues with loading `mtoh` on MacOSX and created a PR internally. I also believe the fixes I made should help your problem on Linux. I will try it tomorrow once I am on Linux. 

<img width="1438" alt="mtoh" src="https://user-images.githubusercontent.com/48299423/67903081-1aa55680-fb41-11e9-8e27-b653888e9d27.png">

**Comment by suekieza** [comment]
Thanks, @HamedSabri-adsk will rebuild tomorrow :D/
