### ISSUE TITLE
Maya PR120 usdmaya 0.5.0 plugin does not load

### ISSUE THREAD

**Issue by suesauer** [Autodesk/maya-usd#858]
**Describe the bug**
Maya PR120 usdmaya 0.5.0 plugin does not load in either python3 or python2.

**Steps to reproduce**
1. download new pr120 release 
2.download mayausd 0.5.0 version from release website

run builds on linux centos 7
plugin doesnt load(not the error is the same in both python3 and python2 )
![maya2021error](https://user-images.githubusercontent.com/58251706/96709209-ab9cbf80-139a-11eb-934e-2eb0b5fc6cbe.PNG)

**Expected behavior**
For the Maya plugin to load

**Specs (if applicable):**
 - OS & version Linux CentOS Linux release 7.8.2003 
 - Compiler & version gcc 6.3.1
 - Maya version Maya PR120
 - Maya USD commit MayaUSD-0.5.0-202010160126-e1f62f2-maya-2021

**Comment by kxl-adsk** [comment]
On Github, we are posting binaries for Maya 2020 (Update 2 and 3). For beta releases of Maya (like PR120), please refer to instructions on the beta forum and post questions over there.

**Comment by santosg87** [comment]
hi @suesauer  if you run maya with the env var "MAYA_PYTHON_VERSION=2", does this still happen for you?

**Comment by santosg87** [comment]
thank you for posting this!

Looks like we had issues during the posting process. could you download the installer again and see if the problem persists?

cheers!

**Comment by suesauer** [comment]
Will do, thanks for the help. Sorry for posting in wrong place

**Comment by suesauer** [comment]
Fixed 👍
