### ISSUE TITLE
[MAYA-109886] Viewport highlighting does not work as expected for invisible instances

### ISSUE THREAD

**Issue by csyshing** [Autodesk/maya-usd#900]
**Describe the bug**

Hi,

We noticed that highlighting in may-usd **UFE mode** does not work as expected for invisible instances, I have attached an example USD file to reproduce the problem.

The `assembly.usda` file contains 5 instances, on viewport from top to bottom are `ball_01`, `ball_02`, `ball_03`, `ball_04` and `ball_05`; the second instance, `ball_02` has been set to be **invisible** on purpose so it does not show up on viewport.

The first image is a test with **maya-usd v0.5.0 (UFE build)** with **USD 19.11**, those 6 sub images (labeled in the red font) are:
 - **1** Select the first instance, `ball_01`, both manipulator and highlighting are correct;
 - **2** Select the second instance, `ball_02`, which has been set to be **invisible** in USD, there should be no highlighting, but `ball_03` is highlighting instead;
 - **3** Select the "ball_03", the manipulator seems correct, but highlighting is on "ball_04" which is wrong;
 - **4** Select the last instance, the highlighting is gone;
 - **5** and **6**: Once the highlighting is broken, it stops working and no way get highlighting back again

![maya-usd-v0 5 0_USD-19 11_incorrect_highlighting](https://user-images.githubusercontent.com/1593576/98329496-75bf3280-204c-11eb-8fc8-f7eef5b3ecdd.png)

The second image (with 4 sub images) is a test with **maya-usd v0.5.0 (UFE build)** with **USD 20.11**, selection and highlighting seem getting *better* but it's still **incorrect** if the instance is **invisible**, selecting `ball_02` causes highlighting all the instances.

![maya-usd-v0 5 0_USD-20 11_incorrect_highlighting](https://user-images.githubusercontent.com/1593576/98329563-9ab3a580-204c-11eb-9f8c-f340f3a9f56b.png)

**Steps to reproduce**
1. Load mayaUsd plugin and load attached usd file, "assembly.usda"
2. Select prim either from outliner or from viewport
3. Notice the highlighting behaviors differently on visible / invisible prim

**Attachments**
[assembly_and_ball_usd_files.zip](https://github.com/Autodesk/maya-usd/files/5499283/assembly_and_ball_usd_files.zip)

**Specs (if applicable):**
 - OS & version: Centos 7.4
 - Compiler & version : gcc 6.3.1
 - Maya version: Maya 2020
 - Maya USD commit SHA: v0.5.0  [dev at 62037f3] **UFE build**
 - Pixar USD: official tagged version 19.11 and 20.11

**Comment by HdC-adsk** [comment]
This is a bug of VP2RenderDelegate. It doesn't check visibility of each instance when highlighting selected items, while the regular scene items are being drawn with an instance matrix array that only contains visible instances, in this scene it will be like:

|xform_01|xform_03|xform_04|xform_05|

So when VP2RenderDelegate wants to highlight the second instance, it highlights the second entry in the above array.

**Comment by HdC-adsk** [comment]
The relevant code area is at 
https://github.com/Autodesk/maya-usd/blob/dev/lib/mayaUsd/render/vp2RenderDelegate/mesh.cpp#L1363

We will probably need to maintain a visibility array for all the instances, so we can skip hidden instances for updating the selection highlight item.

The same issue should present in the basisCurves implementation as well, so the fix will need to include both Rprims.

**Comment by fabal** [comment]
Thanks @HdC-adsk . Is it something you've planned to implement soonish?

**Comment by kxl-adsk** [comment]
@fabal Currently, our main focus around VP2RenderDelegate is on features that require changes in Maya. The highlighting defect described here requires only changes to the plugin. This may not be the answer you were looking for, but we can provide more guidance if you are willing to contribute a fix.

**Comment by williamkrick** [comment]
In USD 20.11 and later I believe there is a defect in USD which is causing all the instances to be drawn selected. I've logged that at https://github.com/PixarAnimationStudios/USD/issues/1461.

In USD 20.08 and earlier there is a defect in Vp2RenderDelegate which causes the wrong instance to be drawn selected. I am working on a solution for this. I believe the fix will be necessary when the bug in newer versions of USD is resolved.

**Comment by williamkrick** [comment]
@csyshing is it okay if we use a lightly modified version of assembly_and_ball_usd_files as a part of our public MayaUSD tests? The files will show up in MayaUSD/test/testSamples.

**Comment by csyshing** [comment]
Yes @williamkrick , totally fine by me.

**Comment by santosd** [comment]
This has been addressed and will be resolved in the next release. Closing the issue for now. Please give it a try in the next release and confirm.
