### ISSUE TITLE
[MAYA-103692] mayaUsdProxyShape primPath mask not working

### ISSUE THREAD

**Issue by ndeebook** [Autodesk/maya-usd#901]
**Describe the bug**
`mayaUsdProxyShape.primPath` has no effect

**Steps to reproduce**
```
proxy = maya.cmds.createNode('mayaUsdProxyShape')
maya.cmds.setAttr(proxy + '.filePath', 'Kitchen_set.usd', type='string')
maya.cmds.setAttr(proxy + '.primPath', '/Kitchen_set/Props_grp/West_grp', type='string')
```

**Expected behavior**
Expecting same effect as when using `mask` argument with usdview:
`usdview Kitchen_set.usd --mask /Kitchen_set/Props_grp/West_grp`

**Attachments**
![image](https://user-images.githubusercontent.com/8027693/98371662-d21a5600-203c-11eb-9e8e-7e14650a6132.png)

**Specs:**
 - Windows 10 1909
 - Visual Studio 2017
 - Maya 2020.3
 - Maya USD v0.5.0
 - Pixar USD v20.11

**Comment by ndeebook** [comment]
If anybody lands here, I just found out about this video which explains other ways to do this:
https://youtu.be/6EqcwefKMRI?t=738

**Comment by santosd** [comment]
Hello @ndeebook ,
Thank you for reporting this to us. The issue is logged internally and at this point has not been resolved. We will report back when things change in regards to that issue.
Cheers,
David Santos

**Comment by ndeebook** [comment]
Ok thanks.
Then I guess you know that `complexity` is also broken.
