### ISSUE TITLE
Windows build failed on building shadingModeRegistry.cpp.obj

### ISSUE THREAD

**Issue by HXhester** [Autodesk/maya-usd#909]
**Describe the issue**
When build with the command below:
"python D:\Pixar\maya-usd\build.py --generator Ninja --maya-location="D:\Autodesk\Autodesk_Maya_2019_dlm\Maya2019" --pxrusd-location="C:\USD_BuildWith2015" --devkit-location=" C:\Users\hanxu.11\devkitBase" D:\Autodesk\MayaPlugins --build-args="-DBUILD_WITH_PYTHON_3=ON,-DCMAKE_MAKE_PROGRAM='C:\ninja.exe'""

it reports 
"D:\Pixar\maya-usd\lib\mayaUsd\fileio\shading\shadingModeRegistry.cpp(219): note: No constructor could take the source type, or constructor overload resolution was ambiguous
[19/478] Building CXX object lib\mayaUsd\CMakeFiles\mayaUsd.dir\fileio\shading\shadingModeImporter.cpp.obj
[20/478] Building CXX object lib\mayaUsd\CMakeFiles\mayaUsd.dir\fileio\shading\shadingModeExporterContext.cpp.obj
[21/478] Building CXX object lib\mayaUsd\CMakeFiles\mayaUsd.dir\fileio\shading\shadingModeExporter.cpp.obj
[22/478] Building CXX object lib\mayaUsd\CMakeFiles\mayaUsd.dir\fileio\shading\symmetricShaderWriter.cpp.obj
[23/478] Building CXX object lib\mayaUsd\CMakeFiles\mayaUsd.dir\fileio\shading\shadingModeUseRegistry.cpp.obj
[24/478] Building CXX object lib\mayaUsd\CMakeFiles\mayaUsd.dir\fileio\jobs\readJob.cpp.obj
[25/478] Building CXX object lib\mayaUsd\CMakeFiles\mayaUsd.dir\fileio\shading\shadingModePxrRis.cpp.obj
ninja: build stopped: subcommand failed."

**Build log**
build_log.txt is attached below.

**Specs:**
 - OS : Windows 10
 - CMake 3.16.5, Ninja v1.10.1
 - Maya version: Maya 2019
 - Maya USD commit SHA: tag v0.5.0, master 9d931cb70
 - Pixar USD commit SHA: tag v20.11

[build_log.txt](https://github.com/Autodesk/maya-usd/files/5514922/build_log.txt)

**Comment by HXhester** [comment]
Have changed to Maya 2020 with the latest maya-usd release.

**Comment by kxl-adsk** [comment]
Before a pull-request is merged, we always compile with different combinations of Maya and USD versions, including Maya 2019. I'm wondering if the if the difference is coming from VS version, since we are using VS 2017 for this test.

Additionally, I noticed you are building with python3 support, but Maya 2019 has no support for python 3. Not something I tried, but I would expect at minimum runtime failures.

Anyhow, glad that you got unblocked.

**Comment by HXhester** [comment]
@kxl-adsk Thank you for explaining! The released build is really handy! 

I got a followup question. I managed to export usd with the following settings, but after I imported usd into Unity, even if I set St to Import, the texture mapping was still wrong. Is there any more settings I'm missing? Or do I still need to build pxrUsd.mll to be able to use the full functionality? Or it can be a Unity plugin issue?
![image](https://user-images.githubusercontent.com/16118741/98783942-4c7c1900-2435-11eb-93a9-43686629324a.png)
![image](https://user-images.githubusercontent.com/16118741/98784591-518d9800-2436-11eb-8317-caf6e1081d8f.png)

**Comment by kxl-adsk** [comment]
Re building pxrUsd plugin - there is absolutely no difference when it comes to import / export support between the two plugins. Both Autodesk and Pixar are sharing the same core translation framework and translators.

Re import to unity - would you mind starting a conversation in https://github.com/Autodesk/maya-usd/discussions?
