### ISSUE TITLE
No module named UsdMaya

### ISSUE THREAD

**Issue by efleurant** [Autodesk/maya-usd#910]
**Describe the bug**
Built maya-usd 0.5.0 using Pixar USD 20.11 uneventfully, but I get an error when trying to load `pxrUsd.so` plugin in Maya 2020:
```
# Error: file: /prod/software/centos7/autodesk/maya/2020.2/scripts/others/pluginWin.mel line 317: ImportError: file <maya console> line 1: No module named UsdMaya # 
// Error: file: /prod/software/centos7/autodesk/maya/2020.2/scripts/others/pluginWin.mel line 317: initializePlugin function failed (pxrUsd) // 
```
I have set `MAYA_MODULE_PATH` correctly to where the `mayaUSD.mod` and `pxrUSD.mod` files reside and this is what it seems to have populatedin my `PYTHONPATH` : 
```
/software/centos7/USD/20.11/lib/python
/software/centos7/autodesk/maya/plug-ins/maya-usd/0.5.0/2020/plugin/adsk/scripts
/software/centos7/autodesk/maya/plug-ins/maya-usd/0.5.0/2020/plugin/pxr/maya/lib/usd/usdMaya/resources
/software/centos7/autodesk/maya/plug-ins/maya-usd/0.5.0/2020/lib/python
/software/centos7/autodesk/maya/plug-ins/maya-usd/0.5.0/2020/plugin/pxr/lib/python
```
The `UsdMaya` module seems to be located somewhere inside the last path listed above, so I'm really out of ideas here... no idea why it's not loading.

`mayaUsdPlugin.so` and `pxrUsdPreviewSurface.so` loads without any errors though. Also no crash when trying to import other modules belonging to `pxr` when in Maya. FYI, I did not build the animal logic plugin.

**Expected behavior**
Plugin should load.

**Specs**
 - CentOS 7.5
 - gcc 6.3.1
 - Maya 2020.2
 - maya-usd 0.5.0
 - Pixar USD 20.11

Would really appreciate a helping hand here,
Cheers

**Comment by kxl-adsk** [comment]
@efleurant please share with us your build log. As well, I will convert this issue to a discussion, since at this point there isn't anything we can act on.

**Comment by efleurant** [comment]
Here's a [verbose log](https://gist.github.com/efleurant/752900bf62d773ab365af4911b6b065b) of my build.

Now I have noticed that the doc is encouraging to use Ninja as the cmake generator... could that be a problem down the road if I didn't use that?

Let me know if there's something you can see from the build log, but like I said in my preview post, I think I have everything specified in my `PYTHONPATH`... or what could be missing?

**Comment by HamedSabri-adsk** [comment]
> Here's a verbose log of my build.

There is a `build_log.txt` that is created inside the build directory which provides more info. Can you please share that instead?

> Now I have noticed that the doc is encouraging to use Ninja as the cmake generator... could that be a problem down the road if I didn't use that?

Using Ninja is recommended but it is not forced and shouldn't be a problem if you don't want to use it.

**Comment by efleurant** [comment]
I have found why this was happening on our side. It seems to be the order in which we were adding the paths to our `PYTHONPATH`.

We were adding the python libs of our USD python install `.../USD/20.11/lib/python` in `PYTHONPATH` and then declaring `MAYA_MODULE_PATH` in `.../autodesk/maya/plug-ins/maya-usd/0.5.0/2020`. It looks like Maya was then appending what it found in it's `.mod` file in such an order that it wasn't detecting what was in the USD python install folder. So to work around that, we have decided to not specify the USD python install in `PYTHONPATH` and let maya `.mod` files to do the job.

Closing

**Comment by wangluo2028** [comment]
I have encountered the same problem.

**Comment by seando-adsk** [comment]
@wangluo2028 Sorry I don't quite understand your question. The .mod file that we configure and install as part of the build does add (by appending) USD to the PYTHONPATH. You can see that [here](https://github.com/Autodesk/maya-usd/blob/dev/modules/mayaUSD.mod.template#L7). The problem is if you have another USD installed on your machine and in your PATH/PYTHONPATH it will be found first (before the one MayaUsd was built with).

Sean
