### ISSUE TITLE
Make it easier to run clang-format

### ISSUE THREAD

**Issue by pmolodo** [Autodesk/maya-usd#916]
**Is your feature request related to a problem? Please describe.**
I've noticed that since the "[big format](https://github.com/Autodesk/maya-usd/pull/890)", we've already had some non-clang-formatted files slip in.  While this isn't a big issue by itself, I do worry that over time this will build up, and we'll need to do another "big format."

**Describe the solution you'd like**
We need ways to make it easier to apply clang-format.  At minimum, we should probably provide basic shell scripts which can run clang-format on the repo.  https://github.com/Autodesk/maya-usd/pull/890 already gives instructions for Linux + OSX, so really all we'd need to do would be come up with a windows script, and then place them into binaries somewhere in the repo.

However, that would be a small band-aid.  Really, we want a way to run clang-format in an automated fashion, on github.  Looking around, I found this neat approach which uses commands given in PR comments:

https://github.com/peter-evans/slash-command-dispatch/pull/11
https://peterevans.dev/posts/chatops-for-github-actions/
https://github.com/peter-evans/slash-command-dispatch

The same author also describes a previous approach he took using github actions:

https://peterevans.dev/posts/github-actions-how-to-automate-code-formatting-in-pull-requests/

I'm sure there's other ways to accomplish this, but wanted to get the conversation started...

**Comment by kxl-adsk** [comment]
We have enabled clang-format lint action on the repository. Every time we run PF, we also run a clang-format check to validate if the formatting was applied.
