### ISSUE TITLE
Multiple Animated AL_usdmaya_Transforms Crash Maya in EM Mode

### ISSUE THREAD

**Issue by cfmoore007** [Autodesk/maya-usd#93]
**Issue :**

We ran into 2 scenarios, where the EM evaluates several of the same AL_usdmaya_Transform nodes at the same time, which in tern sends updates or 'writes' to the AL_usdmaya_proxyShape's session layer ... also at the same time.  USD does not like this.

Our work-around is to set the AL_usdmaya_Transform nodes to kGloballySerial ( in plugin/al/lib/AL_USDMaya/AL/usdmaya/nodes/Transform.h) , but we're wondering if there's a different way.    We are willing to submit a PR for it, but we're concerned over scalability ( or lack thereof ) of this approach.  As more keyed AL_usdmaya_Transform nodes are added, so does the evaluation time.

**Error / Crash :**
Detected usd threading violation.  Concurrent changes to layer(s) composed in stage 0x16241710 rooted at @3_Spheres.usda@.  (serial=435, lastSerial=436). -- Coding Error in _HandleLayersDidChange at line 3564 of src/USD/pxr/usd/lib/usd/stage.cpp
Detected usd threading violation.  Concurrent changes to layer(s) composed in stage 0x16241710 rooted at @3_Spheres.usda@.  (serial=530, lastSerial=531). -- Coding Error in _HandleLayersDidChange at line 3564 of src/USD/pxr/usd/lib/usd/stage.cpp
Detected usd threading violation.  Concurrent changes to layer(s) composed in stage 0x16241710 rooted at @3_Spheres.usda@.  (serial=675, lastSerial=676). -- Coding Error in _HandleLayersDidChange at line 3564 of src/USD/pxr/usd/lib/usd/stage.cpp

**( crash )**

**Steps to re-produce :**

1. cmds.AL_usdmaya_ProxyShapeImport(file="3_Spheres.usda")
2. cmds.AL_usdmaya_ProxyShapeImportAllTransforms("AL_usdmaya_Proxy", p2p=True)
3. make 3 locators
4. wire up parent constraint between locators and spheres
5. key frame locators
6. playback
**5. crash**

or 

1. cmds.AL_usdmaya_ProxyShapeImport(file="3_Spheres.usda")
2. cmds.AL_usdmaya_ProxyShapeImportAllTransforms("AL_usdmaya_Proxy", p2p=True)
3. key frame sphere AL_usdmaya_Transform nodes ( 2 offset keys )
4. playback
**5. crash**

[3_Spheres.zip](https://github.com/Autodesk/maya-usd/files/3791620/3_Spheres.zip)

**Comment by cfmoore007** [comment]
Here was the maya stack trace :

`Detected usd threading violation.  Concurrent changes to layer(s) composed in stage 0x195c1d90 rooted at @/p/heart:scene:sq1060:sc01SecurityRoom-scene/scene.usda@.  (serial=592, lastSerial=593). -- Coding Error in _HandleLayersDidChange at line 3564 of USD-19.10.bss.0/build/base_platform-maya2019-dist-up2.1.bss0/USD-prefix/src/USD/pxr/usd/lib/usd/stage.cpp
Detected usd threading violation.  Concurrent changes to layer(s) composed in stage 0x195c1d90 rooted at @/p/heart:scene:sq1060:sc01SecurityRoom-scene/scene.usda@.  (serial=3871, lastSerial=3872). -- Coding Error in _HandleLayersDidChange at line 3564 of USD-19.10.bss.0/build/base_platform-maya2019-dist-up2.1.bss0/USD-prefix/src/USD/pxr/usd/lib/usd/stage.cpp
Detected usd threading violation.  Concurrent changes to layer(s) composed in stage 0x195c1d90 rooted at @/p/heart:scene:sq1060:sc01SecurityRoom-scene/scene.usda@.  (serial=6287, lastSerial=6288). -- Coding Error in _HandleLayersDidChange at line 3564 of USD-19.10.bss.0/build/base_platform-maya2019-dist-up2.1.bss0/USD-prefix/src/USD/pxr/usd/lib/usd/stage.cpp
Detected usd threading violation.  Concurrent changes to layer(s) composed in stage 0x195c1d90 rooted at @/p/heart:scene:sq1060:sc01SecurityRoom-scene/scene.usda@.  (serial=7221, lastSerial=7222). -- Coding Error in _HandleLayersDidChange at line 3564 of USD-19.10.bss.0/build/base_platform-maya2019-dist-up2.1.bss0/USD-prefix/src/USD/pxr/usd/lib/usd/stage.cpp
Detected usd threading violation.  Concurrent changes to layer(s) composed in stage 0x195c1d90 rooted at @/p/heart:scene:sq1060:sc01SecurityRoom-scene/scene.usda@.  (serial=7351, lastSerial=7358). -- Coding Error in _HandleLayersDidChange at line 3564 of USD-19.10.bss.0/build/base_platform-maya2019-dist-up2.1.bss0/USD-prefix/src/USD/pxr/usd/lib/usd/stage.cpp
Detected usd threading violation.  Concurrent changes to layer(s) composed in stage 0x195c1d90 rooted at @/p/heart:scene:sq1060:sc01SecurityRoom-scene/scene.usda@.  (serial=8124, lastSerial=8125). -- Coding Error in _HandleLayersDidChange at line 3564 of USD-19.10.bss.0/build/base_platform-maya2019-dist-up2.1.bss0/USD-prefix/src/USD/pxr/usd/lib/usd/stage.cpp
Detected usd threading violation.  Concurrent changes to layer(s) composed in stage 0x195c1d90 rooted at @/p/heart:scene:sq1060:sc01SecurityRoom-scene/scene.usda@.  (serial=9759, lastSerial=9760). -- Coding Error in _HandleLayersDidChange at line 3564 of USD-19.10.bss.0/build/base_platform-maya2019-dist-up2.1.bss0/USD-prefix/src/USD/pxr/usd/lib/usd/stage.cpp
Detected usd threading violation.  Concurrent changes to layer(s) composed in stage 0x195c1d90 rooted at @/p/heart:scene:sq1060:sc01SecurityRoom-scene/scene.usda@.  (serial=10189, lastSerial=10190). -- Coding Error in _HandleLayersDidChange at line 3564 of USD-19.10.bss.0/build/base_platform-maya2019-dist-up2.1.bss0/USD-prefix/src/USD/pxr/usd/lib/usd/stage.cpp
Detected usd threading violation.  Concurrent changes to layer(s) composed in stage 0x195c1d90 rooted at @/p/heart:scene:sq1060:sc01SecurityRoom-scene/scene.usda@.  (serial=10950, lastSerial=10951). -- Coding Error in _HandleLayersDidChange at line 3564 of USD-19.10.bss.0/build/base_platform-maya2019-dist-up2.1.bss0/USD-prefix/src/USD/pxr/usd/lib/usd/stage.cpp
Detected usd threading violation.  Concurrent changes to layer(s) composed in stage 0x195c1d90 rooted at @/p/heart:scene:sq1060:sc01SecurityRoom-scene/scene.usda@.  (serial=12893, lastSerial=12894). -- Coding Error in _HandleLayersDidChange at line 3564 of USD-19.10.bss.0/build/base_platform-maya2019-dist-up2.1.bss0/USD-prefix/src/USD/pxr/usd/lib/usd/stage.cpp
Detected usd threading violation.  Concurrent changes to layer(s) composed in stage 0x195c1d90 rooted at @/p/heart:scene:sq1060:sc01SecurityRoom-scene/scene.usda@.  (serial=15047, lastSerial=15048). -- Coding Error in _HandleLayersDidChange at line 3564 of USD-19.10.bss.0/build/base_platform-maya2019-dist-up2.1.bss0/USD-prefix/src/USD/pxr/usd/lib/usd/stage.cpp
*** Error in `<maya2019.2>/bin/maya.bin': double free or corruption (fasttop): 0x00007ff17834eda0 ***
======= Backtrace: =========
/lib64/libc.so.6(+0x81489)[0x7ff368e73489]
USD-19.10.bss.0/plugin/al/lib/libAL_USDMaya.so(_ZNSt8_Rb_treeIN32pxrInternal_v0_19__pxrReserved__11UsdTimeCodeESt4pairIKS1_N8Autodesk4Maya16OpenMaya2019000012MBoundingBoxEESt10_Select1stIS8_ESt4lessIS1_ESaIS8_EE8_M_eraseEPSt13_Rb_tree_nodeIS8_E+0x1f0)[0x7ff253cbc7d0]
USD-19.10.bss.0/plugin/al/lib/libAL_USDMaya.so(_ZN2AL7usdmaya5nodes10ProxyShape16onObjectsChangedERKN32pxrInternal_v0_19__pxrReserved__9UsdNotice14ObjectsChangedERKNS3_9TfWeakPtrINS3_8UsdStageEEE+0x1cc)[0x7ff253d6c27c]
USD-19.10.bss.0/plugin/al/lib/libAL_USDMaya.so(_ZN32pxrInternal_v0_19__pxrReserved__8TfNotice18_StandardDelivererINS0_20_DelivererWithSenderINS_9TfWeakPtrIN2AL7usdmaya5nodes10ProxyShapeEEENS3_INS_8UsdStageEEEMS7_FvRKNS_9UsdNotice14ObjectsChangedERKSA_ESC_EEE15_SendToListenerERKS0_RKNS_6TfTypeEPKNS_10TfWeakBaseEPKvRKSt9type_infoRKSt6vectorINS3_INS0_5ProbeEEESaIS10_EE+0xde)[0x7ff253d7571e]
<maya2019.2>/lib/python/pxr/UsdUtils/../../../libtf.so(_ZN32pxrInternal_v0_19__pxrReserved__17Tf_NoticeRegistry8_DeliverERKNS_8TfNoticeERKNS_6TfTypeEPKNS_10TfWeakBaseEPKvRKSt9type_infoRKSt6vectorINS_9TfWeakPtrINS1_5ProbeEEESaISI_EERKSt4pairIPSt4listIPNS1_14_DelivererBaseESaISQ_EESt14_List_iteratorISQ_EE+0x1b6)[0x7ff2d800c866]
<maya2019.2>/lib/python/pxr/UsdUtils/../../../libtf.so(_ZN32pxrInternal_v0_19__pxrReserved__17Tf_NoticeRegistry5_SendERKNS_8TfNoticeERKNS_6TfTypeEPKNS_10TfWeakBaseEPKvRKSt9type_info+0x516)[0x7ff2d800cf06]
<maya2019.2>/lib/python/pxr/UsdUtils/../../../libtf.so(_ZNK32pxrInternal_v0_19__pxrReserved__8TfNotice5_SendEPKNS_10TfWeakBaseEPKvRKSt9type_info+0x4f)[0x7ff2d8048d2f]
<maya2019.2>/lib/python/pxr/UsdUtils/../../../libusd.so(_ZN32pxrInternal_v0_19__pxrReserved__8UsdStage22_HandleLayersDidChangeERKNS_9SdfNotice27LayersDidChangeSentPerLayerE+0x566)[0x7ff2da51da66]
<maya2019.2>/lib/python/pxr/UsdUtils/../../../libusd.so(_ZN32pxrInternal_v0_19__pxrReserved__8TfNotice18_StandardDelivererINS0_10_DelivererINS_9TfWeakPtrINS_8UsdStageEEENS3_INS_8SdfLayerEEEMS4_FvRKNS_9SdfNotice27LayersDidChangeSentPerLayerEES9_EEE15_SendToListenerERKS0_RKNS_6TfTypeEPKNS_10TfWeakBaseEPKvRKSt9type_infoRKSt6vectorINS3_INS0_5ProbeEEESaISV_EE+0x6e)[0x7ff2da535b5e]
<maya2019.2>/lib/python/pxr/UsdUtils/../../../libtf.so(_ZN32pxrInternal_v0_19__pxrReserved__17Tf_NoticeRegistry8_DeliverERKNS_8TfNoticeERKNS_6TfTypeEPKNS_10TfWeakBaseEPKvRKSt9type_infoRKSt6vectorINS_9TfWeakPtrINS1_5ProbeEEESaISI_EERKSt4pairIPSt4listIPNS1_14_DelivererBaseESaISQ_EESt14_List_iteratorISQ_EE+0x1b6)[0x7ff2d800c866]
<maya2019.2>/lib/python/pxr/UsdUtils/../../../libtf.so(_ZN32pxrInternal_v0_19__pxrReserved__17Tf_NoticeRegistry5_SendERKNS_8TfNoticeERKNS_6TfTypeEPKNS_10TfWeakBaseEPKvRKSt9type_info+0x6c2)[0x7ff2d800d0b2]
<maya2019.2>/lib/python/pxr/UsdUtils/../../../libtf.so(_ZNK32pxrInternal_v0_19__pxrReserved__8TfNotice5_SendEPKNS_10TfWeakBaseEPKvRKSt9type_info+0x4f)[0x7ff2d8048d2f]
<maya2019.2>/lib/python/pxr/UsdUtils/../../../libsdf.so(_ZN32pxrInternal_v0_19__pxrReserved__17Sdf_ChangeManager12_SendNoticesEv+0xd2c)[0x7ff2d974231c]
<maya2019.2>/lib/python/pxr/UsdUtils/../../../libsdf.so(_ZN32pxrInternal_v0_19__pxrReserved__17Sdf_ChangeManager16CloseChangeBlockEv+0x56)[0x7ff2d9742786]
<maya2019.2>/lib/python/pxr/UsdUtils/../../../libsdf.so(_ZN32pxrInternal_v0_19__pxrReserved__8SdfLayer13_PrimSetFieldINS_25SdfAbstractDataConstValueEEEvRKNS_21SdfAbstractDataSpecIdERKNS_7TfTokenERKT_PKNS_7VtValueEb+0x66)[0x7ff2d9844d36]
<maya2019.2>/lib/python/pxr/UsdUtils/../../../libsdf.so(_ZN32pxrInternal_v0_19__pxrReserved__8SdfLayer8SetFieldERKNS_21SdfAbstractDataSpecIdERKNS_7TfTokenERKNS_25SdfAbstractDataConstValueE+0x1a2)[0x7ff2d98381c2]
<maya2019.2>/lib/python/pxr/UsdUtils/../../../libusd.so(_ZN32pxrInternal_v0_19__pxrReserved__8UsdStage13_SetValueImplINS_25SdfAbstractDataConstValueEEEbNS_11UsdTimeCodeERKNS_12UsdAttributeERKT_+0x43e)[0x7ff2da54880e]
USD-19.10.bss.0/plugin/al/lib/libAL_USDMaya.so(_ZNK32pxrInternal_v0_19__pxrReserved__14UsdGeomXformOp3SetINS_7GfVec3fEEEbRKT_NS_11UsdTimeCodeE+0xe2)[0x7ff253d29762]
USD-19.10.bss.0/plugin/al/lib/libAL_USDMaya.so(_ZN2AL7usdmaya5nodes20TransformationMatrix10pushVectorERKN8Autodesk4Maya16OpenMaya201900007MVectorERN32pxrInternal_v0_19__pxrReserved__14UsdGeomXformOpENS9_11UsdTimeCodeE+0x49b)[0x7ff253d9709b]
USD-19.10.bss.0/plugin/al/lib/libAL_USDMaya.so(_ZN2AL7usdmaya5nodes20TransformationMatrix12pushRotationERKN8Autodesk4Maya16OpenMaya2019000014MEulerRotationERN32pxrInternal_v0_19__pxrReserved__14UsdGeomXformOpENS9_11UsdTimeCodeE+0x11c)[0x7ff253d993dc]
USD-19.10.bss.0/plugin/al/lib/libAL_USDMaya.so(_ZN2AL7usdmaya5nodes20TransformationMatrix16pushRotateToPrimEv+0x9e)[0x7ff253d994fe]
USD-19.10.bss.0/plugin/al/lib/libAL_USDMaya.so(_ZN2AL7usdmaya5nodes20TransformationMatrix8rotateToERKN8Autodesk4Maya16OpenMaya2019000014MEulerRotationENS5_6MSpace5SpaceE+0x134)[0x7ff253d9e8a4]
<maya2019.2>/lib/libOpenMaya.so(_ZN8Autodesk4Maya16OpenMaya2019000012MPxTransform19checkAndSetRotationERNS1_10MDataBlockERKNS1_5MPlugERKNS1_14MEulerRotationENS1_6MSpace5SpaceE+0x395)[0x7ff324dc5705]
<maya2019.2>/lib/libOpenMaya.so(_ZN8Autodesk4Maya16OpenMaya2019000012MPxTransform19validateAndSetValueERKNS1_5MPlugERKNS1_11MDataHandleERKNS1_10MDGContextE+0x665)[0x7ff324dd0c05]
USD-19.10.bss.0/plugin/al/lib/libAL_USDMaya.so(_ZN2AL7usdmaya5nodes9Transform19validateAndSetValueERKN8Autodesk4Maya16OpenMaya201900005MPlugERKNS5_11MDataHandleERKNS5_10MDGContextE+0xae2)[0x7ff253d94702]
<maya2019.2>/lib/libOpenMaya.so(_ZN8Autodesk4Maya16OpenMaya2019000012MPxTransform19validateAndSetValueERKNS1_5MPlugERKNS1_11MDataHandleE+0x41)[0x7ff324dbfa01]
<maya2019.2>/lib/libOpenMaya.so(+0x3806d0)[0x7ff324dda6d0]
<maya2019.2>/lib/libDependEngine.so(_ZNK5Tplug8setValueERK11TdataHandleRK10TdgContext+0x4d)[0x7ff37756d1dd]
<maya2019.2>/lib/libDependEngine.so(_ZNK5Tplug18getConnectionValueEbRK10TdgContextR11TdataHandle+0x12a)[0x7ff37757a39a]
<maya2019.2>/lib/libDependEngine.so(_ZNK5Tplug8getValueER11TdataHandleRK10TdataBlockbbb+0x45f)[0x7ff37757abef]
<maya2019.2>/lib/libDependEngine.so(_ZNK5Tplug8getValueER11TdataHandleRK10TdataBlockbbb+0x586)[0x7ff37757ad16]
<maya2019.2>/lib/libDependEngine.so(_ZNK5Tplug8getValueER11TdataHandleRK10TdgContext+0x85)[0x7ff37757b9c5]
<maya2019.2>/lib/libDependEngine.so(_ZN11TdependNode12getPlugValueERK5TplugR11TdataHandleRK10TdgContext+0xd6)[0x7ff3776bcbe6]
<maya2019.2>/lib/libDependEngine.so(_ZN11TdependNode14processMessageER4Tmsg+0x1f6)[0x7ff3776c2fe6]
<maya2019.2>/lib/libDataModel.so(_ZN10TdagObject14processMessageER4Tmsg+0x82c)[0x7ff3756f483c]
<maya2019.2>/lib/libDependEngine.so(_ZN13TmsgPlugValue4sendEv+0x17)[0x7ff377682b27]
<maya2019.2>/lib/libDataModel.so(_ZN10TdagObject24doLazyEvalDirtyAttributeERK10Tattribute+0x103)[0x7ff3756ea2d3]
<maya2019.2>/lib/libDataModel.so(_ZN10Ttransform23evaluateXformAttributesEv+0x284)[0x7ff3757bac74]
<maya2019.2>/lib/libOpenMaya.so(+0x384e74)[0x7ff324ddee74]
<maya2019.2>/lib/libDataModel.so(_ZNK10Ttransform10pathMatrixEb+0x325)[0x7ff3757bbf95]
<maya2019.2>/lib/libDataModel.so(_ZNK8TdagPath15inclusiveMatrixEv+0x53)[0x7ff375782e23]
<maya2019.2>/lib/libDataModel.so(_ZN10TdagObject16putMatrixInBlockER10TdataBlockR11TdataHandlePK10TattributeR8TdagPathMS7_KF12T4dDblMatrixvE+0x41)[0x7ff3756e1fe1]
<maya2019.2>/lib/libDataModel.so(_ZN10TdagObject11computePlugERK5TplugR10TdataBlock+0x2a0)[0x7ff3756eed60]
<maya2019.2>/lib/libDataModel.so(_ZN10Ttransform11computePlugERK5TplugR10TdataBlock+0x17e)[0x7ff3757b345e]
<maya2019.2>/lib/libOpenMaya.so(+0x383446)[0x7ff324ddd446]
<maya2019.2>/lib/libDependEngine.so(_ZN15TevaluationNode18evaluateDirtyPlugsEP12TdataBlockDGNS_14TdirtyPlugTypeE+0x618)[0x7ff377629eb8]
<maya2019.2>/lib/libDependEngine.so(_ZN15TevaluationNode14taskEvaluationERK12TsyncMessage+0x272)[0x7ff37762a9b2]
<maya2019.2>/lib/libDependEngine.so(_ZN33TevaluationTransparentClusterNode20taskEvaluationOpaqueERK12TsyncMessage+0x13c)[0x7ff3776394ac]
<maya2019.2>/lib/libtbb.so.2(_ZNK3tbb10interface78internal15task_arena_base16internal_executeERNS1_13delegate_baseE+0x1ed)[0x7ff36a627a8d]
<maya2019.2>/lib/libDependEngine.so(_ZN15TschedulingNode14task_body_leafIN33TevaluationTransparentClusterNode4TaskEEclERK12TsyncMessage+0x62)[0x7ff3776399b2]
<maya2019.2>/lib/libDependEngine.so(+0x24e0ee)[0x7ff37763b0ee]
<maya2019.2>/lib/libtbb.so.2(+0x286c9)[0x7ff36a62c6c9]
<maya2019.2>/lib/libtbb.so.2(+0x2306e)[0x7ff36a62706e]
<maya2019.2>/lib/libtbb.so.2(+0x20ecf)[0x7ff36a624ecf]
<maya2019.2>/lib/libtbb.so.2(+0x1c5f6)[0x7ff36a6205f6]
<maya2019.2>/lib/libtbb.so.2(+0x1c586)[0x7ff36a620586]
/lib64/libpthread.so.0(+0x7dd5)[0x7ff3691c6dd5]
/lib64/libc.so.6(clone+0x6d)[0x7ff368eefead]`

**Comment by vlasovi** [comment]
@cfmoore007 I'm wondering if this issue is still valid for you, or if we can close it?

**Comment by cfmoore007** [comment]
This is no longer required.
