### ISSUE TITLE
IBL Support for USD Preview Surface Shader

### ISSUE THREAD

**Issue by dgovil** [Autodesk/maya-usd#933]
**Is your feature request related to a problem? Please describe.**
The current USD Preview Surface shader doesn't allow for IBL's to contribute to the look of things with lighting and reflection.
This makes it somewhat cumbersome to accurately assess what a shader would look like when using Maya for lookdev with the Usd Preview Surface Shader

**Describe the solution you'd like**
It would be nice if there was a slot for an IBL texture similar to the way the Stingray shader was setup to gauge lighting and reflection

**Describe alternatives you've considered**
N/A

**Additional context**
Our Maya users like to lookdev in Maya, and having a better IBL representation would help them better match their assets to an environment or handle reflections etc...

**Comment by JGamache-autodesk** [comment]
Hi @dgovil
have you tried using an Arnold Skydome Light from the MtoA plugin to light assets with UsdPreviewSurface shading?

**Comment by dgovil** [comment]
Hi @JGamache-autodesk , sorry I missed your reply earlier.
The Skydome works pretty well for the lighting aspect of the IBL. 

However, it doesn't seem to handle reflection like Stingray PBR did though in the shader. I've updated my (in hindsight poorly worded) issue to reflect that the IBL would benefit both lighting and reflection.

**Comment by dgovil** [comment]
@JGamache-autodesk so I discovered something today, the USDPreviewSurface does actually support reflection of the aiSkyDomeLight **IF** `specularColor>0`. 

![image](https://user-images.githubusercontent.com/4443090/115310332-7e02ba00-a122-11eb-83d7-054de6534971.png)

There seems to be a related bug that this doesn't depend on specular workflow being enabled or not. As long as specular color is set to something you get reflections of the SkyDome Light as an IBL.

**Comment by dgovil** [comment]
I'm finalizing a PR internally to submit to get support for IBL reflection with the metallic workflow as well
