### ISSUE TITLE
[MAYA-101854] UFE fails to populate USD hierarchy when proxy is not parented to world

### ISSUE THREAD

**Issue by BigRoy** [Autodesk/maya-usd#94]
### Issue

UFE seems to be unable to detect the USD children hierarchies whenever the Proxy Transform is *not* parented to the world.

#### To reproduce

1. Create a proxy.
2. Group the proxy.

Note that now:

- The outliner cannot expand lower than the shape showing the 'usd hierarchy' through UFE. It will stop at the Proxy shape.
- You cannot use the UFE selection to select parts of the USD scene.
  - When trying to do so you'll see the following warning in the Output Window:

```
Warning: in getInstancedSelectionPath at line 409 of D:\dev\usd\maya-usd\lib\render\vp2RenderDelegate\proxyRenderDelegate.cpp -- UFE runtime is not updated for the USD stage. Please save scene and reopen.
```
- That using the `ufe` python library you now cannot get the children from the hierarchy as also is done [here](https://github.com/Autodesk/maya-usd/blob/e47ca0229dc60158c0a87acbbb404df9117be350/test/lib/ufe/testDeleteCmd.py#L67).

#### Known issue

_This is a **known issue**, it's described in [this code](https://github.com/Autodesk/maya-usd/blob/e47ca0229dc60158c0a87acbbb404df9117be350/test/lib/ufe/ufeTestUtils/mayaUtils.py#L75)_. However it's somewhat hidden and I'm opening this issue to track status and discuss. Plus it might help others to spot it too.

### Specs

- Windows 10
- Maya 2019.2
- refactoring_sandbox ( [`e47ca02`](https://github.com/Autodesk/maya-usd/commit/e47ca0229dc60158c0a87acbbb404df9117be350) ) 
- Pixar USD dev ( `1d08054` )

**Comment by santosg87** [comment]
Thank you for bringing this up. I can see the issue on my side as well.

Although it is a known limitation, it's definitely a workflow that would need to be investigated. 

I also logged this internally as MAYA-101854.

**Comment by santosg87** [comment]
@BigRoy I believe this is fixed in the beta builds. marking it as closed for the time being. 

if the issue persists, we can re-open it. :)
