### ISSUE TITLE
Mesh with Many Material Assignments Do Not Always Export Correctly

### ISSUE THREAD

**Issue by stevkalinowski** [Autodesk/maya-usd#941]
**Describe the bug**
When exporting a USD file with several materials assigned to the mesh, the materials assigned to the faces in the USD file are not all correct.

**Steps to reproduce**
1. Open Example Scene (I will send to our Autodesk contact)
2. Select the mesh
3. File > Export Selection
4. Set Sub-division to Polygonal Mesh
5. Import the resulting usd file back into an empty scene.  Notice some faces have lambert1 applied

**Specs (if applicable):**
 - Windows 10
 - Maya PR 120

**Comment by stevkalinowski** [comment]
![image](https://user-images.githubusercontent.com/64916304/100031710-221e4a00-2dab-11eb-9722-b06625b098c9.png)
The problematic materials has 2 connections to the shape node.  All other materials that are working correctly seem to have just 1 connection.  Maybe that's causing an issue?

**Comment by JGamache-autodesk** [comment]
That looks a lot like an issue that was fixed in pull request #860. I will have to see if that fix was in PR 120 or if it was added later.

**Comment by JGamache-autodesk** [comment]
The above fix will be available in the next PR. I the meantime we can check and make sure your scene exports correctly with the current branch.

**Comment by stevkalinowski** [comment]
That would be great, thanks.

**Comment by stevkalinowski** [comment]
Sweet, thanks for confirming.
