### ISSUE TITLE
[MAYA-111503] Nurbs curves not importing?

### ISSUE THREAD

**Issue by jmalaska** [Autodesk/maya-usd#947]
**Describe the bug**
I've tried exporting and importing Nurbs curves with a variety of options on both, but everything imports only as transform nodes -- no shapes of the curves actually import.

**Steps to reproduce**
1. Create a nurbs curve. Select it's transform and shape node. Export with default options.
2. Create a new scene
3. Import the file with default options.

**Expected behavior**
The shape of the curve should be visible.

**Comment by santosg87** [comment]
hi @jmalaska, thanks for reporting this. 

The export works as expected, but I am able to reproduce the import not showing the curves.

 You should be able to see them in your file when using a stage. ("create > Universal Scene Description (USD) > stage from file).

hope this helps! :)

**Comment by benkilgore** [comment]
I also would love to see NURBS supported correctly via USD.  And to note, when using the method described above to bring in curves via a stage, the curves are inaccessible as nodes.  Additionally the paramaterisation is lost, so they're not even drawn as they were when exported.

**Comment by santosg87** [comment]
this should be working as of mayaUSD 0.15.0 

marking this issue as closed for the time being, feel free to re-open if it is still a problem on your side @jmalaska.
