### ISSUE TITLE
[MAYA-114409] UsdSkel joint weight primvar should not use the index primvar notation

### ISSUE THREAD

**Issue by koen-v** [Autodesk/maya-usd#987]
Hello Autodesk, 

While comparing models exporting from maya with the ones I had imported, I noticed the naming of the skin weight attributes had changed.

The source file uses the usdSkel api to create the attributes:

skin_binding.CreateJointIndicesPrimvar(...)
skin_binding.CreateJointWeightsPrimvar(...)

and the result looks like this:
int[] primvars:skel:jointIndices
float[] primvars:skel:jointWeights

However in the file that came from the maya export, they look like this:
float[] primvars:skel:jointWeights
int[] primvars:skel:jointWeights:indices

The maya way seems more in line with the way the other attributes are named, I will also bring this up in the usd google group.

Thanks,
Koen

**Comment by koen-v** [comment]
I asked on the google group:
https://groups.google.com/g/usd-interest/c/St3Zg_3rGWQ

**Comment by koen-v** [comment]
Hello all,

As pointed out on the google group, the pixar api gives the correct result, and the autodesk output should be considered a bug.

The primvar:indices naming convention is for indexed primvars, ie, a compression scheme on primvars with a lot of repeating values. These indices however are not pointing into the weights array, they are pointing into the joint array, they are indices of the joints.

Thanks,
Koen

**Comment by wtelford** [comment]
Hey @santosg87 can you repro and log internally please.

**Comment by santosg87** [comment]
@koen-v we have recently re-tested this, and it seems we are using the proper naming convention now, as far as I can tell. I am closing this issue for the time being. if this is still a problem for you on recent builds of maya + mayaUsd let us know and we can investigate further.

cheers!
